### ISSUE TITLE
Consul-template crashing frequently 

### ISSUE THREAD

**Issue by rturam** [hashicorp/consul-template#1002]
We use consul-template to generate the HAproxy configuration.
### Configuration

```hcl
consul = "10.4.1.10:8500"
token = ""
retry = "10s"

log_level = "info"
```

```liquid
   ###### path based routing
{{- $services_path := "haarp/services" -}}
{{range tree $services_path -}}
  {{ if .Key | regexMatch "/team$" -}}
    {{$service_name := .Key | regexReplaceAll "/team$" "" }}
    ### {{$service_name}}
    {{- range tree (print $services_path "/" $service_name "/concerns") -}}
      {{- if .Key | regexMatch "/command$" -}}
        {{- $concern := .Key | regexReplaceAll "/command$" "" -}}
        {{- range ( key (print $services_path "/" $service_name "/concerns/" $concern "/public-endpoints") | split " " ) -}}
        {{- $host_path := ( . | split "/" ) }}
    use_backend {{$service_name}}-{{$concern}} if { req.hdr(host) -i {{index $host_path 0}} } { path /{{index $host_path 1}} }
    use_backend {{$service_name}}-{{$concern}} if { req.hdr(host) -i {{index $host_path 0}} } { path_beg /{{index $host_path 1}}/ }
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end}}

    ###### host based routing
{{- range tree $services_path -}}
  {{ if .Key | regexMatch "/team$" -}}
    {{$service_name := .Key | regexReplaceAll "/team$" "" }}
    ### {{$service_name}}
    {{- range tree (print $services_path "/" $service_name "/concerns") -}}
      {{ if .Key | regexMatch "/command$" -}}
        {{$concern := .Key | regexReplaceAll "/command$" "" }}
        {{- $public_dns := (key (print $services_path "/" $service_name "/concerns/" $concern "/public-dns")) }}
    use_backend {{$service_name}}-{{$concern}} if { req.hdr(host) -i {{$service_name}}-{{$concern}}.lb.service.paas {{$public_dns}} }
      {{- end -}}
    {{end }}
  {{end -}}
{{end -}}


{{range tree $services_path -}}
  {{ if .Key | regexMatch "/team$" -}}
    {{$service_name := .Key | regexReplaceAll "/team$" "" }}

#### {{$service_name}} backends
    {{- range tree (print $services_path "/" $service_name "/concerns") -}}
      {{ if .Key | regexMatch "/command$" -}}
        {{$concern := .Key | regexReplaceAll "/command$" "" }}
backend {{$service_name}}-{{$concern}}
    {{- $healthEndpoint := key (print $services_path "/" $service_name "/concerns/" $concern "/health-path") }}
    option httpchk  GET {{ $healthEndpoint | regexReplaceAll "^:\\$PORT[01]" ""}}
        {{$metrics_path := (key (print $services_path "/" $service_name "/concerns/" $concern "/metrics-path"))}}
        {{- if $metrics_path}}
    http-request deny if { path -i {{$metrics_path | regexReplaceAll "^:\\$PORT[01]" ""}} }
        {{end -}}
        {{range $cnt, $service := service (print $concern "." $service_name)}}
    server {{(printf "%s%s%s%s%04d" $concern "-" $service_name "-" $cnt)}} {{$service.Address}}:{{$service.Port}} check
{{- if $healthEndpoint | regexMatch "^:\\$PORT1.*" -}}
  {{- $healthServiceID := $service.ID | regexReplaceAll ":8080$" ":8081" -}}
  {{- range $_, $healthService := service (print $concern "." $service_name "-private") -}}
    {{- if eq $healthService.ID  $healthServiceID }} port {{ $healthService.Port }}{{ end -}}
  {{- end -}}
{{- end -}}
        {{- end}}
      {{end -}}
    {{end -}}
  {{end -}}
{{end}}
```

### Command

```shell
/usr/local/bin/consul watch -http-addr=127.0.0.1:8500 -type=event -name=haarp /usr/local/bin/consul-template -once -wait=2000ms -consul=127.0.0.1:8500 -template="/etc/consul-template/haproxy.cfg.ctmpl:/etc/haproxy/haproxy.cfg:systemctl reload haproxy"
```

### Debug output

https://gist.github.com/rturam/cfa5ef89946e848d07548bb1bb832bec

### Expected behavior

It should not have crashed

### Actual behavior

Crashing frequesntly on one machine but not on other 2 machine.

### Steps to reproduce

1. Just run with given command.

**Comment by sethvargo** [comment]
Hi @rturam 

You are running CT version 0.15.0. The latest version is 0.19.1 and there have been significant changes, bug fixes, and performance improvements in later versions. 

The error appears to be that you're out of file descriptors. It's possible that you're making a lot of external requests to Consul and have a low fd limit for the user this process is running ask.

The later versions support automatic retrying in failure scenarios, which might help with this.

**Comment by rturam** [comment]
Thanks for quick reply, I will try 0.19.1 and let you know tomorrow.

**Comment by rturam** [comment]
@sethvargo I am just trying the 0.19.1 version and it is getting stuck in the consul template generation process.

When I do ctrl + c, I got error code: 130 in console along with other general logs.

Command:
consul-template -once -consul-addr=consul1:8500 -log-level=ERR -template="${PWD}/haproxy.cfg.ctmpl:${PWD}/haproxy.cfg"
./haproxy-reload

consul watch -http-addr=consul1:8500 -type=event -name=xxx \
  consul-template -once -wait=500ms -consul-addr=consul1:8500 -log-level=ERR -template="${PWD}/haproxy.cfg.ctmpl:${PWD}/haproxy.cfg:${PWD}/haproxy-reload"

Is something in command is changed/missing?

**Comment by sethvargo** [comment]
Hi @rturam 

130 [means](http://www.tldp.org/LDP/abs/html/exitcodes.html) "Script terminated by Control-C", so that makes sense for the exit code. 

Can you share the debug logs? run with `-log-level=TRACE` please

**Comment by rturam** [comment]
@sethvargo Please find the logs with TRACE.
https://gist.github.com/rturam/f0b17d0bf8d01d98139a9101ff868909

For a small set of test values in consul, it is running for 15+ minutes. And it is still running I have just posted the 13 minutes run in Gist.

**Comment by sethvargo** [comment]
Can I see your CT configuration file? It's weird that you're only blocking for a few seconds on those keys.

**Comment by rturam** [comment]
consul.json
------------

{
  "ports": {
    "dns": 53
  }
}

**Comment by rturam** [comment]
@sethvargo Do you got any chance to look into it further?

**Comment by sethvargo** [comment]
Hi @rturam 

I have not been able to reproduce this unfortunately. I see a few things worth noting.

1. You should always query the local consul agent. That will help reduce network traffic because it'll multiplex to the server, and you also don't have to discovery your service discovery.

1. What version of Consul are you running and what is the topology?

1. Does this reproduce when you run Consul Template as its own service? I'm not sure I understand the use of `consul watch` combined with `consul-template` in this instance.

1. In the new CT output you sent, there's no errors (you can search for `[ERR` in the output.

1. The output is waiting for a bunch of keys to become available. You can see this as "returned nil" in the output. Consul Template won't render the template or run the command until all keys have received data at least once.

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/consul-template/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
