### ISSUE TITLE
Support multiple templates for one service

### ISSUE THREAD

**Issue by freeseacher** [hashicorp/consul-template#1006]
I have a service that have to be configured with about 20 config files. 
All of them have to be rendered before service got reload command. 

Please add some kind of dependent templates. Or may be
```
template { 
  multiple {
  	template {
  	  source  = "source.1"
  	  destination = "destination.1"
  	}
  	template {
  	  source  = "source.2"
  	  destination = "destination.2"
  	}
  command = "service reload"
  command_timeout = "60s"
  perms = 0644
  backup = false
  wait {
    min = "2s"
    max = "60s"
  }
}
```

Currently only one solution can be applied afaik that is to set multiple templates with dummy reload command and one with actual reload. That is pretty buggy solution

**Comment by sethvargo** [comment]
Hi @freeseacher 

You can use `exec` mode for this: https://github.com/hashicorp/consul-template#exec-mode. Exec mode waits until all templates have been rendered at least once before spawning the command.

**Comment by OsoianMarcel** [comment]
@sethvargo 
Exec Mode: **"If the child process dies, the Consul Template process will also die"**

In this case exec mode does not help, because service reload is a process that will die, then consul-template will also die.

**Comment by OsoianMarcel** [comment]
@sethvargo 
@freeseacher 

I was wrong, I did multiple tests, and the consul-template is smart enough to not run same command multiple times.

So, if you have 3 different templates with command "echo 1", then if you'll check consule-template logs, you will see that only one echo was executed.

Test #1
template1: echo 1
template2: echo 1
template3: echo 1
result: 1 (executed only one time)

Test #2
template1: echo 1
template2: echo 1
template3: echo 2
result: 1 2 (echo 1 was executed only one time)
