### ISSUE TITLE
command does not run after template being rendered successfully 

### ISSUE THREAD

**Issue by ritxos** [hashicorp/consul-template#1015]
### Consul Template version
consul-template v0.19.3 (ebf2d3d)

### Configuration

```hcl
template {
  source = "/tmp/dummy.cfg.ctmpl"
  destination = "/tmp/dummy.cfg"
  command = "bash /tmp/xyz.sh"

}
```

```liquid
{{range services}}
   upstream {{.Name}} {
   {{range service .Name}}
       server {{.Address}}:{{.Port}}
       {{else}}server 127.0.0.1:65535;
   {{end}}
   }
{{end}}
```

### Command

```shell
/usr/local/bin/consul-template -config /etc/consul-template.d -log-level=trace
```
command used in template can be identified in trace level logs in the below gist (permissions double checked and running such command returns 0 exit )

### Debug output

https://gist.github.com/ritxos/7e9b9491bee28aa4cb0038cacf59fef3

### Expected behavior

command should run after templates are rendered successfully 

### Actual behavior

I don't see any traces of command being run after template rendering.

### Steps to reproduce

1. keep a simple bash script in /tmp that returns 0
2. call this bash script from consul-template ( bash your_script.sh)

**Comment by sethvargo** [comment]
Hi @ritxos 

Does the file already exist on disk with the correct contents?

**Comment by ritxos** [comment]
@sethvargo apologies for a delayed response
-- Yes, File exists on the disk with appropriate permissions and contents.

**Comment by sethvargo** [comment]
Hi @ritxos 

That's why the command is not running. If the file already exists on disk with the correct perms, contents, etc, the command does not run. The command runs on template _change_

**Comment by ritxos** [comment]
Hi @sethvargo 

I certainly understand that it has a watch and only triggers command when there is a configuration/service layer change . I might have misunderstood you, I thought we were talking about bash script(file with appropriate permissions). When I've tried running it -- I've deleted the rendered template in previous run

Also attached logs in the Gist say that templates have been  rendered during the run -
**2017/09/22 09:48:59.114770 [DEBUG] (runner) rendering "/tmp/dummy.cfg.ctmpl" => "/tmp/dummy.cfg"**
2017/09/22 09:48:59.114851 [DEBUG] (runner) diffing and updating dependencies
2017/09/22 09:48:59.114881 [DEBUG] (runner) catalog.services is still needed
2017/09/22 09:48:59.114902 [DEBUG] (runner) health.service(consul|passing) is still needed
2017/09/22 09:48:59.114912 [DEBUG] (runner) health.service(service-x|passing) is still needed
2017/09/22 09:48:59.114931 [DEBUG] (runner) watching 3 dependencies
**2017/09/22 09:48:59.114939 [DEBUG] (runner) all templates rendered**

However I've tried same steps with **consul-template 0.18.0** and it worked fine.

**Comment by sethvargo** [comment]
Hi @ritxos 

The log output changed slightly between 0.18 and 0.19. If you run with `LOG_LEVEL=trace`, you should see a message indicating if the file was actually rendered or if it would have been rendered (but was not due to the contents already existing).

Are there other files in that config.d directory?

**Comment by ritxos** [comment]
@sethvargo yes there are two files -- 
-- one named default.json having content 
{}
-- and the other named dummy with following content -
template {
  source = "/tmp/dummy.cfg.ctmpl"
  destination = "/tmp/dummy.cfg"
  command = "bash /tmp/xyz.sh"

}

**Comment by gmr** [comment]
Hey, just throwing what I'm seeing in as well. I was previously running v0.10.0. 

With v0.10.0, after a template is re-rendered,  the command specified is run, which restarts my application that reads the rendered config file.

After upgrading to v0.19.3, the command specified is not run anymore, after rendering.
```
2017/09/26 14:35:19.099423 [DEBUG] (runner) received template "cc75f94e7e2db96ad049069a7254663a" from quiescence
2017/09/26 14:35:19.099533 [INFO] (runner) initiating run
2017/09/26 14:35:19.099549 [DEBUG] (runner) checking template cc75f94e7e2db96ad049069a7254663a
2017/09/26 14:35:19.448733 [INFO] (dedup) updated de-duplicate data 'consul-template/dedup/cc75f94e7e2db96ad049069a7254663a/data'
2017/09/26 14:35:19.449161 [DEBUG] (runner) rendering "/etc/consul-templates/rejected.yaml.ctmpl" => "/etc/rejected.yaml"
2017/09/26 14:35:19.449663 [DEBUG] (runner) diffing and updating dependencies
...
2017/09/26 14:35:19.493693 [DEBUG] (runner) enabling global quiescence for "cc75f94e7e2db96ad049069a7254663a"
2017/09/26 14:35:19.493848 [WARN] (runner) watching 267 dependencies - watching this many dependencies could DDoS your consul cluster
2017/09/26 14:35:19.494014 [DEBUG] (runner) all templates rendered
```

**Comment by sethvargo** [comment]
Hmm weird because we have test coverage for this exact use case. I'm going to need some time to dig into this more (I'm very busy this week with other work). Hopefully I can get to this next week. In the meantime, I recommend using 0.19.0 if you can. Sorry!

**Comment by gmr** [comment]
It appears this is an issue in:

- 0.19.0
- 0.18.5
- 0.18.0

But I think I figured out the issue is a change in the behavior with complex commands. 

Currently, I am fixing ownership and file permissions with the command so it looks like:

```hcl
template {
    source = "/etc/consul-templates/rejected.yaml.ctmpl"
    destination = "/etc/rejected.yaml"
    command = "chgrp rejected /etc/rejected.yaml && chmod 0640 /etc/rejected.yaml && service rejected restart"
}
```
While this works with older consul-template versions ( `0.10.0` in production), it does not work with `0.18.0` or higher (at least).

Changing the config to the following works:

```hcl
template {
    source = "/etc/consul-templates/rejected.yaml.ctmpl"
    destination = "/etc/rejected.yaml"
    perms = 0644
    command = "service rejected restart"
}
```

Ideally, to make the behavior work, a new version would support an owner and group setting for template for filesystem permissions.

**Comment by sethvargo** [comment]
Previously we spawned the given command as `/bin/sh`. We changed that to just execute the command directly. Functions like `&&` and `||` are functions of a _shell_, not a command. You can get around this by wrapping you're entire command in `/bin/sh -c "..."` or move your command to an external file with a shebang `#!/usr/bin/env sh`.

As for setting owner/group - at present, there's no cross-platform way to accomplish this in Golang without cgo. If and when that functionality exists, we can definitely update support.
