### ISSUE TITLE
Info on running the XC targets and building docker container

### ISSUE THREAD

**Issue by tanner-bruce** [hashicorp/consul-template#1022]
I am receiving this error when trying to build the XC targets when I'm trying to build the docker container.
```
-->        linux/amd64: /home/tanner/go/src/github.com/hashicorp/consul-template
can't load package: package home/tanner/go/src/github.com/hashicorp/consul-template: no buildable Go source files in /go/src/home/tanner/go/src/github.com/hashicorp/consul-template```

**Comment by tanner-bruce** [comment]
Changing the make-xc-target macro to the following allows it to build. It seems like using ${PROJECT} as the shared volume directory is incorrect since it also includes `/home/tanner/` as part of the path.

```make
define make-xc-target
  $1/$2:
  ifneq (,$(findstring ${1}/${2},$(XC_EXCLUDE)))
		@printf "%s%20s %s\n" "-->" "${1}/${2}:" "${PROJECT} (excluded)"
  else
		@printf "%s%20s %s\n" "-->" "${1}/${2}:" "${PROJECT}"
		@printf "${PROJECT} ${CURRENT_DIR}"
		@docker run \
			--interactive \
			--rm \
			--dns="8.8.8.8" \
			--volume="${CURRENT_DIR}:/go/src/github.com/hashicorp/consul-template" \
			--workdir="/go/src/github.com/hashicorp/consul-template" \
			"golang:1.8" \
			env \
				CGO_ENABLED="0" \
				GOOS="${1}" \
				GOARCH="${2}" \
				go build \
				  -a \
					-o="pkg/${1}_${2}/${NAME}${3}" \
					-ldflags "${LD_FLAGS}" \
					-tags "${GOTAGS}"
  endif
  .PHONY: $1/$2

  $1:: $1/$2
  .PHONY: $1

  build:: $1/$2
  .PHONY: build
endef
```

**Comment by sethvargo** [comment]
Hi @tanner-bruce 

Thank you for opening an issue. Do you have a `$GOPATH` set?  `PROJECT` is defined as:

```
PROJECT := $(CURRENT_DIR:$(GOPATH)/src/%=%)
```

Which strips out the GOPATH (which should be `/home/tanner/go` in your example), leaving you with /src/github.com/hashicorp/consul-template, and then src is stripped leaving you with github.com/hashicorp/consul-template.

If you don't have a `$GOPATH` set, it defaults to `$(HOME)/go`, which should still be /home/tanner/go in your case.
