### ISSUE TITLE
Crashes due to extra : in template config

### ISSUE THREAD

**Issue by tanner-bruce** [hashicorp/consul-template#1023]
### Consul Template version

0.19.3

### Configuration

Empty

### Command

```shell
consul-template -template "in.tmpl:out.tmpl:curl -XPOST http://prometheus:9090/-/reload"
```

### Debug output

Fails here
https://github.com/hashicorp/consul-template/blob/master/config/template.go#L392

### Expected behavior

The below command should be executed
```shell
curl -XPOST http://prometheus:9090/-/reload
````

### Actual behavior
Crashes due to extra `:` in the template line.

I would propose changing https://github.com/hashicorp/consul-template/blob/master/config/template.go#L392 from
```go
	parts := configTemplateRe.FindAllString(s, -1)
```

to

```go
	parts := strings.SplitN(s, ":", 3)
```

**Comment by sethvargo** [comment]
https://github.com/hashicorp/consul-template/pull/1026
