### ISSUE TITLE
RFC: Indent template helper

### ISSUE THREAD

**Issue by tanner-bruce** [hashicorp/consul-template#1024]
I'd like to add an `indent` function to consul-template, along the lines of

```liquid
{{ "foo" | indent 2 }}
```

It can be somewhat accomplished via 
```liquid
{{ "foo" | regexReplaceAll "^|\n" "\n<number of spaces to indent>" }}
```

however this adds extra spacing at the start (`{{-` fixes that), and is pretty ugly to write.

Of course, it can also be accomplished by a `plugin`, but that is also not very user-friendly.

**Comment by sethvargo** [comment]
What's the use case here?

**Comment by tanner-bruce** [comment]
We have some keys that contain multiline blocks of YAML code. When we are including these blocks in the template, occasionally these blocks need to be at a different level of indentation. 

If there is a better solution that I don't know about, I'm all ears :)

**Comment by sethvargo** [comment]
The yaml help just dumps from `yaml.Marshal`, so it'd be impossible to get a real indentation, especially if the yaml itself contains newline characters, etc

**Comment by tanner-bruce** [comment]
The YAML is besides the point, it could be any arbitrary block that I want to indent. In this case, I am not even using the `toYAML` helper, because it doesn't fit quite right with what we are doing.

**Comment by sethvargo** [comment]
Okay, but I think you're missing my point. Given a key in consul like this:

```
This is
my value
```

indent(2) could either return:

```
  This is
my value
```

or

```
  This is 
  my value
```

especially when you consider `\r\n` vs `\n`, etc.

**Comment by tanner-bruce** [comment]
What I am looking for is the second one - all I want is a way to indent my multiline block of code from a Consul key. If `indent(2)` is not the way to do it, and writing the `regexReplaceAll` feels hacky, what would you suggest?

**Comment by tanner-bruce** [comment]
> especially when you consider \r\n vs \n, etc.

I do agree with this, but it's pretty trivial to deal with in code. The contract for indent(#) would simply be that it will split a string on \n or \r\n, insert the number of spaces at the start and combine the string.

Since 
```
  This is
my value
```
is trivially accomplished by adding 2 spaces before the opening delimiter, I would disagree that this is a problem.

**Comment by sethvargo** [comment]
https://github.com/hashicorp/consul-template/pull/1034
