### ISSUE TITLE
Take CT version into account in de-duplication

### ISSUE THREAD

**Issue by thedebugger** [hashicorp/consul-template#1025]
I want to reopen https://github.com/hashicorp/consul-template/issues/920 because we see the issue in our environment. The issue makes upgrade non-safe and deleting keys manually is not a good option too. So consul-template should handle this user case better. Maybe dedup template/version so that it doesn't conflict with other versions of consul-template? Our upgrade path looks like v0.19.3, v0.16.0, other old version. Let me know if you need more details.

**Comment by sethvargo** [comment]
I've updated the title. 

TL;DR - globbing can change between versions or if you are running different versions of CT, therefore we need to take the version number into account during deduplication hashing.

**Comment by thedebugger** [comment]
@sethvargo also, do you know how long do consul-templete persists "consul-template/dedup/*" keys? I was under the impression that if the leader of template dies, they are recreated. But we have to delete it manually to fix the problem. So i don't understand how it all works?
