### ISSUE TITLE
~<NEAR> syntax is broken

### ISSUE THREAD

**Issue by white-hat** [hashicorp/consul-template#1027]
According to documentation https://github.com/hashicorp/consul-template#service
when `~<NEAR>` is specified, results should be ordered by latency to `<NEAR>` host, instead results are always returned in alphabetical order, so `~<NEAR>` is ignored.
I ran `tcpdump` and captured a proper request to consul server, so IMHO the issue is in the renderer, which reorders items in alphabetical order even when `~<NEAR>` is used

### Consul Template version

consul-template v0.19.3 (ebf2d3d)

### Configuration

no configuration 

```liquid
{{ range service "nginx-offload-exporter~hss100|passing" }}
{{ .Node }}{{ end }}
```

### Command

```shell
/bin/consul-template  -once -consul-addr=localhost:8500 -template="template:result"
```

### Debug output
https://gist.github.com/white-hat/c252c760630a15ecdd5192a526cdaa56

### Expected behavior

result should be ordered by latency

### Actual behavior

result is always ordered alphabetically 

### Steps to reproduce

1. query services catalog using `~<near>` syntax
2. result will be always ordered alphabetically
3. query same services using API
4. result will be ordered by latency

**Comment by sethvargo** [comment]
Yea, I think that's a bug. I think `passing` automatically sorts.

**Comment by white-hat** [comment]
@sethvargo I removed `|passing` from the template, but results are the same
```bash
/ # cat template
{{ range service "nginx-offload-exporter~hss100" }}
{{ .Node }}{{ end }}
/ # /bin/consul-template -once -consul-addr=localhost:8500 -template="template:result"
/ # head result
sat-ams-prod-1-0
sat-ams-prod-1-1
sat-ams-prod-1-2
sat-ams-prod-1-3
sat-ams-prod-1-4
sat-ams-prod-1-5
```
