### ISSUE TITLE
Retries explode after about an hour

### ISSUE THREAD

**Issue by ibusse** [hashicorp/consul-template#1028]
### Consul Template version

consul-template v0.18.5 (9902dd5)

### Configuration

```hcl
consul {
    address = "127.0.0.1:8500"
    retry {
        enabled = true
        attempts = -1
        backoff = "250ms"
        max_backoff = "1m"
    }
}

log_level = "INFO"

syslog {
    enabled = true
    facility = "LOCAL6"
}

max_stale = "10m"

wait = "5s:10s"
```

```liquid
listen foo
    bind 192.168.254.1:8000
    # From consul: healthy nodes for service foo-api@dc1 {{range service "foo-api@dc1" }}
    server {{.Node}} {{.Address}} check inter 2000 rise 2 fall 5{{end}}
```

### Command

```shell
consul-template -config=$confdir &>> $logfile &
```

### Debug output
```
2017/09/20 06:36:28.572273 [WARN] (view) health.service(foo-api@dc1|passing): Unexpected response code: 500 (rpc error: EOF) (retry attempt 1 after "250ms")
2017/09/20 06:36:28.824683 [WARN] (view) health.service(foo-api@dc1|passing): Unexpected response code: 500 (rpc error: failed to get conn: rpc error: lead thread didn't get connection)
 (retry attempt 2 after "500ms")
...
2017/09/20 08:30:12.057318 [WARN] (view) health.service(foo-api@dc1|passing): Get http://127.0.0.1:8500/v1/health/service/foo-api?dc=dc1&passing=1&stale=&wait=60000ms: dial tcp 127.0.0
.1:8500: getsockopt: connection refused (retry attempt 57 after "-2562047h47m16.854775808s")
2017/09/20 08:30:12.057982 [WARN] (view) health.service(foo-api@dc1|passing): Get http://127.0.0.1:8500/v1/health/service/foo-api?dc=dc1&passing=1&stale=&wait=60000ms: dial tcp 127.0.0
.1:8500: getsockopt: connection refused (retry attempt 58 after "0s")
```

### Expected behavior

consul-template proceeds to retry with max_backoff

### Actual behavior

retry attempts produce an overflow that results in nearly immediate retries

### Steps to reproduce

1. Start consul-template as a service
2. Stop the corresponding consul server
3. Wait for about 58 retries, then there will be an overflow in calculation and immediate retries resulting in log file filling up the disk

### References

none

**Comment by sethvargo** [comment]
Hi @ibusse 

Can you please try upgrading to 0.19.x? We fixed some retry bugs in the later releases.

**Comment by ibusse** [comment]
Ok, I will give it a try.


Am 13.10.2017 15:24 schrieb "Seth Vargo" <notifications@github.com>:

Hi @ibusse <https://github.com/ibusse>

Can you please try upgrading to 0.19.x? We fixed some retry bugs in the
later releases.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hashicorp/consul-template/issues/1028#issuecomment-336451257>,
or mute the thread

**Comment by ibusse** [comment]
Same behavior.

Checked the code. I think in retry.go the pow expression produces an
overflow that results in a negative value. Then true and the negative
backoff time are returned.

Am 13.10.2017 15:26 schrieb "Ingo Busse" <ingo.busse@gmail.com>:

**Comment by ibusse** [comment]
Using max_backoff 1s you can easily produce a test case that misbehaves after a minute.

**Comment by sethvargo** [comment]
https://github.com/hashicorp/consul-template/pull/1031
