### ISSUE TITLE
Docker Hub full description

### ISSUE THREAD

**Issue by martinssipenko** [hashicorp/consul-template#1030]
The [full description in docker hub](https://hub.docker.com/r/hashicorp/consul-template/) has wrong tags listed. The `alpine-0.19.0` tag does not exist and should be changed to `0.19.0-alpine`.

I could not find a file this git repository that lists the available tags. In case such file exists please point me to it and I'll send a pull request.

**Comment by sethvargo** [comment]
Fixed
