### ISSUE TITLE
Enhancement: add config option to disable recursive mkdir

### ISSUE THREAD

**Issue by hex2a** [hashicorp/consul-template#1033]
Currently, if the parent directories for a file are missing, they are created recursively by consul-template.
This may cause issues with ownership,permissions,...

Please provide a config option (preferably per-template) to disable this behaviour and return an error instead (if the directory does not exist).

https://github.com/hashicorp/consul-template/blob/710c4a24ea413541a7d8cf68e755f8ba9eecb32c/manager/renderer.go#L95

**Comment by sts** [comment]
+1
