### ISSUE TITLE
[enhancement request] template config file does not render destination path

### ISSUE THREAD

**Issue by danipopiw** [hashicorp/consul-template#1044]
### Consul Template version

v0.19.4 (68b1da2)

### Configuration

```hcl
template {
  destination="{{ printf \"config/exim/%s-%s.pem\" (key \"config/exim/company-dkim-hostname\") (key \"config/exim/company-selector\") }}"
  contents="{{ printf \"config/exim/%s-%s.pem\" (key \"config/exim/company-dkim-hostname\") (key \"config/exim/company-selector\") | key }}"
  error_on_missing_key = true
}
```

### Command

```text
$ consul-template -consul-addr=$CONSUL_URL -config /tmp/keys.tpl -log-level=trace
```

### Debug output

I already checked the logs and it looks like destination is not rendered:
https://gist.github.com/danipopiw/eea5156322306c719549fa461625f28a

### Expected behavior

Destination dynamic values are not rendered, and also can be seen from log file

### Actual behavior

In my opinion destination would be nice to be rendered, as I have a lot of situations where based on several consul keys I could create my destination, and that would be really nice when using multiple dynamic files, the content renders very well as expected.

### Steps to reproduce

1. Create the template config file in `/tmp/keys.tpl`
2. Run the consul-template command line and use `-config /tmp/keys.tpl`

**Comment by sethvargo** [comment]
Hi @danipopiw 

Thank you for opening an issue, and thank you for using Consul Template. As I understand it, you want the destination path to be interpolated and rendered as a template. Unfortunately this is not possible for a number of reasons, and would require a very large refactor of Consul Template to accomplish. Additionally, it could lead to a denial of service attack, as a skilled attacker could simply keep renaming those keys in Consul and fill the filesystem with duplicate files.

Instead, I would recommend writing the file to a random destination, and then using the arbitrary shell command to move and rename the file as needed. Thanks and have a great day!

**Comment by danipopiw** [comment]
thank you very much
