### ISSUE TITLE
Running Multiple Commands After Rendering

### ISSUE THREAD

**Issue by orarnon** [hashicorp/consul-template#1046]
Hi,

After upgrading to CT 0.19.4 (from CT 0.10.0), I'm not able to perform 2 commands upon rendering as I did before. Is there any solution?
We have one CT service running which gets a directory of config files. 
Relevant section:
```command = "/usr/bin/php -l /tmp/env.development.inc && /bin/mv /tmp/env.development.inc /ephemeral/php/var/config/env/env.development.inc"```

**Comment by piavka** [comment]
@orarnon  see the breaking changes in 0.18.0 https://github.com/hashicorp/consul-template/blob/v0.19.4/CHANGELOG.md#v0180-january-20-2017

**Comment by sethvargo** [comment]
Hi @orarnon 

Thank you for opening an issue. As @piavka pointed out, this was a documented breaking change between those versions. Please review the changelog for more information and recommended workarounds. Thanks!
