### ISSUE TITLE
Get PKI CRL from vault (Non JSON response)

### ISSUE THREAD

**Issue by srcnix** [hashicorp/consul-template#1048]
Is there functionality that supports getting the PKI CRL from vault? Currently I have the following template:

```
{{ secret "pki/crl/pem" }}
{{ . }}
{{ end }}
```

However I am receiving the following error:

```
2017/11/25 12:03:11.707856 [WARN] (view) vault.read(pki/crl/pem): invalid character '-' in numeric literal (retry attempt 3 after "1s")
```
Which makes me believe only JSON responses are allowed. The CRL endpoint returns either binary (without /pem) or a body of the PEM contents.

**Comment by sethvargo** [comment]
Hi there,

Consul Template only works with the JSON responses in Vault at this time.

**Comment by jefferai** [comment]
You can use https://www.vaultproject.io/api/secret/pki/index.html#read-certificate to get it

**Comment by sethvargo** [comment]
Hey @srcnix 

As @jefferai just pointed out - you can use `/pki/cert/crl` and it should work!

**Comment by srcnix** [comment]
Thanks @jefferai  and @sethvargo, I missed that!
