### ISSUE TITLE
trimSpace function does not work

### ISSUE THREAD

**Issue by dmitryint** [hashicorp/consul-template#1050]
### Consul Template version

```
consul-template v0.19.4 (68b1da2)
```

### Template

```liquid
{{ range ls "root"}}{{.Key | trimSpace }}={{.Value | trimSpace }}
{{end}}
```

### Command

```shell
/usr/local/bin/consul-template -log-level=WARN -consul-addr=consul:8500 -template=/templates/common.ctpl:/out/common.txt
```

### Expected behavior

my_key=["value1","value2","value3"]

### Actual behavior

```
my_key=[
    "value1",
    "value2",
    "value3"
]
```

### Steps to reproduce

1. put this value into the Consul:

```
[
    "value1",
    "value2",
    "value3"
]
```

**Comment by sethvargo** [comment]
Hi @dmitryint 

You need to move the `{{ end }}` up to the top line. You're telling it to insert the newline character:

```
{{ range ls "root" }}{{ .Key | trimSpace }}={{ .Value | trimSpace }}{{ end }}
```

You're also probably better off just using `toJSON` in this case on the result of the `ls` - that will produce the same output and will be less fragile.
