### ISSUE TITLE
env blacklist in cli?

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/consul-template#1051]
The docs say that all options in the config are supported in CLI, but in 0.19.4 I don't see any option in the cli help for the env blacklist/whitelist settings?

**Comment by pearkes** [comment]
Unfortunately I think the docs are incorrect here for the env block of exec.

Following the pattern here:

https://github.com/hashicorp/consul-template/blob/master/cli.go#L669-L686

We'd probably add additional commands for the env configuration options, following the existing pattern, such as:

```
-exec-env-pristine
-exec-env-custom
-exec-env-whitelist
-exec-env-blacklist
```
