### ISSUE TITLE
debug mode isn't helpful with missing keys

### ISSUE THREAD

**Issue by spanktar** [hashicorp/consul-template#1052]
### Consul Template version

0.8.5

### Debug output

https://gist.github.com/spanktar/f71220e4d26bcc1201d54a602a5f3bad

### Expected behavior

A missing key should be shown in the output.

### Actual behavior

In DEBUG mode, when a key isn't found it should say explicitly which key is missing. It says how many, but not what. Then it shows all the dependencies, which is nice, but not what's needed.

2017/12/02 08:08:01.081283 [DEBUG] (runner) missing data for 2 dependencies

Which ones?!

### Steps to reproduce

1. Make a consul template with multiple dependencies, but then remove one
2. Run consul-template in debug mode
3. Look at the output

**Comment by sethvargo** [comment]
Hi @spanktar 

You are running a _very_ old version of Consul Template. The latest version os 0.19.0. With that mode, you can run with `-log-level=trace` and it will list the missing deps. Thanks!

**Comment by spanktar** [comment]
Oh man, sorry for the noise, I hadn't checked on that!
