### ISSUE TITLE
Endless De-Dup Triggers

### ISSUE THREAD

**Issue by orarnon** [hashicorp/consul-template#1053]
Hi,

After upgrading to CT 0.19.4 with dedup enabled, I get endless: "watcher triggered by de-duplication manager" which results in endless rendering of a config file.

I should add that before dedup, this file was not rendered in an endless loop.

> 2017/12/06 08:49:17.718726 [INFO] (dedup) loading 17 dependencies from 'php/production/dedup/8aaa9c736ea7e2932860b9aa15ba7266/data'
> 2017/12/06 08:49:17.718784 [INFO] (dedup) listing data for template hash 8aaa9c736ea7e2932860b9aa15ba7266
> 2017/12/06 08:49:17.718901 [INFO] (runner) watcher triggered by de-duplication manager
> 2017/12/06 08:49:17.718916 [INFO] (runner) initiating run
> 2017/12/06 08:49:17.722637 [INFO] (runner) rendered "env.production.inc.ctmpl" => "/tmp/env.production.inc"
> 2017/12/06 08:49:17.725396 [INFO] (runner) executing command "/bin/bash -c '/usr/bin/php -l /tmp/env.production.inc && mv /tmp/env.production.inc env.production.inc'" from "/etc/consul-template/template.d/env.production.inc.ctmpl" => "/tmp/env.production.inc"
> 2017/12/06 08:49:17.725474 [INFO] (child) spawning: /bin/bash -c /usr/bin/php -l /tmp/env.production.inc && mv /tmp/env.production.inc /env.production.inc
> No syntax errors detected in /tmp/env.production.inc

**Comment by sethvargo** [comment]
Hi @orarnon 

Can you please complete the issue template that appears when you make a new issue? It asks for your template, debug logs, and other helpful information that helps us solve your issue the fastest. Thanks!
