### ISSUE TITLE
Support -config-dir option

### ISSUE THREAD

**Issue by Perlovka** [hashicorp/consul-template#1054]
Hi,

Consul agent have an -config-dir option (https://www.consul.io/docs/agent/options.html#_config_dir), that allows to load config files from directory by mask, so any other files (like *.rpmsave etc.) are not involved.

It would be nice to support such a way in consul-template as well.

For example:

```
/etc/consul/template.d/
    consul-template.conf
    template1.conf
    template1.ctmpl
    template2.conf
    template2.ctmpl
```

And then one can start consul-template from unit/service file like this (assuming -config-dir will load files by mask `*.conf/*.json` etc.):
```
consul-template -config-dir /etc/consul/template.d/
```
or (assuming -conf option will accept wildcard):
```
consul-template -config /etc/consul/template.d/*.conf
```

In such a way adding new templates/configs wil be way more easy.

### Consul Template version

consul-template v0.19.4 (68b1da2)

**Comment by sethvargo** [comment]
Hi @Perlovka 

This is already the behavior. Unlike Consul, Consul Template detects if the given path is a file or directory. If it's a directory, _all_ files in that directory are loaded, regardless of their file extension. I would recommend putting all your conf in `/etc/consul-template.d/conf`, etc.

**Comment by Perlovka** [comment]
This is exaclty a problem, that ALL files are considered as configs. I want to be able to put templates in the same directory. Also, I'm installing consul-template with rpm, so sometimes there will be files like .rpmsave, .rpmnew etc. Then consul-template will fail on reload/restart.
