### ISSUE TITLE
Issue with Rendering haproxy.cfg

### ISSUE THREAD

**Issue by jerrin92** [hashicorp/consul-template#1056]
### Consul Template version

v0.19.4 (68b1da2)

```liquid
frontend http-in
 bind *:80
 default_backend www

backend www{{range service "Portal"}}
 server {{.ID}} {{.Address}}:{{.Port}}{{end}}
```

### Command

```shell
consul-template -consul-addr 10.10.10.8 -template /home/consul/haproxy.ctmpl:/etc/haproxy/haproxy.cfg -log-level=trace
```

### Debug output

```text
2017/12/06 18:01:26.113553 [DEBUG] (runner) diffing and updating dependencies
2017/12/06 18:01:26.113560 [DEBUG] (runner) watching 1 dependencies
2017/12/06 18:01:26.113606 [TRACE] (view) health.service(Portal|passing) starting fetch
2017/12/06 18:01:26.113631 [TRACE] health.service(Portal|passing): GET /v1/health/service/Portal?stale=true&wait=1m0s
2017/12/06 18:01:26.114205 [WARN] (view) health.service(Portal|passing): Get http://10.10.10.8/v1/health/service/Portal?passing=1&stale=&wait=60000ms: dial tcp 10.10.10.8:80: getsockopt: connection refused (retry attempt 1 after "250ms")
2017/12/06 18:01:26.364420 [TRACE] (view) health.service(Portal|passing) starting fetch
2017/12/06 18:01:26.364459 [TRACE] health.service(Portal|passing): GET /v1/health/service/Portal?stale=true&wait=1m0s
2017/12/06 18:01:26.364912 [WARN] (view) health.service(Portal|passing): Get http://10.10.10.8/v1/health/service/Portal?passing=1&stale=&wait=60000ms: dial tcp 10.10.10.8:80: getsockopt: connection refused (retry attempt 2 after "500ms"
```

### Expected behavior

After running the statement, it should have created the haproxy configuration file and started the service

### Actual behavior

What actually happened?
It throws the above error and the consul-template is unable to render the haproxy configuration file

### Steps to reproduce

1. Install haproxy and use the above the configuration file.
2. Set up 3 consul servers
2. Configure a portal server that listens on 8000

**Comment by sethvargo** [comment]
Hi @jerrin92 

Is 10.10.10.8 accessible from where you're running? Usually consul runs on port 8500, so that would be 10.10.10.8:8500. Additionally, you should always query the _local_ consul agent, not the server directly, in which case it would be 127.0.0.1:8500.

**Comment by jerrin92** [comment]
Hi @sethvargo 

Thank you for the update. Yes, it works now!

**Comment by slackpad** [comment]
Thanks for the update!
