### ISSUE TITLE
Vault PKI certificate renewal taking place too often?

### ISSUE THREAD

**Issue by srcnix** [hashicorp/consul-template#1071]
I seem to be having some weird behaviour with Consul-Template - but I'm unsure if this is actually how it's supposed to work.

## The problem
Every now and again some of our containers restart and continuously restart until upgraded - then all works as expected until the next time this occurs.

What's causing the restart is our command that is run when certificates change on disk. This shows our commands are running correctly as we need to either restart or reload a service when certificates have changed.

What it doesn't explain though is the following:

Certificates are set to expire 7 days after creation. In the situation described above, new certificates are always obtained even if not expired, causing a continuous restart cycle.

## Other notes
Restarting the containers results in no change, but upgrading the containers resolves the issue. Taking into account that this can happen on services without persistent storage, it doesn't make sense why the upgrade solves the issue.

As far as we can see, it's sporadic. For example, in one environment (staging) only a few containers using Consul-=Template are affected, but other similar containers are now. Then in another developers local environment, many containers are affected by this.

Final note: I've set the generate_lease for each role that certificates are created against. Is there anything else I should be setting for roles or anything related?

Just to note, the vault token renewal is working a treat!

## My thoughts
Does Consul-Template look at the lease duration / expire time of a certificate to see if it needs to fetch another, or just it just continuously fetch new certificates when ever it feels like it?

If the latter, how can we stop this, and only fetch certificates when they are due to expire?

**Comment by srcnix** [comment]
Race condition, our fault. Thanks!

**Comment by smintz** [comment]
I am experiencing the same, can you elaborate more about how you solved that?

**Comment by errnoh** [comment]
@smintz this is usually case of missing the `generate_lease` setting mentioned at https://github.com/hashicorp/consul-template/blob/master/examples/vault-pki.md
