### ISSUE TITLE
Log level info is too noisy

### ISSUE THREAD

**Issue by jarro2783** [hashicorp/consul-template#1080]
I think that log level `INFO` is too noisy. For example, if I want to know when Consul Template actually updates a file, I need to see all the other `INFO` messages that I don't really care about. So this message is useful:
`log.Printf("[INFO] (runner) executing command %q from %s", command, t.Display())`

but one of these every 5 seconds is not:
`[INFO] (runner) initiating run`

Can the log levels of some of the messages be adjusted so that there is a more useful distinction between info and debugging noise. Really I feel `initiating run` is debugging, and I would be happy enough if that was just moved to `DEBUG`.

### Consul Template version

`v0.19.4`

**Comment by jvrplmlmn** [comment]
@jarro2783 I've opened https://github.com/hashicorp/consul-template/pull/1088 to address this issue.

**Comment by pearkes** [comment]
Should be fixed in #1088
