### ISSUE TITLE
Allow leader selection via template

### ISSUE THREAD

**Issue by flyhard** [hashicorp/consul-template#1085]
I am looking for a feature that allows me to configure one node of my application cluster as a leader via config file. 

I am running the same template on multiple nodes and would like one of them to be configured different from all others. So something that allows me to specify it in a IF statement would be great:

    {{ if leader("key") }} .... {{ end }}

I have not been able to find a function like this yet. My workaround is this currently:

```
{{- with service "application" }}
{{- with index . 0}}
{{- $leader := printf "%s-%s" .Node .ID}}
{{- range service "application" }}
{{- if printf "%s-%s" .Node .ID | regexMatch $leader }}
        {{.Address}}:{{.Port}} leader=yes
{{- else }}
         {{.Address}}:{{.Port}} leader=no
{{- end }}
{{- end }}
{{- end }}
{{- end }}
```

**Comment by banks** [comment]
Hey @flyhard,

Leader election is a complex distributed systems issue that is very challenging to reason about. We already build the lock mechanism in Consul itself via the API. We even have a command line helper for really trivial cases where integrating with Consul is not convenient.

In general though there are so many subtelties around timing, safety, liveness, consistency, deteminism etc. that the feature as you described it doesn't seem to be something we'd want to encourage.

If the workaround you listed is good enough for your app then that's great but it's far from clear the subtleties around the semantics at work there are suitable for anyone else who want's "leader election". For example I'm not sure we even make a strong guarantee about ordering of the responses so it's not obvious that every consul-template instance would even get the same instance as index 0.
