### ISSUE TITLE
arise many tcp connections on port 8500

### ISSUE THREAD

**Issue by vinglogn** [hashicorp/consul-template#1086]
1.  I used consul-template to synchronize configuration from consul in my application.
2.  consul-template version:  0.19.4  and consul version: 1.06
3.  I complie the source code of consul-template version 0.19.4， and only modify one file  to change the time of blocking query in view.go list bleow: 
.........
const (
	// The amount of time to do a blocking query for
	defaultWaitTime = 10 * time.Minute
)
........
4. I used 64 consul-template file ( like abc.ctmpl, ovw.ctmpl .... ), and my config.hcl content list: 
############################################
............
consul {
address = "x.x.x.x:8500"
}
pid_file="/var/run/consul-template.pid"
log_level = "warn"
wait {
  min = "5s"
  max = "10s"
}
template {
source = "/usr/local/myapp/consul/apps_conf.ctmpl"
destination = "/usr/local/myapp/consul/apps.conf"
backup = true
} 
........
#####################################
5. In my OS（CentOS6.5）which the consul-template program run in,  I find 982 tcp connections on port 8500 in the link list. 
the command:   ~# lsof -i:8500|wc -l 
and I restart the consul-template program (kill it,  start it)
but the connections is also reach to 133.  I wonder why it happen?  does it normal or abnormal things?
I am worrying about the connection count will group up in a slow way and hard to control？

**Comment by skyrocknroll** [comment]
For every consul key you watch  there will be an TCP connection.

**Comment by eikenb** [comment]
Thanks for the feedback @vinglogn and for the help @skyrocknroll.

AFAIK there is no leak of connections and this is expected behavior as @skyrocknroll indicated. I'm going to close this ticket but I will keep an eye out for related issues. Thanks.
