### ISSUE TITLE
Consul-template single point of failure

### ISSUE THREAD

**Issue by vinglogn** [hashicorp/consul-template#1089]
1.  consul-template version:  0.19.4
2.   consul-template configuration File:
....................
consul {
  auth {
    enabled  = true
    username = "test"
    password = "test"
  }
  address = "127.0.0.1:8500"
  token = "abcd1234"
}
........................
3.  Problem description:
      In the section of consul in config.hcl , the consul addr is only support one remote consul agent,  if this consul agent is down by a crash, it will lead to consul-template single point of failure.

4. I  wonder if there a schdule to support mutil-address of consul address ? just like Confd 
"https://github.com/kelseyhightower/confd/blob/master/docs/configuration-guide.md"

**Comment by pierresouchay** [comment]
My 2 cents:

On our side, tools like consul template are using localhost, but we also registered all Consul agents with a name, so when outside systems from our clusters do need a reference over a Consul agent, we use DNS, for instance:

consul-agent-http.service.consul

**Comment by guidoiaquinti** [comment]
If you use the local `consul` agent as "proxy" you can multiplex all the requests to the consul servers over a single TCP connection. Doing that the number of connections on the server scale linearly with the number of nodes in your cluster (if you don't do that, the number of connections will scale linearly with the number of watches).

I never had issues with `consul` agent crashing but you can work around that by letting `systemd`/`runit` managing it.

I anyway support this feature request!

**Comment by vinglogn** [comment]
@guidoiaquinti @pierresouchay ,Dear all:
1.  I have solved this problem in another way. 
2.  In my enverment, I used the consul-template to pull the configure from consul for my 100+ nginx servers of cluster, each nginx server node install a consul-template. I deploy  a consul cluster with 5 server agent and 5 client agent separately. So, all the consul-template will pull the configure from a remote consul address.
3. I used my nginx to do a 7-layers balance-load to support high availability, and the configure file of nginx as follows:
/**********************************
*file: loalhost.conf
***********************************/
upstream consul_template {
    server **consul_addr1**:**8500** weight=3 max_fails=2 fail_timeout=10s;
    server **consul_addr2**:**8500** weight=3 max_fails=2 fail_timeout=10s;
}
server {
   listen **8038**;
   server_name 127.0.0.1;
   **proxy_http_version 1.1**;
   index index.html index.htm;
   default_type text/html;
   error_log /usr/local/nginx/logs/error.log      error;
   access_log off;

   location / {
       proxy_pass http://consul_template;
   }
}
/******************************************************************/
and my consul-template configure file config.hcl：
..................................
consul {
auth {
enabled = true
username = "test"
password = "test"
}
address = "127.0.0.1:**8038**"
token = "abcd1234"
}
...............................
4. All the connections from consul-template link to local host nginx first, and then nginx proxy them to the backend consuls with a  long connection. **If one of the consul devices in the upstream power down**,  the consul-template can not observe this situation. In this way, single point of failure can be solved!

**Comment by eikenb** [comment]
Thanks everyone for your thoughts and solutions. As mentioned the designed use is to have a local consul-agent listening on localhost working as a proxy to the consul server cluster. The agent works with servers to monitor health/availability as well as to work as a caching proxy for requests.
