### ISSUE TITLE
Watch templates for changes on disk

### ISSUE THREAD

**Issue by inean** [hashicorp/consul-template#109]
Currently, consul-template doesn't detect changes on template contents. It would be good if consul-template could update internally template dependencies (watches, etc) and template contents when it's updated on disk.

**Comment by armon** [comment]
@sethvargo Agreed. I think SIGHUP should be documented as a way to solve this for now, and leave it on back burner, as the multi-pass dependency resolution is much more important.

**Comment by sean-** [comment]
File system watches... one of the less enjoyable problems to solve correctly.  HUP sounds fine to me.  For color (and humor):

https://www.youtube.com/watch?v=vm1GJMp0QN4&start=2475

**Comment by rotatingJazz** [comment]
How about an option that would "reload" the file every X seconds?

**Comment by wwalker** [comment]
+1

I think the expectation is that if the template is modified, one would expect the target file updated.

**Comment by armon** [comment]
After thinking this through further, we've decided against implementing this. The primary reason is that it makes it hard to stage changes to the template and control the roll out. Using an explicit SIGHUP allows for fine grained control of the reloading, where automatic reloading does not. In addition, this would introduce more complexity to the project. Instead, using a SIGHUP is a standard approach almost all software uses to handle configuration file updates.
