### ISSUE TITLE
divide function fails if first argument is the output of (service "myservice" | len)

### ISSUE THREAD

**Issue by WolverineFan** [hashicorp/consul-template#1091]
### Consul Template version

consul-template v0.19.4 (68b1da2)

### Configuration

In the examples below if I print the result of `service "myservice" | len` I get `4`

These templates fail:
```liquid
{{ $test := divide (service "myservice" | len) 5 }}
{{ $test }}
```

```liquid
{{ $len := service "myservice" | len }}
{{ $test := divide $len 5 }}
{{ $test }}
```

These all work:
```liquid
{{ $test := divide 5 (service "myservice" | len) }}
{{ $test }}
```

```liquid
{{ $len := 4 }}
{{ $test := divide $len 5 }}
{{ $test }}
```

```liquid
{{ $test := divide 5 5 }}
{{ $test }}
```

```liquid
{{ $test := multiply (service "myservice" | len) 5 }}
{{ $test }}
```

### Command

```shell
/usr/local/bin/consul-template -once -template ~/test.tpl:test.out
```

### Debug output

https://gist.github.com/WolverineFan/a01191276a4de4a001d5cb33143b3caf

### Expected behavior

Print the value of `$test`

### Actual behavior

```
panic: runtime error: integer divide by zero [recovered]
	panic: runtime error: integer divide by zero

goroutine 6 [running]:
text/template.errRecover(0xc42015b258)
	/usr/local/go/src/text/template/exec.go:140 +0x1df
panic(0x864aa0, 0xb62b60)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/hashicorp/consul-template/template.divide(0x83ae80, 0xc4201961f0, 0x83ae80, 0xc4201620c8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/hashicorp/consul-template/template/funcs.go:1093 +0xe05
```

**Comment by WolverineFan** [comment]
It's not just the output of the `len` function.  Using `len` to find the length of a string works:
```liquid
{{ $len := "stringhere" | len }}
{{ $test := divide $len 5 }}
{{ $len }}
{{ $test }}
```

**Comment by WolverineFan** [comment]
Found the problem.  I don't know if this is expected behavior (it certainly isn't intuitive) but what appears to be happening is `divide` is called before `services ... | len` has a value, so it gets called the first time with 0 as a placeholder.  Then it gets called **again** after it does have a value.  I would expect the call to `divide` to be delayed until the second pass when we have a value from `services`.

The following works around the problem by providing a non-zero default value that later gets replaced with the real value:
```liquid
{{ $test := divide (or (service "myservice" | len) 1) 5 }}
{{ $test }}
```

Perhaps more clearly:
```liquid
{{ $len := or (service "myservice" | len) 1 }}
{{ $test := divide $len 5 }}
{{ $test }}
```

I'm going to leave this open in case the current behavior is a bug, but I expect it's a *feature*

**Comment by eikenb** [comment]
Hey @WolverineFan, thanks for the issue and followup with your workaround.

So it sounds like the evaluation order isn't what you'd expect using the generally standard parenthesis based grouping. While not entirely intuitive it seems like the desired behavior based on the docs where it is mentioned several times that templates will be evaluated multiple times and initially templated values will be missing. Eg.

> Note: Consul Template evaluates the template multiple times, and on the first evaluation the value of the key will be empty (because no data has been loaded yet). This means that templates must guard against empty responses.

At this point this seems like an (understandable) mistake in your template.  The only thing I can think of to possibly address it is to catch the panic and add some context to the error about needing to deal with zero values in cases such as divide where the zero value can cause a panic.

I'm going to make a local note of it but not file an issue at this point as I want to get up to speed more before deciding on that. If you don't want to wait on me and would like to file an issue, please do.
