### ISSUE TITLE
Make timeout for blocking query configurable

### ISSUE THREAD

**Issue by guidoiaquinti** [hashicorp/consul-template#1096]
To do that we should probably simply expose the `defaultWaitTime` to the CLI/conf package:
https://github.com/hashicorp/consul-template/blob/d0ee7a7a959b1106932665677d8259974907741e/watch/view.go#L13-L16

I might be able to work on this _soon_ but I'm opening the issue anyway to keep track of the progress.

**Comment by guitmz** [comment]
@guidoiaquinti hey do you still plan to work on this? I was thinking about submitting a patch myself if I find the time

**Comment by guidoiaquinti** [comment]
Unfortunately not @guitmz, happy if you can PR

**Comment by eikenb** [comment]
@guidoiaquinti @guitmz 

Would either of you mind giving a bit more context about why you'd like this feature? A use case you have in mind or like? Thanks.

**Comment by guitmz** [comment]
@eikenb sure, a real example that happened to me (which made me fork consul-template and implement this feature) was the following:

I have consul running behind AWS application load balancer which had a keepalive of 120 seconds and everything was just fine.

For reasons, this keepalive had to be changed to 45 seconds and then problems started to appear. See, this means that the load balancer is now closing connections after 45 seconds and consul-template wants them open for 60 seconds. This was causing 5xx error all over the place.

Solution was to fork and make this value less than 60 seconds in consul-template.
