### ISSUE TITLE
Busy loop when node not found in catalog 

### ISSUE THREAD

**Issue by rcarpa** [hashicorp/consul-template#1103]
Hi Hashicorp team,

We are hitting sometimes a case when consul-template is spamming the log with hundreds of messages of the type: 
`[WARN] catalog.node(example.com): no node exists with the name "example.com"`
at millisecond intervals. 

Increasing the log level leads to the following output: 
`2018/05/09 13:12:27.243344 [DEBUG] (runner) checking template d050dff4d793aad2b64966c66d05c67f`
`2018/05/09 13:12:27.345362 [TRACE] catalog.node(example.com): returned response`
`2018/05/09 13:12:27.345444 [WARN] catalog.node(example.com): no node exists with the name "example.com"`
`2018/05/09 13:12:27.345502 [TRACE] (view) catalog.node(example.com) marking successful data response`
`2018/05/09 13:12:27.345529 [TRACE] (view) catalog.node(example.com) had a lower index, resetting`
`2018/05/09 13:12:27.345568 [TRACE] (view) catalog.node(example.com) successful contact, resetting retries`
`2018/05/09 13:12:27.345590 [TRACE] catalog.node(example.com): GET /v1/catalog/node/example.com?stale=true&wait=1m0s`
`2018/05/09 13:12:27.347126 [TRACE] catalog.node(example.com): returned response`
`2018/05/09 13:12:27.347183 [WARN] catalog.node(example.com): no node exists with the name "example.com"`
`2018/05/09 13:12:27.347200 [TRACE] (view) catalog.node(example.com) marking successful data response`
`2018/05/09 13:12:27.347216 [TRACE] (view) catalog.node(example.com) no new data (index was the same)`
`2018/05/09 13:12:27.347248 [TRACE] catalog.node(example.com): GET /v1/catalog/node/example.com?stale=true&wait=1m0s`
`2018/05/09 13:12:27.347291 [TRACE] (view) catalog.node(example.com) successful contact, resetting retries`
`2018/05/09 13:12:27.350146 [TRACE] catalog.node(example.com): returned response`
`2018/05/09 13:12:27.350180 [WARN] catalog.node(example.com): no node exists with the name "example.com"`
`2018/05/09 13:12:27.350196 [TRACE] (view) catalog.node(example.com) marking successful data response`
`2018/05/09 13:12:27.350221 [TRACE] (view) catalog.node(example.com) no new data (index was the same)`
`....................................................................................................`
`.................... < previous block repeated each couple of milliseconds >`
`....................................................................................................`

Is this an expected behaviour?  Or it is a bug due by the fact that 
* [catalog_node.go#L95](https://github.com/hashicorp/consul-template/blob/d57ece130dad4c31c1873ff588cd00628937a366/dependency/catalog_node.go#L95) returns no error when node is empty. Moreover, qm.LastIndex == 0 in this case.
* [view.go#L258](https://github.com/hashicorp/consul-template/blob/d57ece130dad4c31c1873ff588cd00628937a366/watch/view.go#L258) resets v.index 
* and [view.go#L252](https://github.com/hashicorp/consul-template/blob/d57ece130dad4c31c1873ff588cd00628937a366/watch/view.go#L252), combined with [view.go#L155](https://github.com/hashicorp/consul-template/blob/d57ece130dad4c31c1873ff588cd00628937a366/watch/view.go#L155), create a busy loop ?

In the meantime, we are still trying to investigate what happens on the consul side : is the returned node really empty? why does it happen? The issue is not frequent, and transitory (a couple of seconds, for random node). Difficult to catch.  If you are aware of such behavior of consul, it may help us in debugging. 

Sincerely, 
Radu

**Comment by eikenb** [comment]
Hey @rcarpa, a belated thanks for the report.

Are you still seeing this? Did your additional investigations turn up any more info?

Thanks.

**Comment by rcarpa** [comment]
Hi @eikenb . Sorry for the late answer. We ended by completely removing consul-template and substituting it with direct calls to the consul http api. Unfortunately, I cannot provide more insights on the issue anymore.

**Comment by eikenb** [comment]
@nielssandmann, @wdauchy, @leowmjw, @samm-git, @vbratkev

You all :+1:'d this... any of you still having the issue? Any insights?

**Comment by samm-git** [comment]
Hi, not on my side anymore - was fixed long time ago, i think on one of the version upgrades

**Comment by eikenb** [comment]
@samm-git .. That's great news. Thanks for letting me know. :)

**Comment by eikenb** [comment]
No one else has chimed in, so I'm going to assume @samm-git speaks for the group and this issue is fixed. :)

**Comment by shantanugadgil** [comment]
FWIW, today I happened to see this error for the first time, but I am using Nomad 1.2.6
