### ISSUE TITLE
Consul Template + Load Balancer

### ISSUE THREAD

**Issue by impguard** [hashicorp/consul-template#1104]
### Consul Template version

consul-template v0.18.1 (9c62737)

### Configuration

consul {
  address = "%(ENV_CONSUL_HTTP_ADDR)s"
}

template {
  source = "nginx.conf.tpl"
  destination = "/etc/
  command = "nginx -s reload"
  destination = "/etc/nginx/conf.d/nginx.conf:nginx"
}

### Command

consul-template -config "/app/build/consul-template.hcl"

#### Question

Hey, hopefully dumb question about consul-template or perhaps how it works internally. I'm connecting to consul through a load balancer with a timeout of 60 seconds. From research (including the reference below), it seems like 60 seconds is the magic number where there is contention between consul-template polling consul (keeping the connection alive) and the load balancer ending the idle connection.

Is there any way consul template can have a configuration option to configure the keepalive duration or the polling rate so it's not the load balancer that needs to be changed?

Or is there something it uses internally that hard codes this timeout or keepalive of a minute that I don't understand well?

### References

- https://github.com/hashicorp/consul-template/issues/699

**Comment by saurabtanej** [comment]
@impguard did you find something for this? I have an exact question, doesn't seem to be configurable though

**Comment by impguard** [comment]
No, it's not configurable as far as I could tell. The only option right now is to reconfigure the load balancer itself, which is somewhat lame.

**Comment by guitmz** [comment]
this is basically blocking the use of the tool for me.. I had to lower the load balancer idle timeout and now consul always returns 504 when consul-template queries it

**Comment by eikenb** [comment]
Hey @impguard, thanks for posting.

The TLDR is no, this isn't configurable. Though there is an issue requesting it be so: #1096.

Please feel free to upvote that issue with the +1 emoji reaction (the thumbs up). I'll be using those in the future to help determine community priorities. Thanks.
