### ISSUE TITLE
Watching dependencies DDoS

### ISSUE THREAD

**Issue by rchernobelskiy** [hashicorp/consul-template#1107]
### Consul Template version

0.19.4

### Command

```shell
consul-template -once -dry -config .tmp/ct.conf
```

### Warning
```
[WARN] (runner) watching 132 dependencies - watching this many dependencies could DDoS your consul cluster
```

### Description
Inside the template I have a loop and it looks like consul-template is starting a new watcher for every sub-path in that loop, even though i'm using -once, so I have two questions:
1) Should I be concerned about this with my use case?
2) Any plans to fix this?

**Comment by pierresouchay** [comment]
https://github.com/hashicorp/consul-template/issues/1065 Allows mitigating this as well as https://github.com/criteo/consul-templaterb which as heuristics to avoid DDos your Consul cluster (we are using it on clusters of more than 6k nodes)

But basically, this is just a message -not based on any heuristics - unless you plan to use the template on hundreds of nodes on large clusters, it should be fine

**Comment by mkeeler** [comment]
@rchernobelskiy  I am going to close this as @pierresouchay  looks to have answered the question. Like he said the message isn't based on anything certain but rather is emitted if you are watching more than 128 things. What your Consul cluster can handle could be significantly higher (if you only have a couple consul-template instances running and your cluster isn't already at its resource limites) or lower (running many consul-template instances or your cluster is pushing its resource limits).

The message is there just to make users aware of the potential for harming their clusters if they abuse it. One example of this I had seen in the past resulted in over 200,000 go routines being spawned on the leader of the consul cluster to field all the blocking queries originated from the users usage of consul-template. That was a much more extreme case but it definitely had a negative impact on the cluster health.
