### ISSUE TITLE
Rendering templates without consul

### ISSUE THREAD

**Issue by nlewo** [hashicorp/consul-template#1114]
Is it possible to render templates without consul?

The main objective is to validate configuration files at build time.
Suppose we build a container where configuration files are rendered by consul-template. 
At container build time, it would be nice to be able to run consul-template with dummy data, to generate a config file. This dummy configuration file could then be checked by a linter, or by the services itself.

It would also be able to run the container without having a up and running consul, for testing purposes also.

This could be a consult-template option that takes a JSON file that contains datas. For instance:
```
consul-template --dummy-consul-data consul.json ...
```

**Comment by sean-** [comment]
@nlewo : I believe the droid you are looking for is [`gomplate`](https://github.com/hairyhenderson/gomplate).

**Comment by nlewo** [comment]
@sean- Are you suggesting to switch from `consul-template` to `gomplate` ?

I would prefer to continue to use `consul-template` which gets its data from consul on production environments. But on CI environments, I would like to be able to validate these template without having to rely on consul.

**Comment by sean-** [comment]
> Are you suggesting to switch from consul-template to gomplate ?

If your templates are being rendered only once and not being updated when a consul value changes, then yes.

https://gomplate.hairyhenderson.ca/datasources/#using-consul-datasources

And if you want to see your values change on the fly, then use Nomad's `template` stanza https://www.nomadproject.io/docs/job-specification/template.html for dynamic updates.  We've moved to using `gomplate` to unconditionally launch our executables and `nomad` to pick up dynamic changes in `consul` values, which causes a restart of a task, which causes `gomplate` to be re-run.

Best of luck with the feature request.

**Comment by nlewo** [comment]
My services need to watch Consul and templates have to be rendered on the fly. I'd prefer to continue to use `consul-template` which is easy to understand and use.

In fact, I just wrote a small [consul-template mock](https://github.com/nlewo/consul-template-mock) that does what I need: 
```
$ cat trivial.tmpl
Rendered {{- key "message" }}

$ cat trivial.json
{ "key": { "message": " without Consul :/" }}

$ consul-template-mock trivial.tmpl trivial.json
Rendered without Consul :/
```

Thanks for your comments

**Comment by mkeeler** [comment]
@nlewo For your situation I would recommend running an instance of Consul in dev mode and populating it with all the information you need via the API or consul configuration files. Then you can point consul-template at the dev instance to render the templates.

The added complexity to support getting data from sources other than the consul API is not something we would want to support. Especially given you already have worked around with your mock yourself I am going to close this feature request.

**Comment by lawliet89** [comment]
@mkeeler Since consul-template also supports reading secrets from Vault, my use case is to only template out the secrets from Vault without needing anything from Consul. 

Seems like (AFAIK) it's not possible to leave out Consul at all when using consul-template.

**Comment by peimanja** [comment]
@mkeeler I have the same use case as @lawliet89. Basically, I am looking at getting certificates for Consul RPC encryption from Vault prior to starting Consul.

**Comment by mkeeler** [comment]
@peimanja and @lawliet89 You should be able to use consul-template with Vault without having any interaction with a Consul cluster. There have been some discussions around renaming or refactoring into a new library/command to make this more apparent. Essentially thought you should be able to configure just the vault pieces and have it work as expected. If you run into any issues, please submit a new bug report with the details.

**Comment by lawliet89** [comment]
I will give it a try. Last I tried, I left out configuring consul and it complained about not being able to connect to the default local consul agent.

**Comment by lawliet89** [comment]
For those who have arrived at this issue, Vault Agent from 1.3 will support Consul Template like rendering: https://github.com/hashicorp/vault/blob/master/website/source/docs/agent/template/index.html.md
