### ISSUE TITLE
Docker image for v0.19.5

### ISSUE THREAD

**Issue by bezidejni** [hashicorp/consul-template#1116]
Hi, 

I was wondering if there are any plans to push the official image with the latest version, v0.19.5, to Docker Hub?

Thanks!

**Comment by banks** [comment]
Thanks @bezidejni that was my oversight.

I'm tracking down the right permission to push to our Docker Hub account as the previous maintainer is no longer around.

**Comment by banks** [comment]
Done. Thanks for reporting this!
