### ISSUE TITLE
consul-template not useable with vault's versioned KV store

### ISSUE THREAD

**Issue by ShimiTaNaka** [hashicorp/consul-template#1121]
Have tried to get secrets from the versioned KV with no success (if I want a specific version)
given the following mount point: `/secret` and the secret `test` in int,
I am able to use the following template:
```liquid
{{ with secret "secret/data/test" }}{{ .Data.data }}{{ end }}
```
and that brings me the latest version.
However, if I want to pin a version, and use it like so:
```liquid
{{ with secret "secret/data/test?version=1" }}{{ .Data.data }}{{ end }}
```
I get `No value found at secret/data/test?version=1`
I assume that it's in part due to the KV being relatively new feature.
Is it planned to be added soon?

Thanks

**Comment by derBroBro** [comment]
I am not sure if this is related. If we try to use KV v2 we get `no secret exists at ...`. 
For a v1 it works without any issues.

**Comment by eBeyond** [comment]
I've got the same issue. After changing the KV to v2 I also get the mentioned error. Nothing else changed except switching to v2.

**Comment by i4s-pserrano** [comment]
hi all, take a look to 
https://github.com/hashicorp/nomad/blob/c6d9dba7b54898cb9c6925b407e6e18e464f8d34/website/source/docs/job-specification/template.html.md#vault-kv-api-v2

**Comment by ShimiTaNaka** [comment]
But that doesn't resolve the question of getting specific version
