### ISSUE TITLE
Non-renewable leases aren't used to full potential

### ISSUE THREAD

**Issue by nutbunnies** [hashicorp/consul-template#1126]
### Consul Template version

```consul-template v0.19.4 (68b1da2)```

### Configuration

```liquid
{{with secret "aws/sts/somerole" "ttl=12h"}}
AWS_KINESIS_ACCESS_KEY={{.Data.access_key}}
AWS_KINESIS_SECRET_KEY={{.Data.secret_key}}
AWS_KINESIS_SECURITY_TOKEN={{.Data.security_token}}
{{end}}
```

### Command

```shell
consul-template -template ct.hcl -dry -log-level=trace
```

### Debug output

```
2018/07/24 15:54:57.621191 [TRACE] vault.write(aws/sts/somerole -> 54d618e4): secret is not renewable, sleeping for 3h3m17.348840674s
```

### Expected behavior

Non-renewable vault lease would cause re-render of template towards the end of it's TTL.

### Actual behavior

Template is re-rendered roughly 1/3 thru the leases TTL.  This looks to be caused by the logic in [vault_common.go:67](https://github.com/hashicorp/consul-template/blob/master/dependency/vault_common.go#L67).  Our use case is actually the template stanza in Nomad job specs.  When injecting AWS STS values via the template it's causing the template to render every 2-4h on a 12h TTL which is causing unnecessary churn of instances.

A quick test of checking the renewability of the lease in `vaultRenewDuration()` appears to do the right thing:
```go
if vaultSecretRenewable(s) {
    // Renew at 1/3 the remaining lease. This will give us an opportunity to retry
    // at least one more time should the first renewal fail.
    sleep = sleep / 3.0

    // Use a randomness so many clients do not hit Vault simultaneously.
    sleep = sleep * (rand.Float64() + 1) / 2.0
} else {
    // For non-renewable leases setting renew duration to use much of the secret lease as possible.
    // Ranging 85%-99% so many clients do not hit Vault simultaneously.
    sleep = sleep * (.85 + rand.Float64()*0.14)
}
```

If this is a valid issue and the solution is on the right track, I can add some tests around it and do a PR.

### Steps to reproduce

1. Setup a vault mount with non-renewable leases (AWS with STS is a good example)
2. Use template with non-renewable leases in it

**Comment by Jeff-Hanson** [comment]
Any update on this? Would like to see this fixed in the next release. It is really making our non-renewable leases cause unneeded churn for our nomad-managed services. The fix appears to be straightforward. Can we at least get confirmation that this approach is valid so a PR can be submitted? thanks.
