### ISSUE TITLE
Case-only import variation failure when importing consul-template and k8s.io/helm

### ISSUE THREAD

**Issue by sbueringer** [hashicorp/consul-template#1133]
### Consul Template version

v0.19.5

### Expected behavior

What should have happened?

I'm trying to build a command-line tool which uses consul-template as well as some Helm rendering capabilities. Therefore, I have dependencies to consul-template and k8s.io/helm and I'm trying to vendor both. dep ensure should run successful.

### Actual behavior

What actually happened?

dep ensure leads to Case-only import variation failures. This happens because consul-template as well as helm has imports to "github.com/BurntSushi/toml". 
Consul-template imports it as:
* "github.com/burntsushi/toml" [link](https://github.com/hashicorp/consul-template/blob/master/Gopkg.toml#L3)

Helm imports it as:
* "github.com/BurntSushi/toml" [link](https://github.com/helm/helm/blob/7cad59091a9451b2aa4f95aa882ea27e6b195f98/pkg/chartutil/files.go#L27)

BurntSushi/toml refers to itself by `BurntSushi/toml` [link](https://github.com/BurntSushi/toml/blob/master/cmd/tomlv/main.go#L13)

I'm not sure which one is idiomatic, but one possible fix would be if consul-template could import BurntSushi/toml the same way as helm. I could/would open a PR if that's an option for you.

### References

Are there any other GitHub issues (open or closed) that should
be linked here? For example:
- https://github.com/golang/dep/issues/806
- [Go dep failure modes](https://golang.github.io/dep/docs/failure-modes.html)

**Comment by eikenb** [comment]
Hey @sbueringer, sorry for the long delay in response. The package was sort of in limbo for a time while but is now maintained again... or at least on its way to. I recently took on the maintainer role for the project and am working through things now.

I'll look into changing that import name as that does seem like the best solution to the issue. I'm planning on 1 update to the dep managed vendored packages before migrating to go-modules and will try to include #1139 in that (and keep the fix in go-modules).

Thanks.

**Comment by sbueringer** [comment]
@eikenb Thanks, no problem. Nice to hear the project is maintained again :)
