### ISSUE TITLE
how could i get consul-template ResponseMetadata in my template

### ISSUE THREAD

**Issue by hjybdrs** [hashicorp/consul-template#1136]
Please note that the Consul Template issue tracker is reserved
for bug reports and enhancements. For general usage questions,
please use the Consul mailing list:

    https://groups.google.com/forum/#!forum/consul-tool

### Consul Template version
consul-template v0.19.5 (57b6c71)
Run `consul-template -v` to show the version. If you are not
running the latest version, please upgrade before submitting an
issue.

### Configuration

```hcl
# Copy-paste your Consul Template configuration file here
```

```liquid
# Copy-paste your Consul Template template here
```

### Command

```shell
# Place your Consul Template command here
```

### Debug output

Provide a link to a GitHub Gist containing the complete debug
output by running with `-log-level=trace`.

### Expected behavior

What should have happened?

### Actual behavior

What actually happened?
i see this return ,just want to know any configuration to get  LastIndex:   qm.LastIndex,
![image](https://user-images.githubusercontent.com/6185339/44954908-de467e00-aedc-11e8-848d-d1bc327214c1.png)

### Steps to reproduce

1.
2.
3.

### References

Are there any other GitHub issues (open or closed) that should
be linked here? For example:
- GH-1234
- ...

**Comment by pierresouchay** [comment]
@hjybdrs I don't think you can, you can access it into consul-templaterb however: https://github.com/criteo/consul-templaterb/blob/master/TemplateAPI.md#common-structure-of-returned-objects

**Comment by eikenb** [comment]
Hey @hjybdrs. Thanks for the post.

If you still have this question, please ask in the community support resources as someone there might be able to help. I eventually might be able to, but am still getting up to speed. And the issue tracker here on github is meant for bugs or feature requests. Thanks.
