### ISSUE TITLE
Compiling without docker

### ISSUE THREAD

**Issue by zen42** [hashicorp/consul-template#1142]
Any chance of updating the readme with details on how to compile without docker? 

Also 'make bin' doesn't seem to be an option in the make file but is listed on the readme.

**Comment by mkeeler** [comment]
We probably should do this but for your reference until we update the README `make dev` will do what you want. If you want to cross compile you can `GOOS=<desired OS> GOARCH=<desired arch> make dev`

**Comment by eikenb** [comment]
I'm going to be re-working this to not use Docker for the builds in the near future. I think local native should be the default with the possibility to add a docker wrapper of that for pristine builds if it seems useful.

**Comment by eikenb** [comment]
Missed it when I made the update. But this is done.
