### ISSUE TITLE
output the actual change of consul (kvs) 

### ISSUE THREAD

**Issue by jianzzz** [hashicorp/consul-template#1147]
May I ask such a question: 
What can I do to output the actual change of consul (kvs) via consul-template
I want to store the history of change, and makes it easy to troubleshoot problems

**Comment by skyrocknroll** [comment]
@jianzzz You can use consul watch for your use case. More details can be found here https://www.consul.io/docs/commands/watch.html

**Comment by eikenb** [comment]
Thanks for the question @jianzzz  and the followup @skyrocknroll.

If you need any more help with this may I refer you to the community support resources as the issue track is meant for bugs and feature requests.

https://discuss.hashicorp.com/c/consul                        
https://www.consul.io/community.html
