### ISSUE TITLE
Allow reading tokens from file

### ISSUE THREAD

**Issue by Phylu** [hashicorp/consul-template#1154]
### Consul Template version

Docker container hashicorp/consul-template:alpine. Directs to version `consul-template v0.19.5 (57b6c71)`

### Configuration

```hcl
vault {
  ssl {
    ca_cert = "/etc/vault/tls/ca.pem"
  }
  retry {
    backoff = "1s"
  }
}
```

### Command

```shell
/bin/consul-template
```

### Expected behavior

It should be possible to load the VAULT_TOKEN from a location on the disc in order to use consul-template in combination with a vault init container which places the VAULT_TOKEN onto a shared in memory file system.

### Actual behavior

The vault token can be either placed statically in the configuration which is provided via `CT_LOCAL_CONFIG` environment variable or as `VAULT_TOKEN` environment variable. Both is methods are not possible as the token is retrieved in the init container which has no access to these variables.

### Steps to reproduce

1. Deploy a Kubernetes cluster
2. Run sethvargo/vault-kubernetes-authenticator:0.1.2 as an init container
3. Run hashicorp/consul-template as container

### References

- https://github.com/sethvargo/vault-kubernetes-workshop/issues/4

**Comment by atheiman** [comment]
It should read from `homePath + "/.vault-token"`. See https://github.com/hashicorp/consul-template/blob/d3b6838a3ad8c82b60b5416c733595d6db4f7ea1/config/vault.go#L222-L234

But I think that there should be an option in consul template config for a file path to read the token from.

**Comment by Phylu** [comment]
Thanks for the hint. I will try to see if I can get it working with that knowledge in mind.

**Comment by ac-astuartkregor** [comment]
@atheiman Will consul-template periodically re-read the token at `$HOME/.vault-token` or would consul-template need to be restarted in order to pick up a new token? I realise consul-template can renew the token, but I'm working through the case of what happens when the `max_ttl` is reached.

**Comment by atheiman** [comment]
I haven’t tested that, but it should be fairly easy to test

**Comment by ac-astuartkregor** [comment]
@atheiman I'll have a look and see whether I have an opportunity to test it myself.

**Comment by dicarlo2** [comment]
Seems like https://github.com/hashicorp/consul-template/pull/1153 resolves this issue (and others related to watching files for integration with vault agent), would be nice if the maintainers could take a look. @mkeeler @banks

**Comment by mbrancato** [comment]
I'd like to see this as well. I don't think that the vault agent PR will fix the underlying issues here at all. Definitely not for the use-cases I'm thinking of as I think it assumes the user has a home folder and that the same user context was used for authentication.

There are security concerns here as well. Specifying secrets (including auth tokens) as command parameters is a really bad idea. Command line params can often be read by other users and are frequently logged and extractable via monitoring systems as well. I'd highly recommend removing the ability to specify a token as a parameter and move it to a file location instead. It might be valuable to support an environment variable that specifies this file location as well.

**Comment by jefferai** [comment]
The agent PR doesn't make that assumption.

**Comment by mbrancato** [comment]
Absolutely you are correct @jefferai, sorry about that . This is my mistake conflating the process with the Vault login process and the token file in a home folder. With the Vault agent you can specify the location of the file in the sink.

**Comment by eikenb** [comment]
Any reason this issue shouldn't be closed? Seems #1153 resolves it as @dicarlo2 points out.

**Comment by catsby** [comment]
@eikenb I think we can close this now 👍

**Comment by eikenb** [comment]
Thanks again @catsby... I do believe it is fixed and it has been long enough waiting.
