### ISSUE TITLE
i want to read only secret password from consul template but renders false map and a token with the password

### ISSUE THREAD

**Issue by shashankimanage** [hashicorp/consul-template#1175]
### Configuration
config.tpl
{{ with secret "kv/hello-secret" }}
{{ . }}{{ end }}

consul-template.hcl

consul{
  address="consul-dev:8500"
}

vault {
  address="http://vault:8200"
  token=""
  renew_token = false
	
}

template {
    source      = "/config/vault/config.tpl"
    destination = "/config/vault/config.txt"
   
}

### Debug output
below is the output.txt file with a token and false map from consul  template

{10fce22e-6f74-3f0a-8174-7575b12915c0  2764800 
false 
map[var:1]
 [] <nil> <nil>}

### Expected behavior

only the password which is var:1 should be in a output file

### Actual behavior

there is a token with a false map and a nil value
- ...

**Comment by kyhavlov** [comment]
Hey @shashankimanage, for this case (printing *only* the value of the secret) you'd want to use syntax like `{{ .Data.var }}` in the template rather than `{{ . }}`. There's more info at https://github.com/hashicorp/consul-template#secret. Hope this helps!
