### ISSUE TITLE
Namespace support

### ISSUE THREAD

**Issue by pearkes** [hashicorp/consul-template#1176]
We want to support configuration for [Vault Namespaces](https://www.vaultproject.io/docs/enterprise/namespaces/index.html) at the _configuration_ level i.e the configuration for consul-template.

**Comment by vaneyckt** [comment]
Hi @pearkes. I'm a new consul-templates user and am currently trying to get it to generate a certificate using Vault's pki secrets.

The README file shows the following example for this:

```
{{ with secret "pki/issue/my-domain-dot-com" "common_name=foo.example.com" }}
{{ .Data.certificate }}{{ end }}
```

However, for my particular use case, I need to specify a namespace. I'm having a really hard time finding any documentation on how to do this. Does the current iteration of `consul-template` just not support this at all? Or is there an approach out there that I manage to keep overlooking?

**Comment by kyhavlov** [comment]
Hey @vaneyckt, currently there's no way to set a namespace with consul-template - #1181 will add a field to the vault config where you can specify one. We're looking to cut a v0.20.0 sometime within the next week which will have that and some other recent improvements as well.

**Comment by vaneyckt** [comment]
that is perfect. Thank you so much!
