### ISSUE TITLE
-log-file不工作

### ISSUE THREAD

**Issue by henry-pro** [hashicorp/consul-template#1184]
1.  指定-log-file=/opt/consul/logs/consul.log并不会生成consul.log日志文件，而是生成默认的consul-{timestamp}.log这种格式。
2.  生成的日志文件名为consul-1550128440659571478.log这种格式，不易区分，建议改成consul-2019-02-15.log。

**Comment by eikenb** [comment]
I believe this is basically asking for the command line argument to set what #1170 was asking for. So not quite a duplicate.
