### ISSUE TITLE
consul-template Vault KV integration

### ISSUE THREAD

**Issue by kjanshair** [hashicorp/consul-template#1199]
I'm trying to pull Vault secrets from the KV store. I wish to do 2 things:

1. When using Vault in non-dev mode, we get Vault KV version 1 (since versions are not displayed while updating a secret). I want `consul-template` to pull secrets from KV v1 automatically when it is updated in Vault, which is not happening.

2. When using dev mode, we get KV version 2 (as versions are maintained on each secret update). `consul-template` successfully update pulls the secrets **after some time** and update the destination config file automatically without restarting `consul-tempate`.

Questions:

1. How can I use `consul-template` with KV v1 with automatic secret updates?
2. How can we reduce **the time** to update the destination configs via `consul-template` whenever secrets are updated in KV v2 store.

Below are my configs:

`consul-template.hcl`

    vault {
      address = "http://localhost:8200"
      token = "x.xxxxxxxxxxxxx"
      renew_token = true
    }

    template {
      source = "./templates/config.ctmpl"
      destination = "./templates/config.txt"
    }

`config.ctmpl`

    {{ with secret "secret/data/database" }}{{ .Data.data.url }}{{ end }}

Command:

    vault kv put secret/database url=me.example.com

`Vault v1.0.3`

`consul-template v0.20.0`

**Comment by eedwards-sk** [comment]
Vault does not support blocking queries. The only way that consul-template sees vault value updates is when it renews its lease on each secret, which I believe by default happens at 1/2 of the lease time.

Thus if your secret is leased for 1 hour, and you change it after only 5 minutes, it won't see the change until 30 minutes have passed, when it attempts to renew the lease.

**Comment by kjanshair** [comment]
Okay and how do we specify leases time while putting\updating a value in the KV v2 store i.e. via command line?

And how about question 1?

**Comment by eikenb** [comment]
Hey @kjanshair, thanks for your post.

You might have better luck with your questions on in one of our community support resources. Either the [new discussion site](https://discuss.hashicorp.com/c/consul) and/or the [mailing list](https://groups.google.com/group/consul-tool) would be good places to ask. Maybe even one of [Vaults community  resources](https://www.vaultproject.io/community). Thanks.

**Comment by eikenb** [comment]
> And how about question 1?

This is what @eedwards-sk answered above.

> Okay and how do we specify leases time while putting\updating a value in the KV v2 store i.e. via command line?

You specify the vault lease times in the vault config.

**Comment by vvitayau** [comment]
For myself, I noticed kv v2 required an additional `data.` layer deeper for consul-template `v0.20.0`

```
{{ with secret "secret/data/database" }}{{ .Data.data.data.url }}{{ end }}
```
