### ISSUE TITLE
consul-template to watch for reload events

### ISSUE THREAD

**Issue by anhldbk** [hashicorp/consul-template#1201]
Hi guys,

I think there's a need to NOT auto reload services when configurations are changed as described [here: Running and Process Lifecycle](https://github.com/hashicorp/consul-template#running-and-process-lifecycle):

> While there are multiple ways to run Consul Template, the most common pattern is to run Consul Template as a system service. When Consul Template first starts, it reads any configuration files and templates from disk and loads them into memory. From that point forward, changes to the files on disk do not propagate to running process without a reload.
> 
> The reason for this behavior is simple and aligns with other tools like haproxy. A user may want to perform pre-flight validation checks on the configuration or templates before loading them into the process. Additionally, a user may want to update configuration and templates simultaneously. Having Consul Template automatically watch and reload those files on changes is both operationally dangerous and against some of the paradigms of modern infrastructure. Instead, Consul Template listens for the SIGHUP syscall to trigger a configuration reload. If you update configuration or templates, simply send HUP to the running Consul Template process and Consul Template will reload all the configurations and templates from disk.

I wonder if there's any configuration of consul-template allowing me to watch for a specific [consul-event](https://www.consul.io/docs/agent/watches.html#event) like `service-reload` to manually reload spawn services?

Thanks in advance!

**Comment by eikenb** [comment]
Hey @anhldbk, thanks for taking the time to post your question. 

AFAIK the only way to trigger a reload is via the signals (or restarting). Though I'm not an expert yet, as I'm still getting up to speed on the code base. You might want to try asking on the community portal's forum or on the mailing list (links below) as they exist for questions like this. Thanks.

https://discuss.hashicorp.com/c/consul

https://groups.google.com/group/consul-tool
