### ISSUE TITLE
0.20.0 is failing to render templates before running exec

### ISSUE THREAD

**Issue by eedwards-sk** [hashicorp/consul-template#1209]
### Overview

from 0.19.5 to 0.20.0, exec with daemon no longer works correctly

the sub process is launched before a template is rendered

### Consul Template version

0.20.0

### Expected behavior

What should have happened?

Template rendered before running the command

### Actual behavior

What actually happened?

Command is ran before the template is rendered, template never gets rendered

**Comment by eedwards-sk** [comment]
related:

#1196
#1207

**Comment by eikenb** [comment]
Hey @eedwards-sk, thanks for reporting the issue and taking the time to link in the other related issues.

When you had this issue did you have a `wait` set like #1196 and #1207 did? I can reproduce the issue with `wait` set, but not without.

Thanks.

**Comment by eikenb** [comment]
I figured out this was probably not the once/wait issue as exec/wait have a separate issue. I'm going to leave it closed though as a duplicate of #1229
