### ISSUE TITLE
how to range value

### ISSUE THREAD

**Issue by sunnylua** [hashicorp/consul-template#1211]
I have some values in a k/v like:
one
two
three

can range each row?

**Comment by lite2073** [comment]
This should do it:
```
{{- /* Given "key" = "one\ntwo\nthree" in consul KV */ -}}
{{- range $index, $value := (key "key" | split "\n") -}}
    {{- $value }}
{{ end -}}
```

**Comment by eikenb** [comment]
Thanks @sunnylua for using consul-template and a big thanks to @lite2073 for helping out.

In the future I suggest using our community support options as they are meant for helping answer questions where github issues are meant for bugs/feature-requests. You can find the community support links on the front page, but I'll repeat them here for convenience.

Community portal: https://discuss.hashicorp.com/c/consul
Other resources: https://www.consul.io/community.html

Thanks.
