### ISSUE TITLE
Feature request: add unix socket connection support

### ISSUE THREAD

**Issue by jordiclariana** [hashicorp/consul-template#1214]
### Consul Template version

`consul-template v0.20.0 (b709612c)`

### Configuration

```hcl
vault {
  address = "unix:///var/run/vault-agent.socket"
}

template {
  source = "/tmp/ctmp/token.ctmpl"

  destination = "/etc/consul/consul.d/token.json"
  command = "killall -HUP consul"

  error_on_missing_key = true
}
```
`/tmp/ctmp/token.ctmpl` template:
```liquid
{
    "acl": {
        "tokens": {
            "default": "{{ with secret "consul/creds/bec" }}{{ .Data.token }}{{ end }}"
        }
    }
}
```

### Command

```shell
consul-template -config /tmp/ct.conf
```

### Debug output

https://gist.github.com/jordiclariana/7c1353dfc74657ed1dd70c02dabbeb30

### Expected behavior

Consul-template should be able to connect to a unix socket and retrieve in this case the consul token.

### Actual behavior

Consul-template doesn't support unix sockets, although Vault do. As consul-template supports Vault, it should also support all its network schemas.
This is the error that `consul-template` throws (it is actually a warning, but I think it should be an error):
```
2019/05/30 08:26:35.552115 [WARN] (view) vault.read(consul/creds/bec): vault.read(consul/creds/bec): Get unix:///var/run/vault-agent.socket/v1/sys/internal/ui/mounts/consul/creds/bec: unsupported protocol scheme "unix" (retry attempt 2 after "500ms")
```

### Steps to reproduce

1. Prepare a Vault server/agent to listen to a unix socket. For instance with this config snippet:
```hcl
listener "unix" {
  address = "/var/run/vault-agent.socket"
  tls_disable = true
}
```

2. Config  `consul-template` to connect to that unix socket (refer to config file above).
3. Run `consul-template`:
```shell
consul-template -config /tmp/ct.conf
```

**Comment by lneva-fastly** [comment]
This is odd, since the vault client library _does_ support unix sockets...

**Comment by lneva-fastly** [comment]
The latest consul-template (0.21.0) supports unix sockets!  :tada:

**Comment by eikenb** [comment]
Thanks for the report @lneva-fastly!

It must have been an issue with the vendored dependencies. As this is working now, I'm going to close it. Thanks again.
