### ISSUE TITLE
Warning in health.service code: 404

### ISSUE THREAD

**Issue by telita** [hashicorp/consul-template#1216]
### Consul Template version

consul-template v0.20.0 (b709612c)

### Configuration

```hcl
consul {
        address = "localhost:8500"
        ssl {
                enabled = false
                verify = false
        }

        retry {
                enabled = true
                attempts = 12
                backoff = "250ms"
                max_backoff = "1m"
        }
}

max_stale = "10m"
pid_file = "/var/run/consul-template.pid"
log_level = "ERR"
```

```liquid
{{ $srv := "ups-bookingengine-bookingservicefactory" }}
{{ $app := "" }}
{{ $srvapp := print $srv $app }}
upstream "{{ $srv }}" {
        least_conn;
        {{range service $srvapp }}
        server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=5s;{{end}}
        keepalive 15;
}
```

### Command

```shell
sudo /opt/consul-template/bin/consul-template -config=/opt/consul-template/config -consul-addr=localhost -log-level=trace
```

### Debug output

2019/06/07 10:34:59.599631 [TRACE] (view) health.service(ups-checkout-bookingfactoryapi|passing) starting fetch
2019/06/07 10:34:59.599682 [TRACE] health.service(ups-checkout-bookingfactoryapi|passing): GET /v1/health/service/ups-checkout-bookingfactoryapi?stale=true&wait=1m0s
2019/06/07 10:34:59.599929 [WARN] (view) health.service(ups-checkout-bookingfactoryapi|passing): Unexpected response code: 404 (<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by telita** [comment]
This issue is not necessary, sorry

**Comment by telita** [comment]
I have a question about health service. Can I deactivate it in some way?

**Comment by eikenb** [comment]
Hey @telita, thanks for posting.

I'm still getting up to speed on all the different tech involved and am not sure about this right off. According to the consul docs you are able to register services without a healtcheck (they are listed as optional). So maybe start there...

https://www.consul.io/api/agent/service.html#register-service

You might be better off asking in one of the community support forums. There is the new portal at https://discuss.hashicorp.com/c/consul or you can find information on the mailing list and other resources at https://www.consul.io/community.html. Either of those places will be a better place to ask as github issues are meant more for bugs and feature requests.

Thanks.
