### ISSUE TITLE
Var in keypath

### ISSUE THREAD

**Issue by rosebude** [hashicorp/consul-template#1217]
Hello,
using a var on the botom of my template like that:
{{with $var1 := "value1" }}

I would like t use this var in a keypath definition:

   {{ $keypath := printf "primary/%s/fix" $var1 }}
   {{ $keyname := key $keypath }}
      {{with $d := printf "%s/%s" $keypath $keyname | key | parsejson}} {{ $d.valueeee | ...action....}}{{end}}
{{ end }}

Any idea ?

**Comment by greut** [comment]
did you try `executeTemplate` ?

**Comment by rosebude** [comment]
no i don't know `executeTemplate`.

my problem is about using $var in keypath :-/

**Comment by eikenb** [comment]
Hey @rosebude.

Github issues is intended for bugs and such, so is not the best place for general questions. For those we recommend you use the [support portal](https://discuss.hashicorp.com/c/consul) or [mailing list](https://groups.google.com/group/consul-tool).

**Comment by eikenb** [comment]
@rosebude .. I Just happened across this one again while digging around into executeTemplate and thought I'd take a stab at it... but I'm not exactly sure what you are asking.

Eg. here's a local attempt to reproduce it. I simplified the `with $d ..` line into something that would render. This renders as long as I have 1 value in consul... 

`$ consul kv put primary/value1/fix foo`

```
$ consul-template -template template.hcl -dry -once
{{ with $var1 := "value1" }}
{{ with $keypath := printf "primary/%s/fix" $var1 }}
{{ with $keyname := key $keypath }}
{{with $d := printf "%s/%s" $keypath $keyname }}{{ $d }}{{ end }}
{{ end }}{{ end }}{{ end }}
```
Outputs.. (whitespace trimmed)
`primary/value1/fix/foo`

My best guess is that you are having issues looking up the value in `$d` (the output). You can look up its value in consul if you replace `$d` with `key $d` in the template...
```
{{ with $var1 := "value1" }}
{{ with $keypath := printf "primary/%s/fix" $var1 }}
{{ with $keyname := key $keypath }}
{{with $d := printf "%s/%s" $keypath $keyname }}{{ key $d }}{{ end }}
{{ end }}{{ end }}{{ end }} 
```
