### ISSUE TITLE
Hierarchical Vault mount points are not working

### ISSUE THREAD

**Issue by mbeiter** [hashicorp/consul-template#1221]
Vault supports hierarchical mounts, like so:

```
/myFirstProject/kv-engine
/myFirstProject/pki-engine
/mySecondProject/kv-engine
/mySecondProject/pki-engine
```
Consul template removes the `/` in the path for some reason, which results in an API request to an invalid Vault URL (e.g. turning `/myFirstProject/kv-engine` into `/myFirstProjectkv-engine`) and subsequent authZ / GET request errors.

### Consul Template version

```
$ consul-template -v
consul-template v0.20.0 (b709612c)
```

### Consul Template Configuration (working example, non-hierarchical)

```hcl
field11={{with secret "/myProject_kv/key_1"}}{{ .Data.field_11 }}{{ end }}
```

### Consul Template Configuration (failing example, hierarchical)

```hcl
field11={{with secret "/myProject/kv/key_1"}}{{ .Data.field_11 }}{{ end }}
```

### Command

```shell
consul-template -config=myProject.hcl -log-level=trace
```

### Debug output (working example, non-hierarchical)

Relevant excerpt from the trace:

```
2019/06/25 18:43:53.589359 [TRACE] (view) vault.read(myProject_kv/key_1) starting fetch
2019/06/25 18:43:54.022319 [TRACE] vault.read(myProject_kv/key_1): GET /v1/myProject_kv/key_1
2019/06/25 18:43:54.192891 [TRACE] (view) vault.read(myProject_kv/key_1) marking successful data response
2019/06/25 18:43:54.193023 [TRACE] (view) vault.read(myProject_kv/key_1) successful contact, resetting retries
2019/06/25 18:43:54.193068 [TRACE] (view) vault.read(myProject_kv/key_1) received data
2019/06/25 18:43:54.193172 [TRACE] (view) vault.read(myProject_kv/key_1) starting fetch
2019/06/25 18:43:54.193272 [TRACE] vault.read(myProject_kv/key_1): secret is not renewable, sleeping for 4m37.675302392s
```

### Debug output (failing example, hierarchical)

```
2019/06/25 18:46:52.482294 [TRACE] (view) vault.read(myProject/kv/key_1) starting fetch
2019/06/25 18:46:52.964589 [WARN] (view) vault.read(myProject/kv/key_1): vault.read(myProject/kv/key_1): Error making API request.

URL: GET https://REDACTED/v1/sys/internal/ui/mounts/myProject/kv/key_1
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "myProject/kvkey_1/" (retry attempt 1 after "250ms")
```

### Expected behavior

Consul template should have successfully processed both the non-hierarchical `myProject_kv/key_1` and the hierarchical `myProject/kv/key_1`.

### Actual behavior

When processing the hierarchical `myProject/kv/key_1`, Consul template reported an error (authZ error due to an incorrect path, see debug error above).

### Steps to reproduce

Set up Vault like so:

Failing example
```
$ vault secrets enable \
    -path=/myProject/kv \
    --version=1 \
    -description="K/V v1 engine for my project (hierarchical)" \
    kv
```
Working example:
```
$ vault secrets enable \
    -path=/myProject_kv \
    --version=1 \
    -description="K/V v1 engine for my project (non-hierarchical)" \
    kv
```
Policies:
```
$ cat > myProject.hcl << EOF
# List, create, update, and delete values in the k/v engines
path "/myProject/kv/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}

path "/myProject_kv/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}

EOF

$ vault policy write myProject myProject.hcl

```

Assign the policies, and verify with the vault client that access to the engines works as expected:

```
$ vault write /myProject/kv/key_1 \
    ttl=5m \
    field_11=value_11 \
    field_12=value_12 \
    field_13=value_13
Success! Data written to: myProject/kv/key_1

$ vault read /myProject/kv/key_1
Key                 Value
---                 -----
refresh_interval    5m
field_11            value_11
field_12            value_12
field_13            value_13
ttl                 5m

$ vault write /myProject_kv/key_1 \
    ttl=5m \
    field_11=value_11B \
    field_12=value_12B \
    field_13=value_13B
Success! Data written to: myProject_kv/key_1

$ vault read /myProject_kv/key_1
Key                 Value
---                 -----
refresh_interval    5m
field_11            value_11B
field_12            value_12B
field_13            value_13B
ttl                 5m
```

**Comment by eikenb** [comment]
Hey @mbeiter, thanks for the report.

Would you mind either providing the contents of the config file (myProject.hcl) or a consul-template command line call that doesn't rely on a config file. Thanks.

**Comment by mbeiter** [comment]
@eikenb Here you go: https://gist.github.com/mbeiter/8b9945e316680b4c59fa41ce73dc3339

Thanks for looking into this.

**Comment by eikenb** [comment]
Thanks for posting that, though right after you responded I realized it wasn't working because I just forgot to issue/use a token. :P 

I'm still getting up to speed on these tools. Sorry for the bother.

**Comment by mbeiter** [comment]
No worries! Please let me know if you need help / additional information to reproduce. This is a pretty hot issue for me.

**Comment by eikenb** [comment]
Which version of vault are you using? I'm not able to reproduce this with Vault 1.1.2.

Here's what I used. First the templates...

```
[~]cat heir.ctmpl
field11={{ with secret "/myProject/kv/key_1" }}{{ .Data.field_11 }}{{ end }}
[~]cat flat.ctmpl
field11={{ with secret "/myProject_kv/key_1" }}{{ .Data.field_11 }}{{ end }}
```

Here's my shell script to quickly reproduce it w/ the environment variable VAULT_TOKEN set.

```
#!/bin/sh

### vault setup
if ! vault secrets list | grep -q 'myProject/kv'
then
    vault secrets enable \
        -path=/myProject/kv \
        --version=1 \
        -description="K/V v1 engine for my project (hierarchical)" \
        kv
fi

if ! vault secrets list | grep -q 'myProject_kv'
then
vault secrets enable \
    -path=/myProject_kv \
    --version=1 \
    -description="K/V v1 engine for my project (non-hierarchical)" \
    kv
fi

vault policy write myProject - << EOF
path "/myProject/kv/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
path "/myProject_kv/*"
{
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
EOF

vault write /myProject/kv/key_1 field_11=foo field12=zed
vault write /myProject_kv/key_1 field_11=bar field12=zed
### setup done
echo
printf 'flat: '
consul-template -template=flat.ctmpl:out:cat\ out -once
printf 'heir: '
consul-template -template=heir.ctmpl:out:cat\ out  -once
```

**Comment by eikenb** [comment]
Just updated to Vault 1.1.3 (noticed I was behind) and still not able to reproduce.

**Comment by mbeiter** [comment]
Vault 1.1.3 is what I am using as well. I will try out the setup you have
with this shellscript tonight.

**Comment by eikenb** [comment]
Great. Let me know if you see anything I did that is different. Note that this is just a test setup on my laptop running the vault in dev mode and a token set in the environment...

`vault server -dev -log-level=warn`

**Comment by mbeiter** [comment]
I ran your shellscript, and got the same error:

```
Success! Uploaded policy: myproject
Success! Data written to: myProject/kv/key_1
Success! Data written to: myProject_kv/key_1

flat: field11=bar

heir: 2019/06/27 00:43:28.113324 [WARN] (view) vault.read(myProject/kv/key_1): vault.read(myProject/kv/key_1): Error making API request.

URL: GET https://REDACTED:xxxx/v1/sys/internal/ui/mounts/myProject/kv/key_1
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "myProject/kvkey_1/" (retry attempt 1 after "250ms")
```
Notice the slash is missing in the error message - that was the same I saw in my original attempt: `myProject/kvkey_1/`

**Comment by mbeiter** [comment]
I did an http trace, and it seems as if the `vault` CLI client uses a different http endpoint than `consul-template`:

**Vault CLI**

```
GET https://REDACTED:xxxx/v1/myProject/kv/key_1 HTTP/2.0
← 200 application/json 194b 268ms
```
This looks correct, and is also what the policy is made out to allow.

**Consul Template**

```
GET https://REDACTED:xxxx/v1/sys/internal/ui/mounts/myProject/kv/key_1
← 403 Forbidden application/json 132b 355ms
```
The error message with the mangled path actually comes from the Vault server, not from the client. It is part of the HTTP response:

```
{
    "errors": [
        "preflight capability check returned 403, please ensure client's policies grant access to path \"myProject/kvkey_1/\""
    ]
}
```

It may be possible that your example worked for you because you may have used the Vault root token, which gives access to this different path (or anything under `sys` FWIW).


From the documentation for this [endpoint](https://www.vaultproject.io/api/system/internal-ui-mounts.html):

> Due to the nature of its intended usage, there is no guarantee on backwards compatibility for this endpoint.

Maybe the issue is caused by Consul Template using a different path to access the secret engine than what the `vault` CLI is using? Quite possible that this access pattern may have worked at some point, but that an update in vault changed this (as there is not necessarily backwards compatibility maintained on the endpoint that Consul Template is using)?

One way or another, it seems to me that Consul Template should use the same endpoints as what the CLI is using, as all the policies are written that way (i.e. it seems odd to write different policies to enable functional access for Consul Template to the same endpoints that the REST client / `vault` client have access to).

**Comment by eikenb** [comment]
@mbeiter, sorry for the delay. Got busy working on other things.

I'm using a token created using the root token, like so...
```
curl -i --request POST -H 'Content-Type: application/json' \
    -H "X-Vault-Token: $ROOT_TOKEN_ID" \
    -d '{"id":"b_token","renewable":"true","ttl":"200m"}' \
    http://localhost:8200/v1/auth/token/create

export VAULT_TOKEN=b_token
```

How are you creating your token? It seems like it must have to do with that as everything else seems to be the same between our 2 environments.

Thanks.

**Comment by eikenb** [comment]
> GET https://REDACTED:xxxx/v1/sys/internal/ui/mounts/myProject/kv/key_1

That URL is not used to get the value for that key, it is used in a call to determine if the KV secrets store is version 1 or 2.

I'm not finding an obvious place where it would be stripping out that slash in either the consul-template code or the vault code. I'm going to start reading more about Vault's permissions to see if I can figure out how your token might be setup that is different from mine.

**Comment by eikenb** [comment]
So I thought maybe I needed to use that policy. So I updated my script to create a new token with the policy. Ie. (this is right after the vault policy write.. call)
```
if ! vault token lookup test_token > /dev/null 2>&1
then
    vault token create -id test_token -policy=myProject -ttl 20m \
        > /dev/null 2>&1
fi
export VAULT_TOKEN=test_token
```
Unfortunately it made no difference and the templates still both render fine.

**Comment by eikenb** [comment]
I double checked, and that new token doesn't have the root policy.
```
$ vault token lookup test_token 
Key                  Value
---                  -----
[...]
policies             [default myproject]
renewable            true
ttl                  18m7s
type                 service

**Comment by eikenb** [comment]
I updated my original comment with the script I'm running to set/use the test_token.

**Comment by eikenb** [comment]
I don't really think it is an permissions/access issue now. That endpoint used for the kv version detection, sys/internal/ui/mounts, is documented as unauthorized and in testing no permissions settings had any affect on it. I believe the 403 is strictly the result of the path being wrong (missing the `/` in `kvkey_1`).

The only way I've been able to reproduce the issue is by just making that path wrong in my template. As that is obviously not what's happening on your end, I'm going to try to see what I can do to help you figure out what's going on in your case. I'm going to walk through the code one more time to identify every place where something could change that path so you might be able to track down what is doing this.

**Comment by eikenb** [comment]
I've tracked down the places where the path is manipulated in the consul-template code. But before going into that you should first check that the problem is in the consul-template code by checking the path just before the call that produces the error.

To do that print out the value of path right before the request to vault... (before this)...
https://github.com/hashicorp/consul-template/blob/09f01db9793d142864fab7bed5251b5ebc0a54b3/dependency/vault_common.go#L216-L217

If the path is messed up there, then you can start poking the places where it manipulates that path/string...

This is where it first reads in the value from the template..
https://github.com/hashicorp/consul-template/blob/09f01db9793d142864fab7bed5251b5ebc0a54b3/template/funcs.go#L292

Just doing some trimming here...
https://github.com/hashicorp/consul-template/blob/09f01db9793d142864fab7bed5251b5ebc0a54b3/dependency/vault_read.go#L35-L36

Here is where it calls url.Parse on it (print secretURL.Path)...
https://github.com/hashicorp/consul-template/blob/09f01db9793d142864fab7bed5251b5ebc0a54b3/dependency/vault_read.go#L41

If, on the other hand, it is fine there that means the problem is somewhere over in the vault code. I'll trace through that after you've verified it isn't in the consul-template code.

Thanks.

**Comment by mbeiter** [comment]
Thank you @eikenb for the detailed investigation. I will try this out on my end. 

The endpoint being supposedly unauthenticated gives me some ideas where else to look - I will try a few raw requests (the ones I intercepted earlier) with postman to rule out any possible server issues, and then go back to consul-template from there.

**Comment by eikenb** [comment]
Great! Look forward to hearing what you find.

**Comment by eikenb** [comment]
@mbeiter .. Any update on this?

**Comment by mbeiter-nv** [comment]
@eikenb I deployed today with 0.2.3, and I can no longer reproduce the issue. 

Please feel free to close, and thanks for looking into this.

**Comment by eikenb** [comment]
Great to hear that it is resolved! Thanks for following up.
