### ISSUE TITLE
Consul Template Release SHA256 validation fails for 0.21.0

### ISSUE THREAD

**Issue by stefreak** [hashicorp/consul-template#1248]
### Consul Template version

template_0.21.0_linux_amd64

### Command

```shell
$ shasum -a 256 Downloads/consul-template_0.21.0_linux_amd64.zip
c95085ab94c19442a2cbd0edc36f42b4b5f3af7bf2ab156361a8b368c45049c8  Downloads/consul-template_0.21.0_linux_amd64.zip
$ curl https://releases.hashicorp.com/consul-template/0.21.0/consul-template_0.21.0_SHA256SUMS \
    | grep c95085ab94c19442a2cbd0edc36f42b4b5f3af7bf2ab156361a8b368c45049c8
$ echo $?
1
```

### Expected behavior

I expect to find the SHA256 hash of the release zip file in the SHA256SUMS file.

### Actual behavior

The hash is wrong and cannot be found in the SHA256SUMS file.

### Steps to reproduce

See `command` section

### References

Did not find existing issues.

**Comment by eikenb** [comment]
This was a temporary issue with our CDN caching old versions of the files. It has been resolved.

**Comment by stefreak** [comment]
@eikenb cool perfect!

**Comment by eikenb** [comment]
@stefreak .. Thanks for reporting it.

I was in a hurry yesterday and forgot to say that. :)
