### ISSUE TITLE
How to handle "No path to datacenter" correctly?

### ISSUE THREAD

**Issue by ole-lukoe** [hashicorp/consul-template#1250]
### Consul Template version

```
consul-template v0.21.0 (05c6b65)
```

### Configuration

test.tpl file:
```liquid
{{ range $dc := datacenters }}
    {{ with $svc := service (printf "my-service@%s" $dc) }}
        {{ range $svc }}
            {{ .Address }}:{{ .Port }}
        {{ end }}
    {{ end }}
{{ end }}
```

### Command

```shell
consul-template -once -dry -template test.tpl
```

### Actual behavior

It works as expected. We are using this way to find services over all the datacenters we have.
But once we removed DC or DC became unavailable, Consul will list downgraded datacenters for 72 hours and all the templates across nomad jobs will be failed.

It can be simply reproduced if you will try to access nonexistent datacenter.

```liquid
{{ with $svc := service "consul@dcdcdcdccdcdcd" }}
    {{ range $svc }}
        {{ .Address }}:{{ .Port }}
    {{ end }}
{{ end }}
```

Both cases fails with similar reasons:

```
2019/08/07 16:21:43.004031 [WARN] (view) health.service(consul@dcdcdcdccdcdcd|passing): Unexpected response code: 500 (No path to datacenter) (retry attempt 2 after "500ms")
2019/08/07 16:21:43.556007 [WARN] (view) health.service(consul@dcdcdcdccdcdcd|passing): Unexpected response code: 500 (No path to datacenter) (retry attempt 3 after "1s")
2019/08/07 16:21:44.601870 [WARN] (view) health.service(consul@dcdcdcdccdcdcd|passing): Unexpected response code: 500 (No path to datacenter) (retry attempt 4 after "2s")
2019/08/07 16:21:46.654765 [WARN] (view) health.service(consul@dcdcdcdccdcdcd|passing): Unexpected response code: 500 (No path to datacenter) (retry attempt 5 after "4s")
```

### Expected behavior

Do you know, is this possible to handle this unwanted behavior correctly? 

We can have a list of desired datacenters and iterate over them in template.
This will resolve removing dc scenario but will not help when one of listed datacenters will be downgraded for a large preiod of time.

**Comment by pierresouchay** [comment]
No AFAIK, you might have a look and vote for https://github.com/hashicorp/consul/issues/5881

**Comment by eikenb** [comment]
Hey @ole-lukoe, thanks for the report.

Seems like the desired behavior here would be to render the template with the datacenters that respond as healthy, skipping those that don't. But instead it is.. what.. never rendering the template and just spitting out those warnings in the log?

**Comment by pierresouchay** [comment]
@eikenb this is a bit tricky, you might want to render it in some cases, while not performing rendering in some other cases. Hence a way to force removing DC at consul level as explained here https://github.com/hashicorp/consul/issues/5881 seems to me like the correct solution

**Comment by eikenb** [comment]
Hi @pierresouchay, good to hear from you. 

If I may ask, would you mind giving a quick example of why you wouldn't want it to render the template? I don't mean to impose, you just seem to have a lot of experience with this and I'm still coming up to speed on the use cases. If you don't have time, please disregard.

Thanks.

**Comment by pierresouchay** [comment]
Example: I am generating a prometheus template to alert me when ratio of healthy instances of an app goes below 50% across several DCs (real world case). If my current DC cannot connect to other DCs, I might want to be alerted, not having 100% on my current DC.
it really depends of use-case, thus, in our case (while we use more consul-templaterb than consul-template, we face the same issue), we use a the local KV to decide whether we should blacklist some DCs when DCs are down, but those errors are considered errors, until blacklisted as non-errors explicitly by an operator.
Having a way to decide at Consul level whether this is normal (for instance while decommissioning a DC or when we know a link is down and took appropriate ddecisions) or not would be helpful I think.

**Comment by eikenb** [comment]
I guess the question is then whether the current behavior is the best default. If so, then we can just resolve this issue. Otherwise we should try to define it.

@ole-lukoe, @pierresouchay, anyone else.. what do you think? Is the current behavior the a good default or can you propose something better?

**Comment by pierresouchay** [comment]
The issue lies in the fact it is not possible whether an error (regarding DCs) exists or is a temporary error (for most endpoints).

According to me, we should be able to distinguish both: tempError (when DC is present in Wan clusters) or 404 (no such DC...) it would help quite a bit

**Comment by ole-lukoe** [comment]
@eikenb @pierresouchay pie Thank you for your answers. 

As for me, I don't think hiding logs is a good, but I would like to have ability to "render the template with the datacenters that respond as healthy" as you said. I appreciate hashicorp/consul#5881 intentions, but does it help me when datacenter is completely down? It will try to re-render template and will fail entire Nomad job. 5 minutes of DC downtime it is quite enough. Even if I'm iterate over pre-defined list of datacenters and one of them goes down it will return 500 and fail entire job. Ok, I will struggle for DC availability but should my services die from it? May be It can be covered by {{ else }} operator or datacenter|healthy filter.

**Comment by eikenb** [comment]
Sounds like this has ended up being a feature request for the ability to filter datacenters on their "health". Unfortunately, at this point, the consul API doesn't support this. You can try submitting an issue with Consul for them to add the feature and if they do them we might be able to do something here. But until then there is nothing to be done in consul-template.

I have heard they are working on something related to https://github.com/hashicorp/consul/issues/5881, not sure about a timeline for it however. But once that is out you will at least be able to mitigate the issue when it comes up and possibly automate something if it is a frequent enough of an issue.

**Comment by eikenb** [comment]
As this is currently impossible, I'm going to close it. If Consul does eventually add a datacenter health filtering feature please re-submit a new issue for this.

Thanks.
