### ISSUE TITLE
Template function 'service' break in v0.20.0

### ISSUE THREAD

**Issue by rcarre** [hashicorp/consul-template#1263]
Hi all,
moving from 0.12 to 0.20. Then neither old format `{{service "webcomws" "passing, warning, critical, maintenance" }}` nor new format `{{service "webcomws" "|passing, warning, critical, maintenance" }}` are running properly.

Single health check status filter like "passing" or "warning" is still ok

### Debug output for each try:

> 2019/08/21 13:43:28.807394 [ERR] (cli) /opt/application/webcom-server/conf/application.conf.tmpl: execute: template: :16:42: executing "" at <service "webcomws" "...>: error calling service: health.service: invalid format: "webcomws|passing, warning"

> 2019/08/21 13:44:25.576053 [ERR] (cli) /opt/application/webcom-server/conf/application.conf.tmpl: execute: template: :16:42: executing "" at <service "webcomws" "...>: error calling service: health.service: invalid format: "webcomws||passing, warning"

**Comment by eikenb** [comment]
Hey @rcarre, thanks for the issue report.

Your example doesn't line up with the docs, have you tried ... (note there is only one set of quotes around the entire field).

`{{service "webcomws|passing, warning, critical, maintenance" }}`

Just want to make sure that isn't the problem. Thanks.

**Comment by eikenb** [comment]
Related? https://github.com/hashicorp/consul-template/issues/857

**Comment by rcarre** [comment]
Hey @eikenb,
my mistake ... I was not checking the correct version for doc.
Thx.

**Comment by eikenb** [comment]
@rcarre Does this mean you have it working and I can close this issue?

**Comment by eikenb** [comment]
@rcarre NM. I think it is pretty clear you do have it working based on what you said. So I'm going to go ahead and close this issue.
