### ISSUE TITLE
Merge multiple consul-template results in a single file

### ISSUE THREAD

**Issue by dibyajyotiron** [hashicorp/consul-template#1273]
# Consul Template version - 0.21.2

### Configuration

```tpl
Let's say I've two tpl files for two templates.
therm-staging-template.tpl -> {{ key "/therm/staging" }}
common-staging-template.tpl -> {{ key "/common/staging" }}
```
### Command
I'm running both these commands in two different shells.
```shell
consul-template -consul-token=$token_therm -template "therm-staging-template.tpl:stage.json"
consul-template -consul-token=$token_therm -template "common-staging-template.tpl:stage.json"
```
You can see that I've provided the same file to be updated in both the template commands.
### Debug output
I can see the file to be updated only takes the first template command's output that I run.
### Expected behavior
I want to be able to concatenate the results of the two template commands in the staging.json file.
### Actual behavior
 I'm running two template commands, whichever I run first, values from that kv store only gets written to the staging file.
What actually happened?

### Steps to reproduce

1. create ```therm-staging-template.tpl``` with ```{{ key "/therm/staging" }}``` and ```common-staging-template.tpl``` with ```{{ key "/common/staging" }}```
2. add the keys in your kv store
3. run ```consul-template -consul-token=$token_therm -template "common-staging-template.tpl:stage.json"``` & ```consul-template -consul-token=$token_therm -template "common-staging-template.tpl:stage.json"``` in two different shells or tmux sessions.

**Comment by pierresouchay** [comment]
This hardly make sense, how is consul-template supposed to guess it has to concatenate files? Besides that, in which order?

You can do this by:
1. output common-staging-template.tpl => stage1.json
2. output therm-staging-template.tpl => stage2.json
3. run a command on each change on one of them and concatenate with a script of your own.

OR:

Even easier: concatenate your *.tpl files at startup and output to a single file...

**Comment by eikenb** [comment]
Hey @dibyajyotiron,

@pierresouchay nailed it, that you basically want to either just have 1 template with both values or use a command to concat the 2 files. For the latter, here is a simple example of a config which could do this... 

```
template {
  source = "one.tmpl"
  destination = "one.out"
  command = "sh -c 'if test -e one.out -a -e two.out; then cat one.out two.out > both; fi'"
}

template {
  source = "two.tmpl"
  destination = "two.out"
  command = "sh -c 'if test -e one.out -a -e two.out; then cat one.out two.out > both; fi'"
}
```
Though it would probably be better to put the command in a shell script to eliminate the duplication. You want to command on both as either one could be re-rendered.
 
Hope this helps.

**Comment by dibyajyotiron** [comment]
Okay great, thanks, I'm using 1 template with both values and restarting my server when the output file changes.
