### ISSUE TITLE
Fix `secret` and `secrets` documentation for KVv2

### ISSUE THREAD

**Issue by eikenb** [hashicorp/consul-template#1274]
Both `secret` and `secrets` have different paths for KVv2. The documentation doesn't mention this... fix that.

References:
secret
- https://www.vaultproject.io/api/secret/kv/kv-v1.html#read-secret
- https://www.vaultproject.io/api/secret/kv/kv-v2.html#read-secret-version

secrets
- https://www.vaultproject.io/api/secret/kv/kv-v1.html#list-secrets
- https://www.vaultproject.io/api/secret/kv/kv-v2.html#list-secrets

**Comment by iyurev** [comment]
I spent  almost ~2 hours to resolve  this trouble .
