### ISSUE TITLE
Is services API functions get only services that have status passing ?

### ISSUE THREAD

**Issue by abhip** [hashicorp/consul-template#1291]
### Consul Template version

consul-template v0.18.1 (9c62737)

### Configuration
consul-template/templates/services.ctmpl
```{{ range services }}{{ .Name }}
{{ end }}```

consul-template/config.d/service-list.json
```
template {
	source = "/usr/local/consul-template/templates/services.ctmpl"
	destination = "/haproxy/servicelist.lst"
	command = " /bin/bash -c 'test.sh' "
	perms = 0664
    	wait = "3s:5s"
}
### Expected behavior

What should have happened?

the servicelist.lst should not be updating/changing whenever services status change to fail.

### Actual behavior

What actually happened?

the servicelist.lst is getting updating as services status change to fail

**Comment by eikenb** [comment]
Hey @abhip,

You didn't include most of your template. Could you either add that as a comment or to the original issue (if you can edit it).

Thanks.

**Comment by abhip** [comment]
@eikenb 

Here complete template 

```
{{ range services }}{{ .Name }}
{{ end }}
```
I have only that in my template

**Comment by abhip** [comment]
```
template {
	source = "/usr/local/consul-template/templates/whitelist.lst.ctmpl"
	destination = "/usr/local/haproxy/whitelist.lst"
	command = "/bin/bash -c '/usr/local/haproxy/haproxy -D -f /usr/local/haproxy/config/haproxy.conf -q -p /var/run/haproxy.pid -sf $( cat /var/run/haproxy.pid ) &'"
	perms = 0664
	wait = "4s:6s"
}
```

This is my config file.

When we do ls -ltr whitelist.ls , it keeps updating every 3-4min.

**Comment by eikenb** [comment]
@abhip, thanks for getting back to me.

I wanted to see your template as I thought maybe you were talking about the `service` call, as it only returns healthy nodes. The `services` call returns all registered services along with their tags. It doesn't care if there are any healthy nodes or not, just what is registered. For you to be seeing a change in the `services` output would mean you have something registering and deregistering those services.
