### ISSUE TITLE
Install consul-template.exe as a Windows service

### ISSUE THREAD

**Issue by kchan2011** [hashicorp/consul-template#1305]
Please note that the Consul Template issue tracker is reserved
for bug reports and enhancements. For general usage questions,
please use the Consul Community Portal or the Consul mailing list:

    https://discuss.hashicorp.com/c/consul
    https://groups.google.com/forum/#!forum/consul-tool

Please try to simplify the issue as much as possible and include all the
details to replicate it. The shorter and simpler the bug is to reproduce the
quicker it can be addressed. Thanks.

### Consul Template version

consul-template v0.22.0 (6cae10fe)

### Configuration

```hcl
# Copy-paste your configuration files here. Only include what is necessary or
# what you've changed from defaults. Include all referenced configurations.

```

```liquid
# Copy-paste your Consul Template template here
# Config.njprod.tpl

Lock_serverHost = "lockserver-njmaster"
Lock_serverHost = "{{ key "/cmdev/prod/prism/config/Lock_serverHost" }}"


```liquid
# Include sample data you reference in the template from Consul or Vault here.
![image](https://user-images.githubusercontent.com/24794854/68393725-9a7f8200-013a-11ea-99d6-69392f673061.png)

### Command
na

```shell
# Place your Consul Template command here
na

### Debug output

Provide a link to a GitHub Gist containing the complete debug
output by running with `-log-level=trace`.

### Expected behavior

What should have happened?

Able to run the following consul-template in CLI:

C:\apps\consul-template.exe -consul-addr=http://ci:8500 -template C:\apps\config\Config.njprod.tpl:C:\apps\config\Config.njprod.1"

Installed Consul-template as a Windows service on a Windows 10, consul-template using the following SC command but the service fail to start.

SC create "Consul-template" start= demand displayname= "Consul-template" binpath= "C:\apps\consul-template.exe -consul-addr=http://ci:8500 -template C:\apps\config\Config.njprod.tpl:C:\apps\config\Config.njprod.1"

### Actual behavior

What actually happened?


### Steps to reproduce

1.  Run a cmd session with admininstrator
2.  SC create "Consul-template" start= demand displayname= "Consul-template" binpath= "C:\apps\consul-template.exe -consul-addr=http://ci:8500 -template C:\apps\config\Config.njprod.tpl:C:\apps\config\Config.njprod.1"

3.  NET start "Consul-template" and fail to start with the following error msg

The service is not responding to the control function.

More help is available by typing NET HELPMSG 2186.


Are there any other GitHub issues (open or closed) that should
be linked here? For example:
- GH-1234
- ...

**Comment by eikenb** [comment]
DHey @kchan2011, thanks for report.

Were you able to run it from the command prompt? If so, did it work or did you get some error output? I'm not sure I see what the bug is you are reporting.

If you are instead having issues getting it to run as a window service that you'd like to have help with, you'd be better served by asking that on one of the consul community channels [1]. I have no experience trying to run consul-template as a windows servers and will not be able to help.

https://github.com/hashicorp/consul-template#community-support

**Comment by kchan2011** [comment]
Thank you for replying.  I'm able to run it from a Windows cmd session.   It turned out Windows native c:\windows\system\sc.exe doesn't install the consul-template correctly as a Windows service.  I need to use the nssm.exe to install as a Windows service, e.g.  nssm.exe install consul-template, and is working as expected with consul KV store.
