### ISSUE TITLE
runTemplate - DEBUG logging is needed to identify missing dependencies

### ISSUE THREAD

**Issue by domelz** [hashicorp/consul-template#1308]
github.com/hashicorp/consul-template/manager/runner.go's runTemplate function waits until there are no missing dependencies before executing the template, but does not identify which dependencies are missing.

Adding DEBUG print statements would allow one to identify which dependencies are missing that are preventing a template from being executed.

### Consul Template version

consul-template v0.22.1 (46ddb478)

### Expected behavior

Additional DEBUG logging would enable missing dependencies to be identified.

### Actual behavior

Existing DEBUG logging states that there are missing dependencies, but does not identify them.

**Comment by eikenb** [comment]
Merging #1309 fixed this.
