### ISSUE TITLE
README - Contributing section incorrectly says "Envconsul" instead of "consul-template"

### ISSUE THREAD

**Issue by domelz** [hashicorp/consul-template#1310]
The [README.md]("To build and install Envconsul locally, you will need to install Go.") document's Contributing section incorrectly says "To build and install Envconsul locally, you will need to install Go."

It should say "consul-template" instead of "Envconsul".

### Consul Template version

consul-template v0.22.1 (46ddb478)

### Expected behavior

What should have happened?

The README.md  should say "To build and install consul-template locally, you will need to install Go."

### Actual behavior

The README.md  incorrectly says "To build and install Envconsul locally, you will need to install Go."

**Comment by eikenb** [comment]
Thanks for the report @domelz. Looks like I did that back when I was reworking both projects guides to bring them more in line with each other... looks like I went a bit to far. :)
