### ISSUE TITLE
String functions: hasPrefix, hasSuffix, etc

### ISSUE THREAD

**Issue by aclowkey** [hashicorp/consul-template#1316]
How about adding some string functions such as hasPrefix, hasSuffix, regexp.Match?
EDIT: Oh I see there's regexp.Match() which should cover all other cases.
But maybe it's still worth to add these simple ones as most programming languages have them without regexes..?

**Comment by blake** [comment]
Support for sprig functions was added in #1312 and made available in consul-template version 0.28.0.

The Sprig library has `hasPrefix` and `hasSuffix` functions that can be used within Consul template by prefixing the function name with `sprig_`. E.g., `sprig_hasPrefix` and `sprig_hasSuffix`.
