### ISSUE TITLE
Mismatch between documentation and implementation for default `exec-kill-signal`

### ISSUE THREAD

**Issue by fubhy** [hashicorp/consul-template#1319]
### Expected behavior

The documented default value for `exec-kill-signal` should match the actual default value.

### Actual behavior

In the documentation, the default `exec-kill-signal` is described as `SIGTERM` but the actual default value is `SIGINT`.

Imho, `SIGTERM` would be the correct and preferable default value but since that would be a breaking change I only adapted the documentation for now. Whether you want to make the breaking change and actually switch to `SIGTERM` is up to the maintainers to decide ;-).

### References

Pull request: https://github.com/hashicorp/consul-template/pulls
Current default value: https://github.com/hashicorp/consul-template/blob/4da01d456ba166d145a86b57d37f3f1f0482015c/config/exec.go#L13

**Comment by eikenb** [comment]
Hey @fubhy, noticed this after already merging your PR that fixed this. Thanks for reporting it and fixing it.

This was fixed by PR #1318
