### ISSUE TITLE
fatal error: PowerRegisterSuspendResumeNotification failure on windows container

### ISSUE THREAD

**Issue by ericstu** [hashicorp/consul-template#1335]
Please note that the Consul Template issue tracker is reserved
for bug reports and enhancements. For general usage questions,
please use the Consul Community Portal or the Consul mailing list:

    https://discuss.hashicorp.com/c/consul
    https://groups.google.com/forum/#!forum/consul-tool

Please try to simplify the issue as much as possible and include all the
details to replicate it. The shorter and simpler the bug is to reproduce the
quicker it can be addressed. Thanks.

### Consul Template version

Run `consul-template -v` to show the version. If you are not
running the latest version, please upgrade before submitting an
issue.
 
consul-template v0.23.0 (5cf9d687)
consul-template v0.24.0 (36bc20c9)

### Command

```shell
consul-template.exe -v
```

### Debug output

Provide a link to a GitHub Gist containing the complete debug
output by running with `-log-level=trace`.

### Expected behavior

What should have happened?

show consul-template v0.24.0

### Actual behavior

What actually happened?

C:\consul-template>consul-template.exe -v
fatal error: PowerRegisterSuspendResumeNotification failure

runtime stack:
runtime.throw(0xa02ebb, 0x2e)
        /usr/local/go/src/runtime/panic.go:774 +0x79 fp=0x103fde0 sp=0x103fdb0 pc=0x430d59
runtime.monitorSuspendResume()
        /usr/local/go/src/runtime/os_windows.go:294 +0x1a9 fp=0x103fe80 sp=0x103fde0 pc=0x42d2a9
runtime.goenvs()
        /usr/local/go/src/runtime/os_windows.go:531 +0x1ba fp=0x103fed8 sp=0x103fe80 pc=0x42dc2a
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:554 +0xa9 fp=0x103ff30 sp=0x103fed8 pc=0x433759
runtime.rt0_go(0x103ff60, 0x7ffe4f90cedf, 0x103ff60, 0x0, 0x7ffe4f90cedf, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/asm_amd64.s:214 +0x13d fp=0x103ff38 sp=0x103ff30 pc=0x45991d

### References

Are there any other GitHub issues (open or closed) that should
be linked here? For example:
- Maybe the same as https://github.com/containous/traefik/issues/5968

**Comment by eikenb** [comment]
This is a general Go issue; https://github.com/golang/go/issues/35447

It has been fixed in 1.13.6; https://github.com/golang/go/issues/35746

I'll close this ticket as soon as I get a chance to rebuild the docker images.

**Comment by eikenb** [comment]
I've re-pushed the images after rebuilding them with go 1.13.6 which should fix this issue. Please let me know if this fixes it for you.

**Comment by ericstu** [comment]
> I've re-pushed the images after rebuilding them with go 1.13.6 which should fix this issue. Please let me know if this fixes it for you.

Can https://releases.hashicorp.com/consul-template/ also rebuild for this issue?

**Comment by eikenb** [comment]
I think I'll do a small release then. Due to our distribution setup uploading a new binary for the same release is a PITA... and this is technically a bug fix. I'll try to get it out ASAP.

**Comment by eikenb** [comment]
Pushed out 0.24.1 which fixes this (it's built with 1.13.6).

**Comment by ericstu** [comment]
Thank you for your help.
