### ISSUE TITLE
How to pass an environment variable to squid.conf

### ISSUE THREAD

**Issue by mihailemnaru** [hashicorp/consul-template#1345]
I have squid.conf.ctmpl with this value:

 {{ key "squid/auth/squid.conf" }}

Now, I need to pass env variable AUTH_PROXY_PORT to http_port from squid.conf

Can anyone help or at least point me in the right direction?

**Comment by mihailemnaru** [comment]
{{ key "squid/auth/squid.conf" }}

**Comment by pierresouchay** [comment]
The issue is not very clear... you might take more time to describe your problem. You want to output the value of ENV variable in the file?

if so, that's https://github.com/hashicorp/consul-template#env

**Comment by mihailemnaru** [comment]
> The issue is not very clear... you might take more time to describe your problem. You want to output the value of ENV variable in the file?
> 
> if so, that's https://github.com/hashicorp/consul-template#env

I have a consul template file squid.conf.ctmpl that contains {{ key "squid/auth/squid.conf" }}

From my understanding, this will render the contents of squid/auth/squid.conf which contains this line: http_port 3128 

I have an environment variable AUTH_PROXY_PORT which I want to pass to consul template in order to modify port 3128 with its value.

**Comment by pierresouchay** [comment]
I think you could try yourself and read documentation :-)

https://github.com/hashicorp/consul-template#replaceall

I would try (did not test):
```
{{ $repl := env "AUTH_PROXY_PORT"}}
{{ key "squid/auth/squid.conf" | replaceAll "3128" $repl }}
```

**Comment by mihailemnaru** [comment]
> I think you could try yourself and read documentation :-)
> 
> https://github.com/hashicorp/consul-template#replaceall
> 
> I would try (did not test):
> 
> ```
> {{ $repl := env "AUTH_PROXY_PORT"}}
> {{ key "squid/auth/squid.conf" | replaceAll "3128" $repl }}
> ```

it worked beautifully!!!

Thank you for your time and the help provided!!!!
