### ISSUE TITLE
Running tests creates ~/.vault-token file which changes future behavior

### ISSUE THREAD

**Issue by eikenb** [hashicorp/consul-template#1353]
It is a side effect of running vault. You can reproduce it by running `vault server -dev`.

Look into a way to disable this or add a cleanup method. Having it do this messes with manual testing if you forget about it (which I have).

**Comment by eikenb** [comment]
Found the option that disables it. I'm asking the vault people if there would be any unintended consequences of setting this in our integration tests so they'd stop creating that file.

```
  -dev-no-store-token
      Do not persist the dev root token to the token helper (usually the local
      filesystem) for use in future requests. The token will only be displayed
      in the command output. The default is false.
```

**Comment by eikenb** [comment]
Vault people confirmed no worries. We can disable it.

**Comment by eikenb** [comment]
@findkim I missed that you had assigned this to yourself. Sorry about that.

**Comment by findkim** [comment]
No worries! happy that it's resolved!
