### ISSUE TITLE
featue request: please oublish container images for arm64 on dockerhub

### ISSUE THREAD

**Issue by Josua-SR** [hashicorp/consul-template#1362]
### Description

I have started using Vault in a self-hosted baremetal kubernetes cluster.
For making existing applications aware of Vault I have started using consul-template in a custom startup script for populating configuration files and environment variables.

To that purpose I simply pull in the vault and consul-template binaries from dockerhub ... and this is the point where I would like to have arm64 docker images available like they are for vault itself.

Fyi here is a little Dockerfile to illustrate the user story:
```
ARG VAULT_IMAGE=vault:1.3.2
ARG DRONE_IMAGE=drone/drone:1.6.5
ARG CONSUL_IMAGE=hashicorp/consul-template:0.24.0-alpine

FROM ${VAULT_IMAGE} AS vault-bin
FROM ${CONSUL_IMAGE} AS consul-bin

FROM ${DRONE_IMAGE} AS run
COPY --from=vault-bin /bin/vault /bin/
COPY --from=consul-bin /bin/consul-template /bin/

RUN apk add net-tools strace curl wget

COPY init.sh /
ENTRYPOINT ["/bin/sh", "/init.sh"]
```

### Consul Template version

any (next)

### References

https://hub.docker.com/r/hashicorp/consul-template/tags

**Comment by thevilledev** [comment]
arm64 images have been available in Dockerhub since June 2021 or consul-template v0.26.0

**Comment by Josua-SR** [comment]
I stepped away and didn't play close attention. Looks like you're right and this feature has been completed :)
