### ISSUE TITLE
High CPU load on consul-template agent process when watching 119 dependencies.

### ISSUE THREAD

**Issue by KPiccoloDaimao** [hashicorp/consul-template#1365]
### Consul Template version
consul-template_0.24.1

### Problem Statement:
* High CPU load on consul-template agent process when watching 119 dependencies.
* Interval where dependencies are checked seems to be ocurring 

### Considerations:
* Vault secrets are retrieved every ttl / 3 is being done as per "sleeping for 51.693109968s" . According to https://www.vaultproject.io/docs/secrets/kv/kv-v1/ and https://github.com/hashicorp/consul-template/blob/master/dependency/vault_common.go
* Watching less dependencies retrieving all data at once and compile a single file using tree/explode might help, but separate files are required for each template so that doesn't work for my use case https://groups.google.com/forum/#!topic/consul-tool/XYsUsOBASsU https://github.com/hashicorp/consul-template#tree
* The wait quiescence timers only affect render to disk so that doesn't help with "in memory check interval" "the template will render in-memory, but then the result will not be written to disk (since it is unchanged)." https://github.com/hashicorp/consul-template/issues/994

### Debug output

There are hundreds of records such as this per second:
Apr 10 10:46:15 host consul-template[66666]: 2020/04/10 10:46:15.117178 [DEBUG] (runner) vault.read(kv/test/key) is still needed
Apr 10 10:46:15 host consul-template[66666]: (runner) vault.read(kv/test/key) is still needed
Apr 10 10:46:15 host consul-template[66666]: 2020/04/10 10:46:15.152993 [DEBUG] (runner) vault.read(kv/test/key) is still needed
Apr 10 10:46:15 host consul-template[66666]: (runner) vault.read(kv/test/key) is still needed
Apr 10 10:46:15 host consul-template[66666]: 2020/04/10 10:46:15.190610 [DEBUG] (runner) vault.read(kv/test/key) is still needed
Apr 10 10:46:15 host consul-template[66666]: (runner) vault.read(kv/test/key) is still needed
Apr 10 10:46:15 host consul-template[66666]: 2020/04/10 10:46:15.228896 [DEBUG] (runner) vault.read(kv/test/key) is still needed
Apr 10 10:46:15 host consul-template[66666]: (runner) vault.read(kv/test/key) is still needed
Apr 10 10:46:15 host consul-template[66666]: 2020/04/10 10:46:15.267128 [DEBUG] (runner) vault.read(kv/test/key) is still needed
Apr 10 10:46:15 host consul-template[66666]: (runner) vault.read(kv/test/key) is still needed

After "starting fetch" hundreds of records are generated for "checking template" following that:
Apr 10 10:45:59 host consul-template[66666]: (runner) watching 119 dependencies
Apr 10 10:45:59 host consul-template[66666]: (runner) all templates rendered
Apr 10 10:45:59 host consul-template[66666]: 2020/04/10 10:45:59.153200 [TRACE] (view) vault.read(kv/test/key) marking successful data response
Apr 10 10:45:59 host consul-template[66666]: 2020/04/10 10:45:59.153223 [TRACE] (view) vault.read(kv/test/key) successful contact, resetting retries
Apr 10 10:45:59 host consul-template[66666]: (view) vault.read(kv/test/key) marking successful data response
Apr 10 10:45:59 host consul-template[66666]: 2020/04/10 10:45:59.153231 [TRACE] (view) vault.read(kv/test/key) received data
Apr 10 10:45:59 host consul-template[66666]: 2020/04/10 10:45:59.153248 [TRACE] (view) vault.read(kv/test/key) starting fetch
Apr 10 10:45:59 host consul-template[66666]: 2020/04/10 10:45:59.153259 [DEBUG] (runner) checking template 5dc04d0f3b8aedcfaec45946ca688fbe
Apr 10 10:45:59 host consul-template[66666]: (view) vault.read(kv/test/key) successful contact, resetting retries
Apr 10 10:45:59 host consul-template[66666]: (view) vault.read(kv/test/key) received data
Apr 10 10:45:59 host consul-template[66666]: (view) vault.read(kv/test/key) starting fetch
Apr 10 10:45:59 host consul-template[66666]: (runner) checking template 5dc04d0f3b8aedcfaec45946ca688fbe
Apr 10 10:45:59 host consul-template[66666]: 2020/04/10 10:45:59.153365 [DEBUG] (runner) checking template b10d9df2a7b5de8d76fdae2f95e66a92
Apr 10 10:45:59 host consul-template[66666]: (runner) checking template b10d9df2a7b5de8d76fdae2f95e66a92
Apr 10 10:45:59 host consul-template[66666]: 2020/04/10 10:45:59.153260 [TRACE] vault.read(kv/test/key): secret is not renewable, sleeping for 51.693109968s
Apr 10 10:45:59 host consul-template[66666]: vault.read(kv/test/key): secret is not renewable, sleeping for 51.693109968s
Apr 10 10:45:59 host consul-template[66666]: 2020/04/10 10:45:59.153473 [DEBUG] (runner) checking template ba1d9ddc7774cd6bae3c60c28f4ecbc7
Apr 10 10:45:59 host consul-template[66666]: (runner) checking template ba1d9ddc7774cd6bae3c60c28f4ecbc7
Apr 10 10:45:59 host consul-template[66666]: 2020/04/10 10:45:59.153589 [DEBUG] (runner) checking template 1e970f9ad158ae4713ascb98168d0c1e
Apr 10 10:45:59 host consul-template[66666]: (runner) checking template 1e970f9ad158ae4713ascb98168d0c1e

### Expected behavior

Lower CPU utilization by increase the check intervals.

### Actual behavior

Checks are being performed hundreds of times per second increasing CPU load on consul-template agent process.

### Steps to reproduce

Watch more than 100 Vault dependencies.

**Comment by eikenb** [comment]
Hey @KPiccoloDaimao, thanks for taking the time to file the issue.

To be sure of my interpretation of what you're saying.. the log has it checking the same secret, over and over, 100s of times a second? The secret at "vault.read(kv/test/key)".

I  want to be sure that wasn't a placeholder you put in to hide the real ones or that you only included part of the log that had that one secret.

**Comment by KPiccoloDaimao** [comment]
Hi @eikenb, thanks for looking into this. That is absolutely correct, data was anonymized and that kv/test/key correspond to one of the 100s keys it is checking multiple times a second.

**Comment by eikenb** [comment]
Hey @KPiccoloDaimao, thanks for getting back to me with the additional info.

I think you are hitting a limitation of the current design. With 119 dependencies expiring and being fetched every 50 seconds, that means it refreshes a little over 2 dependencies a second. Whenever a dependency is fetched, it needs to re-render all templates (the `checking template ...` messages) and verify each dependency is still used (the `vault.read(...) is still needed` messages). To do these 2 things it re-evaluates each template, generating the text and tracking what is used while doing so. Then it compares the new text vs. the current text for updates and looks over the tracked dependencies for anything not in use anymore. I believe this is what is using the CPU time.

I think the best short term solution, if possible, is to increase the TTL on your secrets so it checks them less often than every 50 seconds.

Long term you could file a feature request to have consul-template be smarter about template and dependency checks. If it tracked template and dependency references and dependency tress it could only update things as needed.

**Comment by KPiccoloDaimao** [comment]
@eikenb that would perfectly explain the scenario. I considered extending TTL on most keys, but there is still one of them which has a 2sec TTL as it is used as a "healthcheck" to make sure the daemon is retrieving data from Vault. That 2sec TTL is probably causing all other templates to be rendered as you mentioned.
Even not considering that by increasing the TTL when dealing with hundreds of dependencies each one is fetched with 'sleep = sleep * (rand.Float64() + 1) / 2.0' https://github.com/hashicorp/consul-template/blob/master/dependency/vault_common.go so overtime there is a chance that randomness will cause high CPU again.
As a workaround I've used -once mode for the majority of dependencies and only leaving a few to be watched by the daemon.
It would be great to have this feature request implemented though.

**Comment by eikenb** [comment]
@KPiccoloDaimao .. I'm happy I was able to help explain what was going on and that you were able figure out a workaround. If you have time and interest to submit a separate feature request issue for the dependency/template check optimization that would be great. Thanks.
