### ISSUE TITLE
consul-template does not preserve user and group owners of existing destination file

### ISSUE THREAD

**Issue by jsfrerot** [hashicorp/consul-template#1379]
### Consul Template version
consul-template v0.25.0 (99efa642)

Opening new issue for same problem as 1061
### Command
```shell
# ls -al web-key.pem
-rw-rw---- 1 root cloud 1675 May 12 17:14 web-key.pem
# systemctl restart consul-template@web
# ls -al web-key.pem
-rw-rw---- 1 root root 1679 May 12 17:26 web-key.pem
```
### Expected behavior

What should have happened?
File shouldn't have changed ownership

### Actual behavior

What actually happened?
Ownership is replace with the user/group of the running service. In this case root/root

### Steps to reproduce
```shell
# ls -al web-key.pem
-rw-rw---- 1 root cloud 1675 May 12 17:14 web-key.pem
# systemctl restart consul-template@web
# ls -al web-key.pem
-rw-rw---- 1 root root 1679 May 12 17:26 web-key.pem
```

### References
- GH-1061

**Comment by eikenb** [comment]
Hey @jsfrerot, belated thanks for the report.

I cannot reproduce this. Eg. running this little script the GID of the file stays the same and I verified the code is updating both the group (gid) and user (uid) ownership of the file. This is on Linux. Though it should work on any *nix. It will not work on Windows.

To run, replace `[group]` with a group are a member of (or anything if you test with root).
`
#!/bin/sh

rm -f out

echo foo > out
chgrp [group] out

cat > in.tmpl << EOF
bar
EOF

stat out
echo "-----------------------------------------------------------------"
consul-template -template "in.tmpl:out" -exec "cat out" -once > /dev/null
stat out
`

**Comment by AlexeyDemidov** [comment]
It seems that the file ownership is being reset to `root:root` when there is `perms = ` present in `template {}` in the config file.

**Comment by eikenb** [comment]
Thanks @AlexeyDemidov, I was able to reproduce it with that additional information. I'm looking into it now.
