### ISSUE TITLE
Replace whitelist/blacklist terminology with allowlist/denylist

### ISSUE THREAD

**Issue by findkim** [hashicorp/consul-template#1387]
Update consul-template to use inclusive language, notably replacing the usage of whitelist/blacklist.

### Consul Template version
```
consul-template -v
 v0.25.0 ()
```

### Expected behavior
Configuration options for exec
```
exec {
  env {
    allowlist = []
    denylist = []
  }
}
```

### Actual behavior
```
exec {
  env {
    whitelist = []
    blacklist = []
  }
}
```

### References
- This mirrors Consul's efforts in https://github.com/hashicorp/consul/pull/7971
- Config documentation in [README.md](https://github.com/hashicorp/consul-template/blob/v0.25.0/README.md#configuration-file-format)

**Comment by eikenb** [comment]
Note we'll need to keep backwards compatibility whitelist/blacklist in the code for some time to come. But we can replace them in the docs and help.
