### ISSUE TITLE
Help understanding CONSUL_HTTP_SSL

### ISSUE THREAD

**Issue by gmr** [hashicorp/consul-template#1389]
I'm trying to understand where `CONSUL_HTTP_SSL` is parsed in the code base. It's probably PEBKAC, but the only references I can find are for the child environment.

I was hoping someone would be kind enough to point out what I'm obviously missing. I see ENV VAR parsing for `CONSUL_HTTP_ADDR`, `CONSUL_TOKEN` and others, but not `CONSUL_HTTP_SSL`.

Can someone please point me in the right direction?

**Comment by findkim** [comment]
Hi @gmr, it seems what you have described is accurate and not a PEBKAC! 

For Consul Template configuration, it supports the Consul address and token environment variables and requires SSL to be specified in a configuration file ([source](https://github.com/hashicorp/consul-template/blob/master/config/consul.go#L126)). Context of `CONSUL_HTTP_SSL` is scoped to child environments and not used for Consul Template connection with Consul.

If there is a follow up request, please feel free to open another issue to describe the behavior you expect or capture a feature request.

Best,
Kim

**Comment by gmr** [comment]
It's been my experience that setting `CONSUL_HTTP_SSL=1` will have consul-template connect to `CONSUL_HOST_ADDR`, where `consul.service.ENVIRONMENT.consul` using SSL on port 443. `CONSUL_HTTP_SSL=0` will have it connect to `CONSUL_HOST_ADDR` on port 80. Unless I am doing something wrong, it seems that it is respected, but for the life of me, I can't find where.

**Comment by eikenb** [comment]
@gmr .. A lot of the code for parsing those environment variables is in the Consul API client. So if you can't find it in consul-template you could check there. 

https://github.com/hashicorp/consul/tree/master/api
https://godoc.org/github.com/hashicorp/consul/api

**Comment by gmr** [comment]
Thanks @eikenb, didn't think to check there.

**Comment by findkim** [comment]
good call @eikenb!
