### ISSUE TITLE
cannot use custom environment variable in consul-template config

### ISSUE THREAD

**Issue by ericsonrumuy7** [hashicorp/consul-template#1390]
i'm trying to use custom environment variable in my config file :
exec {
  command = "echo ${TEST}"
  env {
    custom = ["TEST=123"]
  }
 }

template {
  source = "./test.conf"
  destination = "/etc/nginx.conf"
  perms       = 0644
  command     = "systemctl reload nginx"
}

output : 
2020/07/08 09:13:25.787582 [INFO] consul-template v0.25.0 (99efa642)
2020/07/08 09:13:25.787716 [INFO] (runner) creating new runner (dry: false, once: true)
2020/07/08 09:13:25.788188 [DEBUG] (runner) final config: {"Consul":{"Address":"","Namespace":"","Auth":{"Enabled":false,"Username":"","Password":""},"Retry":{"Attempts":12,"Backoff":250000000,"MaxBackoff":60000000000,"Enabled":true},"SSL":{"CaCert":"","CaPath":"","Cert":"","Enabled":false,"Key":"","ServerName":"","Verify":true},"Token":"","Transport":{"DialKeepAlive":30000000000,"DialTimeout":30000000000,"DisableKeepAlives":false,"IdleConnTimeout":90000000000,"MaxIdleConns":100,"MaxIdleConnsPerHost":2,"TLSHandshakeTimeout":10000000000}},"Dedup":{"Enabled":false,"MaxStale":2000000000,"Prefix":"consul-template/dedup/","TTL":15000000000,"BlockQueryWaitTime":60000000000},"DefaultDelims":{"Left":null,"Right":null},"Exec":{"Command":"echo ${TEST}","Enabled":true,"Env":{"Blacklist":[],"Custom":["TEST=123"],"Pristine":false,"Whitelist":[]},"KillSignal":2,"KillTimeout":30000000000,"ReloadSignal":null,"Splay":0,"Timeout":0},"KillSignal":2,"LogLevel":"trace","MaxStale":2000000000,"PidFile":"","ReloadSignal":1,"Syslog":{"Enabled":false,"Facility":"LOCAL0","Name":"consul-template"},"Templates":[{"Backup":false,"Command":"systemctl reload nginx","CommandTimeout":30000000000,"Contents":"","CreateDestDirs":true,"Destination":"/etc/nginx.conf","ErrMissingKey":false,"Exec":{"Command":"systemctl reload nginx","Enabled":true,"Env":{"Blacklist":[],"Custom":[],"Pristine":false,"Whitelist":[]},"KillSignal":2,"KillTimeout":30000000000,"ReloadSignal":null,"Splay":0,"Timeout":30000000000},"Perms":420,"Source":"./test.conf","Wait":{"Enabled":false,"Min":0,"Max":0},"LeftDelim":"","RightDelim":"","FunctionBlacklist":null,"SandboxPath":""}],"Vault":{"Address":"","Enabled":false,"Namespace":"","RenewToken":false,"Retry":{"Attempts":12,"Backoff":250000000,"MaxBackoff":60000000000,"Enabled":true},"SSL":{"CaCert":"","CaPath":"","Cert":"","Enabled":true,"Key":"","ServerName":"","Verify":true},"Transport":{"DialKeepAlive":30000000000,"DialTimeout":30000000000,"DisableKeepAlives":false,"IdleConnTimeout":90000000000,"MaxIdleConns":100,"MaxIdleConnsPerHost":2,"TLSHandshakeTimeout":10000000000},"UnwrapToken":false},"Wait":{"Enabled":false,"Min":null,"Max":null},"Once":true,"BlockQueryWaitTime":60000000000}
2020/07/08 09:13:25.788456 [INFO] (runner) creating watcher
2020/07/08 09:13:25.788872 [INFO] (runner) starting
2020/07/08 09:13:25.788932 [DEBUG] (runner) running initial templates
2020/07/08 09:13:25.788968 [DEBUG] (runner) initiating run
2020/07/08 09:13:25.789012 [DEBUG] (runner) checking template 907a468ab9989fe2904bc5f0f80f2c19
2020/07/08 09:13:25.789261 [DEBUG] (runner) rendering "./test.conf" => "/etc/nginx.conf"
2020/07/08 09:13:25.790607 [INFO] (runner) rendered "./test.conf" => "/etc/nginx.conf"
2020/07/08 09:13:25.790675 [DEBUG] (runner) appending command "systemctl reload nginx" from "./test.conf" => "/etc/nginx.conf"
2020/07/08 09:13:25.790713 [DEBUG] (runner) diffing and updating dependencies
2020/07/08 09:13:25.790761 [INFO] (runner) executing command "systemctl reload nginx" from "./test.conf" => "/etc/nginx.conf"
2020/07/08 09:13:25.790853 [INFO] (child) spawning: systemctl reload nginx
2020/07/08 09:13:25.821394 [DEBUG] (runner) watching 0 dependencies
2020/07/08 09:13:25.821616 [DEBUG] (runner) all templates rendered
2020/07/08 09:13:25.822028 [TRACE] (runner) acquired child lock for command, spawning
2020/07/08 09:13:25.822177 [INFO] (child) spawning: echo
2020/07/08 09:13:25.822807 [INFO] (runner) once mode and all templates rendered
2020/07/08 09:13:25.827659 [DEBUG] (runner) stopping watcher
2020/07/08 09:13:25.827759 [DEBUG] (watcher) stopping all views
2020/07/08 09:13:25.827859 [INFO] (runner) waiting for child process to exit
2020/07/08 09:13:25.821534 [DEBUG] (cli) receiving signal "child exited"

2020/07/08 09:13:25.828493 [INFO] (runner) child process died
2020/07/08 09:13:25.828563 [ERR] (cli) child process died with exit code 0

its seem empty, but when i change config to print env variable like this :
exec {
  command = "env"
  env {
    custom = ["TEST=123"]
  }
 }

template {
  source = "./test.conf"
  destination = "/etc/nginx.conf"
  perms       = 0644
  command     = "systemctl reload nginx"
}

output : 
....
CONSUL_HTTP_SSL=false
CONSUL_HTTP_SSL_VERIFY=true
TEST=123
2020/07/08 09:16:17.380178 [INFO] (runner) child process died
2020/07/08 09:16:17.380253 [ERR] (cli) child process died with exit code 0

its exist there. is there something i did wrong ?

**Comment by eikenb** [comment]
Hey @ericsonrumuy7, thanks for the report. 

I've figured out the issue you're having. The core of it is that the command string doesn't itself process environment variables. They are fed to the underlying command run. So if you change  your command from `echo ${TEST}` to calling a shell script that contains ...
```sh
#!/bin/sh
echo ${TEST}
```
It should work.

**Comment by ericsonrumuy7** [comment]
thanks @eikenb, it works. but can we use it in template ?
ex:
{{ printf (env "TEST") }}

**Comment by eikenb** [comment]
Sorry @ericsonrumuy7, but the custom environment setting is part of the exec settings and are only applied to the exec'd command. To have something available for both the templates and the command you would need to add it to consul-template's environment (and not specify exec/pristine option).

**Comment by ericsonrumuy7** [comment]
what is the parameter for consul-template's environment ? I cannot find it in documentation

**Comment by eikenb** [comment]
It's not something you would config with consul-template, it is how you'd run consul-template. There are many ways to do it really with the answer depending on your circumstances and how you are calling/using consul-template. A simple example might be `env TEST=123 /usr/bin/consul-template`, which adds the TEST environment variable to the environment in which it runs consul-template.

If you give more details about how you are running consul-template, I might be able to help.

**Comment by ericsonrumuy7** [comment]
oh I see. I though it can be configure through consul-template config like exec. 
Thanks @eikenb for the explanation
