### ISSUE TITLE
[Feature] Add support for ServiceTaggedAddresses

### ISSUE THREAD

**Issue by danieleva** [hashicorp/consul-template#1398]
I need to access the values published by a service in its `ServiceTaggedAddresses` field. I can see the value by querying consul API directly, but they are not available in consul-template.
If I understood the code correctly that is because `ServiceTaggedAddresses` is not parsed into the CatalogService struct in
https://github.com/hashicorp/consul-template/blob/master/dependency/catalog_service.go

Would you be interested in a PR to add that?

**Comment by eikenb** [comment]
Hey @danieleva, 

This seems like it should be a pretty simple addition and If you'd like to submit a PR I'd be happy to look at it. Please remember tests.

Thanks.
