### ISSUE TITLE
Roll back Arm GCC build

### ISSUE THREAD

**Issue by eikenb** [hashicorp/consul-template#1404]
We were using CGO with our ARM builds due to this bug... https://github.com/golang/go/issues/32912

Which was fixed in go1.14. So we can remove this workaround.

The workaround was initially implemented here.. https://github.com/hashicorp/consul-template/commit/d1e1dad20844a4a98429b367985b5b5d4ccb8b70

Just need to remove the special cases for ARM.

**Comment by faizansiddiqu007** [comment]
just remove them straight
