### ISSUE TITLE
Log-to-file / logging on Windows with SC.exe

### ISSUE THREAD

**Issue by itdaniher** [hashicorp/consul-template#1416]
### Consul Template version

v0.25.1

### Expected behavior

Consul-template supports logging to file. Consul-template can be started as a service on Windows, and the resultant messages can be inspected. Consul offers `-log-file` via stdarg and Nomad offers `log_file` in the config.

### Actual behavior

Consul-template only supports Syslog and stdout/stderr logging mechanisms. Windows discards stdout/stderr messages from services. Seemingly no way to get persistent logging without wrapping consul-template.exe in a script that captures stdout and stderr to a file. 

```
Calling: ArraySeq(sc.exe, create, consul-template, binpath=, C:\opt\consul-template\consul-template.exe)
Calling: ArraySeq(sc.exe, config, consul-template, DisplayName=, Consul-Templat, binPath=, C:\opt\consul-template\consul-template.exe -config=C:\opt\consul-template\config-windows.hcl -vault-token=s.REDACTED -consul-token=REDACTED)
Calling: WrappedArray(sc.exe, start, consul-template)
```

### Steps to reproduce

1. Create and start an instance of consul-template as a service with sc.exe on Windows
2. Attempt to inspect behavior. 
3. Unable to inspect behavior - no ability to log messages to a file.

### References

Are there any other GitHub issues (open or closed) that should
be linked here? For example:
- #1382

**Comment by eikenb** [comment]
They @itdaniher, thanks for taking the time to submit a ticket.

What do applications typically do for logging on Windows? Is it typical to provide something like a '-log-file /path/to/log` style option, either as a command line argument or a config option? What would you like to see?

I'm sure I can look this up but I'm mainly interested in what you want, a real use case.  Thanks.

**Comment by itdaniher** [comment]
I'd love to see `-log-file` as a command line argument. [Consul's semantics here](https://www.consul.io/docs/agent/options.html#_log_file) work very nicely for our needs. Not sure what's the norm (fortunately not often problem-solving on Windows!)

Thanks!

**Comment by ksandrmatveyev** [comment]
Hi @eikenb . I think it will be really useful as we can run consul-template as windows service https://github.com/hashicorp/consul-template/pull/1382, but we are blind due to no logs we can get. https://www.consul.io/docs/agent/options#_log_file, such as `-log-file`, `-log-rotate-bytes`, `-log-rotate-duration` and `-log-rotate-max-files`, are what I assume is ok

**Comment by deblasis** [comment]
Hi there 👋

I just created #1534. It should address this issue by adding `-log-file`, `-log-rotate-bytes,` `-log-rotate-duration` and `-log-rotate-max-files` and also the corresponding items inside a new configuration stanza named `log-file`.

I also dared to write the relevant documentation. I hope that's OK.

Cheers!

**Comment by mcouillard** [comment]
As an alternative, some Windows magic can redirect standard output to a file. So creating the service like this will do it (capturing both standard out, 1, and errors, 2, in the same file).

`sc.exe create VaultAgent binPath= "vault.exe agent -config=vault-agent.hcl -log-level=DEBUG 1>> agent.log 2>&1" displayName= "VaultAgent" start= auto`
