### ISSUE TITLE
' ' has invalid keys: telemetry error

### ISSUE THREAD

**Issue by developer-guy** [hashicorp/consul-template#1417]
### Consul Template version

consul-template v0.25.1 (171d54d)
[
![Screen Shot 2020-10-19 at 14 29 06](https://user-images.githubusercontent.com/16693043/96444817-a400dd80-1217-11eb-97fc-c91e51d1fc87.png)
](url)

### Configuration

```hcl
telemetry {
  stdout {
    reporting_interval = "60s"
    pretty_print = false
    do_not_print_time = false
 }
}

```

### Command

```shell
consul-template -template data.tpl/data.txt -config ./config.hcl
```

![Screen Shot 2020-10-19 at 14 28 54](https://user-images.githubusercontent.com/16693043/96444924-c692f680-1217-11eb-874b-516edd5978c6.png)

**Comment by greut** [comment]
it's been reverted, https://github.com/hashicorp/consul-template/commit/6bc149b39e69a3686af2786cbf92c57daca1b84e

**Comment by findkim** [comment]
Hi @developer-guy thank you for your interest in running Consul Template with telemetry! Unfortunately I had to make the difficult to decision to pull that iteration for telemetry support before it made it into the `v0.25.1` release as @greut had mentioned above.

At that time the supported features were limited and would have brought CT down a path that would not have been ideal for the future to maintain dogstatsd compatibility with statsd. More context is captured here https://github.com/hashicorp/consul-template/issues/1395.

Apologies for any confusion that the revert might have caused. Please do let me know if there are any docs I may have missed which caused it to incorrectly surface as currently supported.
