### ISSUE TITLE
Run command on the first render

### ISSUE THREAD

**Issue by williamoliveira** [hashicorp/consul-template#1424]
We noticed that the command on template do not run on first render, it runs only on the next kv changes. 
Is there a reason for its behavior to be this way? 
Could there be a flag to force it to run on the first time?

My config:
```
consul {
  address = "https://consul.mydomain.com"
}

template {
  contents = "{{ key \"docker-compose-key\" }}"
  destination = "docker-compose.yml"
  command = "cat docker-compose.yml"
}
```

My workaround:
`consul-template -config config.hlc -once && consul-template -config config.hlc`

**Comment by geniousphp** [comment]
I have the same issue. A flag to force run on first render in really important

**Comment by eikenb** [comment]
Thanks @geniousphp  for chiming in and the :+1:. We will have time to a look at these bugs very soon.

**Comment by eikenb** [comment]
I'm not able to reproduce this. I used a simple template like yours with 1 value to look up, where consul had that value already in the KV store. Run consul-template and the destination file is rendered out to disk right away. I don't have to update the consul KV entry to get it to update.

Below is the shell script I used to try to reproduce it. When I run that it spits out `foo`, the contents of docker-compose.yml, immediately. I don't have to change the KV value to trigger an update.

```
#!/bin/sh

rm -f config.hcl docker-compose.yml

cat > config.hcl << EOF
consul {
  address = "http://localhost:8500"
}

template {
  contents = "{{ key \"docker-compose-key\" }}\n"
  destination = "docker-compose.yml"
  command = "cat docker-compose.yml"
}
EOF

consul kv put docker-compose-key "foo" > /dev/null

consul-template -config config.hcl
```

**Comment by geniousphp** [comment]
I can't reproduce that issue anymore. I'm not sure what was causing me this issue before. I'm sorry for the false alert.

**Comment by eikenb** [comment]
Thanks for responding and letting me know. If it does come up again please don't hesitate to file a new ticket.
