### ISSUE TITLE
consul-template master branch does not respect log levels

### ISSUE THREAD

**Issue by jjjordan** [hashicorp/consul-template#1426]
Running consul-template in `master` results in trace output regardless of what log level is configured.  This appears to have been caused by 4caec4d, specifically [here](https://github.com/hashicorp/consul-template/blob/ff2eac702d069bb265f079ce08ea431c41813a73/logging/logging.go#L76) where the LevelFilter is completely disregarded.

**Comment by eikenb** [comment]
@jjjordan thanks for reporting this.. points out a lack of testing around logging. We should fix that when we fix this.

**Comment by eikenb** [comment]
Opps... missed this one when I fixed this in #1454, which overwrote the normal log filter with just dumping everything out, ignoring the log level.

Anyways, it should be fixed.
