### ISSUE TITLE
Add ability to load consul token from a file

### ISSUE THREAD

**Issue by nvx** [hashicorp/consul-template#1429]
There is currently a feature to load a Vault token from a file with the vault_agent_token_file option. This is super handy as it allows consul-template to read the Vault token outputted from a Vault Agent. This file is periodically checked for updates as well which is useful.

There is a similar use-case for loading the Consul token from a file. When running a Vault agent, it is possible to read out a Consul token from Vault and output it into a file using the Vault Agent template option. Unfortunately Consul currently cannot simply load a Consul token so you would have to either template a file that somehow sets the CONSUL_HTTP_TOKEN environment variable and trigger a restart of consul-template, or template out the entire consul-template config file and trigger a reload of consul-template whenever this is changed.

Simply having a "token_file" or similar directive under the consul config block that behaves the same way as the existing vault_agent_token_file vault configuration directive would solve this problem nicely.

**Comment by kvendingoldo** [comment]
any news here?

**Comment by eikenb** [comment]
Hey @kvendingoldo, 

I'm afraid this isn't really high up on my priority list right now and to get added anytime soon will require a community PR (which I do make a priority).

**Comment by lawliet89** [comment]
@eikenb does the `CONSUL_HTTP_TOKEN_FILE` environment variable work to enable this?

**Comment by lawliet89** [comment]
@eikenb I've submitted a fix for this in #1516. Please take a look.
