### ISSUE TITLE
https api with consul-template

### ISSUE THREAD

**Issue by re5et** [hashicorp/consul-template#143]
We put nginx in front of the consul web ui for a variety of reasons, and were wondering if there is something we are missing regarding using consul-template with an https instead of http api?

**Comment by sethvargo** [comment]
ping @armon

**Comment by ryanuber** [comment]
@re5et we simply didn't have the options set up in consul-template to tell the API client to talk HTTPS to the endpoints. #145 adds options to allow using the `https://` scheme, and optionally skip certificate warnings for self-signed certs.

**Comment by re5et** [comment]
awesome, thanks!
