### ISSUE TITLE
Provide a mechanism to query the latest release for consul-template

### ISSUE THREAD

**Issue by JonZeolla** [hashicorp/consul-template#1437]
### Expected behavior
I can anonymously query an endpoint receive JSON in the response body that contains latest version of `consul-template`.

### Actual behavior
There are no github releases, and https://checkpoint-api.hashicorp.com does not have a `consul-template` endpoint.

### Steps to reproduce
1. No github releases: `curl https://api.github.com/repos/hashicorp/consul-template/releases` returns an empty list
2. No endpoint on the checkpoint-api: `curl https://checkpoint-api.hashicorp.com/v1/check/consul-template` returns a 404

**Comment by JonZeolla** [comment]
@findkim any idea where this fits into the priorities?  I would be willing to contribute if there is a preferred approach in mind.

**Comment by eikenb** [comment]
Hey @JonZeolla,

We have a new release pipeline that we will be converting these projects over to soon and I'm pretty sure it does github releases as part of the process. You can see it in action with our [new project](https://github.com/hashicorp/consul-terraform-sync/) (which is nearing its initial release).

**Comment by JonZeolla** [comment]
Wonderful, thank you for the update.  I will stay tuned

**Comment by JonZeolla** [comment]
Are you open to external contributions to the conversion?

**Comment by eikenb** [comment]
I'm sorry, I would be open to it but the process requires use of internal/private resources so we need to do it.

I am finishing up with my work on the last big issue on the other project and will be doing this soon. I just need to get a docker image for consul-esm out then I'm going to rework all the release pipelines for consul-template, env-consul and consul-esm to our new system. So it will be happening in the next week or 2 and will be used in the future. So starting next release we should have github releases.

**Comment by JonZeolla** [comment]
Ok, thanks for the update.

**Comment by JonZeolla** [comment]
This appears to be resolved for this project as of v0.26.0.  Thanks!
