### ISSUE TITLE
One command for multiple templates

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/consul-template#1440]
Hello,

After following the [guide](https://learn.hashicorp.com/tutorials/nomad/vault-pki-nomad?in=nomad/integrate-vault#configure-consul-template) I now have a consul-template to generate new certificates for the nomad.

The issue is that I have to generate multiple files but after I need to execute the same command.

The first concern is the race between generating template1 and running command from template1 before template2 generated(like crt + key).

The second concern is the immutability and overall load. I have a case where I need to run the same consul-template on 3 nodes(HA) and when do an operation with Vault(for updating Nomad secret engine) and it makes zero sense to do it 3 times and it also a race between 3 nodes. Something like de-duplication for both rendering a template AND command execution would be very interesting.

**Comment by eikenb** [comment]
Hey @Oloremo, I think you can do this now (without any changes to CT). Below are a couple ideas that seem like they should work for you. Please test them (particularly the first one as it is the easiest) and let me know.

A couple options off the top of my head.

1. If the command you want to run for each template is the same for all templates, just put it as the command for all of them and when they are evaluated it checks to see if the command is already queued up to run and skips it if it is. So all 3 templates can have (and must have for this to work) the exact same command but it will only get run once if no matter  if just 1 or all 3 templates are rendered.
 
2. Use the top level exec program to run the command when it receives a signal (which you can configure with the reload_signal configuration parameter).  You can even do this with a shell script, something like...
```
#!/bin/sh              
# output shell scripts PID for `kill -s SIGHUP [PID]`
echo $$
# this trap is the key, you'd run your command here
trap 'echo runit' HUP
# you need the loop as sleep blocks everything, including the trap. The loop frees the block so the trap can run.
while true
do
    sleep 1 # this can be a decimal, depending on your system (check man page)
done
```

**Comment by Oloremo** [comment]
> and when they are evaluated it checks to see if the command is already queued up to run and skips it if it is. 

Hmm, is that behavior documented somewhere? 

And what do you think about adding command execution de-duplication logic? Imagine I have 3 servers with the same command, but in reality, I need to run it once, on any node.

**Comment by eikenb** [comment]
> Hmm, is that behavior documented somewhere?
No (well, in the code). My guess it was done more thinking of it as an optimization than as a semantic thing... but it should be documented. Probably in the Caveats->Command section. I'll file a ticket for that.

> Also what is the algo exactly here? If I render 5 templates, I need to run this command after all templates are rendered usually.
The flow when a monitored value is updated in consul would look something like..
1. value updated
2. all templates using that value re-rendered
3. command from rendered template's config is checked for in list of commands to run and if not present, added (https://github.com/hashicorp/consul-template/blob/91c3dd4189ad3d8d21130694f436e9706e3ccf5a/manager/runner.go#L823-L833)
*at this point all templates have been rendered
4. all commands in list are run
https://github.com/hashicorp/consul-template/blob/91c3dd4189ad3d8d21130694f436e9706e3ccf5a/manager/runner.go#L566-L586


> And what do you think about adding command execution de-duplication logic? Imagine I have 3 servers with the same command, but in reality, I need to run it once, on any node.

This is beyond the scope of CT. In general I'd think this would require a central service that you'd notify about the event and that the command would be run when that happens with a buffering/waiting period for the events so 2 events close together don't both trigger the command run.

**Comment by Oloremo** [comment]
Thanks for the explanation!

I am still a bit unsure about "value updated".
In my case it's a a templates like:

```
[[ with secret "pki_int_nomad/issue/nomad-cluster" "common_name=agent.global.nomad" "ttl=24h" "alt_names=localhost" "ip_sans=127.0.0.1" ]]
[[ .Data.certificate ]]
[[ end ]]
```

It's not like a KV value, it's supposed to be triggered at the middle of the cert TTL for example.
Will the same logic applied in that case? or it could be a race since it's a time after all.

**Comment by eikenb** [comment]
I fixed the formatting in my previous post, sorry if it was hard to read.

Are you running a cluster of consul-template servers or single one. The previous post's question about de-duplicating the logic made me think you were using a cluster of consul-template servers and were asking about ways to limit each of the separate consul-template servers from sending the command.

If you are running a single instance than it shouldn't be an issue. Assuming the 3 servers all use the same cert, that cert is a single data value consul-template monitors/polls and when updated would trigger all 3 templates (servers) to be updated at the same time. If all 3 template configs specified the same command then it would only run that command the once.

I'm kind of speculating about your setup a bit as I haven't seen the config. If the above doesn't sound right maybe consider posting your config so I can have a bit more context.

**Comment by Oloremo** [comment]
Yeah, I should've started with my configuration to make it more clear, sorry.

So what I have is a:
3 nodes - that have CT, Nomad Server, Vault
100+ nodes - that have CT, Nomad Agent

All nomad certificates are provisioned by CT by using a Vault PKI, as per the guide I mentioned.
Each CT has a 5 templates configured:

```
vault {
  address = "https://127.0.0.1:8200"
  unwrap_token = false
  renew_token  = true

  ssl {
[CUT]
  }
}

template {
  source = "/opt/nomad/ctemplates/agent.crt.tpl"
  destination = "/opt/nomad/tls/agent.crt"
  perms = 0600
  command = "/opt/nomad/utils/consul-template-restart.sh"
  error_on_missing_key = true
}

template {
  source = "/opt/nomad/ctemplates/agent.key.tpl"
  destination = "/opt/nomad/tls/agent.key"
  perms = 0600
  command = "/opt/nomad/utils/consul-template-restart.sh"
  error_on_missing_key = true
}

template {
  source = "/opt/nomad/ctemplates/ca.crt.tpl"
  destination = "/opt/nomad/tls/ca.crt"
  command = "/opt/nomad/utils/consul-template-restart.sh"
  error_on_missing_key = true
}

template {
  source = "/opt/nomad/ctemplates/cli.crt.tpl"
  destination = "/opt/nomad/tls/cli.crt"
  command = "/opt/nomad/utils/consul-template-restart.sh"
  error_on_missing_key = true
}

template {
  source = "/opt/nomad/ctemplates/cli.key.tpl"
  destination = "/opt/nomad/tls/cli.key"
  command = "/opt/nomad/utils/consul-template-restart.sh"
  error_on_missing_key = true
}
``` 

All ctemplates are like this one:
```
[[ with secret "pki_int_nomad/issue/nomad-cluster" "common_name=agent.global.nomad" "ttl=24h" "alt_names=localhost" "ip_sans=127.0.0.1" ]]
[[ .Data.certificate ]]
[[ end ]]
```

So they issue and template new certs in the middle of the expected TTL.

What I want is for a single CT on a single node to run that command once, after all templates are rendered. 

And they should all be rendered roughly at the same time if I understand how it's working correctly since all those certs has the same TTL. But since we're talking about TTL, we're talking about time, I guess, and if we talking about the time we could talk about races here. That is why I want to understand how exactly CT evaluates its logic in that particular scenario.

**Comment by eikenb** [comment]
Sorry for the delay in feedback, got sucked into other things.

Seems like the crux of the problem is these 2 things combined...
A) "What I want is for a single CT on a single node to run that command once, after all templates are rendered."
B) Lots of CT instances running this code.

While A) is possible with on a single node, consul-template has no facilities to deal with wanting A) but having B).

As I said above, unless I'm missing something, this is beyond the scope of CT and I think you'll need an external system to coordinate things.

Sorry I can't be of more help. If it seems like I'm not quite getting the issue and you think it might be workable please feel free to respond and I'll keep trying.

**Comment by Oloremo** [comment]
Missed your reply.

> A) "What I want is for a single CT on a single node to run that command once, after all templates are rendered."

Correct

> B) Lots of CT instances running this code.

Correct

> While A) is possible with on a single node,

And I don't have to do anything here, right? it just will work like this? I do not fully understand how CT will know that there are multiple templates about to render with the same command so let's render them first and then execute the command.

This is probably due to the fact that I do not fully understand how CT decided that it's time to re-render the template in the case of Vault PKI. Seem like it takes the TTL and waits half(???) of its time and when re-render?

If I define 2 templates with the same TTL will they be re-rendered at the same time? What is precision? Could we have races here?

I'm very sorry but it feels like a black box right now and while it works I do not fully understand how and what to expect.

**Comment by eikenb** [comment]
> And I don't have to do anything here, right? it just will work like this? I do not fully understand how CT will know that there are multiple templates about to render with the same command so let's render them first and then execute the command.

When consul-template gets an update from Consul it runs through each template to check if they need updating. While doing so it collects commands to be run if the paired template is rendered (and the command needs to be run). It keeps these commands in a way where it de-duplicates them. So if 3 templates are all rendered with the same command, that command will only be run once after they are all done.

> This is probably due to the fact that I do not fully understand how CT decided that it's time to re-render the template in the case of Vault PKI. Seem like it takes the TTL and waits half(???) of its time and when re-render?

For Vault, if the secrets have a TTL it does something pretty close to what you are saying. It polls vault for new values based on the TTL, and it uses a starting off with that TTL/3 plus some noise. It only waits for about 1/3 the time as this allows for some retrying if there are network issues.

> If I define 2 templates with the same TTL will they be re-rendered at the same time? What is precision? Could we have races here?

The secrets have the TTL's, not the templates. So if those 2 templates are using the same secret and that secret would follow the TTL and if updated would trigger both templates to be rendered.

If the secrets are different they will have slightly different timeouts by design due to the random noise added to the TTL.

> I'm very sorry but it feels like a black box right now and while it works I do not fully understand how and what to expect.

No problem. For such a small tool, consul-template has a lot of complexity to it. So please feel free to ask more questions here or on the [discuss forum](https://discuss.hashicorp.com/tags/c/consul/29/consul-template), where you might get responses faster as it has a much larger audience than just us devs.

**Comment by Oloremo** [comment]
I think I have a better picture now of how CT works. Thank you very much for your patience and answers.
