### ISSUE TITLE
how can i explicitly get the first and the second element of Tags in order to use them as host address and port ?

### ISSUE THREAD

**Issue by sotirisk** [hashicorp/consul-template#1444]
i have tried the following with no success

{{ first .Tags }} 
{{index .Tags 0}}
{{.Tags[0]}}
{{(index .Tags 0).field}}
{{index .Tags '0'}}
{{index .Tags 1}}
{{ (index .Tags 1).field }}
{{ .Tags._0 }}

Tags has values . The following produce these outputs 

{{.Tags}} ->  [tag1 tag2]
{{ range .Tags }}{{ . }}{{end}}  ->  tag1tag2
{{ .Tags | join "," }} ->  tag1,tag2

**Comment by sotirisk** [comment]
ok i found it 
the syntax is this

{{ with .Tags}}{{ with index . 0 }}{{ . }}{{end}}{{end}}

**Comment by eikenb** [comment]
Hey @sotirisk, I'm glad you were able to figure this out on your own. I just wanted to suggest that the next time you have an issue you consider posting your question on your [discuss forum](https://discuss.hashicorp.com/c/consul). You are more likely to get help as there are more community members watching it as well as our developer advocates and us devs. Thanks.
