### ISSUE TITLE
service, nodes functions returns list of some hex values

### ISSUE THREAD

**Issue by mchumakov** [hashicorp/consul-template#1460]
Hello, 
I'm trying to get list of healthy nodes of service "patroni-cluster-a" as well as cluster nodes but in both cases I'm getting lists of unreadable hex values. 

Template I'm using.
```liquid
{{ service "patroni-cluster-a" }}
{{ nodes }}
```

### Consul Template version
consul-template -v
consul-template v0.25.2 (c8372a0a)

### Configuration

```hcl
# Copy-paste your configuration files here. Only include what is necessary or
# what you've changed from defaults. Include all referenced configurations.

```

```liquid
# Include sample data you reference in the template from Consul or Vault here.
consul catalog services -tags
consul
patroni-cluster-a      dc_cvt,master,replica
patroni-cluster-b      master,replica
patroni-cluster-c      replica
```

### Command

```shell
consul-template -config /etc/consul-template.d/consul-template-config.hcl -log-level=trace
```

### Debug output
https://gist.github.com/mchumakov/c20045d75c4a0670f169dc459121af51

### Expected behavior
There should be human readable list of healthy nodes of service patroni-cluster-a
There should be human readable list of cluster nodes

### Actual behavior
In both cases I've got list of hex values
```
[0xc0003b45b0 0xc0003b4680 0xc0003b4750 0xc0003b4820 0xc0003b48f0 0xc0003b49c0]
[0xc000238230 0xc000238280 0xc0002382d0 0xc000238320 0xc000238370 0xc0002383c0 0xc000238410 0xc000238460 0xc0002384b0 0xc000238500 0xc000238550 0xc0002385a0 0xc0002385f0 0xc000238640 0xc000238690 0xc0002386e0 0xc000238730 0xc000238780 0xc0002387d0 0xc000238820 0xc000238870 0xc0002388c0 0xc000238910 0xc000238960 0xc0002389b0 0xc000238a00 0xc000238a50 0xc000238aa0 0xc000238af0 0xc000238b40 0xc000238b90 0xc000238be0 0xc000238c30 0xc000238c80 0xc000238cd0 0xc000238d20]
```
- ...

**Comment by findkim** [comment]
Hi @mchumakov it looks like the hex values observed are go pointers to your service instances and nodes. A common approach is to iterate over the lists within the template to access the values and its attributes. An example is provided in the [templating language docs](https://github.com/hashicorp/consul-template/blob/master/docs/templating-language.md#service).

Following the template provided in the ticket, modifying it to iterate over the list may look like the below:
```
{{ range service "patroni-cluster-a" }}
{{ .Name }} {{ .ID }} {{ .Address }}:{{ .Port }}{{ end }}

{{ range nodes }}
{{ .Address }}{{ end }}

patroni-cluster-a patroni-cluster-a-01 10.5.2.45:2492
patroni-cluster-a patroni-cluster-a-02 10.2.6.61:2904

10.5.2.45
10.2.6.61
```

I'm going ahead and closing this out. If you have more questions on templates and running Consul-Template, I would encourage posting questions on our [discuss forum](https://discuss.hashicorp.com/tags/c/consul/29/consul-template). You are more likely to get help as there are more community members watching it as well as our developer advocates and us devs. Thanks.
