### ISSUE TITLE
Key not found - error handling (error_on_missing_key = true ) 

### ISSUE THREAD

**Issue by error08** [hashicorp/consul-template#1469]
In case a key in a template is not found when running with  'error_on_missing_key = true', consul-template exists with an error code. Unfortunately, the key missing is not provided in the error message.

Expected behavior:
Provide the (first) key not found in the error message.

### Consul Template version: 0.25.1

**Comment by eikenb** [comment]
Hey @error08, thanks for filing this issue.

Whether or not the key is included depends on the underlying error. The built-in dot `.var` style lookup includes the key name in the error, so does consul-template's `secret` (the 2 I tested with).... but I'm sure there are some without. If you could include the specific template functions used which don't return the key in the error, I could add it.

@whit-e, @mkaesz if either of you know of any and would like to provide that info I can hit those as well.

Thanks!

**Comment by eikenb** [comment]
I've tested a few more and haven't found a case where this occurs. IMO if it doesn't print out the key on one of these errors it is a bug and the use case needs to include the template syntax so I can reproduce and fix the issue for that case. So I'm going to change the tags on this issue accordingly.

I'm going to close this issue as unreproducible as it is missing the details needed to address.

If you find one of these, please file new issues with the details.

Thanks.
