### ISSUE TITLE
Allow setting user/group ownership of template output

### ISSUE THREAD

**Issue by drawks** [hashicorp/consul-template#1497]
As asked for in #639 it would great if we could define the user/group ownership of output files. Previously it has been stated that a solution that is completely platform independent would be welcome, however since that comment was made #1185 was merged which preserves user/group only on "unix OSs." It seems like perhaps there is some flexibility on the need for all features to be fully platform independent and if that is the case I'd argue that being able to set owner/group/mode (perhaps even extended attributes and se contexts) on supported platforms would make this tool much more powerful.

**Comment by deblasis** [comment]
Hi there, I came here after some triaging on https://github.com/hashicorp/nomad/issues/5020 which seems to be related.

I agree that being able to set the ownership of the rendered templates can be powerful and sometimes a must-have.
I was wondering, wouldn't a `template.Exec` with a `chown` command be enough in order to achieve this?

**Comment by deblasis** [comment]
I wanted to be my own devil's advocate so I have also PRd #1531, looking forward to hearing back from you guys!

Cheers

**Comment by eikenb** [comment]
>  I was wondering, wouldn't a `template.Exec` with a `chown` command be enough in order to achieve this?

If the consul-template process is run with permissions to do this, then yes that could work. All commands are run with the permissions of the process (and their user/group owner). 

I Read through https://github.com/hashicorp/nomad/issues/5020 and as Nomad doesn't support the Exec (and I don't think they'd want to) it is of no help there. On the other hand, your PR would address their case nicely and I'll take some time to review it.

**Comment by deblasis** [comment]
Awesome! Thank you @eikenb!

**Comment by eikenb** [comment]
Fixed by #1531
