### ISSUE TITLE
[Req] Multiple token support

### ISSUE THREAD

**Issue by rotatingJazz** [hashicorp/consul-template#150]
> Add a token setting per template that will override the "master". This way we can have granural control with only one instance.

**Comment by sethvargo** [comment]
Hi @rotatingJazz,

Thank you for the request. This is not something we plan to support, but there is an easy solution. Consul Template runs with an incredibly small footprint (like a few MB) and runs in isolated processes. Therefore, if you want to use a different token on a per-template basis, just spawn multiple consul-template instances, each with a different `-token` parameter.

There is no harm in running more than one instance of Consul Template, in fact it is encouraged.

**Comment by rotatingJazz** [comment]
Thanks @sethvargo for the clarification! I was a bit reluctant with multiple processes because I hadn't realized it's the recommended way.
