### ISSUE TITLE
Release 0.26.0 does not contain all the builds on site releases.hashicorp.com

### ISSUE THREAD

**Issue by jidckii** [hashicorp/consul-template#1506]
Page [0.26.0](https://releases.hashicorp.com/consul-template/0.26.0/
) does not contain all previously available assemblies as for example in [0.25.2](https://releases.hashicorp.com/consul-template/0.25.2/).
There are no arm, arm64 and many other builds...

**Comment by eikenb** [comment]
Hey @jidckii, thanks for reporting this.

We recently switched to a new common build pipeline and these are the default builds with the new system. The defaults were picked based on the general requirements across projects. I should be able to update it with more build targets. If you could list the ones you are interested in I can make those a priority to be included in the next release. Thanks.

**Comment by eikenb** [comment]
More build targets have been added and I never heard back on which ones were missed. So I'm going to resolve this.

If you come across an architecture you need a binary for file a specific bug about that architecture. Thanks.
