### ISSUE TITLE
Range can't iterate over ENV variable when using it with parseJSON 

### ISSUE THREAD

**Issue by sielaq** [hashicorp/consul-template#152]
I'm not quite sure if this is by desin,
but I have problems when a JSON stuff is in a ENV variable.

To reproduce:
prepare ENV variable and json file
```
export FOO="[\"bar\"]"
echo $FOO > data.json

```
Code that works:
```
{{with $foo := file "data.json" | parseJSON}}
  {{range $foo}}
    {{.}}
  {{end}}
{{end}}
```
Code that fails:
```
{{with $foo := env "FOO" | parseJSON}}
  {{range $foo}}
    {{.}}
  {{end}}
{{end}}
```
error:
```
[ERR] template: out:2:8: executing "out" at <$foo>: range can't iterate over FOO
```

**Comment by sielaq** [comment]
without range, both returns the same "array"
```
{{with $foo := file "data.json" | parseJSON}}
  {{$foo}}
{{end}}
{{with $foo := env "FOO" | parseJSON}}
  {{$foo}}
{{end}}
```
```
[bar]

[bar]
```

**Comment by sethvargo** [comment]
@sielaq I was unable to reproduce this issue on master. I also added a few tests for it in #156 and those all passed. If you are still able to reproduce this on master, please provide more information about your setup so that I may try and reproduce.

**Comment by sielaq** [comment]
@sethvargo You right, I used pure 0.5.1 in this case.
I have tried with master branch and ENV is working perfectly.
but
I can't read any json file anymore. same JSON like before, same config:
```
{{with $foo := file "data.json" | parseJSON}}
  {{range $foo}}
    {{.}}
  {{end}}
{{end}}
```
error:
```
executing "test" at <parseJSON>: error calling parseJSON: unexpected end of JSON input
```
and this is the same error when json file is missing. Could it be that it looks into different directory ?

**Comment by sethvargo** [comment]
@sielaq can you please open another issue and include the output with `CONSUL_TEMPLATE_LOG=debug`?

**Comment by sethvargo** [comment]
@sielaq nevermind. I was able to fix it: https://github.com/hashicorp/consul-template/pull/158
