### ISSUE TITLE
[feature request] Add an ability to specify the renewal time for the secrets 

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/consul-template#1526]
## Description

As per [documentation](https://github.com/hashicorp/consul-template/blob/master/docs/templating-language.md#secret):
> The Renew API tries to use most of the time the secret is good, renewing at around 90% of the lease time (as set by Vault).

In some cases, we really want to control the time for renewal.

For example here is how it looks like for the TLS certificates that consul-template populate from the Vault:

![image](https://user-images.githubusercontent.com/4280480/138162584-00ff2974-059c-444d-ab24-eba92253a1b3.png)

It's very hard to monitor. We'd really like to set the threshold to like half of the TTL and alert if half of the TTL + 1 hour has passed but certificates are not renewed.

**Comment by chrisvanmeer** [comment]
I would also like this feature. I'm currently having static secrets in a K/V 2 engine and now it takes around 5 minutes for Consul to pickup this change and signal it to Nomad. K/V 1 allowed for a `ttl` k/v pair to specify the ttl for the specific secret. It would be great if either that `ttl` k/v option would be available in K/V 2.

**Comment by Oloremo** [comment]
Was implemented.

**Comment by eikenb** [comment]
Thanks @Oloremo
