### ISSUE TITLE
Document Exec{} block as part of template configuration

### ISSUE THREAD

**Issue by eikenb** [hashicorp/consul-template#1530]
Configuration file template block needs updating. It still lists the `command` options and doesn't have the `Exec` block in the documentation at all. It does have a correct `exec{}` block in the example though.

- [ ] mark `command` as deprecated
- [ ] add `exec` block to template section

**Comment by marco-m-pix4d** [comment]
If I understand correctly, also the README needs updating

**Comment by eikenb** [comment]
Hey @marco-m-pix4d,

We split the README documentation up into smaller chunks a while back and, AFAIK, all the needed changes are in the docs that were split out (in docs/configuration.md). The documentation still in the top level README.md, in the `Commands` section, applies equally to the Exec.Command setting. So I think it is OK for now.

**Comment by marco-m-pix4d** [comment]
You are indeed right, thanks for the quick answer @eikenb :-)
