### ISSUE TITLE
Latest release with -log-file support

### ISSUE THREAD

**Issue by frederiko** [hashicorp/consul-template#1538]
Hello,

I noticed consul-template `0.27.2` does not contain the latest `-log-file` support. This is a neat feature to have it, specially the log rotation support. Any plans to cut a new release? Currently, I am building myself, but it would be nice to have an office release. 

Best.

**Comment by eikenb** [comment]
Hey @frederiko, thanks for the interest.

That feature is going to be part of the 0.28.0 release which will be our priority to get out after the holidays (in the new year).
