### ISSUE TITLE
trimprefix need to added in consul-template

### ISSUE THREAD

**Issue by thatsk** [hashicorp/consul-template#1544]
i am trying to access tags from service information and perform some operation on tags strings.
```
{{ range $tag, $services := service "test-service" | byTag }}{{ if $tag | contains "contextPath" }}{{ $tag }}{{ end }}{{ end }}
```

if tags have contextPath=/service-info I need to just print service-info in the output I just found https://www.terraform.io/language/functions/trimprefix so if we can use that or any suggestions are welome

**Comment by eikenb** [comment]
Hey @thatsk, thanks for the interest.

That looks like a pretty direct wrapper for the Golang strings trim functions. That's be a pretty easy thing to add to the available template functions. I won't have time any time soon to implement it, but I'd be happy to review any PR adding them.

If you would like to add it, take a look at the existing trimSpace() template function as an example.

https://github.com/hashicorp/consul-template/blob/be5fcd832e806c11812d65b125ab9fb1bd0ed631/template/funcs.go#L953

**Comment by jsanant** [comment]
Hey @eikenb, I would like to take this up. 

Just to confirm these are the functions that need to be added to the existing template functions:

- `trim`
- `trimPrefix`
- `trimSuffix`

**Comment by thatsk** [comment]
Yes

**Comment by eikenb** [comment]
Thanks @jsanant for taking this up and thanks @thatsk for answering! :)

I'll keep an eye out for your PR.
