### ISSUE TITLE
Helper function "byTag" prints extra line

### ISSUE THREAD

**Issue by jsnook** [hashicorp/consul-template#155]
I'm using the helper "byTag" function to print out an HAProxy config.  My consul-template stanza is:

```
listen http-in
  bind *:80{{range $tag, $services := service "webapp" | byTag}}
  acl host_app1 hdr(host) -i {{$tag}}{{end}}
```
This results in:
```
listen http-in
bind *:80
  acl host_app1 hdr(host) -i
  acl host_app1 hdr(host) -i this-is-tag1
  acl host_app1 hdr(host) -i this-is-tag2
```
The expected outcome is:
```
listen http-in
  bind *:80
  acl host_app1 hdr(host) -i this-is-tag1
  acl host_app1 hdr(host) -i this-is-tag2
```

I am unsure as to why its picking up a blank value and printing it.  I'm using consul-template v0.5.1.  

I've solved the problem by adding an "if" even though the consul-template example doesnt require one:
```
listen http-in
    bind *:80{{range $tag, $services := service "webapp" | byTag}}
    {{if $tag}}acl host_app1 hdr(host) -i {{$tag}}{{end}}{{end}}
```

**Comment by sethvargo** [comment]
@jsnook can you tell me which services you have? Like what is the output if you loop over each service and do not group by tag?

I suspect you have a service without a tag, in which case you actually have something like this:

```text
{
  "": [service1, service2],
  "tag1":[service3],
}
```

I think we need to ignore if the tag is the empty string, but I don't see how that is possible. Can you run this:

```liquid
{{ range service "webapp" }}
  {{.Node}}:{{ range .Tags }}
    {{.}}
  {{ end }}{{ end }}
```

**Comment by sethvargo** [comment]
Nevermind - I found the bug. This will be fixed in the next release.

**Comment by jsnook** [comment]
Perfect. I was just about to hit send with my results and saw the update.

Thanks
