### ISSUE TITLE
Vault certificate issue multiple file output results in one blank file

### ISSUE THREAD

**Issue by alexwd8a** [hashicorp/consul-template#1550]
I am attempting to issue a certificate from Vault, and retrieve the secret key and certificate as two file outputs. One of the outputs generates an empty file. The empty file is always the second template regardless of whether it is key or certificate.

Configuration based on: https://github.com/hashicorp/consul-template/blob/master/examples/vault-pki.md

### Consul Template version 

consul-template v0.28.0 (ae2bbca1)

### Configuration

vaultcontemp.hcl

```hcl
template {
    source = "/etc/vault/vaultkey.tpl"
    destination = "/etc/vault/ssl/test/vaultkey.pem"
    perms = 0640
}

template {
    contents = "/etc/vault/vaultcert.tpl"
    destination = "/etc/vault/ssl/test/vaultcert.pem"
    perms = 0640
}
```
vaultkey.tpl

```liquid
{{- /* /etc/vault/vaultkey.tpl */ -}}
{{ with secret "pki_intermedca/issue/d8a-associates" "common_name=vlt.adm.d8a.associates" "alt_names=localhost" "ip_sans=127.0.0.1" "ttl=7d" }}
{{ .Data.private_key }}
{{ end }}

```

vaultcert.tpl

```liquid
{- /* /etc/vault/vaultcert.tpl */ -}}
{{ with secret "pki_intermedca/issue/d8a-associates" "common_name=vlt.adm.d8a.associates" "alt_names=localhost" "ip_sans=127.0.0.1" "ttl=7d" }}
{{ .Data.certificate }}
{{ end }}

```

### Command

```shell
consul-template -config vaultcontemp.hcl -log-level=trace
```

### Debug output

Debug output 1 (key first): https://gist.github.com/alexwd8a/7569d1390bb365bbbcc14eb80cbddd6b
Debug output 2 (cert first): https://gist.github.com/alexwd8a/49caa255c97e4985677bcae601448b91

### Expected behavior

vaultcert.pem and vaultkey.pem should both contain their relevant content

### Actual behavior

Only the file in the first template scope is generated with content. The other is generated as an empty file.

### Steps to reproduce

1. Setup Vault with a root CA, intermediate CA, and a role
2. Setup Consul-Template as above, and attempt to run
3. vaultkey.pem is populated with content, while vaultcert.pem is not (created as empty file)
4. Swap order of the template scopes in the hcl file
5. Run Consul-Template again
6. Now vaultcert.pem is populated with content, while vaultkey.pem is not (created as empty file)

In both instances, only one new certificate is created in the vault (as expected).

For this test, consul-template is being run under sudo so there are no file permission restrictions in creating the files.

### References

None identified

**Comment by eikenb** [comment]
Thanks for reporting this @alexwd8a, I'm looking at the Vault PKI code in relation to other things currently so I should be able to get to this as well. I'll follow up more when I start working on it.

**Comment by eikenb** [comment]
I haven't been able to reproduce this using this setup.

Templates.

key.tmpl
```
{{ with secret "pki/issue/example-dot-com" "common_name=test.example.com" "alt_names=localhost" "ip_sans=127.0.0.1" "ttl=7d" }}
{{ .Data.private_key }}
{{ end }}
```

cert.tmpl
```
{{ with secret "pki/issue/example-dot-com" "common_name=test.example.com" "alt_names=localhost" "ip_sans=127.0.0.1" "ttl=7d" }}
{{ .Data.certificate }}
{{ end }}
```

config.hcl
```vault {
  address = "http://127.0.0.1:8200"
  renew_token = false
  ssl {
     enabled = false
   }
 }
template {
  source = "key.tmpl"
  destination = "key.pem"
}
template {
  source = "cert.tmpl"
  destination = "cert.pem"
}
```

vautl test server setup..
```
# run vault server in separate terminal
vault server -dev -log-level=warn \
    -dev-no-store-token -dev-root-token-id="a_token"

# create/set token for use
export VAULT_TOKEN=a_token
export VAULT_ADDR='http://127.0.0.1:8200'
vault token create -id b_token -ttl 20m -renewable
export VAULT_TOKEN=b_token

# enable and setup pki CA
vault secrets enable pki
vault secrets tune -max-lease-ttl=8760h pki/
vault write -field=certificate pki/root/generate/internal \
        common_name="example.com" \
        ttl=8760h > CA_cert.crt
vault write pki/roles/example-dot-com \
    allowed_domains=example.com \
    allow_subdomains=true \
    max_ttl=72h
```

calling consul-template
```
consul-template -config config.hcl
```

**Comment by alexwd8a** [comment]
Ah it turns out, I'm blind, there is a typo in my config that I didn't see the whole time.

Since you pointed out the second config was showing (dynamic) instead of the source, I realised I had the second template is set to "contents" instead of "source".

It even has it there in my post above but we both managed to miss it somehow. But your feedback about the log made me read it a bit more carefully. So it is working now - thanks.

**Comment by eikenb** [comment]
:rofl: .. Great catch. Happy to be your rubber duck.
