### ISSUE TITLE
consul-template could'nt get Meta value

### ISSUE THREAD

**Issue by Zgrrl** [hashicorp/consul-template#1552]
Hi,
I have service as below.
`
services {
  id = "svc1"
  name = "service1"
  address = "1.1.1.1"
  port = 8080,
  meta = { uri = "example"}
}
`
I want to use uri part in nginx conf. location part
When i changed location part , after this question 
[https://stackoverflow.com/questions/71486612/how-can-i-set-automaticly-registered-services-on-nginx-config-using-consul-templ/](url)  thanks to @blake .

`
location ^~ /{{  .ServiceMeta "uri" | sprig_title }}.asmx {
    proxy_pass http://{{ .Name }};
    proxy_redirect off;
  }
`
i'm getting error about "at <.ServiceMeta>: can't evaluate field ServiceMeta in type *dependency.CatalogSnippet".
In doc,[https://github.com/hashicorp/consul-template/blob/master/dependency/catalog_service.go](url)  parameter name is seems ServiceMeta. 

thanks,

**Comment by eikenb** [comment]
Hey @Zgrrl, thanks for the question.

In that stackoverflow post the template is looping over the data from `services` ([catalog_services.go](https://github.com/hashicorp/consul-template/blob/master/dependency/catalog_services.go)) not `service` ([catalog_service.go](https://github.com/hashicorp/consul-template/blob/master/dependency/catalog_service.go)). The `services` returns a very limited subset of data, only the name and tags (it mirrors the Consul API).

You can use the `.Name` field of the `services` to do a secondary lookup of more information on the service. Similar to the [services](https://github.com/hashicorp/consul-template/blob/master/examples/services.md) example.

Please let me know if you have any other questions.
Hope this helps.

**Comment by Zgrrl** [comment]
Hi  @eikenb ,
Thanks for your support.  We've too much service and we need to use `.Name` field for monitoring.
How can I use tags field ? When I update  consul-config to 
`"services": [
  {
    "id": "Svc0",
    "name": "Service",
    "port": 3307,
    "address": "1.1.1.1",
    "tags" : ["service1"]
    "checks": [
      {
      "http": "http://1.1.1.1:123/service1.asmx",
      "method": "GET",
      "interval": "10s",
      "timeout": "1s"
      }]
  }
  ]`
nginx config was like that.
`location ^~ /[service1].asmx `
Can i delete square brackets :) I just added tags directly to template as below

`location ^~ /{{ .Tags  }}.asmx {
    proxy_pass http://{{ .Name }};`

**Comment by eikenb** [comment]
Hey @Zgrrl,

You get the `[]` (square brackets) because `.Tags` is a a list of tags, known as a slice in Go. In the case of '[service1]' it is a list with only 1 entry. If you know it will **always** just have the 1 entry you can replace `/{{ .Tags }}.asmx` with `{{- range .Tags -}}{{- . -}}{{- end -}}.asmx`. Note the `-` (dashes) as they are what eliminates the whitespace padding normally added by the template language.

This would make that location line look like...
```
location ^~ /{{- range .Tags -}}{{- . -}}{{- end -}}.asmx { proxy_pass http:// {{- .Name -}}

```

This should get you what you want. If this doesn't work directly there are probably workarounds and feel free to ask more questions.

Hope this helps and thanks for using consul-template!

**Comment by Zgrrl** [comment]
Hi @eikenb,
Yes, it will just one value. I added this code and its work.
Thanks for your help.

**Comment by blake** [comment]
Hi @Zgrrl,

The following template collects all services in the catalog that have the metadata tag `uri`, and then generates a list of upstreams and locations for these hosts, grouped by the `uri` value.

```go
{{- /* Obtain list of services from the catalog */ -}}
{{- $servicesList := services -}}

{{- /* Dictionary to hold services grouped by URI */ -}}
{{- $servicesByURI := sprig_dict "" "" -}}

{{- /* Generate upstream configurations for each logical service */ -}}
{{- range $servicesList -}}
  {{- if and (ne .Name "consul") (.Name | contains "sidecar" | not) -}}

    {{- /*
      Obtain all services for specified .Name, regardless of health status.
      Group services by the metadata 'uri'
    */ -}}
    {{- $groupedServices := (service .Name "any" | byMeta "uri") -}}

    {{- range $uri, $services := $groupedServices -}}
      {{- /* Only process services with 'uri' metadata */ -}}
      {{- if ne $uri "_no_uri_" -}}

        {{- /* Create array item if this is the first entry in the map */ -}}
        {{- if not (sprig_hasKey $servicesByURI $uri) -}}
          {{- $_ := sprig_set $servicesByURI $uri $services -}}
        {{- else -}}
          {{- /* Append services to the existing list for this URI */ -}}
          {{- $currentList := index $servicesByURI $uri -}}
          {{- $newList := sprig_concat $currentList $services -}}
          {{- $_ := sprig_set $servicesByURI $uri $newList -}}
        {{- end -}}

      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

{{- /* Filter empty value that was used to initially create the dictionary */ -}}
{{- $filteredServices := sprig_omit $servicesByURI "" }}

{{- /* Render upstreams templates for each URI */ -}}
{{- range $uri, $services := $filteredServices }}
### Upstream configuration for URI {{ $uri }}
upstream uri_{{ $uri }} {
  zone upstream_for_uri_{{ $uri }} 128k;
  {{ range $services }}
  # Instance: {{ printf "%s-%s" .ID .Name }}

  {{- /* Mark the backend as down if the health status is critical */ -}}
  {{- $is_down := sprig_ternary " down" "" (eq .Status "critical") }}
  server {{ printf "%s:%d%s" .Address .Port $is_down -}};
  {{ end }}
}

{{- end }}

server {
  listen                443 ssl;
  server_name           domainname.com.tr;
  proxy_set_header      X-Forwarded-Port 443;
  ssl_certificate       /etc/nginx/tls/..crt;
  ssl_certificate_key   /etc/nginx/tls/..key;

  access_log /etc/nginx/log/gw/https/access.log;
  error_log /etc/nginx/log/gw/https/error.log;

  {{ range $uri, $services := $filteredServices }}
  location ^~ /{{ $uri | sprig_title }}.asmx {
    # Route requests to the upstream named uri_{{ $uri }}
    proxy_pass http://uri_{{ $uri }};
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  {{ end }}
}
```

Given the following service registration configuration…

```hcl
services {
  id = "svc1"
  name = "service1"
  address = "192.0.2.10"
  port = 8080
  meta = {
    uri = "example"
  }
}

services {
  id = "svc2"
  name = "service2"
  address = "198.51.100.20"
  port = 8081
  meta = {
    uri = "example"
  }
}

services {
  id = "svc3"
  name = "service3"
  address = "203.0.113.30"
  port = 8080
  meta = {
    uri = "example2"
  }
  check = {
    http = "http://203.0.113.30/Example2.asmx"
    method = "GET"
    interval = "10s"
    timeout = "1s"
  }
}
```

Consul template will render the following nginx configuration.

```nginx
### Upstream configuration for URI /example
upstream uri_example {
  zone upstream_for_uri_example 128k;
  
  # Instance: svc1-service1
  server 192.0.2.10:8080;
  
  # Instance: svc2-service2
  server 198.51.100.20:8081;
  
}
### Upstream configuration for URI /example2
upstream uri_example2 {
  zone upstream_for_uri_example2 128k;
  
  # Instance: svc3-service3
  server 203.0.113.30:8080 down;
  
}

server {
  listen                443 ssl;
  server_name           domainname.com.tr;
  proxy_set_header      X-Forwarded-Port 443;
  ssl_certificate       /etc/nginx/tls/..crt;
  ssl_certificate_key   /etc/nginx/tls/..key;

  access_log /etc/nginx/log/gw/https/access.log;
  error_log /etc/nginx/log/gw/https/error.log;

  
  location ^~ /Example.asmx {
    # Route requests to the upstream named uri_example
    proxy_pass http://uri_example;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  
  location ^~ /Example2.asmx {
    # Route requests to the upstream named uri_example2
    proxy_pass http://uri_example2;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  
}
```

I hope this configuration is close to what you were looking for.

**Comment by Zgrrl** [comment]
thank @blake so much. I can use this too. 
All of you have been very helpful, thanks again.
Have a nice day
