### ISSUE TITLE
how to iterate over map in sorted order of keys

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/consul-template#1560]
I have a suspicion that the **order of the services** returned is not same every time and hence the `IP:PORT` output is changing and causing a template re-render and thus a task restart (I am using Nomad)

Is there any way to coerce a "sorted by key" iteration of a Map?
(The second template is what I have tried so far)

### Consul Template version
 v0.26.0 (3b7f233a)

### Templates

```liquid
myvar=[[range $index, $service := service "myservice" ]][[if ne $index 0]],[[end]][[$service.Address]]:[[$service.Port]][[end]]
```

```liquid
[[- range $index, $service := service "myservice" -]]
[[- scratch.MapSet "test" $service.Address $service.Port -]]
[[- end -]]

myvar=[[- $dummy := 0 -]]
[[- range $key, $val := scratch.Get "test" -]]
[[- if ne $dummy 0 -]],
[[- else -]]
[[- $dummy = 1 -]]
[[- end -]]
[[- $key ]]:[[ $val -]]
[[ end ]]
```

### Command

```shell
consul-template -default-left-delimiter '[[' -default-right-delimiter ']]' -once -dry -template s1.ctmpl
```

**Comment by eikenb** [comment]
Hey @shantanugadgil, thanks for asking!

The template `range` should have deterministic lexical (alphabetical) ordering based on the keys of the dictionary with the caveat (quoted from the docs)...

    If the value is a map and the keys are of basic type with a defined order,
    the elements will be visited in sorted key order.

Based on the snippets you provided, they might seem unordered as it looks like the ordering would be done on `$service.Addresses` which might not be the most obvious in ordering and might even change (depending on setup).

Maybe use another field for the keys to get the ordering you want?

Hope this helps!

**Comment by shantanugadgil** [comment]
> Maybe use another field for the keys to get the ordering you want?

Ummm, I need the final variable as a list of `ip1:port1,ip2:port2,...`, so I am not sure how to restructure the original template to get a forced sorted output.

Also, minor detail I missed in the original query. I am using Nomad 1.2.6 and Consul 1.11.4. My template is part of Nomad, not a standalone CT usage.

**Comment by eikenb** [comment]
Here's an example using the first tag as the key and the full address:port as the value. Maybe something like this will work....


```
{{- range $idx, $srv := service "myservice" -}}
{{- $key := index $srv.Tags 0 -}}
{{- $val := printf "%s:%d" $srv.Address $srv.Port -}}
{{- scratch.MapSet "test" $key $val -}}
{{- end -}}
{{range $k, $v := scratch.Get "test" }}
:: {{$k}} {{$v}}
{{end}}
```

Hope this helps.
