### ISSUE TITLE
Changing destination file user and group is not working

### ISSUE THREAD

**Issue by voanhduy1512** [hashicorp/consul-template#1570]
Sorry to report issue against unreleased version, but I have been waiting for this feature for a long time. Currently I am using some complex systemd service + bash script that I hope I can remove if this feature works properly in consul-template 

### Consul Template version

Dev build at https://github.com/hashicorp/consul-template/commit/0012f40cc6293301decd1c39963ab8821c23f5df

### Configuration

key.tmpl
```liquid
{{ with secret "pki/issue/example-dot-com" "common_name=test.example.com" "alt_names=localhost" "ip_sans=127.0.0.1" "ttl=7d" }}
{{ .Data.private_key }}
{{ end }}
```
cert.tmpl
```liquid
{{ with secret "pki/issue/example-dot-com" "common_name=test.example.com" "alt_names=localhost" "ip_sans=127.0.0.1" "ttl=7d" }}
{{ .Data.certificate }}
{{ end }}
```
config.hcl
```hcl 
vault {
  address = "http://127.0.0.1:8200"
  renew_token = false
  ssl {
     enabled = false
   }
 }
template {
  user = "myusername"
  group = "users"
  source = "key.tmpl"
  destination = "key.pem"
}
template {
  user = "myusername"
  group = "users"
  source = "cert.tmpl"
  destination = "cert.pem"
}
```

### Command

```shell
consul-template -config config.hcl
```

### Expected behavior

`key.pem` and `cert.pem` should be created with correct user `myusername` and group `users`

### Actual behavior
The files are created with same user and group of the account running consul-template. 

I thought it could be a permission issue so I tried running it with:
- `CAP_CHOWN CAP_FOWNER` capabilities (https://man7.org/linux/man-pages/man7/capabilities.7.html)
-  root account

but the problem still happened.

**Comment by igor-nikiforov** [comment]
I have exactly the same case and can confirm that `user` and `group` does not work as expected with this case.

**Comment by eikenb** [comment]
Hey @voanhduy1512, thanks for filing this (and the related PR/fix).

Is including this in 0.29.0 enough or will anyone need a 0.28.2 bugfix release with this?

**Comment by voanhduy1512** [comment]
Thanks for checking, including this in 0.29.0 is enough for me, I don't need a bugfix release for this.
