### ISSUE TITLE
Consul template ignoring rendered file,  keeps generating certs at every reload or restart

### ISSUE THREAD

**Issue by Siamert** [hashicorp/consul-template#1597]
Please note that the Consul Template issue tracker is reserved
for bug reports and enhancements. For general usage questions,
please use the Consul Community Portal or the Consul mailing list:

    https://discuss.hashicorp.com/c/consul
    https://groups.google.com/forum/#!forum/consul-tool

Please try to simplify the issue as much as possible and include all the
details to replicate it. The shorter and simpler the bug is to reproduce the
quicker it can be addressed. Thanks.

### Consul Template version

Run `consul-template -v` to show the version. If you are not
running the latest version, please upgrade before submitting an
issue.

consul-template v0.29.1 (4525703)

### Configuration

```hcl
# Copy-paste your configuration files here. Only include what is necessary or
# what you've changed from defaults. Include all referenced configurations.

```
template {
  source      = "/etc/consul-template.d/nginxcert.tpl"
  destination = "/etc/nginx/certs/nginx.crt"
  perms       = 0755
  command     = "systemctl reload nginx"
}

template {
  source      = "/etc/consul-template.d/nginxkey.tpl"
  destination = "/etc/nginx/certs/nginx_key"
  command     = "systemctl reload nginx"
}

template {
  source      = "/etc/consul-template.d/test.tpl"
  destination = "/etc/consul-template.d/pki_cert.rendered.txt"
}

```liquid
# Copy-paste your Consul Template template here
```
template.hcl

nginxcert.tpl

{{ with secret "pki_int/issue/nginx" "ttl=200h" "common_name=foo.example.com" }}
{{ .Data.certificate }}
{{ .Data.issuing_ca }}{{ end }}

nginxkey.tpl

{{ with secret "pki_int/issue/nginx" "common_name==foo.example.com" "ttl=200h"}}
{{ .Data.private_key }}{{ end }}

test.tpl

{{- with pkiCert "pki_int/issue/nginx" "ttl=200h" "common_name=foo.example.com" -}}
Certificate: {{ .Cert }}
Private Key: {{ .Key }}
Authority: {{ .CA }}
{{ end }}

```liquid
# Include sample data you reference in the template from Consul or Vault here.
```

### Command

```shell
# Place your Consul Template command here
```

### Debug output

Provide a link to a GitHub Gist containing the complete debug
output by running with `-log-level=trace`.

### Expected behaviour
From this https://github.com/hashicorp/consul-template/issues/1259

What should have happened?

The rendered template file as a sort of cache for it, checking for template destination for a file on startup/reload and, if it finds one, loads the cert from there. If that certificate is still good it will use it, if it is expired or not there it will fetch a new one from Vault.

### Actual behavior

Consul template is ignoring the rendered file "pki_cert.rendered.txt",  the cert keep getting regenerated at every reload or restart

What actually happened?

The cert keeps getting regenerated.

### Steps to reproduce

1. Create the files as above
2. Restart consul template systemctl restart consul-template.service
3. nginx.crt and nginx.key getting regenerated and ignoring the generated file pki_cert.rendered.txt to be used as for the local cache.

### References

Are there any other GitHub issues (open or closed) that should
be linked here? For example:
- GH-1234
- ...

**Comment by Inotsacred** [comment]
Hi!
You use separate templates thats not communicate between themselves.
method secret still have old behaviour - render every time new secret.
you should use only pkicert for pki.


Try to use this construction with only one template.

```
template {
source = "/etc/consul-template.d/nginxcert.tpl"
destination = "/etc/nginx/certs/nginx.crt"
perms = 0400
command = "systemctl reload nginx"
}
```

/etc/consul-template.d/nginxcert.tpl
```
{{- with pkiCert "pki_int/issue/nginx" "ttl=200h" "common_name=foo.example.com" -}}
{{ .Cert }}
{{ .CA }}
{{ if .Key }}
{{ .Key  | writeToFile "/etc/nginx/certs/nginx.key" "root" "root" "0400" }}
{{ end }}
```

**Comment by Siamert** [comment]
> Hi! You use separate templates thats not communicate between themselves. method secret still have old behaviour - render every time new secret. you should use only pkicert for pki.
> 
> Try to use this construction with only one template.
> 
> ```
> template {
> source = "/etc/consul-template.d/nginxcert.tpl"
> destination = "/etc/nginx/certs/nginx.crt"
> perms = 0400
> command = "systemctl reload nginx"
> }
> ```
> 
> /etc/consul-template.d/nginxcert.tpl
> 
> ```
> {{- with pkiCert "pki_int/issue/nginx" "ttl=200h" "common_name=foo.example.com" -}}
> {{ .Cert }}
> {{ .CA }}
> {{ if .Key }}
> {{ .Key  | writeToFile "/etc/nginx/certs/nginx.key" "root" "root" "0400" }}
> {{ end }}
> ```

Hi
Neither certs nor key is generated now,  empty folder.

**Comment by eikenb** [comment]
I'm not sure why it is not generating files. Using what you have there and only tweaking for my system (shown below), your example works for me. I'd say double check your permissions and access to files/directories. Maybe something is going on there.

```
{{- with pkiCert "pki/issue/example-dot-com" "ttl=200h" "common_name=foo.example.com" -}}
{{ .Cert }}
{{ .CA }}
{{ if .Key }}
{{ .Key | writeToFile "./key.pem" "" "" "0644" }}
{{ end }}
{{ end }}
```

**Comment by Siamert** [comment]
> I'm not sure why it is not generating files. Using what you have there and only tweaking for my system (shown below), your example works for me. I'd say double check your permissions and access to files/directories. Maybe something is going on there.
> 
> ```
> {{- with pkiCert "pki/issue/example-dot-com" "ttl=200h" "common_name=foo.example.com" -}}
> {{ .Cert }}
> {{ .CA }}
> {{ if .Key }}
> {{ .Key | writeToFile "./key.pem" "" "" "0644" }}
> {{ end }}
> {{ end }}
> ```

Hi Working now forgot to add the token, one thing is the first time the service get reloaded or restarted the cert will get re-downloaded but with the same pub key and serial number but then it wont download again which is much better.  Thank you both appreciate it.

**Comment by eikenb** [comment]
Glad we could help! 

I'm going to close the ticket as you seem like you've got a handle on it now. If you have more, related questions I'll reopen it.

**Comment by Siamert** [comment]
> Glad we could help!
> 
> I'm going to close the ticket as you seem like you've got a handle on it now. If you have more, related questions I'll reopen it.

Perfect have great wknd.

**Comment by Inotsacred** [comment]
anyway i recommend you to use more least permissions for certificate files
