### ISSUE TITLE
trivy scanner is reporting CVEs

### ISSUE THREAD

**Issue by noorul** [hashicorp/consul-template#1614]
### Expected behavior

What should have happened?

Should not have had any CVEs

### Actual behavior

Found CVEs

<img width="1669" alt="Screenshot 2022-08-08 at 12 01 18 PM" src="https://user-images.githubusercontent.com/155376/183354066-983c8556-1f7e-4557-bcfb-4c0e66321ed0.png">

What actually happened?

### Steps to reproduce

1. trivy image --security-checks vuln hashicorp/consul-template:0.29.1

**Comment by noorul** [comment]
@eikenb Can we have a release?

**Comment by eikenb** [comment]
I'm giving the pkiCert issue a little time to respond and want to look into that dedup/exec issue but plan on getting a release out next week.

**Comment by jleemur-sonrai** [comment]
Also waiting for the official release
