### ISSUE TITLE
Support logging to syslog

### ISSUE THREAD

**Issue by tgwizard** [hashicorp/consul-template#163]
It would be great if consul-template could log to syslog, in the same way as consul does. I guess parts of the configuration and setup could be copied/ported from there, and that a rewrite of all places doing `log.Printf()` would be necessary.

**Comment by sethvargo** [comment]
@armon thoughts here?

**Comment by armon** [comment]
@sethvargo We already have a syslog library that you could use. (https://github.com/hashicorp/go-syslog). I think this makes sense.

**Comment by tiwilliam** [comment]
:+1:

**Comment by mfischer-zd** [comment]
If you're running it from runit, you can pipe it to syslog by using the following as your `log/run` script:

```
#!/bin/sh

exec /usr/bin/logger -t consul-template
```

We do this for many different services and it works fine, provided each log line is less than 8kB.  If you consistently have longer log lines, it's trivial to write a Perl/Ruby/Python script that reads lines from stdin and sends them to syslog.

**Comment by sean-** [comment]
Off topic, but it's not necessary to use logger to redirect log output to syslog.  From svlogd(8) http://smarden.org/runit/svlogd.8.html :

```
ua.b.c.d[:port]
tells svlogd to transmit the first len characters of selected log messages to the IP address a.b.c.d, port number port. If port isn’t set, the default port for syslog is used (514). len can be set through the -l option, see below. If svlogd has trouble sending udp packets, it writes error messages to the log directory. Attention: logging through udp is unreliable, and should be used in private networks only.
Ua.b.c.d[:port]
is the same as the u line above, but the log messages are no longer written to the log directory, but transmitted through udp only. Error messages from svlogd concerning sending udp packages still go to the log directory.
```

FYI.  If there's a compelling reason to use logger vs svlogd I'd be interested in hearing more about that.

**Comment by mfischer-zd** [comment]
We tried using svlogd for awhile, but:

1. It requires you enable a UDP listener on your syslog server; many ship with it turned off for security reasons.  logger(1) imposes no such requirement.
2. svlogd doesn't allow you to specify facility, severity, or program name; logger(1) does.

**Comment by sean-** [comment]
Ah, yup - all perfectly valid reasons, thanks for including them.  I've had writing an svlogd replacement on my personal todo list for ages, something faster at scanning for newlines and uses multiple threads.  Anyway.  Thanks.

**Comment by itheiss** [comment]
:+1:

**Comment by sethvargo** [comment]
This is done in 0fdf1a7
