### ISSUE TITLE
Update golang.org/x/text dependency to 0.3.7

### ISSUE THREAD

**Issue by jleemur-sonrai** [hashicorp/consul-template#1633]
### Consul Template version

`0.29.2`

### Expected behavior

No CVE's

### Actual behavior

Found CVE's

### Steps to reproduce

1. `trivy image --security-checks vuln hashicorp/consul-template:0.29.2`

<img width="1019" alt="Screen Shot 2022-08-17 at 12 31 01 PM" src="https://user-images.githubusercontent.com/107048648/185180541-f2a67e13-6a2b-44b5-b6d1-fc114575637a.png">

**Comment by eikenb** [comment]
This CVE does not impact consul-template and will be handled with normal dependency updates.

**Comment by eikenb** [comment]
Thanks for reporting it!

**Comment by noorul** [comment]
@eikenb Not sure why dependabot is not picking this up.

**Comment by eikenb** [comment]
My guess is dependabot doesn't bump indirect dependencies until the direct dependency bumps it. To put it another way, the dependency that depends on x/text hasn't bumped its version yet.

**Comment by noorul** [comment]
But when I do `got get -u` "golang.org/x/text" is getting updated to `golang.org/x/text v0.3.7 // indirect
`

**Comment by eikenb** [comment]
Could be that Dependabot also analyzes the code paths and found that consul-template doesn't use the features covered by the CVE (which is doesn't). If you check with the [govulncheck](https://go.dev/blog/vuln) it doesn't find any security issues either.

**Comment by noorul** [comment]
@eikenb Can we do as `go get -u` for the time being? I could have done this, but CLA requirement is stopping me.

**Comment by eikenb** [comment]
I can take care of it for the next release. Not worth it in the meantime as that CVE doesn't impact consul-template.

**Comment by eikenb** [comment]
> Not worth it in the meantime [..]

I mean its not worth cutting a release for it.

**Comment by eikenb** [comment]
New security scanner can't get past this either so I went ahead and forced the update. It will make it in the next release.

**Comment by noorul** [comment]
Thanks
