### ISSUE TITLE
Fetaure request: a way for consul-template to exit upon a failed key lookup

### ISSUE THREAD

**Issue by eikenb** [hashicorp/consul-template#1637]
Requested feature is pretty straightforward and is simply that they want consul-template to exit with an error if a key it is looking up in Consul does not exist. 

It should work with the `template_error_fatal` setting.

Look into making this cover all backends but only if simple. Otherwise keep this consul specific.

**Comment by eikenb** [comment]
Poked around this today trying to figure out the best solution. My current idea is to add a simple `error` template function that returns an error in a place that. Having a function that returns an error means you can use it with the keyExists function to dynamically check and trigger an error in the template. Eg.
```golang
{{ if not (keyExists "foo") }}
    {{ error "key foo doesn't exist" }}
{{end}}
```

**Comment by eikenb** [comment]
Oh.. and using the above with the `template_error_fatal` setting will achieve the goal of this enhancement request.

**Comment by eikenb** [comment]
That was naive. Templates always render once through with everything failing to look up. So any sort of exists check will always fail the first time triggering the error.

**Comment by eikenb** [comment]
Added it as a top level option that triggers the error on any data lookup that fails 2 fetch attempts. The error happens on the second attempt as the first attempt is a special case that does some setup.

Note that setting this disables retries for failed lookup attempt errors.

**Comment by akamensky** [comment]
Does not seem to work.

Template:

```
$ cat some.tpl 
{{ key "/does/not/exist" }}
```

Executing as:

```
$ consul-template -template-error-fatal -once -template "some.tpl:out.txt"
```

Hangs indefinitely. And I keep seeing in Consul logs:

```
2023-01-30T17:36:57.248+1100 [DEBUG] agent.http: Request finished: method=GET url="/v1/kv/does/not/exist?index=50&stale=&wait=60000ms" from=127.0.0.1:45502 latency=1m2.449311662s
```

**Comment by jlouros** [comment]
Hi @eikenb, any news about @akamensky comments? Do we know if `-template-error-fatal` is a valid cmd line argument?

Thanks
