### ISSUE TITLE
Question: Does this replace confd?

### ISSUE THREAD

**Issue by MrMMorris** [hashicorp/consul-template#167]
Also, good to see you around the non-Chef parts @sethvargo!

**Comment by sethvargo** [comment]
Hi @MrMMorris 

Thank you for your inquiry. You might be interested in [this entry in the FAQ](https://github.com/hashicorp/consul-template#faq), but the answer really varies depending on your setup. Depending on which parts of confd are important to you and your infrastructure, consul-template could replace confd if that is a desired goal. However, they can also live in harmony.
