### ISSUE TITLE
Support Cluster Peering in the service / services API functions

### ISSUE THREAD

**Issue by jcjones** [hashicorp/consul-template#1694]
Consul 1.14 added support for Cluster Peering, and the new [`peer` parameter for the `/health` API endpoint](https://developer.hashicorp.com/consul/api-docs/health#peer) to access imported services.

It would be natural for consul-template to support the new `peer` parameter for the `service` and `services` API functions. This would allow consul-template to offer imported services in configuration files

The current `service` function syntax is:

```
{{ service "<TAG>.<NAME>@<DATACENTER>~<NEAR>|<FILTER>" }}
```

Perhaps simply double-@s like `@@<PEER>`, or a character like `!<PEER>` would suffice and stay short, or add convention for `peer=<PEER>`?

The code changes for this seem to be mostly in https://github.com/hashicorp/consul-template/blob/main/dependency/health_service.go.

**Comment by blake** [comment]
Support for querying peered services was added by #1822.
