### ISSUE TITLE
CPU-bound managing 31 config files and 1200 keys

### ISSUE THREAD

**Issue by gdhbashton** [hashicorp/consul-template#171]
Hi,

Running `0.6.0` on an AWS EC2 `t2.medium` instance with config as per title, `consul-template` burns all available CPU and only updates the managed config files very sporadically.

A run of `consul-template -config /etc/consul-template/config.json -dry -once` does not complete even after letting it run for 10 minutes. If I add `CONSUL_TEMPLATE_LOG=info` to the commandline I am treated to a endless torrent of runner was missing NN dependencies / brain checking if key has data / watcher adding key.

This doesn't sound like expected behaviour - how can I help make it better?

Cheers,
Gavin.

**Comment by sethvargo** [comment]
@gdhbashton can you join the discussion in https://github.com/hashicorp/consul-template/issues/168 please? It sounds like the exact same issue.

Please note that, even if we fix the N^2 performance, watching 1200 keys is never going to be performant and you're probably going to DDoS your Consul instance. Please [see my response here](https://github.com/hashicorp/consul-template/issues/165#issuecomment-70862099) for a more-detailed explanation of why that is the case.
