### ISSUE TITLE
How to list all services

### ISSUE THREAD

**Issue by Dkhusainov** [hashicorp/consul-template#1715]
Now I'm only able to list service{s) by their name. I want to list every single service that's available at `/v1/agent/services`. How can I do that? I'm thinking of something like ```{{ range service "*" }}```

**Comment by air3ijai** [comment]
@Dkhusainov,

Is the example from the [Use case: discover all services](https://developer.hashicorp.com/consul/tutorials/developer-configuration/consul-template#use-case-discover-all-services) what you are looking for?
```go
{{ range services -}}
# {{ .Name }}
{{- range service .Name }}
{{ .Address }}
{{- end }}

{{ end -}}
```

```
consul-template -template t.tpl -dry -once
>
# consul
10.10.183.71

# wireguard
10.10.5.253
10.10.68.29
```

**Comment by Dkhusainov** [comment]
> @Dkhusainov,
> 
> Is the example from the [Use case: discover all services](https://developer.hashicorp.com/consul/tutorials/developer-configuration/consul-template#use-case-discover-all-services) what you are looking for?
> 
> ```go
> {{ range services -}}
> # {{ .Name }}
> {{- range service .Name }}
> {{ .Address }}
> {{- end }}
> 
> {{ end -}}
> ```
> 
> ```
> consul-template -template t.tpl -dry -once
> >
> # consul
> 10.10.183.71
> 
> # wireguard
> 10.10.5.253
> 10.10.68.29
> ```

Yes. Didn't know you can use `.Name` as an input to `service`. Should probably include it in the README of this repository. Thanks!

**Comment by air3ijai** [comment]
Looks like we may found something useful in the [examples](../tree/main/examples) - [Querying all services with Consul Template](../blob/main/examples/services.md#querying-all-services-with-consul-template).
