### ISSUE TITLE
Support Cluster Peering with Consul Template

### ISSUE THREAD

**Issue by Esity** [hashicorp/consul-template#1810]
Currently, Consul Template supports querying across federation links to other datacenters but has no docs and appears to not support querying services from peering connections which seems silly

https://github.com/hashicorp/consul-template/blob/2d446f0d8c37626a7bebcce9ef46877e99f1d57c/docs/templating-language.md?plain=1#L200-L230

I don't see a good reason on why we wouldn't add this in as a supported thing considering federation is going away
Example PR talking about querying consul via DNS for peering
https://github.com/hashicorp/consul/blob/3332f63c4c00592e186843df85df9a5d0241cf7b/website/content/docs/services/discovery/dns-static-lookups.mdx#L102-L110

**Comment by blake** [comment]
@Esity Support for listing peers and querying services from peers was implemented in #1822 and #1869, and is available in the recent releases of Consul template.
