### ISSUE TITLE
`make build` not working, returns "No rule to make target `build'"

### ISSUE THREAD

**Issue by hlung** [hashicorp/consul-template#1818]
Quick question.
After downloading the source code, I run `make build` as instructed in readme, but got this error.

```
➜  consul-template git:(main) make build
make: *** No rule to make target `build'.  Stop.
```

I am in the correct directory, same directory as Makefile.

Am I missing something.

**Comment by roncodingenthusiast** [comment]
You are right, instructions in the readme are outdated as the `build` rule was removed a couple of versions back. I'd suggest using `make dev`

**Comment by roncodingenthusiast** [comment]
updated readme to ensure other folks don't run into this, https://github.com/hashicorp/consul-template/pull/1824. Thank you for reporting this

**Comment by hlung** [comment]
cool. thanks bro.

**Comment by JasVXR** [comment]
> Hi all,
> 
> trying to make code by punching in "make dev" which creates the following error;
> 
> ```
>     "$ make dev
>     make: *** No rule to make target 'dev'.  Stop."
> ```
> 
> What would be the solution for this?

i'm also seeing the same

**Comment by JasVXR** [comment]
> Hi all,
> 
> trying to make code by punching in "make dev" which creates the following error;
> 
> ```
>     "$ make dev
>     make: *** No rule to make target 'dev'.  Stop."
> ```
> 
> What would be the solution for this?

I got this working by first "Run without debugging" on the file first to create the "filename.c" then I ran the make filename in the terminal and it created my binary file. Hopefully this helps?
