### ISSUE TITLE
Address from API CatalogService

### ISSUE THREAD

**Issue by bryantidd** [hashicorp/consul-template#185]
When will you pull the address from the HashiCorp Consul API catalog.go CatalogService, instead of from the Node? This is important as the address in the CatalogService maybe very different from that of the Node.

Thanks
Very willing to test this change
Bryan

**Comment by sethvargo** [comment]
Hi @bryantidd,

I apologize, but I do not understand what you are asking. Which of the Consul HTTP API endpoints would you like to see implemented?

We currently have `service`, which talks to the `/health` endpoint, and `services`, which talks to the `/catalog` endpoint. What exactly are you trying to do?

**Comment by vixns** [comment]
I guess @bryantidd means #186

**Comment by bryantidd** [comment]
Yes, something like that would be great. I forked and implemented by adding ServiceAddress to HealthService struct...I think there would be times when someone might want both addresses, The node address and and actual service address. 

I am running docker based services, running a forked version of https://github.com/progrium/registrator to update Consul 0.5.0rc1 that has implemented Address as part of service. I need that address instead of the node address when templating nginx and other configs that need to reach back to the docker host:port. 

I hopes this helps.
