### ISSUE TITLE
Bad behavior when consul is inaccessible

### ISSUE THREAD

**Issue by tailhook** [hashicorp/consul-template#190]
Hi,

I have a slighly badly behaved consul, i.e. it often loses leadership and does new election (because disks are too overloaded on machine), but let's ignore consul issues. consul-template should work anyway. But instead it generates too much requests per second and never repairs (AFAICS even if consul is ok ATM). First I see the following errors:
```
2015/02/11 17:10:48 [ERR] (view) key "some/path" Unexpected response code: 500
2015/02/11 17:10:48 [ERR] (view) storeKeyPrefix "some/path" consul returned nil qm; this should never happenand is probably a bug in consul-template or consulapi
2015/02/11 17:10:48 [ERR] (view) key "some/path" Unexpected response code: 500
2015/02/11 17:10:48 [ERR] (view) storeKeyPrefix "some/path" consul returned nil qm; this should never happenand is probably a bug in consul-template or consulapi
2015/02/11 17:10:48 [ERR] (view) key "some/path" Unexpected response code: 500
```
Then following:
```
2015/02/11 17:26:48 [ERR] (view) key "some/path" Get http://127.0.0.1:8500/v1/kv/some/path?wait=60000ms: dial tcp 127.0.0.1:8500: cannot assign requested address
2015/02/11 17:26:48 [ERR] (view) storeKeyPrefix "some/path" consul returned nil qm; this should never happenand is probably a bug in consul-template or consulapi
2015/02/11 17:26:48 [ERR] (view) key "some/path" Get http://127.0.0.1:8500/v1/kv/some/path?wait=60000ms: dial tcp 127.0.0.1:8500: cannot assign requested address
2015/02/11 17:26:48 [ERR] (view) storeKeyPrefix "some/path" consul returned nil qm; this should never happenand is probably a bug in consul-template or consulapi
```
And two groups of log messages repeat. In total it's about **6000** messages per second.

I have consul v0.4.1-184-g9f9087b (was master from some time ago) and consul-template v0.6.5.

I might need to update consul itself. But behaviour of consul-template seems to be wrong nevertheless.

**Comment by sethvargo** [comment]
@tailhook what does your template look like?

**Comment by tailhook** [comment]
The relevant part of template is:
```
{{ $config := key "some/path" | parseJSON }}
```

But I just noticed that it failed when consul was running with `-bootstrap-expect 2` but `consul join` never run. I.e. I think it never had a leader. (I didn't notice it earlier because I was looking at UI in second consul instance which displays data).

**Comment by sethvargo** [comment]
@tailhook could you please let me decide which parts of your template are relevant? If you only give me part of your template, I can only debug part of your issue. I understand you might be frustrated, but let's try to keep the Consul and Consul Template issues separate. If you have a Consul-specific issue, please post it on the Consul repo or ask on the Consul mailing list.

**Comment by tailhook** [comment]
> @tailhook could you please let me decide which parts of your template are relevant? If you only give me part of your template, I can only debug part of your issue.

Well, let me say it other way. I can reproduce same issue on the template displayed above.

> I understand you might be frustrated, but let's try to keep the Consul and Consul Template issues separate. If you have a Consul-specific issue, please post it on the Consul repo or ask on the Consul mailing list.

Sure, I'm not frustrated. I'm just saying that easiest way to reproduce this consul-template issue is to start consul with `-server -bootstrap-expect 2` and not issue a `consul join` command.

**Comment by sethvargo** [comment]
@tailhook the default retry value is "0s" if you do not specify a retry interval when running to command. What happens if you specify a retry interval in your CT config or on the CLI?

**Comment by sethvargo** [comment]
@tailhook I just verified this myself locally using your template. If you specify `-retry 5s` on the command line or `retry "5s"` in your Consul Template config, the request will sleep for 5 seconds before trying again.

I have pushed up https://github.com/hashicorp/consul-template/pull/191 which will change the default value from "0" to something more reasonable.

**Comment by tailhook** [comment]
Great! Thanks for quick response.
