### ISSUE TITLE
consul-template package does not install consul-template.service

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/consul-template#1946]
How to reproduce:
Follow this tutorial: https://github.com/hashicorp/learn-nomad-cluster-setup/pull/29/files#diff-8861620391a76415cf718872544b7f3f71cd2b33e69d1db8530da092938a6291R81

```
$ dpkg --listfiles consul-template
/usr
/usr/bin
/usr/bin/consul-template

$ dpkg --listfiles consul
/etc
/etc/consul.d
/etc/consul.d/consul.env
/etc/consul.d/consul.hcl
/usr
/usr/bin
/usr/bin/consul
/usr/lib
/usr/lib/systemd
/usr/lib/systemd/system
/usr/lib/systemd/system/consul.service
/usr/share
/usr/share/doc
/usr/share/doc/consul
/usr/share/doc/consul/LICENSE.txt

$ sudo systemctl status consul-template
Unit consul-template.service could not be found.
```

**Comment by tgross** [comment]
@EugenKon there is no `consul-template.service`, nor is one necessary to run Nomad because Nomad runs consul-template internally as part of the `template` runner. In fact, I'd be surprised if you were to find consul-template being installed or invoked directly in any of the tutorial.

**Comment by tgross** [comment]
@EugenKon I'd encourage you to open an issue in that repo.

**Comment by tgross** [comment]
Turns out I don't have permissions to that repo to transfer this issue. So yeah, go ahead and open an issue there, and whomever owns that repo can deal with that.

**Comment by EugenKon** [comment]
I almost opened it

**Comment by qd3v** [comment]
@EugenKon there's one problem: `consul-template` can be used outside Nomad. This tiny file (you are correct, I was surprised not to find it in deb package) can save thousands of hours for people creating ansible task to upload it to their servers. FreeBSD maintainers [did this](https://cgit.freebsd.org/ports/tree/textproc/consul-template/files/consul-template.in?id=f6d390a579295eca8de08bd589c55c788a27d35e#n10)

**Comment by schematis** [comment]
I was hit by this issue just now and was able to grab the service file from the link above. For a specific example of use outside of Nomad (per @qd3v), it can be used for [rotating certs sourced from Vault for mTLS](https://developer.hashicorp.com/consul/tutorials/operate-consul/vault-pki-consul-secure-tls#configure-consul-template), which is my use case.
