### ISSUE TITLE
Index KV data in template

### ISSUE THREAD

**Issue by etuttle** [hashicorp/consul-template#202]
Say I had some extra per-node data in a KV tree like /weights/node_name.  I wish I could query this entire tree with a single watch:

```
{{$weights := tree "/weights"}}
```

And then lookup the per-node keys while looping over services:

```
{{range service "release.webapp"}}
    {{$weight := or (index $weights (print "/weights/" .Node)) 100}}
    server {{.Node}} {{.Address}}:{{.Port}} weight {{$weight}}{{end}}
```

It doesn't work because `tree` returns a slice, not a map: `error calling index: cannot index slice/array with type string`.

One idea is a `byKey` function that indexes the result of `tree` by they Key property of each entry:

```
{{$weights := tree "/weights" | byKey}}
```

Probably better would be a treeMap function that is similar to tree, but returns a map of subkeys under the lookup path.  This would make the map less clunky to index:

```
{{$weights := treeMap "/weights"}}
{{range service "release.webapp"}}
    {{$weight := or (index $weights .Node) 100}}
    server {{.Node}} {{.Address}}:{{.Port}} weight {{$weight}}{{end}}
```

**Comment by etuttle** [comment]
Third option... if tree just returned a map, would it break any existing templates?  I see this in the go template docs for `range`:

> If the value is a map and the keys are of basic type with a defined
> order ("comparable"), the elements will be visited in sorted key order.

**Comment by sethvargo** [comment]
@etuttle does https://github.com/hashicorp/consul-template/pull/209 solve your use case?

**Comment by etuttle** [comment]
I was hopeful and I just tried it out, but not quite!  I'm trying to use go template's `index` function to lookup a single value from a map, which was queried from the KV store using a single watcher.  The new byKey function returns a map whose values are a slice of (Key, Value) objects, so looking up a single value by its key isn't possible.

I looked at what @hoffoo is trying to do in #209.  If there was a way to query a tree structure out of the KV (maps whose values are either maps or strings, which is the data model of KV if I understand correctly), both of our use cases would work.  His use case would look like this:

```
### groups
{{range $group, $hosts := tree "groups/"}}           # $hosts is a map of hostname -> ''
define hostgroup {
    hostgroup_name {{$group}}
    members {{range $host, $empty}}{{$host}},{{end}}
}
{{end}}

### services
{{range $service, $checks := tree "services/"}}     # $checks is a map of check -> '' (?)
{{range $check, $empty := $checks}}
define service {
    use generic-service
    check_command {{$check}}
    service_description {{$service | toTitle}}
    servicegroups {{$service}}
}
{{end}}{{end}}
```

My use case would look like:

```
{{$weights := tree "/weights"}}                     # $weights is a map of node -> weight
{{range service "release.webapp"}}
    {{$weight := or (index $weights .Node) 100}}
    server {{.Node}} {{.Address}}:{{.Port}} weight {{$weight}}{{end}}
```

And we could use go template's dot notation! ($tree.key1.key2)

That's my plug for a way to query maps out of the KV! :)
