### ISSUE TITLE
Support populating configuration directories with a common template

### ISSUE THREAD

**Issue by ryanbreen** [hashicorp/consul-template#204]
I'm interested in deprecating fsconsul in favor of consul-template.  I created fsconsul at a time when CT didn't exist; while it has worked out well for our purposes, CT is clearly a better way forward because you have to do all the work.

One thing I'm having a hard time mapping, though, is a model for emerging multiple files based on the same template without needing a priori knowledge of the keys that might be used.  As a concrete example, it's pretty common that an application will take a directory of files as its configuration, as with Consul's `-config-dir`.  Ideally, people could add or remove configuration files in these directories just by touching KVs.

For this use case, it seems easiest to have a single template file that you apply recursively to keys sharing a given path.  Each key would get rendered to a separate file.  In this way, configuration files can get added and the app can get reloaded as KVs are changed, without the template needing to be pinned to the specific keys that might be used.  This is particularly useful because the template, which lives on the systems that need to be configured, is inherently more difficult to modify than are Consul's KVs.

Is there already a way to do this with consul-template?  If not, is this an enhancement you would consider?

**Comment by sethvargo** [comment]
Do `tree` and `ls` not satisfy this constraint? I'm not sure I understand the requirement here

**Comment by ryanbreen** [comment]
Both of those operators work within the context of a single generated file, right?  What I'm looking for is a way to apply `tree` or `ls` to the generation of multiple files, one per key.

**Comment by ryanuber** [comment]
It sounds like what @ryanbreen is asking for (correct me if I am mistaken) is a way to basically mirror a consul K/V hierarchy onto the filesystem using consul-template. AFAIK, this would not work right now, since you need to pre-configure consul-template with template inputs and file outputs.

@ryanbreen is there a specific use case you have where you can't create a more monolithic configuration file, but auto-generated with consul-template? To me it seems like that would be a fairly easy way to go about configuring something like Consul.

**Comment by sethvargo** [comment]
Why would you want to do that though? 

The general use case for ".d" directories is so CM and similar tools can avoid partial file content updates. It seems weird to me that you would want to go the other way given you already manage the entire file.

Consul Template really isn't designed to behave this way or accommodate this use case. 

What you _could_ do is run multiple instances of Consul Template, one that writes all the keys to a file, and another that pushes that file out to some `xargs` that spawns n watcher instances. That's horribly performant both from an OS-perspective and DDoSing your Consul install. 

If you're already using a .d style directory, I don't understand the use case. Why not just write the entire contents of the file out?

**Comment by ryanbreen** [comment]
@ryanuber, yes, that's exactly what I'm looking for, and that's the challenge I ran into when trying to map fsconsul's current behavior on to CT.

Yeah, .d makes life easier for CM, and I particularly like the granularity and isolation it provides to config changes.  If you're supporting multiple teams who need to add logstash config to their apps, for example, and one team borks their config, it's really nice if that hoses a single file in logstash/config.d rather than _the_ single file in logstash/config.d.  Someone on Team B messes up and adds an unclosed filter and suddenly no one gets logs. 

So it's not entirely accurate to say that I manage the entire file.  I manage infrastructure allowing teams to configure their own services.  I would prefer to do so in a way that minimizes their ability to step on each others' toes.  One option is to tightly constrain the things you allow to be output in your templates, but then you're shackling the configuration options exposed to teams to whatever we put in the template (and odds are teams have a better idea how they want to use logstash than I do, so I would hate to constrain them).

**Comment by ryanbreen** [comment]
Another use-case we have is for management of OAuth creds.  Each cred needs to be its own file.  It's really nice having Consul manage these as KVs: the speed of getting those changes propagated around the network is awesome.  It would be nice if we could just use Consul Template to splat out these files if any change.

This is just to say that there are at least a couple of real-world use-cases where configuration as discrete files seems nice.

**Comment by sethvargo** [comment]
Hi @ryanbreen,

The more I think about this, coupled with the conversations I've had with @ryanuber, I do not think Consul Template is the right tool for your use case. 

The overall purpose and goal of Consul Template is to take dependencies (like key prefixes and services) and apply them to a single template that is rendered to disk. In this way, CT is an n->1 mapping n dependencies to one output. What you're requesting is a 1->n mapping - 1 dependency with n outputs. Consul Template is not designed to support a 1->n, and it would be an entirely different implementation than the current (whilest the current would need to remain enact for the existing use case CT solves). For this reason, we will not be implementing this feature in CT.

The good news, however, is that I have abstracted large components of Consul Template into packages that are easily shared with our other Consul-related tooling like envconsul and Consul Replicate. You can use the `watch` and `dependency` packages to create a library/tool that fits your particular use case and share it with the community. I would be happy to add your tool to the Consul community tools page.

I'm sorry that we won't be implanting this feature, but it is too far out of scope for Consul Template.

**Comment by ryanbreen** [comment]
Thanks, Seth. I'll look at updating fsconsul to use those packages.

**Comment by sean-** [comment]
Random thought/partial solution: use consul-template to render out an `mtree(1)` specification and apply with `mtree(1)`.  Similar awful can be achieved by creating a `shar(1)` file.  I don't fully understand the specifics, but there are some unix utilities that sound like they'd get you closer to your objective.

**Comment by ryanbreen** [comment]
@sean-, some of the clients are on Windows, and I don't have much control over the stuff installed on those systems (read: saying "install Cygwin or MinGW to get Unix tools" is a non-starter).  Unfortunately, that means I need a cross-platform solution.

**Comment by clstokes** [comment]
I think it's short-sighted to completely take this off the table as "out of scope for Consul Template". It seems a natural expectation that a tool that takes N values out of Consul could render N files from a template. Modern tools (such as Consul) are meant to handle dynamic environments and to have to have static bindings of 1-to-1 file mappings is limiting.

Just my two cents obviously - still love you all for the work and tools you've provided us! :heart_eyes:

**Comment by sethvargo** [comment]
Hi @clstokes thank you for your feedback. I do not think the use case is invalid by any means, just out of scope. There's definitely a use case for mapping values from a Consul query onto n-files on the filesystem, but that is not Consul Template's objective. Instead CT aims to bring all that data into a single template that contains all of that information, possible mutated or aggregated in some way.

I think the tool you are describing is fundamentally a _different_ tool than Consul Template, and it looks like @ryanbreen's [fsconsul](https://github.com/Cimpress-MCP/fsconsul) is a really great solution. I am happy to work with Ryan to utilize the watch libraries that are provided by Consul Template in fsconsul and answer any questions he may have along the way :smile:.

**Comment by memelet** [comment]
In scope or out, another use case that I was hoping to use consul-template or envconsul for is: 

I need to start dependent services based on the presence of other services (1-1 in this case). I was hoping to watch for all services under a prefix/tag and start/stop the dependent service with configuration based on the dependee service.
