### ISSUE TITLE
ls with sub-directories

### ISSUE THREAD

**Issue by hoffoo** [hashicorp/consul-template#207]
If I have a directory groups/ with another level of directories under it:

```
{{range ls "groups/"}}
     members {{range ls (print "/groups/" .Key)}}{{.Key}},{{end}}
{{end}}
```

Doing this kind of thing with the tree command is actually pretty hard (ie: Id have to do some weird replacing, and the range loop would be much less simple)

The reason that this doesn't work is that consul-template doesn't return directories.  Would it be possible to do something like this? Even if the value would be empty and the key would only be the the name of the directory, its still a really nice way to iterate subdirs.

**Comment by hoffoo** [comment]
I guess this is here: https://github.com/hashicorp/consul-template/blob/master/template_functions.go#L113 

Does it make sense to make the "/" check optional? Or maybe have a dir command (dumb name i know) that only returns sub-directories at the key?

**Comment by sethvargo** [comment]
@hoffoo what do you mean by "does not return directories"?

I would caution your current template - it is going to create N+1 entires for each service as opposed to a single watcher on a prefix. You will be creating N independent queries on Consul which could be bad.

What exactly are you trying to accomplish here? If you better explain your use case, I can probably provide a better recommendation.

**Comment by hoffoo** [comment]
@sethvargo with the "no directories" bit i mean that ls only returns top level keys. That makes sense to me, what I would like though is range over a list of keys that aren't the top level.

Here is my use case, with keys like this:

```
/group/elasticsearch/es1
/group/elasticsearch/es2
/group/redis/redis1
```

I would like to loop /group and have only two keys returned, elasticsearch and redis. I was planning on having a second ls range that would get the contents of /group/elasticsearch and /group/redis, thanks for explaining why that isnt very efficient.

Is there a better way to do this? Originally I was using tags but ended up with a lot of tags for different things and it got complicated, also the kv is much clearer.

**Comment by sethvargo** [comment]
@hoffoo can we take a step back though - what is your _use case_? What is the end result you are trying to achieve? I understand what your code is trying to do, but I want to understand what _you_ are trying to do :smile:.

**Comment by hoffoo** [comment]
Right okay, we collect facts about hosts in consul whenever our provisioning tools do stuff (setup a new service or whatever). Specifically this is for nagios, we have groups of hosts and I want to be able to add host a to a group by putting a key somewhere (not by appending to a list or something like that).

For it to work I need to iterate a list of groups first, and aftwarwards get all the keys in each one.
