### ISSUE TITLE
Connecting to consul based on DNS SRV record

### ISSUE THREAD

**Issue by mthenw** [hashicorp/consul-template#213]
Hi,

I running following setup:

* Container 1 - consul serving DNS server for all containers
* Container 2,3 - application hosts
* Container 4 - HAProxy with consul-template load balancing between application hosts

Because consul and consul-template are not running in the same container I need to connect to consul using ip and external docker port. Is there a way to provide only hostname "consul.service.consul" and consul-template would internally query DNS server and connect to one of consul instances?

**Comment by sielaq** [comment]
Consul registered himself with server RPC port (default is 8300), so this could be problematic for counsul-template.since it use API port (default 8500).

But If you haven't changed consul default API port (8500) it suppose to work with option
"-consul=consul.service.consul:8500".

If you have changed, then 
what you could do is to register your consul_api in consul as a new service and write a wrapper for consul-template to get the PORT via ``dig consul_api.service.consul SRV`` command.

**Comment by mthenw** [comment]
Currently I do 
```/bin/consul-template  -consul `dig +search +noall +answer consul.service.consul SRV | awk '{printf("%s:%d\n", $8, $7)}'` ... ```
but it's not perfect (e.g. requires `dig`).

My point is that would be cool to support SRV records in consul-template.

**Comment by sethvargo** [comment]
Hrm. This is a tough one. A little bit of background:

> Consul Template uses the [HTTP API](https://consul.io/docs/agent/http/agent.html) long-polling to watch dependencies for changes. Basically, CT makes an HTTP request and Consul blocks on that request until data changes. Consul Template then does some data munging and provides an API to the template.

I do not think Consul exposes SRV records via the HTTP API. @armon do you think you could chime in here? I think we may need some upstream changes in Consul to support this (if you think this is a good idea).

**Comment by mthenw** [comment]
@sethvargo probably I'm not clear enough :) it still should use HTTP API, but when `-consul` value ends with .service.consul it should query DNS for SRV record and then make an API call to one of consul instances.

IMHO, there is no need to change consul.

**Comment by sielaq** [comment]
@sethvargo 
If @mthenw re-maped default ports (when using docker net bridge mode - I assume he does since he have "consul as default DNS server for all containers"), 
It would NOT be even possible. How consul would know what is a port mapping. In his case you need to have external ports so to reflected by SRV query.

**Comment by mthenw** [comment]
Exactly @sielaq. I start consul container with `-p 172.17.42.1:53:53/udp`.

**Comment by armon** [comment]
The SRV port is still problematic since that contains the RPC port, and not the HTTP port that is available, so I'm not sure if it helps. I think using the DNS name with a well-known port as suggested by @sielaq would work however.

**Comment by sielaq** [comment]
@armon, how about this:  
would it be possible, that consul register some internal ports with tag? 
Then accessing them via DNS would be:
``dig api.consul.service.consul SRV`` -> (default you would get instances with 8500)
``dig server_rpc.consul.service.consul SRV`` -> (default you  would get instances with 8300)

but this require change in consul behavior. is it a "BIG" change in consul ?
how compatible would it be when doing consul upgrade?

Then @sethvargo could implement SRV in consul-template.

@mthenw , but still, those are internal ports. What you would need to do then is re-map those ports to  exactly the same external ports by docker - or you could use ``net host`` mode ( **not** ``net bridge``  anymore) in docker.  (If your external ports are assigned fully dynamic, which I doubt, then you need to register consul api by yourself - like a new service - consul_api and external ports)

**Comment by mthenw** [comment]
As I have only one consul per docker instance I've decided to publish 8500 port as 8500 in docker so I don't need to get it from DNS.
