### ISSUE TITLE
Service name based on ENV variable

### ISSUE THREAD

**Issue by mthenw** [hashicorp/consul-template#214]
Is there a way to declare `range service` with service name based on ENV variable?

**Comment by sielaq** [comment]
Maybe this example gonna help you:

``export FOO='["bar"]'``

```
{{with $foo := env "FOO" | parseJSON }}
  {{ range $foo }}
    #{{.}}
    {{ range service .}}
      {{.}}
    {{ end }}
  {{end}}
{{end}}
```

Probably this can be done easier :smile:  but I know only this complicated one :smile:

**Comment by mthenw** [comment]
Thanks @sielaq, but I was thinking about something more elegant :)

**Comment by sielaq** [comment]
ok just playing few seconds with it you can do it like that:

``export FOO='bar'``

```
{{with $foo := env "FOO" }}
  {{ range service $foo}}
    {{.}}
  {{ end }}
{{end}}
```

**Comment by mthenw** [comment]
Maybe not ideal, but acceptable, thanks @sielaq

**Comment by ryanuber** [comment]
This could probably be condensed even further, like this:
```
{{range service (env "FOO")}}{{.}}{{end}}
```

@mthenw If the "not ideal" comes from the extra `with` statement, then this might help.

**Comment by mthenw** [comment]
@ryanuber, yeah, this one is better, thanks.
