### ISSUE TITLE
--config with empty directories

### ISSUE THREAD

**Issue by hoffoo** [hashicorp/consul-template#215]
When passing --config we tend to send a few directories and a base config file. Sometimes one of the directories could be empty if we don't have templates to be ran yet.

Does it make sense to lift the restriction [here](https://github.com/hashicorp/consul-template/blob/master/runner.go#L799) that the directories contain at least one file?

**Comment by armon** [comment]
This makes sense to me, Consul does not require that the -config-dir contains any files either.
