### ISSUE TITLE
Troubles with byKey and key function within range loop

### ISSUE THREAD

**Issue by clstokes** [hashicorp/consul-template#217]
Per a request from Armon, I'm duplicating my group post from https://groups.google.com/forum/#!topic/consul-tool/uxhm1oGmf54 into this issue.

Given these K/V entities:
```
/databases/main/url         = mainUrl
/databases/main/username    = mainUsername
/databases/main/password    = mainPassword

/databases/backup/url       = backupUrl
/databases/backup/username  = backupUsername
/databases/backup/password  = backupPassword
```
I'm trying to generate this file:
```
main:
  url: urlMAIN
  username: mainUsername
  password: mainPassword
  
backup:
  url: urlBACKUP
  username: backupUsername
  password: backupPassword
  ```
Borrowing ideas from https://groups.google.com/d/msg/consul-tool/BTDUN6mopRw/6mw3E0rSlLYJ, I tried this template:
```
{{range $key, $pairs := tree "databases" | byKey}}
{{ $key }}:{{with $url := printf "databases/%s/url" $key }}
  url:  {{ key $url }}
  #urlPath: {{ $url }} <- for troubleshooting purposes
{{end}}{{end}}
```
The output is completely empty, though in the debug log I can see it fetches the key successfully. Interestingly, if I remove the `{{ key $url }}` call, I get the output I would expect based on that template:
```
{{range $key, $pairs := tree "databases" | byKey}}
{{ $key }}:{{with $url := printf "databases/%s/url" $key }}
  #urlPath: {{ $url }} <- for troubleshooting purposes
{{end}}{{end}}
```
output:
```
backup:
  #urlPath: databases/backup/url <- for troubleshooting purposes

main:
  #urlPath: databases/main/url <- for troubleshooting purposes
```
The log output from both of these runs is here - https://gist.github.com/clstokes/d8948b2b2c5e7c8b45d4. I'm using consul-template v0.7.1.dev (0171aa07d).

What am I missing or doing wrong?

**Comment by armon** [comment]
Cross-linking to https://github.com/hashicorp/consul-template/issues/211, since I think they are related. @clstokes I don't think you are doing anything wrong, I think you are hitting a bug.

Currently @sethvargo is on vacation, but we will investigate this. Thanks for reporting.

**Comment by sethvargo** [comment]
This is the same as #211 and unfortunately I haven't found the race condition yet. Let's track that issue to keep everything in one place though :smile:
