### ISSUE TITLE
SSL Verify doesnt works as expected

### ISSUE THREAD

**Issue by raulSevilla** [hashicorp/consul-template#219]
I have a consul server with a self-signed ssl certificate. Im running consul-template with ssl-verify=false and it gives me an error like:
```
Get https://<ip_address>/v1/kv/proxy_pass?token=<token>&wait=60000ms: x509: cannot validate certificate for <ip_address> because it doesn't contain any IP SANs
```

My consul-template command is the next:
```
./consul-template -ssl ssl-verify=false -consul <ip_address> -token <token> -log-level=debug -template "apache2.tmpl:final.tmpl"
```

**Comment by sethvargo** [comment]
@armon is this a bug in the HTTP a client itself?

**Comment by ryanuber** [comment]
@raulSevilla could you verify the command? It looks like you might just be mis-using the ssl options. Specifically:

```
-ssl ssl-verify=false
```

**should** be:

```
-ssl -ssl-verify false
```

Note the `-` before `ssl-verify`.
