### ISSUE TITLE
Basic authentication wrong behaviour

### ISSUE THREAD

**Issue by raulSevilla** [hashicorp/consul-template#220]
Executing consul-template with basic authentication flag seems to not work well.
Here is my consul-template command:

```
./consul-template -consul <consul_addr> -token <token>  -template "apache2.tmpl:final.tmpl" -once   -config=config.json -auth='user:password'
```
My consul server is located behind a proxy http server. Looking for consul-template traces, i found that auth headers are incorrect:

```
[12/Mar/2015:08:36:21 +0000] VQFQBQoAABcAAAZtOuIAAAAP 10.3.0.18 24874 10.3.0.25 80
--ab4g2d48-B--
GET /v1/kv/value?token=8fa14cdd34f3419e719291234fe7&wait=60000ms HTTP/1.1
Host: consul.com
User-Agent: Go 1.1 package http
Authorization: Basic Og==
Accept-Encoding: gzip

[rsevilla@rsevilla consul-docker]$ echo "Og==" | base64 -d
:
```

**Comment by sethvargo** [comment]
Hi @raulSevilla 

I'm sorry you are having issues. Could you please describe your setup a bit more? The auth flags are for consul, not a proxy.
