### ISSUE TITLE
SSL Configuration overwritten after merging DefaultConfig

### ISSUE THREAD

**Issue by ChrisAubuchon** [hashicorp/consul-template#228]
The command:
```consul-template -ssl -ssl-verify  -consul <ip> -template <template> -log-level=debug``` 
sends HTTP instead of HTTPS requests to consul.

After some digging, it looks like the SSL configuration is overwritten in runner.go with the default configuration via `r.config.Merge(DefaultConfig())`

**Comment by sethvargo** [comment]
Potentially a duplicate of #219

**Comment by ChrisAubuchon** [comment]
Possibly but I'm not even getting to the certificate validation. It's not even trying to use SSL since by the time newAPIClient is called, r.config.SSL.Enabled = false.
