### ISSUE TITLE
When node drops and comes back, template not rewritten

### ISSUE THREAD

**Issue by jefferai** [hashicorp/consul-template#233]
I have three haproxy instances being configured from a template using consul-template. The relevant portion of the template is:
```
frontend ft_poml_vip
    bind :80

    {{range services}}{{if ne .Name "consul"}}{{range service .Name}}
    acl host_{{.Name}} hdr_beg(host) -i {{.Name}}
    use_backend be_{{.Name}} if host_{{.Name}}
    {{end}}{{end}}{{end}}

{{range services}}{{if ne .Name "consul"}}{{range service .Name}}
backend be_{{.Name}}
    server {{.Node}} {{.Address}}:{{.Port}} check
{{end}}{{end}}{{end}}
```
The corresponding configuration is:
```
template {
    source = "/etc/haproxy/haproxy.cfg.ctmpl"
    destination = "/etc/haproxy/haproxy.cfg"
    command = "chmod 644 /etc/haproxy/haproxy.cfg && service haproxy reload"
}
```
A number of services are coming from a node that (for reasons I haven't figured out yet, but aren't important here) loses connectivity now and again; from the host where the Consul server is and consul-template is running:
```
    2015/03/19 03:56:35 [INFO] serf: EventMemberLeave: registry 10.88.24.2
    2015/03/19 03:56:35 [INFO] consul: member 'registry' left, deregistering
    2015/03/19 03:56:37 [INFO] serf: EventMemberJoin: registry 10.88.24.2
    2015/03/19 03:56:37 [INFO] consul: member 'registry' joined, marking health alive
    2015/03/19 08:41:32 [INFO] serf: EventMemberLeave: registry 10.88.24.2
    2015/03/19 08:41:32 [INFO] consul: member 'registry' left, deregistering
    2015/03/19 08:41:33 [INFO] serf: EventMemberJoin: registry 10.88.24.2
    2015/03/19 08:41:33 [INFO] consul: member 'registry' joined, marking health alive
    2015/03/19 14:18:23 [INFO] serf: EventMemberLeave: registry 10.88.24.2
    2015/03/19 14:18:23 [INFO] consul: member 'registry' left, deregistering
    2015/03/19 14:18:25 [INFO] serf: EventMemberJoin: registry 10.88.24.2
    2015/03/19 14:18:25 [INFO] consul: member 'registry' joined, marking health alive
```
When this happens, the template is rewritten without any services from registry represented in it. It is *not* then written when the node comes back.

There is no output from consul-template to stdout or stderr other than from haproxy itself receiving the reload command.

For announcing to Consul, I'm using `registrator`; it actually is ensuring that the services are announced every thirty seconds:
```
2015/03/19 16:16:22 [INFO] agent: Synced service 'registry:ramlsnarf:8000'
2015/03/19 16:16:22 [INFO] agent: Synced service 'registry:docbrowse:80'
2015/03/19 16:16:22 [INFO] agent: Synced service 'registry:docbrowse:443'
2015/03/19 16:16:22 [INFO] agent: Synced service 'registry:registry:5000'
2015/03/19 16:16:22 [INFO] agent: Synced service 'registry:aiab:8080'
2015/03/19 16:16:52 [INFO] agent: Synced service 'registry:ramlsnarf:8000'
2015/03/19 16:16:52 [INFO] agent: Synced service 'registry:docbrowse:80'
2015/03/19 16:16:52 [INFO] agent: Synced service 'registry:docbrowse:443'
2015/03/19 16:16:52 [INFO] agent: Synced service 'registry:registry:5000'
2015/03/19 16:16:52 [INFO] agent: Synced service 'registry:aiab:8080'
```
But consul-template does not pick up on this, presumably because it thinks that it already has the correct state represented.

I have played around with no wait, with half a second, and with two second wait times; currently my start command is:
```
exec /usr/local/bin/consul-template -config="/etc/consul-template" -wait 2s
```
It's possible I need even more wait, but 2 seconds is already getting to the point where reactions are happening slower than they ought to.

The only way for me to fix this problem so far is to restart consul-template regularly.

**Comment by sethvargo** [comment]
Looks like a duplicate of https://github.com/hashicorp/consul-template/issues/198. Can you confirm?

**Comment by jefferai** [comment]
I've been aware of that issue, which is why I tried different sleep values, but the sleep values suggested by @armon in that issue did not help.

Also, the underlying cause may be the same, but may be different; in that case specific services are being toggled and in this case it is node availability being toggled, which does necessarily affect service availability but may have other concerns within consul-template(?).

If you think this is the same exact issue, feel free to mark duplicate and close it and I'll watch the other one.

**Comment by sethvargo** [comment]
The fact that there's no log output or anything from Consul Template leads me to believe that the edge triggering in Consul is not happening when the same nodes/services are removed and re-added later. 

If Consul was releasing the long-poll, we would see a debug message that new data was received from the server, but that never happens. /cc @ryanuber

**Comment by jefferai** [comment]
Ah -- good point. I need to turn on debug logging. I'll do that and report back when this happens again.

**Comment by ryanuber** [comment]
Hmm, the log messages with `Synced service` indicate a change to its definition, which seems odd. If the definition had not changed, these INFO-level messages would not appear, and instead in DEBUG-level you would see something like `Service x is in sync`. I do think the debug logs will help here, so @jefferai if you could provide those that would be useful. Thanks!

**Comment by jefferai** [comment]
There is no change to the definition; `registrator` allows you to have it re-sync the services it is announcing every X seconds. I have that turned on, partially because I was hoping it would help with this problem.

I have debug now turned on with `consul-template`; if nothing useful comes out of that I can turn on debug in `consul` itself.

**Comment by ryanuber** [comment]
@jefferai got it, that makes sense then. The logs will definitely help in that case, especially the Consul logs if available.

**Comment by jefferai** [comment]
It seems I can even trigger this by having Terraform tear down a Docker container and restart it (for instance, with a new image). Obviously that happens quite quickly, but every time I do it I need to restart consul-template.

A gist of this behavior with all relevant information is here:

https://gist.github.com/jefferai/32d950c10e66853b9624

Let me know if I can provide anything else.

**Comment by sielaq** [comment]
seems like same problem to mine, I was able to exclude Registrator
in #198 and wrote a dummy script to reproduce it (inside 198).
same motive:  

```
{{range services}}
  {{range service .Name}}
   ...
  {{end}}
{{end}}
```

I was also able to workaround it via "template for a template":
https://github.com/eBayClassifiedsGroup/paas-in-a-box/blob/master/infrastructure/haproxy/template.conf

execution of double templating:

https://github.com/eBayClassifiedsGroup/paas-in-a-box/blob/master/infrastructure/haproxy/supervisord.conf

sorry for spam

**Comment by jefferai** [comment]
@sielaq It does seem at this point like the same problem...probably the node going down and coming up is a red herring and the real problem is just the services going down and back up. Possibly with enough of a delay (> 2 seconds) I might get it to work stably. But it's also possible that it's just an ordering problem and no amount of delay will help.

I did see your workaround and may try it myself as soon as I get a chance.

**Comment by jefferai** [comment]
I can confirm at this point that @sielaq 's workaround works for the case where I take a single service down and back up in my Terraform provider. Also, the simple test case @sielaq posted is the exact paradigm I was using, which is in fact *exactly* the use case from the readme: https://github.com/hashicorp/consul-template#querying-all-services

I will report back once my node loses connectivity again and see if it fixes the problems when the whole node goes down and comes back up (in which case it will definitely be a duplicate of #198 and I will mark it as such).

**Comment by jefferai** [comment]
OK, after seeing the node drop and come back everything is still working, so I'm marking this as a duplicate of #198. Sorry about the noise.
