### ISSUE TITLE
consul-template --version should return 0

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul-template#234]
I read your comment in https://github.com/hashicorp/consul-template/blob/master/cli.go#L75-L82
But, IMHO, this should behave the same as it's behaving in Consul. Return 0 and make our scripting lives easier.

**Comment by c4milo** [comment]
Inconsistency I'm talking about:

![](https://cldup.com/LL7_mo4NmF.png)

**Comment by ryanuber** [comment]
Hmm, this makes sense to me. I think @c4milo is right. All of our tools are currently printing this to stdout. Also tried some UNIX tools like grep, awk, tree, and a few others, and they also print to stdout. @sethvargo was there any other reason we were doing this?

**Comment by sethvargo** [comment]
From the spec:

> Standard error is another output stream typically used by programs to output error messages or diagnostics.

IMO, "version" is a diagnostic message and therefore should output to stderr. Git, Java, and many other Unix tools that I looked at all use stderr for version output.

In my testing, the command still returns 0 - the output just isn't stdout. Why not just redirect?

```shell
consul-template -version 2>&1 | grep "v0.7"
```

**Comment by mitchellh** [comment]
@ryanuber Most of our tools print the version to stdout but @sethvargo is correct that the general UNIX tool actually uses stderr for the the reasons he brought up. Given that, I really think either is correct/fine here. I defer.

**Comment by c4milo** [comment]
I originally thought it was returning non-zero. But, redirecting stderr to stdout is not a problem to me. I can live with that. Thanks!

**Comment by sethvargo** [comment]
Awesome. I'm glad we got everything figured out :smile:
