### ISSUE TITLE
About consul-template configuration log problem

### ISSUE THREAD

**Issue by lindane** [hashicorp/consul-template#235]
consul-template version 0.7.0、consul version 0.5.0、haproxy version 1.5.2

Clustered environment for three server, one agent.
server address: 192.168.2.71,192.168.2.72,192.168.2.73
agent address: 192.168.2.37

1.install rsyslog
2.mkdir /var/log/consul-template
3.Configuring rsyslog
Add rsyslog configuration file local5.*    /var/log/consul-template/consul-template.log
Open udp port
4.Rsyslog configuration complete，Restart rsyslog service：systemctl restart rsyslog
5.Run the command as follows：
consul-template -consul 192.168.2.71:8500 -syslog=true -syslog-facilitg=“LOCAL5” -template “/tmp/haproxy.ctmpl：/etc/haproxy.cfg：service haproxy restart”
6.haproxy successful configuration and start success
7./var/log/consul-template directory is empty,Do not print out the log.
issue：consul-template configutation correctly?Haproxy configuration log is successful.Description rsyslog configuration is no wrong.misconfigure？

**Comment by sethvargo** [comment]
Hi @lindane 

It looks like the command you are running may have a typo. Instead of:

```shell
-syslog-facilitg="LOCAL5"
```

I think you want:

```shell
-syslog-facility="LOCAL5"
```

Notice the spelling of "facility". Can you please try that and report if there is still an issue?

**Comment by lindane** [comment]
I'm sorry，This is my mistake，Test command is as follows：
consul-template -consul 192.168.2.71:8500 -syslog=true -syslog-facility="LOCAL5" -template "/tmp/haproy.ctmpl:/etc/haproxy/haproxy.cfg:service haproxy reload"

consul-template log directory is empty.

Configure rsyslog and start  consul-template，The need for other operations?Log files will be generated？

**Comment by sethvargo** [comment]
Hi @lindane 

I am unable to reproduce this issue on Ubuntu 12.04. Steps I took:

1. Install rsyslog:

        $ apt-get install rsyslog -y

1. Add the configuration to the rsyslog:

        $ echo "local5.* /var/log/consul-template/consul-template.log" > /etc/rsyslog.d/consul-template.conf

1. Restart rsyslog:

        $ service rsyslog restart

1. Install CT:

        $ wget https://github.com/hashicorp/consul-template/releases/download/v0.7.0/consul-template_0.7.0_linux_amd64.tar.gz
        $ tar -xvf consul-template_0.7.0_linux_amd64.tar.gz
        $ mv consul-template_0.7.0_linux_amd64/consul-template /usr/local/bin/

1. Run CT:

        $ consul-template -consul demo.consul.io -syslog=true -syslog-facility="LOCAL5" -template "test.ctmpl:out.txt" -log-level info

1. Stop CT

1. Inspect the log:

        $ cat /var/log/consul-template/consul-template.log
        2015/03/23 14:39:46 [INFO] (runner) creating new runner (dry: false, once: false)
        2015/03/23 14:39:46 [INFO] (runner) creating consul/api client
        2015/03/23 14:39:46 [INFO] (runner) creating Watcher
        2015/03/23 14:39:46 [INFO] (runner) starting
        2015/03/23 14:39:46 [INFO] (runner) running
        2015/03/23 14:39:46 [INFO] (runner) was not watching 1 dependencies
        2015/03/23 14:39:46 [INFO] (watcher) adding "service(consul [passing])"
        2015/03/23 14:39:46 [INFO] (runner) diffing and updating dependencies
        2015/03/23 14:39:47 [INFO] (view) "service(consul [passing])" received data from consul
        2015/03/23 14:39:47 [INFO] (brain) remembering "service(consul [passing])"
        2015/03/23 14:39:47 [INFO] (runner) running
        2015/03/23 14:39:47 [INFO] (brain) recalling data for "service(consul [passing])"
        2015/03/23 14:39:47 [INFO] (brain) recalling data for "service(consul [passing])"
        2015/03/23 14:39:47 [INFO] (runner) diffing and updating dependencies
        ^CReceived interrupt, cleaning up...
        2015/03/23 14:39:50 [INFO] (runner) stopping
        2015/03/23 14:39:50 [INFO] (watcher) stopping all views
        root@precise64:~/consul-template_0.7.0_linux_amd64# cat /var/log/consul-template/consul-template.log Mar 23 14:39:46 precise64 consul-template[23544]: (runner) creating new runner (dry: false, once: false)
        Mar 23 14:39:46 precise64 consul-template[23544]: (runner) creating consul/api client
        Mar 23 14:39:46 precise64 consul-template[23544]: (runner) creating Watcher
        Mar 23 14:39:46 precise64 consul-template[23544]: (runner) starting
        Mar 23 14:39:46 precise64 consul-template[23544]: (runner) running
        Mar 23 14:39:46 precise64 consul-template[23544]: (runner) was not watching 1 dependencies
        Mar 23 14:39:46 precise64 consul-template[23544]: (watcher) adding "service(consul [passing])"
        Mar 23 14:39:46 precise64 consul-template[23544]: (runner) diffing and updating dependencies
        Mar 23 14:39:47 precise64 consul-template[23544]: (view) "service(consul [passing])" received data from consul
        Mar 23 14:39:47 precise64 consul-template[23544]: (brain) remembering "service(consul [passing])"
        Mar 23 14:39:47 precise64 consul-template[23544]: (runner) running
        Mar 23 14:39:47 precise64 consul-template[23544]: (brain) recalling data for "service(consul [passing])"
        Mar 23 14:39:47 precise64 consul-template[23544]: (brain) recalling data for "service(consul [passing])"
        Mar 23 14:39:47 precise64 consul-template[23544]: (runner) diffing and updating dependencies
        Mar 23 14:39:50 precise64 consul-template[23544]: (runner) stopping
        Mar 23 14:39:50 precise64 consul-template[23544]: (watcher) stopping all views

There are two things you may need to check:

1. **log-level** - by default, Consul Template logs _warnings only_. If you want Consul Template to log info and debug messages, you need to specify the `-log-level` flag as I did above.
2. Try without systemd.

**Comment by lindane** [comment]
Thank you,Very detailed，in the virtual machine inside consul-template logs are no problem.But there is an error in the docker container，the error message is as follows：

Consul Template returned errors:
error setting up syslog logger: Unix syslog delivery error

1.docker container execute commands as follows：

/bin/consul-template -consul 192.168.2.71:8500 -syslog=true -syslog-facility="LOCAL5" -log-level info -template "/etc/consul-template/haproxy.ctmpl:/etc/haproxy/haproxy.cfg:service haproxy reload"

 -sysylog=true and -syslog-facility=“LOCAL5”parameters are not configured can not go wrong.

**Comment by lindane** [comment]
Thank you.Please close this issue，I'll open another one issue.
