### ISSUE TITLE
Syslog on configuring consul-template in the docker container

### ISSUE THREAD

**Issue by lindane** [hashicorp/consul-template#237]
docker version 
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

consul-template version 0.7.0,haproxy version 1.5.2

1.run docker container，Container installed rsyslog and consul-template and haproxy

2.Into the container configuration rsyslog

<pre><code>$ echo "local5.* /var/log/consul-template/consul-template.log" >> /etc/rsyslog.conf</code></pre>

3.Restart rsyslog:

<pre><code>$ service rsyslog restart</code></pre>

4.Restart haproxy

<pre><code>$ service haproxy restart</code></pre>

4.Run consul-template:

<pre><code>$ /bin/consul-template -consul 192.168.2.71:8500 -syslog=true -syslog-facility="LOCAL5" -log-level info -template "/etc/consul-template/haproxy.ctmpl:/etc/haproxy/haproxy.cfg:service haproxy reload"</code></pre>

The error message is as follows：

<pre><code>$ Consul Template returned errors:
error setting up syslog logger: Unix syslog delivery error</code></pre>

5.-syslog and -syslog-facility not specified，Command is as follows：

<pre><code>$ /bin/consul-template -consul 192.168.2.71:8500  -log-level info -template "/etc/consul-template/haproxy.ctmpl:/etc/haproxy/haproxy.cfg:service haproxy reload"</code></pre>

consul-template startup success

issue:In docker container inside consul-template configuration problem or consul-template configuration logging does not support  in container docker?

**Comment by sielaq** [comment]
your problem is that you are not using a proper tools to spawn it / (re)start it.
You cannot just do "service haproxy restart" - probably there is no init.
Moreover if rsyslogd was running already - restarting it will not work -  because the /var/run/rsyslogd.pid  is never clean up - because - if you check your process list (after restart), there is a Zombie <defunct> - isn't there ?. 

Which means there is no arbiter like init / supervisord.

So in your current rsyslogd is not running at all, remove the pid file /var/run/rsyslogd.pid.  And try again - you will see that rsyslog is running and write logs.

How to fix that:
use for example supervisord:
```
[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autorestart=true
user=root
```
or better why not using supervisord build in logging ?

**Comment by sielaq** [comment]
btw. don't use  /etc/syslog.conf  - because it is not read by default.
Rather use /etc/rsyslog.d/consul-template.conf

**Comment by sethvargo** [comment]
Hey @sielaq thank you for answering those questions.

@lindane does @sielaq's response make sense/

**Comment by lindane** [comment]
Operating system:  centos 6
Check the process list，no Zombie.Same error.

centos 6 rsyslog configuration file is /etc/rsyslog.conf
ubuntu rsyslog configuration file is /etc/esyslog.d/.Is not it?

Virtual machines can be configured inside the log is successful，The docker not.

**Comment by sielaq** [comment]
Dude, maybe I'm stupid, but not too much, to not recognize, that you have changed question :)
First, your question was:
``
echo "local5.* /var/log/consul-template/consul-template.log" > /etc/syslog.conf
``
and now you now you have edit comments for:
``
 $ echo "local5.* /var/log/consul-template/consul-template.log" >> /etc/rsyslog.conf
``
yea you can use /etc/rsyslog.conf and /etc/rsyslog.d/* both are supported by Ubuntu and Centos6
(checked on rsyslog-5.8.10-10.el6_6.x86_64.rpm CentOS 6.6)

and I cannot reproduce your error on docker tutum/centos:centos6 - it works beautiful.

**Comment by sielaq** [comment]
@lindane I have also check for you pure centos6 from https://registry.hub.docker.com/_/centos/
also works fine. I really assume that you have destroyed you basic configuration by 
`... > /etc/rsyslog.conf` (thats why you should used `/etc/rsyslog.d/your.conf` ) 
so now rsyslog is not running.

please reinstall your rsyslog `yum reinstall rsyslog` and try again.
also check if its running (ps / ptree whatever)

**Comment by lindane** [comment]
We are sorry,This is my mistake，
Adding content is as follows：
<pre><code>$ echo "local5.* /var/log/consul-template/consul-template.log" >> /etc/rsyslog.conf</code></pre>


1.dockerfile as follows:
<pre><code># Haproxy Dockerfile
# Pull base image.
FROM centos:centos6

# Install Haproxy.
RUN yum -y install haproxy rsyslog tar

 
# Add files.
ADD rsyslog.conf /etc/rsyslog.conf
ADD consul-template_0.7.0_linux_amd64/consul-template /bin/consul-template
ADD run.sh /root/run.sh

# Define mountable directories.
VOLUME ["/etc/haproxy","/etc/consul-template","/var/log/haproxy","/var/log/consul-template"]

# Define working directory.
WORKDIR /etc/haproxy

CMD ["/bin/bash", "/root/run.sh"]</code></pre>

2.run.sh as follows:
<pre><code>#!/bin/bash

service rsyslog restart
service rsyslog status | grep -w "running"
if [ $? -ne 0 ]; then
        exit 1
fi
service haproxy restart
service haproxy status | grep -w "running"
if [ $? -ne 0 ]; then
        exit 2
fi

/bin/consul-template -consul ${ConsulServerIP} -syslog=true -syslog-facility="LOCAL5" -log-level ${LogType} -template "/etc/consul-template/haproxy.ctmpl:/etc/haproxy/haproxy.cfg:service haproxy reload"</code></pre>

3.rsyslog.conf Add the following:
<pre><code>local1.*						/var/log/haproxy/haproxy.log
local5.*						/var/run/log/consul-template/consul-template.log</code></pre>

4.The following two-line comment open(rsyslog.conf):
<pre><code>$ModLoad imudp
$UDPServerRun 514</code></pre>

5.build docker image
<pre><code>docker build -t="dockerfile/haproxy" .</code></pre>

6.Start docker container
<code><pre>docker run -d -it --net=host -e ConsulServerIP="192.168.2.71:8500" -e LogType=info -v /data/LB/conf/consul-template/:/etc/consul-template/ -v /data/LB/conf/haproxy/:/etc/haproxy/ -v /data/LB/logs/haproxy/:/var/log/haproxy/ -v /data/LB/logs/consul-template/:/var/log/consul-template dockerfile/haproxy /bin/bash</code></pre>

7.Into the container
<pre><code>docker exec -it (Container ID) /bin/bash</code></pre>

8.Run run.sh script
<pre><code>sh run.sh</code></pre>

The error message is as follows:
<pre><code>Consul Template returned errors:
error setting up syslog logger: Unix syslog delivery error</code></pre>

issue:Well above where there are problems?
Thank you！

**Comment by sielaq** [comment]
1. to exclude problems with permission end external resources, can you first, disable VOLUME in Dockerfile , build it again 
```
# Define mountable directories.
#VOLUME ["/etc/haproxy","/etc/consul-template","/var/log/haproxy","/var/log/consul-template"]
```
and start without mounting them.

2. same, exclude ``#ADD rsyslog.conf /etc/rsyslog.conf``  in Dockerfile and try with the one which is delivered with rsyslogd. You can add your options:
```
RUN echo "local5.* /var/log/consul-template/consul-template.log" >> /etc/rsyslog.conf
```
This is how I could do it  (because I have no your config & devices ) and it worked.

**Comment by lindane** [comment]
Thank you very much,log configuration is successful,problem solving

Thanking
