### ISSUE TITLE
should consul agent be run with template?

### ISSUE THREAD

**Issue by MrMMorris** [hashicorp/consul-template#248]
I noticed that the consul-template config only allows for specifying one IP. Is it recommended that a consul agent is run on the same instance as template and then the template config points to the local agent? Or else what if the single consul server that template was pointing to went down?

**Comment by ryanuber** [comment]
@MrMMorris in most cases we have an agent running on each node in client mode. Client mode in Consul has a reduced set of responsibilities and is relatively light-weight, so this is always a safe route to take. However, if you don't have a local Consul agent running, you could also go the route of pointing to `consul.service.consul`, which should always resolve to a healthy Consul server node. This assumes that the machine is set up to resolve the .consul domain.

Hope that helps!

**Comment by sethvargo** [comment]
Hi @MrMMorris 

Did @ryanuber's response answer your question?

**Comment by MrMMorris** [comment]
@sethvargo yes, thanks @ryanuber ! I ddin't even know about the consul.service.consul. Very useful
