### ISSUE TITLE
Add option for byTag for the CatalogService as well

### ISSUE THREAD

**Issue by split3** [hashicorp/consul-template#249]
Currently we have the byTag for the HealthService but it would be nice to have the same for the CatalogService as well.  That way I can group and filter on the services in the Catalog without creating a watch on them if I don't actually need them.

I'm happy to add this feature if you think it is of value.  I found that it reduced the number of watches down as I could query all the services in the catalog and regex on their tags now grouped and skip them if they don't match or then actually query the HealthService (creating the watch) if they did.

**Comment by split3** [comment]
Hey @sethvargo 

Since there is no method overloading in go do you have any preferences to the name, byTagCatalogService?

**Comment by sethvargo** [comment]
Hi @split3. I think we will want to use an interface here instead of adding another template function.

**Comment by split3** [comment]
Sounds good, I'll make those modifications

**Comment by sethvargo** [comment]
Yea, I'm thinking of having a `Taggable` or `HasTags` interface that requires a `Tags()` function. Then just update the method signature :)

**Comment by split3** [comment]
Yea that is the direction I was heading

**Comment by split3** [comment]
Won't be able to use the function name `Tags()` as there is already a field called `Tags`.  How about something like `GetTags()`?

**Comment by sethvargo** [comment]
@split3 that or `TagsList()`

**Comment by split3** [comment]
It seems as though this change (though it originally seemed simple) is a little harder to make than I expected. Running into issues with converting automatically (which it seems Go doesn't support unless I'm missing something) `[]*HealthService` to something like `[]Taggable`.

**Comment by sethvargo** [comment]
@split3 ^ ended up doing that

**Comment by split3** [comment]
Ha, that is exactly what I just come around to as well.

**Comment by split3** [comment]
Wasn't sure if that would be "acceptable" with all the type erasing by using `interface{}`.  Thanks for jumping in and helping out.  I'm still getting used to `go`
