### ISSUE TITLE
Q: How to conditional omit range-items?

### ISSUE THREAD

**Issue by psi-4ward** [hashicorp/consul-template#252]
Can i omit some range-items depending of the existence in another range?

something like 
```
foreach($range2 as $item): 
  if( ! $range1.hasVal($item)) continue;
```

its for generating HAProxy config.
* Backends rendered from services with tag "http"
* Fronends rendered from the KV store
* HAProxy config gets invalid if a `use_backend` statement references an unknowen backend so i would just drop any invalid use_backend

**Comment by sethvargo** [comment]
Hi @psi-4ward 

To the best of my knowledge, this is not currently possible given Go's templating language - [text.template](http://golang.org/pkg/text/template/).

If you could convert the contents of `$range1` to a map (using the `byKey` function for example), you could do something like this (psuedo-code):

```liquid
{{ range $item := $range2 }}
{{ if index $range1 $item }}
{{$item.Name}}
{{ end }}
{{ end }}
```

**Comment by psi-4ward** [comment]
I thought that, probalby ill try something like

```go
{{range $v1 := s1}}
  {{range $v1 := s2}}
    {{if eq $v1 $v2}}
      Hello
    {{ end }}
  {{end}}
{{end}}
```

**Comment by sethvargo** [comment]
Yea, that would work too. Sounds like you found a solution! :smile:. Let me know if I can be of further help.
