### ISSUE TITLE
get the last registered node of a service

### ISSUE THREAD

**Issue by ezyk** [hashicorp/consul-template#259]
Hello,
i am using 
````
{{range service "web"}}
    server  {{.Address}}:{{.Port}};
{{end}}
```
To iterate all the nodes of the of the service *web*. The array that the *service* function returns how  is it ordered?  Can i get the last registered node of the service? I am using consul-template to rewrite an nginx config file. Every time a new docker container is created , i want the nginx proxy to point to the new container. 

Thanks

**Comment by sethvargo** [comment]
Hi @ezyk 

Services are sorted by their [Node and then ID fields](https://github.com/hashicorp/consul-template/blob/master/dependency/health_service.go#L353-L360) using a stable sort. The Consul API does not expose the time when a particular node was registered - the following fields are available:

```
Node        string
NodeAddress string
Address     string
ID          string
Name        string
Tags        ServiceTags
Status      string
Port        uint64
```

In general, with service discovery, you want to proxy to all available nodes, not just the most recently created one. If you know the name of the node, you can filter by it. You can get the last node in the list by using the `index` function, but unfortunately that is the last node by name, not by creation time.

**Comment by sethvargo** [comment]
Hi @ezyk 

I just wanted to follow up and see if you had any questions about my response above. Please let me know if there is anything I can clarify.

**Comment by sethvargo** [comment]
Hi @ezyk 

I am going to close this issue, but if you are still having problems, please comment and I will re-open it. Thanks! :smile:
