### ISSUE TITLE
Get services by multiple tags

### ISSUE THREAD

**Issue by piavlo** [hashicorp/consul-template#260]
For example i want to get all cassandra seed nodes in production environment
afaiu something like `{{service "seed.production.cassandra" "any"}}` is not possible currently.
How complex would it be to add support for selecting service by several tags?

ps. I know that i can just add compound tag like "seed-production" then registering the node
but would strongly prefer to avoid doing this.

**Comment by sethvargo** [comment]
Hi @piavlo 

In this example, we recommend getting all the services and then filtering by the list of tags:

```liquid
{{range service "cassandra"}}
{{if or .Tags.Contains("production") .Tags.Contains(seed) }}
{{.Address}}
{{end}}
{{end}}
```

Does that work for you?

**Comment by sethvargo** [comment]
Hi @piavlo 

I just wanted to follow up and see if that solution worked for you.

**Comment by kevwil** [comment]
I've been searching for a similar behavior, so I tried this example using service names and tags we use, and I'm getting a syntax error right where the first parenthesis begins.

```
unexpected "(" in operand; missing space?
```

**Comment by sethvargo** [comment]
Ah yes, you might need the parenthesis for grouping.

**Comment by weitzj** [comment]
This is a really nice feature. Could you add it to the documentation?

**Comment by scalp42** [comment]
@sethvargo @kevwil the `or` is confusing me. Does it include `production` *and* `seed` ?

How would someone go about actually making a true *or*, production nodes *or* seed nodes ?

**Comment by sirlatrom** [comment]
@scalp42 You would have to write something complicated like the following since there's currently no builting `xor`, neither in `consul-template` nor in [Go template] (http://golang.org/pkg/text/template/) which it extends:

    {{range service "cassandra"}}
    {{if or (and (not (.Tags.Contains "seed")) (.Tags.Contains "production")) (and (not (.Tags.Contains "production")) (.Tags.Contains "seed")) }}
    {{.Address}}
    {{end}}
    {{end}}
