### ISSUE TITLE
regexMatch not found

### ISSUE THREAD

**Issue by ChristianKniep** [hashicorp/consul-template#262]
Hey guys,

I love `consul` and `consul-template` but that's no strange behavior to you... :)

I got a list of nodes (names are container_id, thus hex) which I would like to separat into an odd and an even group. 
I thought this should work (as a first iteration):
```
{{range $i, $e := service "slurmd" "any"}}{{if $e.Node| regexMatch ".*(1|3|5|7|9|a|c|e)$" }}{{$e.Node}}{{end}}{{end}}
```
But I got an error back:
```
Consul Template returned errors:
template: template: slurm.conf.tmpl:56: function "regexMatch" not defined
```
I use...
```
# consul-template --version
consul-template v0.8.1.dev
```

**Comment by sethvargo** [comment]
Hi @ChristianKniep 

Can you pull down the latest master and re-compile please? `regexMatch` was very recently added.

**Comment by ChristianKniep** [comment]
OK, somehow I got it. Thank again.
