### ISSUE TITLE
var increment within a range 

### ISSUE THREAD

**Issue by mrh666** [hashicorp/consul-template#263]
Hi there, 

I can't find out how to increment variable within a range. And how to suppress last ","?
Let's say I need to have an output within a config:
1:consul_node_1,2:consul_node_2,3:consul_node_3

How I can do it? This one doesn't work, just for example: {{range service "consul@dc1"}}{{$somewar}}:{{.Address}},{{$somevar += 1}}{{end}} ?

**Comment by sethvargo** [comment]
Hi @mrh666 

Thank you for opening an issue. You will need to do something like the following:

```liquid
{{range $index, $service := service "consul@dc1" }}
{{if ne $index 0}},{{end}}{{.Address}}
{{end}}
```

Does that help?

**Comment by mrh666** [comment]
sethvargo, Thank you, I've got an correct output, without last comma from:

```
{{range $index, $service := service "consul@dc1" }}{{if ne $index 0}}{{$index}},{{end}}:{{.Address}}{{end}}

:172.17.0.11,:172.17.0.22,:172.17.0.3
```
But how can I add a an incremental var there to have an output like:

```
1:172.17.0.11,2:172.17.0.22,3:172.17.0.3
```
I've tried to use different go syntax, but no luck. May be you can provide me some link to detailed docs for templates or examples?

**Comment by sethvargo** [comment]
Hi @mrh666 

The documentation for text/template can be found here: http://golang.org/pkg/text/template/. I do not think it is possible to do what you are trying to do - that is just a limitation of Go's templating language.

**Comment by sielaq** [comment]
Actually there is add function in go template 
you can see it in tests:
http://golang.org/src/text/template/exec_test.go?h=add#L355
and in html/template examples here:
http://gohugo.io/templates/go-templates/

but probably its missing in text/templates so consul-template cannot inherit it.

**Comment by sethvargo** [comment]
@sielaq hugo uses it's own template extensions. I've been thinking of writing a verbose template plugin that includes many of the functions of CT, plus things like `add`, `subtract`, etc.

**Comment by mrh666** [comment]
Anyway, using ```{{$index}}``` I have a desired output (starting from 0):

```
servers-spec={{range $index, $service := service "zookeeper"}}{{if ne $index 0}},{{end}}{{$index}}\:{{.Address}}{{end}}
```

```
servers-spec=0\:zookeeper-node-1,1\:zookeeper-node-2,2\:zookeeper-node-3
```

**Comment by digitalronin** [comment]
Thanks so much, that's just what I needed. This works;

    {{range $index, $service := service "loadbalancer" "any"}}{{if ne $index 0}},{{end}}{{.Node}}{{end}}

It's pretty fugly though.

**Comment by alpduhuez** [comment]
I've been loving the use of consul-template in setup, but I ran into this very same issue.  The tool we are using needs a 1 based index instead of 0.  The only workaround I have come up with is using the node name to put the integer values in as key/values in consul.  Just the ability to add or subtract would be a good work around.

**Comment by ChristianKniep** [comment]
Any improvement on that one? I would love to increment the index as well. Zookeeper likes to start from 1... :)

**Comment by scalp42** [comment]
@alpduhuez any chance you can share with us how it look like?

**Comment by alpduhuez** [comment]
I ended up using the node name to find a key based on the node name in the key/values of consul.  It looks like this, not ideal but it was working.
```
{{range $index, $service := service "zookeeper-reporting"}}
{{$nodeNameRaw := .Node}}{{$nodeName := .Node | replaceAll "." "_" }}
{{range ls "reporting/zookeeper/myid"}}
{{$key := .Key | replaceAll "." "_" }}
{{if $nodeName | regexMatch $key }}server.{{.Value}}={{$nodeNameRaw}}:2888:3888{{end}}{{end}}
{{end}}
```

**Comment by scalp42** [comment]
@alpduhuez thanks for sharing, any chance you can give me what the node name look like ?

I'm thinking of hooking consul-template with Exhibitor `/cluster/list` endpoint (https://github.com/Netflix/exhibitor/wiki/REST-Cluster#getcluster)
