### ISSUE TITLE
How to concatenate strings?

### ISSUE THREAD

**Issue by onnimonni** [hashicorp/consul-template#267]
Go noob here.

How can I concatenate two string variables into one in consul templates?
I want to make a service query with that new variable.

**Comment by sethvargo** [comment]
Hi @onnimonni 

You can use Go's template `print` and `printf` functions: http://golang.org/pkg/text/template/. Does that answer your question?

**Comment by onnimonni** [comment]
I was trying to figure this out for so long, thanks :+1: 

This was the behaviour what i was looking for
```go
{{$first := "data"}}{{$second := "base"}}
{{range service (print $first $second) "any"}}
upstream {{.ID}} { {{.Address}}:{{.Port}}; } {{end}}
```

**Comment by sethvargo** [comment]
@onnimonni awesome, I'm glad you figured it out! Go's templating language isn't the most UX-friendly to work with, but it gets the job done :smile:

**Comment by onnimonni** [comment]
Not sure how to ask this but if I use dynamic KV paths like this in a loop:
```golang
{{$name := 'example.com' }}
set $upstream {{ key (print "sites/" $name "/production") }};
```
Will consul-template update the template file if the key 'sites/example.com/production' is changed? How will it evaluate the changes in KV-store? Polling?

**Comment by sethvargo** [comment]
Hi @onnimonni 

Yes, Consul Template uses Consul's watches and long-polling to have edge-trigger changing. Basically CT issues an HTTP query to Consul and Consul _blocks_ on that query until a change occurs.

**Comment by onnimonni** [comment]
Ahh, yes!

Can I somehow trigger this prematurely? I will only change these keys in certain situation and it needs to happen as fast as possible.

**Comment by sethvargo** [comment]
@onnimonni I'm not sure what you are asking? The current situation is already as fast as possible.

**Comment by onnimonni** [comment]
Ok, thats good to know :). I thought that the polling time is something like 30seconds. Thank you so much!

**Comment by gyoza** [comment]
I know this is super freaking old but I just figured out how to do this from a scratch and find it may be useful for some if you need to concatenate an int with a string. 

```
{{ range $hkey, $hval := scratch.Get "map" }}
    {{ $combine := (printf "%v@%v" $hkey $hval) }}
    {{ $combine }}
    {{end}}

**Comment by 030** [comment]
https://stackoverflow.com/a/45390194/2777965

**Comment by evelyndanel** [comment]
Another take on it:

`{{ include "kcg.updaterName" . }}-{{ $action }}`
