### ISSUE TITLE
iterate vault

### ISSUE THREAD

**Issue by jacoelho** [hashicorp/consul-template#270]
The possibility of iterate over a vault path could be very useful, atm:

```
template: application.ctmpl:1:27: executing "application.ctmpl" at <"secret/example/prod...>: range can't iterate over <dependency.Secret Value>
```

**Comment by jacoelho** [comment]
hmm ok, this should work:
```
production: {{ with $secret := vault "secret/example/production" }}
  {{range $secret.Data  }}
    {{.}}
  {{end}}
{{end}}
```

**Comment by sethvargo** [comment]
Hi @jacoelho 

Thank you for opening an issue. You can iterate using Go's default `range` function. More information can be found in the docs: http://golang.org/pkg/text/template/. Please let me know if you need more examples or help. Go's templating language is sometimes a bit limiting.

**Comment by ChrisAubuchon** [comment]
Is it possible to range over a vault path? Say for a list of users with passwords?

```
vault write secret/app/users/<username1> username=<username1> password=<password1>
vault write secret/app/users/<username2> username=<username2> password=<password2>
```

with a template something like:
```
{{ range vault "secret/app/users" }}
{{ .Data.username }} {{ .Data.password }}
{{ end }}
```

**Comment by sethvargo** [comment]
Hi @ChrisAubuchon 

That is not currently possible with Vault: https://github.com/hashicorp/vault/issues/111. If Vault gets that functionality, CT can incorporate it.

**Comment by irlevesque** [comment]
@sethvargo https://github.com/hashicorp/vault/issues/111 has been closed with the merge of https://github.com/hashicorp/vault/issues/617 - I'd certainly be grateful if consul-template could take advantage of this.
