### ISSUE TITLE
How to use an environment variable as part of a key in consul-template HCL

### ISSUE THREAD

**Issue by kaelumania** [hashicorp/consul-template#272]
For example I want to download a service definition out of the key-value store depending on the nodes name/hostname and then reload the consul agent, e.g.:

```
{
  {{with $host := env "HOSTNAME"}}
    {{with $service_definition := key "config/$host/service_definition"}}
      {{if $service_definition}}
        $service_defintion
      {{end}}
    {{end}}
  {{end}}
}
```

with

```
consul-template -template "/tmp/template.ctmpl:/tmp/result:consul reload"
```

**Comment by kaelumania** [comment]
Anyone who is interested:

```
{{$host := env "HOSTNAME"}}
{{$keyname := printf "config/%s/consul/services" $host}}
{{if $keyname}}
 {{key $keyname}}
{{end}}
```

**Comment by sethvargo** [comment]
Hi @kaelumania 

As you discovered, Go's templating language is sometimes a bit limiting and confusing. As you also discovered, you need to use the `printf` function :smile:. Please let met know if you have any other questions!

**Comment by nevir** [comment]
For anyone else stumbling across this, a more compact way to grab keys w/ variables in their path:

```
{{printf "config/%s/consul/services" $host | key}}
```
(the output of printf is piped to `key` as its first argument)

**Comment by etlweather** [comment]
And even simpler, why setting a `$host` variable at all if not needed anywhere else...

```
 {{printf "config/%s/consul/services" (env "HOSTNAME") | key}}
```

**Comment by st33v** [comment]
This is helpful. Thanks guys!

**Comment by ericjmcalvin** [comment]
This was extremely helpful. Thanks!

I am having issues getting this to work with secrets(vault).  

I have my secret in vault at the following location:
secret/marketdatafeed/DEV/db_username

So, I set environment variables for my APPID (marketdatafeed) and ENV (DEV) and want to substitute those values in the path.  

Hardcoding APPID and ENV obviously produces the proper result:
`USERNAME={{with secret "secret/marketdatafeed/DEV/db_username" }}{{.Data.value}}{{end}}`
produces this:  **USERNAME=eric**

`USERNAME={{printf "secret/%s/%s/db_username" (env "APPID") (env "ENV") | secret}}`
produces this:  **USERNAME={ 2592000 false map[value:eric]}**  

`USERNAME={{with secret "secret/%s/%s/db_username" (env "APPID") (env "ENV") }}{{.Data.value}}{{end}}`
produces this:  **USERNAME=\<no value\>**


Any ideas what the proper syntax is?  Go templating language is not as fun as jinja2 :)

**Comment by sethvargo** [comment]
You need to use `printf`

**Comment by ericjmcalvin** [comment]
Thanks - here's the statement that I finally got working:

`USERNAME={{with printf "secret/%s/%s/db_username" (env "APPID") (env "ENV") | secret }}{{.Data.value}}{{end}}`

**Comment by nugend** [comment]
Is there a "tips and tricks" document for consul-template?

It seems like there are a fair number of things which require convolutions because of go template's limitations such as this.

**Comment by prein** [comment]
Should that work the same way with envconsul HCL config file?

**Comment by bpattarkine** [comment]
what is the best way to write macro to convert to lower case

**Comment by aschneid75** [comment]
I'm hoping somebody can help me out with this one, talking to Vault:

{{ with secret "pki_int2/issue/foo-dot-com" "common_name=foo.foo.com" }}

I would like to replace the host in the domain name with the current hostname of the machine the template is running on.  I know I can get env "HOSTNAME", however when I tried various versions of the printf solutions above, I cannot figure out how to do substitutions in the second string variable.

I've tried:

`{{ with printf "pki_int2/issue/foo-dot-com common_name=%s.foo.com" (env "HOSTNAME") | secret  }}`

But that obviously is not what the secret should be and it fails the call.  Since that second parameter is not associated with a key, I don't see a way of assigning it.

Any help on this one?

**Comment by aschneid75** [comment]
So, not sure if it's the best solution, but here's how I got around the above:

`{{ $host := printf "common_name=%s.foo.com" (env "HOSTNAME") }}
{{ with secret "pki_int2/issue/foo-dot-com" $host }}
{{ .Data.ca_chain }}{{ end }}`

**Comment by deeco** [comment]
I have same issue , tried similar to USERNAME={{with printf "secret/%s/%s/db_username" (env "APPID") (env "ENV") | secret }}{{.Data.value}}{{end}} , consul template just hangs, is there a debug option to see what is happening ?  
This is my syntax among static lines , env: name = test

url="jdbc:sqlserver://{{with printf "config/%s/consul/services" (env "name") | key }}{{.Data.value}}{{end}};MultiSubnetFailover=true;DatabaseName=logs;loginTimeout=5;sendStringParametersAsUnicode=false"

**Comment by deeco** [comment]
believe found the issue in that env "name" not set

**Comment by mimianddaniel** [comment]
Is there something special about "file" function? 
eg: 
{ $fileA := file "testfile"  }}
{{ $csr := printf "csr=%v" $fileA }}
{{ with pkiCert "pki/sign/role" "ttl=1h" $csr }}
{{ .Cert }}
{{ end }}

using spew_printf shows that $csr contains the necessary csr information. but when in the log, $csr is empty in the request being sent. 

replacing $fileA with a content from non "file" function shows up properly.
