### ISSUE TITLE
Setting log level through config file does not work.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul-template#276]
I was able to get debug output when using the CLI flags in order to set log levels. But, I couldn't get it to work from the configuration file: 

```
retry = "5s"

ssl {
	enabled = true
	verify = true
	cert = "/etc/consul.d/ssl/consul.cert"
	ca_cert = "/etc/consul.d/ssl/ca.cert"
}

log_level = "debug"
```

I believe a mention about `log_level` is missing in the README as well.

**Comment by sethvargo** [comment]
@c4milo log_level is not a valid configuration option. It is only available via the CLI.

**Comment by c4milo** [comment]
hm, ok.
