### ISSUE TITLE
Configuration is not getting updated

### ISSUE THREAD

**Issue by marc-** [hashicorp/consul-template#283]
I have following template:
```
backend web{{range service "web"}}
  server {{.Node}} {{.Address}}:{{.Port}} weight 1 maxconn 100 check{{end}}
```
When I start consul-template it turns to be:
```
backend web
  server client2 192.168.33.37:8080 weight 1 maxconn 100 check
  server clients-centos-70-client_0 192.168.33.35:8080 weight 1 maxconn 100 check
  server clients1-centos-70-client_0 192.168.33.36:8080 weight 1 maxconn 100 check
```
When I shutdown node `client2` (`serf: EventMemberLeave: client2 192.168.33.37
`), my configuration is not getting updated (I expect line `server client2 192.168.33.37:8080 weight 1 maxconn 100 check` to be removed, but it still there), despite I see consul-template polled service successfully:
```
2015/05/12 17:48:54 [DEBUG] ("service(web)") Consul returned 2 services
2015/05/12 17:48:54 [DEBUG] ("service(web)") 2 services after health check status filtering
2015/05/12 17:48:54 [INFO] (view) "service(web)" received data from consul
2015/05/12 17:48:54 [DEBUG] (view) "service(web)" starting fetch
2015/05/12 17:48:54 [DEBUG] ("service(web)") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:6363 WaitTime:1m0s Token:}
2015/05/12 17:49:54 [DEBUG] ("service(web)") Consul returned 2 services
2015/05/12 17:49:54 [DEBUG] ("service(web)") 2 services after health check status filtering
2015/05/12 17:49:54 [DEBUG] (view) "service(web)" no new data (index was the same)
2015/05/12 17:49:54 [DEBUG] ("service(web)") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:6363 WaitTime:1m0s Token:}
```
Output of `curl "http://localhost:8500/v1/health/service/web?index=6363&passing=1&wait=60000ms"`:
```json
[
   {
      "Node" : {
         "Node" : "clients-centos-70-client_0",
         "Address" : "192.168.33.35"
      },
      "Service" : {
         "Port" : 8080,
         "Service" : "web",
         "Address" : "192.168.33.35",
         "Tags" : [
            "web",
            "httpd"
         ],
         "ID" : "web0"
      },
      "Checks" : [
         {
            "Output" : "Agent alive and reachable",
            "Status" : "passing",
            "Node" : "clients-centos-70-client_0",
            "ServiceName" : "",
            "Notes" : "",
            "Name" : "Serf Health Status",
            "ServiceID" : "",
            "CheckID" : "serfHealth"
         }
      ]
   },
   {
      "Service" : {
         "Tags" : [
            "web",
            "httpd"
         ],
         "Address" : "192.168.33.36",
         "Port" : 8080,
         "Service" : "web",
         "ID" : "web1"
      },
      "Checks" : [
         {
            "Output" : "Agent alive and reachable",
            "Status" : "passing",
            "Node" : "clients1-centos-70-client_0",
            "Notes" : "",
            "ServiceName" : "",
            "Name" : "Serf Health Status",
            "ServiceID" : "",
            "CheckID" : "serfHealth"
         }
      ],
      "Node" : {
         "Address" : "192.168.33.36",
         "Node" : "clients1-centos-70-client_0"
      }
   }
]
```
Not sure if it is related but I was observing same behavior when runing consul with `watch` enabled: watch wasn't triggered after I shutdown/start up node.

Consul version v0.5.0-240-g739d1fd.dev .
Consul-template version v0.9.0.dev .

**Comment by sethvargo** [comment]
Hi @marc- 

Could you please send your entire raw template, the Consul Template command you are running, and the complete output in debug mode? Thanks!

**Comment by marc-** [comment]
Here is `consul-template` command:
```bash
/usr/local/bin/consul-template -log-level debug -template \
"/home/vagrant/haproxy-backends.cfg.ctmpl:/etc/haproxy/haproxy-backends.cfg:/usr/sbin/haproxy \
-f /etc/haproxy/haproxy.cfg -f /etc/haproxy/haproxy-backends.cfg -p /var/run/haproxy.pid \
-sf $(cat /var/run/haproxy.pid) || true" &>consul-template.log &
```
haproxy-backends.cfg.ctmpl template:
```
backend web{{range service "web"}}
  server {{.Node}} {{.Address}}:{{.Port}} weight 1 maxconn 100 check{{end}}
```
Here is consul-template [log](https://gist.github.com/marc-/16f64dea8ea23523add7) and consul [log](https://gist.github.com/marc-/9379db468e1c89559b4d).

**Comment by marc-** [comment]
Looks like consul-template stuck on waiting for command to exit. Command
```
/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -f /etc/haproxy/haproxy-backends.cfg \
-p /var/run/haproxy.pid -sf $(cat /var/run/haproxy.pid)
```
stays in foreground and never returns until you kill it manually. This seems prevents consult-template to update configuration. Once you add `-D` option to command, it starts work as expected.


Issue is not consul-template fault, but having some detection mechanism like timeout would be really helpful. At least this needs to be covered in documentation. 
@sethvargo, can you please consider this?

**Comment by sethvargo** [comment]
Oh oh oh. Yea. Gosh, that's awful. Good thing you found that because I was headed down a completely different path :wink:. 

What do you think about having a "sane" timeout (like 30s) for the command to execute? I'm not sure what the behavior should be on timeout though /cc @armon @ryanuber 

I think that, if the command has not finished after 30s, we should error and kill CT (this is parallel to what happens if the command exits non-zero), but I'm open to other ideas.

**Comment by marc-** [comment]
>What do you think about having a "sane" timeout (like 30s) for the command to execute?

How about having flag for this?
>I'm not sure what the behavior should be on timeout

Good question. There 2 possible solutions among others: 
- notify about command execution reached timeout and do nothing
- notify about command execution reached timeout and terminate process (what about return code?)

I think best would be have a flag to be able to switch between this two.

BTW, I believe `consul` `watch` is also affected by this issue.
