### ISSUE TITLE
file directive does not render

### ISSUE THREAD

**Issue by gigaroby** [hashicorp/consul-template#287]
Quoting from the docs: Read and **render** the contents of a local file on disk.
My understanding from the doc is that I can include further templates and they will be rendered in the context of the current file. 
This does not appear to be the case, as this is the result I get trying to include further templates:
```
frontend fe
    bind *:30000
    mode http
    option http-server-close
    default_backend be

frontend be
    mode http
    balance roundrobin
    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]
    option httpchk GET /status HTTP/1.1\r\nHost:localhost
    {{range service "api"}}
    server {{.Node}} {{.Address}}:{{.Port}}
    {{end}}
``` 

Did I misunderstand the documentation or am I doing something wrong?

**Comment by sethvargo** [comment]
Hi @gigaroby 

Can you please share your template? I do not see a `file` declaration in the one you've provided.

The `file` function reads and renders the contents, but it does not "render" them as I think you are thinking. This might be misleading so I will think of another word and update the documentation. The file is read (like `ioutil.ReadFile`) and the string contents are rendered into the template.

If you are looking for "nested templates", Go's templating language supports that out of the box: http://golang.org/pkg/text/template/. Does that help?

**Comment by gigaroby** [comment]
@sethvargo I was attempting to split a haproxy configuration files in various files (since haproxy does not have that capability built in).
To that end I thought that ```file``` would allow me to render other templates (from different files) into the main file as follows
```go
... various default stuff
{{file "/etc/haproxy/s/backend.ctmpl"}}
{{file "/etc/haproxy/s/other.ctmpl"}}
```
Nested templates do not solve my problem as I have to define all of them in the same file.

**Comment by sethvargo** [comment]
Updated the docs, thanks!
