### ISSUE TITLE
Pulling agent/node address instead of address set in registered service JSON.

### ISSUE THREAD

**Issue by Spicykoala** [hashicorp/consul-template#292]
I have an issue where I've registered services, in the format:
```
{
  "ID": "app1",
  "Name": "app",
  "Tags": [
    "production"
  ],
  "Address": "127.0.0.1",
  "Port": 8000
}
```

I'm then attempting to render the template as follows:

```
upstream app {
  #least_conn;
  {{range service "production.app"}}server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=60 weight=1;
  {{else}}server 127.0.0.1:65535; # force a 502{{end}}
}
```

However, the .Address is rendering the consul agent's IP instead of the Service Address - in the example case, it would be "127.0.0.1". I have confirmed that when I pull the services down via '/v1/agent/services', that the correct information is shown. And when I pull down the service from the catalog, the SERVICE ADDRESS is correct. For some reason the Node Address is being used instead of the service address.

Thoughts?

Thanks in advance!

**Comment by sethvargo** [comment]
Hi @Spicykoala 

Could you please share:

- the version of Consul Template you are using
- the exact command you are running
- the complete template

Thanks!

**Comment by Spicykoala** [comment]
Oh wow, I had swapped some docker stuff around and it was using a REALLY old version. 0.1 !! After updating to 0.9 the problem is resolved. My apologies - keep up the great work guys!
