### ISSUE TITLE
simulate self behavior

### ISSUE THREAD

**Issue by kalw** [hashicorp/consul-template#293]
Hi there,

The thing I'm trying to is listing nodes and excluding the host where i execute consul-template.
something like this : 
```
{{range service "nginx"}}
host : {{env "HOST"}}
node : {{.Node}}
{{if ne .Node "{{env \"HOST\"}}"}} ran into if  {{end}}
{{end}}
```

despite that {{env "HOST"}} equals {{.Node}} once a loop, the if statement never match.
Any ideas how could I achieve this behavior in any way ? =)

Regard,

-- 
Regis A. Despres

**Comment by sethvargo** [comment]
Hi @kalw 

I think your template is literally checking if the `Node` matches the string `"{{env "HOST"}}"` instead of the value. I would recommend this approach:

```liquid
{{ $host := env "HOST" }}
{{ range service "nginx" }}
host : {{$host}}
node : {{.Node}}
{{ if ne .Node $host }} ran into if {{ end }}
{{ end }}
```

**Comment by kalw** [comment]
Obviously ! You're the man =)
