### ISSUE TITLE
`log_level="debug"` in config file did not work like -log-level="debug"

### ISSUE THREAD

**Issue by ruoshan** [hashicorp/consul-template#294]
using `-log-level="debug"` print pretty much info, but set it in the config file, nothing is printed.
this issue is produced on v0.9.0.

**Comment by sethvargo** [comment]
Hi @ruoshan 

I believe this has been fixed on the master branch. Can you please give it a try? Thanks!

**Comment by ruoshan** [comment]
will do :)

**Comment by sethvargo** [comment]
I have confirmed this is fixed in master.
