### ISSUE TITLE
Service Names With `.`

### ISSUE THREAD

**Issue by saulshanabrook** [hashicorp/consul-template#295]
Currently this will not work with service names that have `.`s in them. 

Debug log for consul-template

```
2015/05/17 19:39:19 [DEBUG] ("service(cats.com [any])") 0 services after health check status filtering
```

Debug log from `consul monitor -log-level=trace`

```
2015/05/17 19:39:15 [DEBUG] http: Request /v1/health/service/com?tag=cats&wait=60000ms (2.646559ms)
```

As you can see, instead of requesting `/v1/health/service/cats.com` it requests `/v1/health/service/com?tag=cats`.

When I make the HTTP request myself to `/v1/health/service/cats.com` consul returns the right result.

**Comment by saulshanabrook** [comment]
Maybe it would be possible to do `cats\.com` so it doesn't get confused and think it's a tag?

**Comment by sethvargo** [comment]
Hi @saulshanabrook 

I talked about this with @armon and using "dots" as service names in Consul is not technically valid. It is accepted, but the repercussions are that you experience issues such as these :frowning:. It might work, but it is not recommend (think about DNS). As such, we do not want to support dots in service names. Sorry!

Please let me know if you have any questions.

**Comment by saulshanabrook** [comment]
@sethvargo Thanks for the thought, yeah makes sense. For reference hashicorp/consul#215 is the issues about providing a warning for dots in names.
