### ISSUE TITLE
can not use `index` function in template for `service`

### ISSUE THREAD

**Issue by ruoshan** [hashicorp/consul-template#296]
I try to get the first element from a list returned by `service` with this template:
```{{ $first := index service 0}}```
Though the service did return a list, calling `index` would
raise the error `<index $service 0>: error calling index: index out of range: 0` anyway.

I don't if this issue belongs here or the `text/template` of Go.

**Comment by sethvargo** [comment]
Hi @ruoshan 

This is both a limitation of Go's text/template and a confusion point about how Consul Template functions. Consul Template does an n-pass evaluation, accumulating dependencies on each pass. As a result, the first pass (0-pass) always returns "empty" data. To get around this, you should alter your template to ensure the service list has at least one element before getting the zeroth element.

You can use the `len` function to check this.

I think (haven't tried) it is also possible to specify the service as an `if`:

```liquid
{{ if service "foo" }}
{{ with index (service "foo" 0) }}
{{.Node}}
{{ end }}
{{ end }}
```

Does that help?

**Comment by ruoshan** [comment]
@sethvargo yes, it works. Thanks.

But it didn't look very intuitive. I haven't look into the code carefully. I would figure out what does the `n-pass` mean when my hands are free.

Maybe it should be documented on the README page :)
