### ISSUE TITLE
A helper to convert strings to integers

### ISSUE THREAD

**Issue by mattupstate** [hashicorp/consul-template#297]
All KV's are returned as strings, but I've come into a situation where I need to iterate over a defined range as specified by what should be an integer value in the KV store. I imagine being able to do something like this:

```go
{{ $workers := key "service/name/workers" | parseInt }}
{{ range $i := loop 1 $workers }}
   worker.{{ $i }}.something
{{ end }}
```

**Comment by mattupstate** [comment]
@sethvargo right on!

**Comment by zeldal** [comment]
Currently that usage throws  
> wrong type for value; expected int; got int64.
on loops, since parseInt return int64, i am not go expert any trick to do this?
