### ISSUE TITLE
syslog logging only seems to work if you pass it on the command line

### ISSUE THREAD

**Issue by darron** [hashicorp/consul-template#300]
I'm using Ubuntu 14.04. Starting Consul Template with Upstart:

```
description "Consul Template"
emits consultemplate-up

start on filesystem and started consul
stop on runlevel [!2345]

script
  /usr/local/bin/consul-template -config /etc/consul-template/config/
end script

post-start exec initctl emit consultemplate-up

kill signal INT
```

rsyslog is setup:

```
root@i-c972d41e:/etc/rsyslog.d# cat consul-template.conf
local5.*	-/var/log/consul-template/consul-template.log
```

`/etc/consul-template/config/` has 2 config files in it:

```
consul = "127.0.0.1:8500"
retry = "10s"
max_stale = "10m"

syslog {
  enabled = true
  facility = "LOCAL5"
}

template {
  source = "/etc/consul-template/templates/default.ctmpl"
  destination = "/etc/consul-template/default.txt"
}
```
and
```
consul = "127.0.0.1:8500"
retry = "10s"
max_stale = "10m"
log_level = "debug"

syslog {
  enabled = true
  facility = "LOCAL5"
}

template {
  source = "/home/darron/template.ctmpl"
  destination = "/home/darron/rendered.txt"
}
```

When I run Consul Template - there are no logs at all output:

```
root@i-c972d41e:/var/log/consul-template# service consul-template start
consul-template start/running, process 27426
root@i-c972d41e:/var/log/consul-template# ls -al
total 8
drwxr-xr-x   2 root root   4096 May 25 20:23 .
drwxrwxr-x+ 17 root syslog 4096 May 25 20:27 ..
-rwxr-----   1 root root      0 May 25 20:35 consul-template.log
```

Logs are only output if I update the Upstart script and pass this along:

`-syslog=true -syslog-facility="LOCAL5" -log-level=debug`

Then it logs just like I expect: https://gist.github.com/darron/90e62da45cbfc78b4ce1

So - is logging via syslog not supported on a per config basis?

OR do I just remove the syslog parts from my config files and just pass it via the Upstart script?

From the documentation it looks like maybe this is a bug - but I may be misunderstanding something.

Thanks for a great piece of software!

**Comment by sethvargo** [comment]
Hi @darron 

Thanks for the bug report. This is fixed on master.

I also wanted to point out - configs are recursively loaded, an the values are intelligently merged. You should not need to specify the "common" attributes (like the consul address) more than once :smile:.
