### ISSUE TITLE
Retrieving SSL/TLS certificates with proper line breaks.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul-template#302]
I tried using consul-template to render some SSL/TLS keys but they were wrongly rendered. I'm sure I'm missing something.

**Comment by sethvargo** [comment]
Hi @c4milo 

I am sorry, but there is not enough information here to diagnose the issue. What do you mean they are "wrongly rendered"? Most likely you are missing line endings or the line endings are not properly being written. Unfortunately I cannot provide any additional insight without more information.

**Comment by c4milo** [comment]
Hey Seth,

It was actually my mistake. Pushing the certificate to Consul with curl and
--data-binary worked beautifully, line breaks are preserved and
consul-template renders the TLS certificate correctly.

Cheers,
Camilo

**Comment by sethvargo** [comment]
Ah yes - I've been bitten by this before as well. Curl is sad like that. Glad you figured it out!

**Comment by datacarl** [comment]
@c4milo do you have an example of what you did? I tried three different approaches but all give me litteral `\n` in the output when querying consul.

`curl -X PUT --data-binary @server.pem $IP:8500/kv/v1/path/to/key`

Also tried --data-binary with the content sent on the command line, with \n, e.g.
`curl -X PUT --data-binary '---BEGIN ETC---\nASDF\nQWERY----END----' $IP:8500/kv/v1/path/to/key`

Finally tried @- e.g.
```
curl -X PUT --data-binary @- $IP:8500/kv/v1/path/to/key << EOF
line 1
line 2
EOF
```

**Comment by datacarl** [comment]
Ah, look at that, I mixed up `v1` and `kv` in the path. 
`curl -X PUT --data-binary @server.pem $IP:8500/v1/kv/path/to/key` works just fine.
