### ISSUE TITLE
Intermittent test failures, probably from external resources

### ISSUE THREAD

**Issue by cbednarski** [hashicorp/consul-template#310]
Using `watch -e go test ./... -timeout=30s -parallel=4` I get some periodic failures.
Some examples:

- https://gist.github.com/cbednarski/ab73a0a4e03ab1b6a37d
- https://travis-ci.org/hashicorp/consul-template/builds/65944853#L147

/cc @ryanuber @sethvargo

**Comment by sethvargo** [comment]
Hi @cbednarski 

I am going to tag this as an upstream bug. I think there is a race condition in the consul test server "wait to be ready". /cc @ryanuber 

If we determine I'm wrong, I'm happy to re-look into it :smile:

**Comment by sethvargo** [comment]
This is no longer happening as of Go 1.5. If it happens again I'll reopen :smile:
