### ISSUE TITLE
multiple templates

### ISSUE THREAD

**Issue by lbpierre** [hashicorp/consul-template#314]
Hi,

I wonder, when using configuration file with multiple templates. How do you manage consul.result file writing. Does multi templates allow the possibility to have the same output file ?

**Comment by sethvargo** [comment]
Hi @lbpierre 

Thank you for opening an issue. Each template has it's own destination:

```javascript
template {
  source = "template1.ctmpl"
  destination = "/tmp/1"
}

template {
  source = "template2.ctmpl"
  destination = "/tmp/2"
}
```

It is not possible to output multiple templates to the same file, because the latest would overwrite.

Please let me know if that answers your question.

**Comment by lbpierre** [comment]
@sethvargo, thank's perfect.
