### ISSUE TITLE
Failure attempting to remove file that doesn't exist on first run

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul-template#315]
I've got a configuration that doesn't exist the first time I run consul-template and it errors out due to not being able to remove that file.

See logs below:
```
2015/06/13 18:10:44 [DEBUG] (config) loading configs from "C:\\opt\\consul-template\\conf"
2015/06/13 18:10:44 [DEBUG] (config) merging with "C:\\opt\\consul-template\\conf\\base.conf"
2015/06/13 18:10:44 [DEBUG] (config) merging with "C:\\opt\\consul-template\\conf\\log-courier.conf"
2015/06/13 18:10:44 [DEBUG] (logging) setting up logging
2015/06/13 18:10:44 [DEBUG] (logging) config:

{
  "name": "consul-template",
  "level": "warn",
  "syslog": false,
  "syslog_facility": "LOCAL0"
}

Consul Template returned errors:
remove c:\opt\log-courier\base-conf.json: The system cannot find the file specified.
```

This error is correct - `c:\opt\log-courier\base-conf.json` truly does not exist when consul-template is run, but if I make a blank empty file before I run it, the problem goes away and it works fine after that.

**Comment by sethvargo** [comment]
Hi @highlyunavailable 

Can you please share your configuration and the command you are running?

**Comment by highlyunavailable** [comment]
#316 fixes this - sorry I didn't include the config and command.
