### ISSUE TITLE
Enable use of other vault authentication backends

### ISSUE THREAD

**Issue by sebastiang** [hashicorp/consul-template#318]
It could be I am just missing something in the documentation. Is it possible to use an alternate authentication backend, e.g. `method=github`?

**Comment by sethvargo** [comment]
This is not something that is currently possible. You can use the `vault` CLI to login with the auth method and get a token which can then be passed to Consul Template.

This is something we are thinking about for a later version, but it is difficult to implement without re-implementing all of Vault's options. Instead, you can generate the token with Vault and then just give Consul Template the token for now.

**Comment by sebastiang** [comment]
That works, though bit odd how many private keys end up on the filesystem

    vault auth method=github token=$(cat ~/.my-private-github-key)
    export VAULT_TOKEN=$(cat ~/.vault-token)

**Comment by sethvargo** [comment]
I think we could probably ready `~/.vault-token` to save that step

**Comment by mhurne** [comment]
I would love to see support for App ID authentication!

**Comment by blalor** [comment]
+1 to App ID.

**Comment by sethvargo** [comment]
Hi everyone,

I've spent some time thinking about this, and, I don't think Consul Template should be responsible for the other authentication methods, but let me explain why.

If one considers the API for Vault, it's quite massive. As Vault becomes more pluggable, it will be impossible for every tool to support every possible authentication medium for Vault. Conversely, at the end of the day, all communication with Vault happens via a single token. This is all 99.9% of applications will need to communicate with Vault. As such, I think it makes the most sense to have a wrapper tool (similar to `envchain`) that _does_ support all the possible authentication mechanisms and then execs into the subprocess with the correct environment variable set. For example:

```
vault-auth -method=github -token=abcd1234 consul-template -template=in.ctmpl -once
```

This would auth against github, passing the resulting vault token as `VAULT_TOKEN` into the consul-template process.

**Comment by mhurne** [comment]
Neat - is there a home for `vault-auth` yet so those who are interested can keep an eye on its development?

**Comment by mhurne** [comment]
Hey @sethvargo , any chance some progress has been made on `vault-auth`?

**Comment by jefferai** [comment]
I believe that @sethvargo was simply giving an example of what a wrapper invocation might look like. There is currently no `vault-auth` tool.

**Comment by mhurne** [comment]
@jefferai Yeah, I'm aware there's no tool. Sounds like I incorrectly assumed @sethvargo / HashiCorp was planning on creating one.

**Comment by fuero** [comment]
Sorry for reopening this, I just want to add this for people that look for a solution for this :-)

Here's a sample script to authenticate via certificate I'm using:

```bash
#!/usr/bin/env bash

set -euo pipefail

PUPPET_SSL_DIR="/var/lib/puppet/ssl/"
HOST="$(hostname --fqdn)"
VAULT_ADDR="https://vault.service.consul:8200"


VAULT_TOKEN="$(VAULT_ADDR=${VAULT_ADDR} \
vault login -method=cert \
  -client-cert="${PUPPET_SSL_DIR}/certs/${HOST}.pem" \
  -client-key="${PUPPET_SSL_DIR}/private_keys/${HOST}.pem" \
  -format=json \
  -no-store \
  2> /dev/null \
| jq -r '.auth.client_token')"

#env VAULT_ADDR="${VAULT_ADDR}" VAULT_TOKEN="${VAULT_TOKEN}" vault token lookup
exec env VAULT_TOKEN="${VAULT_TOKEN}" "${@}"
```

Should be easy enough to adapt for your needs.
