### ISSUE TITLE
Default values?

### ISSUE THREAD

**Issue by jplock** [hashicorp/consul-template#323]
I'm trying to use a consul template and handle the situation where a consul key may not exist, but I need some value to be populated in the template.  Ansible supports a syntax like:

```
"myproperty": {{ myvalue | default('true') }}
```

which if `myvalue` doesn't exist, it would write `true`.  Is there a way to do this in consul-template or would you accept a pull request to add a `default` template function?  Thanks.

**Comment by jplock** [comment]
Reading the go template documentation, it looks like this may be what i was looking for:

```
{{with pipeline}} T1 {{else}} T0 {{end}}
	If the value of the pipeline is empty, dot is unaffected and T0
	is executed; otherwise, dot is set to the value of the pipeline
	and T1 is executed.
```

but I'm not sure how to use that with `{{key "service/redis/maxconns@east-aws"}}`.

**Comment by sethvargo** [comment]
Hi @jplock 

You can use something like:

```liquid
{{ if key "foo" }}
{{ else }}
{{ end }}
```

Does that work?

**Comment by jplock** [comment]
Yes it does, thanks

**Comment by AnkushPuri** [comment]
Try using 
key_or_default

Query Consul for the value at the given key. If no key exists at the given path, the default value will be used instead. The existing constraints and usage for keys apply:

{{key_or_default "service/redis/maxconns@east-aws" "5"}}

**Comment by gdombrov** [comment]
`{{ or myvalue 'true' }}`
