### ISSUE TITLE
Consul support for service instances

### ISSUE THREAD

**Issue by VaradDeolankar** [hashicorp/consul-template#324]
Does Consul return different instances of the same service in a load balanced manner(round-robin) etc.?

Eg: Lets say i have a service named "Test" and we create 3 instances of the same service during service registration. We currently use a serviceManager class that manages the service(Test) instance. This class has a method getService("Test") which returns different instances of the service(in round robin fashion) upon different calls with same service name. 

So, Is this possible in Consul?

**Comment by slackpad** [comment]
Hi @VaradDeolankar - not sure if you have a more consul-template specific spin on your question, but Consul does a randomized load balance for DNS if there are multiple healthy nodes with a given service:

> The DNS query system makes use of health check information to prevent routing to unhealthy nodes. When a service query is made, any services failing their health check or failing a node system check will be omitted from the results. To allow for simple load balancing, the set of nodes returned is also randomized each time. These mechanisms make it easy to use DNS along with application-level retries as the foundation for an auto-healing service oriented architecture.

See [DNS Interface](https://www.consul.io/docs/agent/dns.html) for more details.

**Comment by sethvargo** [comment]
Hi @VaradDeolankar 

This appears to be a question about Consul. Could you please ask on the [Consul Mailing list](https://groups.google.com/forum/#!forum/consul-tool) or open a GitHub issue on the [Consul project](https://github.com/hashicorp/consul)? Thanks!

If you have a question specifically about Consul Template, please feel free to open another issue with more information. Thanks! :smile:
