### ISSUE TITLE
toYAML starting indent

### ISSUE THREAD

**Issue by gmr** [hashicorp/consul-template#327]
I'd like to use ``toYAML`` to define snippets in a YAML template that is being built, but run into an issue where due to the starting indent at 0. Is it possible to expand toYAML to include a starting indention level? If not, do you have any suggestions to get around this issue?

Ideally, I could do something like line #8 (stuff provided for context):
```
Foo:{{with $hostname := env "HOSTNAME"}}{{with $c := printf "services/foo/node_assignments/%s" ($hostname) }}{{range key $c | parseJSON}}
  {{.}}:
    connections: {{range service "bar"}}
      - {{.Node}}{{end}}
    qty: {{with $k := printf "services/foo/%s/qty" (.)}}{{ key $k }}{{end}}
    config: {{with $config := printf "services/foo/%s/config/" (.)}}
{{ tree $config | explode | toYAML(6)}}{{end}}
{{end}}{{end}}{{end}}
```

Also FWIW, I am using the following code to work around it at the moment since YAML does parse JSON properly:
```
config: {{with $config := printf "services/foo/%s/config/" (.)}}{{ tree $config | explode | toJSON}}{{end}}
```

**Comment by sethvargo** [comment]
Hi @gmr 

You could write a plugin that adds indentation like this:

```liquid
{{ tree "config" | explode | toYAML | plugin "indent" 6 }}
```

Then write a plugin that splits on the newline character an indents by the give parameter.

Does that answer your question?

**Comment by gmr** [comment]
Fair enough, thanks.
