### ISSUE TITLE
Add support for cascading keys.

### ISSUE THREAD

**Issue by nathanielc** [hashicorp/consul-template#328]
A cascading key would look through the KV store from most specific to least specific. For example given a template directive like so:
```
{{ cascadingkey "myapp/nyc/webserver/w1.example.com/httpd.conf" }}
```
consul-template would look for a key in this order until it found a value:

1. myapp/nyc/webserver/w1.example.com/httpd.conf
2. myapp/nyc/webserver/httpd.conf
3. myapp/nyc/httpd.conf
4. myapp/httpd.conf

This way the template could contain a specific key but then cascade up the hierarchy defined by the key. Then if at some point in time later you add a more specific key it will update the template. Optionally you could specify a "root" key so that it does cascade above that root.

Thoughts? I am willing to submit a PR if you think its valid approach. For the kind of work I am trying to do this seems very useful. This is similar to how the multiple -prefix options work in envconsul.

**Comment by sethvargo** [comment]
Hi @nathanielc 

Thank you for opening an issue. This has been proposed a few times (https://github.com/hashicorp/consul-template/issues/165, https://github.com/hashicorp/consul-template/pull/273), and we do not think this is a job for Consul Template. In your example, Consul Template would need to create 4 separate watches for each node running Consul Template. This quickly creates a lot of load on the Consul server. Instead, you should use an external tool to populate the KV store with the "merged" result. Does that make sense?

Unfortunately Consul is not designed to be a replacement for Chef attributes or Puppet Hiera data. As a general rule, you should question if you _really_ need that many layers of specificity. It makes it significantly harder to reason about infrastructure, especially in a large distributed system. It's much easier to push that merging logic onto another tool that fits your customization and keep Consul KV store flat.

Please let me know if you have any questions.

**Comment by nathanielc** [comment]
Thanks for the quick reply and the links to the other issues. I had not seen them. The discussions are helpful and I think I will look into a  tool to merge up the hierarchy before adding the data to Consul KV. Do you know of any such tools that do the merging out-of-band? Thanks.

**Comment by sethvargo** [comment]
Hi @nathanielc 

I would imagine that _someone_ has created a plugin for that by now, but I'm not aware of any offhand unfortunately.
