### ISSUE TITLE
function `node` not defined

### ISSUE THREAD

**Issue by Kosta-Github** [hashicorp/consul-template#330]
This simple template:
```
{{node}}
```
produces the following error:
```
$ consul-template -consul=consul:8500 -template=test.conf:out.txt -once
Consul Template returned errors:
template: template: test.conf:1: function "node" not defined
```
Do I miss something or how do I get access to the "local" node instance described in the documentation in the `README.md`?

**Comment by sethvargo** [comment]
Hi @Kosta-Github 

What version of Consul Template are you using? `consul-template -v`

**Comment by Kosta-Github** [comment]
On OSX:
```
$ consul-template --version
consul-template v0.9.0
```

**Comment by Kosta-Github** [comment]
Ah, sorry, I just noticed that the `node` command is >=`0.10.x` ... :-)

**Comment by sethvargo** [comment]
@Kosta-Github you will need to update to 0.10.x. Thanks!
