### ISSUE TITLE
Service query with port number doesn't work as documented

### ISSUE THREAD

**Issue by cdwertmann** [hashicorp/consul-template#333]
I'm trying to select only the services running on port 80 in this template:

    config firewall vip
    edit "http"
    config realservers
    purge
    y
    {{range $index, $service := service "nginx@dc1:80"}}edit 0
    set ip {{.Address}}
    set port {{.Port}}
    next
    {{$index}}
    {{end}}end
    end

Unfortunately, services running on 443 also get listed in the output:

    config firewall vip
    edit "http"
    config realservers
    purge
    y
    edit 0
    set ip 172.16.0.200
    set port 443
    next
    0
    edit 0
    set ip 172.16.0.200
    set port 80
    next
    1
    edit 0
    set ip 172.16.0.201
    set port 443
    next
    2
    edit 0
    set ip 172.16.0.201
    set port 80
    next
    3

I'm aware that I can use "if" to filter out services on port 443, but that prevents me from having a continuous index sequence.

1) what am I doing wrong?
2) how can I select all "nginx" services at port 80, without specifying the data centre? service "nginx@:80" doesn't work

**Comment by sethvargo** [comment]
Hi @cdwertmann 

I am sorry you are having issues with Consul Template. I think the documentation might be a bit confusing/legacy here. The port is actually the "fallback" port if the original port was not defined in consul. It's not a search; there is no API in consul to search for a service by port.

To filter out other services, you will need to do something like the following:

```liquid
config firewall vip
edit "http"
config realservers
purge
y
{{range $index, $service := service "nginx@dc1:80"}}
{{if eq .Port 80}}edit 0
set ip {{.Address}}
set port {{.Port}}
next
{{$index}}
{{end}}{{end}}end
end
```

**Comment by cdwertmann** [comment]
Hi @sethvargo ,

the documentation led me to believe that I can select services by data centre and ports, may be this could be clarified?

I've used the "if" construct before, problem with that is my $index values will be 1 3 5 7 9... and so on rather than 0 1 2 3 4...  Any suggestions?
