### ISSUE TITLE
Consul-Template using multiple Consul servers

### ISSUE THREAD

**Issue by mike-mitchell** [hashicorp/consul-template#334]
We are using Consul under best practices and have 3 Consul servers running under leader election. The template states to use one IP address in order to query the consul server. Statically setting one server causes consul-template to be our single point of failure. Is there a way we can set -consule to point to multiple consul servers?

**Comment by sethvargo** [comment]
Hi @mike-mitchell 

You can use the `-consul` flag to point to the DNS address of your consul server (which is `consul.service.consul:8500` by default). This will use Consul's DNS capabilities to route requests to all Consul servers. However, followers will still forward requests to the leader. If you want to allow followers to respond to requests without the leader, you can specify the `-max-stale` parameter to a time value that indicates how "stale" a follower's data can be before it must forward and refresh from the leader.

Does that answer your question?

**Comment by mike-mitchell** [comment]
@sethvargo

Thank you for the quick response. That answered my question perfectly. I appreciate the help.

**Comment by sethvargo** [comment]
Awesome. Thanks!
