### ISSUE TITLE
[Question] Global regex flag

### ISSUE THREAD

**Issue by MrMMorris** [hashicorp/consul-template#335]
Sorry for having to create an issue for this, I can't get on the IRC channel and you guys are pretty quick at answering tickets :smile: 

I have a service 'monitoring'. It has tags ui, consul, nginx, alerts, node, container, server, mongo, and redis.

I want to print upstreams in an nginx conf only for the 'ui', 'server' and 'alerts' tags.

I was thinking of something like this:
```
{{range $tag, $services := service "monitoring" | byTag | regexMatch "(ui|alerts|server)"}}
upstream monitoring-{{$tag}}.frontend {
  least_conn;
{{range $services}}  server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=60 weight=1;
{{end}}}
{{end}}
```

I haven't tested it yet, but I know that I need the 'global' regex flag in order to match **all** occurrences or  else only 'ui' is matched.

**So my question:** 

Is there a way to set the global flag? Or, alternatively, is there a better way to do what I want?

**Expected Result:**
```
upstream monitoring-ui.frontend {
  least_conn;
  server x.x.x.x:<port> max_fails=3 fail_timeout=60 weight=1;
}

upstream monitoring-alerts.frontend {
  least_conn;
  server x.x.x.x:<port> max_fails=3 fail_timeout=60 weight=1;
}

upstream monitoring-server.frontend {
  least_conn;
  server x.x.x.x:<port> max_fails=3 fail_timeout=60 weight=1;
}
```

Thanks!

**Comment by ryanuber** [comment]
@MrMMorris since `regexMatch` returns only `(bool, error)` and doesn't itself filter / return results, one thing you might do is loop one level earlier, and in each iteration, check `regexMatch` against that tag. I'm sure there are other ways to accomplish what you want as well, but after a quick glance that's what I would probably try to do.

**Comment by MrMMorris** [comment]
alright, I will try that thanks!

**Comment by scalp42** [comment]
@MrMMorris any chance you could share?

**Comment by MrMMorris** [comment]
@scalp42 I ended up just doing it the lazy way and hardcoding each ui/server/alerts block
