### ISSUE TITLE
Consul template writes garbage to templates (rpc error: unexpected EOF)

### ISSUE THREAD

**Issue by jnsaff** [hashicorp/consul-template#338]
When Consul is having trouble Consul Template writes error messages into the template outputs. In my case it's "rpc error: unexpected EOF". Having garbage written into configuration files for applications is worse then writing anything at all or keeping previous good file.

**Comment by sethvargo** [comment]
Hi @jnsaff 

That seems like a bad thing - can you please share your configuration file and the command you are running?

**Comment by jnsaff** [comment]
This was not a consultemplate problem after all. We downloaded the templates via curl from consul to be used by consultemplate. Consul itself gave 200 response to a failing request and this message. So this is a problem with Consul and/or how our workflow is set up. Sorry about crying wolf without understanding the issue.

**Comment by sflint** [comment]
I am having a similar issue : 

==> WARNING: LAN keyring exists but -encrypt given, using keyring
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Joining cluster...
==> EOF

This is what I get when trying to connect to a cluster with a client agent 

Config file : 
{
    "server": false,
    "datacenter": "nyc2",
    "data_dir": "/var/consul",
    "ui_dir": "/home/consul/dist",
    "encrypt": "F5dVJ1T1JXKKdUDlKOTkBw==",
    "log_level": "INFO",
    "enable_syslog": true,
    "start_join" : ["192.186.2.44","192.168.2.45","192.168.2.46"],
    "bind_addr" : "192.168.2.47",
    "node_name" : "192.168.2.47"
}

**Comment by sflint** [comment]
I think I found what the issue is : https://github.com/hashicorp/consul/issues/1013
