### ISSUE TITLE
How to get ServiceAddress from a node when it differs from node address

### ISSUE THREAD

**Issue by digitalronin** [hashicorp/consul-template#342]
I've got a private network where my haproxy servers and backends live, and a consul cluster that sits outside of that. So, my backend nodes advertise a different IP address for the service, compared to the IP address of the node itself, from the consul cluster's POV.

i.e. something like this;

    curl http://localhost:8500/v1/catalog/service/myservice?pretty

    [
        {
            "Node": "backend1",
            "Address": "1.2.3.4",
            "ServiceID": "myservice",
            "ServiceName": "myservice",
            "ServiceTags": null,
            "ServiceAddress": "10.0.0.1",
            "ServicePort": 0
        },
        {
            "Node": "backend2",
            "Address": "1.2.3.5",
            "ServiceID": "myservice",
            "ServiceName": "myservice",
            "ServiceTags": null,
            "ServiceAddress": "10.0.0.2",
            "ServicePort": 0
        },

        ...
    ]

I need the ServiceAddress value in my haproxy config, but I can't seem to get it.

The relevant part of my template looks like this;

    {{range service "myservice"}}
            server {{.Node}} {{.Address}}:8888{{end}}

".Address" evaluates to the address of the node, not the ServiceAddress, but ".ServiceAddress" gives me the following error;

    ServiceAddress is not a field of struct type *dependency.HealthService

Is there a way to get the ServiceAddress in this situation? i.e. where it's different from the address of the node?

My consul-template version is 0.10.0

**Comment by digitalronin** [comment]
Sorry, please ignore me. I had an old version of consul on the node where I was trying to generate the template. After updating it, I'm getting the correct address value.

**Comment by piontec** [comment]
How did you solve this? I'm running into the same issue now with consul v0.8.3 and consul-template v0.18.5
