### ISSUE TITLE
publish executables for consul-template

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/consul-template#343]
While it is easy to build/install, consul-template is a great tool, and I believe it would be valuable (and increase adoption) to include consul-template (publish the executables) with the rest of the consul suite of utilities.

**Comment by sethvargo** [comment]
Hi @ketzacoatl 

You can download the executable from the releases page here: https://github.com/hashicorp/consul-template/releases and click on any release (for example: https://github.com/hashicorp/consul-template/releases/tag/v0.10.0) and download the version for your operating system.

Does that answer your question?

**Comment by ketzacoatl** [comment]
Hi @sethvargo,

Right you are, how silly of me not to look there. That certainly answers my question, though I would like to vote for getting a link to the releases page on the http://www.consul.io/downloads_tools.html

**Comment by sethvargo** [comment]
Hi @ketzacoatl 

We generally link directly to the repository, and the README says the following under the installation steps:

> You can download a released consul-template artifact from [the Consul Template release page](https://github.com/hashicorp/consul-template/releases) on GitHub.

I'll try to make that a bit clearer. Thanks! :smile:

**Comment by ketzacoatl** [comment]
I'm not sure how I missed that too.

I can send a PR with the following update if you wanted to make that clearer:
> You can download the latest release executable from the [Github Releases](https://github.com/hashicorp/consul-template/releases) page.

otherwise ignore me :)

**Comment by satish-zettata** [comment]
Hi @sethvargo,
  after installing consul -template ,we have to paste that binary file in directory  /usr/local/bin?
