### ISSUE TITLE
Trouble filtering byKey

### ISSUE THREAD

**Issue by alpduhuez** [hashicorp/consul-template#345]
Hi,
I'm trying to find a key based on a node's name.  The byKey filter does not seem to be working.

This will not compare the Node name to the Key.
```
{{range ls "reporting/" | byKey}}{{node.Node.Node}}
{{.Key}}={{.Value}}{{end}}
```

The only way I have been able to get the two to match is using the regexMatch
```
{{with node}}{{$nodeName := node.Node.Node | replaceAll "." "_" }}
{{range ls "reporting/"}}
{{$key := .Key | replaceAll "." "_" }}
{{$key}}***{{$nodeName}}
{{if $nodeName | regexMatch $key }}{{.Value}}{{end}}{{end}}{{end}}
```

I am guessing that I am running into type issues?

What I would really like to do is this:
```
{{range ls "reporting/${nodeName}" | byKey}}{{node.Node.Node}}
{{.Key}}={{.Value}}{{end}}
```
Thoughts?
Thanks!

**Comment by sethvargo** [comment]
Hi @alpduhuez 

I think you need to separate the keys from the values:

```
{{range $key, $pairs := tree "reporting" | byKey}}{{$key}}:
{{range $pair := $pairs}}  {{.Key}}={{.Value}}
{{end}}{{end}}
```

https://github.com/hashicorp/consul-template#bykey

**Comment by alpduhuez** [comment]
Thanks for the pointer on the 'tree' command, that led me to a little cleaner solution for querying for keys are based on the Node names.
```
{{with node}}
{{range $key, $pairs := tree "reporting/kafka" | byKey}}
{{range $pair := $pairs}}{{if eq node.Node.Node .Key}}broker.id={{.Value}}{{end}}
{{end}}{{end}}{{end}}
```
