### ISSUE TITLE
can I skip rendering when watcher reported error?

### ISSUE THREAD

**Issue by ruoshan** [hashicorp/consul-template#346]
hi,
    I have this problem (pasted below). as the healthcheck had error, and the watcher reported the error in the runner's loop, but the runner still render the template with empty data and restart the haproxy.
    The log said it would retry, but runner didn't wait til retry, instead, it rendered and called the command instantly.

(CT V0.9.0)
```
2015/07/30 09:55:00 [DEBUG] ("service(release.YYY)") 1 services after health check status filtering
2015/07/30 09:55:00 [DEBUG] (view) "service(release.YYY)" no new data (contents were the same)
2015/07/30 09:55:00 [DEBUG] ("service(release.YYY)") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:1532615 WaitTime:1m0s Token:}
2015/07/30 09:55:00 [ERR] (view) "service(release.YYY)" health services: error fetching: Unexpected response code: 500 (rpc error: rpc error: unexpected EOF)
2015/07/30 09:55:00 [INFO] (view) "service(release.YYY)" errored, retrying in 5s
2015/07/30 09:55:00 [ERR] (runner) watcher reported error: health services: error fetching: Unexpected response code: 500 (rpc error: rpc error: unexpected EOF)
2015/07/30 09:55:00 [INFO] (runner) running
2015/07/30 09:55:00 [DEBUG] (runner) checking template /data/XXX/etc/haproxy-tmpl/YYY.tmpl
2015/07/30 09:55:00 [DEBUG] (runner) checking ctemplate &{Source:/data/XXX/etc/haproxy-tmpl/YYY.tmpl Destination:/data/XXX/etc/haproxy/YYY.cfg Command:/usr/sbin/haproxy -f /data/XXX/etc/haproxy/YYY.cfg -sf `cat /data/XXX/pid/YYY-haproxy.pid`}
2015/07/30 09:55:00 [DEBUG] (runner) wouldRender: true, didRender: true
2015/07/30 09:55:00 [DEBUG] (runner) appending command: /usr/sbin/haproxy -f /data/XXX/etc/haproxy/YYY.cfg -sf `cat /data/XXX/pid/YYY-haproxy.pid`
2015/07/30 09:55:00 [INFO] (runner) diffing and updating dependencies
2015/07/30 09:55:00 [DEBUG] (runner) "service(release.YYY)" is still needed
2015/07/30 09:55:00 [DEBUG] (runner) running command: `/usr/sbin/haproxy -f /data/XXX/etc/haproxy/YYY.cfg -sf `cat /data/XXX/pid/YYY-haproxy.pid``
```

**Comment by sethvargo** [comment]
Hi @ruoshan 

Can you please share you complete configuration file and the exact consul-template command you ran?

**Comment by ruoshan** [comment]
I can't reproduce the error in my VM, but the timing in the log above is quite strange.
And when testing with a single consul and CT, CT didn't rerender things when I terminated the consul. That looks right as I wish. but I can't produce the situation again that healthcheck got an `500` rpc error. :(

## CT is run like:
$ consul-template -config=/data/etc/consul-template/YYY.hcl -log-level=debug 2>LOGFILE

## CT config
```
consul = "127.0.0.1:8500"
retry = "10s"
log_level = "debug"

template {
  source = "/data/XXX/etc/haproxy-tmpl/YYY.tmpl"
  destination = "/data/XXX/etc/haproxy/YYY.cfg"
  command = "/usr/sbin/haproxy -f /data/XXX/etc/haproxy/YYY.cfg -sf `cat /data/XXX/pid/YYY-haproxy.pid`"
}
```

## template
```
# some static configs are left out

listen YYY
    stick-table type ip size 1k expire 30m store http_req_rate(10s),conn_cur
    tcp-request connection track-sc0 src
    option forwardfor header X-Real-IP
    bind *:3001{{range service "release.YYY"}}
    server {{.Node}} {{.Address}}:{{.Port}} check inter 5s{{end}}
```

**Comment by ruoshan** [comment]
hi @sethvargo , any idea of how to fix this?

**Comment by sethvargo** [comment]
@ruoshan I have not been able to reproduce this issue. Until I can identify the underlying cause, I don't have any ideas on how to fix it. Are you still experiencing it? Do you have any additional information you could share?

**Comment by ruoshan** [comment]
@sethvargo I'll give it another shot. BTW if I use `service "XXX" "any"` directive, will CT use other consul http api instead of the `health service` one?

**Comment by sethvargo** [comment]
@ruoshan it uses the same service endpoint, but allows failing nodes

**Comment by ruoshan** [comment]
@sethvargo got it. I'll dig into this issue and send my feedback. thanks

**Comment by ruoshan** [comment]
@sethvargo I think it maybe my mistake that the destination file was changed outside of CT, and caused this wired log: `2015/07/30 09:55:00 [DEBUG] (runner) wouldRender: true, didRender: true`.

so sorry to bother you with this issue :(

I have one more question: in the `runner.Start()` function, why not break out to the outer `for` loop when `r.watcher.ErrCh` has something, so the `r.Run()` will not be called.
