### ISSUE TITLE
Consul token

### ISSUE THREAD

**Issue by a-nldisr** [hashicorp/consul-template#352]
When i look at the token in your template example, i asume this is the same value as the encrypt value in the consul-client/server/bootstrap. But am i correct? Is the token a shared value that is generated by consul keygen?

```
{
  consul = "127.0.0.1:8500"
  token = "abcd1234" // May also be specified via the envvar CONSUL_TOKEN
  retry = "10s"
  max_stale = "10m"
  log_level = "warn"
  pid_file = "/path/to/pid"
}
```

```
{
  "encrypt": "UgmMsZwR2XFNGGvJTnpHRg=="
}
```

**Comment by sethvargo** [comment]
Hi @a-nldisr 

This is not the encrypt token, it is the API token used for ACLs. If you do not have ACLs enabled, you do not need a token. You can read more here: https://www.consul.io/docs/internals/acl.html. Does that answer your question?

**Comment by a-nldisr** [comment]
Hi Seth, Yes thanks. I do have another question regarding SSL. Shall i open another ticket for that?

**Comment by sethvargo** [comment]
Hi @a-nldisr 

Yes, please open another ticket; it's helps maximize the google-ability.
