### ISSUE TITLE
Issues with parseInt

### ISSUE THREAD

**Issue by bmonkman** [hashicorp/consul-template#353]
I've been having some issues using `parseInt` with the return value of the key function in version 0.10.0.

When I call 

```liquid
{{ key "config/min-servers" | parseInt }}
```

I get:

```
executing "template.conf" at <parseInt>: error calling parseInt: parseInt: strconv.ParseInt: parsing "": invalid syntax
```

But if I put in a string containing the same value as that key in Consul it works fine.

It behaves the same way if I assign the return value of key to a variable and then use parseInt on the variable.

I also see some problems when trying the example from the readme:

```liquid
{{range $i := loop key "config/pool_size" | parseInt}}
# ...{{end}}
```

Gives the error:

```
executing "template.conf" at <key>: wrong number of args for key: want 1 got 0`
```

When I add some quotes like this:

```liquid
{{range $i := loop ( (key "config/pool_size") | parseInt ) }}
# ...{{end}}
```

It resolves that problem but I still get the first issue with parseInt

Any ideas?

Thanks!

**Comment by bmonkman** [comment]
Hmm I'm guessing this is because of multi-phase execution.. If I wrap it in a with, it seems to work.

    {{ with key "config/min-servers" }}
    {{ key "config/min-servers" | parseInt }}
    {{ end }}

Unfortunately this complicates my template quite a bit because of the limitations with variable scope within the "with" block.

**Comment by sheldonkwok** [comment]
In the notes for parseJSON it describes solutions 
https://github.com/hashicorp/consul-template#parsejson
