### ISSUE TITLE
service names with periods don't populate from template

### ISSUE THREAD

**Issue by atomi** [hashicorp/consul-template#354]
This works
```
  {{range service "webapp"}}
```
This doesn't

```
  {{range service "www.myapp.com"}}
```

consul-template v0.10.0

I'm using underscores in the meantime and regex replace :/

**Comment by sethvargo** [comment]
Hi @atomi 

This is a known issue, but not a bug. You should not use dots in service names and Consul specifically calls this out in the documentation; it messes with the DNS query interface.

The "dots" have special meaning in CT as it specifies the [tag](https://github.com/hashicorp/consul-template#service) search attribute.

Please let me know if you have any questions.

**Comment by atomi** [comment]
Thanks.
