### ISSUE TITLE
How to get consul peers

### ISSUE THREAD

**Issue by sielaq** [hashicorp/consul-template#355]
H

Mostly consul servers (aka peers - `/v1/status/peers`) are working on specific hosts
that are statically assigned to this function
In our use case also do some other specific functions (like  mesos+master + marathon and others) 

is there possibility to get those IPs of consul peers,
kind of extra option for `{{nodes}}` ? (nodes contains that list but also with slaves)

**Comment by slackpad** [comment]
Hi @sielaq if I understand correctly, you are trying to use the peer addresses to discover other functions that run on the same machines as your Consul servers. Have you considered registering regular Consul service definitions for those other functions and using the regular service lookup mechanism in consul-template? That way those won't be tied to the special case of the Consul peers, which is tied to Consul's internal workings and Raft, and not really intended to be used to service discovery (for example, you could move those functions to other machines and things would still work).

**Comment by sielaq** [comment]
I have consider that, but I'm looking for alternative solutions.

**Comment by sielaq** [comment]
Ok. peers are automatically registered with consul.service.consul 
so ticket closed :)
