### ISSUE TITLE
Issue with services that include dot on the name 

### ISSUE THREAD

**Issue by bernardeli** [hashicorp/consul-template#356]
Hi,

I had a setup with consul + consul-template + nginx working fine, until launching services with dots.

See below the current setup:

### Consul

```
curl $CONSUL_URL/v1/catalog/services | jq .
{
  "consul": [],
  "projector.nginx-v13": [],
  "web.nginx-v13": [],
  "worker.nginx-v13": []
}

curl $CONSUL_URL/v1/catalog/service/web.nginx-v13 | jq .
[
  {
    "Node": "staging-b-slave",
    "Address": "10.75.95.48",
    "ServiceID": "consul:10.75.95.48:web.nginx-v13:31941",
    "ServiceName": "web.nginx-v13",
    "ServiceTags": null,
    "ServiceAddress": "10.75.95.48",
    "ServicePort": 31941
  },
  {
    "Node": "staging-a-slave",
    "Address": "10.75.91.11",
    "ServiceID": "consul:10.75.91.11:web.nginx-v13:31331",
    "ServiceName": "web.nginx-v13",
    "ServiceTags": null,
    "ServiceAddress": "10.75.91.11",
    "ServicePort": 31331
  }
]
```

#### With `range services`, and then `range service .Name`:

```
{{ range services }}
# {{ .Name }}
{{ range service .Name }}-> Found: {{.Address}}.
{{ else }}-> Empty!
{{ end }}
{{ end }}
```

Output:
```
# consul
-> Found: 10.75.91.11.
-> Found: 10.75.95.0.
-> Found: 10.75.95.48.

# web.nginx-v13
-> Empty!
```

#### With `service "consul"` and `service "web.nginx-v13"`:

```
# consul
{{ range service "consul" }}-> Found: {{.Address}}.
{{ end }}
# web.nginx-v13
{{ range service "web.nginx-v13" }}-> Found: {{.Address}}.
{{ else }}-> Empty!
{{ end }}
```

Output:
```
# Consul
-> Found: 10.75.91.11.
-> Found: 10.75.95.0.
-> Found: 10.75.95.48.

# web.nginx-v13
-> Empty!
```

Running that with: `consul-template -consul $CONSUL_URL -template default.conf.ctmpl -dry -once`

Consul-template version: v0.10.0
Consul version: v0.5.2

I've spent few hours trying different things but none helped. 

Any obvious mistake I'm making? I was hoping someone can shed some light for me.

Thanks

**Comment by slackpad** [comment]
Hi - this came up recently under #354 - here are the details (from @sethvargo):

> This is a known issue, but not a bug. You should not use dots in service names and Consul specifically calls this out in the documentation; it messes with the DNS query interface.

> The "dots" have special meaning in CT as it specifies the tag search attribute.

Let us know if you have any questions!

**Comment by bernardeli** [comment]
Thanks @slackpad - appreciated. My bad not going through closed issues.

**Comment by terryzwt** [comment]
@sethvargo Any suggestion to solve this problem. I have struggle whole night on this problem and then I found this issue.

In our situation, we do need using the domain(with dot) in consul template.

Thanks in advanced.

**Comment by terryzwt** [comment]
@bernardeli just in curious, have you resolve this problem in other way? Thanks for early reply.

**Comment by bernardeli** [comment]
@terryzwt I took the advice above and didn't use dots to avoid messing up with DNS query interface. 

Sorry not being helpful. It's also been more than 2 years I don't use consul.
