### ISSUE TITLE
range service with regexMatch

### ISSUE THREAD

**Issue by ljcp** [hashicorp/consul-template#357]
I want to list all the services that starts with webserver

webserver-one
webserver-two
....

```
{{range service | regexMatch "webserver*"}}
      server {{.Name}}:{{.Port}};
                {{else}}
                        server 127.0.0.1;
                {{end}}

```

but i throws an error ? any clues

**Comment by sethvargo** [comment]
Hi @ljcp,

The `regexMatch` function expects a string parameter to match again and returns a boolean value. I think you want something like this instead:

```liquid
{{range service}}
{{if .Name | regexMatch "webserver*"}}
server {{.Name}}:{{.Port}}...
{{end}}
{{end}}
```

But also note that if your service is named "webserver", you can just pass that as an argument to the `service` call to filter by name. It does not accept wildcards though.

Does that answer your question?

**Comment by ljcp** [comment]
Hi @sethvargo  thank you for the fast response

I just tested the next
```
                {{range service}}
                {{.Name}}
                {{if .Name | regexMatch "webserver*"}}
                        server {{.Name}}:{{.Port}};
                {{end}}
                {{else}}
                        server 127.0.0.1;
                {{end}}
```

the result 

```
server 127.0.0.1;
```

looks like the {{range service}} without any other param doesn't returns any data , and using {{range services }}  i'm not sure how to get the .Port ( I think services doesn't support health check )

also if the if never enters how can I add a default like server 127.0.0.1;


thank so much in advance !

**Comment by sethvargo** [comment]
Hi @ljcp 

I don't think you want the second `end` before the `else`. I'm not exactly sure what you're end goal is...

**Comment by ljcp** [comment]
@sethvargo  the result of this code

```

{{range service}}
                {{.Name}}
{{end}}

```
returns empty

What i want is the next 

I have several services running in the same port for example

webserver-one:8080
webserver-two:8080
webserver-three:8080

so I want to list those in my nginx upstream and if there are no services found with that name i want to add a default 

pseudo code 
```
range service webserver* 
      {{.Name}}:{{.Port}}
 else
      127.0.0.1:80
```

Let me know if that make sense to you

**Comment by sethvargo** [comment]
Hi @ljcp 

Hmmm that's not really possible with Consul Template. If you name all the services the same thing and then provide that service name as an argument to the `service` call it will work, but there's no concept of a "map" function in Go's templating language.

It's possible to say "if this string does not match a regex, do something" and "if there are no services, do something", but it is not possible to say "give me all the services that match this regex, do nothing if there are none". That's a `map` function, and unfortunately Go's templating language doesn't allow for that.

If you name N services that you want to load balance, you can name them the same thing like so:

```liquid
{{ range "webserver" }}
  {{.Address}}:{{.Port}}
{{ else }}
  127.0.0.1:80
{{ end }}
```

I'm not sure how you have data structured in Consul, but it's perfectly acceptable to have a service with multiple nodes. The `service` method is used for querying a specific _service_ (not _server_). Give all your webservers a webserver service and then query by that service.

Does that make sense?

**Comment by ljcp** [comment]
thank you so much! @sethvargo 

I guess I still need to learn about consul,  going to look another alternative on how I'm creating my services!! 

I guess I'm going to use a tag :)  

web.service.consul  <--- service

server-one.web.service.consul  <--tag
server-two.web.service.consul  <--tag

I'm using an internal docker config and each container is a service and each service can have the same port.

**Comment by sethvargo** [comment]
@ljcp there's also node queries. If you need to care about specific queries, you can query the node namespace:

```
server-one.node.consul
server-two.node.consul
```

I would not recommend tagging services by their node name.

**Comment by ljcp** [comment]
@sethvargo maybe you can help me to understand your recommendation 

currently i have 

```
curl 172.17.42.1:8500/v1/catalog/nodes
[{"Node":"node1","Address":"172.17.0.43"}]

curl 172.17.42.1:8500/v1/catalog/services
{"consul":[],"server1":[],"server2":[]}

curl 172.17.42.1:8500/v1/catalog/service/server2
[{"Node":"node1","Address":"172.17.0.43","ServiceID":"server2_id","ServiceName":"server2","ServiceTags":null,"ServiceAddress":"172.17.1.2","ServicePort":8000}
```

```
@dig node1.node.consul it will return the 172.17.0.43
```
```
@dig server2.service.consul it will return 172.17.1.2
```
```
@dig server2.service.node1.node.consul looks like is not possible.
```
not sure what is your recommendation , 

1. doing a new node for each service  and ignoring the service api 
      server1.node.consul
      server2.node.consul but the node doesn't have a port 

2. (I guess this is what you mean ) 
I  can have a node just for my webservers another node for my databases..etc

so I can query with consult template  the  mainservernode.node.consul and it will return all child services inside it ?

    



Thank you so much for your time , I really appreciate it

**Comment by sethvargo** [comment]
@ljcp I think you are conflating "service" and "server". A service is logical (like redis or nginx). A server is physical (like "node5" or "192.168.4.23"). Multiple nodes can be attached to a single logical service.

For example, let's say you have three nginx nodes that all serve frontend traffic. You wouldn't create three services, you would create one service called "web" and add that service definition to those three nginx nodes.

I'm still not exactly following what you're trying to achieve, but it looks like you're thinking in terms of servers instead of services.

**Comment by ljcp** [comment]
thank you for your patience :100:  now I I understood :)

**Comment by ljcp** [comment]
@sethvargo  I have been testing it through the day and I found something


running the next template that list all the services in a specific node 


``` 
upstream xxxxxxx {
		{{with node "xx" }}
			{{range .Services}}
                            	server {{.Service}}.service.xx.xx.xx:{{.Port}};
                        {{end}}
		{{end}}
	}
```

that works correct ! , but there a bunch of white spaces in the generated file


```
http {
	upstream xxx_xxxx {























                            	server xxx.service.xxx.xxx.xx:8443;









	}

```

I really don't care to have whitespaces but could be an improvement 

and another interesting things is if the daemon is running 

```
/consul-template -consul=$CONSUL_URL -template "/etc/consul-templates/nginx/nginx.ctmpl:/etc/nginx/nginx.conf:nginx -s reload" -wait 30s
```

and I check the generate file with   cat /etc/nginx/nginx.conf it throws weird things!! like
```
user root;
user root;

events {
        worker_connections 1024; # Default


                                server xxx.service.xxx.xx.xxxx:8443;












        }

```

as you see instead of adding the service inside of the upstream it add it also add it  to the events and two user root; are shown and I just have one 

but if i do nginx -s reload everything runs fine(it should break with something like this) and if I stop the daemon I can correctly see the latest generated file. so I guess is ok 


Kind Regards

**Comment by sethvargo** [comment]
Hi @ljcp 

The first issue with whitespace is not a Consul Template issue, but rather a Go templating issue. You're looping over something that includes whitespace. I usually play around with it, but you'll want to reduce whitespace like this:

```liquid
upstream xxxxxxx {
{{with node "xx" }}{{range .Services}}
  server {{.Service}}.service.xx.xx.xx:{{.Port}};
{{end}}{{end}}
}
```

The second issue simply isn't possible. `user root` is an nginx-specific configuration that is coming from somewhere in your template. Consul Template has no nginx-specific configuration and would not automatically add that - it simply isn't smart enough to even know that's a thing. I would be willing to bet that declaration exists in your template as well :smile:.

**Comment by ljcp** [comment]
@sethvargo going to change it thanks !!,  yeah  in my template i have the user root; but it duplicates it when the daemon is up and i do cat to see the generated file , I'm using a docker volume container for the template and nginx config  so I guess I'm looking something stale in someway but it doesn't matter nginx seems to see the correct one :+1: 

again thank you!

**Comment by thiamteck** [comment]
@ljcp not sure if you still working on this use case regexMatch on service name, I manage to get the example below working:

```
listen http-in
    bind *:8000 {{range services}}{{if .Name | regexMatch "web0*"}}{{range service .Name}}
    server {{.Name}} {{.Address}}:{{.Port}} {{end}}{{end}}{{end}}
```

which produce:

```
listen http-in
    bind *:8000
    server web01 127.0.0.1:5001
    server web02 127.0.0.1:5002

```
