### ISSUE TITLE
Support for renewing vault token

### ISSUE THREAD

**Issue by AndrewKlopper** [hashicorp/consul-template#359]
As far as I can tell, consult-template does not have support for renewing the vault token used to retrieve secrets. Since all tokens except those using the 'root' policy have a maximum lease time of 30 days, this means that the vault token used by consul-template will eventually expire and require a restart of the consul-template process. This in turn will result in losing all in-memory secret leases held by consul-template, meaning all config files managed by consul-template that contain dynamic secrets will have to be regenerated, and the associated processes restarted.

Am I missing something, or is there a way around this to avoid unnecessary interruptions in service?

**Comment by sethvargo** [comment]
Hi @AndrewKlopper 

CT automatically renews _secrets_ requested from Vault, but it does not renew the token used to communicate. This is a bug. Tagged. Thanks! :smile:
