### ISSUE TITLE
 ServiceAddress is not a field of struct type *main.Service

### ISSUE THREAD

**Issue by yeasy** [hashicorp/consul-template#362]
I use consul-template to get service information from consul.
It seems receives the data, but cannot get the ServiceAddress.
Anyone know how to debug this?

The default conf fields to be generated from consul-template is:

{{range service "backend.web"}}server {{.ServiceAddress}}:{{.ServicePort}}

**Comment by sethvargo** [comment]
Hi @yeasy 

I think you just want `Address`. https://github.com/hashicorp/consul-template/blob/a8e96a0fa031ae461a6e91367881702a9f170f17/dependency/health_service.go#L26-L35

Please let me know if you have any other questions! :smile:

**Comment by yeasy** [comment]
So the Address field is mapping to ServiceAddress in consul?
Thanks!

**Comment by sethvargo** [comment]
Hi @yeasy 

It tries to use the service address first, then falls back to the node address if the service doesn't have one: https://github.com/hashicorp/consul-template/blob/a8e96a0fa031ae461a6e91367881702a9f170f17/dependency/health_service.go#L99-L105.

**Comment by yeasy** [comment]
@sethvargo Thanks!
I checked the output of consul, there did be a Service Address, however, consul-template get the node address by using `Address`. 
Maybe we should add another `ServiceAddress` field to distinguish between each other?

**Comment by sethvargo** [comment]
Hi @yeasy 

Can you share the Consul output?

**Comment by yeasy** [comment]
Sure, the output of Consul is 
`[{"Node":"consulserver","Address":"172.17.1.145","ServiceID":"registrator:composeconsuldiscovery_web_1:80","ServiceName":"web","ServiceTags":["backend"],"ServiceAddress":"172.17.1.144","ServicePort":80}]`

When using `{{.Address}}`, the value is "172.17.1.145", while I wanna get "172.17.1.144".

**Comment by sethvargo** [comment]
@yeasy what endpoint are you querying?

**Comment by yeasy** [comment]
Checkout the latest code, now it works!

By the way, do we need to distinguish the node address from service address in consul-template?

**Comment by sethvargo** [comment]
Hi @yeasy 

Awesome to hear. 

I'm not sure what you're asking, but `Address` will always correspond to the `ServiceAddress` and `NodeAddress` will always correspond to the node's address.

**Comment by yeasy** [comment]
Oh, understand.
Maybe both names from consul, consul-template can be more aligned with each other.
I guess `ServiceAddress` and `NodeAddress` should be good enough for usage.

**Comment by sethvargo** [comment]
@yeasy 

I agree it can be confusing. The thinking was this - when you search for a service like so:

```liquid
{{ service "foo" }}
```

Everything refers to the "service" by default. So `Address` would refer to the Service's address. If you wanted the specific node, you could get the node's address.

That being said, it is incredibly rare to want the Node's address. You are searching for the service address and want the address and port of the service (which should be exposed). It is unlikely you want the address of the "physical" node, since it could be running multiple services and not listening on the correct ports.

Does that make sense?

**Comment by yeasy** [comment]
yes, agree.
And in most cases, we want the service address instead of the node.
Thanks, now I can make my test works. 
Also, I write down a docker-compose template, please feel free to drop comments!

see [https://github.com/yeasy/docker-compose-files/blob/master/consul-discovery/docker-compose.yml](https://github.com/yeasy/docker-compose-files/blob/master/consul-discovery/docker-compose.yml)
