### ISSUE TITLE
support tag like "protocol:XXX" in `service` directive

### ISSUE THREAD

**Issue by ruoshan** [hashicorp/consul-template#363]
I use tags like `[ "protocol:xxx", ...]` a lot. Can the regular exp in `ParseHealthServices` support the `:` in parsing the `tag`. thanks

**Comment by ruoshan** [comment]
I can get around this with `byTag`, but `service "protocol:xxx.service"` would be nice.

**Comment by ruoshan** [comment]
Find out that `.Tags` has a method `.Contains` implemented, I can use this in `if` :)

**Comment by sethvargo** [comment]
Hi @ruoshan 

This is a duplicate of https://github.com/hashicorp/consul-template/issues/33. You are correct, the best solution is using the Contains function for now until we can get this functionality from Consul core.

Thanks! :smile:
