### ISSUE TITLE
Vault app-id auth method support

### ISSUE THREAD

**Issue by ekristen** [hashicorp/consul-template#365]
Is this supported? If not, is there any chance in getting the app-id auth method supported for vault?

**Comment by sethvargo** [comment]
Hi @ekristen 

This is not currently supported. Consul Template expects to be given a VAULT_TOKEN envvar. This is fairly common for applications that need to communicate with Vault. If you want to use the app-id authentication, I would recommend running it out-of-band of consul template and then export the environment variable.

Does that make sense?

I have noticed you have opened a number of tickets on different projects for AppID authentication. I am super excited you are using Vault, but I also do not think it is sustainable for every project to support every authentication/login mechanism for Vault. Vault itself has the primary support for authentication, and you end up clouding the CLI with vault-specific options which should really be the responsibility of Vault itself. It is my belief that all applications should expose the "give me a vault token" interface, and it is the responsibility of the caller to generate/provide that token. Does that make sense?

**Comment by ekristen** [comment]
Hey @sethvargo thanks for the reply.  I get what you are saying and it makes sense for everything except the app-id authentication method IMHO.

Having an out-of-band process for every application that requires AppID authentication is just not scalable or sustainable. 

To me the whole idea behind app id, is that it'll only work if the said application is running on the right machine where the user-id and the app-id can be combined and used to get a token. Without having this built into applications it makes very little sense to try and use it. 

In the case of consul template, I would have to run another process out-of-bound that would have to login to vault using the app-id and user-id, get the token, update the consul template config, restart consul-template and then monitor and renew the token and repeat. Doing this for 10 or even 2 apps doesn't scale well.

Anyways, just my two cents. Appreciate everything you are doing!

**Comment by sethvargo** [comment]
Hi @ekristen 

Okay, consider the GitHub backend then. Or simple username/password authentication. These all share the same requirement. It gets exponentially more complex if users have custom mount points or attributes they want to use.

I gave myself some time to think about this over lunch and I think there's a happy middleground that is scalable. Similar to a Postgres connection string, we should come up with a syntax for a vault token string that includes the necessary authentication information, mount points, attributes, and more. That endpoint should be assumed to return a string that is a vault token. Something like:

    vault://127.0.0.1:8200/auth/app-id?app_id=abcd&user_id=efgh&mount=foo&thing=bar

Thoughts?

**Comment by ekristen** [comment]
Thanks for taking some time to think about it.

I agree that it gets exponentially more complex if having to support all the various authentication methods, I get and appreciate that. I also don't necessarily thing that all auth methods should be supported (ie GithHub, User/Pass, LDAP)

If AppID is about application identification, I do think it makes sense to natively support this in applications that support vault integration. 

GitHub, User/Pass, LDAP to me all user based interactions and do not need to be supported, the majority of the time these would be used for interaction with the vault cli tool.

**Comment by sethvargo** [comment]
Okay cool. I am going to close this as a duplicate of https://github.com/hashicorp/consul-template/issues/318 for now. But I'm cross-linking so we can come up with a general solution. Thanks!
