### ISSUE TITLE
Checking for Consul k/v keys produces log spam

### ISSUE THREAD

**Issue by JayH5** [hashicorp/consul-template#368]
A common pattern is to check for the presence of a key and if it is not present, use a default value.
```
{{if key "service/app/max_conns"}}
  max_conns={{key "service/app/max_conns"}}
{{else}}
  max_conns=500
{{end}}
```

But doing this produces a constant stream of log messages:
```
2015/08/20 11:27:56 [WARN] ("key(service/app/max_conns)") Consul returned no data (does the path exist?)
2015/08/20 11:28:58 [WARN] ("key(service/app/max_conns)") Consul returned no data (does the path exist?)
...
```

Should this really be a `WARN` message? It seems like `DEBUG` is more suited.

**Comment by sethvargo** [comment]
Hi @JayH5 

This is working as intended. If you search through old issues (I don't have the number off hand), users wanted a warning because of typographical errors. 

Also note, I believe you could refactor this as:

```liquid
max_conns={{or (key "service/app/max_conns") 500}}
```

That won't make the warning go away though.

It's challenging to find a balance to suit everyone's needs, but I think warning for a non-existent key is the correct UX, even if it's chatty. What do you think?

**Comment by JayH5** [comment]
Thanks for the reply.

I did have a search through the issues before creating this one but didn't manage to find that issue.

I still think `DEBUG` is more suited to this case... `WARN` to me signifies something like a "recoverable error", not someone using a function in one of the ways it was intended (but not the *main* way).

Otoh, I guess people hardly ever think to set the log level as low as debug so I suppose this is reasonable...

**Comment by sean-** [comment]
If a key doesn't exist, can we suppress future notifications for N seconds that way some folk could set it to 86400 and only get this message once a day?  It's not the space that's the concern, it's the signal-to-noise ratio that's important.

**Comment by sethvargo** [comment]
@JayH5 @sean- what if we move it to an info level - then you can just run with log-level warn if you don't care

**Comment by JayH5** [comment]
@sethvargo Moving from `WARN` to `INFO` would not make much difference to me. I wouldn't switch the log level to `WARN` as then we would lose basically any messages that would let us know consul-template is working -- we'd only get messages when something goes wrong.

I'm still pro making it `DEBUG` but I wouldn't lose much sleep over it if that didn't happen :sweat_smile:

**Comment by sethvargo** [comment]
@JayH5 okay I understand that. You're obviously a "power user", but I think this is one of those situations where we have to optimize for the "regular user". It's a terrible UX to accidentally have a typo and spend hours debugging it when a simple WARN statement would have avoided the rabbit hole. Users were _actually experiencing this_ (i.e. this isn't a contrived use case :wink:)

I'm going to think about this a bit more

/cc @armon @ryanuber

**Comment by JayH5** [comment]
@sethvargo I'm also pro good UX... the logging UX at the moment is not good for my use case :wink:

Another option is to add something like a `key_get` (or `key_fetch`?) function that gets the value of a key if the key exists or returns Nil/empty string. Then the `key` function could throw an exception if the key doesn't exist. Similar to some languages like Python. But that breaks the API so probably not the best option.

Would it be possible to do something more like a Go map? 
`{{$value, $present := key "service/app/max_conns"}}{{if $present}}...`
Although that might not help much...

Anyway, this is starting to feel a bit like bikeshedding...

**Comment by amochtar** [comment]
@JayH5 I ran into the same issue, and worked around it by using [explode](https://github.com/hashicorp/consul-template#explode). This way you can check whether max_conns exists.

In your case I think it would look like something like this:
```
{{ with ls "service/app" | explode }}
  {{ if .max_conns }}
    max_conns={{ .max_conns }}
  {{ else }}
    max_conns=500
  {{ end }}
{{ end }}
```

**Comment by JayH5** [comment]
Hi @amochtar. Thanks, yes I was aware of this. Using `ls`/`tree` + `explode` still seems like overkill when you just want to get 1 value, but it's one solution.

**Comment by c4po** [comment]
Can we add an `exist` API function to test if key is existing?

**Comment by 123BLiN** [comment]
Hello, could you revisit this for a such usecase:
Get one KV, if not found get second KV (default)
e.g. 
`{{$healthcheck := (key_or_default (printf "/nginx/profiles/%s/healthcheck" .Name) (or (printf "/nginx/%s/healthcheck" $type | key) "false")) | parseBool}}`
still produces spam:
```
2015/11/24 12:36:46 [WARN] ("key(/nginx//healthcheck)") Consul returned no data (does the path exist?)
2015/11/24 12:36:46 [WARN] ("key(/nginx//healthcheck)") Consul returned no data (does the path exist?)
```
