### ISSUE TITLE
Removing keys doesn't seem to rebuild template.

### ISSUE THREAD

**Issue by darron** [hashicorp/consul-template#37]
Here's what I've done:

https://gist.github.com/darron/5c3b84036f6aad0eb43a

And key2 is definitely gone:

http://shared.froese.org/2014/2n411-12-23.jpg

Am I missing something? Or is there a bug here?

Thanks for all your work already - it looks like a great solution to a few problems I'm working on.

**Comment by armon** [comment]
This should now be fixed upstream. It will be part of Consul 0.5
