### ISSUE TITLE
consul template leaks file descriptors opened by consul-template into processes invoked by command

### ISSUE THREAD

**Issue by piavlo** [hashicorp/consul-template#371]
Seems like due to execve
https://github.com/hashicorp/consul-template/blob/master/runner.go#L597
command controlled by consul template "command" will inherit file descriptors of consul-template process

The specific issue i hit , is that consul-template init.d scripts uses flock based locks to make sure there is no other instance of consul-template running in the system, and thus consul-template cannot be restarted since processes which consul-template started also have this lock opened

for example

<pre>
# lsof /var/run/lock/consul-template
COMMAND    PID    USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
consul-te 9059    root    3w   REG   0,17        0 542758 /run/lock/consul-template
haproxy   9072 haproxy    3w   REG   0,17        0 542758 /run/lock/consul-template
#
</pre>

**Comment by sethvargo** [comment]
Hi @piavlo 

Can you please provide the output of `lspf -`p?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. I am happy to revisit this once we can get more information :smile:.
