### ISSUE TITLE
Run command only after the output file has changed

### ISSUE THREAD

**Issue by shanielh** [hashicorp/consul-template#379]
Many times the rendered template isn't modified after receiving updates from the consul, But `consul-template` runs the command that should run after the configuration change.

I have a suggestion to run the command only if the rendered file is modified from a configuration update.

**Comment by sethvargo** [comment]
@shanielh Consul Template only runs the command if the rendered output has been changed. This check is [right here](https://github.com/hashicorp/consul-template/blob/072af7963c4fac31b336da499ddb18d632ec14f9/runner.go#L527-L529). Are you experiencing different behavior? Can you please share your template and the version of CT you are running.

**Comment by shanielh** [comment]
No. I'm sorry. Consul was updating service status to "fail" and "success" really fast so I couldn't see the updates. You can close this issue. Thanks. 



—

שני.
