### ISSUE TITLE
Change default `max-stale` from 0 to 1s

### ISSUE THREAD

**Issue by armon** [hashicorp/consul-template#386]
Currently we default the `max-stale` to 0, meaning stale reads are not allowed. We should instead use "1s" which enables stale reads with a very small time bound. In practice, Consul followers are only milliseconds behind the leader, but without stale reads all the read pressure falls to the leader which imposes scalability problems at scale. Moving to default stale reads will spread load and reduce performance impacts without appreciably affecting the latency of updates.

**Comment by tgwizard** [comment]
:+1: We had issues in our 70+ node cluster where we use consul-template extensively. Most of these issues seems to have gone away when we changed `max-stale` to 1s. Much fewer leader transitions now:

<img width="1375" alt="screenshot 2015-09-04 09 35 00" src="https://cloud.githubusercontent.com/assets/660706/9678693/4289b746-52e8-11e5-9395-17d9bc767bee.png">

**Comment by MrMMorris** [comment]
@tgwizard what are you using for consul metrics? I wish the Prometheus exporter had Consul Raft Elect Self Count :)

**Comment by tgwizard** [comment]
@MrMMorris we're using the standard consul statsd metrics + [Datadog](https://www.datadoghq.com/).

This is the graph definition:

```json
{
  "viz": "timeseries",
  "requests": [
    {
      "q": "sum:consul.raft.candidate.electSelf.count{*} by {host}.as_count()",
      "style": {
        "palette": "cool"
      },
      "type": "bars",
      "conditional_formats": []
    }
  ]
}
```
