### ISSUE TITLE
creating temp slice in template

### ISSUE THREAD

**Issue by arthurtsang** [hashicorp/consul-template#387]
hi there,

i'm writing a  nginx template to proxy all services from consul.  
https://github.com/arthurtsang/consul-nginx/blob/master/nginx.conf.ctmpl

so i have ```range services``` to build all the upstream section and inside the server section, i need to loop again for the locations.  however, if a service is being deregister right between calling ```range services``` and ```range service .Name```, it could end up empty.  I've added ``if service .Name``` to remove the unwanted upstream, however, how can i remove the corresponding location section?

can i create a slice during the ```range services``` loop and store only the names of those ```if service .Name``` returns true?  how can i do that?

Thanks,
--arthur

**Comment by sethvargo** [comment]
Hi @arthurtsang 

Thank you for opening an issue. It's unclear - are you experiencing problems or expecting potential problems? Consul Template will not change dependencies during rendering. While the template is being rendered, the data is copied and frozen. This means it is not possible to have race conditions between each evaluation of the template.

You should be able to use the same `{{ if service .Name }}` in the location block, but you'll need to left-align with the margin to avoid extra whitespace. 

Go's templating language does not permit us to "map" or "reduce" values, so you cannot build up a map of services and then reduce them.

If you explain the issue you are experiencing a bit more, I would be happy to provide other recommendations for you to structure your template. Thanks!

**Comment by arthurtsang** [comment]
Hi @sethvargo,

Thanks for the quick response.  So, if i call ```{{if service .Name}}``` again, it won't cause consul-template to call consul again?  if so, this will work.  What I was trying to do is to avoid having a location section without a corresponding upstream section or vice versa.  

thanks,
--arthur

**Comment by sethvargo** [comment]
Hi @arthurtsang 

It will only watch Consul once for that endpoint, and the data will be the same for the rendering of that template.

**Comment by arthurtsang** [comment]
awesome.  thanks.
