### ISSUE TITLE
consul-template does not regenerate from template when a Vault setting changes

### ISSUE THREAD

**Issue by wwalker** [hashicorp/consul-template#390]
If I change a Consul KV value changes, consul-template regenerates the file from the template using the new data.

If a Vault value changes, consul-template does nothing.
 
After changing a vault value, when consul-template regenerates due to the changed Consul KV value, the Vault value is empty.

**Comment by wwalker** [comment]
https://gist.github.com/76eee191fe8f40eade2e - template etc.

**Comment by sethvargo** [comment]
Hi @wwalker 

This is the intended behavior. Vault does not support edge triggering like Consul (there is no long-polling endpoint), and that is somewhat outside the scope of Vault. The recommended pattern for acquiring and renewing secrets with Vault is as follows:

- Attempt a read
- Store
- Queue a background job to renew at lease_duration / 2.0

Then, the background job looks like this:

- Attempt a renew
- If renew fails, attempt a read
- If read fails, error
- If read succeeds, update data
- If renew succeeds, update data

Can you elaborate more on:

> After changing a vault value, when consul-template regenerates due to the changed Consul KV value, the Vault value is empty.

That should not be happening. Once CT has stored data from Vault, it should remain stored until the secret expires.

**Comment by wwalker** [comment]
Everything I know right now is in that Gist.  
I created a template and started consul-template as a daemon.
The file was immediately created, correctly.
I change the Vault value, nothing happened.
I changed a KV value, the file was regenerated, with the Vault value missing.

Vault has the new value and the token consul-template is running with can read it.

**Comment by sethvargo** [comment]
Hi @wwalker 

Can you please run CT in debug mode and gist the output?

**Comment by wwalker** [comment]
Just now, I removed the target file, stopped consul-template, and restarted it, and it generated the file with correct data.

But just changing the Vault data and KV data didn't result in another file regenerated with bad data.

**Comment by wwalker** [comment]
I'll switch it to debug and attempt to reproduce.

**Comment by wwalker** [comment]
If I can reproduce, I will open a separate ticket on the <no value>.

**Comment by wwalker** [comment]
On using CT to keep config files up to date with changes, does CT currently do the lease check?  So I can make the lease on the items shorter and they will get update after half the lease has expired?  Or is that the pattern that will exist when it gets implemented?

**Comment by wwalker** [comment]
Ah, I see now.
I once typoed value as vaule. 
Didn't catch it, restarted consul-template to test the command= feature.
So it captured the currently blank value of "value" which was accurate, I just didn't take into effect that it would not get the corrected value.

Thus the <no value> is solved.

**Comment by wwalker** [comment]
I also see that the lease retry stuff is implemented.

Closing out this one.  Thank you Seth.
