### ISSUE TITLE
Question: Get specific index in range?

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/consul-template#391]
Hello,

I'm trying to get one Address:Port for a single instance in a service. Specifically, Consul service:port to feed into a templatized Prometheus config file.

I have five Consul servers all registered in Consul, however, I'm not sure how to "templatize" grabbing just a single Address:Port?

Looking through the configs, it looks like i should be able to do:
```
{{ (service "consul" 0) | .Address }}
```
That however, returns 
```
template: template: prometheus-template.go:18:34: executing "prometheus-template.go" at <0>: expected string; found 0time="2015-09-08T20:25:24Z"
```

I also tried looking at the object with a `{{ service "consul" | toYAML }}`, but that returns:
```
template: template: prometheus-template.go:18:36: executing "prometheus-template.go" at <toYAML>: wrong type for value; expected map[string]interface {}; got []*dependency.HealthServicetime="2015-09-08T20:29:04Z"
```

Any idea why I keep getting a timestamp?

If i were to do:
```
{{ range service "consul }}{{.Address}}:{{.Port}}
{{end}}
```

That correctly spits out all the Address and Ports of my consul service, but i only need one of them!

Suggestions?

**Comment by sethvargo** [comment]
Hi @djenriquez 

I think you will need to use the `index` function that is built into Go's template language as well as a conditional to insure the data is a specific length. Something like:

```go
{{ range  $i, $s := service "consul" }}
{{ if eq $i 0 }}
{{.Address}}:{{.Port}}
{{ end }}
```

* Just psudo-code and not tested

Does that help?

**Comment by djenriquez** [comment]
Hi @sethvargo, that worked!

...well sort of.

You missed the last `{{ end }}` =P

Useless!! (massive sarcasm, thank you very much)

**Comment by sethvargo** [comment]
No problem
