### ISSUE TITLE
saneViewLimit

### ISSUE THREAD

**Issue by wwalker** [hashicorp/consul-template#392]
If one exceeds the ```saneViewLimit```, the warning says:

    2015/09/09 17:45:42 [WARN] (runner) watching 129 dependencies - watching this many dependencies could DDoS your consul cluster.

In my case, this makes 97 connections to the local consul agent.  Quite the number.

Yet while those connections stay open and are apparently blocked HTTP requests, there are no connection from that machine to any of the 3 servers in this consul cluster.  My assumption would be, that for each of the 97 connections from consul-template, the local consul agent registered a call back request with a cluster server.

Am I mistaken?

If not, I ask what to look for to make certain that I do not DDoS the Consul Cluster.  Is it that there will be hundreds (thousands) of callbacks registered on a queue in the cluster?  What resource will be significantly consumed enough to DDoS the cluster?  Or is that only a significant problem if I am running a cluster without local agents?

**Comment by sethvargo** [comment]
Hi @wwalker 

It looks like you might have an N+1 query. The most common cause is something like this:

```
{{range services}}
{{range service .Name}}
# ...
{{end}}
{{end}}
```

Which will create one watch on all services in the catalog and another watch for _each_ service in the catalog. Hence N+1. 

The local consul agent makes a very small number of HTTP requests to the Consul server, but then it multiplexes all the watches over that single connection. Each watch is a blocking query that consumes resources on the cluster (memory and cpu). 

You can think of each watch as an HTTP call to the Consul server that runs every few seconds.

I hope that answers your question. I would be happy to explain in more detail.
