### ISSUE TITLE
v0.10.0 Not properly using https when SSL switch is included

### ISSUE THREAD

**Issue by ericchapman** [hashicorp/consul-template#395]
Hi all,

I am trying to connect to my TLS enabled consul server using v0.10.0.  Here is my runit script

```
#!/bin/sh

exec consul-template \
  -consul=consul:8501 \
  -ssl \
  -ssl-verify \
  -ssl-cert /path/to/certs/cert.pem \
  -ssl-ca-cert /path/to/certs/ca.pem \
  -template "$CT_FILE:$NGINX_FILE:cat $NGINX_FILE; /usr/sbin/nginx -s reload"; 
```

When I do this I get the following error in my logfile

```
[ERR] (view) "service(<service>)" health services: error fetching: Get http://consul:8501/v1/health/service/<service>?passing=1&tag=<tag>&wait=60000ms: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

Notice it is trying HTTP.  I tried backing off to version 0.9.0 and there I get the following error (same command line)

```
runner: crypto/tls: failed to parse key PEM dataConsul Template returned errors:
```

I am positive these certificates are good.  They are the same ones I am using in Consul and NGINX and they work when I include them with curl --key <key> --cert <cert>

Any idea?

**Comment by sethvargo** [comment]
@ericchapman what happens if you specity `-consul=https://consul:8501`?

**Comment by ericchapman** [comment]
@sethvargo 

[ERR] (view) "service(<service>)" health services: error fetching: Get http://https://consul:8501/v1/health/service/<service>?passing=1&tag=<vault>&wait=60000ms: dial tcp: too many colons in address https://consul:8501

Looks like it just appended it to the http

**Comment by sethvargo** [comment]
Doh - this was fixed in https://github.com/hashicorp/consul-template/commit/20dc99c69f6dfc5a7481321c9f7668a8ecc11074, which has not been released yet. The workaround in 0.9+ is to use a config file instead. Sorry about that!

**Comment by ericchapman** [comment]
@sethvargo No problem.  Thanks for your help
