### ISSUE TITLE
get list of all service ip:port on consul

### ISSUE THREAD

**Issue by seongminwoo** [hashicorp/consul-template#396]
Hello.
I use nginx and consul-template. I need to get all consul service ip:port for nginx proxy.
I read all the consul-template guide. And I found "Multi-phase Execution".
And I wrote like below. But It was not working correctly. 
```
{{range services}}
   upstream {{.Name}} {
   {{range service .Name}}
       server {{.Address}}:{{.Port}}
       {{else}}server 127.0.0.1:65535;
   {{end}}
   }
{{end}}
```

after consul-template rendering.
maybe "{{range service .Name}} function is not working. all the ip:port is same fallback address.
```
upstream consul {                 
		  least_conn;                            
		server 127.0.0.1:65535; 
				} 
upstream consul-53 {                 
		  least_conn;                            
		server 127.0.0.1:65535; 
				} 
upstream consul-8500 {                 
		  least_conn;                            
		server 127.0.0.1:65535; 
				} 
upstream drcon2-80 {                 
		  least_conn;                            
		server 127.0.0.1:65535; 
				} 
upstream redis {                 
		  least_conn;                            
		server 127.0.0.1:65535; 
				} 
upstream simple {                 
		  least_conn;                            
		server 127.0.0.1:65535; 
				} 
```

consul service catalog
```
$ curl -XGET $DOCKER_IP:8500/v1/catalog/services
{"consul":[],"consul-53":["udp"],"consul-8500":[],"drcon2-80":[],"redis":[],"simple":[]}
```

Can anyone please help me.

**Comment by sethvargo** [comment]
Hi @seongminwoo 

What happens when you query the health service for consul, drcon2-80, etc?

**Comment by seongminwoo** [comment]
Hi @sethvargo.
Thanks for your interest.

drcon2-80 health check result is below.
```
$ curl -XGET $DOCKER_IP:8500/v1/health/service/drcon2-80
[{"Node":{"Node":"node","Address":"192.168.99.100"},"Service":{"ID":"default:hopeful_varahamihira:80","Service":"drcon2-80","Tags":null,"Address":"127.0.0.1","Port":80},"Checks":[{"Node":"node","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":""}]}]
```

**Comment by sethvargo** [comment]
@seongminwoo how are these services registered in Consul?

**Comment by seongminwoo** [comment]
All services are registered automatically by Registrator component.
I followed this guide.
https://www.airpair.com/scalable-architecture-with-docker-consul-and-nginx

**Comment by sethvargo** [comment]
Hi @seongminwoo 

This is rather strange. Could you please tell me what version of Consul Template you are running and also gist the output of running CT in debug mode please?

**Comment by seongminwoo** [comment]
@sethvargo 
https://github.com/grahamjenson/DR-CoN/blob/master/Dockerfile
DR-CoN Dockerfile use consul template binary version is 0.5.1
```
#Link to Consul Template Binary
ENV CT_URL http://bit.ly/15uhv24
```
I was inspired by your comment. I replace the consul template binary download url for version 0.10.0.
And finally It succeeded!!! Thank you very much!
