### ISSUE TITLE
Question: Loop break

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/consul-template#398]
Is there a way to break out of a loop?

I'm currently looping through a service and only looking for service instances that have a particular set of tags. Once I find one that satisfies the tag requirements, I'm needing to break out of the loop.

Any suggestions on how to break in this scenario?

**Comment by sethvargo** [comment]
Hi @djenriquez 

There is no way to "break" out of a loop because all the resources have been loaded at that point. Go's templating language is a bit limiting here, but it's relatively quick to just surround the entire thing with a loop. Sorry about that!

Please let met know if I can help clarify any more. If you share a template, I can provide a more detailed answer.

**Comment by djenriquez** [comment]
Heres a sample directly from our NGINX config.

What it does is kind of cheesy: if you look at the server line, it adds a # at the end so that all looped entries are basically commented out. But, it would be nicer to figure out a way to ignore them completely.

I have a service which shares its name with every environment (dev,test,staging,prod), but i need it to process values based on the tags for the service that belong to each respective environment.

I though the `{{ if ... }}` statement at the top handles it, but its in the scope of the entire service, so it fails at some checks for environment.

Any ideas?

```
{{range services}}{{if and (.Tags.Contains "lbc") (.Tags.Contains $app_env)}}
{{ range service .Name }}{{ if .Tags.Contains $app_env }}
server {
  listen        80;
  server_name {{ range service .Name }}{{if .Tags.Contains $app_env}}{{.Name}}.{{if eq $app_env "comm"}}{{$aws_region}}.{{else}}{{$app_env}}.{{end}}test.com {{ if .Tags.Contains "domains" }}{{ key (print $app_env "/" .Name "/domains" ) }}{{end}};#{{end}}{{end}}
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    {{ if .Tags.Contains "ab"}}proxy_pass http://${{ .Name | replaceAll "-" "_"}}_upstream_variant;
    {{ else }}proxy_pass  http://{{.Name}}/;{{ end }}
  }
}
{{end}}{{end}}
```

**Comment by djenriquez** [comment]
Or maybe...is there a way to filter services instances? If there is, I could use indices to get the first instance.. something like

```
{{ range $i, $s := service .Name | .Tags.Contains "dev" }}
{{ if eq $i 0 }}
{{ s.Name }}
{{ end }}
{{ end }}
```

**Comment by sethvargo** [comment]
Hi @djenriquez 

That's kinda close - you need to do something like this:

```liquid
{{ $name := printf "dev.%s" .Name }}
{{ range $i, $s := service $name }}
{{ if eq $q 0 }}
{{ $s.Name }}
{{ end }}
{{ end }}
```

You can't pipe a filter to a range function like that, but you can interpolate the service search with a tag: https://github.com/hashicorp/consul-template#service.

Does that answer your question?

**Comment by djenriquez** [comment]
This will do! Thanks.

**Comment by ezraroi** [comment]
is there a way to get exactly one healthy instance of a service from all the data centers?

**Comment by bofm** [comment]
@ezraroi

For range $i, $svc := service ... |passing
If $i == 0
    That is the one

**Comment by ezraroi** [comment]
Thanks @bofm, but this is the current DC... we need from all DCs as the service that we configure might not bed in the same DC as the healthy instance we are looking for
