### ISSUE TITLE
#297 not working properly

### ISSUE THREAD

**Issue by zeldal** [hashicorp/consul-template#401]
Currently #297  usage throws

> wrong type for value; expected int; got int64.

on loops, since parseInt return int64, i am not go expert any trick to do this?

**Comment by sethvargo** [comment]
Hi @zeldal 

Can you please share your template? Here is the commit where that was added and you can see it is an int64: https://github.com/hashicorp/consul-template/commit/44fce54dcde3b6070585677c2f966701a510d2dd#diff-2a6a9c31468754a4fdc2862ccc0513cd

**Comment by zeldal** [comment]
well, loop function expects primitive int,
>func loop(ints ...int) (<-chan int, error) {

 but parseInt returns int64. and loop throws exception. i added atoi function:

>func atoi(s string) (int, error) {
	if s == "" {
		return 0, nil
	}
	result, err := strconv.Atoi(s)
	if err != nil {
		return 0, fmt.Errorf("Atoi: %s", err)
	}
	return result, nil
}

but cant merge atm, u may add now or i will fork and create pull request later if u wish.

**Comment by sethvargo** [comment]
Hi @zeldal 

I am not following. I don't understand how atoi is going to solve the problem that loop only takes an int. I think it should take an int64 instead probably.
