### ISSUE TITLE
Is it possible to template multiple files without knowing their names in advance?

### ISSUE THREAD

**Issue by onnimonni** [hashicorp/consul-template#404]
**TL;DR: Is it possible populate contents of multiple files from certain KV path using consul-template?**

I would like to store multiple ssl-certificates in consul backend (filename and content) and distribute them through cluster using consul-template.

I figured out that I can make create a bash script in cron which polls for them in consul http api and creates them. But it's much slower than using consul-template and in our architecture some consul-templates require those ssl-certificates to be in place before they are created.

**Comment by sethvargo** [comment]
Hi @onnimonni 

That is not the job of Consul Template. There is another open source project that does that though: https://github.com/Cimpress-MCP/fsconsul.

**Comment by onnimonni** [comment]
Thanks man!
