### ISSUE TITLE
commands fail to run for some random templates

### ISSUE THREAD

**Issue by wwalker** [hashicorp/consul-template#405]
I have a config with 30 templates, all essentially identical:

(with shortened paths for readability) they all look like this:

    template {
      source = "/templates/bugsy-alpha/product_group_auto.properties"
      destination = "/temp_render/bugsy-alpha/product_group_auto.properties"
      command = "/usr/bin/sudo /bin/fix_file_perms bugsy-alpha product_group_auto.properties"
    }
    template {
      source = "/templates/bugsy-bravo/product_group_auto.properties"
      destination = "/temp_render/bugsy-bravo/product_group_auto.properties"
      command = "/usr/bin/sudo /bin/fix_file_perms bugsy-bravo product_group_auto.properties"
    }
    template {
      source = "/templates/bugsy-charlie/product_group_auto.properties"
      destination = "/temp_render/bugsy-charlie/product_group_auto.properties"
      command = "/usr/bin/sudo /bin/fix_file_perms bugsy-charlie product_group_auto.properties"
    }

I'm running this:

consul-template --once --config /path-to/config_dir --log-level=debug

It generates All 30 target files, but it randoms fails to run the command for about 25% of the targets.

On one run it failed to run the command for bugsy-bravo and bugsy-charlie, on the next run , it failed only for charlie (out of alpha, bravo, charlie).

In the debug output I notice that, although the "command" parameter is in the "final config", these lines do not appear for the ones which don't run:

From the final config:

2015/09/16 12:50:31 [DEBUG] (runner) final config (tokens suppressed):

    {
    ....
      "templates": [
        {
          "source": "/var/local/hector/conf/consul-template/templates/bugsy-alpha/product_group_auto.properties",
          "destination": "/var/local/consul-template/conf/temp_render/bugsy-alpha/product_group_auto.properties",
          "command": "/usr/bin/sudo /var/local/hector/lib/bin/fix_file_perms bugsy-alpha product_group_auto.properties"
        },
        {
          "source": "/var/local/hector/conf/consul-template/templates/bugsy-bravo/product_group_auto.properties",
          "destination": "/var/local/consul-template/conf/temp_render/bugsy-bravo/product_group_auto.properties",
          "command": "/usr/bin/sudo /var/local/hector/lib/bin/fix_file_perms bugsy-bravo product_group_auto.properties"
        },
        {
          "source": "/var/local/hector/conf/consul-template/templates/bugsy-charlie/product_group_auto.properties",
          "destination": "/var/local/consul-template/conf/temp_render/bugsy-charlie/product_group_auto.properties",
          "command": "/usr/bin/sudo /var/local/hector/lib/bin/fix_file_perms bugsy-charlie product_group_auto.properties"
        },
      ]
    ....

alpha registers and runs:

    2015/09/16 13:11:47 [DEBUG] (runner) appending command: /usr/bin/sudo /var/local/hector/lib/bin/fix_file_perms bugsy-alpha product_group_auto.properties
    2015/09/16 13:11:50 [DEBUG] (runner) running command: `/usr/bin/sudo /var/local/hector/lib/bin/fix_file_perms bugsy-alpha product_group_auto.properties`
  
but no lines for bravo :-(
  
And they appear identical.

**Comment by wwalker** [comment]
Running v0.10.0

**Comment by wwalker** [comment]
The same behavior exists in daemon mode.

**Comment by sethvargo** [comment]
Hi @wwalker 

Consul Template will only run the command if the file has been changed. Can you check that those files do not already exist?

**Comment by wwalker** [comment]
Thank you.

OK, that was it; trusting the existing files to be "up to date" wasn't an assumption I expected.
