### ISSUE TITLE
consul-template doesn't reliably render missing output files on SIGHUP

### ISSUE THREAD

**Issue by jdelic** [hashicorp/consul-template#408]
We use `consul-template` to render configuration files for `haproxy` through an intermediary script. We also use [Salt](https://github.com/saltstack/salt) for configuration management.

The setup works like this:
  * `consul-template` is run via systemd with this command-line.

      ```
consul-template -config /etc/consul/consul-template.conf -config /etc/consul/template.d

# consul-template.conf
consul = "127.0.0.1:8500"
retry = "10s"
max_stale = "10m"
log_level = "warn"
pid_file = "/run/consul/consul-template.pid"
```

    Expected outcome: Consul loads the first config file and all files from `template.d`.

  * A "watcher state" in Salt monitors the rest of the configuration management system when it runs and when any state drops a new configuration file in `/etc/consul/template.d` it automatically sends a SIGHUP to `consul-template`. We know this works because `consul-template` sends lines like `Sep 19 11:56:59 test consul-template[569]: Received HUP, reloading configuration...` to syslog.

  * A typical template configuration file in `template.d` looks like this:
    ```
# /etc/consul/template.d/haproxy-internal.conf
template {
        source = "/etc/consul/servicerenderer.ctmpl.py"
        destination = "/etc/consul/renders/smartstack-internal.py"
        command = "/usr/bin/python /etc/consul/renders/smartstack-internal.py -o /etc/haproxy/haproxy-internal.cfg -c \"systemctl reload haproxy@internal\" --has smartstack:internal /etc/haproxy/haproxy.jinja.cfg"
}
```

**Expected behavior:** If we send a SIGHUP to `consul-template` it should load `consul-template.conf` and all configuration files from `/etc/consul/template.d` then check whether all `destination` files exist and render them if necessary, then execute any `command`s.

**Actual behavior:** `consul-template` acknowledges the SIGHUP, but then does "nothing". Only restarting `consul-template` achieves the desired effect of it loading the new configuration files in `template.d` and rendering their output.

If this is actually expected behavior, that's fine. In any case, whether this is a bug or not, I think that the `consul-template` documentation could definitely use sections on signals and when consul-template will check whether a *destination* exists and render it if necessary. Thanks :)

**Comment by omribahumi** [comment]
I need this as well +1 :)

**Comment by sethvargo** [comment]
Hi @jdelic 

Thank you for reporting. Upon further investigation, this has been fixed in https://github.com/hashicorp/consul-template/commit/ce870dde2cd4aa14f6eddce6e14b0c4f25ba39a7 and will be part of the next release (today or tomorrow). Thanks! :smile:
