### ISSUE TITLE
Unable to read key or fodler including '@'

### ISSUE THREAD

**Issue by itheiss** [hashicorp/consul-template#411]
Hi!

I am able to create a key or folder including a '@' over the consul ui, but when reading the key I get an exception:

```2015/09/25 09:24:39 [ERR] (view) "key(test/accounts/test@example.com)" store key: error fetching: Unexpected response code: 500```

Either this is an issue regarding the web ui allowing all kind of chars or an error from consul-template...

Regards
Ingo

**Comment by sethvargo** [comment]
Hi @itheiss 

The "@" key is a reserved key. It dictates which data center you would like to query from. Unfortunately this is a hard requirement, so you will need to refactor your key names a bit. Please also note that dots (`.`) are also a reserved keyword and using dots in a name is highly discouraged by both CT and Consul. :smile:
