### ISSUE TITLE
How to get node address of service

### ISSUE THREAD

**Issue by shotai** [hashicorp/consul-template#413]
My node address is not same with the ServiceAddress, and I need to use Node Address to visit the service.  
However, the {{.Address}} is not working. 
How to use node address instead of ServiceAddress?

consul template file:

```
upstream app {                 
  ip_hash;                            
  {{range service "test"}}         
  server  {{.Address}}:{{.Port}};        
  {{else}}server 127.0.0.1:65535;{{end}} 
}  

```

Consul service:

http://192.168.0.100:8500/v1/catalog/service/test?pretty
```
[
    {
        "Node": "machine1",
        "Address": "192.168.0.100",
        "ServiceID": "test:1",
        "ServiceName": "test",
        "ServiceTags": null,
        "ServiceAddress": "172.17.0.61",
        "ServicePort": 3000
    }
]
```

The created nginx config:
```
upstream app {                 
  ip_hash;                            
           
  server  172.17.0.61:3000;        
   
}
```

consul-template version:
```
consul-template v0.10.0
```

**Comment by sethvargo** [comment]
I think you want [`.NodeAddress`](https://github.com/hashicorp/consul-template/blob/c8ac674856d0671645685cc2f50c78ddec5dff4f/dependency/health_service.go#L27).

**Comment by shotai** [comment]
That works! Thanks!
