### ISSUE TITLE
Allow specification of a configuration directory

### ISSUE THREAD

**Issue by leprechau** [hashicorp/consul-template#420]
Allow specification of a configuration directory in the style of /etc/consul-tempalte.d/ where multiple template definitions could be specified as individual files.

**Comment by sethvargo** [comment]
This is already possible with the `-config` option. Multiple `template` blocks are merged. Are you experiencing something different?

> The path to a configuration file or directory of configuration files on disk, relative to the current working directory. Values specified on the CLI take precedence over values specified in the configuration file. There is no default value.

**Comment by leprechau** [comment]
Sorry, you're absolutely right.  That does work as expected.  Apology for missing that in the documentation.
