### ISSUE TITLE
syslog to remote server

### ISSUE THREAD

**Issue by sebest** [hashicorp/consul-template#421]
Hello,

Is it possible to log to a remote syslog server udp/tcp?

It would be really useful when using consul-template in Docker where you don't have any local syslog.

thanx

**Comment by sethvargo** [comment]
HI Sebest,

Thank you for opening an issue. It is not possible to configure a remote syslog server, and that seems a bit out of scope for Consul Template's responsibilities :smile:.

I think the recommended pattern here is to log to the container, and then have the container log to a rsyslog or similar: https://docs.docker.com/reference/logging/overview/

**Comment by sebest** [comment]
that's what i'm currently doing but you loose informations like the severity.

**Comment by sethvargo** [comment]
@sebest I personally do not know enough about syslog to implement this, and it has not been a widely requested feature up to this point (CT is almost a year old now :smile:). I think this is something we would look to a community contribution for :wink:.

I am going to close this issue, but I would gladly review a PR that implements this functionality. Have a great day! :smile:
