### ISSUE TITLE
Building v0.11.0 with go1.4.2 fails without finding the vault api

### ISSUE THREAD

**Issue by ch-acctg** [hashicorp/consul-template#424]
Our Jenkins output shows go isn't retrieving the vault api:

+ git clone https://github.com/hashicorp/consul-template.git /var/lib/jenkins/workspace/consul/label/squeeze/go-pkg/src/github.com/hashicorp/consul-template
Cloning into /var/lib/jenkins/workspace/consul/label/squeeze/go-pkg/src/github.com/hashicorp/consul-template...
warning: unable to read /etc/mailname: Permission denied

+ cd /var/lib/jenkins/workspace/consul/label/squeeze/go-pkg/src/github.com/hashicorp/consul-template
+ git checkout v0.11.0
warning: unable to read /etc/mailname: Permission denied

Note: checking out 'v0.11.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 5744f25... Release v0.11.0
+ make
find . -type f -name '.DS_Store' -delete
go generate ./...
go test ./...  -timeout=30s -parallel=4
dependency/client_set.go:8:2: cannot find package "github.com/hashicorp/vault/api" in any of:
	/var/lib/jenkins/workspace/consul/label/squeeze/go/src/github.com/hashicorp/vault/api (from $GOROOT)
	/var/lib/jenkins/workspace/consul/label/squeeze/go-pkg/src/github.com/hashicorp/vault/api (from $GOPATH)
template_functions.go:16:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/var/lib/jenkins/workspace/consul/label/squeeze/go/src/gopkg.in/yaml.v2 (from $GOROOT)
	/var/lib/jenkins/workspace/consul/label/squeeze/go-pkg/src/gopkg.in/yaml.v2 (from $GOPATH)
make: *** [test] Error 1
Build step 'Execute shell' marked build as failure

**Comment by sethvargo** [comment]
@ch-acctg you need to run `make updatedeps` before running `make` or `make test`: https://github.com/hashicorp/consul-template#contributing. Additionally, the new version of CT is compiled using go 1.5.1, so you should compile using that if possible.
