### ISSUE TITLE
Support for multiple Vault addresses and/or for getting Vault Address from Consul Catalog

### ISSUE THREAD

**Issue by wwalker** [hashicorp/consul-template#425]
I have a cluster of 3 vault servers, but I can only tell consul-template about one.

We could :

* Add support for reading the addresses from catalog and try them all in newVaultClient() until they have all failed, or one succeeds.

* Add VAULT_ADDRS which would be a semi-colon separated list of URLs

**Comment by sethvargo** [comment]
Hi @wwalker 

You have three _separate_ Vault clusters or three servers in the same cluster? In the cluster, all requests are forwarded to the leader, so there's no point in having the client do a round-robin. You can read here for more information: https://github.com/hashicorp/vault-ruby/issues/44

**Comment by wwalker** [comment]
I have a single cluster, it was a leader and two standbys, but one standby had to be rebooted.

During the reboot, and up until 3 shares of the master key were entered, that address was unavailable. Therefore, all consul-template actions can fail when only 1 of the 3 member cluster is unavailable.

**Comment by wwalker** [comment]
To clarify, even when it is up, yet still sealed, the vault server does not forward.  It only returns a sealed message.

**Comment by sethvargo** [comment]
@wwalker your leader and all followers need to be unsealed (even when they are standby). They cannot take leadership if they are not unsealed.

To put it another way, all the leaders and followers need to be unsealed :smile:

**Comment by wwalker** [comment]
@sethvargo I'm mis-communicating I think.

I'm talking about having a vault cluster of 3 hosts: v1, v2, and v3.   All three are up and unsealed.  So I start consul-template with VAULT_ADDR (or vault{address:  ) set to v1.  All is well.

Unexpectedly, v1 reboots or vault crashes.  Until one of the following occurs, consul-template will crash and fail to restart:

* change the value (on hundreds of hosts) of VAULT_ADDR (or vault{address:  )) to v2 or v3 (which are up and happy) and restart consul-template
* v1 finishes rebooting and we get the people together with the key shares to unseal v1.

**Comment by sethvargo** [comment]
@wwalker correct. As I said on the linked ticket, I do not think it is a client library's responsibility to support HA. Instead, that should be done at the infrastructure layer by putting the vault instances behind some kind of load balancer with a health check. Then you query the load balancer endpoint instead of a vault instance directly.
