### ISSUE TITLE
consul-template is not reaping children in container

### ISSUE THREAD

**Issue by mvanholsteijn** [hashicorp/consul-template#428]
We are running consul-template as a simple wrapper around HAproxy. Whenever the configuration changes, we perform a soft restart of haproxy. However, the exited HAProxy processes are not reaped and left as zombie processes.

Would you consider having  consul-template  take the PID 1 responsibility and handle the SIGCHLD events? Otherwise we would need to  complicate the container with an init system.

Cheers,

Mark

**Comment by sethvargo** [comment]
Cross-linking with https://github.com/hashicorp/consul/issues/1183. @slackpad is going to take this. Thanks!

**Comment by mvanholsteijn** [comment]
Hi Seth, consul-template is running inside a container without a consul agent, so I do not see who the consul agent can assume the role as PID 1....

**Comment by sethvargo** [comment]
Hi @mvanholsteijn 

It won't. James is going to work on both tickets at the same time.
