### ISSUE TITLE
Looking for the loop of string values or array handler

### ISSUE THREAD

**Issue by mrh666** [hashicorp/consul-template#429]
Hi there,

I need an advise it if's even possible. I need to generate list of IP addresses in following format (for Graphite cluster relay destinations):
ip1:2004:a, ip1:2104:b, ip1:2204:c, ip1:2304:d, ip2:2004:a, ip2:2104:b, ip3:2204:c, ip4:2304:d

I successfully get a list of IP without trailing letter by:

```
{{range $index, $node := service "graphitecarbon"}}{{range $i := loop 0 4}}{{if or (ne $index 0) (ne $i 0)}}, {{end}}{{$node.Address}}:2{{$i}}04{{end}}{{end}}
```

But I don't a have a clue how to loop a letters. Or handle an array like a,b,c,d from which I can get an index (0,1,2,3) and values (a,b,c,d) if it's possible.

Please advice or point me to some doc!

Thank you.

**Comment by sethvargo** [comment]
Hi @mrh666 

You can range over any iterable type (like arrays or maps). I do not fully understand your question, but it's very possible that Go's templating language makes this impossible. There is no way to "map" or "reduce" values in a Go template. I don't understand the syntax you are trying to create or how that data is mapped to data in Consul

Consul Template includes some helpers to make working with Go templates easier, but I do not think it is possible to do the operation you desire with Go's templates.

**Comment by mrh666** [comment]
sethvargo, good thing your answer just gave me the reason to read the documentation again and again... :)
Until I figured out the way to get a list formatted as I want to using split. Now I have my Graphite cluster working (two relays and two cache instances) based on discovery by consul template.
This is desired output for carbon.conf relays DESTINATIONS:

```
172.31.14.247:2004:a, 172.31.14.247:2104:b, 172.31.14.247:2204:c, 172.31.14.247:2304:d, 172.31.15.36:2004:a, 172.31.15.36:2104:b, 172.31.15.36:2204:c, 172.31.15.36:2304:d
```

And this is the code I wrote to get it:

```
{{range $index, $node := service "graphitecarbon"}}{{range $indexarray, $i := "a b c d" | split " "}}{{if or (ne $index 0) (ne $indexarray 0)}}, {{end}}{{$node.Address}}:2{{$indexarray}}04:{{$i}}{{end}}{{end}}
```
