### ISSUE TITLE
Subtract not working

### ISSUE THREAD

**Issue by brokenhowl** [hashicorp/consul-template#430]
so im trying the new Arithmetic functions and for some reason subtract is always returning 0 

Here is some test example 

```
{{add 1 1 }}
{{subtract 2 1}}
{{subtract 1 2 }}
{{2 | subtract 1 }}
```

**Comment by sethvargo** [comment]
Hi @brokenhowl 

Do the other functions work for you? What version of Consul Template are you using? Can you paste the output in debug mode?

**Comment by brokenhowl** [comment]
v0.11.0 

ok i made this quick test:
{{add 1 1 }} 
{{subtract 2 1}}
{{subtract 1 2 }}
{{2 | subtract 1 }}
{{ multiply 2 2 }}
{{ divide 2 10 }}
{{ 10 | divide 2 }}

add and multiply are working fine but ... subtract is always returning 0 and divide is always returning 1

**Comment by sethvargo** [comment]
Weird. Okay thanks for reporting.

**Comment by brokenhowl** [comment]
no biggie thanks for the quick response :) hope this helps

**Comment by sethvargo** [comment]
Hey @brokenhowl 

Actually, none of them were working. It was always using the first element as both arugments to the function :frowning:

**Comment by zonzamas** [comment]
What about a hotfix for this fix ?

**Comment by sethvargo** [comment]
Still debugging https://github.com/hashicorp/consul-template/issues/442, which appears to be a regression. If you'd like to jump in there, I'd appreciate it :smile:
