### ISSUE TITLE
build instructions incomplete

### ISSUE THREAD

**Issue by mvanholsteijn** [hashicorp/consul-template#431]
The local build instructions for consul-template are incomplete. There are a number of dependencies in the build which  are not mentioned (codecgen, ffsjon, msgp).

**Comment by sethvargo** [comment]
Hi @mvanholsteijn 

Did you mean to open this on Consul? None of these are requirements for Consul Template, and the `make updatedeps` function should pull in everything you need. Are you experiencing something different?

**Comment by mvanholsteijn** [comment]
Hi Seth,

No I was opening this on consul-template. The installation instructions in the readme of consul-template states to install:

```bash
$ git clone https://github.com/hashicorp/consul-template.git
$ cd consul-template
$ make
```
This does not work.
