### ISSUE TITLE
I want to add customer field in the configuration file .suggest me a step to add

### ISSUE THREAD

**Issue by satish-zettata** [hashicorp/consul-template#437]

**Comment by sethvargo** [comment]
Hi @satish-zettata 

You can use Consul's KV store to add custom data using the `key` function.

**Comment by satish-zettata** [comment]
hey man ,i want output in such a format that ,if i select a region and in
that i chose a
node i want list of the customers in that node.

tell me in detail how i can add customer field in conf file . when i added
cust field in conf.json file i got an error called Error decoding
'/etc/consul.d/config.json': Config has invalid keys: customer


Thanks & Regards
Satish .P. Chavan

**Comment by sethvargo** [comment]
Hi @satish-zettata 

There is no such thing as a "customer" in Consul or Consul Template.

**Comment by satish-zettata** [comment]
hey man ,

if am executing below template am getting error



global
    daemon
    maxconn {{key "service/haproxy/maxconn"}}

defaults
    mode {{key "service/haproxy/mode"}}{{range ls "service/haproxy/timeouts"}}
    timeout {{.Key}} {{.Value}}{{end}}

listen http-in
    bind *:8000{{range service "release.web"}}
    server {{.Node}} {{.Address}}:{{.Port}}{{end}}






error


2015/10/29 12:19:49 [WARN] ("key(redis/key1)") Consul returned no data
(does the path exist?)


->tell me the solution for this



Thanks & Regards
Satish .P. Chavan
