### ISSUE TITLE
Vault not renewing leases properly

### ISSUE THREAD

**Issue by sean-brandt** [hashicorp/consul-template#443]
It would seem ( unless I'm missing something ) that when vault is enabled the codebase goes into a spammy loop attempting to renew the lease for 5m because it thinks it's 0.

Looking at the code, and I'm by no means anything more than a novice at go it would seem that the vault_token code is checking the wrong fields for lease duration, etc, on client token renewals.

I actually think that a different struct should be used ( not Secret ) as is used on 46-51, but instead a ClientTokenInfo or similar struct.

The actual fields I think that should be being checked are here:

token.Auth.ClientToken,
token.Auth.LeaseDuration,
token.Auth.Renewable,
token.Auth.Metadata

Could be I'm missing something entirely and it's an oddity in my config/vault/consul setup but I don't think so.

**Comment by sethvargo** [comment]
Hi @sean-brandt 

Can you please share your Vault setup and Consul Template template? Is your Vault token renewable?

**Comment by sean-brandt** [comment]
Sure. Though as a side note, I'm testing my changes locally and they do appear to resolve the issue. It would appear that the vault_token.go code, as written, isn't inspecting the 'Auth' field of the returned Token info from Renew, but expecting that data to be at the root level of the object. Tokens/Names below changed to protect the innocent..or some such.

__consul_template_config__
```
consul = "127.0.0.1:8500"
retry = "10s"
max_stale = "5m"
log_level = "info"
token = "DDDDDDDDDD"

vault {
  address = "https://vault.service.consul:8200"
  token = "ABCDEF1234"
  renew = true
  ssl {
    enabled = true
    verify = true
    ca_cert = "/usr/local/vault/ssl/ca.pem"
  }
}
template {
  source = "/etc/rexray/config.yml.ctmpl"
  destination = "/etc/rexray/config.yml"
  perms = 0600
}
```
__vault_token_info___
vault read  auth/token/lookup/ABCDEF1234
```
Key          	Value
creation_time	1.445462252e+09
display_name 	token-Consul-Template
id           	ABCDEF1234
meta         	<nil>
num_uses     	0
path         	auth/token/create
policies     	[consul_template]
ttl          	3600
```

__consul template__
cat /etc/rexray/config.yml.ctmpl 

```
logLevel: info
awsAccessKey: {{with vault "aws/creds/foobar_storage"}}{{.Data.access_key}}{{end}}
awsSecretKey: {{with vault "aws/creds/foobar_storage"}}{{.Data.secret_key}}{{end}}
```

**Comment by sean-brandt** [comment]
That appears to fix the issue - though I wonder if checking Auth.Renewable is advisable as opposed to simply checking the leaseDuration == 0? Might be worth warning about trying to renew non-renewable tokens.
