### ISSUE TITLE
Consul-Template always prints DEBUG messages on startup

### ISSUE THREAD

**Issue by kawikao** [hashicorp/consul-template#445]
Happens when setting a -config argument. Looks like it's the first line in ConfigFromPath(). It would be nice if the log.Printf() honored the log-level. Thanks.

**Comment by sethvargo** [comment]
Hi @kawikao 

What version of Consul Template are you running?

**Comment by kawikao** [comment]
v0.11.0

**Comment by kawikao** [comment]
It looks like it's by design.

321 func ConfigFromPath(path string) (*Config, error) {
322	   log.Printf("[DEBUG] (config) loading configs from %q", path)

**Comment by sethvargo** [comment]
@kawikao it's a bit of a catch-22. We want need to log level from the config, but we need to log where we got the config before we can get the log level. I have an idea though.
