### ISSUE TITLE
Behavior on vault secret update

### ISSUE THREAD

**Issue by frntn** [hashicorp/consul-template#451]
I have a `vault` instance with `consul` as secret backend, and a template containing the following :
```
{{  with vault "secret/foobar" }}
username={{ .Data.username }}
password={{ .Data.password }}
{{ end }}
```

When starting `consul-template`, the generated file contains the expected username and password.

But when I change the key values of that path, no file regeneration is triggered. 
I have to restart consul-template for the new values to appear in the generated file.

**=> Is it the expected behavior of consul-template w/ vault ? (or is it supposed to automatically update like it does w/ consul services for example)**

**Comment by sethvargo** [comment]
Hi @frntn 

Unfortunately Vault does not support blocking queries, so we just long-poll on lease_duration/2. This is the expected behavior until Vault supports blocking queries so we can edge trigger.

**Comment by frntn** [comment]
Ok I'm cool with this behavior. Just needed to be sure.
Thanks.
