### ISSUE TITLE
Have Consul Template run even if a template's source doesn't exist

### ISSUE THREAD

**Issue by harish324** [hashicorp/consul-template#452]
I am using Chef to provision an environment.  I want to start Consul Template upfront because I need it to start up certain services correctly.  The problem is if I start Consul Template toward the beginning of provisioning, all of the source ctmpl files may not exist yet.  When this happens, I get an error like below and Consul Template stops.

```
Consul Template returned errors:
open /home/test3.ctmpl: no such file or directory
```

Is there any way that the log file could show this message but other existing .ctmpl files would still render?  If the missing .ctmpl file is created, I understand I would probably have to restart Consul Template for it to start rendering (I will do this at the end of the Chef run).

I am using version 0.10.0 of Consul Template

**Comment by sethvargo** [comment]
Hi @harish324 

I think the proper behavior is to error if you specify a template that does not exist. I would recommend you use the `delayed` argument as you write out the templates to aggregate the Consul Template service, for example (my Chef might be a little rough):

```ruby
service "consul-template" do
  # ...
  action :nothing
end

template "/home/test3.ctmpl" do
  # ...
  notifies :restart, "service[consul-template]", :delayed
end
```

This will tell the CT process to run at the end of the Chef run. Does that make sense?

**Comment by harish324** [comment]
Thanks for the quick response.

I got some other ways to solve my issue because its kind of complicated.  Just wanted to make sure I wasnt overlooking anything.
