### ISSUE TITLE
allow passing permissions with -template option

### ISSUE THREAD

**Issue by robwdux** [hashicorp/consul-template#453]
v0.11.0

..."Consul Template no longer mirrors existing destination file permissions. Instead, users can specify the file permissions in the configuration file."

currently "-template" -- The input template, output path, and optional command separated by a colon (:). This option is additive and may be specified multiple times for multiple templates.

--proposed--
```
<src>:<dest>:<perms>:<cmd>
```

with <perms> and <cmd> optional

**Comment by sethvargo** [comment]
Hi @robwdux 

We discussed this when implementing the permissions option, and we actively decided against this. The CLI is not descriptive enough to explain _what_ those values are. If you want to specify file permissions, you will need to use a config file. Sorry! :smile:
