### ISSUE TITLE
Read and parse file from template

### ISSUE THREAD

**Issue by alex-pekurovsky** [hashicorp/consul-template#454]
I'm building application in docker, where I'm running CentOS 7 with systemd, consul-agent, consul-template and java application itself. Java application requires property file, which should be built from KV storage.

Path in KV storage depends on environmental variable docker is started with.

For example,
docker run -d -e APP_ENV="US" dockerimage

In template I could write something like:

[Global]
{{$ENV := (print "APP_" (env "APP_ENV"))}}
{{range ls $ENV}}
{{.Key}}={{.Value}}{{end}}

however consul-template service is spawned by systemd with clear environment. The only one way to get APP_ENV variable is to parse /proc/1/environ, so I have two options:

1) Execute shell:
  xargs -n 1 -0 < /proc/1/environ | grep APP_ENV | cut -d"=" -f2
2) Parse environ file with go:
  {{file "/proc/1/environ" | ...

The problem is I can't find how to execute shell from template or how to parse file in go.

**Comment by sethvargo** [comment]
Hi @alex-pekurovsky 

Thank you for opening an issue, and I am sorry you are having difficulties with Consul Template. I'm having trouble following your issue. It sounds like you are trying to run a docker container with certain environment variables which are coming from Consul's KV store.

I would recommend you take a look at [envconsul](https://github.com/hashicorp/envconsul) for this as it's specifically designed for environment variables and subprocesses.

**Comment by alex-pekurovsky** [comment]
Not really what I wanted, but you gave me a great idea how I can solve my issue. I created consul-template-wrapper (bash script), where I'm parsing /proc/1/environ and launching consul-template and replaced systemd consul-template.service with consul-template-wrapper.service

Thank you for idea
