### ISSUE TITLE
Can't use range or ls for keys with spaces

### ISSUE THREAD

**Issue by greggilbert** [hashicorp/consul-template#456]
So using Consul UI, I can add a key that's, say, `Foo Bar/Baz Bat`. When I do this, `{{range ls "Foo Bar"}}` returns: "error calling ls: invalid key prefix dependency format".

Both `range` and `ls` throw that error. Interestingly, `{{range tree "/"}}` will include the value in it.

**Comment by sethvargo** [comment]
Hi @greggilbert 

We do not recommend creating keys with spaces in them, since it can break the underlying queries (as you are seeing). I would recommend using a dash or an underscore instead. 

Ideally the Consul UI should actually prohibit this behavior as well.

**Comment by spellgen** [comment]
Another side of this is services with spaces in them. While you can suggest that they not be used, if you *do* use them an unsuspecting ctmpl definition can crash consul-template.

We just experienced this when a user added a url-encoded service with spaces added as %20. What would be a good way to handle this in consul-template - I'm considering doing a fix but would appreciate some feedback on what would be a good way to handle it.
