### ISSUE TITLE
consul-template spamming logs with 'lease duration is 0, setting to 5m'

### ISSUE THREAD

**Issue by raffraffraff** [hashicorp/consul-template#458]
I created a token with a long TTL. When I renew the token with the vault CLI, I get a valid 'token_duration':
```
        Key                Value
        token              <mytokenid>
        token_duration     2592000
        token_renewable    true
        token_policies     [default,responses]
```
When I use CURL to perform 'auth/token/lookup-self', I get a mixed response:
```
$ curl -kL --tlsv1.2 \
  -H "X-Vault-Token: $TOKEN" \
  -X GET https://vaultserver:8200/v1/auth/token/lookup-self
 {
   "lease_id":"",
   "renewable":false,
   "lease_duration":0,
          "data": {
             "creation_time":1447157350,
             "display_name":"token-responses",
             "id":"<mytokenid>",
             "meta":null,
             "num_uses":0,
             "path":"auth/token/create",
             "policies": [
                "default",
            "responses"
             ],
             "ttl":1700   # old version of vault lease_duration here!
      },
   "auth":null
 } 
```
I have read this issue https://github.com/hashicorp/vault/issues/527, which explains the difference between lease_duration and ttl (although in that issue, it was still lease_duration):

>  what you're actually seeing is a lease structure which optionally contains 
> authentication information. "0" is simply the zero value for the duration type; 
> it is shown because in some cases this literally means "using the default"
> whereas in other cases it just means "not set", and it's a bit context-specific 

But based on the response to my curl command, I think that consul-template's vault_token.go code may be looking at the wrong value:
```
        secret := &Secret{
            LeaseID:       token.LeaseID,
            LeaseDuration: token.Auth.LeaseDuration,
            Renewable:     token.Auth.Renewable,
            Data:          token.Data,
        }

        leaseDuration := secret.LeaseDuration
        if leaseDuration == 0 {
            log.Printf("[WARN] (%s) lease duration is 0, setting to 5m", d.Display())
            leaseDuration = 5 * 60
        }
```

I've just started looking under the hood, and don't have any Go experience. So I'm confused about how the JSON returned from my curl matches up with `secret` in vault_token.go. But shouldn't this go code set LeaseDuration to token.Data.TTL or something like that?

**Comment by sethvargo** [comment]
Hi @raffraffraff 

What version of Consul Template are you using?

**Comment by raffraffraff** [comment]
Hi @sethvargo 

I'm on v0.11.0
I see that v0.11.1 is available - I'll quickly try it.

**Comment by raffraffraff** [comment]
Riiight, silly me. Change log lists the fix:
> Renew the vault token based off of the auth, not the secret [GH-443]

**Comment by sethvargo** [comment]
@raffraffraff please let me know if that fixes your issue

**Comment by raffraffraff** [comment]
OK, so v0.11.1 of consul-template appears to be working with Vault 0.3.1. Thanks.
