### ISSUE TITLE
Complex strings from results of calls

### ISSUE THREAD

**Issue by doubleyou** [hashicorp/consul-template#460]
We can do something like `{{env "SERVICE_NAME" | service}}` to pass a result of one function to another.

However, it doesn't look like we can do something like `{{key "services/"{{env "SERVICE_NAME"}}/config"}}`, can we? I understand that it's a bit too much of a demand from a simple template engine, but never hurts to ask.

**Comment by sethvargo** [comment]
Hi @doubleyou 

Please see the golang text/template documentation. You need to use the `printf` function to construct the string first, before passing it to `key`:

```liquid
{{ $name := env "SERVICE_NAME" | printf "services/%s" }}
{{ key $name }}
```

https://golang.org/pkg/text/template/
