### ISSUE TITLE
Union

### ISSUE THREAD

**Issue by eirslett** [hashicorp/consul-template#462]
I have two data centers. Some applications run on only one of the data centers, some run on both. I want to configure haproxy to load balance traffic between them all.

 I need to make a haproxy template that basically says;
```
for each service in DC 1 + for each service in DC 2:
  - create haproxy backend/virtualhost
  for each instance of this service in DC1 + for each instance of this service in DC 2
  - create server entry
```

The issue is to find the union of all services in DC 1 and DC 2, to construct the outer loop. Is that possible today, with the go template language?

**Comment by eirslett** [comment]
*bump*
Does anybody have a solution to this?

**Comment by sethvargo** [comment]
Hi @eirslett 

We define a data center as a high-bandwidth, low-latency grouping of devices. It is not recommended that you load balance in this manner. Instead, each data center should have it's own per-service LB (or just use the DNS queries) and then you can LB across the various DCs.

Unfortunately Go's template language does not provide us with the ability to do complex map-reduce operations like you've described here.

**Comment by eirslett** [comment]
Yes, you're right that in an ideal world it shouldn't be done - but we're doing a legacy migration, and therefore we need some services communicating across two data centers, temporarily.
It's not really a complex job - the only thing missing really is the union part, so we don't get duplicate entries in haproxy. We've already implemented the rest.
Surely it shouldn't be that difficult to find the union of two string arrays? :disappointed:

**Comment by sethvargo** [comment]
Hi @eirslett 

Thank you for your reply. While the technical implement may not be difficult, I do not want to encourage behavior that is not performant or satisfies just one use case. I'm worried that providing a `union` function would give people a false assumption that it's "okay" to run across multiple data centers like this. I cannot think of another use case, and therefore I am not really in favor of adding the new function. Does that make sense?

**Comment by sethvargo** [comment]
Hi @eirslett 

After thinking about this more and talking with the team, we do not plan to add this functionality to Consul Template as we do not want to encourage bad behavior. Sorry!
