### ISSUE TITLE
Question: Get Node Name in Service Range

### ISSUE THREAD

**Issue by tsupertramp** [hashicorp/consul-template#463]
Hey Ho everybody,

maybe somebody can explain me how to get the node name instead of the service name
in a service range?.

Two nodes get started with this service definition:
<pre>
{
  "service": {
    "name": "someExample"
  }
}
</pre>

I use the following Template File:
<pre>
  {{range service "someExample"}}
  object Host {{.Id}} {
    address = "{{.Address}}"
  }
  {{end}}
</pre>

This template with both nodes generates the following:
<pre>
object Host someExample
    address = "192.168.1.1"
}
object Host someExample  {
   address = "192.168.1.2"
}
</pre>

How can i configure the template that it creates (node.ids)
<pre>
  object Host e36e25adbd88  {
    address = "192.168.1.2"
  }
  object Host afd3e9d14780  {
    address = "192.168.1.1"
  }
</pre>

Thanks in common.

**Comment by sethvargo** [comment]
Hi @tsupertramp 

You can use `.Node`:

```liquid
  {{range service "someExample"}}
  object Host {{.Node}} {
    address = "{{.Address}}"
  }
  {{end}}
```

**Comment by tsupertramp** [comment]
Thanks @sethvargo 
works like a charm.
What i tried out:
.node.id
.node.name
and so on...
Just .node - too easy :D

Have a nice day!
