### ISSUE TITLE
Support for generating Vault tokens?

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul-template#469]
This may not be appropriate for consul-template, and I'm still trying to get my head around the model for providing Vault credentials to applications, so feel free to close this if not appropriate.

Would it be possible to have consul-template generate Vault *tokens*, in addition to retrieving secrets?  I'm envisioning a system where consul-template is started with a token that has a set of policies which is used to create new tokens with a sub-set of those policies.  This way I can have a single, trusted consul-template process that is used to configure other applications with only the policies they need to operate.  This may save me from having to implement application registration in my [centralbooking service](https://github.com/bluestatedigital/centralbooking).

**Comment by sethvargo** [comment]
Hi @blalor 

I think you just want to use the `vault` CLI for this. The "auth" methods do just this.

The problem with duplicating all the auth methods in Consul Template is that it sets a bad precedence that every client that interacts with Vault must implement all auth methods; it creates unmanageable fanout, code duplication, and opens potential security holes in the system. Instead, you should use `vault auth` to generate a token (via whatever auth method makes the most sense for your application) and then pass that token to Consul Template via the envvar or fs. Does that make sense?

**Comment by sethvargo** [comment]
Dupe of #318
