### ISSUE TITLE
Error after cloning solution

### ISSUE THREAD

**Issue by daveres** [hashicorp/consul-template#472]
```
# make
find . -type f -name '.DS_Store' -delete
go generate ./...
go test ./...  -timeout=30s -parallel=4
brain.go:6:2: cannot find package "github.com/hashicorp/consul-template/dependency" in any of:
        /usr/local/go/src/github.com/hashicorp/consul-template/dependency (from $GOROOT)
        /root/go/src/github.com/hashicorp/consul-template/dependency (from $GOPATH)
cli.go:15:2: cannot find package "github.com/hashicorp/consul-template/logging" in any of:
        /usr/local/go/src/github.com/hashicorp/consul-template/logging (from $GOROOT)
```

**Comment by ryanuber** [comment]
Hey @daveres, make sure you have cloned consul-template into `$GOPATH/src/github.com/hashicorp/consul-template`. You might also need to do a `make updatedeps`. Give that a try and let us know if you still have trouble!

**Comment by sethvargo** [comment]
Hi @daveres 

Thank you for opening an issue. Take a look at the [contributing section of the README](https://github.com/hashicorp/consul-template#contributing). You will need to clone the repo into your GOPATH and run `make updatedeps` and then run `make dep`. Thanks!

**Comment by daveres** [comment]
My bad, a lot of thanks
