### ISSUE TITLE
function not defined

### ISSUE THREAD

**Issue by tymofii-polekhin** [hashicorp/consul-template#473]
Hello,

Tried v0.11.1 from release site and 0.11.0 from github releases for linux_amd64, but both of them give the same issue with new functions:

`function "in" not defined`
`function "contains" not defined`

**Comment by sethvargo** [comment]
Hi @tymofii-polekhin 

Can you please share your Consul Template template?

**Comment by sethvargo** [comment]
I just tried this, and the function is working as expected on 0.11.1 and the master branch.
