### ISSUE TITLE
Log-level cli param ignored?

### ISSUE THREAD

**Issue by itheiss** [hashicorp/consul-template#475]
Hi,

regardless what I do or specify (e.g. -log-level=err) I always get this DEBUG output shown below.
```
consul-template -consul=consul.service.consul:8500  -log-level=err -config=./conf.d/ -once -dry
2015/12/04 12:34:14 [DEBUG] (config) loading configs from "./conf.d/"
2015/12/04 12:34:14 [DEBUG] (config) merging with "conf.d/clamav.conf"
```
Is this intended or bug?

Regards
Ingo

**Comment by sethvargo** [comment]
Hi @itheiss 

What version of Consul Template are you using?

**Comment by itheiss** [comment]
I am using the latest versikn v0.11.1.

**Comment by sethvargo** [comment]
@itheiss its a chicken and egg problem, since the log-level can also be set via the config

**Comment by itheiss** [comment]
OK I See. But anyway doesn't cli params take precedence over config params?
