### ISSUE TITLE
string parsing

### ISSUE THREAD

**Issue by kujohn** [hashicorp/consul-template#478]
consul-template seems to be stripping out colon from strings:

```
[server]
port = ":8080"
```

consul-template turns the above into
```
[server]
port = "8080"
```

Good practice is probably just have the port as number types but is this a rule written somewhere or a bug?

**Comment by sethvargo** [comment]
Hi @kujohn 

I don't quite understand the issue you are encountering. Consul [stores the port as an int](https://github.com/hashicorp/consul/blob/b756c9dace053215a65a6e6d24551545f2588339/command/agent/structs.go#L13), so it would not be possible to have a non-integer port stored in Consul anyway. Can you explain your situation a bit more?

**Comment by kujohn** [comment]
Tried to reproduce this but it's not happening anymore. Strange.

The original encounter was when `consul-template` processes templates, the resulting file had characters stripped away.

Oh well. If I do see it again i'll post steps to reproducing it.
