### ISSUE TITLE
Error calling parseBool

### ISSUE THREAD

**Issue by itheiss** [hashicorp/consul-template#480]
I made a simple test with the parseBool helper and I am not sure if this is a bug or simply how it works.

A template with a simple line like ```{{"3600" | parseBool}}``` will result in the following error:

```<parseBool>: error calling parseBool: parseBool: strconv.ParseBool: parsing "3600": invalid syntax```

Is this expected?

I wanted to loop through some keys and decide depending on the result of parseBool what to do. But I am failing with the above error.

```
{{range ls "service/owncloud/php/ini/"}}
{{if key (printf "service/owncloud/php/ini/%s" .Key) | parseBool}}
php_flag[{{.Key}}] = {{.Value}}
{{else}}
php_value[{{.Key}}] = {{.Value}}
{{end}}
{{end}}
```

Is this posible with the parseBool helper?

I am using consul-template v0.11.1.

**Comment by sethvargo** [comment]
Hi @itheiss 

The `parseBool` helper is used to parse a string representing a boolean into a `bool`:

```
"true" => true
"false" => false
```

There are no other bool types in the Go programming language. It is not possible to convert an integer value like "1234" into a boolean - that conversion doesn't make sense.

Did you mean `parseInt`?

**Comment by itheiss** [comment]
I thought I could use this as a kind of boolean checker. But

**Comment by sethvargo** [comment]
https://golang.org/pkg/text/template/@itheiss unfortunately that is not possible. You can check for presence just using a basic `if`:
