### ISSUE TITLE
Ability to iterate over checks for a given service on a given node

### ISSUE THREAD

**Issue by pepov** [hashicorp/consul-template#482]
I would like to iterate over checks in order to map them as individual services in nagios using https://github.com/ustream/nagios-consul-plugin. What are you're opinions about this? Shall I move on and create a pull request or am I missing something?

**Comment by sethvargo** [comment]
Hi @pepov 

This is not something we currently expose, mostly because it has not been requested. I'm not sure if check changes affect blocking queries, so you might not get the behavior you expect. 

/cc @ryanuber for input

**Comment by pepov** [comment]
It would be nice if you could point me to the right direction and I would be happy to implement it and send a PR

**Comment by sethvargo** [comment]
Hi @pepov 

You'll want to look through the Consul API first: https://github.com/hashicorp/consul/tree/master/api to find which struct fields you need. Then you have to mirror them in Consul Template in the dependency/health_service.go.
