### ISSUE TITLE
Regarding: Consul-Template using multiple Consul servers #334

### ISSUE THREAD

**Issue by vLifeOfBrian** [hashicorp/consul-template#486]
In our configuration we have 3 Consul servers in a cluster, and the consul-template daemon is installed on 2 Nginx servers external to the Consul cluster. How would you configure consul-template to be aware of the Consul cluster DNS? using the -consul flag for consul.service.consul doesn't find the Consul cluster.

Is there any documentation that describes deploying Consul/consul-template in a distributed production environment? I haven't been able to find anything on this topic beyond this issue. All the documentation I can find seems to be based on all the components being installed on the same instance.

**Comment by sethvargo** [comment]
Hi @vLifeOfBrian 

Thank you for opening an issue. As is always true with any Consul tool, you should almost always talk to the _local_ consul agent running on 127.0.0.1:8500. The local Consul agent multiplexes requests to the Consul cluster, and the cluster handles responses (either via stale queries or request forwarding).

The local Consul agent (running in client mode on your nginx servers) connects to your Consul cluster. This is also how you register that node and its services.

Does that help answer your question?

**Comment by vLifeOfBrian** [comment]
Yes. Thank you.

**Comment by dunty** [comment]
I think that is not a good solution. I don't want the consul agent running on every VM, some applications only are the client of consul servers, need not the extra process.
