### ISSUE TITLE
How do I invoke multiple custom consul templates and concatenate them together  

### ISSUE THREAD

**Issue by milind-git** [hashicorp/consul-template#487]
Let me describe what I am trying to do :

```
{{ define "template1" }}  {{ /* Accepts Argument1 and returns back printed string */  }}  {{end}}
{{ define "template2" }}  {{ /* Accepts Argument2 and returns back printed string */  }}  {{end}}
{{ define "template3" }}  {{ /* Accepts Argument3 and returns back printed string */  }}  {{end}}
```

```
{{ with tree (print "xyz/" ( template "template1" arg1 )" ( template "template2" arg2) (template "template3" arg3)  | explode }}
,
"kv" : {{ . | toJSONPretty }}
{{end}}
```

So I am trying to explode the K-V Tree of Consul. Each of _template1 ,template2 and template3_ returns nodes of tree ( based on calculation done using supplied arguments) and I concatenate them together to form the whole path. 

Though  __{{ template "template1" arg1}}__ works fine but calling these __3 templates _as above___ leads to compilation error .

I tried assigning the return from each template functions to some variables as below:

```
{{ $return1 := template "template1" arg1}} 
```

but that also is failing.

Experts, can you suggest on how do I go about it.

Here is what I would like to achieve:

##### tree ( method4(arg1,arg2,arg3) | explode ) 

Since in Consul template ( using define) there seems to be no way to pass multiple arguments, I dropped method4 and invoking method1 , method2 and method3 directly as 

#####  tree ( method1(arg1) + method2(arg2) + method3(arg3) | explode )
 
It would have been nicer if I could do :

##### {{ var $zz = $x + $y + $z }}

and do 

##### {{ with tree (print  $zz ) | explode }}

Remember , I am writing this program in a consul template file __so everything should go inside {{ }}__.

**Comment by sethvargo** [comment]
Hi @milind-git 

Thank you for opening an issue. Unfortunately this is not possible with Go's templating language. While you can define nested template definitions, there is no way to pass arguments to those definitions: https://golang.org/pkg/text/template/. 

I think you should be able to use the `printf` function to concatenate strings to build the proper KV path though.

Please let me know if you have any questions.

**Comment by milind-git** [comment]
Thanks for answering the question promptly, appreciate your help.
I know I can pass single argument to consul custom defined template (DOT) however my main issue is how do I store the value returned by that template method or function 
For example , I have defined something like :
###### {{ define "mytemplatemethod"}} {{ .}} { /*DOT refers to argument passed*/}} {{ end}}

I am able to pass argument like :
###### {{ template "mytemplatemethod" .Tags}}  //THIS IS WORKING 
#### {{ $x : = template "mytemplatemethod" .Tags}}  //THIS IS NOT WORKING 

Thanks.

**Comment by sethvargo** [comment]
You cannot render a template into a variable. This is not a CT bug, but a feature of Gos templating language.

**Comment by milind-git** [comment]
Ok, no issues, I gave up on using variables. __Any chance of making following work__?
##### {{ with tree (print  (template "template1" arg1) "/" (template "template2" arg2 )) | explode }}
#### Right now, it fails if "template" is not first word after {{  ( works only for {{ template "template1" arg1}}
_Thanks for replying persistently to my all questions._

**Comment by milind-git** [comment]
Well, considering suggestions, I have changed my logic to iterate through services and tags and everything seems to be working except value assigned to a variable inside if loop is lost once the if loop is exited ( variable defined outside and before if loop).

**Comment by milind-git** [comment]
__For the benefit of others, how I could resolve the issue:__
Instead of using "defined" templates, I am Looping through tags twice ( This isn't good from performance perspective but I wasn't able to find a better working solution , if anybody has please share your comments):
###### Loop through Services
######    For a Given Service name , loop through all matching services ( could be multiple)
######              Loop through Tags 
######                    Get Value of first matching tag - if matched
######                           Loop through tags again 
######                                 Get Value of second matching tag - if matched 
######                                       Construct K-V Path using first tag and second tag value and explode                                              Tree
