### ISSUE TITLE
exposing tags in template.

### ISSUE THREAD

**Issue by donniev** [hashicorp/consul-template#488]
I am confused about the use of tags:
In my service definition I have
```
{
  "consul": "consul:8500",
  "onStart": "/opt/containerbuddy/reload-hexo.sh",
  "services": [
    {
      "name": "hexo",
      "port": 4000,
      "tags":["joyent.blog.vawter.com"],
      "health": "/usr/bin/curl --fail -s http://localhost:4000/",
      "poll": 10,
      "ttl": 25
    }
  ],
  "backends": [
      ]
}
```
and I want to reference the tags array in my consul template
If I put this in template
```
{{range services}}
  {{range service .Name}}
    {{.Name}}
    {{.Address}}
    {{.Port}}
    {{.Tags}}
   {{end}}
 {{end}}
```
It renders:
```

    hexo
    192.168.128.209
    4000
    []
   
```
What am I missing here?

**Comment by sethvargo** [comment]
Hi @donniev 

Thank you for opening an issue, and I am sorry you are having issues with CT. Unfortunately I am not able to reproduce this issue. Here are the steps I took:

- Consul Template 0.12.0
- Consul 0.6.0

```
$ cat /scratch/consul/web.json
{"service": {"name": "web", "tags": ["rails"], "port": 80}}

$ cat /scratch/template.ctmpl
{{ range services }}{{ range service .Name }}
{{.Name}}
{{.Address}}:{{.Port}}
{{.Tags}}{{end}}
{{end}}

$ consul agent -server -bootstrap -data-dir=/tmp/consul -config-dir=/scratch/consul
# ...

$ consul-template -template=/scratch/template.ctmpl -dry -once
> 

consul
10.0.0.9:8300
[]

web
10.0.0.9:80
[rails]
```

Are you able to provide any additional information? Are you, perhaps, setting tags on the node instead of the service?

**Comment by slackpad** [comment]
As a quick check to make sure your service is getting registered correctly, does http://localhost:8500/v1/catalog/service/hexo show the tags you registered?

**Comment by CenterStoneOSD** [comment]
This may be a joyent containerbuddy issue. That is what is responsible for actually registering the services. Have filed issue with them and will let you know status.

**Comment by CenterStoneOSD** [comment]
This is a container buddy issue. They only register address and port. Thanks for your help.
