### ISSUE TITLE
Consul-Template doesn't seem to run on service port change on same host

### ISSUE THREAD

**Issue by owaaa** [hashicorp/consul-template#489]
I am using consul-template for managing an nginx config. All has been working great when services where the service host IP addresses change. However, as I've begun migrating to AWS ECS I've noticed that consul-template doesn't seem to run when a service is updated to be on a different port random of the same host. My nginx template is stuck on an old obsolete port reference. Is there a configuration or something I can do to listen for service port changes?

I am populating nginx with something like the following 
`upstream service {
  least_conn;
  {{range service "service-name"}}server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=60 weight=1;
  {{else}}server 127.0.0.1:65535; # force a 502{{end}}
}`

**Comment by sethvargo** [comment]
Hi @owaaa 

Consul Template is just using the Consul API for these blocking queries. The Consul API should be returning when a port changes, but I could be wrong. Nonetheless, this is an upstream issue. Could you please open an issue on the Consul project? Thanks! :smile: 

/cc @slackpad
