### ISSUE TITLE
would it possible to auto reload configuration files?

### ISSUE THREAD

**Issue by vfahrenheit** [hashicorp/consul-template#491]
for example, add a specific flag to enable auto reloading feature when starting consul-template. When any file changes detected, auto reload the files.  
Otherwise i would have to write a monitor app to send SIGHUP to daemon. 
Or any better solution to support my scenario?

**Comment by sethvargo** [comment]
Hi @vfahrenheit 

As you said, you can send SIGHUP to reload configuration files and templates. This is not something we want to do automatically at this time due to Go's lack of built-in file watching libraries. This is something we will look into after Go 1.6 (which is when file watching support is slated to be added). Thanks! :smile:

**Comment by ketzacoatl** [comment]
@sethvargo, should a SIGHUP be sent if there are changes to templates?

**Comment by devth** [comment]
@sethvargo now that 1.6 is out, would you consider auto-reloading the template(s) from disk when changed?

**Comment by sethvargo** [comment]
Hi @devth 

After some discussion internally, we determined that automatically reloading configuration files and templates is a bit of an anti-pattern and does not mirror existing tools. For example, you must tell nginx, haproxy, and apache to reload their configurations. This allows the user to have full control over the process, adding validation where appropriate, and better operationalizing the tool.

**Comment by ketzacoatl** [comment]
@sethvargo - does the SIGHUP apply to changes in templates?

**Comment by devth** [comment]
That makes sense. But I might argue that consul-template is at a level above components like nginx/haproxy - it's more of a configuration orchestrator.

So, I need to figure out how to send a HUP to the docker container that's running consul-template.

I'm running on K8S on Google Container Engine. In a single pod I run:

- node app container
- consul-template container

I mount a gcePersistentDisk volume to provide templates for consul-template to render into another volume (at `/config`) that's shared between the node app and consul-template.

Ideal workflow is:

0. Dev changes a template stored in git and uploads it to GCE disk
0. Consul-template picks up the change to the template and re-renders into `/config`
0. Node app watches `/config` dir for changes and picks them up

There's no orchestrator above consul-template to send it a SIGHUP. Options I can think of:

- run yet another container to watch the templates volume
- run some process above consul-template in that container

Thoughts?

**Comment by devth** [comment]
@ketzacoatl yes, SIGHUP makes consul-template reload the template from disk and re-render it.

**Comment by ketzacoatl** [comment]
TY!

**Comment by ketzacoatl** [comment]
@devth, for your problem, you could put consul-template config into a template and have a consul watch that runs consul-template in `-once` mode when that key in consul changes (and put the params for the template into consul).

**Comment by devth** [comment]
@ketzacoatl true but then I can't store app config templates in git, along side the app. (Well I could, but it'd require devs to copy/paste it into Consul -- annoying).

**Comment by ketzacoatl** [comment]
You could have something monitor git and auto-load kv into consul to keep it all in git.

**Comment by devth** [comment]
@ketzacoatl good idea, I might try that!

**Comment by ketzacoatl** [comment]
At least for my uses, it has worked well in practice. I am happier with it in place.
