### ISSUE TITLE
Allow setting user and group ownership of rendered templates

### ISSUE THREAD

**Issue by Chili-Man** [hashicorp/consul-template#494]
Currently, consul-template does not allow changing the user/group ownership of the rendered templates. This does not permit allowing only specific users/groups to read from the rendered templates. As a workaround, one can launch a consul-template as a specific user for each template to be rendered, but it is not ideal as you would have to possibly launch many consul-template processes.

**Comment by sethvargo** [comment]
Hi @Chili-Man 

Thank you for opening an issue. This is a duplicate of https://github.com/hashicorp/consul-template/issues/461, please see the comments on that issue. Thanks! :smile:
