### ISSUE TITLE
Only using vault dynamic data - vault-template?

### ISSUE THREAD

**Issue by nickithewatt** [hashicorp/consul-template#495]
Not sure if this is the best place to raise this question, or possibly within vault's issues, but I shall begin here and if need be migrate it over.

My query is essentially, what if I ONLY want to populate values from Vault into the filesystem (i.e no consul). consul-template has built in support for vault, however it does not seem that you can gain access to this functionality in isolation, you MUST (unless I am missing something) specify consul credentials etc, which is completely understandable given this tool's primarily focus is consul, and vault support was added later.

I suppose my question/feature request is: Is there a way to allow consul-template to only require vault details if Vault is the only place you want to get dynamic data from, or is another tool, a vault-template so to speak, something which could be developed? Also ping @jefferai

**Comment by sethvargo** [comment]
Hi @nickithewatt 

You definitely do not have to provide Consul information to connect to Vault. Please make sure you are running the latest version of Consul Template and it should work fine (just tested myself).

**Comment by nickithewatt** [comment]
@sethvargo you are correct, my bad had some dodgy config!
