### ISSUE TITLE
Using HTTP HEAD on watch poll?

### ISSUE THREAD

**Issue by subchen** [hashicorp/consul-template#496]
On today's implementation, KV store watch is based on a HTTP GET poll. 

Is there a performance issue on poll? Or use HTTP HEAD instead of GET to check updates?

**Comment by sethvargo** [comment]
Hi @subchen 

Thank you for opening an issue. I don't think there are any performance implications. We use Consul's own internal API client to make the queries, so if you think there's a performance improvement to be made, I would recommend opening an issue against consul itself :smile:

The consul API package is at github.com/hashicorp/consul in the api folder.
