### ISSUE TITLE
Walking nested K/Vs?

### ISSUE THREAD

**Issue by polds** [hashicorp/consul-template#502]
This is very similar in question to #258 and that one yielded in a new function being added. 

I'm just wondering if it's possible to walk through several layers of K/Vs. Trying to write an HAProxy config file from K/V not services.

**K/V**
```
services/examples/endpoint = myendpoint.com
services/examples/id = 12345
services/examples/instances/instance1 = 10.0.0.0:80
services/examples/instances/instance2 = 10.0.0.1:80
services/examples2/endpoint = myendpoint2.com
...
```

**Desired Output**
```
acl 12345 hdr(host) -i myendpoint.com
use_backend 12345 if 12345

backend 12345
  server instance1 10.0.0.0:80
  server instance2 10.0.0.1:80
```

The issue I'm running into is when using `tree` and `byKey` I end up with keys named `examples/endpoint`, `examples/id`, `examples/instances/instance1`, `examples/instances/instance2`

I'm not exactly sure how to loop over those. Any ideas?

**Comment by polds** [comment]
I was going about it wrong. I have figured it out. For those curious:

```
acl 12345 hdr(host) -i myendpoint.com
use_backend 12345 if 12345

{{with tree "services" | explode}}{{range $key, $values := .}}
acl {{$key}} hdr(host) -i {{$values.endpoint}}
use_backend {{$key}} if {{$key}}
{{end}}{{end}}
```

```
backend 12345
  server instance1 10.0.0.0:80
  server instance2 10.0.0.1:80

{{with tree "services" | explode}}{{range $key, $values := .}}
backend {{$key}}
	{{range $name, $value := $values.instances}}
	server {{$name}} {{$value}}
	{{end}}
	{{end}}
{{end}}
```

**Comment by scalp42** [comment]
Thanks @polds for the follow up!
