### ISSUE TITLE
error running command: wait: no child processes

### ISSUE THREAD

**Issue by laktak** [hashicorp/consul-template#506]
When my services change I get the following error:

```
2016/01/11 10:54:48 [ERR] (runner) error running command: wait: no child processes
Consul Template returned errors:
1 error(s) occurred:

* wait: no child processes
```

This is with 0.12.1/0.12.0 and haproxy-1.6.2-r0. `docker restart` gives the same error but `docker stop` and `docker start` will fix it (until the next change).

The same configuration works in v0.11.0

**Comment by sethvargo** [comment]
Hi @laktak 

I think you are hitting the same bug as #442, which will be fixed once Go 1.6 is released.
