### ISSUE TITLE
Hot loop reaping child process 0, wait contention

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul-template#507]
Pulling this out from https://github.com/hashicorp/consul-template/issues/442#issuecomment-170895780 and https://github.com/hashicorp/consul-template/issues/442#issuecomment-170899841 since it's a separate issue.

It looks like some users are encountering a situation where the child process reaper is running at 100% claiming to be `Reaping child process 0`. Setting `-reap=false` will work around this, but we need a fix to prevent this.

There's also an issue where CT reports `[ERR] (runner) error running command: wait: no child processes` - this is happening when the reaper steals the wait result from CT.

Both of these issues affect Consul as well, so we will need to update there with a similar fix.

**Comment by slackpad** [comment]
It looks like the zero return value should kick us back to `WAIT` instead of `POLL`:

https://www.mkssoftware.com/docs/man3/wait3.3.asp

> The wait3() and wait4() functions return 0 if WNOHANG is specified and there are no stopped or exited children, and return the process ID of the child process if they return due to a stopped or terminated child process. Otherwise, they return -1 and set errno to indicate the error.

**Comment by geniousphp** [comment]
I encounter this issue when I use CP 0.12.0 with `-reap=true`. I'm working with a container docker containing CP and HAProxy, CP has PID 1. When CP restart HAProxy 2 (and exactly 2)  times, it exists with the following msg error `[ERR] (runner) error running command: wait: no child processes`

**Comment by slackpad** [comment]
@geniousphp interesting - that looks like a separate issue where the process reaper is "stealing" the wait result from Consul Template itself. I've got the hot loop fixed in the PR above but I'll also take a look at this.

**Comment by geniousphp** [comment]
Ouups, maybe I should have opened a new issue because I never encounter the issue `Reaping child process 0`. I'm not sure if my issue is related to #442. May be I should wait for a new CP version compiled with with the last GoLang version and see again. Meanwhile, I continue using CP 0.10.0

**Comment by slackpad** [comment]
@geniousphp no worries - they are closely related so I added your issue to this one so we can track them together.

**Comment by slackpad** [comment]
Fix is in for Consul Template as well as Consul.
