### ISSUE TITLE
Daemon should not terminate when command exit code !=0

### ISSUE THREAD

**Issue by vvanholl** [hashicorp/consul-template#508]
When a template command fails, the main process terminates despite it is in daemon mode. According to me it should simply log the event as an error.

For instance If I write my command as "service haproxy reloa": 
 * haproxy: unknown function `reloa'
2016/01/12 21:29:42 [ERR] (runner) error running command: exit status 1
Consul Template returned errors:
1 error(s) occurred:

* exit status 1

**Comment by sethvargo** [comment]
Hi @vvanholl 

Thank you for opening an issue. We document the [Termination on Error](https://github.com/hashicorp/consul-template#termination-on-error) phases in the README. Most users desire the opposite behavior than what you've reported, and there is a workaround in that section to force the process to continue. Thanks! :smile:

**Comment by shakisha** [comment]
#645
