### ISSUE TITLE
reload config for nginx in container

### ISSUE THREAD

**Issue by anklos** [hashicorp/consul-template#510]
Is there a way to reload nginx config for the nginx running inside docker container? As kill and restart nginx container does not gracefully handle running http connections.

Sorry my question probably does not belongs to this project, just assuming people who using `consule-template` are very likely to have experience on this.

Thanks!

**Comment by sethvargo** [comment]
Hi @anklos 

You can execute any shell script you want when configuration changes, including something like `docker-exec`. If the CT process is running on the same container as the nginx daemon, you can also just reload nginx directly.

**Comment by anklos** [comment]
ah, yes of coure, thanks!

**Comment by EugenKon** [comment]
Ok, I can execute `docker-exec` but is that possible to get the name of the container by service name?
