### ISSUE TITLE
Sopput for consule master nodes list

### ISSUE THREAD

**Issue by toecto** [hashicorp/consul-template#512]
I couldn't find if parameter `-consul` supports list of servers?
In case if I have a cluster of tree consul masters.

**Comment by sethvargo** [comment]
Hi @toecto 

The `consul` parameter accepts any consul DNS or IP. Consul is architected in a way that any followers will forward requests to the leader automatically.

**Comment by dunty** [comment]
That is not the answer that we hope. Same as toecto, I have three consul servers in a cluster, one failed, others can continuely work. But, ```-consul``` only have one server, how to switch when that server is done?

**Comment by slackpad** [comment]
Hi @dunty Consul is designed to have the local agents manage this for you so we haven't architected all our tools to take lists of servers. We recommend that you run a Consul agent on each node where you run consul-template. If you don't want to do this, then you probably want to put something like haproxy in front of your Consul servers, but we generally discourage that. A lot of the benefits of Consul come from running the agents on each node in your cluster.

**Comment by dunty** [comment]
@slackpad, thank you for your patiently answer.
