### ISSUE TITLE
consul-template config (hcl) include?

### ISSUE THREAD

**Issue by strarsis** [hashicorp/consul-template#515]
This may also relate to HCL config generally.

Is it possible to include a folder or files by glob pattern from inside the consul-template config file?
It would like to add consul-template config templates + destination + reload command by dropping those files into a folder.

Thank you and
with best regards

**Comment by sethvargo** [comment]
Hi @strarsis 

You cannot include other files, but you can specify a path to a folder than contains all your configs and they will be merged.
