### ISSUE TITLE
How to do table lookups?

### ISSUE THREAD

**Issue by carlpett** [hashicorp/consul-template#516]
I'm creating a machine inventory generator with consul-template, and now I'm at a point where I need to map a part of the node name to a list of owners - basically a table lookup. How would I go about this in an idiomatic way? 

As an example, given the node name `foo`-web10, I'm extracting the first part `foo` (with `regexReplaceAll`, is there a better way?), and then I'd like to replace this in my template with `The Foomatic Group`. 

I've considered adding the data to consul kv, but it feels a bit dirty. Would this be the time to write a plugin?

**Comment by sethvargo** [comment]
Hi @carlpett 

Thank you for opening an issue. We try to keep the issue tracker reserved for bug reports and feature requests. For general usage questions, could you please post on the Consul mailing list instead? Thanks! :smile:

**Comment by carlpett** [comment]
Hi, sorry about that, thought I saw quite a lot of other "how-to"-looking issues, but I see your point and will send to the mailing list instead :smile:
