### ISSUE TITLE
consul agent + consul-template?

### ISSUE THREAD

**Issue by strarsis** [hashicorp/consul-template#519]
According to README, the consul service is put into maintenance 
during the reload (of nginx in this example).

So consul-template itself offers an update command - 
but it won't toggle the maintenance state by its own?

For a maintenance status of the consul service between the reloads, 
the consul agent should also be installed + a shell script for maintenance toggle/reloading used?

For docker, environment variables are used for mapping service info for a container into consul using registrator, should these environment variables also used to determine the consul service name the container runs with?

Thank you and
with best regards

**Comment by sethvargo** [comment]
Hi @strarsis 

Consul Template watches for changes in Consul and then (optionally) runs a command when the state has changed. When a node changes state (including moving into or out of maintenance mode), Consul Template will receive this event and update the resulting template.

Unfortunately I am having trouble understanding the rest of your question. Could you please add some code samples?

**Comment by strarsis** [comment]
From README in this repository
````
To put a service into maintenance mode in Consul around executing the command, simply wrap your command in a consul maint call:
````
````
#!/bin/sh
set -e
consul maint -enable -service web -reason "Consul Template updated"
service nginx reload
consul maint -disable -service web
````

So during reload the consul service for nginx is put into maintenance mode.

With best regards

**Comment by sethvargo** [comment]
Hi @strarsis 

Consul Template cannot support his natively because it does not know _which_ service you might want to put into maintenance mode. Or, you may want to put two services into maintenance mode before restarting the service. The easiest way to clearly the intent of the restart script is to add everything inline to the script, which is why we recommend using it as such. 

Does that answer your question?

**Comment by strarsis** [comment]
With "Adding inline to the script" it is meant that the service toggling (consul agent) is put into a script -
this script is run by consul-template as the update command instead directly restarting the service?

**Comment by sethvargo** [comment]
Hi @strarsis 

Yes, that's what I mean by "inline in the script", just like the example in the README.

While your particular use case may only use one service per container, many users are not running in containers or may be running multiple processes managed by a single template. As such, it's much easier to use the very flexible restart command to satisfy everyone's use case.

Does that make sense?

**Comment by strarsis** [comment]
Yes, thanks for the response.
