### ISSUE TITLE
consul-template + consul agent: recycle config

### ISSUE THREAD

**Issue by strarsis** [hashicorp/consul-template#520]
Is it possible to use the config directory/config files for both, consul-template and consul agent?
At least the common config, notably the consul server connection settings?

Can consul watch invoke consul-template and pass its own consul connection config to it by default?

Thank you and
with best regards

**Comment by sethvargo** [comment]
Hi @strarsis 

The configuration for consul and the configuration for consul-template is different. The configuration files use a different schema and different configuration values. As such, it is not possible to share a configuration.
