### ISSUE TITLE
document SIGHUP support

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul-template#522]
Please document the use of SIGHUP for reloading configuration in the readme.

**Comment by sethvargo** [comment]
Hi @blalor 

Thank you for opening an issue. Sorry this isn't documented - would you like to open a PR?

**Comment by blalor** [comment]
I would, but I don't really understand what's happening under the hood.  I'm happy to see that it's supported, but I'm not sure what it's *supposed* to do.  It seems that HUP does do a reload (and a removed config is no longer processed), but I witnessed consul-template trigger the script for a template after a reload, and I didn't expect that.  Possibly a bug, but I wanted to be sure I understood how it was supposed to work, first. :-)
