### ISSUE TITLE
question: should consul-template "sync" with KV/catalog if files are "out-of-date"

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/consul-template#527]
ATM, consul-template "renders a template" when a value it is configured to watch changes. If consul-template is offline, and the values change, consul-template does not seem to render/apply templates when it starts up, even if the templates are "out of date". I am curious if this is intended behaviour, or if there are good reasons for not wanting consul-template to apply the template on first run (if needed)..?

**Comment by sethvargo** [comment]
Hi @ketzacoatl 

When the Consul Template process starts (or restarts), it will fetch the latest set of dependencies defined by the template and render the template in-memory. It then compares the in-memory contents with the contents on disk and, if there are any changes, it will re-render the template and execute the command. If there are no changes to the template, it will not re-render or run the command. Does that make sense?

**Comment by ketzacoatl** [comment]
That makes sense, and is as I would expect the tool to function.. so the question remains why I am not seeing this in practice. Maybe.. if the consul cluster is not yet available (but comes available shortly after consul-template starts), and consul-template has to retry it's join, would that interrupt the process you have outlined above?

**Comment by sethvargo** [comment]
Hi @ketzacoatl 

Thank you for your reply. I'm not totally sure I'm following the situation you're experiencing. It would be helpful if you could run Consul Template in debug mode and capture this behavior and submit the debug log as a gist so I can take a look.

**Comment by ketzacoatl** [comment]
Sure, I will enable debug and look into what results - that should help me confirm if my setup is the problem. You have confirmed consul-template should work as I would expect, but I'll post the debug log if I am unable to see consul-template work that way. Thanks for your help @sethvargo!

**Comment by ketzacoatl** [comment]
The debug log was helpful, and it seems consul-template is working as expected. I haven't yet resolved my issue, but I believe consul-template is fine. Thanks @sethvargo!
