### ISSUE TITLE
question: about  wait minimum(:maximum)

### ISSUE THREAD

**Issue by piavlo** [hashicorp/consul-template#531]
How does the wait feature works?

First of all based on what will consul-template decide for how long to wait between "min" and "max" ?

Second what happens if we change some kv key that consul-template  watches and then change it back to old value within the "min" period, will consul-template detect that no change actually was made and will not render new config to disk? 

tnx

**Comment by sethvargo** [comment]
Hi @piavlo 

You can read more about quiescence here: https://en.wikipedia.org/wiki/Concurrent_data_structure#Basic_principles

In short, it specifies the minimum amount of time data must remain unchanged before rendering the result, but it also specifies the maximum amount of time to wait for changes to stop occurring. So, given a minimum of 5s and maximum of 2min, CT will wait until no data changes have occurred with the given dependency set for 5s before rendering the template. If 2min has passed and the dependencies still haven't reached a state of rest, the template will be rendered anyway.

Your assumption is correct that if the value is unchanged from t0 to t1 in the timers, it will not render changes.

**Comment by piavlo** [comment]
@sethvargo  thanks for the prompt reply

gr8 so this gives us both mitigation to non atomic updates of multiple keys
and also we can run a consul watch based validation code on updated/new keys that will automatically
rollback/delete invalid values before the "minimum" is reached and triggers an rolling app restarts
(though we have a distributed circuit breakers that will prevent for more than app instance to fail restarting with bad config, but it's still way better just not to trigger the rolling restart in the first place)

**Comment by piavlo** [comment]
oh forgot to verify
afaiu the wait is per consul-template process setting
and not per template?
any plans to make this per template setting?

**Comment by sethvargo** [comment]
It's per template

**Comment by piavlo** [comment]
hmm ok,  then adding a scope to options in the list 
https://github.com/hashicorp/consul-template#options
would be really helpful

tnx

**Comment by jeffminard-ck** [comment]
I'm posting on this thread because what I'm finding doesn't line up with your explanation @sethvargo 

> So, given a minimum of 5s and maximum of 2min, CT will wait until no data changes have occurred with the given dependency set for 5s before rendering the template. If 2min has passed and the dependencies still haven't reached a state of rest, the template will be rendered anyway.

I would expect this to mean:

 * ct is running, service map has been stable for a while
 * new service comes online (which ct is watching)
 * ct sees this change, but will wait 30 seconds to re-render/exec

However, I'm seeing that render/exec happen much sooner because the max timer is triggering, as if the max timer is on its own timer loop not connected to the triggering event. As an example, I end up seeing this:

```
2016/06/29 13:18:56 [DEBUG] ("service(usersrv)") Consul returned 6 services
2016/06/29 13:18:56 [DEBUG] ("service(usersrv)") 6 services after health check status filtering
...
2016/06/29 13:18:57 [DEBUG] ("service(usersrv)") querying consul with &{Datacenter: AllowStale:true RequireConsistent:false WaitIndex:2995 WaitTime:1m0s Token: Near:}
2016/06/29 13:19:01 [DEBUG] ("service(usersrv)") Consul returned 7 services
2016/06/29 13:19:01 [DEBUG] ("service(usersrv)") 7 services after health check status filtering
2016/06/29 13:19:07 [INFO] (runner) quiescence maxTimer fired for ct
2016/06/29 13:19:07 [INFO] (runner) received template "ct" from quiescence
2016/06/29 13:19:07 [INFO] (runner) running
2016/06/29 13:19:07 [DEBUG] (runner) checking template ct
2016/06/29 13:19:07 [DEBUG] (runner) checking ctemplate &{Source:ct Destination:ct.out Command:echo `date` >> ct.date CommandTimeout:30s Perms:-rw-r--r-- Backup:false}
2016/06/29 13:19:07 [DEBUG] (runner) wouldRender: true, didRender: true
2016/06/29 13:19:07 [DEBUG] (runner) appending command: echo `date` >> ct.date
```

You can see that the change was detected at `01` but the changes were rendered/exec'd 6 seconds later (at `07`) which is much sooner than the 30s wait that it should have been.
