### ISSUE TITLE
Dynamic tag lookup from env-variable

### ISSUE THREAD

**Issue by kolis** [hashicorp/consul-template#532]
I'm trying to set up a template where the service tag value is not statically known. Instead I would like to dynamically fetch this from the environment. Eg something like this

```
{{range service "$CURRENT_TAG.mysql"}}
```

I have tried some syntax-variations but have not found anything that works. eg this does not work

```
{{range service "{{env "CURRENT_TAG"}}.mysql"}}
```
and neither

```
{{range service "mysql"}}
{{ if (.Tags.contains {{env "CURRENT_TAG"}}) }}
```

**Comment by sethvargo** [comment]
Hi @kolis 

I think you need to use the `printf` function to interpolate:

https://golang.org/pkg/text/template/

**Comment by kolis** [comment]
This was a bit challenging for me, I'm not that familiar with go programming, but I figured out something that seem to work
```
        {{range service (printf "%s.mysql" (env "CURRENT_TAG"))}}
```
