### ISSUE TITLE
Reloading configuration duplicates templates

### ISSUE THREAD

**Issue by wwalker** [hashicorp/consul-template#534]
I have a set of templates built from vault variables.  There are only 60 vault variables.  they have a minimum lease time of 30 seconds.  One would expect an average of 4 requests per second max (many of hte variables have longer lease times).

The vault audit log shows that it is handling over 40 requests per second from consul-template.

It seems to be throttled be vault performance (vault it using ~180 % CPU), so it appears that consul-template would be doing  even more if it could.

Vault -0.3.1.  the o.4.0 upgrade is planned for the next couple of weeks.
consul-template is 0.10.0
vault backend is consul 0.6.0

**Comment by jefferai** [comment]
I'm not sure on the CT side but at this point I'd recommend planning for a Vault 0.5 upgrade instead, especially if it's still a few weeks out.

**Comment by sethvargo** [comment]
Hi @wwalker 

As Jeff said, I would recommend going to Vault 0.5, since it will be released shortly.

I also believe there were known issues in Consul Template 0.10 that have been fixed in 0.12.1(and then 0.12.2 was a minor patch release for folks running in Docker containers). https://github.com/hashicorp/consul-template/blob/master/CHANGELOG.md#v0121-january-7-2016

Can you try upgrading and let me know if that fixes the issue?

**Comment by wwalker** [comment]
Upgraded to 0.12.2.

Log shows that, during 1 second, it checked the same variable 6 times:

    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") vault returned the secret
    2016/02/08 16:00:13 [DEBUG] (view) "vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)" no new data (contents were the same)
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") querying vault with &{AllowStale:true WaitIndex:1454968813 WaitTime:1m0s}
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") pretending to long-poll for "15s"
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") vault returned the secret
    2016/02/08 16:00:13 [DEBUG] (view) "vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)" no new data (contents were the same)
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") querying vault with &{AllowStale:true WaitIndex:1454968813 WaitTime:1m0s}
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") pretending to long-poll for "15s"
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") vault returned the secret
    2016/02/08 16:00:13 [DEBUG] (view) "vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)" no new data (contents were the same)
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") querying vault with &{AllowStale:true WaitIndex:1454968813 WaitTime:1m0s}
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") pretending to long-poll for "15s"
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") vault returned the secret
    2016/02/08 16:00:13 [DEBUG] (view) "vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)" no new data (contents were the same)
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") querying vault with &{AllowStale:true WaitIndex:1454968813 WaitTime:1m0s}
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") pretending to long-poll for "15s"
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") vault returned the secret
    2016/02/08 16:00:13 [DEBUG] (view) "vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)" no new data (contents were the same)
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") querying vault with &{AllowStale:true WaitIndex:1454968813 WaitTime:1m0s}
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") pretending to long-poll for "15s"
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") vault returned the secret
    2016/02/08 16:00:13 [DEBUG] (view) "vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)" no new data (contents were the same)
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") querying vault with &{AllowStale:true WaitIndex:1454968813 WaitTime:1m0s}
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") pretending to long-poll for "15s"
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") vault returned the secret
    2016/02/08 16:00:13 [DEBUG] (view) "vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)" no new data (contents were the same)
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") querying vault with &{AllowStale:true WaitIndex:1454968813 WaitTime:1m0s}
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") pretending to long-poll for "15s"
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") vault returned the secret
    2016/02/08 16:00:13 [DEBUG] (view) "vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)" no new data (contents were the same)
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") querying vault with &{AllowStale:true WaitIndex:1454968813 WaitTime:1m0s}
    2016/02/08 16:00:13 [DEBUG] ("vault(secret/ops/configs/properties/product_groups/indeedu-golf/redis.password)") pretending to long-poll for "15s"

**Comment by wwalker** [comment]
I'm wondering if this patch (https://github.com/hashicorp/consul-template/pull/394/files) had a side effect of adding additional runners when it updates the config instead of overriding the config??

**Comment by sethvargo** [comment]
Hi @wwalker 

How many instances of Consul Template are you running?

**Comment by wwalker** [comment]
One on each of two machines

However; in config.go around line 201 in the bottom of Merge(), it appears that the templates get entered multiply from the call at line 367 of cli.go in setup() (all from the v0.12.2 tag) 

Am I misreading this?

**Comment by wwalker** [comment]
My pull request #537 appears to solve the deduplication of ConfigTemplates during Merge() (ignoring the apparent race condition I bring to the table), but it does not stop the excessive requests.  The number of open TCP connections remains fairly low (2000 versus 10,000 before) but the number of requests to the vault is even higher (up to 20 requests _per_variable_ per second now rather than 40 per second total previously).

It appears this one is beyond me providing a quick fix for....
