### ISSUE TITLE
document available template values from API functions

### ISSUE THREAD

**Issue by chuckyz** [hashicorp/consul-template#536]
Hello,

As an example from current documentation:

```
The function returns a []*HealthService struct which can be used for ranging in a template:
```

Would be helpful if it instead read like

```
The function returns a []*HealthService struct (link to HealthService possible values in documentation) which can be used for ranging in a template:
```

Then that link would be something like

# Structs
### HealthService (from `service`)
```
Node           string
NodeAddress    string
Address        string
ID             string
Name           string
Tags           ServiceTags
Checks         (link to HealthCheck)
Status         string
Port           uint64
```

### HealthCheck (from `service.Checks`)
```
...
```

### NodeDetail (from `node`)
```
...
```

### CatalogNode (from `nodes`)
```
...
```

etc...

I think some of my (from) statements are incorrect, but if this was right in the documentation it might save some (including myself) some time.  At least on a 'service learning cost' level.

**Comment by sethvargo** [comment]
Hi @chuckyz 

As you can see from the earlier issue, the documentation can easily become out of date with the dependencies themselves. As such, it's easier if you just go into the `dependency/` folder and look at the structs themselves for the proper fields. I don't think it makes sense to document every possible struct field.
