### ISSUE TITLE
Variable not set in a range

### ISSUE THREAD

**Issue by deuch** [hashicorp/consul-template#538]
Hello,

I've tried this code : 
```

{{ $tagContext := "" }}
{{ $currentFqdn := "" }}

{{ range $tag, $services := service "web" | byTag }}
{{ $fqdn :=  index ($tag | split "/") 0}}
FQDN {{ $fqdn}}
currentFdqn {{$currentFqdn}} /* Always empty */
{{ if (ne $fqdn $currentFqdn) }}
 server {
  listen 80 default_server;
  serverName {{ $fqdn }};
{{end}}
 {{if $tag | regexMatch "^([a-zA-Z0-9]?.)*/[a-zA-Z0-9]"}}
    {{ $tagContext := index ($tag | split "/") 1 }}
    location /{{ $tagContext }}/ {
    proxy_pass http://{{ $tag }}/;{{else}}
    location /
    proxy_pass http://{{ $fqdn }}; {{end}}
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
 {{ $currentFqdn := index ($tag | split "/") 0 }}
currentFdqn {{$currentFqdn}} /* Properly set */
}
{{ end }}
```

The aim is to keep the previous fqdn value read in the range loop in a currentFqdn value to be able to compare it to the next value. I can set the currentFqdn at the end, but the value is wiped out in the next loop, so it's alway set to "".

Is it a multipass issue ? Is it even possible to do that with consul-template and go-template ? Thanks !

**Comment by sethvargo** [comment]
Hi @deuch 

Unfortunately this is not possible with Go's templating language. There is no way to set a variable outside of a range and then update it within the range. Unfortunately there is nothing Consul Template can do in this case. I would recommend opening an issue on the Go project, but I _think_ one already exists for this use case (although google is failing me). Thanks and sorry! :smile:
