### ISSUE TITLE
Get a .count() for objects returned by range

### ISSUE THREAD

**Issue by krjensen** [hashicorp/consul-template#540]
Hi,

Let's say I have 3 nodes in consul with the same service but one of the is "unhealthy", now what I need is to return the count() of the rage of healthy nodes so  in this case 2?

I already use "rage" to get nodes out, but i also need the total count another place in my config.

**Comment by sethvargo** [comment]
Hi @krjensen 

You can use the `len` function: https://golang.org/pkg/text/template/

**Comment by krjensen** [comment]
I still don't get how I use this with a range
It works fine with `{{len service "escl1"}}`

```
{{range service "escl1"}}{{$node:=.Node}}{{ if .Tags | contains "data"}}
```

How do I use `len` on a function like this?

>

**Comment by sethvargo** [comment]
Hi @krjensen 

I'm not sure what you mean. Where are you trying to apply the `len` function there?

**Comment by krjensen** [comment]
I just want the number of nodes returned by this function
```{{range service "escl1"}}{{$node:=.Node}}{{ if .Tags | contains "data"}}```

So if there is 5 nodes in the service "escl1" with the tag "data" i want consul-template to write a "5"

**Comment by danlsgiga** [comment]
Wondering how to do this too, specially to update the count of a Nomad job to auto scale the application based on the number of registered nodes in Consul.
