### ISSUE TITLE
output a subset of services

### ISSUE THREAD

**Issue by donniev** [hashicorp/consul-template#541]
I am sure this isn't an issue of the code but of my understanding of it. I want to loop over the services but only output results for a subset of them and I cannot figure out the syntax. In pseudo code:
```
{{range services}}
  {{if .Name in ("consul","nginx","socketserver") }}
       do something
  }}
}}
```
Can you help me out with the syntax?

**Comment by sethvargo** [comment]
Hi @donniev 

Thank you for reaching out. Unfortunately there is no way to do this with Go's template language. You need to use deeply nested `or` + `eq` statements instead: https://golang.org/pkg/text/template/
