### ISSUE TITLE
Empty file if no services

### ISSUE THREAD

**Issue by MrMMorris** [hashicorp/consul-template#547]
I am using `consul-template` for nginx site config creation and I am trying to figure out a way to have it either a) not create a site.conf or b) create an empty site.conf if there are no services matching.

What I currently have will fill `upstream` with 1 to n services, but if there are no "consul" services, then upstream is empty and nginx complains: 
```
upstream consul.frontend {
  least_conn;
{{range service "consul"}}  server {{.Address}}:80 max_fails=3 fail_timeout=60 weight=1;
{{end}}}

server {
  server_name consul.example.org;
  access_log /var/log/nginx/consul_access.log;
  error_log /var/log/nginx/consul_error.log;

  location / {
    proxy_pass http://consul.frontend;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    if ($http_x_forwarded_proto != "https") {
      rewrite ^(.*)$ https://$server_name$1 permanent;
    }
  }
}
```

How would I modify this so that it works for 0 to n services?

**Comment by sethvargo** [comment]
Hi @MrMMorris 

You can wrap the `upstream` block in something like 

```liquid
{{ if service "consul" }} ... {{ end }}
```

Please see the golang text/template documentation for more details: https://golang.org/pkg/text/template/

**Comment by MrMMorris** [comment]
amazing as always @sethvargo. Thanks
