### ISSUE TITLE
The perms options is confusing

### ISSUE THREAD

**Issue by jaxxstorm** [hashicorp/consul-template#548]
In the template documentation, it says to set perms up like so:
```
template {
  source = "/path/on/disk/to/template"
  destination = "/path/on/disk/where/template/will/render"
  command = "optional command to run when the template is updated"
  command_timeout = "60s"
  perms = 0600
  backup = true
}
```

So I did just that and configured my config file like so:

```
{
    "template": [
        {
            "backup": true,
            "destination": "/tmp/haproxy-test.cfg.1",
            "perms": 0600,
            "source": "/etc/consul-template/templates/sensu.ctmpl"
        }
    ]
}
```

When I went to start consul-template, I got the following error:

```
Consul Template returned errors:
config: walk error: error decoding config at "/etc/consul-template/config/watch_sensu_1.json": 6:25: numbers cannot start with 0
```

Fixing the json to remove the zero made it work.

Can we either update the docs or explain why I'm being dim?

**Comment by sethvargo** [comment]
Hi @jaxxstorm 

Are you writing your configuration file as JSON or HCL? The HCL parser will automatically detect the incoming type as a string and convert. The JSON parser is not that smart, so you have to quote the value.

**Comment by jaxxstorm** [comment]
Ah, that explains it. Yeah it's in JSON, so it has to be a string rather than integer? I think definitely think the documentation needs to be updated for this

**Comment by jaxxstorm** [comment]
I updated my config to look like this:

```
"template": [
        {
            "command": "/sbin/service haproxy restart",
            "destination": "/etc/haproxy.conf.d/sensu.cfg",
            "perms": "0644",
            "source": "/etc/consul-template/templates/sensu.ctmpl"
        }
    ]
```

And I still get an error:

```
config: walk error: 1 error(s) occurred:

* 1 error(s) decoding:

* 'template[0].perms' expected type 'os.FileMode', got unconvertible type 'string'
```

How exactly is this meant to work?

**Comment by mrbobbytables** [comment]
+1 Encountered the same issue today when attempting to use json template configs.
