### ISSUE TITLE
toYAML not outputting arrays in the proper format

### ISSUE THREAD

**Issue by dcparker88** [hashicorp/consul-template#554]
I am trying to generate a yaml file using toYAML and key=value pairs in consul. Everything is working great until it gets to the array. It is treating the array just like a string and not formatting it properly. 

There may be some things I can do to workaround but I am hoping this is something simple with how I am loading the data.

Here is the key=value I am uploading to consul:
`data_file_directories=["/data1","/data2"]`

Here is how the yaml is created with consul-template:
`data_file_directories: '["/data1","/data2"]'`

What I would expect is
```yaml
data_file_directories: 
  - /data1
  - /data2
```

Here is what is in my consul-template:
`{{ tree "my/tree/location" | explode | toYAML }}`

Is there a way to tell consul to treat it as an array, or is just the way I am uploading the value?

Let me know if there is any other info you want to see. Thanks!

**Comment by sethvargo** [comment]
Hi @dcparker88 

Thank you for opening an issue. We use the "official" YAML library: https://gopkg.in/yaml.v2. Could you please open an issue on that upstream? There's not much we can do here because we just call yaml.marshall and the upstream handles it :frowning:

**Comment by dcparker88** [comment]
sure, thanks. I can do that.

**Comment by muradm** [comment]
Hi @sethvargo, I don't think that it is an issue with parser. Looks like explode takes a value as plain string, and has no way to inform marshaler that specific value is actually an array. I.e. marshaler looks at value and sees type of string and behaves accordingly. Same problem is with toJSON as well.

toJSON:
`"paths": "[\"/srv/log/syslog\",\"other\"]"`

toYAML:
`paths: '["/srv/log/syslog","other"]'`

**Comment by 6nazfimmeq** [comment]
I have run into this same issue.  Wouldn't this issue be considered a bug?  

data_file_directories: '["/data1","/data2"]'

should be rendered as proper YAML like:

data_file_directories: 
  - /data1
  - /data2
