### ISSUE TITLE
.tar.gz files at releases.hashicorp.com

### ISSUE THREAD

**Issue by hamzakc** [hashicorp/consul-template#556]
Hi.

I am not sure where to raise this, so I apologize if this is the wrong place. 

First of all I would like to thank you for your efforts for developing consul-template.  We use it heavily and find it a very flexible and awesome tool to use with consul.

In terms of releases. I wanted to suggest making the .tar.gz files available at https://releases.hashicorp.com/ as opposed to only the .zip files.

The simple reason for this is, when we are downloading files in a Dockerfile the container then must have unzip installed.  This leads to a lot of cleaning up to do if you want small images.

Thanks.

Kind Regards
Hamza

**Comment by sethvargo** [comment]
Hi Hamza,

We publish all our binaries as zip files. You can read more about the motivation here: https://www.hashicorp.com/blog/hashicorp-and-fastly.html.

We will also be publishing official docker images for all our projects this year, so building your own images will become unnecessary.
