### ISSUE TITLE
whitespace removal not working

### ISSUE THREAD

**Issue by graphex** [hashicorp/consul-template#558]
In the "Text and Spaces" section of https://golang.org/pkg/text/template/#pkg-overview it mentions you can use "{{- " or " -}}" to remove the leading/trailing whitespace characters from the document.
When I attempt to utilize that functionality, however I get:
```
Consul Template returned errors:
template: template: mytemplate.cfg.ctmpl:1: illegal number syntax: "-"
```

**Comment by sethvargo** [comment]
Hi @graphex 

Thank you for opening an issue. Can you please share your complete template and Consul Template version? That functionality is new in Go 1.6, so only Consul Template 0.12.2+ will have it.

**Comment by graphex** [comment]
Ah, I am using 0.12.0. I did not realize that functionality was so new or that 0.12.2 was out.
My test was a simple:
```
{{ "test" -}}
line2
```

I will retest soon and report if that version bump makes that new feature work.

**Comment by sethvargo** [comment]
Actually, I think I lied. I think it's only 0.13.0 that's gonna have it.

**Comment by jippi** [comment]
@sethvargo any eta on `0.13` ?  I'm stuck with the same issue :(

**Comment by jippi** [comment]
Upgrading to 0.13.0 made the whitespace removal work, however, template logic that worked in 0.12.2 now fails

example

``
{{ $number_of_pools := key_or_default "/apps/demo-app/php-fpm/pools" "1" | parseInt }}
``

yields a 

```
Consul Template returned errors:
config: walk error: error decoding config at "/etc/consul-template/source/frontend/nginx.ctmpl": At 5:21: illegal char
```

**Comment by sethvargo** [comment]
I just confirmed this is working as expected in Consul Template 0.13.0. Please upgrade to that version or later, thanks!

**Comment by abcfy2** [comment]
Oh, thanks. I've met the same issue. I just follow the [releases](https://github.com/hashicorp/consul-template/releases) page, and find `v0.12.1` is the latest. So I think this version will be the latest stable version. But I go to the https://releases.hashicorp.com/consul-template/ , and I find that in fact, the `0.14.0` is the latest. Why not `0.14.0` is not appeared in the github releases page? This could be confused someone.
