### ISSUE TITLE
inconsistent behavior from `wait` param

### ISSUE THREAD

**Issue by jippi** [hashicorp/consul-template#560]
from cli `-wait 5` works

but in a `hcl` config `wait = 5` yields `* 'wait' expected a map, got 'int'`

`wait = "5s"` works fine though

**Comment by sethvargo** [comment]
Hi @jippi 

This is because, on the CLI wait is parsed whereas in the config it is assumed you specify the minimum and maximum:

```
wait {
  min = "5s"
  max = "10s"
}
```

The CLI is just shorthand for that. The same is true for templates:

```
$ consul-template -template="input:output:command"
```

is actually this config:

```
template {
  source = "input"
  destination = "output"
  command = "command"
}
```

**Comment by jippi** [comment]
@sethvargo okay, caught me by surprise - maybe that could be more clear in the docs?
