### ISSUE TITLE
constant refresh of template when using {{timestamp}}

### ISSUE THREAD

**Issue by jippi** [hashicorp/consul-template#561]
When a template uses `{{timestamp}}` it seems to rewrite the file on a interval, even though there are 0 external consul changes to rewrite.

Removing `{{timestamp}}` from the template file, stops the constant re-writing and reloading of a service.

Shouldn't `{{timestamp}}` be ignored when checking for changes required to write out the template?

**Comment by sethvargo** [comment]
Hi @jippi 

Can you please share your complete template? I am not seeing that same behavior in my testing.

**Comment by sethvargo** [comment]
I tried a bunch of different templates today, and I am unable to get this to reproduce. The value of `timestamp` will change if any of the upstream dependencies change, but the templates are only rendered if upstream dependencies change. You can turn on debug logging to see which dependency is flapping and causing the file rewrite. Thanks! :smile:

**Comment by jippi** [comment]
@sethvargo sorry, ended up in bed with flu, will try to reproduce when I'm back into good health! :)
