### ISSUE TITLE
Run command without template?

### ISSUE THREAD

**Issue by cgcgbcbc** [hashicorp/consul-template#562]
can I omit the parameter of template path and output path? e.g. `::command`

**Comment by jippi** [comment]
What is the use case then? sounds like you need https://github.com/hashicorp/envconsul instead :)

**Comment by cgcgbcbc** [comment]
> What is the use case then?

I need to reload nginx when container ip changed, since I use consul dns record in nginx upstream config ( I'm too lazy to rewrite the nginx config  with template)

**Comment by cgcgbcbc** [comment]
Aha, seems that I should simply use consul watch.

**Comment by cgcgbcbc** [comment]
seems that in my case I should use this template so every time a service's address changed or service list changed, it will reload nginx
```
{{range services}}
{{range service .Name}}
  {{.Address}}
{{end}}{{end}}
```
