### ISSUE TITLE
Consul-template not update file when data in Vault is updated 

### ISSUE THREAD

**Issue by minhchuduc** [hashicorp/consul-template#563]
I have a template file like this:
```
...
{{ with $secret := vault "secret/hulk-zone/rabbit" }}
rabbit_userid = {{ key "hulk-zone/rabbit/userid" }}
rabbit_password = {{ $secret.Data.password }} {{end}}
```
Everything works fine. But:
- when i change value of "hulk-zone/rabbit/userid" in Consul, this file is updated.
- when i change value of "secret/hulk-zone/rabbit" in Vault (by `vault write secret/hulk-zone/rabbit password=New_rabbit_password`), this file is NOT updated. The only way i know to make change to "rabbit_password" field is restart consul-template. 

It is a bug or it is a not-yet-implemented feature? 
How i can tell consul-template update when data in Vault change?

**Comment by sethvargo** [comment]
This is the expected behavior. Vault does not support blocking queries to watch for secret updates.

**Comment by minhchuduc** [comment]
It will be great if consul-template can be configured to periodically re-query Vault and update file if the Vault's data changed.

**Comment by sethvargo** [comment]
Hi @minhchuduc 

It is configured that way. Consul Template will pull the data from Vault at half the lease duration of the secret. So if you set a lease duration of 5min, CT will attempt to renew the secret every 2m30s, and if renewal fails, it will attempt to re-read the secret.

**Comment by blalor** [comment]
That obviously only works if the secret *has* a lease.  I believe non-dynamic secrets generally don’t; is that correct?

**Comment by sethvargo** [comment]
Everything has a lease, sometimes that lease is not enforced (like the generic secret backend). Nonetheless, the result of the lease value is consumed and renewal is still attempted.

**Comment by gvenka008c** [comment]
@sethvargo I have configured vault to use consul as the backend. When I write any data using Vault I don't see it in Consul. How can i ensure that Vault is talking to Consul and the data is getting stored in Consul?

```
backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
}

listener "tcp" {
  address = "127.0.0.1:8200"
  tls_disable = 1
}

```
