### ISSUE TITLE
More than one output file from one template

### ISSUE THREAD

**Issue by KrzysztofZalasa** [hashicorp/consul-template#567]
Current features of consul-template works fine in case, when third party software allows one big file for configuration of many services ex. nginx's vhosts. In other case, ex. for SOLR's cores it's not possible to use consul template without creating template file for each service. It's to possible to execute one template with output to many places (duplicated _template_ option) but it will generate just copies of single file in many places.

My use case: 
* I would like to generate configuration for services in SOLR dynamically, based only on consul's KV
* structure in consul's KV
```
solr/cores
solr/cores/core1
solr/cores/core1/propery1
solr/cores/core1/propery2
solr/cores/core2a
solr/cores/core2/propery1
solr/cores/core3/propery2
```
When I add now entry in _solr/cores_ it shall just create new configuration file for new core. I believe this feature may be reused in non SOLR context.

My current workaround is very complex - consul template creates config files for .. consul template and use command to for cascade execution and dynamic templates. It sounds weird, I may share it.

Maybe it would be good idea to create new feature ex. template_multi which may take ex. range function as param and create new config foreach entry, key may be passed to template. 

```
template_multi {
  loop="range $key, $pairs := tree "solr/cores" | byKey"
  source = "core.properties.tmpl"
  destination = "{{$key}}/config.properties"
}
```

```
{{range ls $key}}{{.Key}}={{.Value}}
{{end}}
```

Is it OK for you, or is there any simple way?

**Comment by sethvargo** [comment]
Hi @KrzysztofZalasa 

There are closed issues where I explain this further, but we have no plans to allow Consul KV data to determine the list of files that are rendered to disk. You might be interested in something like consulate if that's your desired use case; otherwise, using Consul Template to call Consul Template is probably your best bet. Thanks! :smile:
