### ISSUE TITLE
Issue using address in template and consul-template returns serviceaddress

### ISSUE THREAD

**Issue by mlopeztn** [hashicorp/consul-template#573]
I have a consul-template which does the following:

```
{{range services}}
  {{range service .Name}}
    service node {{.Node}} {
      address {{.Address}}
    }
  {{end}}
{{end}}
```

I am expecting the following with the IP address:

```
service node Node1 {
  address 192.168.1.1
}
```

I am getting the following with the service address:

```
service node Node1 {
  address https://192.169.1.1/service/api
}
```

I think this is an issue.  Can someone evaluate and please let me know?

Thanks!

**Comment by sethvargo** [comment]
Hi @mlopeztn 

How are you registering services in Consul? What does Consul's API return? I think this is an issue with the way you are registering services, not Consul Template.

**Comment by mlopeztn** [comment]
Seth,

Do you have 30 mins where we can discuss?

Thanks!

**Comment by slackpad** [comment]
Hi @mlopeztn it looks like somehow you are registering services with a URL for the address field. Are you using the [Catalog API](https://www.consul.io/docs/agent/http/catalog.html#catalog_service) to register them manually? Typically you use the [Agent API](https://www.consul.io/docs/agent/http/agent.html#agent_service_register) or [config files on the agent](https://www.consul.io/docs/agent/services.html) to register them and the agent will fill in the proper address when it registers them with the Consul servers.

I don't think this is a consul-template issue - it is just printing what's registered with Consul.

**Comment by mlopeztn** [comment]
I am using Consul agent to register my API's on the API server.  Here is an example of what is returned from consul from a web browser.

http://192.168.1.1:8500/v1/catalog/service/myservice

[{"Node":"server01","Address":"192.168.1.10","ServiceID":"192.168.1.10-80-/-api/-myservice/-api","ServiceName":"myservice","ServiceTags":["v1"],"ServiceAddress":"http://192.168.1.10/api/myservice/api","ServicePort":0,"ServiceEnableTagOverride":false,"CreateIndex":590840,"ModifyIndex":590840}]

Here is my consul-template

{{range services}}
  {{range service .Name}}
    service {{.Name | toLower}} {
      description "Updated {{timestamp}} by discovery service."
      members {
        {.Name}}:{{.Port}} {
          address {{.Address}}
        }
      }
    }
  {{end}}
{{end}}

Here is the output from the template

   service myservice {
      description "Updated 2016-03-09T22:50:56Z by discovery service."
      members {
        myservice:0 {
          address http://192.168.1.10/api/myservice/api
        }
      }
    }

In the address field in the template I am getting the ServiceAddress instead of the Address.  In searching the Internet, others are having the same issue.  Do you have any idea what is going on?  How can I address and get the address only in my consul-template output?

Thanks!

**Comment by slackpad** [comment]
Hi @mlopeztn if you supply a service-specific address when you register the service it will be used instead of the agent's address. If you re-register "myservice" and leave the `Address` field blank it should render as you expect in the template as `192.168.1.10`.

**Comment by mlopeztn** [comment]
So are address and serviceaddress fields not independent of each other?  Does not make much sense why you cannot use both fields independently.   Does anyone know why this is the case here.   I have found others trying to use the product and have the same results and questions. 

Thanks!

**Comment by slackpad** [comment]
The service address field is used when you need a service-specific IP address, so it's used as an override if you don't want the IP address of the agent to be used. The meaning of this field is that it's the IP address you want returned for that service, so this would also be returned via DNS, for example. We don't give the ability for consul-template to choose which address because that's supposed to be a detail that clients don't worry about.

This field is also meant for an IP address, not a URL. If you want to store additional metadata about your service, such as which endpoint to use (`/api/myservice/api` in the example above), you can put that in the Consul KV store in a path by the service name and that can easily be retrieved using consul-template. Hope that helps!

**Comment by yuzd** [comment]
@mlopeztn  do you solve your problem？
