### ISSUE TITLE
-config directory doesn't follow symlinks

### ISSUE THREAD

**Issue by jippi** [hashicorp/consul-template#579]
when having a -config directory to scan recursively, consul-template seem to error out on symlinks

I'm getting the following error

```
config: walk error: error reading config at "/etc/consul-template/config/frontend": read /etc/consul-template/config/frontend: is a directory
```

a `ls`

```
root @ local.bownty.net [ /etc/consul-template/config ] [ 15:49:26 ]  (master *%)
-> ls -al
4 -rw-r--r-- 1 root root   62 Mar  4 14:38 config.hcl
4 lrwxrwxrwx 1 root root   68 Mar 15 15:46 frontend -> /var/www/frontend/htdocs/_infrastructure/dist/consul-template/config
```

a `ls` on the symlink

```
root @ local.bownty.net [ /etc/consul-template/config ] [ 15:49:27 ]  (master *%)
-> ll /var/www/frontend/htdocs/_infrastructure/dist/consul-template/config
total 20
4 drwxr-xr-x 2 root root 4096 Mar 15 15:27 .
4 drwxr-xr-x 4 root root 4096 Mar 15 15:27 ..
4 -rw-r--r-- 1 root root  226 Mar 15 15:46 nginx.hcl
4 -rw-r--r-- 1 root root  217 Mar 15 15:46 php-fpm.hcl
4 -rw-r--r-- 1 root root  219 Mar 15 15:46 supervisor.hcl
```

it works perfectly if i remove the symlink and move the folders inside the directory 

command executed:

```
/usr/local/bin/consul-template -config /etc/consul-template/config/
```

**Comment by sethvargo** [comment]
Hi @jippi 

I did some digging into this issue, and it appears to be a core issue in Go (https://github.com/golang/go/issues/4759). Go's filepath.Walk function does not follow symlinks because it's difficult to get correct and avoid infinite loops.

**Comment by sethvargo** [comment]
I spent some time thinking (and playing with potential fixes), and I think we should take a hint from the core team here (who are much smarter than me). There doesn't seem to be a good and safe way to follow directory symlinks. I'm going to update the documentation to make this clearer.
