### ISSUE TITLE
Support go-template newline suppression (e.g. "{{-SPACE")

### ISSUE THREAD

**Issue by rtoma** [hashicorp/consul-template#590]
RE: v0.11.1

In an attempt to make my consul templates better human-readable I browsed the references go-template docs (https://golang.org/pkg/text/template/) and found this:

> However, to aid in formatting template source code, if an action's left delimiter (by default "{{") is followed immediately by a minus sign and ASCII space character ("{{- "), all trailing white space is trimmed from the immediately preceding text. Similarly, if the right delimiter ("}}") is preceded by a space and minus sign (" -}}"), all leading white space is trimmed from the immediately following text.

When I use `{{- ` in my templates this results in:
```
consul-template[9584]: template: template: template-haproxy.ctmpl:54: illegal number syntax: "-"
```

Please advice (or fix).

**Comment by sethvargo** [comment]
Hi @rtoma 

That change in golang's text/template package came in Go 1.6. CT 0.13+ includes this new version. Please upgrade to get this functionality.

**Comment by rtoma** [comment]
Thanks for the super fast reply. I will upgrade.
