### ISSUE TITLE
Sending SIGHUP does causes consul-template to run out of file descriptors

### ISSUE THREAD

**Issue by benpillet** [hashicorp/consul-template#591]
I put a kill -HUP in a while loop like this:
`while [ 1 ]; do pkill -HUP -f consul-template; sleep 1; done`
and it hit an error with too many open files.  I suspect it's not letting go of something on the reconfig.  Version is 0.11.0.  Please let me know if you need more details.

**Comment by jippi** [comment]
@benpillet can you try 0.14.0 ? :)

**Comment by benpillet** [comment]
Just upgraded to 0.14.0 and seeing same issue.  Some more details.  The symptom doesn't show up if there aren't any templates.  I had it configured with no templates and it held steady at about 18 file descriptors.  When I added a template and sent SIGHUP, the file descriptors incremented by about 25 on each SIGHUP.

**Comment by sethvargo** [comment]
Hi @benpillet 

Can you please share your CT config/command as well as the CT templates you're using?

**Comment by benpillet** [comment]
Run command from puppet module: `/usr/local/bin/consul-template -config /etc/consul-template/config`

/etc/consul-template/config/config.json:
`consul = "localhost:8500"
token = ""
retry = "10s"

log_level = "debug"
template {
  source = "/etc/consul-template/clusterit.ctmpl"
  destination = "/etc/clusterit.consul"
  command = "true"
}
`

and template:
`# clusterit-consul.conf

# GROUPS

{{range services}}GROUP:role-{{.Name}}{{range service .Name}}
{{.Node}} # {{.Address}}{{end}}

{{end}}
`

**Comment by sethvargo** [comment]
Hi @benpillet 

Can you share the output of running the command in debug mode as a GitHub gist after you send it sighup a few times?

**Comment by benpillet** [comment]
https://gist.github.com/benpillet/c8520db0e3eb6a299ad0
The TCP connection lines from lsof are the ones that increase the file descriptor count.
