### ISSUE TITLE
Vault TLS Missing Private Key?

### ISSUE THREAD

**Issue by JoeOrtiz** [hashicorp/consul-template#594]
I keep getting 

runner: crypto/tls: found a certificate rather than a key in the PEM for the private keyF0325 

This is after I applied the cert and key into the cert variable.

If I just have the cert in the cert file:

crypto/tls: found a certificate rather than a key in the PEM for the private key

So there is no winning here :-/

**Comment by sethvargo** [comment]
Hi @JoeOrtiz 

Thank you for opening an issue. Unfortunately I'm having a hard time understanding how you've arrived in this situation, or your desired behavior. Could you please share your Consul Template template, the command your invoking, any configuration files, and the output of CT with the `debug` flag? Thanks! :smile:

**Comment by JoeOrtiz** [comment]
`consul = "localhost:8500"

max_stale = "10m"
log_level = "warn"

vault {
  address = "https://vault.service.consul:8200"
  renew   = true
  ssl {
    enabled = true
    verify  = true
    cert    = "/etc/certs/cert.cert"
    ca_cert = "/etc/certs/cert.ca"
  }
}

ssl {
  enabled = true
  verify  = true
  cert    = "/etc/certs/cert.cert"
  ca_cert = "/etc/certs/cert.ca"
  key = "/etc/certs/cert.key"
}

deduplicate {
  enabled = true
}

template {
  source          = "/etc/consul-templates/auth_config.ctmpl"
  destination     = "/auth_config.yml"
  perms           = 0600
  backup          = true
}`

In debug:

`2016/03/25 22:29:59 [INFO] (runner) creating consul/api client
2016/03/25 22:29:59 [DEBUG] (runner) setting consul address to localhost:8500
2016/03/25 22:29:59 [DEBUG] (runner) setting consul token
2016/03/25 22:29:59 [DEBUG] (runner) enabling consul SSL
2016/03/25 22:29:59 [INFO] (runner) creating vault/api client
2016/03/25 22:29:59 [DEBUG] (runner) setting vault address to https://vault.service.consul:8200
2016/03/25 22:29:59 [DEBUG] (runner) enabling vault SSL
Consul Template returned errors:
runner: crypto/tls: failed to find certificate PEM data in certificate input, but did find a private key; PEM inputs may have been switched/etc/certs #`

But the above is when I tried making the cert for Vault have both the private and cert, since if it just has the cert I get the `runner: crypto/tls: found a certificate rather than a key in the PEM for the private keyF0325`

Error.

**Comment by sethvargo** [comment]
Hi @JoeOrtiz 

Thank you for your reply. I'm still having trouble understanding the steps you took to arrive here. Let's take a step back - what are you trying to achieve? How did you generate these certificates? Are these certificates for connecting to the Vault server or the Consul agent?

**Comment by JoeOrtiz** [comment]
Connecting to the vault server, generated using the vault PKI.

If I set it to verify  = false, it works fine. I know the certificates work fine, as well the same certificates consul uses to connect to itself.

But somehow just for the vault stanza, I can't use the same certs.

**Comment by sean-** [comment]
@JoeOrtiz can you try a few things real quick?  Please don't past the output, but can you compare the outputs of the following two commands?

```sh
$ openssl x509 -noout -text -in /etc/certs/cert.cert
$ openssl rsa -noout -text -in /etc/certs/cert.key
```

The debug log line is interesting and I want to see this resolved first: `runner: crypto/tls: failed to find certificate PEM data in certificate input, but did find a private key; PEM inputs may have been switched/etc/certs #`

It looks like the cert file contains the key.  ?

**Comment by sethvargo** [comment]
Hi @JoeOrtiz 

Did you have a chance to look at Sean's comment?

**Comment by sethvargo** [comment]
Hi there,

I'm going to close this due to inactivity. If this is still an issue, please comment here or open a new issue. Thanks!

**Comment by scareything** [comment]
I encountered a similar error today. In my case, the error was caused by setting VAULT_CAPATH to the PEM file of my vault server's signing CA, when I should've been setting VAULT_CACERT.

I'm not sure if it is the intended behavior, but I wouldn't expect the value of VAULT_CAPATH to end up in the _cert_ field of consul-template's vault ssl configuration object:

```
$ export VAULT_ADDR=https://192.168.99.100:8200
$ export VAULT_CAPATH=/tmp/rootca.pem
$ export VAULT_TOKEN=12cd73a5-b375-88f4-535a-c4d8e802b6c8
consul-template -log-level=debug
2016/11/09 20:45:20.091564 [INFO] consul-template v0.16.0
2016/11/09 20:45:20.092103 [INFO] (runner) creating new runner (dry: false, once: false)
2016/11/09 20:45:20.092590 [DEBUG] (runner) final config (tokens suppressed):

{
  "Path": "",
  "Consul": "",
  "Token": "",
  "ReloadSignal": 1,
  "DumpSignal": 3,
  "KillSignal": 2,
  "Auth": {
    "Enabled": false,
    "Username": "",
    "Password": ""
  },
  "Vault": {
    "Address": "https://192.168.99.100:8200",
    "UnwrapToken": false,
    "RenewToken": true,
    "SSL": {
      "Enabled": true,
      "Verify": true,
      "Cert": "/tmp/rootca.pem",
      "Key": "",
      "CaCert": ""
    }
  },
  "SSL": {
    "Enabled": false,
    "Verify": true,
    "Cert": "",
    "Key": "",
    "CaCert": ""
  },
  "Syslog": {
    "Enabled": false,
    "Facility": "LOCAL0"
  },
  "Exec": {
    "Command": "",
    "Splay": 0,
    "ReloadSignal": null,
    "KillSignal": 15,
    "KillTimeout": 30000000000
  },
  "MaxStale": 1000000000,
  "ConfigTemplates": [],
  "Retry": 5000000000,
  "Wait": {
    "min": 0,
    "max": 0
  },
  "PidFile": "",
  "LogLevel": "debug",
  "Deduplicate": {
    "Enabled": false,
    "Prefix": "consul-template/dedup/",
    "TTL": 15000000000
  }
}

2016/11/09 20:45:20.097609 [INFO] (clients) creating consul/api client
2016/11/09 20:45:20.097736 [DEBUG] (clients) setting consul address to "192.168.99.100:8500"
2016/11/09 20:45:20.097752 [INFO] (clients) creating vault/api client
2016/11/09 20:45:20.097765 [DEBUG] (clients) setting vault address to "https://192.168.99.100:8200"
2016/11/09 20:45:20.097776 [DEBUG] (clients) enabling vault SSL
Consul Template returned errors:
runner: runner: client set: vault: tls: found a certificate rather than a key in the PEM for the private key
```
