### ISSUE TITLE
alternative backends from consul

### ISSUE THREAD

**Issue by jippi** [hashicorp/consul-template#598]
Hi!

Would be pretty amazing, to have the full support of the amazing thight consul integration AND some pluggable backends, ala Rancher / AWS ( https://github.com/kelseyhightower/confd/blob/master/backends/rancher/client.go ) 

It may be out of scope, but confd lack some of the killer-features from CT; but CT lack some more flexible backend calls (e.g. Rancher / template files etc)

Could it maybe be done using Plugins ?

**Comment by sethvargo** [comment]
Hi @jippi 

Thank you for opening an issue. You are correct that this is a bit outside the scope of Consul Template. Sorry! :frowning:

**Comment by jippi** [comment]
@sethvargo could it be done using a plugin?  e.g. `{{ "my/odd/key" | plugin rancher-metadata }}` 

how often would it execute the code? every ~30s like most other things or?
