### ISSUE TITLE
consul-template does not resume after computer awakes

### ISSUE THREAD

**Issue by JohanTan** [hashicorp/consul-template#600]
I run consul-template on my local dev environment to sync with production service lists in Vagrant. Every time when I put laptop to sleep and bring it back later, the instance of consul-template running in Vagrant will seize updating (from the upstart log). strace is giving the following output:
```
root@local:/home/vagrant# strace -ff -p 22117
Process 22117 attached with 8 threads
[pid 22125] futex(0xc82015c108, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 22124] futex(0xc8200f1108, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 22123] epoll_wait(4,  <unfinished ...>
[pid 22122] futex(0xc8200f0108, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 22121] futex(0xc820023108, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 22119] futex(0xc5cd00, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 22118] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid 22118] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid 22117] futex(0xc40568, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 22118] <... restart_syscall resumed> ) = -1 ETIMEDOUT (Connection timed out)
[pid 22118] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
[pid 22118] futex(0xc3f9b0, FUTEX_WAIT, 0, {60, 0}
```
Any ideas on why this happens?

**Comment by sethvargo** [comment]
Hey @JohanTan 

Thank you for opening an issue. I'll be totally honest, I have no idea why this is happening. It's unclear to me if this is an issue in:

1. Consul Template
2. Vagrant
3. Virtualbox
4. Golang

I will need a bit more information to help debug this. First, can you run CT in debug mode and put the logs in a gist when this happens? Can you try to reproduce the issue outside of Vagrant/vbox?

**Comment by JohanTan** [comment]
Thanks for the quick reply! By running CT in debug mode do you mean changing the verbosity of the log levels?

**Comment by sethvargo** [comment]
@JohanTan yea - if you specify `-log-level=debug` when running or `log_level = "debug"` in a config file.

**Comment by JohanTan** [comment]
Unfortunately DEBUG logs don't provide additional details. Still nothing got logged after I brought laptop back from sleep.

**Comment by sethvargo** [comment]
Hi @JohanTan 

Can you inspect the process table and see if CT is running after the VM is resumed? Maybe test this out with another application and see how it behaves?

**Comment by JohanTan** [comment]
Seth:

Believe it's been running before and after the wakeup. The strace results I posted were taken after wakeup. I have entire LAMP stack running in Vagrant and all of them seem to behave consistently before & after wakeup. Let me know if you need more information from me.

**Comment by sethvargo** [comment]
Hi @JohanTan 

Unfortunately I'm not familiar enough with operating systems and OSes at this layer. I just tried to reproduce this using Vagrant, but I was unable to do so. As I said before, this could be an issue anywhere in the stack, and the use case is very much an edge case and doesn't seem to be affecting many users. As such, I don't think it's worth spending time debugging the issue that very well may lie at the virtualization layer, the OS, or the programming language itself. I understand this may be annoying to you. If you do find this to be a bug in Consul Template itself, I'm definitely happy to revisit the issue and fix the problem. Thanks! :smile:
