### ISSUE TITLE
no poll rate limiting, consul-template ddos's consul

### ISSUE THREAD

**Issue by pmbauer** [hashicorp/consul-template#601]
https://github.com/hashicorp/consul-template/blob/5b955a8999a29b01e301cc9b9ac7c4b7b714685f/watch/view.go#L64

1. For every dependency in a template, CT kicks off a go routine that continuously polls consul as fast as it can.  The only time it ever backs off is if there's an error.  for example
`error fetching: Get http://127.0.0.1:8500/v1/health/service/[...]: dial tcp 127.0.0.1:8500: connect: cannot assign requested address`

2. Then the CT go routine waits the configured retry period (no exponential backoff, note the RetryFunc always returns the retry constant)
https://github.com/hashicorp/consul-template/blob/5b955a8999a29b01e301cc9b9ac7c4b7b714685f/runner.go#L939
https://github.com/hashicorp/consul-template/blob/5b955a8999a29b01e301cc9b9ac7c4b7b714685f/watch/view.go#L60

3. and then proceeds to poll the endpoint again as fast as it can

This happens for every single dependency, DDOSing consul.  For our system, this happens well before the dependency count warning.

consul-template needs a configured poll rate and exponential backoff on network failures.

**Comment by pmbauer** [comment]
p.s.
we are working on a patch for this since it's impacting our system; will send a pull request.  Thanks.

**Comment by sethvargo** [comment]
Hi @pmbauer 

Thank you for opening an issue. I'll try to address your issues as best I can:

> 1. For every dependency in a template, CT kicks off a go routine that continuously polls consul as fast as it can. The only time it ever backs off is if there's an error.

This is actually untrue, although it might _look_ that way in the code. The first time a request is made to Consul, it's made as quickly as possible. Future requests include the `WaitIndex` parameter which tells Consul to issue a blocking query. The result is that the dependency will hang, waiting for a response from the Consul server. The Consul server renders that HTTP request when the watcher changes; this is what allows for the edge-triggering and "real-time" behavior in Consul Template.

If data is successfully returned from the Consul server, it's considered a successful request, and CT immediately starts watching the data again while the runner performs the rendering. Consul Template does not "poll", therefore there's not a configurable "poll rate"; it issues blocking queries. 

The exponential backoff _does_ occur in the face of error, like when there's a network issue or when Consul is not available.

Could you please share your Consul Template template, config, and the output of the command in debug mode as a GitHub gist?

**Comment by pmbauer** [comment]
**I'm embarrassed I missed the blocking query bit** and I'm terribly Sorry.
Thanks for the explanation.

I would gist the consul-template and consul agent logs, but at the debug level 1 minute's worth of logs is 16MB and 4.4MB respectively.  consul-template is making ~26900 requests/min for a template that watches 82 dependencies.

Here is our template (haproxy), a 1 second sample of consul-template logs and a 10 sec sample of consul agent logs.  The agent is in client mode and consul-template is currently holds the lock for the haproxy template (dedupe mode).
https://gist.github.com/pmbauer/01212d8a17fba7be0f585018fa5dd917

We've had to bump up the `nf_conntrack_max` and `nf_contrack` hashsize locally just to sustain the network traffic consul-template is generating.

Per your explanation, the consul-template viewer only responds when consul pushes data.  So does it appear the watched services are updating that frequently? We have a few dozen pushes a day to various services, and I do know the IP addresses for those services are not changing that rapidly (docker containers, IP per container setup).

However, wrt exponential backoff, given this is what runner sets for the RetryFunc
https://github.com/hashicorp/consul-template/blob/5b955a8999a29b01e301cc9b9ac7c4b7b714685f/runner.go#L939
It doesn't appear that `currentRetry` is going to be anything other than the configured retry period
https://github.com/hashicorp/consul-template/blob/5b955a8999a29b01e301cc9b9ac7c4b7b714685f/watch/view.go#L95
...unless I'm missing something again.

Sorry for the false alarm and thanks again for your help.

**Comment by pmbauer** [comment]
thanks for rubber ducking; again @sethvargo I'm so terribly sorry I made a bogus issue and burned some of your valuable time today.  The key insight you gave was how consul is pushing updates, which led us to check into what was tickling our service entries.  tl;dr our registration daemon was resyncing too aggressively causing `ModifyIndex` to change, causing the pushes.

Thanks again.
