### ISSUE TITLE
What I am doing wrong?

### ISSUE THREAD

**Issue by SergiuCip** [hashicorp/consul-template#602]
So I try to run make updatedeps and I get this error message:

package consul-template: code in directory /go/src/consul-template expects import "github.com/hashicorp/consul-template"

Am I missing something? Also, the import is there.

**Comment by tgwizard** [comment]
I think `github.com/hashicorp` needs to be on the path. My checkout is on

```
/Users/adam/code/go/src/github.com/hashicorp/consul-template
```

**Comment by sethvargo** [comment]
Hi @SergiuCip 

Go namespaces imports, so the code needs to live in $GOPATH/src/github.com/hashicorp/consul-template. Thanks!

**Comment by SergiuCip** [comment]
@sethvargo @tgwizard  Thank you guys for your help. So I believe I got through that error however, now it is complaining about an additional dependency:

# github.com/hashicorp/vault/http
../vault/http/sys_health.go:51: undefined: http.StatusTooManyRequests
make: *** [updatedeps] Error 123

**Comment by tgwizard** [comment]
@SergiuCip that is github rate-limiting how often you can query their API. I guess either rerun it until it works, or somehow use your github account to increase the rate-limit.

Related: https://github.com/Masterminds/glide/issues/326

**Comment by sethvargo** [comment]
Hi @SergiuCip 

That's actually not GitHub, it's go. What version of Go are you using?

**Comment by SergiuCip** [comment]
Hi @sethvargo  I am using a Go Container with Go 1.5.3

**Comment by tgwizard** [comment]
@sethvargo I had the same issue in the travis build for #589: https://travis-ci.org/hashicorp/consul-template/builds/117742401

**Comment by sethvargo** [comment]
Hi @SergiuCip 

Ah - you need to use Go 1.6 or enable the go vendor experiment on go 1.5

**Comment by SergiuCip** [comment]
Oh I see, I thought it was the otherway round. 1.6 was on 'beta' / 'testing' and 1.5 was the stable version. I will give it a go now and see the result. @sethvargo and @tgwizard  Thank you both for helping solve the issue I am having.

**Comment by SergiuCip** [comment]
Thank you @sethvargo that indeed solved my problem. Now I am encountering another problem. I have cloned this tool in order to make it just to retrieve a file from an URI and then to restart the service (nginx in my case). However, when I m trying to run go run main.go I get an error saying:

command-line-arguments
./main.go:17: undefined: NewCLI

My question in order to run it which file you have to pass to the go run?

Thanks again for all your support
