### ISSUE TITLE
Gets stuck when using {{node}} on --dedup mode

### ISSUE THREAD

**Issue by JoeOrtiz** [hashicorp/consul-template#603]
I'm trying to create a template for each server to query itself if it has a specific service like:

```
{{node}}{{range .Services}}
{{if service "event-service"}}
   blah blah
{{end}}{{if service "event-worker"}}
blahblah
{{end}}{{end}}
{{end}}
```

Anytime I try to do use {{node}} in anything, also like in the example in dedup mode, only the locked one runs, but the others don't run, just waiting for lock.

**Comment by sethvargo** [comment]
This has been fixed as of https://github.com/hashicorp/consul-template/pull/611. Thank you for reporting!
