### ISSUE TITLE
duplicate lines in consul-template output

### ISSUE THREAD

**Issue by goverdhanr55** [hashicorp/consul-template#607]
I am trying to create a template for haproxy.cfg.

The acls, service name, server name, cookie name are being extracted from tags.

the use case is I have more than one container of service A running on different host and ports, we might even need to run them on the same host at different ports.

The acls will be the same for both instances of serviceA (as the service name is the same), but in the backend configuration the host and port will be different. 

When I range {{range services}} for the acls it prints two similar lines for the same service, is there a way to remove duplicate lines from the output?

Te output I am getting is as below:

```
 acl ServiceA_url path_beg /ServiceA
 acl ServiceA_url path_beg /ServiceA

 use_backend ServiceA if ServiceA_url
 use_backend ServiceA if ServiceA_url

backend serviceA
 balance roundrobin
 option forwardfor
 server serverA abc.abc.net:<port1> cookie haproxy_ServiceA1 check inter 30000
 server serverA abc.abc.net:<port2> cookie haproxy_ServiceA2 check inter 30000
```

But what I need is 

```
acl ServiceA_url path_beg /ServiceA

use_backend ServiceA if ServiceA_url

backend serviceA
 balance roundrobin
 option forwardfor
 server serverA abc.abc.net:<port1> cookie haproxy_ServiceA1 check inter 30000
 server serverA abc.abc.net:<port2> cookie haproxy_ServiceA2 check inter 30000
```

I did try to query with the service name for the acls, but its not extracting the tags, as there are two instances running with the same service name.

**Comment by sethvargo** [comment]
Hi @goverdhanr55 

Thank you for opening an issue. There is no way to remove duplicate entries. How are you registering the services in Consul that results in getting duplicate entries? Can you please share your template?

**Comment by goverdhanr55** [comment]
The duplicate entries are being created because I have containers with the same Tags running, and the acls are being generated from the .Tags. I will have to change my approach if removing duplicate lines isnt possible.

We are running docker containers with published ports, and environment variables for SERVICE_NAME, SERVICE_TAGS, SERVICE_PORT and the services get registered.

I am trying to make the service name in the haprocy.cfg itself dynamic, in the acl, and then the host port in the backend dynamic.

e.g: in the below line the service name "ServiceA" will actually be serviceA_Env_Version, and I am extracting the ServiceA, Env, and Version values from the .Tags. I dont want to keep it static, because I am trying to use the same template irrespective of the environment, and trying to be able to route multiple versions of our services in multiple environments through the same haproxy. And once I run a container with the version and environment tagged to it, the haproxy.cfg shud be automatically updated.

acl ServiceA_url path_beg /ServiceA



I am generating the service name from the service tags. The containers which are supposed to be part of the same cluster use the same tags, so the service name i am extracting for the acl is same for all the cluster members, which is as expected, but I need it to be printed only once if the output of the loop is same twice, which is not possible going by your response.

I have gone through some other issues here, and came across suggestions to use a template to generate the template. I am leaning towards that, is it a right way, or have you got any better solutions?

Let me post my current template here

**Comment by goverdhanr55** [comment]
82 #---------------------------------------------------------------------
     83 # Service ACLs
     84 #---------------------------------------------------------------------
     85
     86 {{range $index, $element := service "ServiceA_Dev_1-0"}}
     87 acl context_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "SER"}}{{$value}}{{end}}{{end}}_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "ENV"}}{{$value}}{{end}}{{end}}_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "VER"}}{{$value}}{{end}}{{end}}_url path_beg /context/{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "SER"}}{{$value}}{{end}}{{end}}/{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "ENV"}}{{$value}}{{end}}{{end}}/{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "VER"}}{{$value}}{{end}}{{end}}{{end}}



105 {{range $index, $element := service "ServiceA_Dev_1-0"}}
    106 backend context_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "SER"}}{{$value}}{{end}}{{end}}_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "ENV"}}{{$value}}{{end}}{{end}}_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "VER"}}{{$value}}{{end}}{{end}}{{end}}



 111  {{$service_name:="ServiceA_Dev_1-0"}}{{range service $service_name}}
    112  server {{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "SER"}}{{$value}}{{end}}{{end}}_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "ENV"}}{{$value}}{{end}}{{end}}_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "VER"}}{{$value}}{{end}}{{end}} {{.Node}}.travp.net:{{.Port}} cookie haproxy_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "SER"}}{{$value}}{{end}}{{end}}_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index$tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "ENV"}}{{$value}}{{end}}{{end}}_{{range $index,$tag1 := .Tags}}{{$tag2:=split "=" $tag1}}{{$key:=index $tag2 0}}{{$value:=index $tag2 1}}{{if eq $key "VER"}}{{$value}}{{end}}{{end}} check inter 30000{{end}}


Below is the output:


(Output of line 87, duplicated - I know its going to be printed twice from my template, just wanted to see if there was an option to omit duplicate lines.)
acl context_ServiceA_Dev_1-0_url path_beg /context/ServiceA/Dev/1-0
acl context_ServiceA_Dev_1-0_url path_beg /context/ServiceA/Dev/1-0



(Output of line 106, duplicated)
backend ms_assessment_dd1_V1-0-0
backend ms_assessment_dd1_V1-0-0
 balance roundrobin
 option forwardfor


(output of line 111 as expected)
 server ServiceA_Dev_1-0 host.domain.net:<port1> cookie haproxy_ServiceA_Dev_1-0 check inter 30000
 server ServiceA_Dev_1-0 host.domain.net:<port2> cookie haproxy_ServiceA_Dev_1-0 check inter 30000

**Comment by sethvargo** [comment]
Hi @goverdhanr55 

Could you please format your code using [GitHub Flavored Markdown](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) so it is readable please?

**Comment by sethvargo** [comment]
Hi there,

There is no option to omit duplicate lines in the template file. This is either an issue with the way the data is structured in Consul or an issue with the Consul Template template. Unfortunately you're current template is very complex and the formatting makes it impossible to follow. Please try to create a smaller template that reproduces this issue and include the structure of the services in your Consul cluster. Thanks! 😄

**Comment by goverdhanr55** [comment]
HI Seth,

Thanks for the response. The issue is fixed now. 
I had to add additional tags to the services, filter them by type, and did some indexing, and printed only once if the service belong to the same cluster, where it was duplicating.

Earlier I was looking for an easier way out to omit duplicate lines. 

Thank you.
