### ISSUE TITLE
secrets output contains multiple newlines

### ISSUE THREAD

**Issue by d4v3y0rk** [hashicorp/consul-template#613]
we have a template that looks like this
```
{{range secrets "secret/kitchen"}}
{{with secret (printf "secret/kitchen/%s" .)}}
{{range $k, $v := .Data}}
{{$k | toUpper}}: {{$v}}
{{end}}
{{end}}
{{end}}
```
It is outputting 
```



SECURE_TOKEN: secure





APP_TOKEN: 123456





WEB_TOKEN: 54321


```
this is happening consul-template: v0.14.0

**Comment by Mongey** [comment]
@d4v3y0rk You've got extra whitespace in your template. Try
```go
{{range secrets "secret/kitchen"}}
{{with secret (printf "secret/kitchen/%s" .)}}{{range $k, $v := .Data}}{{$k | toUpper}}: {{$v}}{{end}}{{end}}
{{end}}
```

**Comment by d4v3y0rk** [comment]
@Mongey 
I get this in the log
```
onsul Template returned errors:
template: template: config.ctmpl:3: unexpected {{end}}Consul Template returned errors:
template: template: config.ctmpl:3: unexpected {{end}}
```

**Comment by d4v3y0rk** [comment]
@Mongey thanks! that led me in the right direction!

**Comment by E-N-G-XOR** [comment]
Hi, all,

Do you have the full template config for the pod what we can see what you did? I am sort of doing the same thing, but am having a bit of trouble with it... Is there another {{with secrets ""}} above the range statement?

**Comment by eikenb** [comment]
Hey @E-N-G-XOR

This is probably better handled via our community discussion site... but I'll take a quick swing at it here. If you are having troubles with empty newlines you have 2 options. 1) like above you edit the template to just eliminate all newline. Putting all your templates range/end/etc. on the same line. 2) Go text templates support the "-" operator which will eliminate all whitespace before/after. For more on that see: https://golang.org/pkg/text/template/#hdr-Text_and_spaces

If that doesn't get you what you need please ask again on https://discuss.hashicorp.com/c/consul and be sure to include the consul-template optional tag as that helps us pick them out (ie. email notification filters highlight these).

**Comment by d4v3y0rk** [comment]
@E-N-G-XOR @eikenb That is what ended up fixing it for me so long ago. using the "-" in my template.
