### ISSUE TITLE
QUESTION: "The Best(tm)" editor for editing templates?

### ISSUE THREAD

**Issue by nnordrum** [hashicorp/consul-template#620]
What are people using for editing templates? IntelliJ? TextMate? vim-go? notepad?

**Comment by sethvargo** [comment]
Hi @nnordrum 

Thank you for opening. We try to keep the issue tracker reserved for bug reports and feature requests. Could you ask this on the mailing list instead? Personally I use atom and vim-go interchangeably depending on my mood. Thanks!
