### ISSUE TITLE
Accessing environment variables

### ISSUE THREAD

**Issue by csghuser** [hashicorp/consul-template#622]
Hi there, I found the following code from another issue which someone said was working for them....

```
{{$host := env "HOSTNAME"}}
{{$keyname := printf "config/%s/consul/services" $host}}
{{if key $keyname}}
 {{key $keyname}}
{{end}}
```

However, this does not work for me. Do you have to pass the HOSTNAME environment variable to consul template when it starts? If so, can someone give me an example of how they are achieving this?

**Comment by csghuser** [comment]
The following worked for me:

`/etc/init.d/consul-template`

```
export HOSTNAME=`hostname`
CMD="/usr/local/bin/consul-template -config /etc/consul-template.d"
```
With the following in a template file (it just prints out the hostname)
```
{{with $host := env "HOSTNAME"}}
{{printf $host}}
{{end}}
```

Is this the preferred way or are there any alternatives?

**Comment by sethvargo** [comment]
Hi @csghuser 

Most init systems clear all environment variables (recall that environment variables are a *user* concept), so you either need to source /etc/profile.d in your script or pull the hostname from /etc/hostname.
