### ISSUE TITLE
Parse file permissions as a String in JSON

### ISSUE THREAD

**Issue by Ginja** [hashicorp/consul-template#623]
9475d6f doesn't seem to fix #548. I'm still unable to specify `perms` as a String in JSON.

```bash
$ /opt/consul-template/0.14.0/consul-template --version
consul-template v0.14.0

$ cat /etc/consul-template/conf.d/someconfig.json
{
  "template": {
    "command": "somecommand",
    "destination": "/destination/path",
    "perms": "0600",
    "source": "/template/path"
  }
}

$ /opt/consul-template/0.14.0/consul-template -config /etc/consul-template/conf.d
Consul Template returned errors:
config: walk error: 1 error(s) occurred:

* 1 error(s) decoding:

* 'template[0].perms' expected type 'os.FileMode', got unconvertible type 'string'
```

If you need more information, or would like me to test anything please let me know :)

**Comment by sethvargo** [comment]
Hey @Ginja 

I just put together #626 which has a bunch of test cases. Could you please try it out?

**Comment by Ginja** [comment]
Hey @sethvargo,

I tried compiling consul-template from your PR branch, but ran into some issues. `govendor fetch -v +outside` seems to stall out after fetching a couple of packages. Tried working around it, but was unable to produce a binary with `make dev`. I'll test it out when a new release is published. 

Thanks!

**Comment by sethvargo** [comment]
Hi @Ginja 

With the new vendored deps, just run `make dev` on Go 1.6+ and it'll "just work". No need to update deps.
