### ISSUE TITLE
consul-template error handling

### ISSUE THREAD

**Issue by centromere** [hashicorp/consul-template#629]
I simulated a network partition containing a 3-leader consul cluster. The losing partition is unable to resolve "web.service.consul", and consul-template never rewrites my nginx config file. This results in clients getting routed to unconnectable IPs instead of just failing immediately:

```
2016/05/09 20:55:00 [ERR] (view) "service(web)" health services: error fetching: Unexpected response code: 500 (rpc error: No cluster leader)
2016/05/09 20:55:00 [ERR] (runner) watcher reported error: health services: error fetching: Unexpected response code: 500 (rpc error: No cluster leader)
```

Template:
```
upstream pocket {
  least_conn;
  {{range service "web"}}server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=60 weight=1;
  {{else}}server 127.0.0.1:65535; # force a 502{{end}}
}
```

Can there be a config setting which specifies what to do when consul-template gets a 500 error? In this case I want it to behave as if no "web" instances are available rather than just do nothing.

**Comment by sethvargo** [comment]
Hi @centromere 

Thank you for opening an issue. Consul Template is designed to be highly fault tolerant and retry requests on an exponential backoff if it is unable to connect to the Consul server. You can read more [in the README](https://github.com/hashicorp/consul-template#termination-on-error). This is not something that we plan to make configurable at this time. Thanks! 😄
