### ISSUE TITLE
Can't find any binary releases of consul-template

### ISSUE THREAD

**Issue by cetex** [hashicorp/consul-template#630]
Hi!

I'm trying to rebuild a container i have and i see that i can't find any binary releases of consul-template anywhere. Previously it was available here on github, but now all i find are source releases.

**Comment by Mongey** [comment]
It's available at https://releases.hashicorp.com/consul-template/

**Comment by cetex** [comment]
Thanks!

The documentation should probably be updated then.

https://www.consul.io/downloads_tools.html -> points to github
releases on github -> only contains source releases.

**Comment by slackpad** [comment]
Thanks! I fixed up the readme.
