### ISSUE TITLE
Add support for maps with in/contains?

### ISSUE THREAD

**Issue by bradwilson** [hashicorp/consul-template#635]
We are attempting to use a key's value as JSON (via `parseJSON`), and want to be able to test for values inside the map, because we don't want to have to force all keys to have all legal property values in the JSON.

There appears to be no way to do this today, because `in` does not support maps (and the traditional method of testing for map membership in Go is not supported in consul-template). It would be nice if `in` (and thus `contains`) could implement support for maps, where the thing you're looking for in the map is the key name.

Example value:

```json
{ "tcp_port": 12345 }
```

We'd like to write something like:

```
{{ $value = .Value | parseJSON }}
{{ if in $value "tcp_port" }}
...
{{ end }}
```

Thoughts? Is there a better way to do this?

**Comment by bradwilson** [comment]
BTW, I saw other issues related to people wanting to do things like this with tags, but I'd much prefer to keep these things in the KV system, as we're already using consul-template against KVs (not services or nodes).

**Comment by sethvargo** [comment]
Hi @bradwilson 

Thank you for opening an issue. Please take a look at Go's [templating language](https://golang.org/pkg/text/template/). I believe you want to use the `index` function here. I just tested this:

```go
{{with key "foo" | parseJSON}}
{{index . "key"}}
{{end}}
```

on Consul Template 0.14. Is that not working for you?

**Comment by bradwilson** [comment]
That does not appear to work. I tried:

```
{{ if index $value "tcp_port" }}
```

Then consul-template says:

```
executing "test.ctmpl" at <index $value "tcp_po...>: error calling index: cannot index slice/array with type string
```

Is that the intended usage?

**Comment by sethvargo** [comment]
Hi @bradwilson 

Can you share your complete template? I ran that exact template I posted above and it worked without issue. What is `$value` in this context?

**Comment by bradwilson** [comment]
@sethvargo:

> Can you share your complete template?

This is a simple repro template:

```
{{ range ls "published_services" }}
  {{ $serviceName := .Key }}
  {{ $value := .Value | parseJSON }}
  {{ if index $value "tcp_port" }}
    {{ $serviceName }} is on TCP port {{ $value.tcp_port }}
  {{ else }}
    {{ $serviceName }} is NOT using TCP
  {{ end }}
{{ end }}
```

To test, I have two keys in K/V:

* Key `published_services/foo` with a value of `{ "tcp_port": 12345 }`
* Key `published_services/bar` with an empty value

I expect to see:

```
foo is on TCP port 12345
bar is NOT using TCP
```

Instead, I get the error:

```
template: template: test.ctmpl:4:8: executing "test.ctmpl" at <index $value "tcp_po...>: error calling index: cannot index slice/array with type string
```

> What is $value in this context?

For `foo`, $value is a map with the expected single key/value pair in it; for `bar`, $value is an empty map.

**Comment by sethvargo** [comment]
Hey @bradwilson,

Thank you for sharing, and I think I see the problem. You're template is just slightly different enough from mine that you're getting bitten by the n-pass evaluation first-pass. During the first pass, there is no data, and the template attempts to render. By not using `with`, you're allowing the template to flow into the conditional without a precheck that the value actually exists. If you refactor to the following, it should work fine:

```go
{{ range ls "published_services" }}
  {{ $serviceName := .Key }}
{{ with $value := .Value | parseJSON }}
  {{ if index $value "tcp_port" }}
    {{ $serviceName }} is on TCP port {{ $value.tcp_port }}
  {{ else }}
    {{ $serviceName }} is NOT using TCP
  {{ end }}
{{ end }}
{{ end }}
```

Notice that I'm using `with`. The `with` block will not evaluate its contents until the value is non-nil (it's kind of magic). This will prevent the inner block from being evaluated until Consul actually returns a value for the KV pair. 

The current return value for parseJSON is an empty array of interfaces. The reason you're getting this error is because an array cannot be string indexed. I've opened a PR to return a map as the default value instead of a string, but you should not rely on the data always being a map of strings to objects. It's perfectly valid JSON to have a top-level array.

**Comment by bradwilson** [comment]
Yeah, that sort of works, and sort of doesn't. 😞 

The reason I wasn't using `with` was because it will not run any of the inner code when the result of `parseJSON` is an empty map. That means the only way to get "serverName is NOT using TCP" is if I not only have JSON in the value, but it has to be non-empty JSON (meaning `{}` causes all the logic to be skipped).

I think I can come up with an alternative (using a third variable) that lets me DRY things out a bit -- and is better than the `regexMatch` hack I'm using today -- but it's still pretty awkward.

**Comment by sethvargo** [comment]
Hey @bradwilson 

Did you see #637 above? If you compile at that PR, your existing template will work unmodified.

**Comment by bradwilson** [comment]
@sethvargo My concern with that change is that you may be breaking someone else who is dependent on the existing behavior (for example, their JSON is always an array, and so they aren't broken during first pass like I am, but suddenly they become broken for reasons that would be *really* opaque to them).

It feels to me like having a single place (e.g., `in`) that works on both arrays and maps is the best way to solve the identity crisis of the default value for `parseJSON`.

Thoughts?

**Comment by sethvargo** [comment]
Hi @bradwilson 

I don't think it breaks bc because an array is still a map with int keys, so their use of `index` will continue to operate as expected.

**Comment by bradwilson** [comment]
@sethvargo I've verified that this does fix my issue.
