### ISSUE TITLE
Source template directory not working

### ISSUE THREAD

**Issue by mavencode01** [hashicorp/consul-template#636]
I'm trying to specify a directory for my consul templates but it's complaining it's a directory.

How can I specify multiple templates ?

	template {
	  source      = "/tmp"       #specify directory ???
	  destination = "/tmp/result"
	}

> If a directory is given instead of a file, all files in the directory (recursively) will be merged in lexical order.

**Comment by sethvargo** [comment]
Hi @mavencode01 

Thank you for opening an issue. It is not possible to specify a source folder and destination folder. (See https://github.com/hashicorp/consul-template/issues/574). The comment you referenced refers to the config files themselves. When you specify the `-config` flag on the command line, it can point to a directory, and any files in that directory are merged with the parent configuration. In this way, it's possible to specify the `template` block in a number of files (such as a consul-template.d directory), but templates must be a single source file and destination path. Thanks!
