### ISSUE TITLE
Support static data source for local development & testing

### ISSUE THREAD

**Issue by remko** [hashicorp/consul-template#638]
Hi,

We're using consul-template to generate config files in production. During local development and during our test runs, the values used in these config files are static, and we don't have access to any consul instance. It would be handy to be able to pass a JSON file to `consul-template -dry`, which would process the template with the data as if it came from the consul server. This way, we can use the same config files anywhere, and we don't need to maintain different config files for different scenarios.

thanks!
Remko

**Comment by sethvargo** [comment]
Hi @remko 

The best option here is to use `consul agent -dev` which will give you a local instance and truly test the behavior. Otherwise they will be separate code paths entirely. Thanks! 😄
