### ISSUE TITLE
Dependency graph not properly built when nested inside dynamic conditional 

### ISSUE THREAD

**Issue by jrnt30** [hashicorp/consul-template#64]
We were attempting to dynamically add in ranges per DC in a somewhat "creative" solution to allow a single template to service a dynamic number of DCs.  We are massing the output from the /v1/catalog/datacenters endpoint into a JSON file to indicate the DC's health/addressability of the DC and attempting to use this file in conditionals to add in the range or not. 

What we've observed is the dependency graph does not get properly generated when the range is inside a conditional block that is reliant upon the parsed JSON. 

**Note: I don't know how feasible it would be, but allowing the creation of a dependency against a DC that currently does not exist would fix this issue by simply removing the need to do the conditional in the first place.**

Given the contents of dcs.json are: 
```json
{
  "us-east-1":true, 
  "us-west-2":false
}
```

**Fails when conditional is based solely on the dynamic value via the file pipeline/parsed JSON**
```liquid
{{ with $dcs := file "dcs.json" | replaceAll "-" "_" | parseJSON }}
  {{if $dcs.us_east_1}}
    {{ range service "consul@us-east-1"}}node {{.Node}}{{end}}
  {{end}}
  {{if $dcs.us_west_2}}
    us-west-2 SHOULDN'T APPEAR
  {{end}}
{{end}}
```

**Works "properly" because the dependency was created outside conditional, however not really an option because adding in a range to a non-addressable DC abends the consul-template**
```liquid
{{ range service "consul@us-east-1"}}{{end}}
{{ with $dcs := file "dcs.json" | replaceAll "-" "_" | parseJSON }}
  {{if $dcs.us_east_1}}
    {{ range service "consul@us-east-1"}}node {{.Node}}{{end}}
  {{end}}
  {{if $dcs.us_west_2}}
    us-west-2 SHOULDN'T APPEAR
  {{end}}
{{end}}
```

**Works properly with non-dynamic conditional**
```liquid
{{ with $dcs := true }}
  {{if $dcs }}
    {{ range service "consul@us-east-1"}}node {{.Node}}
    {{end}}
  {{end}}
{{end}}
```

**Comment by armon** [comment]
I think the N pass does solve this. Even with conditionals, let's say you are in the "yes" path at time t0. Sometime in the future, at time t1 we switch to the "no" path (maybe a value changes in Consul), at that point the evaluator will notice we are missing a dependency, and will trigger an N+1 evaluation. Then we redo the evaluation once the data is ready. 

Basically, it is just an iterative evaluator:
1) Attempt render template, accumulate any missing dependencies, mark the used dependencies
2) If unused dependencies, stop watching
3) If no missing dependencies, template is rendered
4) If missing dependencies, add to watch list, goto 1

This loop is just executed *always*, not as part of an initial setup. This way if the set of dependencies
changes over time, we will automatically adjust the watch list to handle it. This also fixes conditionals and dynamic values.

The key is to prevent this loop from cycling forever, so I'd suggest a limit of say 5 iterations per 10 seconds or something. This allows a gradual shift in the dependencies without allowing it to be so dynamic that it never converges. This can even just be soft limited with a modification to step 4, something like a saturating counter that affects how long we sleep between refresh cycles.

**Comment by sethvargo** [comment]
Yea, I think N-pass is what we have to do.

**Comment by ryan-stateless** [comment]
```
range services {
    range service $.Name {
    $.Address
    }
}
```

I went looking for a solution to this exact use case; found this thread.
+1 for this enhancement, put the 'discovery' in "service discovery"!

**Comment by olvesh** [comment]
+1 here as well. The nested services/service range is imo essential if providing a good service discovery platform.

**Comment by grahamjenson** [comment]
+1 to above. I would also really like some way to loop over services then each service instance.

For example, I want a way of writing a nginx configuration file that dynamically load balances services using the service name as the route, e.g.

```
{{range services}}
upstream {{.Name}} {
  least_conn;
  {{range service .Name}}
  server  {{.Address}}:{{.Port}} max_fails=3 fail_timeout=60 weight=1;  
  {{else}}server 127.0.0.1:65535;{{end}}                  
}
{{end}}
server {
  listen 80 default_server;
{{range services}}
  location /{{.Name}} {
    proxy_pass http://{{.Name}};
  }
{{end}}
}
``` 

Is there a workaround or another way of doing this currently?

**Comment by sethvargo** [comment]
This is currently present on master, but it involved some significant refactors. As such, I would not recommend using master until things stabilize a bit more.
