### ISSUE TITLE
Port mismatch

### ISSUE THREAD

**Issue by mavencode01** [hashicorp/consul-template#640]
Am using consul-template (VERSION=0.14.0) with haproxy and I noticed something weird.

The generated or discovered container port (`10.0.9.6:32786`) is mapping to a wrong external container port instead of the local container port (`10.0.9.6:1936`) so my haproxy cannot reverse proxy to the backend services on that port.

My consul template backend section looks like this:

    ...
	{{range $i,$a:=services}}{{$path:=.Name}}{{range .Tags}}{{if eq . "api"}}
	backend srvs_app{{$i}}
	    mode http
	    balance roundrobin
	    option forwardfor
	    option httpchk HEAD / HTTP/1.1\r\nHost:localhost
	    reqrep ^([^\ ]*\ /){{$path}}[/]?(.*)     \1\2{{range $c,$d:=service $a.Name}}
	    server {{ .Node }}-{{ .Port }} {{ .Address }}:{{ .Port }} {{end}}{{end}}{{end}}{{end}}

Generated haproxy (note the port)

	backend srvs_app7
	    mode http
	    balance roundrobin
	    option forwardfor
	    option httpchk HEAD / HTTP/1.1\r\nHost:localhost
	    reqrep ^([^\ ]*\ /)haproxy-1936[/]?(.*)     \1\2
	    server swarm-node-01 10.0.9.6:32786 

Docker ps output:

	dee9bbe274a1        appman/haproxy            "consul-template -con"   10 minutes ago      Up 7 minutes        192.168.99.101:80->80/tcp, 192.168.99.101:32786->1936/tcp

**Comment by sethvargo** [comment]
Hi @mavencode01 

Thank you for opening an issue. This is not a Consul Template issue, but rather an issue in the way you are registering the service with Consul. Consul Template simply reads the API response from the port returned by Consul, so the data is being inserted into Consul with the incorrect port. Please check the tool you are using to register the service with Consul. Thanks! 😄
