### ISSUE TITLE
Possible explanation in docs on ParseJSON behaviour please

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/consul-template#644]
The documentation for parseJSON states that:

>Note: Consul Template evaluates the template multiple times, and on the first evaluation the value of the key will be empty (because no data has been loaded yet). This means that templates must guard against empty responses.

    {{with $d := key "user/info" | parseJSON}}
    {{if $d}}
    ...
    {{end}}
    {{end}}

Does this mean that consul-template will run the command of the template for each evaluation - or just the final evaluation?

For example, imagine I have an Nomad template that uses `parseJSON` to fetch env variables from Vault. The command for this template calls `nomad run` on the resulting HCL job file.

In the first evaluation I understand that `$d` will be falsey and so my environment variables will be empty. On the second evaluation `$d` will be populated with the data from the key and my env variables will be present. Will this result in `nomad run` being executed twice: one without env variables and one with?

**Comment by sethvargo** [comment]
Hi @grobinson-blockchain 

Consul Template only runs the command after the template has received a response for _all_ dependencies. This means it will only run once in your scenario. However, any future changes will result in a new run.

**Comment by sethvargo** [comment]
Does that answer your question?
