### ISSUE TITLE
Question: case on r.DoneCh

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/consul-template#647]
This is not an issue, but more of a question as I am trying to learn more on the watcher, runner, and cli. I am wondering when does this case get triggered: https://github.com/hashicorp/consul-template/blob/master/runner.go#L226. `Runner.Stop()` closes `r.DoneCh`, but the case doesn't get triggered, so I am wondering where the cleanup of runner is actually done. On stop all I see is this:

```
^CReceived interrupt, cleaning up...
2016/05/26 18:08:12 [INFO] (runner) stopping
2016/05/26 18:08:12 [INFO] (watcher) stopping all views
``` 

I was expecting to see the output `[INFO] (runner) received finish` somewhere after the interrupt.

**Comment by sethvargo** [comment]
Hi @cleung2010 

Can you please share your full log output?

**Comment by cleung2010** [comment]
```
consul-template -consul 127.0.0.1:8500 -template "/tmp/template.ctmpl:/tmp/result" -log-level info        [0e3f327]
2016/05/26 19:35:18 [INFO] consul-template v0.15.0-dev
2016/05/26 19:35:18 [INFO] (runner) creating new runner (dry: false, once: false)
2016/05/26 19:35:18 [INFO] (clients) creating consul/api client
2016/05/26 19:35:18 [INFO] (clients) creating vault/api client
2016/05/26 19:35:18 [INFO] (runner) creating Watcher
2016/05/26 19:35:18 [INFO] (runner) starting
2016/05/26 19:35:18 [INFO] (runner) running
2016/05/26 19:35:18 [INFO] (runner) was not watching 2 dependencies
2016/05/26 19:35:18 [INFO] (watcher) adding "datacenters"
2016/05/26 19:35:18 [INFO] (watcher) adding "datacenters"
2016/05/26 19:35:18 [INFO] (runner) diffing and updating dependencies
2016/05/26 19:35:18 [INFO] (runner) watching 1 dependencies
2016/05/26 19:35:18 [INFO] (view) "datacenters" received data
2016/05/26 19:35:18 [INFO] (runner) running
2016/05/26 19:35:18 [INFO] (runner) diffing and updating dependencies
2016/05/26 19:35:18 [INFO] (runner) watching 1 dependencies
^CReceived interrupt, cleaning up...
2016/05/26 19:35:22 [INFO] (runner) stopping
2016/05/26 19:35:22 [INFO] (watcher) stopping all views
```

**Comment by cleung2010** [comment]
I am also wondering why `r.watcher.FinishCh` doesn't get closed to signal that the watcher is during the shutdown process.

**Comment by sethvargo** [comment]
Hey @cleung2010 

It's just a race condition of the actual process ending. Basically, the process is terminating before the log output is shown. If you send SIGHUP instead of ctrl+c, this will be more obvious:

```
2016/05/27 11:37:23 [INFO] consul-template v0.15.0-dev (2c3ec756ca96712c7cc2976d75caf1f137ba5923)
2016/05/27 11:37:23 [INFO] (runner) creating new runner (dry: true, once: false)
2016/05/27 11:37:23 [INFO] (clients) creating consul/api client
2016/05/27 11:37:23 [INFO] (clients) creating vault/api client
2016/05/27 11:37:23 [INFO] (runner) creating Watcher
2016/05/27 11:37:23 [INFO] (runner) starting
2016/05/27 11:37:23 [INFO] (runner) running
2016/05/27 11:37:23 [INFO] (runner) was not watching 2 dependencies
2016/05/27 11:37:23 [INFO] (watcher) adding "storeKeyPrefix(published_services)"
2016/05/27 11:37:23 [INFO] (watcher) adding "storeKeyPrefix(published_services)"
2016/05/27 11:37:23 [INFO] (runner) diffing and updating dependencies
2016/05/27 11:37:23 [INFO] (runner) watching 1 dependencies
2016/05/27 11:37:23 [INFO] (view) "storeKeyPrefix(published_services)" received data
2016/05/27 11:37:23 [INFO] (runner) running
>

2016/05/27 11:37:23 [INFO] (runner) diffing and updating dependencies
2016/05/27 11:37:23 [INFO] (runner) watching 1 dependencies
Received HUP, reloading configuration...
2016/05/27 11:37:35 [INFO] (runner) stopping
2016/05/27 11:37:35 [INFO] (watcher) stopping all views
2016/05/27 11:37:35 [INFO] (runner) creating new runner (dry: true, once: false)
2016/05/27 11:37:35 [INFO] (clients) creating consul/api client
2016/05/27 11:37:35 [INFO] (clients) creating vault/api client
2016/05/27 11:37:35 [INFO] (runner) creating Watcher
2016/05/27 11:37:35 [INFO] (runner) received finish
2016/05/27 11:37:35 [INFO] (runner) starting
2016/05/27 11:37:35 [INFO] (runner) running
2016/05/27 11:37:35 [INFO] (runner) was not watching 2 dependencies
2016/05/27 11:37:35 [INFO] (watcher) adding "storeKeyPrefix(published_services)"
2016/05/27 11:37:35 [INFO] (watcher) adding "storeKeyPrefix(published_services)"
2016/05/27 11:37:35 [INFO] (runner) diffing and updating dependencies
2016/05/27 11:37:35 [INFO] (runner) watching 1 dependencies
2016/05/27 11:37:35 [INFO] (view) "storeKeyPrefix(published_services)" received data
2016/05/27 11:37:35 [INFO] (runner) running
>

2016/05/27 11:37:35 [INFO] (runner) diffing and updating dependencies
2016/05/27 11:37:35 [INFO] (runner) watching 1 dependencies
```

The problem with ctrl+c is that we are actually stopping the application before that last long line has a chance to write. It's technically a race condition, but likely not one worth fixing since it doesn't actually affect behavior.

**Comment by cleung2010** [comment]
SIGHUP triggers the reload. I was thinking about the cleanup process for a termination. 

I took consul-replicate's runner design for a project, and made some adjustments to make it clean up correctly. The issue is that DoneCh is used for both sending and receiving a "done" signal. Having something like a `RcvDoneCh` and `SndDoneCh` should resolve this. `Stop()` closes the `RcvDoneCh`, which is used in `Start()` and  `return` as soon as something is received, which in turn defers `close(SndDoneCh)`. The caller (in this case the CLI), watches for `SndDoneCh`.

**Comment by sethvargo** [comment]
Hi @cleung2010 

I'm aware of with SIGHUP does. The problem is that there's nothing else to "cleanup" after the watcher stops. I don't consider this a bug, because as I said above, the process is stopping anyway, and all cleanup is already done. The only thing that needs to cleanup is the watcher, and the watcher is finished by the time we close the doneCh. If you'd like to submit a pull request to make the log message show up, I'd be happy to review it. Thanks! 😄

**Comment by cleung2010** [comment]
Gotcha! This issue was not intended to be a bug report, but rather a question that came up out of curiosity. Anyhow, thanks for the prompt reply and explanation!
