### ISSUE TITLE
Designate container user for running 'command'

### ISSUE THREAD

**Issue by dkiser** [hashicorp/consul-template#649]
As A Consule Template Service Creator, I Should Be Able To designate a user to run a specified `command` after a template file has been rendered So That I Can run `command` binaries as users other than root in the container.

**acceptance criteria**
GIVEN I specify a UID for a user that exists in the container image
WHEN consul-template launches the binary designated in the template language
THEN I expect a `gosu` style user change to the specified UID when launching the binary.

GIVEN I specify a USERNAME for a user that exists in the container image
WHEN consul-template launches the binary designated in the template language
THEN I expect a `gosu` style user change to the specified username of a user in the container when launching the binary.

**Comment by sethvargo** [comment]
Hi @dkiser 

Thank you for opening an issue. The command argument can be any arbitrary command, so you can use `su -u "my_user" -c "the command to run"` if you want to run the command as a less privileged user. 

You could also run the Consul Template process as the user you want to run the command as. Consul Template does not aim to be an init system or user management system. Thanks! 😄

**Comment by dkiser** [comment]
Derp thanks!
