### ISSUE TITLE
Would you please release consul-template via tar.gz format?

### ISSUE THREAD

**Issue by netroby** [hashicorp/consul-template#650]
Would you please release consul-template via tar.gz format?
We want to using consul-template inside docker, so download and untar will be the very fast way (No need to install unzip )

**Comment by sethvargo** [comment]
Hi @netroby 

We use unzip because it is cross-platform and works on Windows. We have no plans to publish tar.gz (all our tools are zipped). We are working on official docker containers for consul-template though (and the other consul tools).
