### ISSUE TITLE
"wait" option in template config causes "invalid key"

### ISSUE THREAD

**Issue by cavemandaveman** [hashicorp/consul-template#653]
When including the <code>wait</code> option inside of the <code>template</code> block of my config file, I get the following error when starting consul-template:

 <code>'template[0]' has invalid keys: wait</code>

**Comment by sethvargo** [comment]
Hi @cavemandaveman 

Could you please share your complete template?

**Comment by cavemandaveman** [comment]
Here is what is in my config file:
```javascript
consul = "127.0.0.1:8500"
log_level = "warn"
template {
  source = "/my/template.ctmpl"
  destination = "/my/destination.txt"
  command = "my command"
  backup = true
  wait = "2s:6s"
}
```

**Comment by sethvargo** [comment]
And you can please share the complete debug output (`-log-level=debug`)

**Comment by cavemandaveman** [comment]
`debug` gives no more info than `warn` in this case.
Here's the output:
```shell
Consul Template returned errors:
1 error(s) occurred:

* 1 error(s) decoding:

* 'template[0]' has invalid keys: wait
```

**Comment by sethvargo** [comment]
Hi @cavemandaveman 

When you run in `debug`, the output should be very long. What version of Consul Template are you running?

**Comment by cavemandaveman** [comment]
I'm running the latest 0.14.0 consul-template on Ubuntu 14.04.4.

I've tried both adding `log_level = "debug"` to the config file and passing `-log-level=debug` as a runtime arg but both produce the same output as above.

**Comment by sethvargo** [comment]
Hi @cavemandaveman 

I just tried with master and this is working as expected, so it should be fixed with the next release. Thanks!
