### ISSUE TITLE
Plugin Issue

### ISSUE THREAD

**Issue by mg03** [hashicorp/consul-template#654]
HI

I have a consul template like so

`{{ with tree "iptv/qa/amq/v1" | explode }}
{{range $key, $value := . }}
{{$key}} {{$value}}
{{end}}
{{end}}`

When run, it gives

````
consul-template -config=/etc/consul-template/conf -template "test1.ctmpl:/tmp/result" -dry -once
> /tmp/result


amq.config hi ther
dvdfv
df
fdagfads



dffdasgafg


fgfgafsg




dfsgfsgfag



dfgfagafg

changed

amq.json new json

amq.yml hi i am  new yaml

key1 val1

key2 val2

key3 val3
````

what im trying to achieve

under the v1 space there are a bunch of kvs. Each key is a file name and value is the contents of the file.

I would like to create file with name $key with contents of $value.

I thought of creating a ruby plugin. But get error

Ruby Plugin code

````
#! /usr/bin/env ruby
require "json"

if ARGV.empty?
 puts JSON.fast_generate({})
  Kernel.exit(0)
end
File.open('/tmp/test2.out','w') do |s|
ARGV.each do |a|
  s.puts "Argument: #{a}"
end
end
hash = JSON.parse(ARGV.first)
puts JSON.fast_generate(hash)
Kernel.exit(0)
````

The template file is 

````
{{ with tree "iptv/qa/amq/v1" | explode | plugin "/root/pl.rb" }}
{{range $key, $value := . }}
{{$key}} {{$value}}
{{end}}
{{end}}
````

when i run the ct command

I get error

````
consul-template -config=/etc/consul-template/conf -template "test1.ctmpl:/tmp/result" -dry -once
Consul Template returned errors:
template: template: test1.ctmpl:1:49: executing "test1.ctmpl" at <"/root/pl.rb">: wrong type for value; expected string; got map[string]interface {}
````
If there is a way to achieve my goal without plugin I am open to it.
Any pointers/help would be appreciated

**Comment by sethvargo** [comment]
Hi @mg03 

Can you please share the complete debug output of Consul Template, and sample data from that KV path?

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/consul-template/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
