### ISSUE TITLE
New General Relase

### ISSUE THREAD

**Issue by clintonm9** [hashicorp/consul-template#655]
Will you all be putting out a new release soon? I noticed the last is March. 

I need this bug fixed:
https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fhashicorp%2Fconsul-template%2Fcommit%2F2431448c7edd50fd2a2165f4a709f0bb1736e0a3&sa=D&sntz=1&usg=AFQjCNFENzHqbt2kO14e5ys8_GqKJZZXVw

**Comment by sethvargo** [comment]
Yes, very soon.
