### ISSUE TITLE
Add a fromJSON function.

### ISSUE THREAD

**Issue by rayward** [hashicorp/consul-template#658]
Plugin examples as well as comments in the code would suggest that you can return json from a plugin, which you could then iterate over.

It looks like that functionality was removed in this commit though - https://github.com/hashicorp/consul-template/commit/1801dab1a91f6ab35484469526577e3dbed149e1 - meaning you can only return a string. 

This is fine for simple cases, but if you want to manipulate more complex structures, such as services, being able to return a json array or object back to the template is necessary.

Can a `fromJSON` function be implemented to support this?

**Comment by ryanuber** [comment]
Hey @rayward, the [parseJSON](https://github.com/hashicorp/consul-template#parsejson) function should help with this. Does this cover your use case?

**Comment by rayward** [comment]
I must be blind! Thanks @ryanuber
