### ISSUE TITLE
can't use variables to query range

### ISSUE THREAD

**Issue by balexx** [hashicorp/consul-template#66]
I'm trying to grab a range of keys using `{{range ls "path"}}` and then iterate over those, using something like: `{{range ls "path/$key"}}` but can't find a way to make this work.
I've gone as far as create the following:

```
{{range ls "haproxy/tcp/frontend"}}
{{$y := .Key | printf "haproxy/tcp/frontend/%s" }}
y = {{$y}}
{{range ls $y}}
{{.Key}}
{{end}}
{{end}}
```

But that doesn't work either (though $y does contain the correct path). Nesting of {{}} doesn't work either.
Without this capability, use of ranges is quite limited. If there's a way to achieve this that I'm missing, I'd love to know how!

**Comment by dangra** [comment]
can this be closed now that #153 was merged?

**Comment by sethvargo** [comment]
@dangra this has been closed since Nov 9 :smile:

**Comment by dangra** [comment]
oops
