### ISSUE TITLE
Vault address discovery via Consul

### ISSUE THREAD

**Issue by mhurne** [hashicorp/consul-template#664]
Currently, consul-template must be provided with a URL to connect to Vault.

Let's assume we have two Vault 0.6 nodes configured to use our Consul cluster as both the storage and HA backends. It is my understanding that we can configure consul-template's Vault address as follows:

```
vault {
  address = "https://active.vault.service.consul:8200"
}
```

If the active Vault node goes down, how will consul-template behave? Does it perform a DNS lookup each and every time it interacts with Vault, such that it would seamlessly pick up the address of the new Vault leader?

If not (and perhaps regardless, as they are somewhat separate concerns), I think it could be interesting to support a more direct integration between consul-template and Consul for discovery of Vault servers. If I've provided consul-template with a Consul address, perhaps it could recognize that I have Vault server(s) due to the "vault" service registered in Consul, and could use that knowledge to discover the address(es) of those servers without any additional configuration on my part? If I configured Vault to register itself with Consul under some other service name, perhaps I could override the default assumed by consul-template as well:

```
vault {
  consul_service = "hashicorp-vault"
}
```

And (this brings it full circle), I'd expect discovery of Vault leader changes to be handled seamlessly by consul-template when configured to rely directly on Consul for discovery of the Vault servers.

**Comment by sethvargo** [comment]
Hi @mhurne 

Your original assumption is right. It should "just work" because Consul will update the DNS to resolve to the next leader.

**Comment by mhurne** [comment]
Thanks for answering that question, @sethvargo. It's good to know that using Consul DNS in consul-template's configuration is one way to handle Vault HA on the consul-template end.

Perhaps unfortunately, we haven't yet configured our machines such that consul-template can make use of Consul's DNS interface (e.g. by configuring recursors and pointing resolv.conf at Consul). This is primarily because we chose to use consul-template to configure a local nginx proxy on each machine that the service(s) on that machine may use to communicate with remote services, rather than having the services make use of Consul DNS (a familiar SmartStack-like model).

So to set things up for Vault HA on the consul-template side, it seems we're in the position if needing to either configure our machines so that consul-template can use a Consul DNS-based address for Vault, or set up a load balancer in front of Vault and configure consul-template accordingly.

I think it'd be neat if consul-template were able to use the "connection" it already has with Consul to discover the active Vault server address without Consul DNS or a load balancer involved. That'd be a better fit for our current environment, at least. If consul-template didn't already integrate tightly with Consul it might not make much sense, but since it does this idea seems like a natural fit to me.

If we were to put together a pull request to add such functionality to consul-template, would it have a chance of being merged? In other words, do you think it's a worthwhile idea even if you and/or your team don't have the bandwidth or motivation to work on it?

**Comment by jhmartin** [comment]
Agreeing here, it would be very useful if this did not rely exclusively on the DNS interface to consul and instead could deal with the HTTP interface.

**Comment by jhmartin** [comment]
Also, using the DNS interface as above requires vault be on a specific port.
