### ISSUE TITLE
Document printf usage

### ISSUE THREAD

**Issue by fieryvova** [hashicorp/consul-template#665]
Hi,
It would be great if you could document *printf* usage in template files.

My case:
Dynamic configuration of HAProxy. I've tried to pass variables to *service*, e.g., 
```
{{range service "${{var1}}{{var2}}"}}
server {{.Name}} {{.Address}}:8080 check inter 2000 rise 2 fall 2 id 1 maxconn 200
{{end}}
```
It threw the following error, which is caused by strict regexp that checks service names.

> error calling service: invalid health service dependency format

After searching through Consul google group I found [that post](https://groups.google.com/forum/#!searchin/consul-tool/service$20variable/consul-tool/07yGDwGEcgM/5PBLsaz8LwAJ).

It turns out that this is possible to pass variables to *service* using some undocumented trick:
```
{{range printf "%s%s" ($var1) ($var2) | service}}
server {{.Name}} {{.Address}}:8080 check inter 2000 rise 2 fall 2 id 1 maxconn 200
{{end}}
```
I think that this kind of trickiness is not obvious and need to be documented.

Thanks,
Vladimir

**Comment by sethvargo** [comment]
Hi there,

It's go's templating language: https://golang.org/pkg/text/template/. There are lots of links to it in the README:

> Please see Golang's `text/template` package for more information.

**Comment by fieryvova** [comment]
Thanks for letting me know.
I wasn't reading the documentation thoroughly enough.
