### ISSUE TITLE
Finer-grain control on the way consul-template diff's healthy changes to exec commands

### ISSUE THREAD

**Issue by TalonOne** [hashicorp/consul-template#666]
Docker: 1.7.1
Consul: 0.6
Consul-template version: 0.14.0

We have a Docker cluster setup with HAProxy instances sitting on each host. Each HAProxy config is refreshed by consul-template on any changes on consul's side as observed by consul-template.

We recently started observing way too many restarts (~20k) of proxies by consul-template and the reason seems to be because of the way consul-template interprets a "change" in health for a corresponding consul service. Every service in our setup has a HTTP health check registered for it in which we return an output status **along with a timestamp**. So every such call  can have the same status of "passing" but has a different contents in the output field like "Output":  ' "timestamp": 124125354, "status" : "healthy" '.

From what it looks like, consul-template is diffing the state of a service.HealthCheck using go-langs reflect.DeepEqual() to compare if the health check is any different from the last time it was checked. And when this happens, and because your "Output" has a constantly changing timestamp in it, consul-template is perceiving it as an actual health change triggering the command part of the template.

Ideally, I would expect consul-template to interpret a health change only when the "status" part of the consul health check flips from "passing" to "critical" etc or vice-versa.

This is probably an advanced feature ask, but a finer-grained control of what fields consul-template uses to perceives as a health change for a service registered in consul would really be helpful and intuitive.

Happy to provide more details if necessary. Adding @ryanuber for context, we had a chat about this on IRC last evening.

**Comment by ryanuber** [comment]
I didn't think about this yesterday, but closely related is the config option in consul, `check_update_interval` (docs [here](https://www.consul.io/docs/agent/options.html#check_update_interval). To trigger 20k updates rapidly, I am guessing this must be configured very low. By default it should be 5 minutes if the status does not change, so Consul should not be triggering updates below that threshold.

@TalonOne can you tell us what you have that set to in your Consul config?

You could set your consul config to have a very high update interval as a hack work-around for the time being. Either way it would still not be the greatest to restart services on any interval for changing output only.

**Comment by TalonOne** [comment]
@ryanuber I agree. We are currently using the default 5m interval for check_update_interval. That said, we have around 120 services each registered with its own health check run every 15s by Consul. So that's around 28,800 health checks per hour which sure can result in so many (5600) restarts.

We will try to bump up the check_update_interval to a high number to mitigate the problem temporarily, but with so many apps and checks done so frequently, it might still result in high restart count.

**Comment by sethvargo** [comment]
Hi @TalonOne 

This is something I'd happily review a PR for, but I would also encourage you to consider refactoring your health checks to not return that type of output. The blocking query in Consul is going to return that value on change, which is going to have unintended side-effects beyond CT if I understand correctly.
