### ISSUE TITLE
haproxy template for multidomain with container

### ISSUE THREAD

**Issue by peceka** [hashicorp/consul-template#670]
Hi,

i need to create template for haproxy which allows to use container for many virtualdomains.
For example i've got jboss containers which serve main application and i need to get to each container to it's jmx-console, so i think it should works like this:
containers with ie. tags=app will be registered in haproxy in one acl which checks host and and when user create http://app/ he/she will be balanced to all containers with tag=app but when user create connection for http://container_name/jmx-console he/she will be redirected to specified container only.

Can somebody send some hints how to achive such situation?

regards,
p.

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Consul mailing list](https://groups.google.com/forum/#!forum/consul-tool). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
