### ISSUE TITLE
Any way to get a 0.16.0 release or 0.16.0-rc?

### ISSUE THREAD

**Issue by outcoldman** [hashicorp/consul-template#673]
0.16-rc is not available on https://releases.hashicorp.com/consul-template/, really want to use new `-exec` option.

**Comment by sethvargo** [comment]
Correct - we are no longer publishing RC candidates in the index, but you can download it directly using the link. The reason we don't publish it in the index is that we do not guarantee RC candidates will exist past the major release, so we don't want users building automation around pre-release candidates.

Alternatively, you can build from source. Thanks! :smile:

**Comment by sethvargo** [comment]
Correct - we are no longer publishing RC candidates in the index, but you can download it directly using the link. The reason we don't publish it in the index is that we do not guarantee RC candidates will exist past the major release, so we don't want users building automation around pre-release candidates.

Alternatively, you can build from source. Thanks! :smile:

**Comment by sethvargo** [comment]
Correct - we are no longer publishing RC candidates in the index, but you can download it directly using the link. The reason we don't publish it in the index is that we do not guarantee RC candidates will exist past the major release, so we don't want users building automation around pre-release candidates.

Alternatively, you can build from source. Thanks! :smile:

**Comment by outcoldman** [comment]
@sethvargo but what is the rule to generate direct link? Seems like standard rule of `https://releases.hashicorp.com/consul-template/{VERSION}/consul-template_{VERSION}_linux_amd64.zip` does not work. Tried VERSION=0.16.0, 0.16.0rc, 0.16.0-rc

**Comment by sethvargo** [comment]
@outcoldman it'll match [the tag name](https://github.com/hashicorp/consul-template/releases), but please keep in mind *we are likely going to delete the release* once it's final.

**Comment by matleh** [comment]
minor comment: it'll match the tag name - minus the leading "v".  https://releases.hashicorp.com/consul-template/0.16.0-rc1/consul-template_0.16.0-rc1_linux_amd64.zip works currently.
