### ISSUE TITLE
-exec and -once modes together - wait for process to exit

### ISSUE THREAD

**Issue by dansteen** [hashicorp/consul-template#679]
Hi!

First off, thanks for all your work with consul and consul-template (and others!). You guys have really put together a fantastic set of tools.   

Under the current behavior, if you use both -exec mode and -once mode together, consul-template will exit prior to the completion of the task you have told it to exec, and, if the task takes more than a second, the exec'ed command will be killed.   Would it be possible to have consul-template wait for the command to exit when using both modes together?  It would also be great if consul-template could exit with the return value of the command it was supposed to run (right now, it always exits with a 0).

Thanks!

consul-template v0.16.0rc1

**Comment by bennetimo** [comment]
+1 this would be a nice feature

**Comment by dansteen** [comment]
thanks!
