### ISSUE TITLE
under exec mode, signal isn't being triggered during reload when reload_signal is defined

### ISSUE THREAD

**Issue by skippy** [hashicorp/consul-template#680]
### Consul Template version
/ # consul-template -v
consul-template v0.16.0rc1 (44afc882e6c25fe4d62654999f826d68271ff807+CHANGES)

#### consul-template config
```javascript
deduplicate {
  enabled = false
}

log_level = "debug"

vault {
  renew = true
}

template {
  source      = "/consul-template/template.d/internal-proxy.service.consul.pem.tmpl"
  perms       = 0400
  destination = "/etc/haproxy/ssl/internal-proxy.service.consul.pem"
}

template {
  source      = "/consul-template/template.d/service.consul.ca.pem.tmpl"
  perms       = 0400
  destination = "/etc/haproxy/ssl/service.consul.ca.pem"
}

template {
  source      = "/consul-template/template.d/haproxy.tmpl"
  destination = "/etc/haproxy/haproxy.cfg"
}

exec {
  command       = "/haproxy_run.sh"
  reload_signal = "SIGUSR1"
  kill_signal   = "SIGTERM"
  splay         = "5s"
  kill_timeout  = "30s"
}
```

#### consul-template template
this is the template for /consul-template/template.d/internal-proxy.service.consul.pem.tmpl
NOTE: I tried to set the ttl=1m for testing purposes but it seems that 5m is as low as it goes
```liquid
{{with node}}{{ with secret "pki/internal-services/issue/base" "common_name=internal-proxy.service.consul" "ttl=5m" (print "ip_sans=127.0.0.1,0.0.0.0," .Node.Address) }}{{ .Data.certificate }}
{{ .Data.issuing_ca }}
{{ .Data.private_key }}
{{ end }}{{ end }}
```

### Command

```shell
/bin/consul-template -config /etc/consul-template/consul-template.cfg
```

this is the haproxy_run.sh file called by the exec block in the consul-template
```shell
#!/bin/bash

set -e

prepare_haproxy() {
  # setup files and directory for use by haproxy
  touch /var/run/haproxy.pid;
  mkdir -p /var/state/haproxy/
  mkdir -p /var/run/haproxy
  touch /var/state/haproxy/global
  chown -R haproxy:haproxy /var/state/haproxy
  chown -R haproxy:haproxy /var/run/haproxy
  # make sure ssl certs are limited to just haproxy
  chown -R haproxy:haproxy   /etc/haproxy
  chmod 0400 /etc/haproxy/ssl/*
}


verify_haproxy_configs() {
  if ! /usr/sbin/haproxy -c -f /etc/haproxy/haproxy.cfg; then
    echo "Invalid haproxy config"
    echo -e $(cat /etc/haproxy/haproxy.cfg)
    exit 1
  fi
}

start_restart_haproxy() {
  # exec -- do not use; we want THIS script to capture any restart signals and
  haproxy_pid=$(ps | grep sbin/haproxy | grep -v grep | awk '{print $1}')
  /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -sf $haproxy_pid || true
}

reload_haproxy() {
  echo "reloading haproxy"
  prepare_haproxy  # need to reset because of updated certs won't be under the haproxy group
  # Save the current HAProxy state
  socat /var/run/haproxy/socket - <<< "show servers state" > /var/state/haproxy/global
  verify_haproxy_configs
  start_restart_haproxy
}

shutdown_haproxy() {
  echo "gracefully stopping haproxy"
  haproxy_pid=$(ps | grep sbin/haproxy | grep -v grep | awk '{print $1}')
  kill -SIGUSR1 $haproxy_pid
  exit 0 # cleanly shut down!
}


trap reload_haproxy   SIGUSR1
trap shutdown_haproxy SIGTERM


echo "starting haproxy"
prepare_haproxy
verify_haproxy_configs
start_restart_haproxy
```

### Debug output
https://gist.github.com/skippy/d8e19f3e1e90a9352eb18850dec1623e

### Expected vs Actual behavior
I was expecting a `SIGUSR1` to be sent to the script, but I didn't see anything come in... and the logs don't show any sort of exec event being triggered (though I can't tell if that is because there is no logging around that functionality or because it actually didn't trigger).

*UPDATE:* removed comments about cert ttl not being recognized, and updated title and top paragraph to be more specific about unexpected behavior only when `reload_signal` is defined

**Comment by skippy** [comment]
UPDATE: if I *don't* set a `reload_signal = "SIGUSR1"` the script is run again... and I can see it getting called from the `echo` statements; something I wasn't seeing before.

I can work around that (and I like not having to use `inotifywait` :)  Let me know if you would like anything else with regards to `reload_signal`

**Comment by sethvargo** [comment]
Hi @skippy 

Thank you for opening an issue. There are a bunch of tests around the signaling functionality, so I'm a bit surprised that it's not firing.

Could you try a few things for me:

1. Disable deduplicate mode and see if that makes a difference
2. Let's remove HAproxy from the mix and just use a bash script that catches signals and echos (https://github.com/hashicorp/consul-template/blob/ae7d6e86a41ab9968388593bc2a36f5107828dae/runner_test.go#L1374-L1380)
3. The process _will log_ in debug mode when a signal is sent. You should see something like `(child) sending signal to process ...`
4. Try adding a `set -x` to your script as well so we can see what exactly it's running

**Comment by sethvargo** [comment]
I just tried a number of different techniques, and I'm unable to reproduce this. If you can provide additional information, I would be happy to revisit it.

**Comment by skippy** [comment]
Hi @sethvargo sorry for not being more responsive; I got tied up on other stuff.  I'll run your suggestions and let you know what I see (in a few days).

cheers!

**Comment by skippy** [comment]
@sethvargo you're right; this was my fault.  I was holding on the haproxy process, so consul-template was sending the signals right there rather than my wrapper script.

I'm not sure if it is possible, but it would be very helpful in the logs if:
* if a signal was sent to consul-template, which in turn is passed to the child process, it would be *awesome* if all that info (signal received and what pid/procname it is being sent to) is logged as INFO
* similar for signals that consul-template generates; it does say a signal was sent, but not which one or to what child process

I think those two issues would have allowed both of us to hone in on what was going on.

thanks again @sethvargo for your help!
