### ISSUE TITLE
Dumping template dependencies

### ISSUE THREAD

**Issue by carlpett** [hashicorp/consul-template#681]
I'm having some issues debugging a template that does not seem to be firing when I expect it to. The template is a bit complicated, with nested service and k/v lookups depending on `printf`ed service lookups... 

Here's an abbreviated exerpt:
```
{{ $services := tree (printf "%s/%s/" $role $environment) | explode }}
{{ range $service, $config := $services }}
{{ range service (printf "%s.%s" $environment $service) }}
[... stuff ...]
``` 

I'm guessing that some dependency is not getting set correctly, but I'm having problems seeing exactly what CT thinks is a dependency and not. Is it possible to dump the graph somehow?

**Comment by carlpett** [comment]
With some further digging, setting log-level debug gives this:

```
receiving dependency "storeKeyPrefix(some-role/stage/)"
receiving dependency "service(stage.some-service1)"
receiving dependency "service(stage.some-service2)"
receiving dependency "service(stage.some-service3)"
receiving dependency "service(stage.some-service4)"
receiving dependency "service(stage.some-service5)"
receiving dependency "service(stage.some-service6)"
```

Maybe that is as good as it gets?

**Comment by sethvargo** [comment]
Yup! You got it. You want to use debug level logging for this kind of information.
