### ISSUE TITLE
under exec mode pass signal to process rather than handling it first

### ISSUE THREAD

**Issue by dansteen** [hashicorp/consul-template#682]
Hi!

Currently, under exec mode, if you send a signal to consul-template, consul-template will pass that signal on to the process it has exec'ed, however, it will also handle the signal.   So, if you send a SIGTERM into consul-template, it will pass that SIGTERM on to the managed process, however, it will then immediate terminate, taking the managed process with it (rather than waiting for the managed process to complete it's cleanup).   I think it might be better to just pass the signals on to the underlying process rather than handling them in any way.   That way, if the underlying process is configured to exit at a SIGTERM, it will do so at it's leisure, and consul-template will exit anyway once it's done.   

I suppose an alternative, would be to have consul-template wait at least --sig-kill-timeout for the managed process to cleanly exit, but that would not allow you to manage processes with more "exotic" signal handling.   

My test is done with the following code:

```
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>

#include <signal.h> /*for signal() and raise()*/

void sigterm(int signum){
    printf("SIGTERM!\n");
    sleep(10);
    exit(0);
}
void sigusr1(int signum){
    printf("SIGUSR1!\n");
}

int main(){

    signal(SIGTERM, sigterm);
    signal(SIGUSR1, sigusr1);

    //loop forever!
    while(1);
}
```

and then I run:
```
consul-template -exec-kill-timeout 30s -exec ./sig
```

If I send that a SIGTERM it will exit immediately rather than waiting 10 seconds.

consul-template v0.16.0rc1

Thanks!

**Comment by sethvargo** [comment]
Yea, this is a known issue unfortunately, and it's the reason the signals on the child are configurable. CT needs to respond to _some_ signals so it can be gracefully stopped.

**Comment by dansteen** [comment]
well,  if it's running in exec mode,  does it really need to respond to signals?  Couldn't it just pass them all through to the child, and rely on the child to do what it needs to with them?   consul-template will exit anyway if the child does...

Also, I would at least expect it to waith --exec-kill-timeout for the child process to do its thing prior to termination.

Thanks!

**Comment by dansteen** [comment]
had a thought.  Maybe the opposite would work.  Instead of `--exec-kill-signal`, why not have `-ct-kill-signal`.  Then you could specify the signal that would kill consul-template cleanly, and *all* other signals would get passed into the child process.
