### ISSUE TITLE
How to do last kv handling in range tree

### ISSUE THREAD

**Issue by deepagargit** [hashicorp/consul-template#689]
I want to remove last comma in range loop.
Please suggest how to remove it.

{
                "id" : "cust3"
**},**

**Consul Template Version**
$ ./consul-template -v
consul-template v0.15.0

**Template file**
person.ctmpl
"person": [
        {{range tree "/path/person@dc-public"}}
        {
                "id" : "{{ .Key }}"
        },
        {{end}}
]

**Output:**
$ ./consul-template -template person.ctmpl:person.result -dry
> person.result

"person": [

        {
                "id" : "cust1"
        },
        
        {
                "id" : "cust2"
        },
        
        {
                "id" : "cust3"
        },
        
]

**Comment by sethvargo** [comment]
Hi @deepagargit 

We try to keep the issue tracker reserved for bug reports and feature requests. For general usage questions, please use the Consul mailing list. I believe you're going to want to use another parameter to your `range` query and then only print the comma out conditionally: https://golang.org/pkg/text/template/
