### ISSUE TITLE
Include timezone in log output

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/consul-template#691]
Currently `consul-template` logs (written to `/var/log/upstart/consul-template`.log` at least for us) do not contain the timezone. This makes it difficult to accurately ingest the logs into a logging pipeline such as Logstash. See also hashicorp/consul#2227.

**Comment by sethvargo** [comment]
The logs are in UTC, which is the common standard: https://github.com/hashicorp/consul-template/blob/master/logging/logging.go#L64
