### ISSUE TITLE
Missing newline makes log output difficult to parse

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/consul-template#692]
I saw the following log output produced by `consul-template`:

    2016/08/10 01:52:19 [ERR] (runner) error running command: exit status 1
    Consul Template returned errors:
    1 error(s) occurred:
    
    * exit status 12016/08/10 01:52:20 [INFO] consul-template v0.15.0

This formatting is difficult to parse because there is no newline after "exit status 1". Ideally, the output would be:

    2016/08/10 01:52:19 [ERR] (runner) error running command: exit status 1
    Consul Template returned errors:
    1 error(s) occurred:
    
    * exit status 1
    2016/08/10 01:52:20 [INFO] consul-template v0.15.0

**Comment by sethvargo** [comment]
This is fixed on master
