### ISSUE TITLE
avoid generating an empty upstream block if all services with a certain name are down.

### ISSUE THREAD

**Issue by paperpunk** [hashicorp/consul-template#693]
hello,

i am trying to generate an nginx.conf file with multiple upstream blocks with values from consul using consul-template.
i am grouping my services by name and need to be able to proxy to these 'groups' of passing services from nginx.  

For example, let's say I have 3 groups of services.
```
service name: ABC-01
instances: 1 (passing), 2 (passing), 3 (critical)
```
```
service name: ABC-02
instances: 4 (passing), 5 (passing)
```
```
service name: ABC-03
instances: 6 (critical)
```
the end result i am looking for is:
```
upstream ABC-01 {
	server 1;
	server 2;
}

upstream ABC-02 {
	server 4;
	server 5;
}
```
This is the template that I am working on.  
```
{{range services}}					
  {{if .Name | regexMatch "^ABC-."}}
  upstream {{.Name}} {
    {{$service:=.Name}}
    {{range service $service}}
      server {{.Address}}:{{.Port}};
    {{end}}
  }
  {{end}}
{{end}}
```
I realize that this obviously produces an empty upstream block in an event that all instance of the certain ABC service are down, but if i put the 'upstream' line inside the 'range service $service' block, i will end up with an 'upstream' line for each instance. 
Is there a good solutiong to avoid having an empty upstream block? 

thank you.

**Comment by sethvargo** [comment]
You can `{{ else }}` the range:

https://golang.org/pkg/text/template/

**Comment by richard-mauri** [comment]
I ma having the same problem. Would it be possible to clarify how using "{{ else }} in the range" by incorporating it in the original poster's example?Thanks

**Comment by paperpunk** [comment]
i ended up doing it like this:
```
    {{range services}}
      {{if .Name | regexMatch "^ABC-."}}
        {{if service .Name "passing"}}  # only if there are any passing services in this service group
          upstream {{.Name}} {
            {{range service .Name}}
                server {{.Address}}:{{.Port}};
            {{end}}
          }
        {{end}}
      {{end}}
    {{end}}
```
i think what @sethvargo was referring to is `{{range pipeline}} T1 {{else}} T0 {{end}}` this construct where you would say something like:
```
 {{range service $service}}
      server {{.Address}}:{{.Port}};
  {{else}}
     server 127.0.0.1:8080;
  {{end}}
```
but i don't have a default that i could just list in the config file. 

hope this helps.
