### ISSUE TITLE
bosh -n deployfails while deploying cloudfoundry

### ISSUE THREAD

**Issue by vijaay** [hashicorp/consul-template#697]
bosh_qnf20ygd9@70d31ebf-aaa7-4d87-83fc-412c9e3c7b65:/var/vcap/sys/log/doppler$ tail -f doppler.stderr.log
        /var/vcap/data/compile/doppler/loggregator/src/doppler/main.go:98 +0x4cd
panic: sync cluster failed

goroutine 1 [running]:
panic(0xb1a420, 0xc82019a040)
        /var/vcap/data/packages/golang1.6/85a489b7c0c2584aa9e0a6dd83666db31c6fc8e8.1-7c8476bd05c7f6bdd028210df36294423c05708c/src/runtime/panic.go:464 +0x3e6
main.NewStoreAdapter(0xc82005d860, 0x0, 0x0)
        /var/vcap/data/compile/doppler/loggregator/src/doppler/main.go:64 +0x27f
main.main()
        /var/vcap/data/compile/doppler/loggregator/src/doppler/main.go:98 +0x4cd

bosh_qnf20ygd9@70d31ebf-aaa7-4d87-83fc-412c9e3c7b65:/var/vcap/sys/log/loggregator_trafficcontroller$ tail -f loggregator_trafficcontroller.stderr.log
        /var/vcap/data/packages/golang1.6/85a489b7c0c2584aa9e0a6dd83666db31c6fc8e8.1-7c8476bd05c7f6bdd028210df36294423c05708c/src/runtime/panic.go:464 +0x3e6
main.main()
        /var/vcap/data/compile/loggregator_trafficcontroller/loggregator/src/trafficcontroller/main.go:102 +0x888
panic: Unable to connect to ETCD: sync cluster failed

goroutine 1 [running]:
panic(0xb002e0, 0xc8200113a0)
        /var/vcap/data/packages/golang1.6/85a489b7c0c2584aa9e0a6dd83666db31c6fc8e8.1-7c8476bd05c7f6bdd028210df36294423c05708c/src/runtime/panic.go:464 +0x3e6
main.main()
        /var/vcap/data/compile/loggregator_trafficcontroller/loggregator/src/trafficcontroller/main.go:102 +0x888

bosh_qnf20ygd9@70d31ebf-aaa7-4d87-83fc-412c9e3c7b65:/var/vcap/sys/log/consul_agent$ tail -f consul_agent.stderr.log
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded

bosh_qnf20ygd9@70d31ebf-aaa7-4d87-83fc-412c9e3c7b65:/var/vcap/sys/log/consul_agent$ tail -f consul_agent.stderr.log
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded

bosh_qnf20ygd9@70d31ebf-aaa7-4d87-83fc-412c9e3c7b65:/var/vcap/sys/log/consul_agent$ tail -f consul_agent.stderr.log
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded

bosh_qnf20ygd9@70d31ebf-aaa7-4d87-83fc-412c9e3c7b65:/var/vcap/sys/log/consul_agent$ tail -f consul_agent.stderr.log
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded

bosh_qnf20ygd9@70d31ebf-aaa7-4d87-83fc-412c9e3c7b65:/var/vcap/sys/log/consul_agent$ tail -f consul_agent.stderr.log
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded
error during start: timeout exceeded

**Comment by sethvargo** [comment]
These are not issues with Consul Template. There is nothing in the logs to indicate there is an issue with Consul Template. These logs are coming from Bosh.
