### ISSUE TITLE
dedup slaves re-render templates and execute commands every 60 seconds

### ISSUE THREAD

**Issue by deltaroe** [hashicorp/consul-template#698]
Not sure if this falls under the bug or unexpected feature category. 

We are running consul-template 0.15.0 in dedup mode with a single template. Consul is running version 0.6.4. We tried to attach a command to the template to be executed on update and ran into an issue

The master node seems to be working fine, processing template changes and only executing the command when changes occur. The slave nodes however re-render the template and execute the attached command every 60 seconds regardless if there is a change or not. Updating the resulting file that often isn't really an issue but running the command once a minute causes issues in our environment

Looking through the code this appears to be because the template watch is doing a 60s blocking wait on the kv entry where the leader puts the template. When the 60s expires consul returns the kv entry as is, but consul-template doesn't check if the modify version changed or not. Instead consul-template assumes that a change occurred and starts up the runner to process the new template. 

For now I've wrapped the command in a if diff hack that keeps track of the last version of the template and only executes the real command if it has changed.

**Comment by slackpad** [comment]
Interesting - I'll see if I can clean this up. The timeout definitely makes sense for why it's waking, but it should be able to tell that the contents are the same.
