### ISSUE TITLE
Consul-template + HAProxy Gateway Time-out error

### ISSUE THREAD

**Issue by cabrinoob** [hashicorp/consul-template#699]
Hi,
I'am using consul-template to write a haproxy.cfg config file. When I run in debug mode I have this error message every 15s that pop : 

```
2016/08/22 13:55:36 [ERR] (view) "service(MoteurV3)" health services: error fetching: Unexpected response code: 504 (<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
)
2016/08/22 13:55:36 [ERR] (runner) watcher reported error: health services: error fetching: Unexpected response code: 504 (<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
)

```
I'am running consul-teplate 0.15.0 and HAProxy 1.6. Here is my haproxy.ctmpl : 

```
defaults
   mode http
   timeout connect 5000ms
   timeout client 50000ms
   timeout server 50000ms

backend mv3-backend
   balance roundrobin
   mode http
   {{range service "MoteurV3" }}server {{.Node}} {{.Address}}:{{.Port}}
   {{end}}

   reqrep ^([^\ ]*)\ /mv3/(.*) \1\ /\2

frontend http
  bind *:8080
  mode http

  acl url_mv3 path_beg /mv3
  use_backend mv3-backend if url_mv3

listen stats
    bind *:1936
    mode http
    stats enable
    stats hide-version
    stats realm Haproxy\ Statistics
    stats uri /
    stats auth Username:Password
```

Everything works fine but I have this error which pop every 15s ... Any fix?

Thank you

**Comment by sethvargo** [comment]
That error is coming from the HTTP API request to the Consul server. Can you share your config and the command you're running? How do you have your Consul servers setup? What size instances are they?

**Comment by cabrinoob** [comment]
I'am using a consul cluster (3 nodes). I'am using a docker image whith HAProxy and consul-template : 

```
FROM alpine
MAINTAINER fmeriot

ENV CONSUL_TEMPLATE_VERSION=0.15.0
RUN apk --update add haproxy wget

RUN ( wget --no-check-certificate https://releases.hashicorp.com/consul-template/${CONSUL_TEMPLATE_VERSION}/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip -O /tmp/consul_template.zip && unzip /tmp/consul_template.zip && mv consul-template /usr/bin && rm -rf /tmp/* )

COPY files/haproxy.json /tmp/haproxy.json
COPY files/haproxy.ctmpl /tmp/haproxy.ctmpl

ENTRYPOINT ["consul-template","-config=/tmp/haproxy.json"]
CMD ["-consul=172.18.2.88:8500"]
```
I'am runing this image with this command : 

`docker run -it -p 8080:8080 -p 1936:1936  --rm  haproxy-consul -consul=172.18.2.88:8500`

When I call my HAProxy on the port 8080 and a specific route it works fine. I can observe that the HAProxy do its job. When I add or remove a container, the config is updated and the loadbalancing acts as well. But, in my console, every 15s, I have this error message.

**Comment by sethvargo** [comment]
Oh. This makes sense. Consul uses blocking queries which do not render a request immediately (they wait for a state change in the system). Haproxy appears to be severing the connection; you'll need to configure HAproxy to not do that.

**Comment by cabrinoob** [comment]
Ok. Thank you.
