### ISSUE TITLE
Allow support for render-only mode

### ISSUE THREAD

**Issue by n2taylor** [hashicorp/consul-template#701]
In order to control the order of template rendering when provisioning our application, we need a way to render the templates without executing the associated commands. The reason is that there are multiple templates that all need to be rendered before we can start our application (namely various config files). We can't just dump them all in a directory and let Consul Template render them all, because after each template it tries to restart the system, which, lacking all its config, fails to start properly.

This has been a major hassle for us -- we've had to resort to some ugly hacks to get it working.

I would like to have a command-line option, `-no-commands` that simply suppresses any command execution during the lifetime of that instance of CT. Combined with the `-once` option, we could then just run CT once to render everything we need, start the app, and then start the `consul-template` daemon to continue watching for changes.

**Comment by jippi** [comment]
we hack it with `-command date` :)

**Comment by n2taylor** [comment]
@jippi can you provide an example? Are you just passing them in one by one to the `-template` option?

**Comment by sethvargo** [comment]
@n2taylor I think you're going to want `-exec` mode, which is currently in master and the 0.16 rc release.
