### ISSUE TITLE
error while deploying diego on azure 

### ISSUE THREAD

**Issue by vijaay** [hashicorp/consul-template#702]
Please note that the Consul Template issue tracker is reserved
for bug reports and enhancements. For general usage questions,
please use the Consul mailing list:

    https://groups.google.com/forum/#!forum/consul-tool

### Consul Template version
Run `consul-template -v` to show the version. If you are not
running the latest version, please upgrade before submitting an
issue.

### Configuration
```javascript
// Copy-paste your Consul Template configuration file here
```

```liquid
# Copy-paste your Consul Template template here
```

### Command

```shell
# Place your Consul Template command here
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug
output by running with `-log-level=debug`.

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should
be linked here? For example:
- GH-1234
- ...

**Comment by slackpad** [comment]
Closing this as it looks like the empty template, and is probably a mistake.
