### ISSUE TITLE
Feature Improvement request: ignore wait on startup

### ISSUE THREAD

**Issue by skippy** [hashicorp/consul-template#703]
right now, if `wait` is defined, consul-template waits that amount before the initial command is triggered.  It would be nice if `wait` was ignored for that initial startup and then used on subsequent restarts.

The reason is I have a process (an haproxy instance) which needs to be started as quickly as possible.  Yet it is also getting bounced a lot as services flutter, something `wait` is perfect for.  Yet I can't as it delays the initial start of haproxy.

I'm using the exec mode if that makes a difference.

**Comment by sethvargo** [comment]
Hey @skippy,

Thank you for opening an issue. Wait is the minimum amount of time to wait for zero changes in the system, so there's no way to make it start "immediately"... CT might not have that data yet, so it's not safe to tell haproxy to start until the deps are resolved, and they won't be resolved until the minimum quiescence time. The behavior you describe is the opposite of most user's requirements and the opposite of the academically-defined behavior of quiescence, so we will not be adding that functionality. Thanks and have a great day!

**Comment by skippy** [comment]
@sethvargo first off, thank you for the prompt response.  

I couldn't tell from you response if we are on the same page; perhaps, but to be clear, I'm asking that we start the process then wait, rather than wait before starting.  quiescence consistency has to deal with guaranteeing call order over a period of time (which is the quiescence).  At initial execution time (t0) there is no state (or call order), so having a quiescence before t0 doesn't do anything except delay startup.  quiescence only comes into play after t0 and between execution ticks t0 and t1+. 
(big caveat: it has been a decade + since I've academically studied this, so I could be way off). 

AND, even if you agree and still don't want to change it, that is ok, of course :)  I think it would help not to unnecessarily delay t0, but I may be an edge case (I didn't notice anyone else asking a similar question on the forms).  And if I'm not an edge case, at least this question is documented and folks can +1 if need be.  thanks @sethvargo !

**Comment by skippy** [comment]
and @sethvargo no need to respond if you want to keep it closed :)
