### ISSUE TITLE
error while deploying diego on azure 

### ISSUE THREAD

**Issue by vijaay** [hashicorp/consul-template#704]
azurecfbosh@ocfdev-azurebosh:~$ bosh -n deploy
Acting as user 'admin' on deployment 'cf-diego' on 'bosh'
Getting deployment properties from director...

Detecting deployment changes
----------------------------
resource_pools:
- name: resource_z1
  network: diego
  stemcell:
    name: bosh-azure-hyperv-ubuntu-trusty-go_agent
    version: '3262.4'
  cloud_properties:
    instance_type: Standard_D2
compilation:
  workers: 1
  network: diego
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: Standard_D2
networks:
- name: diego
  type: manual
  subnets:
  - range: 10.0.32.0/20
    gateway: 10.0.32.1
    dns:
    - 168.63.129.16
    reserved:
    - 10.0.32.2 - 10.0.32.3
    static: 10.0.32.5
    cloud_properties:
      virtual_network_name: ocfboshvnet-crp
      subnet_name: Diego
releases:
- name: diego
  version: 0.1480.0
- name: garden-linux
  version: 0.339.0
- name: cflinuxfs2-rootfs
  version: 1.18.0
- name: etcd
  version: '60'
- name: cf
  version: '239'
update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-120000
jobs:
- name: diego_z1
  instances: 1
  persistent_disk: 102400
  resource_pool: resource_z1
  templates:
  - name: etcd
    release: etcd
  - name: bbs
    release: diego
  - name: auctioneer
    release: diego
  - name: converger
    release: diego
  - name: rep
    release: diego
  - name: garden
    release: garden-linux
  - name: rootfses
    release: diego
  - name: stager
    release: diego
  - name: nsync
    release: diego
  - name: tps
    release: diego
  - name: cc_uploader
    release: diego
  - name: route_emitter
    release: diego
  - name: ssh_proxy
    release: diego
  - name: file_server
    release: diego
  - name: consul_agent
    release: cf
  - name: metron_agent
    release: cf
  networks:
  - name: diego
    static_ips:
    - 10.0.32.5
  update:
    max_in_flight: 1
    serial: true
  properties:
    diego:
      rep:
        zone: "<redacted>"
    metron_agent:
      zone: "<redacted>"
name: cf-diego
director_uuid: eeae003f-281e-43c6-821e-1f7ded5c3bbf
properties:
  consul:
    agent:
      services:
        etcd: {}
      datacenter: "<redacted>"
      log_level: "<redacted>"
      servers:
        lan:
        - "<redacted>"
    agent_cert: "<redacted>"
    agent_key: "<redacted>"
    ca_cert: "<redacted>"
    encrypt_keys:
    - "<redacted>"
    require_ssl: "<redacted>"
    server_cert: "<redacted>"
    server_key: "<redacted>"
  diego:
    auctioneer:
      bbs:
        api_location: "<redacted>"
        ca_cert: "<redacted>"
        client_cert: "<redacted>"
        client_key: "<redacted>"
        client_session_cache_size: "<redacted>"
        max_idle_conns_per_host: "<redacted>"
        require_ssl: "<redacted>"
      cell_state_timeout: "<redacted>"
      dropsonde_port: "<redacted>"
      log_level: "<redacted>"
    bbs:
      active_key_label: "<redacted>"
      auctioneer:
        api_url: "<redacted>"
      ca_cert: "<redacted>"
      dropsonde_port: "<redacted>"
      encryption_keys:
      - label: "<redacted>"
        passphrase: "<redacted>"
      etcd:
        ca_cert: "<redacted>"
        client_cert: "<redacted>"
        client_key: "<redacted>"
        client_session_cache_size: "<redacted>"
        machines:
        - "<redacted>"
        max_idle_conns_per_host: "<redacted>"
        require_ssl: "<redacted>"
      log_level: "<redacted>"
      require_ssl: "<redacted>"
      server_cert: "<redacted>"
      server_key: "<redacted>"
    cc_uploader:
      cc:
        base_url: "<redacted>"
        basic_auth_password: "<redacted>"
        staging_upload_password: "<redacted>"
        staging_upload_user: "<redacted>"
      dropsonde_port: "<redacted>"
      log_level: "<redacted>"
    converger:
      bbs:
        api_location: "<redacted>"
        ca_cert: "<redacted>"
        client_cert: "<redacted>"
        client_key: "<redacted>"
        client_session_cache_size: "<redacted>"
        max_idle_conns_per_host: "<redacted>"
        require_ssl: "<redacted>"
      dropsonde_port: "<redacted>"
      log_level: "<redacted>"
    executor:
      disk_capacity_mb: "<redacted>"
      drain_timeout_in_seconds: "<redacted>"
      garden:
        address: "<redacted>"
        network: "<redacted>"
      garden_healthcheck:
        command_retry_pause: "<redacted>"
        interval: "<redacted>"
        process:
          args: "<redacted>"
          dir: "<redacted>"
          env: "<redacted>"
          path: "<redacted>"
          user: "<redacted>"
        timeout: "<redacted>"
      log_level: "<redacted>"
      memory_capacity_mb: "<redacted>"
    file_server:
      dropsonde_port: "<redacted>"
      log_level: "<redacted>"
    nsync:
      bbs:
        api_location: "<redacted>"
        ca_cert: "<redacted>"
        client_cert: "<redacted>"
        client_key: "<redacted>"
        client_session_cache_size: "<redacted>"
        max_idle_conns_per_host: "<redacted>"
        require_ssl: "<redacted>"
      cc:
        base_url: "<redacted>"
        basic_auth_password: "<redacted>"
        staging_upload_password: "<redacted>"
        staging_upload_user: "<redacted>"
      dropsonde_port: "<redacted>"
      log_level: "<redacted>"
    rep:
      bbs:
        api_location: "<redacted>"
        ca_cert: "<redacted>"
        client_cert: "<redacted>"
        client_key: "<redacted>"
        client_session_cache_size: "<redacted>"
        max_idle_conns_per_host: "<redacted>"
        require_ssl: "<redacted>"
      dropsonde_port: "<redacted>"
      evacuation_timeout_in_seconds: "<redacted>"
      log_level: "<redacted>"
    route_emitter:
      bbs:
        api_location: "<redacted>"
        ca_cert: "<redacted>"
        client_cert: "<redacted>"
        client_key: "<redacted>"
        client_session_cache_size: "<redacted>"
        max_idle_conns_per_host: "<redacted>"
        require_ssl: "<redacted>"
      dropsonde_port: "<redacted>"
      log_level: "<redacted>"
      nats:
        machines:
        - "<redacted>"
        password: "<redacted>"
        port: "<redacted>"
        user: "<redacted>"
    ssh_proxy:
      bbs:
        api_location: "<redacted>"
        ca_cert: "<redacted>"
        client_cert: "<redacted>"
        client_key: "<redacted>"
        client_session_cache_size: "<redacted>"
        max_idle_conns_per_host: "<redacted>"
        require_ssl: "<redacted>"
      diego_credentials: "<redacted>"
      dropsonde_port: "<redacted>"
      enable_cf_auth: "<redacted>"
      enable_diego_auth: "<redacted>"
      host_key: "<redacted>"
      servers:
      - "<redacted>"
      uaa_secret: "<redacted>"
      uaa_token_url: "<redacted>"
    ssl:
      skip_cert_verify: "<redacted>"
    stager:
      bbs:
        api_location: "<redacted>"
        ca_cert: "<redacted>"
        client_cert: "<redacted>"
        client_key: "<redacted>"
        client_session_cache_size: "<redacted>"
        max_idle_conns_per_host: "<redacted>"
        require_ssl: "<redacted>"
      cc:
        base_url: "<redacted>"
        basic_auth_password: "<redacted>"
        staging_upload_password: "<redacted>"
        staging_upload_user: "<redacted>"
      dropsonde_port: "<redacted>"
      insecure_docker_registry_list: "<redacted>"
      log_level: "<redacted>"
    tps:
      bbs:
        api_location: "<redacted>"
        ca_cert: "<redacted>"
        client_cert: "<redacted>"
        client_key: "<redacted>"
        client_session_cache_size: "<redacted>"
        max_idle_conns_per_host: "<redacted>"
        require_ssl: "<redacted>"
      cc:
        base_url: "<redacted>"
        basic_auth_password: "<redacted>"
        staging_upload_password: "<redacted>"
        staging_upload_user: "<redacted>"
      dropsonde_port: "<redacted>"
      log_level: "<redacted>"
      traffic_controller_url: "<redacted>"
  etcd:
    ca_cert: "<redacted>"
    client_cert: "<redacted>"
    client_key: "<redacted>"
    cluster:
    - instances: "<redacted>"
      name: "<redacted>"
    - instances: "<redacted>"
      name: "<redacted>"
    - instances: "<redacted>"
      name: "<redacted>"
    - instances: "<redacted>"
      name: "<redacted>"
    - instances: "<redacted>"
      name: "<redacted>"
    - instances: "<redacted>"
      name: "<redacted>"
    election_timeout_in_milliseconds: "<redacted>"
    heartbeat_interval_in_milliseconds: "<redacted>"
    machines:
    - "<redacted>"
    peer_ca_cert: "<redacted>"
    peer_cert: "<redacted>"
    peer_key: "<redacted>"
    peer_require_ssl: "<redacted>"
    require_ssl: "<redacted>"
    server_cert: "<redacted>"
    server_key: "<redacted>"
  garden:
    allow_host_access: "<redacted>"
    allow_networks: "<redacted>"
    deny_networks:
    - "<redacted>"
    disk_quota_enabled: "<redacted>"
    enable_graph_cleanup: "<redacted>"
    insecure_docker_registry_list: "<redacted>"
    listen_address: "<redacted>"
    listen_network: "<redacted>"
    log_level: "<redacted>"
    mount_btrfs_loopback: "<redacted>"
    network_mtu: "<redacted>"
    persistent_image_list:
    - "<redacted>"
  loggregator:
    dropsonde_incoming_port: "<redacted>"
    etcd:
      machines:
      - "<redacted>"
    tls:
      ca: "<redacted>"
  loggregator_endpoint:
    shared_secret: "<redacted>"
  metron_agent:
    deployment: "<redacted>"
    dropsonde_incoming_port: "<redacted>"
    preferred_protocol: "<redacted>"
    tls_client:
      cert: "<redacted>"
      key: "<redacted>"
  metron_endpoint:
    shared_secret: "<redacted>"
  nats:
    machines:
    - "<redacted>"
    password: "<redacted>"
    port: "<redacted>"
    user: "<redacted>"
  syslog_daemon_config:
    address: "<redacted>"
    port: "<redacted>"

Deploying
---------

Director task 1348
  Started preparing deployment > Preparing deployment. Failed: Job 'rootfses' not found in Template table (00:00:00)

Error 100: Job 'rootfses' not found in Template table

Task 1348 error

For a more detailed error report, run: bosh task 1348 --debug
--------------------------------------------------------------------------------------------

D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: Migrated cloud config manifest:
{"resource_pools"=>[{"name"=>"resource_z1", "network"=>"diego", "stemcell"=>{"name"=>"bosh-azure-hyperv-ubuntu-trusty-go_agent", "version"=>"3262.4"}, "cloud_properties"=>{"instance_type"=>"Standard_D2"}}], "compilation"=>{"workers"=>1, "network"=>"diego", "reuse_compilation_vms"=>true, "cloud_properties"=>{"instance_type"=>"Standard_D2"}}, "networks"=>[{"name"=>"diego", "type"=>"manual", "subnets"=>[{"range"=>"10.0.32.0/20", "gateway"=>"10.0.32.1", "dns"=>["168.63.129.16"], "reserved"=>["10.0.32.2 - 10.0.32.3"], "static"=>"10.0.32.5", "cloud_properties"=>{"virtual_network_name"=>"ocfboshvnet-crp", "subnet_name"=>"Diego"}}]}]}
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000132s) SET standard_conforming_strings = ON
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000095s) SET client_min_messages = 'WARNING'
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000093s) SET DateStyle = 'ISO'
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000160s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000734s) SELECT * FROM "deployments" WHERE ("name" = 'cf-diego') LIMIT 1
I, [2016-08-25 08:01:22 #8568] [task:1348]  INFO -- DirectorJobRunner: Creating deployment plan
I, [2016-08-25 08:01:22 #8568] [task:1348]  INFO -- DirectorJobRunner: Deployment plan options: {"recreate"=>false, "skip_drain"=>nil, "job_states"=>{}}
D, [2016-08-25 08:01:22 #8568] [] DEBUG -- DirectorJobRunner: (0.007490s) UPDATE "locks" SET "expired_at" = '2016-08-25 08:01:33.849909+0000' WHERE (("name" = 'lock:deployment:cf-diego') AND ("uid" = 'd28be414-93ed-456f-b636-9e1487add401'))
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: reserved ranges #<Set: {}>
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000126s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000108s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000314s) SELECT * FROM "releases" WHERE ("name" = 'etcd') LIMIT 1
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000122s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000106s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000339s) SELECT * FROM "release_versions" WHERE (("release_versions"."release_id" = 27) AND ("version" = '60')) LIMIT 1
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000125s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.001091s) SELECT "templates".* FROM "templates" INNER JOIN "release_versions_templates" ON ("release_versions_templates"."template_id" = "templates"."id") WHERE ("release_versions_templates"."release_version_id" = 32)
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000115s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000104s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000294s) SELECT * FROM "releases" WHERE ("name" = 'diego') LIMIT 1
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000120s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000104s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000324s) SELECT * FROM "release_versions" WHERE (("release_versions"."release_id" = 25) AND ("version" = '0.1480.0')) LIMIT 1
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000107s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.001227s) SELECT "templates".* FROM "templates" INNER JOIN "release_versions_templates" ON ("release_versions_templates"."template_id" = "templates"."id") WHERE ("release_versions_templates"."release_version_id" = 30)
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000116s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000106s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000176s) SELECT * FROM "releases" WHERE ("name" = 'garden-linux') LIMIT 1
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000107s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000101s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000192s) SELECT * FROM "release_versions" WHERE (("release_versions"."release_id" = 26) AND ("version" = '0.339.0')) LIMIT 1
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000107s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000435s) SELECT "templates".* FROM "templates" INNER JOIN "release_versions_templates" ON ("release_versions_templates"."template_id" = "templates"."id") WHERE ("release_versions_templates"."release_version_id" = 31)
D, [2016-08-25 08:01:22 #8568] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000225s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000106s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000110s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.005006s) DELETE FROM "locks" WHERE (("name" = 'lock:deployment:cf-diego') AND ("uid" = 'd28be414-93ed-456f-b636-9e1487add401'))
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:cf-diego uid: d28be414-93ed-456f-b636-9e1487add401
I, [2016-08-25 08:01:22 #8568] [task:1348]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"932ef3d5-0310-419a-994f-357cae775e00","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'cf-diego' against Director 'eeae003f-281e-43c6-821e-1f7ded5c3bbf': #<RuntimeError: Job 'rootfses' not found in Template table>","created_at":1472112082}
E, [2016-08-25 08:01:22 #8568] [task:1348] ERROR -- DirectorJobRunner: Job 'rootfses' not found in Template table
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/job_spec_parser.rb:163:in `block in parse_templates'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/job_spec_parser.rb:134:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/job_spec_parser.rb:134:in `parse_templates'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/job_spec_parser.rb:30:in `parse'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/job.rb:90:in `parse'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/deployment_spec_parser.rb:88:in `block in parse_jobs'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/deployment_spec_parser.rb:84:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/deployment_spec_parser.rb:84:in `parse_jobs'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/deployment_spec_parser.rb:22:in `parse'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/planner_factory.rb:75:in `parse_from_manifest'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/deployment_plan/planner_factory.rb:41:in `create_from_manifest'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/jobs/update_deployment.rb:52:in `block (2 levels) in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/event_log.rb:91:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/event_log.rb:91:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/jobs/update_deployment.rb:50:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/lock_helper.rb:13:in `block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/lock.rb:53:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/lock_helper.rb:13:in `with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/jobs/update_deployment.rb:43:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/job_runner.rb:94:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3232.2.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/jobs/db_job.rb:24:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3232.2.0/lib/bosh/director/jobs/db_job.rb:75:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000122s) SELECT NULL
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000072s) BEGIN
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.000568s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2016-08-25 08:01:22.887917+0000', "description" = 'create deployment', "result" = 'Job ''rootfses'' not found in Template table', "output" = '/var/vcap/store/director/tasks/1348', "checkpoint_time" = '2016-08-25 08:01:22.808941+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'cf-diego', "started_at" = '2016-08-25 08:01:22.808875+0000' WHERE ("id" = 1348)
D, [2016-08-25 08:01:22 #8568] [task:1348] DEBUG -- DirectorJobRunner: (0.009838s) COMMIT
I, [2016-08-25 08:01:22 #8568] []  INFO -- DirectorJobRunner: Task took 0.0932104 seconds to process.

**Comment by sethvargo** [comment]
Please stop opening issues related to bosh deployment failures on this tool. There is nothing in the logs that indicate an issue with Consul Template.
