### ISSUE TITLE
feature request: pull consul-template config and templates from consul

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/consul-template#705]
ATM, when we go to deploy and use consul-template, we need to load up the host with templates and config for those templates before consul-template will know what to do. While thinking about how to best use consul-template with nomad, I stumbled upon this thought of pulling config/templates for consul-template from consul. In other words, on each host, I would tell consul-template how to get connected to consul, and then consul-template would pull the remainder of the config and templates from KV. In some ways, we could consider config/template separate features, but I've bundled them together in this initial "hey, does this make sense for the project?"

Consul-template would need to be provided a KV path prefix to monitor, and that path could be the same or different for each host - that would leave the question of "targeting" on the ops user instead of having consul-template figure that out.

**Comment by stevenscg** [comment]
FWIW, the current git2consul project does something similar to configure itself, but they identified some issues with that. I don't recall the specifics, but in their golang-based rewrite of the project, they are specifically moving away from storing their config in the KV.

**Comment by ketzacoatl** [comment]
That is good to know, it would probably help to review what specific issues they ran into. I've had good luck "configuring through consul" so far in my use. Similarly, fabio - https://github.com/eBay/fabio - exemplifies how well this can work out.

**Comment by sethvargo** [comment]
Hi there,

This is not something we plan to support. If you want this behavior on your own, you can use the `key` functionality to render a template to disk, and then have an auxillary CT process read from that rendered file and parse your correct result.

**Comment by ketzacoatl** [comment]
OK, fair enough, thanks!
