### ISSUE TITLE
Why store_key_prefix.go is changed to ensure trailing slash?

### ISSUE THREAD

**Issue by vfahrenheit** [hashicorp/consul-template#706]
We found that after consul-template 0.15 the  store_key_prefix.ParseStoreKeyPrefix() is  changed to ensure trailing slash.
But in our configuration management solution, we need to monitor some keys with special prefix

For example, we have following keys in k/v store:

- configs/node-all_config1
- configs/node-all_config2
- configs/node-1_config1
- configs/node-2_config1

 (and they are not suitable to store in sub directory for some reasons)

we may want to just monitor  keys start with configs/node-all_
It's possible with consul-template before 0.15, but now It's not possible after 0.15.
Is it a mandatory change for some architecture improvement or restriction?

### References
https://github.com/hashicorp/consul-template/commit/c745f2122fb10cdc7e012d58e96cc3373d17aaad

**Comment by sethvargo** [comment]
Consul Replicate needs to be a folder, but I guess that same requirement isn't true for Consul Template. /cc @slackpad to confirm

**Comment by slackpad** [comment]
Yeah it's legit to watch a key prefix without a trailing slash to monitor an individual key. CT should be more lenient.
