### ISSUE TITLE
in/contains doesn't work on parsed json array

### ISSUE THREAD

**Issue by rayward** [hashicorp/consul-template#708]
Consul Template version: v0.15.0

I have a template that passes services into a plugin which then organises them by port, which I then use to build a haproxy config.

After parsing the json, the `in` and `contains` functions do not work on the `Tags` field, the statement always returns false.

Given a service that has the tag `haproxy-secure`, this template effectively demonstrates the issue without the plugin.

```liquid
{{with node}}{{range .Services | toJSON | parseJSON -}}
    {{if .Tags}}
    {{printf "%#v" .Tags}}
    {{in .Tags "haproxy-secure"}}
    {{end}}
{{end}}{{end}}

{{with node}}{{range .Services -}}
    {{if .Tags}}
    {{printf "%#v" .Tags}}
    {{in .Tags "haproxy-secure"}}
    {{end}}
{{end}}{{end}}
```

Output:
```
    []interface {}{"domain:bcapp.dev", "haproxy-secure"}
    false
    []interface {}{"domain:bcapp.dev", "haproxy"}
    false

    dependency.ServiceTags{"domain:bcapp.dev", "haproxy-secure"}
    true
    dependency.ServiceTags{"domain:bcapp.dev", "haproxy"}
    false
```

**Comment by sethvargo** [comment]
Hi there,

This is the expected behavior. When you parse something as JSON, it's parsed into an untyped interface (notice how it's `[]interface{}`). We do as much reflection as possible, but there's basically no way for us to know the underlying data structure contains strings. You lose all type information when marshaling/unmarshaling to JSON.

**Comment by rayward** [comment]
It appears that the underlying type data for each element of an `[]interface{}` gets lost when calling `lv.Index(i)` here: https://github.com/hashicorp/consul-template/blob/master/template_functions.go#L489

I believe I have fix that works by first checking whether the list is an `[]interface{}` and then extracting the element directly (ie. `l[i]`) and reflecting its value which correctly exposes the type of each individual element. 

Will open a PR.
