### ISSUE TITLE
why consul-template take up 5000 port

### ISSUE THREAD

**Issue by 467754239** [hashicorp/consul-template#715]
$ sudo  netstat -tnlp | grep 5000
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      5249/consul-templat

**Comment by sethvargo** [comment]
Can you please provide additional information? Consul Template maintains a connection to consul via the local consul agent, which defaults to port 8500.

**Comment by sethvargo** [comment]
Closing due to lack of response.

**Comment by 467754239** [comment]
I'm sorry Just see here can reply now?

**Comment by 467754239** [comment]
If I can continue to describe the problem here
