### ISSUE TITLE
Allow Consul KV as Template Source

### ISSUE THREAD

**Issue by robottaway** [hashicorp/consul-template#728]
Currently we have a few issues with boilerplate related to Consul-Template. We store configuration files directly into Consul KV rather than sparse values in tree.

This means the whole configuration file is one value, for example given key `pd-infrastructure/burgundy/lord/application.yml` we return:

```yaml
log_level: warn
cluster_name: bonkers
```

Now we want to be able to fully edit this configuration and have the result update on filesystem w/o having to muck about with any ctmpl files on host. So to accomplish this we create a template that more or less is an `id` function and it looks like:

```
{{ key "pd-infrastructure/burgundy/lord/application.yml" }}
```

We have been doing this quite a bit actually and feels non-productive with smells of boilerplate. Can we add a new source type that allows for reading template directly out Consul KV? For example configuration:

```
template {
  kvsource = "pd-infrastructure/burgundy/lord/application.yml.ctmpl"
  destination = "/etc/lord/application.yml"
  backup = false
}
```

This would solve another problem we have which is using the `id` function template we are unable to take advantage of template constructs such as `service`, `services` or `secret`.

At the end of the day we want to be able to better manage the static and dynamic content via Consul + Consul-Template without having to be further burdened by another system that handles the life cycle of the templates on host (in our case Chef).

Is there any interest and if so how difficult would it be for someone like myself (Go programmer no experience with project) to to put together a PR?

### Consul Template version

Consul 'v0.6.4-380-gfd9a0b7'.dev ('fd9a0b7e969eb790c442314eac9d939e22e528d3')
Consul Protocol: 3 (Understands back to: 1)

### Configuration

```javascript
consul = "127.0.0.1:8500"
retry = "10s"
max_stale = "10m"
log_level = "warn"
wait = "5s:10s"
template {
  source = "/etc/consul-template/templates/lord/unicorn.conf.rb.ctmpl"
  destination = "/etc/lord/unicorn.conf.rb"
  backup = false
}
template {
  source = "/etc/consul-template/templates/lord/environment.yml.ctmpl"
  destination = "/etc/lord/environment.yml"
  backup = false
}
template {
  source = "/etc/consul-template/templates/lord/database.yml.ctmpl"
  destination = "/etc/lord/database.yml"
  backup = false
}
template {
  source = "/etc/consul-template/templates/lord/lord.nginx.conf.ctmpl"
  destination = "/etc/nginx/sites-enabled/lord.conf"
  backup = false
}
template {
  source = "/etc/consul-template/templates/lord/amun_handler.yml.ctmpl"
  destination = "/opt/serf/handlers/config/amun/burgundy-lord.yml"
  backup = false
}
vault {
  address = "https://vault.query.consul:8200"
  token = "<redacted>"
  renew = false
  ssl {
    // verify the vault server certificate
    verify = true
    ca_cert = "/etc/vault/internal_ca_cert_chain.pem"
  }
}
```
Looking at the `/etc/consul-template/templates/ruler/amun_handler_ruler.yml.ctmpl ` template we have basically an `id` function which takes the config file data straight out of Consul.

```liquid
{{ key "/pd-infrastructure/load_test/burgundy/ruler/amun_handler_ruler.yml" }}
```

**Comment by sethvargo** [comment]
https://github.com/hashicorp/consul-template/issues/711
