### ISSUE TITLE
Allow a colon in the -template option command

### ISSUE THREAD

**Issue by anthonysterling** [hashicorp/consul-template#731]
Hello.

I've come across a use case where, when using the `-template` option, we need to use a colon in the command to be executed once the template has been generated - for instance:-

`consul-template -template=''/tmp/template.ctmpl:/var/www/.env:/var/www/bin/cli cache:clear"`

At the moment this fails because the `Config::ParseConfigTemplate` essentially just splits on the colon and expects a maximum of 3 parts - and this produces 4.

Before I create a PR, I wanted to make sure that a) I'm not being thick, and b) That this functionality is required and/or expected?

Thank you.

**Comment by sethvargo** [comment]
Hi @anthonysterling 

You welcome to submit a PR, but I think a better solution for your use case would to be to use the configuration file. It will give you additional control over the command and other options that aren't available via the CLI.
