### ISSUE TITLE
trying to use w/ httpd, keeps dying

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/consul-template#739]
I start it up:
```
consul-template \
     -consul=${CONSUL_HOST_PORT} \
     -log-level=debug \
     -exec="/usr/sbin/httpd -D FOREGROUND" \
     -config="/etc/consul-configs"
```

Httpd launches fine, however consul-template immediately dies with no info as to why
```
httpd (pid 10) already running
2016/10/06 20:53:31.233432 [INFO] (runner) child process died
2016/10/06 20:53:31.233480 [DEBUG] (cli) receiving signal "child exited"
Consul Template returned errors:
child process died with exit code 0
```

**Comment by jippi** [comment]
`httpd (pid 10) already running` seems like the processes is already running elsewhere.. ensure no httpd process run before starting consul-template

**Comment by sethvargo** [comment]
This is not a CT issue. The child process is dying and CT is exiting with that child processes exit code as documented in exec mode.
