### ISSUE TITLE
No command line or env option for vault-address?

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/consul-template#740]
Is there no way to configure the vault address other than in a config file?

**Comment by erydo** [comment]
`VAULT_ADDR` should work. That's what we use.

**Comment by sethvargo** [comment]
You can use the VAULT_ADDR environment variable, but we'll get this added to the CLI too.

**Comment by bitsofinfo** [comment]
Cool, also doc update as well, thanks!
