### ISSUE TITLE
Error renewing vault token, despite "-vault-renew-token=false"

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/consul-template#741]
Starting consul-template 0.16 like this

```
consul-template \
     -consul=${CONSUL_HOST_PORT} \
     -vault-token=${VAULT_TOKEN} \
     -vault-renew-token=false \
     -log-level=debug \
     -exec="/usr/sbin/httpd -D FOREGROUND" \
     -exec-reload-signal=SIGUSR1 \
     -exec-kill-signal=SIGTERM \
     -config="/etc/consul-configs"
```

VAULT_TOKEN is set = to the initial root token

When this starts up it errors with

```
2016/10/07 20:19:28.825513 [DEBUG] (runner) detected custom error type
2016/10/07 20:19:28.825524 [DEBUG] (runner) custom error asked for hard exit
Consul Template returned errors:
error renewing vault token: Error making API request.

URL: PUT http://vault:32775/v1/auth/token/renew-self
Code: 400. Errors:

* lease not found or lease is not renewable
```

How can I get around this?

**Comment by erydo** [comment]
What version of Vault are you using? [Vault 0.6.1](https://github.com/hashicorp/vault/blame/80281c16fcaab7aa2ad0a67816c0bdc307476a80/CHANGELOG.md#L287) fixed an issue (https://github.com/hashicorp/vault/pull/1692) in which root tokens were incorrectly marked as renewable.

That said, it looks like `consul-template` shouldn't be attempting to renew anyway if it was explicitly told not to.

A quick glance shows that [`cli.go:420`](https://github.com/hashicorp/consul-template/blob/5829a9081da5efe6103103c2f5e636890ff8ea0c/cli.go#L420) sets the config var `"vault.renew"`:
```go
	flags.Var((funcBoolVar)(func(b bool) error {
		conf.Vault.RenewToken = b
		conf.Set("vault")
		conf.Set("vault.renew")
		return nil
	}), "vault-renew-token", "")
```

But [`config.go:476`](https://github.com/hashicorp/consul-template/blob/5829a9081da5efe6103103c2f5e636890ff8ea0c/config/config.go#L476) says that it probably should be setting `"vault.renew_token"` instead:
```go
	if vault, ok := parsed["vault"].(map[string]interface{}); ok {
		if val, ok := vault["renew"]; ok {
			log.Println(`[WARN] vault.renew has been renamed to vault.renew_token. ` +
				`Update your configuration files and change "renew" to "renew_token".`)
			vault["renew_token"] = val
			delete(vault, "renew")
		}
	}
```

I'm not set up for Go development right now, but maybe that's helpful to someone attempting to track it down…

**Comment by bitsofinfo** [comment]
The only way I could get it to work was to put this in a config file:

```
vault {
    renew_token = false
}
```
