### ISSUE TITLE
Exec mode with multiple "template" declarations

### ISSUE THREAD

**Issue by stevenscg** [hashicorp/consul-template#750]
I wanted to follow-up with the thread I started last week on the mailing list:
https://groups.google.com/forum/#!topic/consul-tool/8N9g6yx4ac8

Summary:
Should exec mode work with more than 1 "template" declaration?

The docs seem to indicate that multiple "template" declarations are allowed with exec, but the examples only show one.

Running CT with 1 "template" declaration is stable for me. More than 1 "template" results in my exec-monitored process reloading every 6-8 minutes as different templates are rendered. No Consul KV changes were being made during this time.

I see this behavior in v0.16.0 and v0.17.0-dev as of October 8, both running against Consul 0.7.0.

I'm not a Go dev, but it looks to me like the "exec" mode tests in `runner_test.go` only uses a single "template" directive.

Happy to help. Let me know.

**Comment by sethvargo** [comment]
Hi @stevenscg 

Can you please share your debug output when this happens?

**Comment by stevenscg** [comment]
Hi @sethvargo 

I just emailed you the debug output.

**Comment by sethvargo** [comment]
Hi @stevenscg 

Can you try disabling de-duplication please? It looks like that is what is causing the template to "change".

**Comment by stevenscg** [comment]
Disabling `deduplicate` did not have any noticeable change in the issue.

Removing `wait = "5s:10s"` results in the the proper (stable) operation as far as I can tell.

Adding `deduplicate` back in (without `wait`) also results in the proper operation.

Logs for both scenarios are attached.
[ct-stdout-no-deduplicate.txt](https://github.com/hashicorp/consul-template/files/525983/ct-stdout-no-deduplicate.txt)
[ct-stdout-no-wait.txt](https://github.com/hashicorp/consul-template/files/525984/ct-stdout-no-wait.txt)

**Comment by sethvargo** [comment]
Hi @stevenscg 

Thank you for your patience on this. I just tried using master, and I am unable to reproduce this issue. Could you please share your complete template configuration so I can try to reproduce this?

I've tested exec mode with many templates, and the process is always restarted the appropriate number of times.

**Comment by stevenscg** [comment]
Hi @sethvargo 

I'll have to dust off this use case and try it with the latest Consul version. I haven't been back to it since October or November.

**Comment by sethvargo** [comment]
Hey @stevenscg 

I was wondering if you've had a chance to update to v0.18.0 and see if that fixes your changes.

**Comment by stevenscg** [comment]
Hi Seth. I got a test environment ready, but didn't get a chance to run the test yet. Will report back in a few days.

- Chris

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/consul-template/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by dwimberger** [comment]
I have seen this problem occur if the additional templates contain a certificate issue request and the PKI Role was not configured correctly (Generate Lease = true).
See #1071
