### ISSUE TITLE
Add Pipeline Ternary Function

### ISSUE THREAD

**Issue by nugend** [hashicorp/consul-template#753]
Go Template lacks a ternary function for evaluating and returning one or another value based on the value of a boolean inside of template pipelines. Since it seems Go's implementors don't find such a feature compelling, it would be very convenient for users to have one implemented by consul-template.

If such a feature already exists and I've spent the last several hours assiduously googling for naught, then I apologize.

**Comment by sethvargo** [comment]
Can you provide an example?

**Comment by nugend** [comment]
Not sure I understand what you're asking for an example of.

**Comment by sethvargo** [comment]
I'm looking for an example of what you mean by a "ternary function". What do you want to do with it? We have a number of helpers like `key_or_default`, and it is possible to use conditionals in Go's templating language. I'm trying to understand what you're trying to do

**Comment by nugend** [comment]
> it is possible to use conditionals in Go's templating language

Is it possible to use a conditional within a pipeline?

What I mean is a situation like the following. I will use a C like `?:` syntax to demonstrate:

In this hypothetical situation, we have to produce pairs of service name and "guarantee" for the system reading the configuration.

```
{{range services}} 
{{$serviceName := .Name}}
{{with tree (printf "kv/configs/service/%s" $serviceName) | explode }}
{{range $g := ((in .ServiceType "user") ? "highspeed,durable,reliable" : "lowspeed,reliable,restart") | split "," }}
Name={{$serviceName}},Guarantee={{$g}}
{{end}}
{{end }}
```

In this case, it's doesn't feel appropriate to put the guarantees in Consul, because they only exist as a translation to the configuration file format's interpretation of our service types.

**Comment by sethvargo** [comment]
Hi @nugend 

Thank you for providing that example. It's very unlikely we will add something like this to Consul Template. Templates are designed to be descriptive, so adding business logic to the template is outside of the scope. This is probably similar reasoning you heard from the Go core team. A more declarative approach is as follows:

```liquid
{{range services}} 
{{$serviceName := .Name}}
{{with tree (printf "kv/configs/service/%s" $serviceName) | explode }}
{{ if .ServiceType | contains "user" }}
{{ range $g := "highspeed,durable,reliable" | split "," }}
Name={{$serviceName}},Guarantee={{$g}}
{{ end }}
{{ else }}
{{ range $g := "lowspeed,reliable,restart" | split "," }}
Name={{$serviceName}},Guarantee={{$g}}
{{ end }}
{{ end }}
{{ end }}
```

Alternatively, you could [author a small plugin](https://github.com/hashicorp/consul-template#plugins) which could perform this data manipulation for you.

Thanks and have a great day! 😄

**Comment by nugend** [comment]
I strongly, *strongly* disagree with this decision.
