### ISSUE TITLE
using contents under a template results in invalid key

### ISSUE THREAD

**Issue by nwalke** [hashicorp/consul-template#754]
### Consul Template version
0.16.0

### Configuration
```liquid
template {
  destination = "/etc/haproxy/certs.d/somesite.pem"
  contents = "{{key \"certificates/somesite\"}}"
  command = "service haproxy restart"
  perms = 0600
}
```

### Command

```shell
consul-template -config=consul-template.conf
```

### Debug output
```
Consul Template returned errors:
1 error(s) occurred:

* 1 error(s) decoding:

* 'template[1]' has invalid keys: contents
```

### Expected behavior
According to the README, I can pass in the contents here.

### Actual behavior
It tells me that it's an invalid key.

### Steps to reproduce
1. Set up a template under your consul-template config
2. Use the `contents` key to put in the value of a key from Consul
3. Run it

**Comment by nwalke** [comment]
Just to give some context about what I'm trying to do...

I need to render out certificates dynamically as they're added through our web application.  I currently have consul-template writing its own configuration file in order to accomplish this.

If anyone knows a better way to have dynamic templates, I'd love to hear it.

**Comment by dadgar** [comment]
Hey please see the README tagged at 0.16, this is a feature that only exists on master

**Comment by nwalke** [comment]
Yup, sorry about this.  Was able to compile from master and got it working.

**Comment by dadgar** [comment]
No worries! Glad you figured it out!
