### ISSUE TITLE
how can i get map keys from 'byKey' function result?

### ISSUE THREAD

**Issue by zhanglongqiang** [hashicorp/consul-template#774]
data structure in consul:

```
/region/e1/az/a1/
/region/e1/az/a2/
/region/e1/az/a3/
```

i want to get the az list as json string, like this: ["a1","a2", "a3"].

what i had try:

```liquid
[{{range $key, $pairs := tree "region/e1/az"|byKey}}"{{$key}}"{{end}}]
```

but result is:

```
["a1","a2","a3",]
```

as you see , a useless comma near the end of json string.

i also tried use 'join' function ({{$items join ","}}), but how can i get an array as the '$items'??

**Comment by sethvargo** [comment]
https://github.com/hashicorp/consul-template/issues/263#issuecomment-97074185

**Comment by zhanglongqiang** [comment]
Thanks for the quickly reply. 

But I tried the 'index',  it's not take effect in map. 
the template: 
[{{range $index, $key, $pairs := tree "region/e1/az" | byKey}}{{if ne $index  0}},{{end}}"{{$key}}"{{end}}]

error occurs:
template: template: test.ctmpl:8: too many declarations in range

what i want is only the keys of a map from 'byKey' result. Is there any thing i go wrong?
