### ISSUE TITLE
Support for altering log format

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/consul-template#775]
Would love to see an option to adjust the log format. 

I am running this in a container where both `consul-template` and my app log to STDOUT/STDERR, my app also can issue log statements w/ multiple lines. By not having any access to control `consul-template's` log format, I can't rely on a consistent start/end format to each log statement that delineates the start end of a new log statement (single or multiple lines)

We are using fbeats/logstash to consume the logs collected by each docker host

**Comment by sethvargo** [comment]
Hi @bitsofinfo 

Thank you for opening an issue. Could you elaborate a bit more by what you mean? How would you like to adjust it? Consul Template supports logging to syslog. All logs will be prefixed with a ts and one of:

```
[TRACE]
[DEBUG]
[WARN]
[INFO]
[ERR]
```

**Comment by bitsofinfo** [comment]
i.e. a configuration property that would allow you to specify a custom log string, something similar to how one can create a custom log format in apache etc.

i.e.

```
{
  ...
  log_level: "warn", 

  log_format: "mycustomstring %timestamp %ENV[varname] %severity [%severity] %msg"
```

etc

**Comment by bitsofinfo** [comment]
Also any possibility of wrapping any log output in JSON would be great (to kill multilines) such as when in debug mode, the config being dumped over many lines

**Comment by bitsofinfo** [comment]
#779

**Comment by falkenbt** [comment]
We're also having issues with the fixed timezone that is set to UTC. All our applications log in servertime (which is not UTC) so you constantly have to convert. Of course I would rather have all our server running in UTC but that's is not possible in our case. It looks like the Go log package is pretty limited in terms of configuration.

**Comment by sethvargo** [comment]
Hi @bitsofinfo 

We use Go's logging package, which does not give us a ton of flexibility on the logging format. In the future, we plan to support things like logstash, circonus, etc as first-class citizens. Thanks! 😄

**Comment by pbar1** [comment]
Any chance this can be reopened? Would be quite a big help
