### ISSUE TITLE
Add support for "scratch"

### ISSUE THREAD

**Issue by jippi** [hashicorp/consul-template#780]
Hi,

Would be nice if templates could include http://gohugo.io/extras/scratch/ 

To fix cases like this; https://github.com/golang/go/issues/10608 :) 

I keep hitting that kind of scoping challenges when i write my templates

**Comment by sethvargo** [comment]
Duplicate of https://github.com/hashicorp/consul-template/issues/760, and I'm in favor of it. I just need to find time to do it 😄

**Comment by ewah** [comment]
I've got a PR w/ something closed to the scratch functionality (missing Add, but incorporates some of methods found in Java.Map)  #768 

Let me know if that works out for you.
