### ISSUE TITLE
Exits always with error code 12 when stopped gracefully

### ISSUE THREAD

**Issue by kivoli** [hashicorp/consul-template#782]
### Consul Template version
v0.16.0 (also tested with master)

### Configuration
N/A

### Command

```shell
./consul-template -kill-signal=SIGINT
```

### Debug output
Last line:
```
[DEBUG] (runner) child is not running
```

### Expected behavior
If the appropriate signal is sent to the process (as set per `-kill-signal`) the process should exit with status code 0. This is especially important when using `SIGTERM` in Systemd. According to the documentation, `SIGTERM` is the default signal to gracefully stop consul-template. 

### Actual behavior
Regardless whether the `-kill-signal` option has been specified or not, consul-template always exits with status code 12. 

This is most likely “as implemented”, see:
https://github.com/hashicorp/consul-template/blob/master/cli.go#L143
Snippet:

```golang
      case config.KillSignal:
        fmt.Fprintf(cli.errStream, "Cleaning up...\n")
        runner.Stop()
        return ExitCodeInterrupt
```
In my opinion the last line should return `ExitCodeOK` but it may be intended for some reason I’m unaware of. 

### Steps to reproduce
1. Start consul-template with `-kill-signal=SIGINT`
2. Ctrl+C
3. `echo $?`

**Comment by sethvargo** [comment]
Hi @kivoli 

Thank you for opening an issue. This is a tricky one... I see both sides of the argument, but, in general, tools don't exit with 0 when interrupted. I'm going to ask @slackpad and @kyhavlov to weigh in here, because I could be persuaded either way.

**Comment by kivoli** [comment]
Hi @sethvargo,

the challenge I face is that I use a systemd service unit to manage consul-template and it always goes into failed state due to there not being any way to stop consul-template gracefully, i.e. with an exit code of 0.

**Comment by jen20** [comment]
@kivoli You can also prefix the `ExecStart` in systemd unit with `-` to ignore the error code here.

**Comment by kivoli** [comment]
@jen20 That’s a possibility but this effectively disables restart-on-failure, too, right?
It’s not _just_ about getting my stuff to work, I would prefer if consul-template behaves as expected. And that probably means that a successful graceful shutdown exits with status code 0. This is also important if you run a script and check the return code or use `set -e`.

**Comment by sethvargo** [comment]
Hi @kivoli 

I've asked a bunch of people smarter than me and the general consensus is that a process that is interrupted should never exit 0, so we are not going to alter this behavior. Thanks! 😄

**Comment by kivoli** [comment]
Hi @sethvargo 

While writing my reply I discovered that the `README.md` has been updated after I pulled my copy of the master branch some time last month. Your commit [e973bf25](https://github.com/hashicorp/consul-template/commit/e973bf255b71ebda3f7a877b2762dc14c35203c3#diff-04c6e90faac2675aa89e2176d2eec7d8R291) from July clearly stated that “[t]he default value is "SIGTERM"”. Now it points to the value “below” which is `SIGINT`.

But this only solves half the puzzle regarding the (mis-)use of `SIGTERM`. What remains is that you talk about “interrupted” while the documentation and I talk about “graceful shutdown”. In the previous version of the README the correct signal for a graceful shutdown, `SIGTERM`, was used not `SIGINT`. The latter would be what you use for “interrupting” a program, i.e. forcefully shutting it down (but not killing it), i.e. via Ctrl+C.
Regarding `SIGTERM`, let me just quote [GNU libc manual](http://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html):

> The SIGTERM signal is a generic signal used to cause program termination. Unlike SIGKILL, this signal can be blocked, handled, and ignored. It is the normal way to politely ask a program to terminate.

Given your wording (“interrupted”) I’m not surprised by the responses you got. But as I said the documentation is very clearly stating that it’s meant for “graceful stop”. A crash landing hardly qualifies as “graceful” in my opinion. 

> This is the signal to listen for to trigger a graceful stop.

In my humble opinion your documentation and your implementation are at odds. Either you do *not* support gracefully stopping consul-template and `SIGINT` is the correct signal or the program should terminate without throwing an error (i.e. exit status unequal 0) when sent `SIGTERM`. 

As I explained above I would really appreciate the latter since other programs like the Init-System could be very much confused by this, frankly, unexpected (mis)behaviour and poor sysamins like myself would get confused by the use of terms like “graceful stop” when it’s actually a hard shutdown.

**Comment by sethvargo** [comment]
The term "graceful" refers to the fact that the tool does not exit immediately and instead finishes any running processes ands shuts down.

**Comment by ldelossa** [comment]
@sethvargo Found this post when using systemd. 

I have a feeling you may find people with a similar issue, only because systemd makes doing service dependencies easy. Consul-template is going to frequently be a service which is depended on. 

In my opinion, a graceful exit should exit in 0 so systemd does not show the service as failed. I'm going to look now in systemd docks to see if you can specify which exit code can be seen as 'successful' But his does cause a small problem, but is easily ignorable if you're taking an immutable infrastructure approach.

**Comment by ldelossa** [comment]
Work Around:

```
SuccessExitStatus=
Takes a list of exit status definitions that, when returned by the main service process, will be considered successful termination, in addition to the normal successful exit code 0 and the signals SIGHUP, SIGINT, SIGTERM, and SIGPIPE. Exit status definitions can either be numeric exit codes or termination signal names, separated by spaces. For example:

SuccessExitStatus=1 2 8 SIGKILL
ensures that exit codes 1, 2, 8 and the termination signal SIGKILL are considered clean service terminations.

Note that if a process has a signal handler installed and exits by calling _exit(2) in response to a signal, the information about the signal is lost. Programs should instead perform cleanup and kill themselves with the same signal instead. See Proper handling of SIGINT/SIGQUIT — How to be a proper program.

This option may appear more than once, in which case the list of successful exit statuses is merged. If the empty string is assigned to this option, the list is reset, all prior assignments of this option will have no effect.
```

My systemd script looks like this now:

```
[Unit]
Description=Consul-Template daemon

[Service]
Type=simple
SuccessExitStatus=12
ExecStart=/opt/consul-template/consul-template -config /etc/consul-template/consul-template.conf
ExecReload=/bin/kill -SIGHUP $MAINPID
ExecStop=/bin/kill -SIGINT $MAINPID

[Install]
WantedBy=multi-user.target
```

Require network to be online is probably a best practice also.
