### ISSUE TITLE
Use CAP_DAC_OVERRIDE for non-root user access to files

### ISSUE THREAD

**Issue by kivoli** [hashicorp/consul-template#783]
This is an enhancement request for the README. 

It’s not too great to run programs as root but it’s tough if your program potentially needs access to any file. Luckily there’s a [capability](https://linux.die.net/man/7/capabilities) called `CAP_DAC_OVERRIDE` which allows a non-root user full file-system access. 
This is of course almost as dangerous as full root privileges but imo still an improvement. Please be aware that the capability seems to be dropped on every change of owner and binary. Also it’s important to tightly restrict the privilege to execute any program which has been granted such a capability, basically the same caution as with set-suid-bit programs should be applied.

### Command

```shell
USER="consul-template"
BINPATH="/usr/bin/consul-template"
chown "${USER}" "${BINPATH}"
chmod 0500 "${BINPATH}"
setcap CAP_DAC_OVERRIDE=+ep "${BINPATH}"
```

Alternatively distributions with a recent enough version of systemd may also be able to leverage `CapabilityBoundingSet` or `AmbientCapabilities`[1](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) to grant this capability only temporarily, although I haven’t been able to test this yet.

**Comment by sethvargo** [comment]
Hi @kivoli 

Thank you for opening an issue. This is useful and has already been indexed by search engines, but I'm hesitant to add something like this to the README, since it's not specific to CT (it applies to any binary), and it could be confusing to users who don't have this problem. Thanks for understanding! 😄
