### ISSUE TITLE
Consul Template fails on mass service restart

### ISSUE THREAD

**Issue by DaveBlooman** [hashicorp/consul-template#785]
We use a large multi tenant server, 25+ services on a C# stack.  When we restart consul or the server, the event causes HAProxy to check these new services, this in turn causes HAProxy to fail.  It seems that HAProxy just stops working as we have a separate health check on HAProxy and it reports back no response.

Our setup is that we have an HAProxy service that filters this 25+ service C# app.  Is there something bad in our consul-template template that looks obvious to break ?  Is the filtering breaking the setup?

```javascript
{{range services}}
{{  if .Tags | contains "foobar" }}{{else}}
acl is_{{.Name}} hdr(host) -i {{.Name}}.service.example.com
{{end}}{{end}}
{{range services}}
{{  if .Tags | contains "foobar" }}{{else}}
use_backend {{.Name}} if is_{{.Name}}
{{end}}{{end}}

{{range services}}
{{ if .Name | contains "consul" }}
backend {{.Name}}
        mode http
        balance roundrobin
        {{range service .Name}}
        server {{.Name}} {{.Address}}:8500 {{end}}
{{ else if .Tags | contains "foobar" }}{{else}}
backend {{.Name}}
	mode http
	balance roundrobin
        option httpchk GET /status HTTP/1.1\r\n\Host:\ {{.Name}}.service.example.com
	{{range service .Name}}
	server {{.Name}} {{.Address}}:{{.Port}} {{end}}
{{end}}{{end}}

```

### Consul Template version
0.16

### Command

```shell
consul-template -consul 127.0.0.1:8500 -template "/etc/haproxy/haproxy.ctmpl:/etc/haproxy/haproxy.cfg:service haproxy restart" -retry 30s
```

### Expected behavior
Server starts, discovers new services, services are updated if needed in HAProxy.

### Actual behavior
HAproxy stops working due to a mass update.

### Steps to reproduce
1. Start new server with multiple services
2. Watch haproxy fail

**Comment by jippi** [comment]
you can add `-wait` to make CT wait for the cluster to settle down before reloading :)

**Comment by sethvargo** [comment]
Hi @DaveBlooman 

As @jippi said, you can use the `-wait` parameter to start the quiescence timers (more detail in the README), and you can also add a final `{{ else }}` block to the condition to ensure there is at least one backend. This will prevent haproxy from completely dying.

In general, restarting one Consul server is fine, but restarting the entire cluster will have dramatic side effects until quorum is reached and the raft log catches up. This is neither a bug in Consul nor Consul Template; it's just the way Consul functions, and it's the reason we recommend cluster sizes or 3, 5, or 7 Consul servers.

Unfortunately I'm not an expert in haproxy configurations, so I cannot comment on whether the configuration is valid. You can, however, check the resulting rendered file on the system and run it through haproxy's validator; this will tell you if it's valid, and, if it's not, where the error is.

Thanks and have a great day! 😄
