### ISSUE TITLE
key_exists documented but returns: function "key_exists" not defined

### ISSUE THREAD

**Issue by richiemarshall** [hashicorp/consul-template#786]
I can see key_exists documented but when trying to use it consul-template returns the error: 
function "key_exists" not defined. I've tried this with 0.15.0, 0.16.0 and master builds. 

I can see the branch where this was added and the merge into master, but since the 5th october key_exists has gone from the master branch. 

### Configuration

```liquid
{{if key_exists "template_values/app.json/prod/version"}}
env:
{{end}}
```

### Command

```shell
/usr/local/bin/consul-template -consul=consul-host:8500 -template ~/git/test/test.ctmpl -once
```

### Debug output
https://gist.github.com/richiemarshall/f2331d5089d128a5171877e8ddd1a40e

### Expected behaviour
The key exists (I am using it in a template with the key_or_default function) so I'm expecting "env:" to be printed

### Actual behavior
template: template: :1: function "key_exists" not defined

### Steps to reproduce
1. Create a key/value in consul
2. Create a simple consul template with an if key_exists statement

### References
#738 
#769

**Comment by sethvargo** [comment]
Hi @richiemarshall 

As mentioned in very bold letters [at the top of the README](https://github.com/hashicorp/consul-template#consul-template), 

> **The documentation in this README corresponds to the master branch of Consul Template. It may contain unreleased features or different APIs than the most recently released version. Please see the Git tag that corresponds to your version of Consul Template for the proper documentation.**

This functionality has not yet been released. Please refer to the documentation for the specific tag of Consul Template which you are running. Thanks! 😄

**Comment by richiemarshall** [comment]
I have built against master and that doesn’t work either, but I don’t know if that’s intentional/known.
