### ISSUE TITLE
v0.18.0-rc1 doesn't set up dedup default fields properly

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul-template#792]
While doing some testing with the dedup manager turned on I noticed that it's now creating sessions with a TTL value of 0. It gets the lock and then releases it in a loop, which makes a new session each time. Haven't pinned down exactly what happened yet, but it looks like https://github.com/hashicorp/consul-template/commit/8bd6186ccff5bb40acc38ca2e5833a4bdad12b63 isn't pulling in the defaults for the dedup config any more.

I was able to work around it by doing this:

```
deduplicate {
  enabled = true
  ttl = "15s"
}
```

**Comment by slackpad** [comment]
The KV prefix also isn't getting set to the default location.

**Comment by sethvargo** [comment]
Yea - looks like I missed the defaults... and then specifically added tests that they would be blank. Fixing...

**Comment by stevehorsfield** [comment]
Can we get a new 0.18.0 RC or release. This issue is severe in our infrastructure and prevents us moving to CT 0.18 which is needed for Vault TLS support.

**Comment by sethvargo** [comment]
Hey @stevehorsfield 

There are a few other serious bugs with exec mode that are proving challenging to uncover.

**Comment by stevehorsfield** [comment]
I see. Thanks for the update, we'll watch with interest!
