### ISSUE TITLE
use variables in service lookups

### ISSUE THREAD

**Issue by piavka** [hashicorp/consul-template#801]
Unless already possible with some workaround i'd like to be able to use a dynamic variable then looking up a service nodes
for example

    {{$cluster_name := key "some/path/clusterName"}}
    {{if $cluster_name}}
    servers = "{{range $i, $e := service $cluster_name "any"}}{{if ne $i 0}},{{end}}{{$e.Node}}:{{$e.Port}}{{end}}"
    {{end}}

Afaiu since consul-template uses multi phase execution it should be possible ?

**Comment by sethvargo** [comment]
This is possible and should work as written. Are you getting an error?

**Comment by piavka** [comment]
yes i get

    at <service $cluster_nam...>: error calling service: invalid health service dependency format

this is with v0.14.0

**Comment by piavka** [comment]
same thing with v0.16.0

**Comment by sethvargo** [comment]
@piavka What is the value of the key at "some/path/clusterName"?

**Comment by piavka** [comment]
hmm it was *"blah"* but changing to *blah* made it work
ok so next challenge is to make  this work with tags and none of the following works

    {{range $i, $e := service staging.$cluster_name "any"}}

    {{range $i, $e := service "staging.$cluster_name" "any"}}

    {{range $i, $e := service "staging".$cluster_name "any"}}

also i've tried printf 
    
    {{$cluster_name := key "some/path/clusterName" | printf "staging.%s" }}
    {{if $cluster_name}}
    servers = "{{range $i, $e := service $cluster_name "any"}}{{if ne $i 0}},{{end}}{{$e.Node}}:{{$e.Port}}{{end}}"
    {{end}}

which generates $cluster_name == *staging.blah* but still i get the original error
any ideas?

**Comment by piavka** [comment]
this also does not work

    {{$cluster_name := key "some/path/clusterName" | printf "\"staging.%s\"" }}

**Comment by piavka** [comment]
@sethvargo any hints on this?

**Comment by sethvargo** [comment]
Hi @piavka 

Can you please share what you want your template to look like? What do you mean "original error"? Are there other parts to the template?

**Comment by piavka** [comment]
@sethvargo 

    # cat /tmp/consul1.ctmpl
    {{$online_cluster := key "consul-template/staging/kafka/clusters/online/clusterName"}}
    {{if $online_cluster}}
    brokers = "{{range $i, $e := service $online_cluster "any"}}{{if ne $i 0}},{{end}}{{$e.Node}}:{{$e.Port}}{{end}}"
    {{end}}
    # consul-template -once -template /tmp/consul1.ctmpl:/tmp/consul.conf && cat /tmp/consul.conf

    brokers = "staging-kafka1.example.com:9092,staging-kafka2.example.com:9092,dev-kafka.example.com:9092"
    
    #

above works but it returns all nodes that have $online_cluster service
i need to filter based on tag (environment in this case) and all following attempts fail

    # cat /tmp/consul1.ctmpl
    {{$online_cluster := key "consul-template/staging/kafka/clusters/online/clusterName"}}
    {{if $online_cluster}}
    brokers = "{{range $i, $e := service staging.$online_cluster "any"}}{{if ne $i 0}},{{end}}{{$e.Node}}:{{$e.Port}}{{end}}"
    {{end}}
    # consul-template -once -template /tmp/consul1.ctmpl:/tmp/consul.conf && cat /tmp/consul.conf
    Consul Template returned errors:
    template: template: consul1.ctmpl:3: function "staging" not defined
    # 


    # cat /tmp/consul1.ctmpl
    {{$online_cluster := key "consul-template/staging/kafka/clusters/online/clusterName"}}
    {{if $online_cluster}}
    brokers = "{{range $i, $e := service "staging.$online_cluster" "any"}}{{if ne $i 0}},{{end}}{{$e.Node}}:{{$e.Port}}{{end}}"
    {{end}}
    # consul-template -once -template /tmp/consul1.ctmpl:/tmp/consul.conf && cat /tmp/consul.conf
    Consul Template returned errors:
    template: template: consul1.ctmpl:3:29: executing "consul1.ctmpl" at <service "staging.$on...>: error calling service: invalid health service dependency format
    #



    # cat /tmp/consul1.ctmpl
    {{$online_cluster := key "consul-template/staging/kafka/clusters/online/clusterName"}}
    {{if $online_cluster}}
    brokers = "{{range $i, $e := service "staging."$online_cluster" "any"}}{{if ne $i 0}},{{end}}{{$e.Node}}:{{$e.Port}}{{end}}"
    {{end}}
    # consul-template -once -template /tmp/consul1.ctmpl:/tmp/consul.conf && cat /tmp/consul.conf
    Consul Template returned errors:
    template: template: consul1.ctmpl:3: unexpected "$online_cl"... in operand
    #



    # cat /tmp/consul1.ctmpl
    {{$online_cluster := key "consul-template/staging/kafka/clusters/online/clusterName" | printf "staging.%s"}}
    {{if $online_cluster}}
    brokers = "{{range $i, $e := service $online_cluster" "any"}}{{if ne $i 0}},{{end}}{{$e.Node}}:{{$e.Port}}{{end}}"
    {{end}}
    # consul-template -once -template /tmp/consul1.ctmpl:/tmp/consul.conf && cat /tmp/consul.conf
    Consul Template returned errors:
    template: template: consul1.ctmpl:3:29: executing "consul1.ctmpl" at <service $online_clus...>: error calling service: invalid health service dependency format
    #


I've tried many more and nothing works, i'm out of ideas

**Comment by piavka** [comment]
Yay, The following works

     {$online_cluster := key "consul-template/staging/kafka/clusters/online/clusterName"}}
     {{if $online_cluster}}
     brokers = "{{range $i, $e := service (printf "staging.%s" $online_cluster) "any"}}{{if ne $i 0}},{{end}}{{$e.Node}}:{{$e.Port}}{{end}}"
     {{end}}

who could have guessed ? 
I really have no idea why such printf works but following does not ?

    {{$online_cluster := key "consul-template/staging/kafka/clusters/online/clusterName" | printf "staging.%s"}}

**Comment by sethvargo** [comment]
The reason the latter doesn't work is because of the order of operations. I would recommend taking a look at the go text/template docs for more examples: https://golang.org/pkg/text/template/. Glad you got it sorted.
