### ISSUE TITLE
Parsing consul-template metadata inside template files.

### ISSUE THREAD

**Issue by samifruit514** [hashicorp/consul-template#802]
Enhancement suggestion:

It would be great to have a feature where you put meta data inside .ctmpl files. For example, lets say we have a java app that requires a config file at runtime. In the properties.conf.ctmpl, we would have something like this:

```
# this is a comment {{ctmplmeta}}command=echo "test"{{end}}
# another comment {{ctmplmeta}}destination=/etc/properties.conf{{end}}
project.property1="blabla"
project.property2="blabla"
```

Instead of passing a command via consul-template config or command line, the command would be in the ctmpl file which would make a self-contained template config. This way we could centralize template configuration at one place and passing a simple param for consul-template which would look like 

`consul-template -config=file.hcl -template=/dir/properties.conf.ctmpl
`

I can do a PR if you want.

**Comment by sethvargo** [comment]
Hi @samifruit514 

Thank you for opening an issue. This is a bit backward from the approach we recommend. If you want to keep all the configuration in one place, you can use a config file (which includes more options and flags than the CLI), and put the template inline in the configuration file. Consul Template also supports a "dot-d" directory of configurations, so it's easy to manage the files separately if you want.

You get the same behavior:

```
$ consul-template -config=/etc/consul-template.d
```

And all your configs and setups are in there.
