### ISSUE TITLE
Exec mode fail with 0.18.0-rc1

### ISSUE THREAD

**Issue by kak-tus** [hashicorp/consul-template#804]
Exec mode fails in 0.18, but works with same config on 0.16.

### Consul Template version
0.18.0-rc1

### Configuration
none

### Command

```shell
consul-template \
  -template "/home/user/config.xml.template:/home/user/.config/syncthing/config.xml" \
  -exec "syncthing"
```

### Debug output
https://gist.github.com/kak-tus/88f610536203c9ba5204281a6a54087d

### Expected behavior
consul-template should run application

### Actual behavior
consul-template failed with panic

### Steps to reproduce
I have prepared two simplified docker images. Working (consul-template 0.16) and not (0.18).
https://github.com/kak-tus/docker-syncthing-auto/tree/0.1_working
https://github.com/kak-tus/docker-syncthing-auto/tree/0.1_non_working

To reproduce
1. Clone repo.
2. cd to cloned, checkout branch
3. sudo docker build .
4. sudo docker run --rm -it builded_image

### References
none

**Comment by kak-tus** [comment]
Oh, sorry, may be it's duplicate for #791.

**Comment by sethvargo** [comment]
Hi @kak-tus 

This looks like a duplicate of #791 - which is already fixed on master. Could you try a master build and see if that fixes your issue? Sorry about that.

**Comment by kak-tus** [comment]
:+1:
