### ISSUE TITLE
Support dynamic template renderring

### ISSUE THREAD

**Issue by Colstuwjx** [hashicorp/consul-template#805]
As I known, consul-template ONLY support define the templates in the configuration file, just like:

```
# repeat it.
template {
  // This is the source file on disk to use as the input template. This is often
  // called the "Consul Template template". This option is required if not using
  // the `contents` option.
  source = "/path/on/disk/to/template.ctmpl"

  // This is the destination path on disk where the source template will render.
  // If the parent directories do not exist, Consul Template will attempt to
  // create them.
  destination = "/path/on/disk/where/template/will/render.txt"

  ...
}
```

But I want to even render the template dynamically, just like: 

```
{{ range .. }}
template {
  source = "/path/on/disk/to/{{ $key }}.ctmpl"
  destination = "/path/on/disk/where/template/will/render_{{ $key }}.txt"
}
{{ end }}
```

thx.

**Comment by sethvargo** [comment]
Hi @Colstuwjx 

You can either use the "consul-template spawns consul-template process", or use the 0.18 rc with the "execute" block to define a reusable template: https://github.com/hashicorp/consul-template#executetemplate

**Comment by WyseNynja** [comment]
@sethvargo is there an example somewhere of using consul-template to spawn consul-template? I think that will work for what I want and an example would make it easy. Thanks!

**Comment by benmutlu** [comment]
any update on this ? I stuck at same point and looking proper way to create destination files dynamically, for example dns zone files, i have over 100 dns zones and they all using same template, instead of creating 100 files I need to pass value to templates.

**Comment by eikenb** [comment]
Hey @benmutlu, good to hear from you.

My I suggest asking about this on the community forum; https://discuss.hashicorp.com/c/consul
The discuss site is where we (and the rest of the community) try to answer questions and you'll get more eyes there. We try to use github for bugs and feature requests.

Thanks.
