### ISSUE TITLE
Better support for container configuration management

### ISSUE THREAD

**Issue by FlorinAsavoaie** [hashicorp/consul-template#809]
Hi guys,

I am not sure if this is the direction you'd want to go to but I have this use case in mind:

- Run a consul-template image as a global docker service and make it have the capabilities of a Docker Volume Driver (activate the Volume Driver API socket via a configuration or command line flag). The Volume Driver would be local, of course.
- Create local configuration volumes for whatever configurations I want with `docker volume create --volume-driver=consul-template` and opts like --opt service=servicename. That would be a consul-template configuration template for consul-template itself ("Inception"). It would add it to its own configuration, reload itself, and start generating templates for it in a specific folder. It would then reply to mount requests with the path to that folder, for that respective volume.
- When launching containers (or services for that matter), give them the volume created above to use as configuration.
- Add the ability for consul-template to send the reload signals via `docker kill` to all containers having that volume mounted on the local Docker node.

I know it is a more complex thing but it sounds like an extremely useful tool this way and stops us having the requirement to run consul-template in each of the containers.

**Comment by sethvargo** [comment]
Hi @FlorinAsavoaie 

Thank you for opening an issue. All of these things seem like they would exist outside of the Consul Template code itself and would just be a property of the Docker container itself? Sorry, but I'm not very familiar with that part of the Docker ecosystem at this time.

This sounds like a good use case, but it also involves a lot of moving parts in a system we are not that familiar with. I don't think this is something we would implement ourselves, but I would gladly collaborate on a Pull Request to get this into core. Thanks and have a great day! 😄
