### ISSUE TITLE
constant haproxy restarts and occasional loss of service

### ISSUE THREAD

**Issue by joshuafernandes** [hashicorp/consul-template#810]
Hello,

Im not sure what Im doing wrong here, but I keep seeing random restarts and we occasionally loose service for a brief period with HA. So my setup is roughly this: a bunch of containers that all use consul as service discovery and I store info about services in consul as key value pairs which is used by HaProxy to create a config file and handle things. 

Generally this works well, but every now and then I see a HaProxy reload and incoming requests start failing. Nothing on the back end servers has changed (services humming along) and consul hasn't had any changes either, but I see the reloads in the logs. 

### Consul Template version
Im using consul 0.7 and consul-template 0.15 and my dockerfile is pretty standard, contents of the haproxy.hcl shown below.

### Configuration
```javascript
retry = "10s"
max_stale = "10m"
template {
  source = "/tmp/haproxy.ctmpl"
  destination = "/etc/haproxy/haproxy.cfg"
  command = "haproxy -f /etc/haproxy/haproxy.cfg -sf $(pidof haproxy) &"
  wait = "5s"
}
```

### Debug output

**Valid requests like so:**
Dec 02 06:53:19 54.66.199.167 haproxy-production:  10.x.x.x:40256 [01/Dec/2016:20:53:19.779] https-in~ back_svs-api-production/host0 19/0/1/4/24 200 195 - - ---- 0/0/0/0/0 0/0 "GET /test HTTP/1.1" 

**Scores of these that appear at random and if a request comes in between then the next piece below happens witha a 503:**
Dec 02 06:53:20 10.x.x.x haproxy-production:  Stopping frontend http-in in 0 ms. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Stopping frontend https-in in 0 ms. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Stopping backend back_svc_a-production in 0 ms. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Stopping backend back_svc_b-production in 0 ms. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Stopping backend back_svc_c-production in 0 ms. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Stopping backend not_found in 0 ms. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Stopping proxy stats in 0 ms. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy http-in stopped (FE: 1 conns, BE: 0 conns). 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy https-in stopped (FE: 10 conns, BE: 0 conns). 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy back_svc_a-production stopped (FE: 0 conns, BE: 1 conns). 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy back_svc_b-production stopped (FE: 0 conns, BE: 0 conns). 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy back_svc_c-production stopped (FE: 0 conns, BE: 0 conns). 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy not_found stopped (FE: 0 conns, BE: 0 conns). 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy stats stopped (FE: 0 conns, BE: 0 conns). 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy http-in started. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy https-in started. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy back_svc_a-production started. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy back_svc_b-production started. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy back_svc_c-production started. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy not_found started. 
Dec 02 06:53:20 10.x.x.x haproxy-production:  Proxy stats started. 

**Loss of service with 503's when neither the backend has changed nor the consul config:**
Dec 02 06:01:15 10.x.x.x haproxy-production:  10.x.x.x:50583 [01/Dec/2016:20:01:15.739] https-in~ back_svc_c-production/<NOSRV> 30/-1/-1/-1/30 503 212 - - SC-- 0/0/0/0/0 0/0 "GET /test HTTP/1.1" 
Dec 02 06:01:15 10.x.x.x haproxy-production:  10.x.x.x:50584 [01/Dec/2016:20:01:15.739] https-in~ back_svc_b-production/<NOSRV> 72/-1/-1/-1/72 503 212 - - SC-- 0/0/0/0/0 0/0 "GET /test HTTP/1.1" 

### Expected behavior
What I'm expecting is that haproxy reloads on either a consul update or when a service is down (health check fails or the like). However health checks appear fine, no consul changes but full restarts are happening. If they must happen what can I tweak to make them less frequent?

### Steps to reproduce
I've got no idea how to reproduce it. Appears that maybe its not following quiesence properly or maybe I need to set the times a bit longer, I've tried playing with different times but cant seem to pinpoint the cause. I'd really appreciate if someone could shed some light on this please.

**Comment by sethvargo** [comment]
Hi @joshuafernandes 

Can you share your template too? This does not seem like an issue with Consul Template at first glance; haproxy is notorious for being a challenge to properly reload without dropping traffic (see https://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html). Could you please also run Consul Template in debug mode and share that output?

**Comment by joshuafernandes** [comment]
Hi @sethvargo 

It may well be haproxy doing weird resstarts, Im trying one thing at a time atm to figure out whats causing this:

If it is haproxy would the solution be to change command to:

```
sudo iptables -I INPUT -p tcp --dport 443 --syn -j DROP 
sleep 2
haproxy -f /etc/haproxy/haproxy.cfg -sf $(pidof haproxy) &
sudo iptables -I INPUT -p tcp --dport 443 --syn -j DROP 
sleep 1
```
The above in a script or somthing along those lines?


My template config is below:
```
global
    stats timeout 30s
    tune.ssl.default-dh-param 2048
    tune.bufsize 65535
    maxconn 2048
    debug

defaults
    log global
    option httplog
    option dontlognull
    option httpclose
    retries 2
    default-server inter 20s fall 3 rise 2
    mode http{{range ls "service/haproxy/timeouts"}}
    timeout {{.Key}} {{.Value}}{{else}}
    timeout connect 5000
    timeout client  50000
    timeout server  50000{{end}}

frontend http-in
    bind *:80
    mode http
    acl http      ssl_fc,not
    http-request redirect scheme https if http

frontend https-in
    bind *:443 ssl crt /opt/haproxy/certs/
    mode http
    http-request set-header X-Forwarded-Proto https
    default_backend not_found
    {{range services}}{{if in .Tags "haproxy"}}{{$name := .Name}}{{with $d := printf "/containers/%s" $name | key | parseJSON}}
    acl svc_{{$name}} hdr_dom(host) -i {{$d.host}}{{if $d.path}}
    use_backend back_{{$name}} if svc_{{$name}}
    {{end}}{{end}}{{end}}{{end}}


{{range services}}{{if in .Tags "haproxy"}}{{$name := .Name}}{{with $d := printf "/containers/%s" $name | key | parseJSON}}
backend back_{{$name}}
  mode http
  balance leastconn
  option forwardfor{{if $d.check}}
  option httpchk {{$d.check}} HTTP/1.1\r\nHost:localhost{{end}}
  {{range $c,$d := service $name}}server host{{$c}} {{.Address}}:{{.Port}} check
  {{end}}
  {{end}}{{end}}{{end}}{{end}}

backend not_found
  mode http
  errorfile 503 /etc/haproxy/404.http

listen stats
    bind *:1936
    stats enable
    stats uri /
    stats hide-version
```

**Comment by sethvargo** [comment]
Hey @joshuafernandes 

Unfortunately I'm not an expert in haproxy configuration, so I'm not the best person to verify your haproxy configuration. I think the easiest way to diagnose this would be to run both CT and haproxy in debug mode with timestamps and then compare those stamps to see what haproxy is doing around that time. I'm not sure if I'll be able to help outside of that, sorry!

**Comment by sethvargo** [comment]
It would also be helpful if you could run CT in debug mode and send the output. You're also on 0.15, and 0.16-0.17 have a number of bug fixes and improvements that might worth be trying.

**Comment by joshuafernandes** [comment]
Hi @sethvargo: will do, I'll run an updated version and see what I get. Thanks for the assist :)
