### ISSUE TITLE
exec mode reload signal

### ISSUE THREAD

**Issue by mschirrmeister** [hashicorp/consul-template#812]
### Environment 

consul-template version
```
root@3c080c54e029:/# /usr/local/bin/consul-template --version
consul-template v0.16.0
```

consul-template config `/etc/consul-configs/nginx-conf-template.conf`

```
template {
  source = "/etc/consul-templates/nginx.conf.ctmpl"
  destination = "/etc/nginx/conf.d/app.conf"
}
```

consul-template template `/etc/consul-templates/nginx.conf.ctmpl`

```
{{- $consulTargetServiceQuery := env "CONSUL_TARGET_SERVICE_QUERY" -}}

# Backend servers
upstream backendApp {
  least_conn;
  {{range service $consulTargetServiceQuery}}server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=60 weight=1;
  {{end}}
}

```

Variables for container
```
CONSUL_HTTP_ADDR=node1.node.consul.company.com:8501
CONSUL_HTTP_TOKEN=xxx
CONSUL_TARGET_SERVICE_QUERY=dev.app1
CONSUL_HTTP_SSL=True
```

In our entrypoint we start the container like this.
```
/usr/local/bin/consul-template -log-level=info -exec /usr/sbin/nginx -c /etc/nginx/nginx.conf -g 'daemon off;' -exec-reload-signal=SIGHUP -exec-kill-signal=SIGQUIT -config /etc/consul-configs
```

### Problem

We use nginx as a load balancer in front of our container. The container runs consul-template in exec mode. Sometimes when our backend containers change access to the application is no longer possible and we receive a nginx error that it can not connect to upstream. The problem is that the nginx config is not properly reloaded. If we login to the container and execute a `nginx -s reload` it works again.

When the backend conainers change, we see the following in the consul-template log. So it looks like it is reloading the child process, but in reality it is not.

```
2016/12/02 15:55:37.188947 [INFO] (view) "service(dev.app1)" received data
2016/12/02 15:55:37.189088 [INFO] (runner) running
2016/12/02 15:55:37.195419 [INFO] (runner) diffing and updating dependencies
2016/12/02 15:55:37.195435 [INFO] (child) reloading process
2016/12/02 15:55:37.195465 [INFO] (runner) watching 1 dependencies
```

Unfortunately it is right now not 100% reproducable. I have no debug log yet, since I could not reproduce it yet again.
Question is, does anything with the above config look wrong? According to the nginx docu SIGHUP seems to be the proper signal for a config reload.

Thanks
Marco

**Comment by sethvargo** [comment]
Hi @mschirrmeister 

Are you able to run CT in debug mode as well as nginx? Without more information, it's hard to diagnose, but I'm guessing that, at some point, the configuration is being written as invalid (perhaps because services or keys are missing), nginx is reloaded, and then it dies, but async. As such CT is still running and writes out a good config very quickly shortly thereafter, but fails to signal the process.

If you run CT and nginx in debug mode with timestamps, it'll be easier to correlate.

**Comment by mschirrmeister** [comment]
I will definitely attach some debug logs once it happens again.

**Comment by sethvargo** [comment]
Hey there,

I'm relatively confident this is not an issue in Consul Template (we have a lot of coverage here). Without debug logs, it's challenging to track this down. If you are able to reproduce this with more information, we would gladly help debug it and reopen this issue. Thanks!
