### ISSUE TITLE
Add contains(All|Any|None|Notall) functions

### ISSUE THREAD

**Issue by aferreira** [hashicorp/consul-template#816]
These functions allow selection based on multiple tags without having to write templates such as

```liquid
{{ if (contains $tag1 .Tags) and (contains $tag2 .Tags) }}
# ...
{{ end }}
```

or without having to resort to nested `range` constructs if the number of tags to match is not known a priori.

#### `containsAll`
Returns `true` if all needles are within an iterable element,
or `false` otherwise.
Returns `true` if the list of needles is empty.

```liquid
{{ if containsAll $requiredTags .Tags }}
# ...
{{ end }}
```

#### `containsAny`
Returns `true` if any needle is within an iterable element,
or `false` otherwise.
Returns `false` if the list of needles is empty.

```liquid
{{ if containsAny $acceptableTags .Tags }}
# ...
{{ end }}
```

#### `containsNone`
Returns `true` if no needles are within an iterable element,
or `false` otherwise.
Returns `true` if the list of needles is empty.

```liquid
{{ if containsNone $forbiddenTags .Tags }}
# ...
{{ end }}
```

#### `containsNotall`
Returns `true` if some needle is not within an iterable element,
or `false` otherwise.
Returns `false` if the list of needles is empty.

```liquid
{{ if containsNotall $excludingTags .Tags }}
# ...
{{ end }}
```

**Comment by sethvargo** [comment]
This has been merged. Thanks!

**Comment by rickardrosen** [comment]
@aferreira: I'm trying to figure out how to consume these functions, but TBH, the needle, haystack and iterable elements are confusing me, most likely due to my lacking knowledge of go.

The only reference I could find pointed me to the go-template source code, which gave me a 404.

I'd like to be able to require tags "production" and "backend". Perhaps you could throw in an example regarding how to end up with an iterable "$requiredTags" in a template?

**Comment by aferreira** [comment]
@rickardrosen The bigger issue with using these functions is that the go-template language does not support arrays as literals. But, with consul-template, `parseJSON` may help you.

Here is a simple example:

```
{{- $requiredTags := parseJSON `["production","backend"]` -}}

{{- range service "pg" -}}
{{- if .Tags | containsAll $requiredTags -}}

{{ .Name }} {{ .Address }}:{{ .Port }}

{{ end }}{{ end -}}
```

**Comment by rhgreene** [comment]
@aferreira , are you saying that this containsAll function just doesn't work because of the limitations you mention? Your example doesn't use the containsAll function.
