### ISSUE TITLE
executing plugin "did not finish"

### ISSUE THREAD

**Issue by consultantRR** [hashicorp/consul-template#818]
consul-template version:  `consul-template v0.18.0-rc1 (933192d+CHANGES)`

On each CT execution, I need to run a short preprocessing script, and have embedded this in the CT template as a plugin call, ie:

```
{{plugin "./pre.sh"}}
```

Execution of `pre.sh` takes between 3-8 seconds. Sometimes this works fine (CT properly fires `pre.sh` and continues with its execution), but many times CT seems to give up after just a few seconds, returning:

```
template: template: :19:2: executing "" at <plugin "./pre.sh">: error calling plugin: exec "./pre.sh": did not finish
```

Not sure if this is unexpected CT behavior, or if there is a hard time limit here. If the latter, not sure if that is configurable, or potentially negotiable as part of an enhancement request for CT.

**Comment by sethvargo** [comment]
Changed this to 30s to be in line with the other exec timeouts. However, keep in mind that the run function will be blocked while this plugin executes.
