### ISSUE TITLE
Consul-template exits after any error in daemon mode

### ISSUE THREAD

**Issue by dsolsona** [hashicorp/consul-template#819]
Hi,

First and foremost thanks for building and maintaining consul-template, it is pretty awesome!

I'm seeing some unexpected behaviour in how consul-template handles errors when running in daemon mode.

For example, today I had this issue `consul-template[23226]: (runner) error running command: failed to kill "/usr/bin/sudo /var/lib/consul-template/reload_haproxy.sh" in 30s: operation not permitted` that caused consul-template to exit.

I'd expect that consul-template running in daemon mode wouldn't exit due to an issue like this, in my opinion it should keep running. Is this the expected behaviour?

I can easily implement some workaround by running it under monit, supervise, etc.. but it would be nice if it could handle temporary failures like this in a better way.

I can see a similar behaviour with the Vault integration as in https://github.com/hashicorp/consul-template/issues/752

**Comment by sethvargo** [comment]
Hey @dsolsona 

Thank you for opening an issue. While this behavior may be unexpected, it's a very clear design decision, and we have documented it as such [in the README](https://github.com/hashicorp/consul-template#termination-on-error). If CT doesn't terminate on these kinds of errors, it's challenging to deploy at large(r) scale.

**Comment by dsolsona** [comment]
@sethvargo fair enough. I guess I didn't pay enough attention to that section in the README :(
