### ISSUE TITLE
after one node crash consul-templates doesnt deregister failed nodes 

### ISSUE THREAD

**Issue by slawekgh** [hashicorp/consul-template#820]
I have 2 servers with mesos and docker   - 192.168.43.223 and 192.168.43.174

On each node there is gliderlabs/registrator working - I can scale up and down my service in Marathon and everything works perfectly - consul-templates dynamically generates  haproxy config and it works really great 
My Marathon service works on 10 instances , 5 of them is on *.223 and 5 of them on *.174 

After crash simulation (server power-off) of 2nd node (*.174) Marathon+Mesos migrate 5 containers to healthy node and it works as expected. 

My problem is that even if I have 10 working dockers (on healthy node) I still have 5 orphaned records in haproxy.cfg - so the total number of records is 15 :

```
[...]
frontend http-in
    bind *:80
    acl app0 path_beg -i /myservice88
    
    use_backend srvs_app0 if app0


backend srvs_app0
    mode http
    balance roundrobin
    option forwardfor
    option httpchk HEAD / HTTP/1.1\r\nHost:localhost
    reqrep ^([^\ ]*\ /)myservice88[/]?(.*)     \1\2
    server host0 192.168.43.223:31858 check
    server host1 192.168.43.223:31092 check
    server host2 192.168.43.223:31938 check
    server host3 192.168.43.223:31997 check
    server host4 192.168.43.223:31613 check
    server host5 192.168.43.223:31902 check
    server host6 192.168.43.223:31538 check
    server host7 192.168.43.223:31895 check
    server host8 192.168.43.223:31506 check
    server host9 192.168.43.223:31551 check
    **server host10 192.168.43.174:31287 check
    server host11 192.168.43.174:31908 check
    server host12 192.168.43.174:31905 check
    server host13 192.168.43.174:31579 check
    server host14 192.168.43.174:31912 check**
```

how to get rid of them ? 
as a workaround I removed the whole consul instance but it is not good idea on production envs :-(

**Comment by sethvargo** [comment]
It sounds like registrator isn't de-registering those services in Consul. This is not a bug in Consul Template - I would recommend opening an issue on the registrator repo. Thanks and sorry I cannot be of more help!

**Comment by slawekgh** [comment]
right, I move this issue to https://github.com/gliderlabs/registrator/issues/505
