### ISSUE TITLE
Document renaming or "key_or_default" to "keyOrDefault"

### ISSUE THREAD

**Issue by zeisss** [hashicorp/consul-template#822]
### Consul Template version

0.16.0

### Expected behavior

`CHANGELOG.md` should document that the function `key_or_default` was renamed after 0.16 to `keyOrDefault`.

### Actual behavior

Searching for `keyOrDefault` in the changelog only shows one item explaining a behavior change. The old name results in no hit.

**Comment by sethvargo** [comment]
It's currently deprecated, but only the docs have changed. Are you seeing different behavior? https://github.com/hashicorp/consul-template/blob/fb40a31771b0da8c8cf53cb2811a849bbbc4acf1/template/template.go#L236-L237

**Comment by zeisss** [comment]
Well, my story goes like this:

We had 0.13 running. We wanted to change something, looked at the README.md in master which  mentioned `keyOrDefault`, added it and failed (obviously, 0.13 doesn't have this). So, update to 0.16, which is the latest stable. Broken again. Looking at the code in 0.16 and seeing that this was named `key_or_default`. Searching in the CHANGELOG.md in `master` doesn't yield any of this, thus I made a ticket.

It's good for backward compatibility that the old name is still supported, but as someone coming from older versions looking at the CHANGELOG this was confusing. I would have expected the rename to have been mentioned in Changelog on master, then I could have known that in the previous version I had to use the old name.

**Comment by sethvargo** [comment]
Hi @zeisss 

The best thing to do is to always refer to the documentation for your version. We call this out in the README specifically:

> **The documentation in this README corresponds to the master branch of Consul Template. It may contain unreleased features or different APIs than the most recently released version. Please see the Git tag that corresponds to your version of Consul Template for the proper documentation.**

I'm sorry this caused you trouble, but the rename isn't actually a "change" yet, since we haven't released the next version of CT. Thanks!

**Comment by zeisss** [comment]
Agreed :) Just wanted to point out that this is not _yet_ documented. See it as a TODO on master. If you keep those somewhere else, feel free to close :)
