### ISSUE TITLE
Context instead of Dependency.Cancel()?

### ISSUE THREAD

**Issue by sargun** [hashicorp/consul-template#823]
Is there any reason why the dependency interface has a Cancel method, rather than passing dependencies a context and relying upon that for cancellation? Would there be any argument to switching to contexts?

**Comment by sethvargo** [comment]
Hi @sargun 

Thank you for reaching out. I think the short answer is: Consul Template existed before contexts were a thing. I would definitely be open to reviewing a PR to switch to contexts, but I don't think they offer enough value to halt forward progress to refactor at this time. I like contexts, but I don't view dep.Cancel() as enough technical debt yet to warrant the refactor. That said, if someone has a bit more time than myself, I would gladly review it. However, it would be nice to start upstream in Consul's blocking queries, that way we can pass the context along in the API directly 😄 . Thanks and have a great day!
