### ISSUE TITLE
Dedup mode doesn't properly handle parameterized templates

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul-template#827]
If you've got a template such as this:

`{{printf "%s/%s/%s/config" (env "env") (env "app") (env "service"│key}}`

With dedup mode enabled the template will get hashed with the raw contents of the template without regards to the environment variables. Followers with the same environment set will find their dependencies met by the leader, but followers with a different configuration will not be able to resolve their dependencies, so won't render a template.

**Comment by sethvargo** [comment]
I think the issue here is that `env` isn't treated as a dependency, but rather a local helper. I think we need to move env to a dependency or somehow explicitly ignore it.
