### ISSUE TITLE
Add a envOrDefault helper

### ISSUE THREAD

**Issue by Nikkau** [hashicorp/consul-template#829]
## Feature Request
For a new project we use a bench of `{{ if env "TIMEOUT_CONNECT" }}{{ env "TIMEOUT_CONNECT" }}{{ else }}5s{{ end }}` which is a bit verbose and redundant.

It would be very conveniant to use a syntax like `{{envOrDefault "TIMEOUT_CONNECT" "5s"}}`

It should be trivial to implement, I can make a pull request if you are ok with it.

**Comment by sethvargo** [comment]
Hi @Nikkau 

You should be able to use the built-in `or` operator like this:

```liquid
{{ or (env "TIMEOUT_CONNECT") "5s" }} 
```

Does that work?

**Comment by Nikkau** [comment]
Hi,

It works, but `{{ env }}` rely on `os.Getenv` which always return a string, an empty one when the var doesn't exists, it works only because `{{ or }}` consider `""` falsy which is not the case in all language, so not intuitive imho.

`{{ envOrDefault }}` could use `os.LookupEnv` to return default value only when the var doesn't exists in environment.

I don't know if someone need this stricter behavior (today I don't, the "or pattern" does the trick).


I also think explicit helper have value for the sake of explicitness, for coherence with the existence of `keyOrDefault`

**Comment by sethvargo** [comment]
Hi @Nikkau 

Thank you for your response. I am going to close this out until someone has a stricter use case. Thanks!

**Comment by dfredell** [comment]
Hello,

I was searching high and low for this answer. `{{ or (env "TIMEOUT_CONNECT") "5s" }}` does exactly what I want it to do. It was just hard to find. 

I would like to make it easier for the next person to find. Can I make a PR to update the docs and add this example? 

The another option would be for me to make the `envOrDefault` function like @Nikkau suggested. It would be very intuitive and easy to read. {{envOrDefault "TIMEOUT_CONNECT" "5s"}}

**Comment by slackpad** [comment]
> Can I make a PR to update the docs and add this example?

Sure @dfredell we'd welcome that!

**Comment by jtrinklein** [comment]
I also had a very hard time finding the solution to this. I'd like to submit a PR to add the envOrDefault helper.

**Comment by eikenb** [comment]
@jtrinklein, if you'd like to submit a PR with this feature I'll happily review it for possible inclusion. Please remember tests. Thanks.
