### ISSUE TITLE
index on service

### ISSUE THREAD

**Issue by bryanlarsen** [hashicorp/consul-template#83]
Suppose I would like to get the IP address of any consul agent.   I would expect something like this to work:

```
 {{ index (service "consul") 0 }}
```

What am I doing wrong?   Thanks.

**Comment by blalor** [comment]
I also ran across this recently. I'd like to know why the `index` function (pipeline?) doesn't work…

**Comment by nik-johnson-net** [comment]
This is old and closed, but certainly still a "gotcha". I spent an hour trying to figure out what I was doing wrong, only to realize this is a known issue.

**Comment by eikenb** [comment]
Hey @nik-johnson-net, is the issue you were having a similar case to the original issue report here? Ie. something like `{{ index (service "consul") 0 }}`?

**Comment by nik-johnson-net** [comment]
Yes, exactly the same issue.

**Comment by eikenb** [comment]
I've figured out what's going on here and why `{{ index (service "consul") 0 }}` doesn't work.

Consul-template uses a [multi-pass rendering strategy](https://github.com/hashicorp/consul-template#multi-phase-execution) which means that templates need to work on the first pass with no data as that pass is used to start the async lookups in Consul (et al.).

So if you use index without checking the length it will always fail as the first time it will be called it will always have a 0 length.

The simplest way to deal with this is with a conditional around the index. 
Eg. (formatted for readability, not usefulness)

```
{{ $svs := (service "consul") }}
{{ if gt (len $svs) 0 }}
    {{ index $svs 0 }}
{{end}}
```

There was a proposal at one point to have index return nil in these cases which would have fixed this issue without requiring the test, but it was rejected as it made the template behavior different from the language behavior.

**Comment by eikenb** [comment]
That golang proposal... https://github.com/golang/go/issues/14751
