### ISSUE TITLE
consul-template writing to stderr

### ISSUE THREAD

**Issue by ItsKarma** [hashicorp/consul-template#832]
### Consul Template version
consul-template v0.16.0

### Configuration
None

### Command

```shell
consul-template -version
```

### Debug output

consul-template -version -log-level=debug
```shell
2017/01/04 05:15:03.021404 [INFO] consul-template v0.16.0
2017/01/04 05:15:03.021453 [DEBUG] (cli) version flag was given, exiting now
consul-template v0.16.0
```

### Expected behavior
`consul-template -version` should write to stdout.

### Actual behavior
`consul-template -version` is writing to stderr.

### Steps to reproduce
1. Install latest stable consul-template (0.16.0)
2. `consul-template -version > /tmp/consul-template.stdout 2> /tmp/consul-template.stderr`
3. notice that consul-template.stdout is empty and /tmp/consul-template.stderr is populated with the output of the command.
4. `consul-template -dry > /tmp/consul-template.stdout 2> /tmp/consul-template.stderr` appears to yield the same result.

#### Here is another way to reproduce
```shell
consul-template -version | grep 0.16.0; echo $?
  # Here you see it prints the output.
  consul-template v0.16.0
  # but the exit code was a 1 because the grep found nothing from stdout.
  1
```

```shell
2>&1 consul-template -version | grep 0.16.0; echo $?
  # Here you see it prints the output, but this time I redirected stderr to stdout.
  consul-template v0.16.0
  # and now the exit code was a 0.
  0
```

### References
None

**Comment by sethvargo** [comment]
This is a longstanding debate: https://github.com/hashicorp/consul-template/issues/234. Check java and bash, for example. We consider "Version" to be diagnostic information, and thus belongs on stderr according to the spec. Thanks!
