### ISSUE TITLE
Documentation of exec reload mismatch

### ISSUE THREAD

**Issue by a86c6f7964** [hashicorp/consul-template#835]
I see both

>  If no reload signal is provided, Consul Template will kill and restart the process. 

and 

> any change to any dependent template will cause the reload signal to be sent to the child process. This reload signal defaults to nil, in which Consul Template will not kill and respawn the child. 

in the documentation. Which of these is correct? And they should be fixed to say the same thing.

**Comment by sethvargo** [comment]
It defaults to nil, which stops the current instance and spawns a new one. Thanks for pointing this out.
