### ISSUE TITLE
why sort Tags?

### ISSUE THREAD

**Issue by childe** [hashicorp/consul-template#838]
### Consul Template version
0.16.0

I saw a Bug Fix that "Deep copy and sort data returned from Consul API (specifically tags)" in from version 0.50.0.

I am wondering why then should be returned sorted? 
 I want to put domain,appName to consul, and be able to get domain and appName in turn.
But now i don't know which one is domain , the first? or the second?

**Comment by sethvargo** [comment]
Hi @childe 

The tags are always returned in alphabetical order by Consul (not insertion order). You can check yourself via the API.

**Comment by childe** [comment]
Maybe the latest consul returns the origin tags? as below:

% curl -s 10.3.**.**:8500/v1/catalog/service/es-paas-es.corp.com | json_pp
[
   {
      "ServiceID" : "uat6372:jovial_meitner:80",
      "ServicePort" : 30003,
      "Node" : "uat6372",
      "ServiceAddress" : "127.0.0.1",
      "ServiceEnableTagOverride" : false,
      "ModifyIndex" : 1608621,
      "ServiceName" : "es-paas-es.corp.com",
      "Address" : "10.2.**.**",
      "ServiceTags" : [
         "z7777",
         "es.corp.com",
         "z7777",
         "88999"
      ],
      "CreateIndex" : 1608621
   }
]
