### ISSUE TITLE
v0.18.0-rc2 doesn't have vault write operations wired up

### ISSUE THREAD

**Issue by nbrownus** [hashicorp/consul-template#844]
We were trialing v0.18.0-rc2 and noticed that we couldn't use it with pki mounts in `vault`

```
{{- with secret "pki-mount/issue/cert" "common_name=..." "alt_names=..." "ttl=..." "format=pem"}}
...
{{- end }}
```

Digging into it we noticed that only `dep.NewVaultReadQuery` was wired up. We did get it to work by porting over the code that was present in v0.16.0.

I am also curious why errors are no longer being reported.

Here is how we got it working

```
diff --git template/funcs.go template/funcs.go
index 08533c0..e678a0a 100644
--- template/funcs.go
+++ template/funcs.go
@@ -286,15 +286,37 @@ func nodesFunc(b *Brain, used, missing *dep.Set) func(...string) ([]*dep.Node, e
 }
 
 // secretFunc returns or accumulates secret dependencies from Vault.
-func secretFunc(b *Brain, used, missing *dep.Set) func(string) (*dep.Secret, error) {
-       return func(s string) (*dep.Secret, error) {
+func secretFunc(b *Brain, used, missing *dep.Set) func(...string) (*dep.Secret, error) {
+       return func(s ...string) (*dep.Secret, error) {
                result := &dep.Secret{}
 
                if len(s) == 0 {
                        return result, nil
                }
 
-               d, err := dep.NewVaultReadQuery(s)
+
+               path, rest := s[0], s[1:]
+
+               data := make(map[string]interface{})
+               for _, str := range rest {
+                       parts := strings.SplitN(str, "=", 2)
+                       if len(parts) != 2 {
+                               return result, nil
+                       }
+
+                       k, v := strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1])
+                       data[k] = v
+               }
+
+               var d dep.Dependency
+               var err error
+
+               if len(rest) == 0 {
+                       d, err = dep.NewVaultReadQuery(path)
+               } else {
+                       d, err = dep.NewVaultWriteQuery(path, data)
+               }
+
                if err != nil {
                        return result, nil
                }
```

**Comment by sethvargo** [comment]
Hey @nbrownus 

Thank you for reporting that. I'll get this fixed up ASAP. Can you explain this a bit more:

> I am also curious why errors are no longer being reported.

Thanks!

**Comment by nbrownus** [comment]
`ParseVaultSecret` used to [report errors](https://github.com/hashicorp/consul-template/blob/v0.16.0/dependency/vault_secret.go#L164) but now all the errors are [gone](https://github.com/hashicorp/consul-template/blob/master/template/funcs.go#L294)

**Comment by sethvargo** [comment]
Ah - yes. As Vault matures, sometimes you might want a vault-write without any data. A future version of CT will actually deprecate the `secret` function in favor of a `vault.read`, `vault.write`, and `vault.list` function to match parity and give people more control.

The old functions were overloaded ("vault secret" could have corresponded to any operation, and the operation was decided at runtime). How the secret is split out into different parts and the operation is decided at config (reading) time.

I think that's what you're getting at, but the links you sent me are from two different parts of CT (one is the func map, the other is the dep). There are three vault dep types now: 

- `vault_list`: https://github.com/hashicorp/consul-template/blob/d818166af71cb7d6c84a57b3b8f69cd5bfe3eecd/dependency/vault_list.go
- `vault_read`: https://github.com/hashicorp/consul-template/blob/d818166af71cb7d6c84a57b3b8f69cd5bfe3eecd/dependency/vault_read.go
- `vault_write`: https://github.com/hashicorp/consul-template/blob/master/dependency/vault_write.go
- `vault_token`: https://github.com/hashicorp/consul-template/blob/d818166af71cb7d6c84a57b3b8f69cd5bfe3eecd/dependency/vault_token.go

The `vault_write` query _does_ accept the map of data and it [does return an error](https://github.com/hashicorp/consul-template/blob/d818166af71cb7d6c84a57b3b8f69cd5bfe3eecd/dependency/vault_write.go#L32), but [so too does `vault_read`](https://github.com/hashicorp/consul-template/blob/master/dependency/vault_read.go#L27). Maybe I'm missing what you're saying?

**Comment by nbrownus** [comment]
Neat! I am excited to see more expressive vault functions.

They do return the errors but those errors aren't returned by [`secretFunc`](https://github.com/hashicorp/consul-template/blob/d818166af71cb7d6c84a57b3b8f69cd5bfe3eecd/template/funcs.go#L297-L300)
