### ISSUE TITLE
Template  function 'service'  break compatibility in v0.18.0 ?

### ISSUE THREAD

**Issue by hinsqueg** [hashicorp/consul-template#857]
We are using v0.16.0, but when upgrading to v0.18.0-rc3,  consul-template report the template file is invalid format. The file is accepted by v0.16.0.

Then, I read the source file: funcs.go, health_service.go and dependency.go， finally found the answer: 

If you want to filter services by a specific health or health(s), can‘t  use old format: 
```
{{service "web" "passing, warning"}}
```
Must  insert vertical bar before health status， like this：
```
{{service "web" "|passing, warning"}}
``` 

But I lookup the README and CHANGELOG, not find anything about the function 'service' parameter format changed.   and rewrite all template  to new format is not easy.

So, is there any chance the v0.18.0 will be compatible with old format， like below patch:

```
diff --git a/template/funcs.go b/template/funcs.go
index 8aac7fd..6a107fa 100644
--- a/template/funcs.go
+++ b/template/funcs.go
@@ -369,6 +369,19 @@ func serviceFunc(b *Brain, used, missing *dep.Set) func(...string) ([]*dep.Healt
                        return result, nil
                }
 
+               if len(s) == 2 && s[1] != "" {
+                       // compatible with version <= 0.16.0
+
+                       switch s[1][0] {
+                       case byte('@'), byte('~'), byte('|'):
+                       default:
+                               r := []rune(s[0])
+                               if r[len(r)-1] != '.' {
+                                       s[1] = "|" + strings.TrimSpace(s[1])
+                               }
+                       }
+               }
+
                d, err := dep.NewHealthServiceQuery(strings.Join(s, ""))
                if err != nil {
                        return nil, err
```

### Consul Template version

Online Env: running consul-template 0.16.0
Test Env: running consul-template 0.18.0-rc3

### Configuration

template :

```liquid
{{range  $i, $e := service "test-demo-http" "passing,warning" }}
    { "address":  [  { "ip": "{{.Address}}", "port": {{.Port}} } ] }
{{end}}
```

### Debug output

```
2017/01/22 01:28:31.239483 [DEBUG] (runner) checking template 8811e5b7941ac06efa0da770aa1f1a0a
Consul Template returned errors:
/home/tester/consul-template/conf/test.tmpl: execute: template: :1:19: executing "" at <service "test-demo-h...>: error calling service: health.service: invalid format: "test-demo-httppassing,warning"
```

### Expected behavior

Like using v0.16.0,  the template is rendered success.

### Actual behavior

When using v0.18.0-rc3,  consul-template report  "invalid format"

**Comment by shakisha** [comment]
also on v.018.0, i have got the same identical issue.

**Comment by sethvargo** [comment]
Hi all,

Thank you for reporting. This was a bug that made its way in because we didn't have enough test coverage to catch it in a refactor. Sorry about that. You can see the fix in the PR was actually just a one-character change (https://github.com/hashicorp/consul-template/pull/859/files). This will go out with the next release. Thanks! I've also updated the README for new people to adopt the newer style moving forward. In the future, the multi-argument style will be deprecated and replaced with the pipe-filter style, but there will be a clearer deprecation path before the functionality is removed.

**Comment by rcarre** [comment]
Hi all,
moving from 0.12 to 0.20. Then neither old format `{{service "webcomws" "passing, warning, critical, maintenance" }}` nor new format `{{service "webcomws" "|passing, warning, critical, maintenance" }}` are running properly.

### Debug output for each try:

> 2019/08/21 13:43:28.807394 [ERR] (cli) /opt/application/webcom-server/conf/application.conf.tmpl: execute: template: :16:42: executing "" at <service "webcomws" "...>: error calling service: health.service: invalid format: "webcomws|passing, warning"

> 2019/08/21 13:44:25.576053 [ERR] (cli) /opt/application/webcom-server/conf/application.conf.tmpl: execute: template: :16:42: executing "" at <service "webcomws" "...>: error calling service: health.service: invalid format: "webcomws||passing, warning"
