### ISSUE TITLE
tagged addresses not available in service result

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul-template#861]
consul-template 0.18.0 added support for TaggedAddresses in the Node struct, but doesn't expose it in the HealthService struct.  In cases where a template needs a particular address (wan, for example), there's no way to do that, currently.

**Comment by sethvargo** [comment]
I have an open PR for this, and it's working, but there are some issues with the testing server that are causing failures.

**Comment by blalor** [comment]
Thanks @sethvargo!

**Comment by shakisha** [comment]
@blalor  can you help me, making an example of how you make it working?
Because on my side this "TaggedAddresses" it is not working.
