### ISSUE TITLE
no way to determine local datacenter

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul-template#862]
consul-template 0.18.0 has `node`, but the resulting CatalogNode (?) instance doesn't expose the local datacenter.  I want this to exclude the local node when iterating over a service in all datacenters.

**Comment by sethvargo** [comment]
Hi @blalor,

Thank you for opening an issue. This is because that API does not actually return the current data center, but I think that's a good enhancement. Could you please open an upsteam issue on Consul? Thanks!

**Comment by sethvargo** [comment]
For reference: https://www.consul.io/docs/agent/http/catalog.html#catalog_node
