### ISSUE TITLE
DedupManager.attemptLock will loop indefinitely if dedup session has expired due to consul server being down temporarily

### ISSUE THREAD

**Issue by Loushu** [hashicorp/consul-template#864]
If attemptLock fails to acquire lock from Consul due to expired session it will retry indefinitely, not releasing WaitGroup in the dedup manager. The periodic session renewal, once it fails, will be waiting on the same WaitGroup and will never re-attempt to renew the session.  

This can be replicated on a single node setup, shutting down consul server node for the duration enough to let dedup session expire.

Consul-template should be more resilient to Consul server outages and not enter an unrecoverable state.

The issue is present in 0.18

**Comment by sethvargo** [comment]
Hi @Loushu 

Thank you for opening an issue. Are you able to share some debug logs from when this occurs? Thanks!

/cc @armon @slackpad

**Comment by Loushu** [comment]
Here's a log from consul-template shortly after consul server has been down for about 10 seconds. Inspecting session list in consul shows no active sessions. The failed to acquire lock message at the end of the enclosed log continues indefinitely.
.... skipped a bunch of [WARN] (view) health.service...
2017/01/31 23:44:23.069472 [WARN] (view) health.service(et-ui-stack-et-ui@local|any): Unexpected response code: 500 (No path to datacenter) (retry attempt 5 after "4s")
2017/01/31 23:44:23.429508 [WARN] (runner) watching 228 dependencies - watching this many dependencies could DDoS your consul cluster
2017/01/31 23:44:23.702535 [INFO] (dedup) listing data for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:44:23.704535 [INFO] (dedup) attempting lock for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:44:30.716236 [ERR] (dedup) failed to acquire lock 'consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock': failed to read lock: Unexpected response code: 500
2017/01/31 23:44:40.717236 [INFO] (dedup) attempting lock for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:44:40.717236 [INFO] (dedup) acquired lock 'consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock'
2017/01/31 23:44:40.717236 [INFO] (runner) watcher triggered by de-duplication manager
2017/01/31 23:44:40.717236 [INFO] (runner) initiating run
2017/01/31 23:44:40.724237 [ERR] (runner) failed to update dependency data for de-duplication: encode failed: gob: type not registered for interface: []*dependency.KeyPair
2017/01/31 23:44:40.724237 [WARN] (runner) watching 228 dependencies - watching this many dependencies could DDoS your consul cluster
2017/01/31 23:44:50.725237 [INFO] (runner) initiating run
2017/01/31 23:44:50.737238 [ERR] (runner) failed to update dependency data for de-duplication: encode failed: gob: type not registered for interface: []*dependency.KeyPair
2017/01/31 23:44:50.768241 [INFO] (runner) rendered "D:/Consul/nginx/conf/consul_services_json.tmpl" => "D:/Consul/nginx/conf/consul_services.json"
2017/01/31 23:44:50.769241 [INFO] (runner) executing command "D:/Consul/nginx_reload.bat" from "D:/Consul/nginx/conf/consul_services_json.tmpl" => "D:/Consul/nginx/conf/consul_services.json"
2017/01/31 23:44:50.769241 [INFO] (child) spawning: D:/Consul/nginx_reload.bat
2017/01/31 23:44:51.926357 [WARN] (runner) watching 228 dependencies - watching this many dependencies could DDoS your consul cluster
2017/01/31 23:45:03.205485 [WARN] (dedup) lost lock ownership 'consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock'
2017/01/31 23:45:03.205485 [INFO] (dedup) attempting lock for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:45:03.205485 [INFO] (dedup) listing data for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:45:03.205485 [INFO] (runner) watcher triggered by de-duplication manager
2017/01/31 23:45:03.205485 [INFO] (runner) initiating run
2017/01/31 23:45:03.211485 [WARN] (runner) watching 228 dependencies - watching this many dependencies could DDoS your consul cluster
2017/01/31 23:45:13.212485 [INFO] (runner) initiating run
2017/01/31 23:45:13.253489 [INFO] (runner) rendered "D:/Consul/nginx/conf/consul_services_json.tmpl" => "D:/Consul/nginx/conf/consul_services.json"
2017/01/31 23:45:13.253489 [INFO] (runner) executing command "D:/Consul/nginx_reload.bat" from "D:/Consul/nginx/conf/consul_services_json.tmpl" => "D:/Consul/nginx/conf/consul_services.json"
2017/01/31 23:45:13.254490 [INFO] (child) spawning: D:/Consul/nginx_reload.bat
2017/01/31 23:45:14.386603 [WARN] (runner) watching 228 dependencies - watching this many dependencies could DDoS your consul cluster
2017/01/31 23:45:18.283992 [ERR] (dedup) failed to acquire lock 'consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock': failed to acquire lock: Unexpected response code: 500 (invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5")
2017/01/31 23:45:28.284992 [INFO] (dedup) attempting lock for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:45:28.352999 [ERR] (dedup) failed to acquire lock 'consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock': failed to acquire lock: Unexpected response code: 500 (invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5")
2017/01/31 23:45:38.353999 [INFO] (dedup) attempting lock for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:45:38.430007 [ERR] (dedup) failed to acquire lock 'consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock': failed to acquire lock: Unexpected response code: 500 (invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5")
2017/01/31 23:45:48.431007 [INFO] (dedup) attempting lock for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:45:48.540018 [ERR] (dedup) failed to acquire lock 'consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock': failed to acquire lock: Unexpected response code: 500 (invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5")
2017/01/31 23:45:58.541018 [INFO] (dedup) attempting lock for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:45:58.624026 [ERR] (dedup) failed to acquire lock 'consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock': failed to acquire lock: Unexpected response code: 500 (invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5")
2017/01/31 23:46:04.061570 [INFO] (dedup) listing data for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:46:08.625026 [INFO] (dedup) attempting lock for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:46:08.709034 [ERR] (dedup) failed to acquire lock 'consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock': failed to acquire lock: Unexpected response code: 500 (invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5")
2017/01/31 23:46:18.710034 [INFO] (dedup) attempting lock for template hash 1383be08a8e949dac9e5f0698ab50d7e
2017/01/31 23:46:18.786042 [ERR] (dedup) failed to acquire lock 'consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock': failed to acquire lock: Unexpected response code: 500 (invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5")

**Comment by Loushu** [comment]
And here's a log from consul server once it restarted:
    2017/01/31 18:44:32 [INFO] raft: Node at x.x.x.x:8300 [Candidate] entering Candidate state in term 10
    2017/01/31 18:44:32 [INFO] raft: Election won. Tally: 1
    2017/01/31 18:44:32 [INFO] raft: Node at x.x.x.x:8300 [Leader] entering Leader state
    2017/01/31 18:44:32 [INFO] consul: cluster leadership acquired
    2017/01/31 18:44:32 [INFO] consul: New leader elected: consul_server_xxxxx
    2017/01/31 18:44:33 [INFO] agent.rpc: Accepted client: 127.0.0.1:5036
    2017/01/31 18:44:33 [INFO] agent: Synced node info
    2017/01/31 18:45:03 [WARN] consul.kvs: Rejecting lock of consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock due to lock-delay until 2017-01-31 18:45:18.2054852 -0500 EST
    2017/01/31 18:45:08 [WARN] consul.kvs: Rejecting lock of consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock due to lock-delay until 2017-01-31 18:45:18.2054852 -0500 EST
    2017/01/31 18:45:13 [WARN] consul.kvs: Rejecting lock of consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock due to lock-delay until 2017-01-31 18:45:18.2054852 -0500 EST
    2017/01/31 18:45:18 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5043
    2017/01/31 18:45:28 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5047
    2017/01/31 18:45:38 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5052
    2017/01/31 18:45:48 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5052
    2017/01/31 18:45:58 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5052
    2017/01/31 18:46:08 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5057
    2017/01/31 18:46:18 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5057
    2017/01/31 18:46:28 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5059
    2017/01/31 18:46:38 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5068
    2017/01/31 18:46:49 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5068
    2017/01/31 18:46:59 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5068
    2017/01/31 18:47:09 [ERR] http: Request PUT /v1/kv/consul-template/dedup/1383be08a8e949dac9e5f0698ab50d7e/lock?acquire=c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5&flags=3304740253564472344, error: invalid session "c59b5cb2-9f6d-80e7-7591-973e2bfaf4f5" from=127.0.0.1:5092

**Comment by Loushu** [comment]
Once more thing I noticed: with latest version 0.18 I can turn on dedup functionality only from the command line. Adding it to configuration file didn't enable it. This used to work in 0.16 just fine.
