### ISSUE TITLE
option to fail on new blocking for *key*

### ISSUE THREAD

**Issue by dansteen** [hashicorp/consul-template#865]
consul-template v0.18.0 (5211c66)

With the newly added behavior to block on **key** (which I like!)  would it be possible to add a flag to tell consul to fail after blocking for a certain amount of time?  This way it won't simply hang while waiting for a key to become available.

Thanks!

**Comment by sethvargo** [comment]
Hi @dansteen 

Thank you for opening an issue. Can you explain a bit more about your use case? It seems like you might want to use `keyOrDefault` in your case. Having a timeout is somewhat contrary to the concept of a blocking query.

**Comment by dansteen** [comment]
Hi @sethvargo 

Sure!  The most basic example would be when using consul-template with systemd.   Systemd cannot distinguish between when an application is running, and when it is waiting on consul-template to resolve a key that is missing.   So systemd will start up consul-template and think that the app is running successfully.   If we could configure a fail timeout, then systemd would detect that things failed and could issue an alert.

More generally, I think there are three possible desired behaviors when a key is missing:

- Wait for the key to become available  (current behavior)
- Respond with a default value (available with keyOrDefault)
- Fail  (not an option at this point)

I think each of these has a place.

Thanks so much!

-Dan

**Comment by sethvargo** [comment]
Hey @dansteen 

Thank you for your reply. I don't think this is something that Consul Template should support, since this is an application-level issues, not really CT. If an application requires a certain configuration, that application should fail to start/restart, thus reporting upstream.

**Comment by dansteen** [comment]
fair enough.   Thanks!

**Comment by dansteen** [comment]
@sethvargo I ran into an additional case where this would be useful - integration testing.    If I want to test my config to make sure that it is valid, and that all the keys requested are valid and exist, it's very hard to do so if the process just hangs...

**Comment by dansteen** [comment]
@sethvargo any thoughts on this?

**Comment by yellowmegaman** [comment]
@dansteen @sethvargo I second this.
Got matrix build up and running today, to test config against different key sets and consul versions. If key is missing and there's no default value, build would just hang indefinitely. 
Failing templating process after defined number of seconds would be perfect.

**Comment by dansteen** [comment]
the workaround im using now is to use `timeout 5 -s INT` when running consul-template  that way if the template hasnt generated in 5 seconds it fails.  only works with the -once flag of course, but at least its something for some cases.   it still doesnt help debugging not stink though, since consul-template still wont tell you what keys are missing even in debug mode...

**Comment by dansteen** [comment]
the workaround im using now is to use `timeout 5 -s INT` when running consul-template  that way if the template hasnt generated in 5 seconds it fails.  only works with the -once flag of course, but at least its something for some cases.   it still doesnt help debugging not stink though, since consul-template still wont tell you what keys are missing even in debug mode...

**Comment by dansteen** [comment]
the workaround im using now is to use `timeout 5 -s INT` when running consul-template  that way if the template hasnt generated in 5 seconds it fails.  only works with the -once flag of course, but at least its something for some cases.   it still doesnt help debugging not stink though, since consul-template still wont tell you what keys are missing even in debug mode...

**Comment by dansteen** [comment]
the workaround im using now is to use `timeout 5 -s INT` when running consul-template  that way if the template hasnt generated in 5 seconds it fails.  only works with the -once flag of course, but at least its something for some cases.   it still doesnt help debugging not stink though, since consul-template still wont tell you what keys are missing even in debug mode...

**Comment by dansteen** [comment]
the workaround im using now is to use `timeout 5 -s INT` when running consul-template  that way if the template hasnt generated in 5 seconds it fails.  only works with the -once flag of course, but at least its something for some cases.   it still doesnt help debugging not stink though, since consul-template still wont tell you what keys are missing even in debug mode...

**Comment by yellowmegaman** [comment]
@dansteen nice! Can you please provide some details on how exactly you are launching it?

Actually i'm doing this:

```
#!/bin/bash
template="$1"
time=$(date +%s)
consul-template -consul-addr="$CONSUL" -log-level=trace -once -template "$template:/tmp/output$time" &> "/tmp/log$time" &
ctpid="$!"
sleep 3

if kill -0 "$ctpid" &> /dev/null; then
        kill -9 "$ctpid"
        wait $! 2>/dev/null
fi

cat "/tmp/log$time" | grep 'TRACE' | grep -w 'returned nil' | awk '{print $4}' | tr -d ':'
```

Output of script above is missing keys only. But it's messy, and didn't work with drone.io and i'm too lazy to dig, since that really should be achieved cleaner way.

**Comment by dansteen** [comment]
you basically  just add `timeout 5 -s INT` to the head of the `consul-template` line above.  Super easy, and kills consul-template after 5 seconds.
