### ISSUE TITLE
Vault secret behaviour change between 0.18.0-rc3 and 0.18.0

### ISSUE THREAD

**Issue by eolamey** [hashicorp/consul-template#867]
Hi,

We observed a change in behaviour using the result of the `secret` template function between 0.18.0-rc3 and 0.18.0 and I was wondering if it's a regression or if it's intended and we should change our templates.

### Consul Template version
Versions 0.18.0-rc3 and 0.18.0.

### Configuration
We don't use a consul configuration file, just the command below.

The (simplified) template is:
```liquid
{{ $secrets := secret "secret/foo" -}}
{{ $secrets.Data.super_secret }}
```

### Command
```shell
consul-template -consul-addr=consul.domain:8500 -vault-addr=https://vault.domain:8200 -vault-ssl-ca-cert=/etc/ssl/certs/ca-certificates.crt -vault-renew-token=false -vault-unwrap-token=false -once -template=foo.conf.ctmpl:foo.conf
```

### Debug output
With 0.18.0-rc3, the template renders and the debug output is:
```
2017/01/31 13:40:43.470246 [INFO] (runner) creating watcher
2017/01/31 13:40:43.470634 [INFO] (runner) starting
2017/01/31 13:40:43.470722 [DEBUG] (runner) running initial templates
2017/01/31 13:40:43.470909 [INFO] (runner) initiating run
2017/01/31 13:40:43.471045 [DEBUG] (runner) checking template 2a4d2c1437ef9a1a8a3039ffc4f4b06b
2017/01/31 13:40:43.471603 [DEBUG] (runner) was not watching 1 dependencies
2017/01/31 13:40:43.471739 [DEBUG] (watcher) adding vault.read(secret/foo)
2017/01/31 13:40:43.471817 [DEBUG] (runner) diffing and updating dependencies
2017/01/31 13:40:43.471869 [DEBUG] (runner) watching 1 dependencies
2017/01/31 13:40:43.548845 [DEBUG] (runner) receiving dependency vault.read(secret/foo)
2017/01/31 13:40:43.548877 [INFO] (runner) initiating run
2017/01/31 13:40:43.548884 [DEBUG] (runner) checking template 2a4d2c1437ef9a1a8a3039ffc4f4b06b
2017/01/31 13:40:43.549496 [DEBUG] (runner) rendering "foo.conf.ctmpl" => "foo.conf"
2017/01/31 13:40:43.575491 [INFO] (runner) rendered "foo.conf.ctmpl" => "foo.conf"
2017/01/31 13:40:43.575648 [DEBUG] (runner) diffing and updating dependencies
2017/01/31 13:40:43.575691 [DEBUG] (runner) vault.read(secret/foo) is still needed
2017/01/31 13:40:43.575754 [DEBUG] (runner) watching 1 dependencies
2017/01/31 13:40:43.575807 [INFO] (runner) once mode and all templates rendered
2017/01/31 13:40:43.575842 [INFO] (runner) stopping
2017/01/31 13:40:43.575866 [DEBUG] (runner) stopping watcher
2017/01/31 13:40:43.575897 [DEBUG] (watcher) stopping all views
```

With 0.18.0, the template doesn't render, and the output is:
```
2017/01/31 13:42:24.813324 [INFO] (runner) creating watcher
2017/01/31 13:42:24.813630 [INFO] (runner) starting
2017/01/31 13:42:24.813695 [DEBUG] (runner) running initial templates
2017/01/31 13:42:24.813733 [INFO] (runner) initiating run
2017/01/31 13:42:24.813761 [DEBUG] (runner) checking template 2a4d2c1437ef9a1a8a3039ffc4f4b06b
Consul Template returned errors:
foo.conf.ctmpl: execute: template: :2:16: executing "" at <$secrets.Data.s...>: can't evaluate field Data in type *dependency.Secret
```

### Expected behavior
The behaviour should be the same as 0.18.0-rc3 and the template should render.

### Actual behavior
The template doesn't render and `consul-template` exists with an error.

### Steps to reproduce
1. just run `consul-template` with the given template :)

**Comment by sethvargo** [comment]
Hi there,

This is the result of https://github.com/hashicorp/consul-template/issues/853, and rc3 had the incorrect behavior. Sorry about that. You should guard against the empty secret by doing this:

```liquid
{{ with secret "secret/foo" }}
{{ .Data.super_secret }}
{{ end }}
```

Sorry about the breaking change, but it was a regression in rc3 and we had to restore the originally behavior pre-18. You should always guard against the empty value. Again, sorry about the breaking change.

**Comment by eolamey** [comment]
I realise my ticket wasn't clear at all, I'm sorry, but the secret does exist in vault and does end up in the rendered output with any version prior to 0.18.0. If I change the template to use `with` instead of a variable assignment, it works in 0.18.0 (but it's not convenient for our particular templates which use secrets in several places in the file, with other keys keys being used and manipulated in-between).

**Comment by eolamey** [comment]
I'm not sure how to re-open this issue, should I create a new one?

**Comment by sethvargo** [comment]
Hi @eolamey 

Thank you for your reply. In 0.18, all template functions must guard against the empty value, which is the default return function. Sorry for the breaking change, but there is no other way to do it 😦

**Comment by eolamey** [comment]
That's alright, but in this case there is no empty value, the secret returned by vault contains a string. The difference is that I can't assign it to a variable with `$secrets :=` like before.

Or do you mean that in all cases, even when the secret is not empty and does indeed exist in vault, it should be used inside a `with` block?

**Comment by sethvargo** [comment]
Hi @eolamey 

You can assign using `with`:

```liquid
{{ with $secrets := secret "secret/foo" }}
{{ $secrets.Data.super_secret }}
{{ end }}
```

Consul Template has multi-pass execution, which you can read about more here: https://github.com/hashicorp/consul-template#multi-phase-execution
