### ISSUE TITLE
Not able to start consul-template with new config v0.18.0

### ISSUE THREAD

**Issue by buro1983** [hashicorp/consul-template#868]
I am not able to start consul-template while starting using service command, but it is working fine while starting through command line,

    ./consul-template --config=/tmp/consul-template/default.conf

template config:
    
    consul {
      address = "127.0.0.1:8500"

      ssl {
        enabled = true
        verify = true
        cert = "/usr/local/certs/service.crt"
        key =  "/usr/local/certs/service.key"
        ca_cert = "/usr/local/certs/service.ca"
      }
    }

    pid_file = "/var/run/consul-template.pid"

    template {
      source = "/usr/local/consul-template/template/consul.ctmpl"
     destination = "/etc/myservice/conf.d/my_services.conf"
     command = "service myservice reload"
    }

    log_level = "ERR"

Consul-template log

    2017/02/01 04:48:53 [WARN] ssl has been moved under the consul stanza. Update your configuration files and place ssl inside consul { }.
    panic: interface conversion: interface {} is string, not map[string]interface {}
    goroutine 1 [running]:
    github.com/hashicorp/consul-template/config.Parse(0xc4200f61e0, 0x1d3, 0x1d3, 0x3d3, 0xc4200f61e0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:271 +0xe27
    github.com/hashicorp/consul-template/config.FromFile(0xc420103a80, 0x3f, 0x200000003, 0xc4200001a0, 0xc420014000)
    /go/src/github.com/hashicorp/consul-template/config/config.go:338 +0x1a5
    github.com/hashicorp/consul-template/config.FromPath.func1(0xc420103a80, 0x3f, 0xa6e0a0, 0xc420067a00, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:379 +0x71
    path/filepath.walk(0xc420103a80, 0x3f, 0xa6e0a0, 0xc420067a00, 0xc4201105f0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:351 +0x81
    path/filepath.walk(0x7ffe1797ef4f, 0x2e, 0xa6e0a0, 0xc4200676c0, 0xc4201105f0, 0x0, 0x10)
    /usr/local/go/src/path/filepath/path.go:376 +0x414 
    path/filepath.Walk(0x7ffe1797ef4f, 0x2e, 0xc4201105f0, 0x2, 0x2)
    /usr/local/go/src/path/filepath/path.go:398 +0x14c
    github.com/hashicorp/consul-template/config.FromPath(0x7ffe1797ef4f, 0x2e, 0x1, 0x1, 0x0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:386 +0x1aa
    main.(*CLI).ParseFlags(0xc4201026c0, 0xc42006a090, 0x1, 0x1, 0xc4200e2100, 0x8c6ec8, 0x7, 0xc4201101d8)
    /go/src/github.com/hashicorp/consul-template/cli.go:480 +0x240c
    main.(*CLI).Run(0xc4201026c0, 0xc42006a080, 0x2, 0x2, 0x0)
    /go/src/github.com/hashicorp/consul-template/cli.go:65 +0x8e
    main.main()
    /go/src/github.com/hashicorp/consul-template/main.go:7 +0x139
    2017/02/01 04:48:53 [WARN] ssl has been moved under the consul stanza. Update your configuration     files and place ssl inside consul { }.
     panic: interface conversion: interface {} is string, not map[string]interface {}
    goroutine 1 [running]:
    github.com/hashicorp/consul-template/config.Parse(0xc4200e81e0, 0x1d3, 0x1d3, 0x3d3, 0xc4200e81e0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:271 +0xe27
    github.com/hashicorp/consul-template/config.FromFile(0xc4200f5a80, 0x3f, 0x200000003, 0xc4200001a0, 0xc420014000)
    /go/src/github.com/hashicorp/consul-template/config/config.go:338 +0x1a5
    github.com/hashicorp/consul-template/config.FromPath.func1(0xc4200f5a80, 0x3f, 0xa6e0a0, 0xc420067d40, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:379 +0x71
    path/filepath.walk(0xc4200f5a80, 0x3f, 0xa6e0a0, 0xc420067d40, 0xc420100630, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:351 +0x81
    path/filepath.walk(0x7ffc1d1c1f4f, 0x2e, 0xa6e0a0, 0xc420067a00, 0xc420100630, 0x0, 0x10)
    /usr/local/go/src/path/filepath/path.go:376 +0x414
    path/filepath.Walk(0x7ffc1d1c1f4f, 0x2e, 0xc420100630, 0x2, 0x2)
    /usr/local/go/src/path/filepath/path.go:398 +0x14c
    github.com/hashicorp/consul-template/config.FromPath(0x7ffc1d1c1f4f, 0x2e, 0x1, 0x1, 0x0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:386 +0x1aa
    main.(*CLI).ParseFlags(0xc4200f46c0, 0xc42000a130, 0x1, 0x1, 0xc4200d4100, 0x8c6ec8, 0x7, 0xc420100218)
    /go/src/github.com/hashicorp/consul-template/cli.go:480 +0x240c
    main.(*CLI).Run(0xc4200f46c0, 0xc42000a120, 0x2, 0x2, 0x0)
    /go/src/github.com/hashicorp/consul-template/cli.go:65 +0x8e
    main.main()
    /go/src/github.com/hashicorp/consul-template/main.go:7 +0x139
    2017/02/01 04:48:53 [WARN] ssl has been moved under the consul stanza. Update your configuration      files and place ssl inside consul { }.
    panic: interface conversion: interface {} is string, not map[string]interface {}
    goroutine 1 [running]:
    github.com/hashicorp/consul-template/config.Parse(0xc4200e81e0, 0x1d3, 0x1d3, 0x3d3, 0xc4200e81e0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:271 +0xe27
    github.com/hashicorp/consul-template/config.FromFile(0xc4200f5a80, 0x3f, 0x200000003, 0xc4200001a0, 0xc420014000)
    /go/src/github.com/hashicorp/consul-template/config/config.go:338 +0x1a5
    github.com/hashicorp/consul-template/config.FromPath.func1(0xc4200f5a80, 0x3f, 0xa6e0a0, 0xc42010a1a0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:379 +0x71
    path/filepath.walk(0xc4200f5a80, 0x3f, 0xa6e0a0, 0xc42010a1a0, 0xc420100630, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:351 +0x81
    path/filepath.walk(0x7ffe1dc38f4f, 0x2e, 0xa6e0a0, 0xc420067e10, 0xc420100630, 0x0, 0x10)
    /usr/local/go/src/path/filepath/path.go:376 +0x414
    path/filepath.Walk(0x7ffe1dc38f4f, 0x2e, 0xc420100630, 0x2, 0x2)
    /usr/local/go/src/path/filepath/path.go:398 +0x14c
    github.com/hashicorp/consul-template/config.FromPath(0x7ffe1dc38f4f, 0x2e, 0x1, 0x1, 0x0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:386 +0x1aa
    main.(*CLI).ParseFlags(0xc4200f46c0, 0xc42000a130, 0x1, 0x1, 0xc4200d4100, 0x8c6ec8, 0x7, 0xc420100218)
    /go/src/github.com/hashicorp/consul-template/cli.go:480 +0x240c
    main.(*CLI).Run(0xc4200f46c0, 0xc42000a120, 0x2, 0x2, 0x0)
    /go/src/github.com/hashicorp/consul-template/cli.go:65 +0x8e
    main.main()
    /go/src/github.com/hashicorp/consul-template/main.go:7 +0x139
    2017/02/01 04:48:53 [WARN] ssl has been moved under the consul stanza. Update your configuration   files and place ssl inside consul { }. 
    panic: interface conversion: interface {} is string, not map[string]interface {}
    goroutine 1 [running]:
    github.com/hashicorp/consul-template/config.Parse(0xc4200f21e0, 0x1d3, 0x1d3, 0x3d3, 0xc4200f21e0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:271 +0xe27
    github.com/hashicorp/consul-template/config.FromFile(0xc4200fda00, 0x3f, 0x200000003, 0xc4200001a0, 0xc420015300)
    /go/src/github.com/hashicorp/consul-template/config/config.go:338 +0x1a5
    github.com/hashicorp/consul-template/config.FromPath.func1(0xc4200fda00, 0x3f, 0xa6e0a0, 0xc42006fba0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:379 +0x71
    path/filepath.walk(0xc4200fda00, 0x3f, 0xa6e0a0, 0xc42006fba0, 0xc42010c5e0, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:351 +0x81
    path/filepath.walk(0x7ffebaea2f4f, 0x2e, 0xa6e0a0, 0xc42006f860, 0xc42010c5e0, 0x0, 0x10)
    /usr/local/go/src/path/filepath/path.go:376 +0x414
    path/filepath.Walk(0x7ffebaea2f4f, 0x2e, 0xc42010c5e0, 0x2, 0x2)
    /usr/local/go/src/path/filepath/path.go:398 +0x14c
    github.com/hashicorp/consul-template/config.FromPath(0x7ffebaea2f4f, 0x2e, 0x1, 0x1, 0x0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:386 +0x1aa  
    main.(*CLI).ParseFlags(0xc4200fc640, 0xc4200620d0, 0x1, 0x1, 0xc4200de100, 0x8c6ec8, 0x7, 0xc42010c1c8)
    /go/src/github.com/hashicorp/consul-template/cli.go:480 +0x240c
    main.(*CLI).Run(0xc4200fc640, 0xc4200620c0, 0x2, 0x2, 0x0)
    /go/src/github.com/hashicorp/consul-template/cli.go:65 +0x8e
    main.main()
    /go/src/github.com/hashicorp/consul-template/main.go:7 +0x139
    2017/02/01 04:48:54 [WARN] ssl has been moved under the consul stanza. Update your configuration     files and place ssl inside consul { }.
    panic: interface conversion: interface {} is string, not map[string]interface {}
    goroutine 1 [running]:
    github.com/hashicorp/consul-template/config.Parse(0xc4200e81e0, 0x1d3, 0x1d3, 0x3d3, 0xc4200e81e0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:271 +0xe27
    github.com/hashicorp/consul-template/config.FromFile(0xc4200f5a80, 0x3f, 0x200000003, 0xc4200001a0, 0xc420014000)
    /go/src/github.com/hashicorp/consul-template/config/config.go:338 +0x1a5
    github.com/hashicorp/consul-template/config.FromPath.func1(0xc4200f5a80, 0x3f, 0xa6e0a0,     0xc420067a00, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:379 +0x71
    path/filepath.walk(0xc4200f5a80, 0x3f, 0xa6e0a0, 0xc420067a00, 0xc420100630, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:351 +0x81
    path/filepath.walk(0x7ffceec1bf4f, 0x2e, 0xa6e0a0, 0xc4200676c0, 0xc420100630, 0x0, 0x10)
    /usr/local/go/src/path/filepath/path.go:376 +0x414
    path/filepath.Walk(0x7ffceec1bf4f, 0x2e, 0xc420100630, 0x2, 0x2)
    /usr/local/go/src/path/filepath/path.go:398 +0x14c
    github.com/hashicorp/consul-template/config.FromPath(0x7ffceec1bf4f, 0x2e, 0x1, 0x1, 0x0)
    /go/src/github.com/hashicorp/consul-template/config/config.go:386 +0x1aa
    main.(*CLI).ParseFlags(0xc4200f46c0, 0xc42000a130, 0x1, 0x1, 0xc4200d4100, 0x8c6ec8, 0x7, 0xc420100218)
    /go/src/github.com/hashicorp/consul-template/cli.go:480 +0x240c
    main.(*CLI).Run(0xc4200f46c0, 0xc42000a120, 0x2, 0x2, 0x0)
    /go/src/github.com/hashicorp/consul-template/cli.go:65 +0x8e
    main.main()
    /go/src/github.com/hashicorp/consul-template/main.go:7 +0x139

>[WARN] ssl has been moved under the consul stanza. Update your configuration files and place ssl inside consul { }.

This warning message is also unexpected because ssl config is already inside consul stanza. 
Please let me know if it is an issue from consul-template side or I am missing something.

**Comment by buro1983** [comment]
Root cause may be same for this issue and #866 . I have replaced v0.15.0 binary with v0.18.0 and then tried to start and it failed. I modified config file later, but template never read the new config file.

**Comment by sethvargo** [comment]
Hi @buro1983 

I cannot reproduce this using Consul Template v0.18.0. Are you sure this is the config you're loading? I do not get the warning about moving inside the SSL config or the panic.

```hcl
consul {
  address = "127.0.0.1:8500"

  ssl {
    enabled = true
    verify = true
  }
}

pid_file = "/var/run/consul-template.pid"
log_level = "ERR"
```

```
consul-template -config=config.hcl -log-level=debug
2017/02/02 23:30:25.584992 [INFO] consul-template v0.18.0 (d96b750)
2017/02/02 23:30:25.585019 [INFO] (runner) creating new runner (dry: false, once: false)
2017/02/02 23:30:25.585316 [DEBUG] (runner) final config: {"Consul":{"Address":"127.0.0.1:8500","Auth":{"Enabled":false,"Username":"","Password":""},"Retry":{"Attempts":5,"Backoff":250000000,"Enabled":true},"SSL":{"CaCert":"","CaPath":"","Cert":"","Enabled":true,"Key":"","ServerName":"","Verify":true},"Token":""},"Dedup":{"Enabled":false,"MaxStale":2000000000,"Prefix":"consul-template/dedup/","TTL":15000000000},"Exec":{"Command":"","Enabled":false,"Env":{"Blacklist":[],"Custom":[],"Pristine":false,"Whitelist":[]},"KillSignal":2,"KillTimeout":30000000000,"ReloadSignal":null,"Splay":0,"Timeout":0},"KillSignal":2,"LogLevel":"debug","MaxStale":2000000000,"PidFile":"","ReloadSignal":1,"Syslog":{"Enabled":false,"Facility":"LOCAL0"},"Templates":[],"Vault":{"Address":"http://127.0.0.1:8200","Enabled":true,"RenewToken":true,"Retry":{"Attempts":5,"Backoff":250000000,"Enabled":true},"SSL":{"CaCert":"","CaPath":"","Cert":"","Enabled":true,"Key":"","ServerName":"","Verify":true},"UnwrapToken":false},"Wait":{"Enabled":false,"Min":0,"Max":0}}
2017/02/02 23:30:25.585434 [INFO] (runner) creating watcher
2017/02/02 23:30:25.585534 [INFO] (runner) starting
2017/02/02 23:30:25.585582 [DEBUG] (runner) running initial templates
2017/02/02 23:30:25.585635 [INFO] (runner) initiating run
2017/02/02 23:30:25.585650 [DEBUG] (runner) diffing and updating dependencies
2017/02/02 23:30:25.585667 [DEBUG] (runner) watching 0 dependencies
```

Seems to be working for me.

**Comment by buro1983** [comment]
Did you try to start using service command? I also did not face any issue while using command line. But the issue reported here observed when I tried to start template using service command. 

First I coped new binary and started using old config. After that I replaced old config with new one and started again.

**Comment by sethvargo** [comment]
Hi @buro1983 

Thank you for your reply. I'm not sure what you mean by "service command" - could you explain more? v0.15->v0.18 is a large jump where both deprecations and breaking changes have occurred. You can view the changelog for the complete list, but it's possible you have a configuration that was valid in 0.15, deprecated in 0.16 and 0.17, and was removed in 0.18.

**Comment by buro1983** [comment]
I meant to say "service consul-template restart". Did you try to start/stop consul-template using init or init.d?

**Comment by sethvargo** [comment]
Hi @buro1983 

Without your init config, I cannot reproduce this. The configuration of your init configuration determines the way the process is started/restarted.

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/consul-template/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
