### ISSUE TITLE
consul-template 0.18.0 hangs when there're missing keys

### ISSUE THREAD

**Issue by agonzalezandino** [hashicorp/consul-template#870]
### Consul Template version
consul-template v0.18.0 (5211c66)

### Configuration
None. We're not passing any particular configuration to consul-template CLI

The template has been placed in: /tmp/test.ctmpl

```liquid
{{ key "test" }}
```

### Command

```shell
consul-template -log-level debug -consul-addr consul.service.consul:8500 -template "/tmp/test.ctmpl:/tmp/test" -once
```

### Debug output
https://gist.github.com/agonzalezandino/ad4bd6088a26add01ec61d908032d6f3

### Expected behavior
As in previous versions, if there're missing keys we should've seen something like:

```shell
2017/02/02 11:16:27 [WARN] ("key(test)") Consul returned no data (does the path exist?)
```

### Actual behavior
It just hangs with no output at all

### Steps to reproduce
Run the same command using the template referenced above

### References
None as far as I could see

**Comment by jippi** [comment]
```
Query Consul for the value at the given key. If the key cannot be converted to a string-like value, an error will occur. If the key does not exist, Consul Template will block until the key is present. To avoid blocking, see keyOrDefault or keyExists. Keys are queried using the following syntax:
```

https://github.com/hashicorp/consul-template#key

**Comment by agonzalezandino** [comment]
Thank you @jippi! I totally overlooked that new feature in 0.18.0.
