### ISSUE TITLE
examples do not show use of running command after update

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul-template#871]
https://github.com/hashicorp/consul-template/blob/v0.18.0/README.md

> As an added bonus, `consul-template` can optionally run arbitrary commands when the update process completes. See the [Examples](https://github.com/hashicorp/consul-template/tree/master/examples) folder for some scenarios where this functionality might prove useful.

None of the examples appear to show invocation of a command after an update.

**Comment by jippi** [comment]
Can be found here; https://github.com/hashicorp/consul-template#exec-mode :)

**Comment by blalor** [comment]
There are two types of command invocations; one where the entire consul-template process acts as pid 1 for a child, and another where commands are invoked on each template update.  The exec-mode section further down the file references the former case.  The text I quoted is somewhat vague, but I expect it to address the latter case; it doesn't technically say that I _will_ find examples of that in the examples directory, merely that those scenarios may be applicable.

Regardless, I went through every example looking for a case where the per-template command would be run, and there aren't any. :-)

**Comment by sethvargo** [comment]
Hi @blalor 

There are a ton of examples of this in the README:

- https://github.com/hashicorp/consul-template#command-line

```
consul-template \
  -consul-addr my.consul.internal:6124 \
  -template "/tmp/nginx.ctmpl:/var/nginx/nginx.conf:service nginx restart" \
  -template "/tmp/redis.ctmpl:/var/redis/redis.conf:service redis restart" \
  -template "/tmp/haproxy.ctmpl:/var/haproxy/haproxy.conf"
```

- https://github.com/hashicorp/consul-template#configuration-files

```hcl
template {
  // This is the optional command to run when the template is rendered. The
  // command will only run if the resulting template changes. The command must
  // return within 30s (configurable), and it must have a successful exit code.
  // Consul Template is not a replacement for a process monitor or init system.
  command = "restart service foo"
```

Exec mode only supports one command, but you can combine exec mode and template commands in the same Consul Template process.
