### ISSUE TITLE
Windows Binaries missing extensions

### ISSUE THREAD

**Issue by scyellleader** [hashicorp/consul-template#875]
Looks like the binaries in the windows zips for v18 are missing the .exe extension.  The binary works if you add the extension, but this is breaking chef recipes and scripts.  Is this by design and how the packages will be moving forward or is it an oversight?

### Steps to reproduce

1. Download v18 windows zip from releases site.
2. Extract
3. :-(

**Comment by sethvargo** [comment]
This is fixed in 5b5b594.
