### ISSUE TITLE
Cannot force exit 0 on commands specified through the configuration file

### ISSUE THREAD

**Issue by shakisha** [hashicorp/consul-template#886]
I use consul-template with a configuration file;

basically i migrated from version 0.14 to 0.18, but now, when exit of a command it is not zero, the consul-template will stop execution and tell me :

````
=> "/etc/sysconfig/iptables": child: command exited with a non-zero exit status:
This is assumed to be a failure. Please ensure the command
````

from cli version of consul-template i can just append  
|| true  
to the command, but from configuration file this is not working:

command         = "/sbin/iptables-restore < /etc/sysconfig/iptables || true"

giving me the same error as before.

**Comment by sethvargo** [comment]
Please see [this section](https://github.com/hashicorp/consul-template/blob/master/CHANGELOG.md#v0180-january-20-2017) of the 0.18 CHANGELOG which says:

> A shell is no longer assumed for Template commands. Previous versions of Consul Template assumed /bin/sh (cmd on Windows) as the parent process for the template command. Due to user requests and a desire to customize the shell, Consul Template no longer wraps the command in a shell. For most commands, this change will be transparent. If you were utilizing shell-specific functions like &&, ||, or conditionals, you will need to wrap you command in a shell, for example:
> 
> ```shell
> -template "in.tpl:out.tpl:/bin/bash -c 'echo a || b'"
> ```
>
> or
>
> ```hcl
> template {
>   command = "/bin/bash -c 'echo a || b'"
> }
> ```

I've updated the README to make this clearer.

**Comment by shakisha** [comment]
@sethvargo oh, very thank you, you saved my life on this.
