### ISSUE TITLE
Rendering all the nodes in giving strange output

### ISSUE THREAD

**Issue by shakisha** [hashicorp/consul-template#887]
I'm using consul-template to render an iptables rules;

basically i want a datacenter1 to allow all the requests from **ALL** nodes of datacenter2, so i've put this keys on the template file:

````
#CONSUL-TEMPLATE AUTOMATIC GENERATED RULES {{nodes "@datacenter2"}}
-A INPUT -s {{.Address}} -p udp -m udp --dport 45 -j ACCEPT {{end}}
````

but i have got this error:
>parse: template: :20: unexpected {{end}}

if i remove the {{end}} at the end of the template i have got very strange output, nothing related to ip addresses, like 
>#CONSUL-TEMPLATE AUTOMATIC GENERATED RULES 0xc4201a0c00 0xc4201a0c30 0xc4201a0c60 0xc4201a0c90 0xc4201a0cc0

What can be the issue?

**Comment by sethvargo** [comment]
You need to `range` over the `nodes` query. It returns a slice.
