### ISSUE TITLE
consul-template starts the command before rendering template

### ISSUE THREAD

**Issue by sachinhub** [hashicorp/consul-template#895]
we are using consul-template to start and reload haproxy. we upgraded from consul-template version 0.16.0 to 0.18.0 and the following problem started coming. It was working fine till 0.16.0. we required to upgrade because we started using "scratch" keyword in our template which is only supported in 0.18.0.

Following is the docker CMD we use to start the consul template. 

```
# CMD ["consul-template", "-config=/tmp/haproxy.json","-log-level=debug"]
CMD ["consul-template", "-consul-addr", "consul.elasticrun.in:8500", "-template", "/tmp/haproxy.ctmpl:/etc/haproxy/haproxy.cfg", "-exec", "haproxy -f /etc/haproxy/haproxy.cfg -sf $(pidof haproxy)"]
```

The container fails with following logs - 
```
2017/02/16 17:25:09 [WARN] consul now accepts a stanza instead of a string. Update your configuration files and change consul = "" to consul { } instead.
HA-Proxy version 1.6.9 2016/08/30
Usage : haproxy [-f <cfgfile>]* [ -vdVD ] [ -n <maxconn> ] [ -N <maxpconn> ]
        [ -p <pidfile> ] [ -m <max megs> ] [ -C <dir> ] [-- <cfgfile>*]
        -v displays version ; -vv shows known build options.
        -d enters debug mode ; -db only disables background mode.
        -dM[<byte>] poisons memory with <byte> (defaults to 0x50)
        -V enters verbose mode (disables quiet mode)
        -D goes daemon ; -C changes to <dir> before loading files.
        -q quiet mode : don't display messages
        -c check mode : only check config files and exit
        -n sets the maximum total # of connections (2000)
        -m limits the usable amount of memory (in MB)
        -N sets the default, per-proxy maximum # of connections (2000)
        -L set local peer name (default to hostname)
        -p writes pids of all children to this file
        -de disables epoll() usage even when available
        -dp disables poll() usage even when available
        -dS disables splice usage (broken on old kernels)
        -dV disables SSL verify on servers side
        -sf/-st [pid ]* finishes/terminates old pids.

Copyright 2000-2016 Willy Tarreau <willy@haproxy.org>
```

If we login to the Docker container manually and then run consul-template it runs fine 2nd time. on 1st time execution it fails with the same error above.

I suspect that consul-template is starting haproxy even before the file is written completly causing haproxy to fail.

Any inputs?

**Comment by sethvargo** [comment]
Hi @sachinhub 

Thanks for opening an issue. What's happening is that you're passing `-sf` `$(pidof)`, and that value is not populated the first time it runs, so it's erroring out. You can probably confirm this by running a script like this instead:

```
CMD ["consul-template", "-consul-addr", "consul.elasticrun.in:8500", "-template", "/tmp/haproxy.ctmpl:/etc/haproxy/haproxy.cfg", "-exec", "test -f /etc/haproxy/haproxy.cfg || echo "not present""]
```

**Comment by sachinhub** [comment]
Tried below command which prints old haproxy.cfg content (that is before template is applied by consul template.

```
CMD ["consul-template", "-consul-addr", "consul.elasticrun.in:8500", "-template", "/tmp/haproxy.ctmpl:/etc/haproxy/haproxy.cfg", "-exec", "cat /etc/haproxy/haproxy.cfg"]
```
It may also be a problem with -sf flag, but if i run haproxy standalone command with -sf flag it works well.

Moreover the exact same command was working fine with consul template version 0.16.0.

@sethvargo can you please let me know the correct CMD which i can use for running haproxy. My intention is to refresh/restart haproxy whenever there is a configuration change.

**Comment by sethvargo** [comment]
Hi @sachinhub 

I still can't reproduce this with just Consul Template. I haven't tried using Docker yet, but it would be helpful if you can see if this reproduces outside of Docker, as I have been unsuccessful in doing so. If we can't get this to reproduce without Docker, it might be something odd going on inside the container. I'm not saying this isn't a bug, I'm just trying to figure out why I cannot reproduce this.

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/consul-template/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
