### ISSUE TITLE
Where are the releases for amd-64?

### ISSUE THREAD

**Issue by mastermindg** [hashicorp/consul-template#897]
I'm trying to download the latest release for amd-64. According to the README they should be under releases but I only see the source code compressed. Where the binaries?

**Comment by sethvargo** [comment]
https://releases.hashicorp.com/consul-template/0.18.1/

**Comment by mastermindg** [comment]
Wouldn't it be nice if this were on the README?

**Comment by sethvargo** [comment]
It was supposed to be linked (it was linked, but the link wasn't rendering): https://github.com/hashicorp/consul-template/compare/fe42eb0a0ac9355602ed7bf97ba7ce206bbbfaaf...aff696abfcfc56f0dfbe8886876d18d103a99285
