### ISSUE TITLE
executeTemplate usage

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/consul-template#898]
`executeTemplate` documentation appears to be super confusing. I am just not able to under what this means in the documentation
```
Even with a new context:
{{ executeTemplate "custom" 42 }}
```
Can you help me to understand how this 42 is getting used and how use that in a template?

**Comment by sethvargo** [comment]
The optional second argument is the payload to send to the template. If you had a parameterized template, the value passed in becomes `.` in the template. You must define a template before use.

**Comment by sethvargo** [comment]
For example:

```liquid
{{ define "custom" }}{{ . }}{{ end }}
{{ executeTemplate "custom" 42 }}
```

would render

```text
42
```

**Comment by vrenjith** [comment]
>
> Hi Seth, thank you for the update. So to pass multiple values can you suggest how we can construct an object. I am looking at using it for defining a template that receives multiple values. An example for that will be really helpful.
>
>
-- 
Regards,
Renjith
