### ISSUE TITLE
Skip rendering template block

### ISSUE THREAD

**Issue by itatabitovski** [hashicorp/consul-template#899]
Is it possible to have a block that will not be rendered by consul-template? I couldn't find anything in the docs.

```
{{ key "service/redis/maxconns" }}   - this gets read from consul

{% raw % }
{{ key "service/redis/maxconns" }} - this is left as is
{% endraw % } 
```

The use for this would be when rendering template in two steps, for example your CI generates nomad job file that contains consul-template syntax for consul to render on runtime.

**Comment by sethvargo** [comment]
Hi @itatabitovski 

Thank you for opening an issue. There are a few things you can do here:

- Use custom delimiters:

```liquid
<% real_template %>
{{ later_template }}
```

parse the first with `<%` and the second with `{{` (default)

- Use text blocks

```liquid
{{ `{{ foo }}` }}
```

- Read other thing from a file

```liquid
{{ file "other_template" }} # will not be recursively processed
```

Please let me know if you have any questions. You can read more about Go's templating language here: https://golang.org/pkg/text/template/

**Comment by tyliec** [comment]
For others who have this problem, I found that the solution for me was to use a combination of both since I needed to survive two rounds of `consul-template`.

So a

```
{{ file "test" }}
```

where the `test` file contained:

```
{{ `{{ env "NOMAD_PORT_tcp" }}` }}
```
