### ISSUE TITLE
Support tree function both for Consul and Vault

### ISSUE THREAD

**Issue by leanneb** [hashicorp/consul-template#900]
In order not to have different files generated for key-value pairs obtained from Vault and Consul; it would be nice to have a function (similar to the tree function available for Consul) that given a key for consul and another one for vault, it outputs an array of KeyPair with the properties from both sources. The output from this function can then be easily used to generate a YAML file with the combined properties. An example of how the template would look like is:

   {{treeCV "consulKey" "vaultKey" | explode | toYAML}}

where treeCV would be the new function.

**Comment by sethvargo** [comment]
Hi @leanneb 

Thank you for opening an issue. Consul and Vault have very different structures, so it's not possible to merge them like this. Additionally, we recommend you do this sort of compilation of Consul Template, use a plugin, or use the new scratch to save variables and plug them in where necessary.
