### ISSUE TITLE
read nomad runtime environment

### ISSUE THREAD

**Issue by waterdudu** [hashicorp/consul-template#901]
Hi,

Is there a way to read nomad runtime environment, like `NOMAD_PORT_<label>`?

https://www.nomadproject.io/docs/runtime/environment.html

**Comment by sethvargo** [comment]
Hey @waterdudu 

You can use the `env` function to read environment variables. I don't know if they are passed into the subprocess though. /cc @dadgar for more insights.

**Comment by dadgar** [comment]
@waterdudu You will have to use Nomad 0.5.3+ or later to have access to those environment variables

**Comment by sethvargo** [comment]
Thanks @dadgar 

Does that answer your question @waterdudu ?

**Comment by waterdudu** [comment]
I run a grpc server with tag `tcp-service`, but `NOMAD_PORT_tcp` still has no value.

Here is the `haproxy.tmpl` file.

```
{{ range services }}{{ if in .Tags "tcp-service" }}
frontend {{ .Name }}_frontend
    mode tcp
    bind *:{{ env "NOMAD_PORT_tcp" }}
    use_backend {{ .Name }}_backend
{{ end }}{{ end }}


{{ range services }}{{ if in .Tags "tcp-service" }}
backend {{ .Name }}_backend
    mode tcp
    balance roundrobin
    option tcplog
    {{ range service .Name }}
    server {{ .Node }}-{{ .Port }} {{ .Address }}:{{ .Port }}{{ end }}
    {{ end }}{{ end }}
```


And the rendered file `haproxy.cfg`
```
frontend simple-server-grpc_frontend
    mode tcp
    bind *:
    use_backend simple-server-grpc_backend

backend simple-server-grpc_backend
    mode tcp
    balance roundrobin
    option tcplog

    server node-1-39570 10.0.1.166:39570
```

**Comment by sethvargo** [comment]
Hi @waterdudu 

Can you confirm which version of Nomad you are using? I don't think this is an issue for Consul Template, so it might be better to open this over on Nomad.

**Comment by waterdudu** [comment]
Nomad version is v0.5.4, and consul-template version is 0.18.1

**Comment by dadgar** [comment]
@waterdudu Are you using the [`template` block](https://www.nomadproject.io/docs/job-specification/template.html)?

**Comment by waterdudu** [comment]
@dadgar 
yep


`consul-template.hcl`

```
template {
  source = "/opt/consul-template/haproxy.ctmpl"
  destination = "/etc/haproxy/haproxy.cfg"
  command = "service haproxy reload"
  command_timeout = "30s"
  perms = 0644
  backup = true
  left_delimiter = "{{"
  right_delimiter = "}}"
  wait {
    min = "1s"
    max = "4s"
  }
}
```

**Comment by dadgar** [comment]
@waterdudu Hey I am slightly confused. You are running consul-template as its own binary or via Nomad's built in template block I linked (you would put that it a Nomad job file). If you are running via Nomad, those are not all valid fields. So I believe you are running consul-template on its own. 

1) Is consul-template within a task run by Nomad?
2) If you list the environment variables where you are running consul-template, is that one defined?

**Comment by waterdudu** [comment]
Hi @dadgar , sorry to make you confused. I am running consul-template as its own, a upstart service. There is a script in `/etc/init/consul-template.conf`.

**Comment by dadgar** [comment]
I see. So that environment variable does not exist for that consul-template process then. The Nomad environment variables are only made available to processes started by Nomad.

**Comment by waterdudu** [comment]
Thanks for your reply. So I can only access the environment variables if consul-template were ran by nomad?

By the way, I also want to access the meta data for a service. As the doc says, `To access map data such as NodeTaggedAddresses or NodeMeta, use Go's text/template map indexing.`, but when I put `{{index .NodeMeta "port"}}` in `haproxy.tmpl`, I got the following error

```
/opt/consul-template/haproxy.ctmpl: execute: template: :29:20: executing "" at <.NodeMeta>: can't evaluate field NodeMeta in type *dependency.CatalogSnippet
```

But it seems NodeMeta is returned in healthservice struct
https://github.com/hashicorp/consul-template/blob/master/dependency/health_service.go#L45

**Comment by dadgar** [comment]
@sethvargo ^

**Comment by sethvargo** [comment]
Hi @waterdudu 

Let's try not to conflate issues please. If you are not running CT under Nomad, there's no way CT could read Nomad's environment; that's how process environments work. Nomad has a built-in template block you can use to execute a task and that environment will be populated.

Could you please open a new issue for the NodeMeta issue and complete the issue template that pops up please? Thanks! 😄
