### ISSUE TITLE
keyOrDefault returns default value if a key has a null value in consul

### ISSUE THREAD

**Issue by dansteen** [hashicorp/consul-template#903]
### Consul Template version

consul-template v0.18.0 (5211c66)

### Configuration

```key: {{ keyOrDefault "app/core-api-java/1234/aws/globalDefault/protocol" "BOB" }}```

### Command
`consul-template  -once -dry -template=/tmp/generate_config_52950.tmpl:/tmp/generate_config_52950.conf`

### Expected behavior
In the case where `app/core-api-java/1234/aws/globalDefault/protocol` is set in consul, but has a null value, I would expect an empty string to be placed in the config file.

### Actual behavior
It places the "Default" value ("BOB" in this case) into the file instead.

**Comment by sethvargo** [comment]
Hi @dansteen 

This is behaving as intended and as-documented:

> Query Consul for the value at the given key path. If the key does not exist, the default value will be used instead. 

In this case, the key exists, but has a null value, thus null is being returned.

**Comment by dansteen** [comment]
@sethvargo so, the thing is,   having a null value is not the same as not existing.  This is even true from consuls perspective:

```curl -s http://consul.prod.awse.traitify.com:8500/v1/kv/app/core-api-java/1234/aws/globalDefault/protocol
[{"LockIndex":0,"Key":"app/core-api-java/1234/aws/globalDefault/protocol","Flags":0,"Value":null,"CreateIndex":10175404,"ModifyIndex":10175544}]```

``` curl -s http://consul.prod.awse.traitify.com:8500/v1/kv/app/core-api-java/1234/aws/globalDefault/protocol/bob

```

The first is set, and returns a key.  It's empty, but it contains information.  It tells you when the key was created and when it was last modified.  The second was never set and returns nothing.  This is really nothing - no information at all.   

Also,  the `key` stanza treats these two things differently.   `key` will return an empty value for the first example above, but will hang while poling for the second.    (To me this is the more correct behavior)

**Comment by sethvargo** [comment]
Hi @dansteen 

I'm not sure I understand - you are supporting my point. In the first example, the key exists and has a value of null. In the second example, no key exists. 

The reason `key` returns an empty string is not CT, it's a function of Go's templating language. The "null" value for a string is the empty string.

**Comment by dansteen** [comment]
Hi @sethvargo,

Thanks for the response!   You say 

> This is behaving as intended and as-documented:
> `Query Consul for the value at the given key path. If the key does not exist, the default value will be used instead.`
> In this case, the key exists, but has a null value, thus null is being returned.

My issues is that `keyOrDefault` does not return a `null` in the case where the key exists but is set to null - it returns the default value.    I don't think its clear from the documentation that if the key is manually set to null it will be treated as if the key does not exist (by `keyOrDefault`).  

Ultimately,  I don't mind this decision, but I do find the difference in behavior between `key` and `keyOrDefault` to be somewhat confusing.
