### ISSUE TITLE
No way to block rendering of a template waiting for a service

### ISSUE THREAD

**Issue by KJTsanaktsidis** [hashicorp/consul-template#904]
Reading from the KV store with `{{key}}` blocks rendering of the template (and hence executing anything with the `-exec` command) until that key is available. There is `{{keyOrDefault}}` if you want the other behaviour of rendering a default value.

There appears to be no way to get this blocking behaviour with the `{{service}}`. If no instances of the specified service are available, then the template is rendered with an empty array for that service. In many circumstances it would be desirable to not render the template until there actually is a dependant service ready.

### Consul Template version

0.18.1

### Configuration

```liquid
output {
    elasticsearch {
        # The if $i below makes the list comma-separated, but not the last
        # element.
        hosts => [
            {{range $i, $s := service "elasticsearch5"}}
                {{if $i}},{{end}}
                "http://{{$s.Address}}:{{$s.Port}}"
            {{end}}
        ]
    }
}
```

### Command

```shell
/usr/local/bin/consul-template \
    -consul 127.0.0.1:8500 \
    -template="/app/logstash.conf.template:/app/logstash.conf" \
    -exec="${LS_DIR}/bin/logstash -f /app/logstash.conf --path.settings=/etc/logstash"
```

### Expected behavior

There should be a setting whereby the `-exec` command is not executed until the template actually has at least one instance of the service available

### Actual behavior

The template is rendered, the logstash process from my `-exec` command starts, and logstash then crashes because the syntax of the configuration file is invalid without an elasticsearch address in the `hosts =>` section.

### References

I posted this on the mailing lists a couple of days ago ( https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/l9YgeXSMg7o/bEZlVaHXAAAJ ) but got no response, so I assume that the functionality does not exist and so am submitting an enhancement.

**Comment by sethvargo** [comment]
Hi @KJTsanaktsidis 

Thank you for opening an issue. There is no way in Consul's API to issue a blocking query on services to appear. When you query the catalog, you ask for services named "X". If that list is empty, that's the response. There's no way to "block" on that. Instead, your template should use the `else` clause to render a stock configuration or error block until services are available:

```
output {
    elasticsearch {
        # The if $i below makes the list comma-separated, but not the last
        # element.
        hosts => [
            {{range $i, $s := service "elasticsearch5"}}
                {{if $i}},{{end}}
                "http://{{$s.Address}}:{{$s.Port}}"
            {{else}}
                "http://127.0.0.1:80"
            {{end}}
        ]
    }
}
```

**Comment by KJTsanaktsidis** [comment]
RIght - I guess as a workaround I can render some random string and set `-exec` to be a wrapper to check if the elasticsearch hosts are populated in the template.
