### ISSUE TITLE
When service names have forward slash: invalid format error

### ISSUE THREAD

**Issue by cmpex** [hashicorp/consul-template#909]
The template works fine if the service referenced does not have a forward slash in the name.  Experiencing this problem only when forward slash is used in the service name.  Appreciate any help.  From looking at the changelog, forward slash should be supported as of consul-template v0.1.1.

### Consul Template version
consul-template v0.18.1 (9c62737)

### Configuration
```hcl
{
  "log_level": "info",
  "consul": {
    "address": "next-staging.domain.com"
  },
  "template": {
    "source": "/var/www/consul-template/lb.html.ctmpl",
    "destination": "/var/www/next-staging.html"
  }
}
```

```liquid
{{range $tag, $services := service "parent/testservice" | byTag}}
    <h5>{{$tag}}</h5>
    <ul>
    {{range $services}}
        {{.Node}}
    {{end}}
    </ul>
{{ end }}
```

### Command

```shell
/usr/local/bin/consul-template \
    -once \
    -config="/etc/consul-template/once/next-staging"
```

### Debug output

```Consul Template returned errors:
/var/www/consul-template/lb.html.ctmpl: execute: template: :1:9: executing "" at <service "parent/testservice">: error calling service: health.service: invalid format: "parent/testservice"
```

### Expected

So if I switch the service to "differentservice" where the service name does not have forward slash, the template is generated without any errors.

Here is the curl to the catalog/services:
```
# curl -s http://localhost:8500/v1/catalog/services | jq .
{
  "differentservice": [
    "different"
  ],
  "parent/testservice": [
    "forwardslash"
  ]
}
```

curl works fine:
```
# curl -s http://localhost:8500/v1/catalog/service/parent/testservice | jq .
[
  {
    "Node": "testnode.domain.com",
    "Address": "10.1.1.1",
    "TaggedAddresses": {
      "lan": "10.1.1.1",
      "wan": "10.1.1.1"
    },
    "ServiceID": "parent/testservice",
    "ServiceName": "parent/testservice",
    "ServiceTags": [
      "forwardslash"
    ],
    "ServiceAddress": "10.1.1.1",
    "ServicePort": 80,
    "ServiceEnableTagOverride": false,
    "CreateIndex": 6534921,
    "ModifyIndex": 6534926
  }
]
```

### References

Found this issue during my search but not sure how it's related since the template works fine for service names without forward slashes:
- GH-860

**Comment by sethvargo** [comment]
Hi @cmpex 

Thank you for opening an issue, and I'm sorry this is causing an issue. This should be an easy fix, but I'm hesitant to add support for this. While it's technically valid to register a service with a special character like a slash, it is not recommended and will likely be deprecated and removed in future versions of Consul. Using special characters like a slash makes the service unaddressable via the DNS interface and can cause very strange behaviors in client libraries. I would recommend you rename services using a `-` or `_` instead of a slash.

Please let me know if you have any questions.

**Comment by cmpex** [comment]
No worries and thanks for the update.  Went ahead and already switched to using hyphens.  We're mainly using consul via HTTP API so (at the time), it made sense to be able to use forward slashes. However, understand your reasoning.
