### ISSUE TITLE
Node status impacts service status

### ISSUE THREAD

**Issue by jmlacroix** [hashicorp/consul-template#91]
Hi,

I'm using consul-template (with `{{range service "api"}}`) to generate my HAProxy configuration and everything is working fine.

I recently added node health checks. Now, when there is a memory warning on the node, the "api" service from that node gets dropped from the HAProxy configuration.

It looks like - and this is probably by design - when some checks on the node warn or fail, the services on the machine are considered "not passing" too.

In my use case, I don't want a memory warning on the node dropping the services from HAProxy. And I can't use the "any" option because I don't want nodes having critical states to show up in my HAProxy config file.

Is there a workaround for this? I checked to see if I could use conditionals in the templates, but the Status is not exposed (and it's not the service's status that fails anyway).

Example node health:

```
$ curl localhost:8500/v1/health/node/api1

[
    {
        "CheckID": "mem",
        "Name": "mem",
        "Node": "api1",
        "Notes": "",
        "Output": "",
        "ServiceID": "",
        "ServiceName": "",
        "Status": "warning"
    },
    {
        "CheckID": "service:api",
        "Name": "Service 'api' check",
        "Node": "api1",
        "Notes": "",
        "Output": "",
        "ServiceID": "api",
        "ServiceName": "api",
        "Status": "passing"
    }
]
```

**Comment by chrismwendt** [comment]
> Consul is really binary in the "passing vs. failing", and Consul Template follows suit.

Consul returns entries for which checks are "warning" from DNS queries, but Consul Template omits them. Is this an inconsistency?

**Comment by slackpad** [comment]
@chrismwendt this is configurable in Consul via https://www.consul.io/docs/agent/options.html#only_passing but it is a little weird that CT has a different behavior. @sethvargo do you know why CT excludes nodes in the warning state by default?

**Comment by sethvargo** [comment]
@slackpad the reason CT excludes warning was because maintenance mode was formerly a subset of warning

**Comment by grantr** [comment]
Any updates on the inconsistency between DNS service queries and consul-template service queries? This is a significant gotcha when switching between DNS and consul-template.
