### ISSUE TITLE
consul-template 18.0 breaks VAULT_* environment variables

### ISSUE THREAD

**Issue by stvdilln** [hashicorp/consul-template#914]
I have an environment that works in 16 but fails with "x509: certificate signed by unknown authority" in 18.1.   My vault certificates are set with environment variables (VAULT_CLIENT_CERT, VAULT_CACERT, etc) and these are not being read in 18.1.  
I think the error is in config/vault.go:
In DefaultVaultConfig.go

```
// DefaultVaultConfig returns a configuration that is populated with the
// default values.
func DefaultVaultConfig() *VaultConfig {
	v := &VaultConfig{
		Retry:     DefaultRetryConfig(),
		SSL:       DefaultSSLConfig(),
		Transport: DefaultTransportConfig(),
	}

	// Force SSL when communicating with Vault.
	v.SSL.Enabled = Bool(true)

	return v
}
```

Setting v.SSL.Enabled causes v.SLL to no longer be nil.  The environment variables are only picked up if this structure is nil in Function Finalize

```

	if c.SSL == nil {
		c.SSL = DefaultSSLConfig()
		c.SSL.Enabled = Bool(true)
		c.SSL.CaCert = stringFromEnv([]string{api.EnvVaultCACert}, "")
		c.SSL.CaPath = stringFromEnv([]string{api.EnvVaultCAPath}, "")
		c.SSL.Cert = stringFromEnv([]string{api.EnvVaultClientCert}, "")
		c.SSL.Key = stringFromEnv([]string{api.EnvVaultClientKey}, "")
		c.SSL.ServerName = stringFromEnv([]string{api.EnvVaultTLSServerName}, "")
		c.SSL.Verify = antiboolFromEnv([]string{api.EnvVaultInsecure}, true)
	}
```
The attached file has more information including a run with full debug.
[consul-template.txt](https://github.com/hashicorp/consul-template/files/858846/consul-template.txt)

**Comment by stvdilln** [comment]
Thanks for the help and the quick turnaround!

**Comment by sethvargo** [comment]
Sadly dealing with build failures now (unrelated), but I can't merge that until we get a green.
