### ISSUE TITLE
[feature] command_timeout for exec command

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/consul-template#917]
I think it would be useful for the exec command to also have a timeout similar to the template command. As consul-template becomes more of a process manager for the execed process, it could handle terminating batch jobs that take too long to run.

**Comment by sethvargo** [comment]
Hi @sheldonkwok 

This is already supported via the `timeout` option (https://github.com/hashicorp/consul-template/blob/47fe457ecda23624656a4244dbfb42f9c51b82fb/config/exec.go#L55-L62). There are a few APIs that we intentionally do not document such as this one.

**Comment by sheldonkwok** [comment]
Great thanks! Is there a reason why this is intentionally not documented?
