### ISSUE TITLE
Bug when testing executeTemplate?

### ISSUE THREAD

**Issue by cetex** [hashicorp/consul-template#921]
### Consul Template version
```
./consul-template -version
consul-template v0.18.2 (ecb9e46)
```
### Configuration
```
echo '{{ $var := key "test" }}{{ executeTemplate $var}}' > test
```
### Command
```
./consul-template -template "test:test2" -once
```
### Debug output

https://gist.github.com/cetex/5782634af066c9a3cd13ba2f5c770d28

### Expected behavior

What should have happened?
Not sure if this setup is valid, but i'd like consul-template to read the key "test" from consul, then template the data in the key. If i understand executeTemplate correctly this is what it should do?

### Actual behavior

What actually happened?
It crashed and burned after consuming 1GB in heap.

### Steps to reproduce

Check gist.

**Comment by cetex** [comment]
Oh, right. the key "test" doesn't even exist in consul, it makes no difference if it's there, contains a valid template or not.
# consul kv get test
Error! No key exists at: test

**Comment by sethvargo** [comment]
Hi @cetex 

Thank you for opening an issue. You need to define a template before using it:

```
{{ define "custom" }}{{ key "foo" }}{{ end }}
{{ executeTemplate "custom" }}
```

The panic seems like a bug in Go's text/template implementation. To achieve the behavior you want, you'll need two consul-template processes - one that writes the data from the key in consul to disk and one that consumes that file once it is written.
