### ISSUE TITLE
Can cosul-template update the targets dynamically in AWS ALB

### ISSUE THREAD

**Issue by crmadhu20** [hashicorp/consul-template#923]
Please note that the Consul Template issue tracker is reserved
for bug reports and enhancements. For general usage questions,
please use the Consul mailing list:

    https://groups.google.com/forum/#!forum/consul-tool

### Consul Template version

v0.18.2

My Issue is am finding the way to update the consul-template to targets in the AWS ALB target group

Is there a way to achieve this??

**Comment by sethvargo** [comment]
Hi @crmadhu20 

Consul Template only writes to a local file on disk. You may be able to use the Consul API directly for this, or use a load balancer like Fabio in front of the ALB.

**Comment by crmadhu20** [comment]
Could you please let me know how i can use the CONSUl API to do this

Thanks
