### ISSUE TITLE
is there a way to write generic secret via CT

### ISSUE THREAD

**Issue by danielzhanghl** [hashicorp/consul-template#925]
In CT version v0.18.2, I try to use CT to write the generic secret backend(post) to store a secret, 
but it fails with "no secret exists at secret/" error.

It seems CT always expects a return value for vault write operation, but in this case, it returns a empty body, which causes an erro.

```go
if vaultSecret == nil {
	return nil, nil, fmt.Errorf("%s: no secret exists at %s", d, d.path)
}
```

Is there a way to use CT to write a generic secret?

### Steps to reproduce

1.  template file is 
{{ with secret "secret/secret1" "value=123"}}
{{  . }}{{ end }}

**Comment by sethvargo** [comment]
Hi @danielzhanghl 

Thank you for opening an issue. This is behaving as intended. CT is "readonly" in the sense that it reads values from Vault. Some endpoints require additional information via a "write" request, but it returns a credential (like the TLS backend). CT is not (and should not) be used to persist data in Vault.

**Comment by jingene** [comment]
Hi @sethvargo 
I have a question about this issue. Is CT not be used to write data in Vault?
