### ISSUE TITLE
{{node "<NAME>@<DATACENTER>"}} can't render .Address

### ISSUE THREAD

**Issue by yangzhares** [hashicorp/consul-template#926]
### Consul Template version
consul-template version: `0.18.2`
consul version: `0.7.5`

### Configuration
consul-template configuration:
```hcl
consul = "127.0.0.1:8500"
log_level = "debug"

syslog {
  enabled = true
}
```

consul-template template `in.tpl`:
```
{{ with node }}
{{ .Address }}{{ end }}
```

### Command

```shell
consul-template -template "in.tpl:out.txt" -once
```
### Output
```
Consul Template returned errors:
in.tpl: execute: template: :15:3: executing "" at <.Address>: can't evaluate field Address in type *dependency.CatalogNode
```
### Expected behavior
`10.224.243.199`

### Actual behavior
```
Consul Template returned errors:
in.tpl: execute: template: :15:3: executing "" at <.Address>: can't evaluate field Address in type *dependency.CatalogNode
```

But when i change `in.tpl` as follow:
```
{{ with node }}
{{ .Node.Address }}{{ end }}
```
and execute `consul-template -template "in.tpl:out.txt" -once` can get right result that is local address.

could you please help check this issue?

Thanks

**Comment by sethvargo** [comment]
Hi @yangzhares 

Thank you for opening an issue, and sorry this is causing you problems. As the error implies, the catalog node does not have an address field (https://github.com/hashicorp/consul-template/blob/e79894aad0b3789b93d0372e23f6eb0d2b75b35a/dependency/catalog_node.go#L36-L39). I think you want:

```liquid
{{ with node }}
{{ .Node.Address }}{{ end }}
```

as you already discovered.

**Comment by yangzhares** [comment]
hi @sethvargo ,

Thanks your reply, it seems there is an update to be done in README file, please check [https://github.com/hashicorp/consul-template#node](url), that can confuse people.
