### ISSUE TITLE
[question] Does consul-template renew tokens in -once mode?

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/consul-template#935]
### Consul Template version
0.18.2

Does consul-template renew tokens in -once mode? I didn't want consul-template to automatically restart my apps when a secret changed but I did want the postgresql user generated with the postgres backend to be renewed before expiration.

**Comment by sethvargo** [comment]
Hi @sheldonkwok 

What do you mean by "tokens"? There's only one token - the token provided to CT. It is renewed by default unless -renew-token=false or the associated configuration is passed. In once mode, nothing is renewed.

**Comment by sheldonkwok** [comment]
Sorry, I meant to ask if the underlying secrets were renewed. For example I created a user with 
```
{{ secret "postgresql/my-service/creds/readwrite" }}
user: {{ .Data.username }}
...
{{ end }}
```

The docs mention that that secret is kept up to date but my Postgres users are expiring. For my application not using `-once`, the user seems to be renewed.

**Comment by sethvargo** [comment]
@sheldonkwok in once mode, nothing is renewed.

**Comment by sethvargo** [comment]
To put it another way - once mode guarantees that each dependency talks to the server exactly _once_.

**Comment by sheldonkwok** [comment]
Great thanks for the clarification! On a slightly related note, the `exec` `reload_signal` by default is to stop and start the application again. I didn't want our applications to suddenly reboot if a key changes underneath them. Is there a way to not trigger this? I was using `once` for this but I cannot anymore.

**Comment by sethvargo** [comment]
You can fill that in with a dummy signal like USR1. The app doesn't have to respond to it.

**Comment by sheldonkwok** [comment]
I tried a variety of signals like USR1 and USR2 but they have different effects on our services. For example, USR1 will put node into a debug state which we don't necessarily want.

**Comment by sheldonkwok** [comment]
SIGURG might be promising but then we can't use that signal for anything else.

**Comment by sethvargo** [comment]
https://github.com/hashicorp/consul-template/blob/5c11196a787e4dfebbf5a1fae0a9d4ddb8fd1c4e/signals/signals_unix.go#L10-L39

**Comment by sheldonkwok** [comment]
Thanks for providing a lookup! Most of these have the default action of terminating or stopping except SIGCONT and SIGURG. We will probably use one of those two but will have to investigate how all of our services being supported by consul-template handle those signals by default. 

It would be nice if it was configurable to not send a signal.

**Comment by sethvargo** [comment]
I guess it's worth thinking about how `exec` should behave in `once` mode. @slackpad or @armon do you have thoughts?

**Comment by armon** [comment]
@sethvargo I'm not sure... To me the modes are orthogonal. Either it's a long lived parent supervisor _or_ it's being used for one-time generation. You could potentially disallow that configuration, or I guess it could just hang around. The behavior gets very strange in the case of token/lease expiration, so it might be more sensible to disallow.

**Comment by sheldonkwok** [comment]
I can see how `exec` might be confusing if paired with `-once` mode. I only used it because I did not want to send signals or restart my process on template change but still wanted to keep consul-template running for refreshing secret leases. I guess it's possible to just run consul-template in the background without using exec.

**Comment by armon** [comment]
@sheldonkwok That sounds like a good approach, just run it without a reload handler so the app doesn't get restarted.

**Comment by sheldonkwok** [comment]
If it runs without the exec reload handler, it actually stops the application and restarts it again. This behavior started my investigation into reloading because services were restarting without me knowing.

**Comment by armon** [comment]
@sheldonkwok Sorry I wasn't clear, I meant to run it without the `exec` mode at all. The normal mode of consul-template just renders the templates and invokes a reload handler, which can just be a no-op.

**Comment by sheldonkwok** [comment]
Ah, thanks for the clarification! I was hoping consul-template could handle the task management complexity. I would have to write a monitor that waits for the templates to get created and a task manager to maintain both consul-template/my actual service.
