### ISSUE TITLE
[question] Does consul-template global wait and template wait perform the same function?

### ISSUE THREAD

**Issue by wesmiles** [hashicorp/consul-template#936]
consul-template v0.16.0

Within the README.md configuration file format section there are two references to a wait param:

1)

```
# This is the quiescence timers; it defines the minimum and maximum amount of
# time to wait for the cluster to reach a consistent state before rendering a
# template. This is useful to enable in systems that have a lot of flapping,
# because it will reduce the the number of times a template is rendered.
wait {
  min = "5s"
  max = "10s"
}
```

2)
```
  # This is the `minimum(:maximum)` to wait before rendering a new template to
  # disk and triggering a command, separated by a colon (`:`). If the optional
  # maximum value is omitted, it is assumed to be 4x the required minimum value.
  # This is a numeric time with a unit suffix ("5s"). There is no default value.
  # The wait value for a template takes precedence over any globally-configured
  # wait.
  wait {
    min = "2s"
    max = "10s"
  }
```

First one is set at a global level and the second within the context of an individual template.

Do they perform the same function with the only difference being the wait specified in the template would override the global setting?

I am asking because the global setting refers to the time to wait for the cluster whereas the template setting does not.

**Comment by sethvargo** [comment]
Hi @wesmiles 

They perform the same function, but the template one takes precedence (if defined). It's "per template" instead of "per cluster"

**Comment by wesmiles** [comment]
Thanks @sethvargo ....that was a quick response!
