### ISSUE TITLE
Result of 'secret "auth/token/create"' does not include the token.

### ISSUE THREAD

**Issue by phaer** [hashicorp/consul-template#937]
### Consul Template version

originally tested with consul-template v0.18.2 (ecb9e46),
same results with consul-template v0.18.6.dev (a9f9896)

### Configuration

```hcl
consul {
  address = "localhost:8500"
  token = "$MY_TOKEN"
  retry = {
    enabled = true
    attempts = 5
    backoff = "10s"
  }
}

log_level = "trace"
vault {
  address = "https://active.vault.service.consul:8200"
  ssl {
    enabled = true
    verify = true
    cert = "$MY_CERT"
    key = "$MY_KEY"
    ca_cert = ""
  }
}

### Template

template {
  source = "/etc/consul-template/web_config.ctmpl"
  destination = "/etc/web_config"
  command = "chown root:deploy /etc/web_config"
  perms = 0640
}
```

```liquid
{{secret "auth/token/create" "role_name=web" | toJSON }}
```

### Command

```shell
/usr/local/bin/consul-template -config /etc/consul-template/config
```

### Debug output

https://gist.github.com/phaer/30c53b2af9f486802484aa53a84e609c

### Expected behavior

I would expect the rendered template to have a structure similar to the curl response below, and to include the created token.

```shell
curl -XPUT  -H "X-Vault-Token: ${VAULT_TOKEN}" -s 'https://active.vault.service.consul:8200/v1/auth/token/create'
```

```json
{
  "request_id": "adeddf38-e491-1dc5-acee-d681ec32ab91",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": null,
  "wrap_info": null,
  "warnings": null,
  "auth": {
    "client_token": "6843e124-7e9a-8a9b-7af0-681943180dee",
    "accessor": "45406032-7177-06c8-b42d-13501a44132e",
    "policies": [
      "default",
      "web"
    ],
    "metadata": null,
    "lease_duration": 2764800,
    "renewable": true
  }
}
```

### Actual behavior

What actually happened?

The rendered template does not include the token:
```
{"RequestID":"","LeaseID":"","LeaseDuration":300,"Renewable":false,"Data":null}
```

### Steps to reproduce

1. Create a `auth/token`-role called `web`: `vault write auth/token/roles/web allowed_policies='web' explicit_max_ttl=172800`
2. Try to render a new token into a configuration file, using the template above.
3. Wonder if you miss-understood the documentation or if it's a missing feature.

**Comment by phaer** [comment]
Any updates on this? Should the creation of tokens be supported, is it an intended feature? Do I need to provide more info, should I re-test with the latest consul-template?

**Comment by sethvargo** [comment]
This is something I'm working on (I've been working on it for awhile). Auth information is handled very differently in Vault than a traditional token lease.

**Comment by pySilver** [comment]
@sethvargo so it looks like it's still isn't working yet? #1222

**Comment by sethvargo** [comment]
Hi @pySilver. This issue was closed nearly 3 years ago. I no longer work at HashiCorp, but I strongly recommend creating a new issue so someone from the team can triage. Thanks!
