### ISSUE TITLE
[Request] tabwriter support?

### ISSUE THREAD

**Issue by williamdang1710** [hashicorp/consul-template#943]
Is there any plan for supporting tabwriter package in Go?

I want to achieve something like this:
```
 -foo/foo1/foo2                  destination
 -foo/foo3                          destination
 -foooooooooooo             destination
```

**Comment by sethvargo** [comment]
Hi @williamdang1710 

Thank you for opening an issue. This is not something we plan to do at this time. Usually this kind of alignment is important in files that are generated by humans, but machine-generated files are usually under management by another process and it shouldn't matter.
