### ISSUE TITLE
Strategies for vault tokens for long lived consul-template containers that scale up/down

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/consul-template#946]
Hi
Using the latest consul template for some docker containers deployed on a swarm.

When we start our containers (5 of them) we give them a vault token that is renewable with a period of 30m. consul-template uses this token fine and renews it into perpetuity.

The problem is that if we want to scale up the number of containers after 30m (when that initial docker service create command ran using the token initially created). It all fails because that initial token is no longer valid.

Do you guys have any recommended strategies for this kind of scenario?

**Comment by sethvargo** [comment]
Hi @bitsofinfo 

There are generally two practices here:

1. Give swarm the ability to generate tokens and have swarm generate a new token for each container
1. Share the same periodic token with all containers

I'm not sure what you mean by "the initial token is no longer valid" though. Is it expiring?

**Comment by bitsofinfo** [comment]
Thanks Seth - 

What I mean is that we have a process that generates a new orphan token that is renewable and has a 30m period, this is passed to the container as a ENV var that is consumed by consul-template for its `-vault-token` argument. So lets say I start a new `docker service create ....` at 01:00 with an initial service size of 5 containers. This all works great, that token is shared amongst all consult-template based containers, is being renewed ok and all is good.

Lets say however I wait one hour then at 02:00 I do a `docker service myservice scale=10`, the additional 5 new containers it needs to create continually fail because they are still using that original vault token (stored in the ENV var from the original docker service create command issued at 01:00) has expired.

I'm not really sure how to have swarm "generate a new token" for each container for `docker service scale...` as there don't appear to be any hooks to swarms internal mechanism for that.

I guess I could just do a `docker service update --env-add CT_VAULT_TOKEN=[newtoken] myservice` prior to issuing the `scale` to ensure the ENV var for the service has a new token prior to spawning new instances.

**Comment by bitsofinfo** [comment]
also I totally get this is not a consul-template issue per-say but was just curious if anyone had any experience in this scenario or best practice

**Comment by sethvargo** [comment]
Hi @bitsofinfo 

Thank you for your reply. Are you having Consul Template unwrap the token? I'm a bit confused because the tokens are renewed globally, not per-process. So if the other containers are running and renewing the token every so often, future containers which use the same VAULT_TOKEN should work fine.

Are you sure the first 5 containers are still properly communicating with Vault after that time period? If that token expired, it also expired on the other containers too.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to lack of response. If there is still occurring, please open a new issue. Thanks! 😄
