### ISSUE TITLE
Combine services across datacenters

### ISSUE THREAD

**Issue by soansgla** [hashicorp/consul-template#948]
Is there a way to combine services across datacenters and then group byTag? 
I'm using dynamic haproxy to query consul for services in order to generate my acl and backends . This is done by looping through each datacenters. Now when I have duplicate tag across different datacenters I'm getting duplicate acls and backends.
If there is a way to combine all services and then retrieve data group by tags that would resolve this issue.

**Comment by sethvargo** [comment]
Hi @soansgla 

You can use a combination of the `datacenters` component combined with `services` and `scratch` to build that. If you're attempting to build a load balancer based on Consul though, I would recommend taking a look at fabio.

**Comment by soansgla** [comment]
Thanks for the reply @sethvargo . Yeah fabio surely looks good .
As per your response I have looped through DC's and added services in json format in scratch, but I cant get the data grouped byTag . Below is my code

```
{{ range $dc:= datacenters -}}
  {{ if plugin "/bin/dchasleader" $dc | parseBool -}}
    {{ $servicename := (printf "%s@%s" $base_servicename $dc) -}}
    {{ range $service := service $servicename "any"}}

            {{ $service_json := $service | toJSON }}

            {{ scratch.MapSet "jsonservice" $service_json $service_json }}

    {{ end -}}
  {{ end -}}
{{ end -}}


{{ range $i, $serv := scratch.MapValues " jsonservice "  }}

{{ end -}}
```

**Comment by sethvargo** [comment]
Hi @soansgla 

Have you tried grouping `byTag` in the first range first?

**Comment by soansgla** [comment]
hi @sethvargo 

Yes I tried grouping with byTag in the first range but that would still give me duplicate Tags as i'm looping across DC's . What I actually wanted was to group byTag in scratch.MapValues range which would then group as per Tags across my DC's , hence giving me list of servers across DC's for a particular TAG

**Comment by sethvargo** [comment]
Hi @soansgla 

I don't think that's going to be possible. Go's text/template language is a bit limiting, but I would also argue that this type of data aggregation is outside the scope of something that should be done at the template layer.

**Comment by soansgla** [comment]
Ahh ok
@sethvargo let me try to pass the list of services across datacenters to a python plugin and let the python script do the work of combining the services based on tags

**Comment by soansgla** [comment]
@sethvargo I have managed to combine all the services grouped by tag across Datacenters using python. Below is the output that is stored in scratch . Is there a way I can retrieve the key which is the Tag

```

**Comment by sethvargo** [comment]
Are you using Scratch.Set or MapSet?

**Comment by soansgla** [comment]
I'm using scratch MapSet

**Comment by sethvargo** [comment]
Can you share you code sample?

**Comment by soansgla** [comment]
@sethvargo below is the sample code

```
{{ range $dc:= datacenters -}}
  {{ if plugin "/bin/dchasleader" $dc | parseBool -}}
    {{ $servicename := (printf "%s@%s" $base_servicename $dc) -}}
{{ range $services := service $servicename "any"  }}
            {{ $service_json := $services | toJSON }}
            {{ scratch.MapSet "jsonservice" $service_json $service_json }}
    {{ end -}}
  {{ end -}}
{{ end -}}

{{ $var := scratch.MapValues " jsonservice" | toJSON | plugin "groupservicebytag.py" | parseJSON -}} 
/* output for above statement is “[Tag1:[map[Address:172.17.0.4 Port:1080 ID:beta1]] Tag2:[map[Port:1080 ID:twr0322pwn07p Address:172.17.0.4]] Tag3:[map[Port:1080 ID:vwr04cepwn04p Address:172.17.0.4] map[Port:1080 ID:nwr09cepwn01p Address:172.17.0.4] map[Port:1080 ID:fwr39cepwn09p Address:172.17.0.4]] Tag4:[map[Port:1080 ID:bwr09cepwn03p Address:172.17.0.4]]]” */

/* Below statement gets me values buy how do I retrieve the key i.e. Tag1, Tag2, Tag3, Tag4*/
{{ range $k,$var }}
    {{ range $k }}
    backend <Tag>
    server {{.ID}}:{{.Port }} {{.Address}}:{{.Port }}
   {{ end -}}
{{ end -}}
```

``` 
Python code
#!/usr/bin/env python
import json
import sys

def process_input(input_data):
    result  = {}
    for i in input_data:
        if i:
            a = json.loads(i)
            for tag in a.get("Tags"):
                result.setdefault(str(tag), []).append({
                            "ID": str(a.get("ID")),
                            "Address": str(a.get("Address")),
                            "Port": str(a.get("Port"))
                            })
    return json.dumps(result)

if __name__ == "__main__":
    input_data = json.loads(sys.argv[1])
    print process_input(input_data)
```

**Comment by sethvargo** [comment]
Hi @soansgla 

The `range` function can accept two values, so to extract the key and value, do something like

```liquid
{{ range $k, $v := $var }}
{{ end }}
```

**Comment by soansgla** [comment]
ahh yeah thanks @sethvargo works like a charm!
