### ISSUE TITLE
Allow Vault secrets to be replaced prior to TTL expiration

### ISSUE THREAD

**Issue by CpuID** [hashicorp/consul-template#949]
Currently, `consul-template` supports automatic renewal of leases, up to the max_ttl value allowed by the resource. When the max TTL is reached, a renewal is attempted but Vault will error with:

`lease not found or lease is not renewable`

At this point, consul-template proceeds to execute a new `vault read path` (the API equivalent), and things converge within a short duration. The main issue is this is prone to downtime as Vault may have revoked upstream credentials for a resource (eg. the database secret backend), and the app will have no DB access while a new set of credentials are propagated.

The current state of a lease can be accessed using [/sys/leases/lookup](https://www.vaultproject.io/api/system/leases.html#read-lease) against the Vault API, which includes the current TTL of the lease. What I can't tell right now is if Vault exposes the timestamp when the lease will no longer be renewed (based on the max_ttl). You can get it if you do a read on the a specific resource (eg. for `/database/creds/somerole`, if you `vault read /database/roles/somerole` it has the max_ttl but thats a backend specific path, and configuring that type of logic in CT would be a PITA)

Ideally what I am looking for is something like what [Armon suggested here](https://groups.google.com/forum/#!topic/vault-tool/hx2OUZ4P_Y4) with overlapping leases, to mitigate downtime when one lease expires. Ideally retaining one current lease, and if identifiable when that lease is close to max_ttl, request a fresh one to changeover gracefully before max_ttl is reached, then hand back the other one or something.

Thoughts?

**Comment by sethvargo** [comment]
Hi @CpuID 

The only data we get back from Vault is [from the `secret` struct](https://github.com/hashicorp/vault/blob/0747d2d06911bf75c35d46344899261b1a63a656/api/secret.go#L11-L36). 

I think we could add a configurable grace period in which Consul Template will read a new secret _before_ it expires.

**Comment by sethvargo** [comment]
Here's the raw API response:

```json
{
  "request_id": "b0714580-80e1-c970-c9e9-0d645cabbb8a",
  "lease_id": "sys/leases/renew/e4af37a3-29f7-7a0b-582c-6974e0a82328",
  "renewable": true,
  "lease_duration": 15,
  "data": null,
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

**Comment by sethvargo** [comment]
Ah okay. The `lease_duration` is a bit overloaded in the API response. As we get closer and closer to the `max_ttl`, the lease duration takes that into account and returns the correct value.

**Comment by CpuID** [comment]
Super awesome @sethvargo thx :)
