### ISSUE TITLE
Extend exec mode for consul service autoregistration

### ISSUE THREAD

**Issue by reddec** [hashicorp/consul-template#952]
Good day!

I'm very sorry, if this was already reviewed, but maybe will be a good idea to register running `consul-template` in `exec` mode as service in consul.

I mean, I would like to suggest to extend supervisor mode and add flags/options to define service name (like `-service-name`) and tags. If this options are defined, then consul-template will register running application as service.

Main benefit of this idea is wrap and run any application in containers with automatic registeration in distributed environment. 

Sample:

```shell
consul-template -exec 'haproxy' -service-name 'balancer' -tag 'http' -tag 'input'
```

**Comment by sethvargo** [comment]
Good idea - I'll cross with https://github.com/hashicorp/consul-template/issues/570 and track it there!
