### ISSUE TITLE
[Question] Recursive includes

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/consul-template#959]
I just tested on version `consul-template v0.18.1 (9c62737)`  to see if recursive includes will work. 

To give an example, this is what I run `consul-template -once -template "a.hcl:final.hcl"`

`a.hcl`
```
content from a
{{ file "b.hcl" }}
```

`b.hcl`
```
content from b
{{ file "c.hcl" }}
```

`c.hcl`
```
content from c
```

The tests results in `final.hcl` as 
```
content from a
content from b
{{ file "c.hcl" }}
```

Which indicates that the file including is just at one level. How difficult is to make this happen recursively? (we use a shell script now)

cc: @sethvargo

**Comment by sethvargo** [comment]
Hi @vrenjith 

As mentioned [in the `file` documentation](https://github.com/hashicorp/consul-template#file):

> This does not process nested templates. See [`executeTemplate`](https://github.com/hashicorp/consul-template#executetemplate) for a way to render nested templates.

In general though, this type of evaluation is very limited in Golang's templating language.
