### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by martinssipenko** [hashicorp/consul-template#960]
Hi,

I noticed that there is a consul-template Docker image available at https://hub.docker.com/r/hashicorp/consul-template/, and as far as I can tell, the image is built using `scratch` as base.

Are there any plans on supporting an official dockerized consul-template image, similar as with Consul or Vault? I'd be happy to contribute if you think such options is viable. I'm aware that It's simple enough to maintain your own image, but I'd rather not if there would be an official image.

Reason I'm asking this because when I'm trying to use the `hashicorp/consul-template` I'm getting x509 certificate errors, because `scratch` base does not ship with ca-certificates.

**Comment by sethvargo** [comment]
Hi @martinssipenko 

Thank you for opening an issue. I have had a request to Docker open for about 2 months now with no response. 

<img width="313" alt="screen shot 2017-06-14 at 6 08 37 am" src="https://user-images.githubusercontent.com/408570/27127130-c9f940fa-50c7-11e7-980f-672337606d30.png">

I could start publishing something with an alpine base as well and use different tags (like `:full` and `:light`). Would that help?

**Comment by sethvargo** [comment]
Also, the [build is in the docker folder](https://github.com/hashicorp/consul-template/tree/master/docker).

**Comment by sethvargo** [comment]
We could also just download and bundle ca certs into scratch at a path go looks (https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/)

**Comment by martinssipenko** [comment]
Thanks for quick response.

Having an `alpine` image would definitely help. I noticed Terraform and Packer has something similar as you mentioned - https://github.com/hashicorp/docker-hub-images.

Also, I wonder if CTs image should influence from Consul and Vault images, more specifically - those two have `docker-entrypoint.sh` file. I understand that Vault and Consul compared to CT are services that are exposed via ports, but CT could also be a long running process.

**Comment by martinssipenko** [comment]
Here is the gist - https://gist.github.com/martinssipenko/963341d7ec380352247fab3428425f2c

**Comment by sethvargo** [comment]
I'm not a big fan of the entrypoint.sh script, although I see where it's useful. I don't think it would be required for Consul Template. I'd like to take a stab (or if you want to) of just bundling CAs in scratch to keep the image small.

**Comment by martinssipenko** [comment]
Alright, do you want me to open a Pull Request?

**Comment by sethvargo** [comment]
@martinssipenko If you have time - I'm about to jump on a plane. I think the best approach is to have `:light` which is from scratch and then `:full` which is from alpine. But the light one still needs CA certs

**Comment by martinssipenko** [comment]
Ok, I'll try to put something together..

**Comment by martinssipenko** [comment]
I've sent a PR #961, but I think it would be better to have an alpine image. I see your point on image size, but the difference is very small, current 3Mb compared to alpine 6Mb.

Also using Alpine it would be possible to use `apk` to add ca-certificates, instead of just grabbing them from Curl project.

**Comment by sethvargo** [comment]
Hi @martinssipenko 

Thank you for the PR - I just merged it. I don't disagree, but I'd want to give users the option of a light vs full image I think.

**Comment by martinssipenko** [comment]
Ok, I'm happy to contribute, I actually almost started working on it, but then I realised I don't know the process of how you release your images (is it even automated?). I image having two Dockerfiles would be enough - `Dockerfile-light` and `Dockerfile-full`. Do you think the full version should use the entrypoint approach I proposed earlier?

Perhaps the Dockerfile should be moved to a different project, similar as with Terraform?

**Comment by sethvargo** [comment]
I think the convention is `light.Dockerfile` and `full.Dockerfile`. I'm thinking we possibly publish three:

1. scratch (scratch with CA)
1. light (alpline with updated apk certs)
1. full (ubuntu or debian)

Thoughts? I think the naming scheme is then `hashicorp/consul-template:x.y.z-full`

**Comment by martinssipenko** [comment]
1. and 2. make sense to me.

Not sure about 3., some projects include a source code in full version and do a compile during buid, not sure why tho. Also I can't see why someone would want a 300mb debian vs 6mb alpine.

Now that I'm thinking, perhaps it would be better to have following versions (influenced from other project images - [nginx](https://hub.docker.com/_/nginx/), [golang](https://hub.docker.com/r/_/golang/)):
- `0.18`, `0.18.5`, `latest`
- `0.18.5-alpine`, `0.18-alpine`, `alpine`
- `0.18.5-scratch`, `0.18-scratch`, `scratch`

Now the question is, which version should be one tagged with `latest`, I assume it could be the `scratch`?

Regarding Dockerfile convention - looks that others always use `Dockerfile` and organize different version in sub-directories.
https://github.com/nginxinc/docker-nginx/tree/c769ad8ab21dfb374fa33d8fb9d0822d0fa8d2e5/mainline
https://github.com/docker-library/golang/tree/97b2ff201ec59b9a037197d132c64eb937370c64/1.8

**Comment by sethvargo** [comment]
I think it would have to be scratch, for backwards-compat reasons. 

One of the advantages of also having an `ubuntu` build is the arbitrary "command" folks like to run. A _lot_ of people use Consul Template to wrap things like haproxy and nginx, so having a way for them to wrap that easily and use any bashisms or shellisms they want would be useful (I think).

**Comment by martinssipenko** [comment]
Makes sense, what about moving Docker Image to diff project? Do you think that would make sense?

**Comment by sethvargo** [comment]
I don't think it's worth moving to another project until it becomes an issue to maintain it with this one. I like having the git tag also reflect the dockerfile which built the tool.

**Comment by martinssipenko** [comment]
Another issue I came across - while building alpine image, the binary can be pulled from [official releases page](https://releases.hashicorp.com), so that it can be GPG verified before it gets baked into Docker image. However; in case of scratch, the binary is simply copied from local (previously built locally using `make`). How do you suggest solving this issue? Since, if follow other projects, where binary is downloaded from releases, it first has to be released prior docker image can be built..

**Comment by sethvargo** [comment]
Since the binary is already build during a release, I don't see why we'd need to upload it to releases, then download it locally. Additionally, since we built it locally, checksumming isn't quite as important (especially since the build process is the thing that generates the checksums in the first place).

More importantly, I think pulling from releases limits users' ability to build their own fork easily. If we pull from releases, they have to patch the dockerfile. If we add from the existing build, they can have their own code but use our dockerfile.

**Comment by martinssipenko** [comment]
I've creater a PR #963, let me know what you think about it..
