### ISSUE TITLE
Possible regression when using PKI backend with Vault >= 0.7.0

### ISSUE THREAD

**Issue by moritzheiber** [hashicorp/consul-template#966]
We have recently encountered a very unusual bug when using Vault >= 0.7.0 and consul-template, whereas consul-template tries to renew any certificate _without a lease_ after exactly 2 minutes and 30 seconds.

It's so unusual that I don't even know whether this is a bug in consul-template or Vault, but this seemed like the most obvious place to start. I've also [set up a dedicated regression kit to accurately reproduce the issue while stepping through different versions of Vault](https://github.com/moritzheiber/vault-regression-test). You'll find more details in the referenced repository's README.

The expected thing, for me at least, would be that consul-template would not renew a still valid certificate after 2m30s but rather obey the certificate's lifetime. However, without a lease this might prove to be difficult.

Let me know if you need any other information.

**Comment by moritzheiber** [comment]
Adding @pellepelster

**Comment by sethvargo** [comment]
Hi @moritzheiber 

Thank you for opening an issue. To confirm, are you saying this _used_ to work with older versions of Vault, but stopped working after 0.7? Is the CT version controlled in this scenario?

/cc @jefferai

**Comment by moritzheiber** [comment]
Yup, that's what I'm saying.

You can easily verify my claim by passing "VERSION=0.6.5" to the run script (as described in the README). 0.6.5 was the last minor version before the PKI backend behavior changed from generating a lease for every certificate to not generating a lease anymore.

With 0.6.5 the certificate will not be renewed after 2 minutes and 30 seconds, while with anything after 0.6.5 (hence >= 0.7.0) it will.

consul-template version is fixed to 0.18.5 in this test setup. I have not tried HEAD.

**Comment by sethvargo** [comment]
Okay. That definitely seems like something changed in the Vault response then /cc @jefferai 

FWIW, I'm coicidentially re-doing CTs renewal system, but I don't think that's the root cause here.

**Comment by sethvargo** [comment]
Hi @moritzheiber 

Since nothing changed in CT land, I would recommend opening an issue against Vault. Thanks! 😄

**Comment by clstokes** [comment]
@moritzheiber I just ran into this as well. Vault's behavior indeed changed in 0.7.0 to _not_ issue a lease for issued certificates. You can re-enable this per-role with the [generate_lease](https://www.vaultproject.io/api/secret/pki/index.html#generate_lease) parameter like this:

```
vault write pki/roles/consul-service \
    generate_lease=true \
    allowed_domains="service.consul" \
    allow_subdomains="true"
```

The change is listed in the [v0.7.0 changelog](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#070-march-21th-2017) under _DEPRECATIONS/CHANGES_.
