### ISSUE TITLE
Rendering templates to a buffer

### ISSUE THREAD

**Issue by vtorhonen** [hashicorp/consul-template#974]
I have an enhancement request. Currently the `manager` package exposes rendering output as follows:

- By default the output is written to a file.
- If dry run is enabled the output is written to `outStream` of the runner struct. Code comments state that the out/err streams can be modified through `SetOutStream` and `SetErrStream` functions, but as far as I can tell these functions are missing. In addition, render output is written to stdout among other things, so even if these streams could be modified the output would have to be parsed somehow, which is obviously not ideal.

Related code references here:

https://github.com/hashicorp/consul-template/blob/master/manager/runner.go#L44-L50
https://github.com/hashicorp/consul-template/blob/master/manager/runner.go#L609-L616
https://github.com/hashicorp/consul-template/blob/master/manager/renderer.go#L43-L44

It would be super useful if Consul templates could be exposed from the Runner struct. Maybe a map, which could be indexed by the template ID. This would allow the use of `manager` package in other Go projects without the need to write all that boilerplate found in `manager/runner.go`.

What do you think?

**Comment by sethvargo** [comment]
Hi @vtorhonen 

Thank you for opening an issue. This is a really interesting idea, and I'd like to do what I can to support this workflow. One of the main challenges is that the renderer does an atomic write, so it has a pretty hard requirement that the writer it receives is a file, not just any iowriter.

The templates are already exposed (kinda). The `RenderEvents()` function on the runner returns a map of template IDs (which is just the md5 of the input contents) to their `RenderEvent`. Right now, the render event just returns some metadata, but it could also return the rendered template data. Would that help? You'd still have to map input template contents to their md5 to index the map and get the contents. You'd also need to listen on `TemplateRenderedCh()` to receive updates when templates are rendered/changed.

The `SetOutStream` and `SetErrStream` comments are outdated. Sorry about that.

**Comment by sethvargo** [comment]
https://github.com/hashicorp/consul-template/pull/975 as an example

**Comment by vtorhonen** [comment]
Thanks @sethvargo, that would work just fine!

**Comment by sethvargo** [comment]
Cool - merged and will be in the next release!

**Comment by vtorhonen** [comment]
Thanks again! Just had the next improvement on my mind about this. Not opening a new issue since it's pretty tightly related to this change, if that's okay.

Currently `Render()` returns a `RenderResult`, which includes the render output in `Contents` variable. The result is stored in `runner.go` to `result` variable.

https://github.com/hashicorp/consul-template/blob/master/manager/runner.go#L608-L615

Then some of the members of `RenderResult` are copied into `RenderEvent`, but `Contents` is not one of them. Would it be possible to copy `Contents` to `RenderEvent` as well, or possibly just store a pointer to `RenderResult` in `RenderEvent`?

If this is done then the whole `manager` package could be used in another project by something like this:

```go
import (
        "fmt"
        cconfig "github.com/hashicorp/consul-template/config"
        cmanager "github.com/hashicorp/consul-template/manager"
)

func main() {
        input := "{{ key \"foo\" }} "
	cfg := &cconfig.Config{
		Templates: &cconfig.TemplateConfigs{
			&cconfig.TemplateConfig{
				Contents:    cconfig.String(input),
			},
		},
	}
	r, err := cmanager.NewRunner(cfg, true, true)
	if err != nil {
		return "", err
	}

	go r.Start()

	select {
	case <-r.DoneCh:
		for i, k := range r.RenderEvents() {
                        // assuming "Contents" is available in RenderEvent struct
		        fmt.Printf("Render output: %s\n", k.Contents)
	        }
	case err, _ := <-r.ErrCh:
		// error handling
	}
}
```

**Comment by vtorhonen** [comment]
@sethvargo can you re-open this issue?
