### ISSUE TITLE
error calling service: invalid health service dependency format

### ISSUE THREAD

**Issue by mnuic** [hashicorp/consul-template#979]
### Consul Template version

consul-template -v
consul-template v0.15.0

### Configuration

```hcl
{{range services}}
backend consul_{{ .Name}}
    {{range service .Name "passing, warning"}}
    server {{.Node}} {{.Address}}:{{.Port}}
    {{end}}
{{end}}
```

### Command

```shell
/bin/consul-template -log-level="debug" -consul X.Y.Z.A:8500 -template "haproxy.cfg:haproxy.config" -once
```

### Debug output

```
Consul Template returned errors:
template: template: haproxy.cfg:228:12: executing "haproxy.cfg" at <service .Name "passi...>: error calling service: invalid health service dependency format
```

### Expected behavior

It shoud render haproxy conf something like this:
```
backend consul_SERVICE_A
    server node1 1.1.1.1:80

backend consul_SERVICE_B
    server node1 1.1.1.2:81

etc
```

### Actual behavior

got error

I looked all issues, and there are a lot examples but nothing works for me, and can not figure out what am I missing.

**Comment by sethvargo** [comment]
Hi @mnuic 

There are a few things here. First, you're using a really old version of Consul Template. The latest version is 0.19, so I would suggest trying an upgrade to see if that resolves the issue.

Second, Consul Template does not support service names which have a "dot" (period) in them. While Consul permits this, it's highly discouraged. Be sure to check that your service names do not include dots.

**Comment by mnuic** [comment]
Hi,

Thanks for reply. I figure it out, the problem was that one of services registered in Consul had a space before the name. It was not clear from the gui, but when I curl the service catalog saw something like:
   " service_name": []

It would be nice if consul-template could trim spaces before and after the service name so that this doesn't affect it. Or maybe some logging error so that this could be easy seen. It's the same on the latest version.

You can close the issues and maybe for some future release implement some logging or automatic trim for spaces in service names.

**Comment by sethvargo** [comment]
Hey @mnuic 

I actually think Consul itself should disallow that. I'll open an upstream issue.
