### ISSUE TITLE
Add a fail fast option to avoid blocking

### ISSUE THREAD

**Issue by jstoja** [hashicorp/consul-template#980]
Hello guys,

Is there room for a flag/behaviour where consul-template would have a fail fast flag?

Right now I'm using it to template configration files with consul/vault with the `-once` flag  and when a key is missing, consul-template blocks as expected, and only prints the retrieved/missing keys with the debug log-level. I would find useful to have it failing with an explicit output with the missing keys.

Would that be something that could be in consul-template?

Thank you,
Julien

**Comment by sethvargo** [comment]
Hi there,

You can use key_or_missing to prevent blocking, but that won't fail the process. Doing so is against Consul Templates design. Thanks!
