### ISSUE TITLE
Vault token renewal failure behavior

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/consul-template#981]
Consul-template does not natively support aws-ec2 auth (particularly the IAM component) with Vault. This is fine, but it means at some point consul-template might end up with a unusable vault access token.  As a daemon this makes it difficult to recover from the scenario.

I suggest that perhaps it should have a configuration to execute an external command that will return a vault access token, and it could be called on initial invocation and if the token renewal fails.  

Alternatively, it could just exit if it finds that its token is no longer valid, relying on an external system to restart it with an appropriate token.

**Comment by sethvargo** [comment]
Hi @jhmartin 

Thank you for opening an issue. Retrieving a token from Vault is a bit outside the scope of Consul Template's job (there's another issue discussing this). What we recommend is either:

1. Provide a periodic token to CT (one that does not expire, but still terminates if not renewed at a regular interval): https://www.vaultproject.io/docs/concepts/tokens.html#periodic-tokens

2. Let Consul Template die and have a parent process retrieve and inject a new token. When the Vault token dies, the renewal will fail, which will cause CT to either retry or exit immediately, depending on your retry configuration.

Please let me know if you have any questions.

**Comment by jhmartin** [comment]
Ahh, #2 was the bit I was looking for. I don't see how to configure exit-on-retry-exhaustion, what would the configuration for that look like?

**Comment by sethvargo** [comment]
If you set vault retry to 0 or really small, it will fail sooner. Otherwise, it'll retry those failures.
