### ISSUE TITLE
Complete documentation of command line flags

### ISSUE THREAD

**Issue by brianshumate** [hashicorp/consul-template#983]
👋 Howdy!

Users report a little bit of uncertainty about the mapping of CLI flags to their equivalent configuration file options and vice versa.

While documentation does currently mention the mapping of options to flags:

> "The CLI interface supports all options in the configuration file and visa-versa. Here are a few examples of common integrations on the command line."

I think it could be useful to update the documentation with full details on all CLI flags so that folks can have a handy reference for using their preferred style of configuration.

### Consul Template version

consul-template v0.19.0 (33b34b3)

### Configuration

N/A

### Command

N/A

### Debug output

N/A

### Expected behavior

Complete documentation on the mapping between configuration file options and command line flags, i.e.  `ca_cert` / `-consul-ssl-ca-cert` or  `ca_path` /  `-consul-ssl-ca-path`  and so on.

### Actual behavior

I had to look at the source to discover the names of particular command line flags to help the user.

### Steps to reproduce

N/A

### References

None

**Comment by sethvargo** [comment]
Hey @brianshumate 

Thank you for opening an issue. As the surface area of Consul Template grows, documenting these options in the README is troublesome for a few reasons.

1. It's very easy to make a mistake. With over 85 configuration options now, it doesn't make sense to populate the README with every possible configurable. 

2. It's often out-of-date or does not correspond to the version installed. Often times, users are running a stale or outdated version of Consul Template. If they come here looking for flags and CLI options, undoubtably they open an issue saying things are broken; in fact they are just running an old version without the newer CLI flags. That's one of the biggest reasons I removed them in the first place.

3. `-h` is 100% correct for the version running locally. Even if the user is on v0.1.0, `-h` shows the exact flags that that version responds to. Each flag provides a short description of it's behavior as well.

4. The mapping from config - CLI is not 1:1, but it's pretty close. Each stanza is concatenated together with any substanzas, then any underscores are converted to dashes. So:

```hcl
vault {
  ssl {
    ca_cert = "foo"
  }
}
```

Becomes:

```
-vault-ssl-ca-cert
```

But there are also edge cases for BC reasons:

```hcl
consul {
  auth {
    username = "foo"
    password = "bar"
  }
}
```

becomes 

```
-consul-auth foo:bar
```

This is why consulting the local help for the locally installed version is the best approach.
