### ISSUE TITLE
Support signal SIGWINCH on unix

### ISSUE THREAD

**Issue by eric-johnson** [hashicorp/consul-template#989]
I'd like to run Apache 2.2 under consul-template.
Apache 2.2 [will gracefully stop](http://httpd.apache.org/docs/2.2/stopping.html#gracefulstop) when it receives `SIGWINCH`.
Consul-template does not include `SIGWINCH` in its list of signals for unix.
I've made a fork that adds `SIGWINCH` and am successfully using it to run apache as a direct child process of consul-template.

I'm trying to run the tests (not a go developer, don't have any of the dependencies). I'll submit a PR if/when I figure it out.
https://github.com/eric-johnson/consul-template/tree/allow-sigwinch

**Comment by sethvargo** [comment]
Hi @eric-johnson 

You should just be able to add `SIGWINCH` to the list of signals (alphabetized) and submit the PR. The tests will run when you open the PR>

**Comment by eric-johnson** [comment]
Great. Thanks for the super-quick response.
