### ISSUE TITLE
child spawns before templates render

### ISSUE THREAD

**Issue by eric-johnson** [hashicorp/consul-template#991]
### Consul Template version

Version: 7bb9418
Works correctly in 0.19.0 (33b34b3)
I also reproduced this in the previous commit, 252f61d, out of paranoia that my SIGWINCH change from the other day caused it.

### Configuration

```hcl
kill_signal = "SIGTERM"
max_stale = "15s"

template {
  contents = "{{ keyOrDefault \"envrionment-name\" \"dev\" }}"
  destination = "/tmp/consul-template/file1"
}

template {
  contents = "{{ keyOrDefault \"envrionment-name\" \"dev\" }}"
  destination = "/tmp/consul-template/file2"
}

exec {
  command = "/bin/bash -c \"ls --full-time /tmp/consul-template/; sleep 1; ls --full-time /tmp/consul-template/\""
  splay = "15s"
  reload_signal = "SIGUSR1"
}
```

### Command

```shell
rm -r /tmp/consul-template/
/consul-template_252f61d -log-level trace -consul-addr=consul:8500 -config "/ct-bug.hcl"
```

### Debug output

https://gist.github.com/eric-johnson/bf695c3f0914a0419b631b4e0f214fc8

### Expected behavior

It should not spawn a process until the templates have rendered.

### Actual behavior

It spawned a process before the templates rendered.

### Steps to reproduce

1. Configure a template. The longer it takes to run, the more likely you are to see the bug.
2. Configure an executable that immediately opens the file you're templating.
3. Run consul-template with your config.
4. Watch your executable fail.

**Comment by sethvargo** [comment]
@dadgar FYI
