### ISSUE TITLE
AWS/GCE Tag watcher feature

### ISSUE THREAD

**Issue by alex-leonhardt** [hashicorp/consul-template#992]
Hi All,

I hope the below largely makes sense, but please do let me know if you have questions .. ?

### **Feature**
 
I was wondering if it was possible to, just like consul-template has a `file` watcher, to add watchers for `aws instance tags` and similar the equivalent for `gce` ?

### **Background**

It would be helpful in re-configuring consul agent should tags throughout the lifetime of an instance change, this could help, for example, with canary deployments where a deployment is a release of a new ASG (new tags, new app version, etc.) ... think "immutable" app ... but system services (like consul agent) may need update itself based on tags from AWS/GCE to "move" a tested instance/application from "canary" to "in production".

All other services, discovering the/a service can simply keep asking for `service-X with tag "in-produciton"` whereas test-traffic can be sent to `service-X with tag "canary"`.

Thanks,
Alex

**Comment by sethvargo** [comment]
Hi @alex-leonhardt 

Thank you for opening an issue. This is largely outside the scope of Consul Template, so we will not be adding this functionality. Sorry!
