### ISSUE TITLE
Latest Download

### ISSUE THREAD

**Issue by port22** [hashicorp/consul-template#993]
Please consider providing a sticky "latest" symlink for download at https://releases.hashicorp.com/consul-template/

for automatic downloads f.e. in Dockerfiles, so that we can avoid those messy grep/cut pipes.
Those were the days when this was common practise...

Thanks!

**Comment by sethvargo** [comment]
Hi @port22 

I've explained our thoughts on [this Terraform thread](https://github.com/hashicorp/terraform/issues/9803#issuecomment-257903082), but the same applies for Consul Template:

1. Best practices dictate that you should never just install HEAD of a tool
1. Always lock to a known version
1. Upgrade when ready and test the upgrade
1. Lock to the new version

We also publish an official docker image which is tagged `:latest` and has tags for each version.
