### ISSUE TITLE
consul-template renders kv pairs template at wait-min quiescence timer even without a change

### ISSUE THREAD

**Issue by marcelki** [hashicorp/consul-template#994]
### Consul Template version

consul-template v0.19.0 (33b34b3)

### Configuration

```hcl
consul {
  address = "127.0.0.1:8500"
}

reload_signal = "SIGHUP"
kill_signal = "SIGINT"
max_stale = "10s"
log_level = "warn"

# It is also possible to configure templates via the CLI directly.
template {
  source = "/home/cionix/consul-tool-issue.tmpl"

  wait {
    min = "2s"
    max = "8s"
  }
}

template {
  source = "/home/cionix/consul-tool-issue-1.tmpl"

  wait {
    min = "2s"
    max = "8s"
  }
}
```

```liquid
{{ range tree "folder/" }}
foo {{ .Value }}
{{ end }}
```

```liquid
{{ range tree "folder1/" }}
foo1 {{ .Value }}{{ end }
```

### Command

```shell
consul-template -config "/etc/consul-template/conf/config.hcl" -dry
```

### Debug output

https://gist.github.com/marcelki/88fe3cc38574de8871350cdcc2b2ff98

### Expected behavior

Render templates and update when changes occur.

### Actual behavior

Consul-template renders and updates the templates at the configured min wait quiescence timer even when no change at the key value pairs occured.
When removing the wait quiescence timer, the template only gets updated on a actual change, as intended. This behavior doesn't seem to occur when using a single template in the configuration file.

### Steps to reproduce

1. Create key value pair on consul kv storage ( folder/test -> Content: bar)
2. Create key value pair on consul kv storage ( folder1/test -> Content: bar1)
3. Configure templates as above, place configuration file and run consul-template

**Comment by sethvargo** [comment]
Hi @marcelki 

Thank you for opening an issue. This is actually behaving as expected. When the timers tick, we check if the template has been updated, then we compare the update with the updates that have occured on disk. In your debug output, you're running in "dry" mode, so there is no comparison available, so the template is rendered each time. If you run without dry mode, you'll see the quiescence tick, the template will render in-memory, but then the result will not be written to disk (since it is unchanged).

**Comment by marcelki** [comment]
Hello,

but why does the "dry" mode works as intended when using a single template file?

I run into the same problem without using the "dry" mode. So this might not be the solution to my problem. 
Should I update/comment on this issue with the other use-case or create a new issue?

**Comment by marcelki** [comment]
So I build new templates to demonstrate my behviour. 
It used "timestamp" so it might be linked to [#873](https://github.com/hashicorp/consul-template/issues/873)

What's kinda weird is that:
1. It acts normally when you run "timestamp" with a single template
2. When both templates use "timestamp"

My _config.hcl_ and the key:value pairs on the consul kv store stayed the same. Only the templates changed and I did not run _consul-template_ in "dry" mode!

/home/cionix/consul-tool-issue.tmpl
`{{ timestamp "unix" }}`

/home/cionix/consul-tool-issue-1.tmpl
`{{ key "folder/test" }}
`
