### ISSUE TITLE
toYAML escapes booleans and ints/floats with double quotes.

### ISSUE THREAD

**Issue by eliasbrange** [hashicorp/consul-template#997]
The function `toYAML` escapes integers, floats and booleans (True, true, TRUE, False, false, FALSE) with double quotes. This is not in line with the documentation.

I used the following key value structure while testing.

- config/
  - admin/
    - port: 1234
  - maxconns: 5
  - minconns: 2

`toJSON` and `toJSONPretty` seems to have the same behaviour.

### Consul Template version

Tested with:
consul-template v0.18.5 (9902dd5)
consul-template v0.19.1.dev (4fbd9b3)

### Configuration

```liquid
{{ tree "config" | explode | toYAML }}
```

### Command

```shell
consul-template -dry -once -template "test.tpl"
```

### Expected behavior

I expected the output to be like documented in README.md, e.g:

```yaml
admin:
  port: 1234
maxconns: 5
minconns: 2
```

### Actual behavior

The integers are escaped with double quotes, e.g:

```yaml
admin:
  port: "1234"
maxconns: "5"
minconns: "2"
```

### Steps to reproduce

1. Replicate the KV structure.
2. Use template from readme: {{ tree "config" | explode | toYAML }}
3. Run consul-template.

**Comment by sethvargo** [comment]
Hi @eliasbrange 

As you can see in [this code](https://github.com/hashicorp/consul-template/blob/4fbd9b3a8175608c9efa2af1bee85625f01a6cd9/template/funcs.go#L912), we just call yaml.Marshal. The data that comes back from Consul's KV store is always a string.

**Comment by eliasbrange** [comment]
Hi @sethvargo. Yeah I saw that when skimming through the code.

You should probably update the documentation as it makes you believe that integers are actually returned as integers, even though consul represents them as strings.

**Comment by eliasbrange** [comment]
We actually hacked our way past it with this beautiful being:

```{{ tree "config" | explode | toYAML | toJSON | replaceAll "\\\"" "" | parseJSON }}```

which produces the YAML we need.
